### ISSUE TITLE
get address from another derivePath from address

### ISSUE THREAD

**Issue by askz** [bitcoinjs/bitcoinjs-lib#1003]
Hi, I don't know if its possible but its woth an example for explaining my case: 
Say I generate two addresses from a node: 
BTC: 17Dqa7g5jJXgESUThGjvyoBjXv7dCHDQDG (m/44'/0'/0')
KMD: RQJULiXSdyfbPaNPdWN1ezsghGeUv4GHQg (m/44'/141'/0')

Can I, with only knowing the BTC address, retrieve the kmd one?
I know this possible if I have the pubkey but.... don't know if possible in that manner

Thanks in advance, and thanks again for this awesome library! keep up the good work

**Comment by dabura667** [comment]
No it is not possible.

**Comment by askz** [comment]
And is it possible to retrieve xpub from address?

**Comment by dabura667** [comment]
No it is not.

**Comment by askz** [comment]
So I am completely fucked?

**Comment by askz** [comment]
My use case is to exchange fund via a script that scan incoming (BTC) transactions and send equivalent (KMD) transactions. My best guess is to send data with the transaction, encoded address....

**Comment by dabura667** [comment]
1. you need the xpub of `m/44'/0'/0'` for receiving bitcoin.
2. you need the private data (seed, key, whatever) for sending KMD.

Just generate the xpub for `m/44'/0'/0'` from your bitcoin private seed, then upload the xpub to the server, and derive `0/x` where x is the next user. (count up one for each request) and generate the addresses.

Then use the private data to send KMD once you notice money received on the bitcoin address associated with the order.

**Comment by dcousens** [comment]
> My best guess is to send data with the transaction, encoded address....

This is typically a very expensive and unscalable approach too.  You are better suited to find a transport layer **other** than the blockchain for sharing data.
