### ISSUE TITLE
Transaction Builder not very detailed as TXID can not be retrieved easily

### ISSUE THREAD

**Issue by dagogodboss** [bitcoinjs/bitcoinjs-lib#1004]
I would appreciate an example that shows how to send BTC using the Lib. the ones in your documentation is not detailed enough I have read both the open and close issue concerning this, and it not quite explanatory. 

```
send_btc : function(pvkey){
		let account = bitcoin.ECPair.fromWIF(pvkey)
    	let txb = new bitcoin.TransactionBuilder()
    	txb.addInput('61d520ccb74288c96bc1a2b20ea1c0d5a704776dd0164a396efec3ea7040349d', 0) // Alice's previous transaction output, has 15000 satoshis. How do i get this please recommend ie the TXID of  previous transaction.  Which api should i use and how do i push to the network.
	    txb.addOutput('3LafzYKRU9DepHxE5zib3LFZqJRyUpki6k', 12000)
	    // (in)15000 - (out)12000 = (fee)3000, this is the miner fee

    	txb.sign(0, account)
    	return txb.build().toHex()
	}
```

A full example would be appreciated.

Ok, I found https://www.smartbit.com.au/api and I ran the address API call the result was so much I don't  which one to pick I saw over 23 transaction id or should I pick anyone, how do I know the last transaction id? now using the address I just created from bitcoinjs-lib it has no transaction id. [Link To API Call ](https://api.smartbit.com.au/v1/blockchain/address/1BvvRfz4XnxSWJ524TusetYKrtZnAbgV3r)

[The Link bitcoinjs-lib address aka new address](https://api.smartbit.com.au/v1/blockchain/address/15JG86Aq9VgDDrHENuUAqyThb7Sx1EnsgY). 

So if the address doesn't have a transaction id that means the wallet is empty right? 

 So which of the transaction id should i pick? ``` is address.trasaction.9.txid```

**Comment by dabura667** [comment]
`https://api.smartbit.com.au/v1/blockchain/address/1BvvRfz4XnxSWJ524TusetYKrtZnAbgV3r/unspent`

response.unspent is an array with each output that is not spent for an address.

use the txid for txid, use n for the vout, and use value_int to count how much input you are adding / code your logic for input selection.

**Comment by dcousens** [comment]
> A full example would be appreciated.

What part of the example wasn't clear for you to consider it less than 'full'?

**Comment by dabura667** [comment]
I think he doesn’t understand the idea of input values, change outputs, and input value total - output value total = fees.

Without an understanding of any of that, normal devs would think sending bitcoin is like:

var key = import(“key”)
var balance = key.getBalance()
key.send(balance)

Etc. to send full balance.

Under those expectations, looking at bitcoinjs-lib examples must be a nightmare lol
