### ISSUE TITLE
How do I derive new Accounts from xPub?

### ISSUE THREAD

**Issue by vzelenko** [bitcoinjs/bitcoinjs-lib#1006]
I am trying to derive a new address based on xPub key on Testnet.

```javascript
const rootKey = bitcoin.HDNode.fromBase58(WALLET_XPUB_KEY, bitcoin.networks.testnet).neutered();
const key = { accountNumber: 20, lastAddressNumber: 10 };
const txtPath = `m/49'/1'/${key.accountNumber}'/0/${key.lastAddressNumber}`;
const child = rootKey.derivePath(txtPath);
return child.getAddress();
```

It fails  on `derivePath` with message `Error: Not a master node` - what is the correct way of getting N'th account addresses?

**Comment by dabura667** [comment]
You can’t derive hardened paths with the xpub alone. You need the private xprv.

**Comment by dcousens** [comment]
`Error: Not a master node` means exactly the Error message.
You can only derive `m/` paths from a master node.

Additionally,  as pointed out by @dabura667,  to derive hardened paths you need the private key.

**Comment by vzelenko** [comment]
@dabura667 & @dcousens - please excuse my ignorance and thank you both for answering!  I still do NOT understand HOW to alter the Account digit on the hardened path during the derivation, private or public based.  Where can I learn more about it?

**Comment by dabura667** [comment]
```javascript
function getBIP44AccountXPub(xprv, accountNumber) {
  const rootKey = bitcoin.HDNode.fromBase58(xprv, bitcoin.networks.testnet);
  const txtPath = `m/44'/1'/${accountNumber}'`;
  const child = rootKey.derivePath(txtPath);
  return child.toBase58(); // returns xpub
}

function xPubToAddress(xpub, index, isChange) {
  if (isChange === undefined) isChange = 0
  else isChange = 1

  if (index === undefined) index = 0

  if (xpub === undefined) throw new Error('Need xpub')

  const accountRootKey = bitcoin.HDNode.fromBase58(xpub, bitcoin.networks.testnet);
  const txtPath = `${isChange}/${index}`;
  const child = accountRootKey.derivePath(txtPath);
  return child.keyPair.getAddress();
  // Note: getAddress() only returns a non-segwit address that starts with a 1 (or m/n in testnet)
  // So to generate BIP49 addresses (P2WPKH-in-P2SH) you need to manually hash the public key
  // and generate the scripts to hash for the P2SH.
}
```

**Comment by vzelenko** [comment]
Thank you!

**Comment by dcousens** [comment]
@vzelenko could you help us improve [this example](https://github.com/bitcoinjs/bitcoinjs-lib/blob/fdcd7aaf986962f2cf0503637ab8e8765635e31a/test/integration/bip32.js#L50) to help others in future?

**Comment by vzelenko** [comment]
I'd be happy to give it a shot today/tomorrow.
