### ISSUE TITLE
Can't sign transaction with private key from hex.

### ISSUE THREAD

**Issue by askz** [bitcoinjs/bitcoinjs-lib#1009]
```javascript
var privateKey = new Buffer(privKeyHex, 'hex')
let wifFromPkey = wif.encode(bitcoinjs.networks.testnet.wif, privateKey, true)
this.privkey = bitcoinjs.ECPair.fromWIF(wifFromPkey, bitcoinjs.networks.testnet)
```
I have a private key in this format e82d33c3eb7f4115290686136e6f466a25aae1d393ccae2204986cf61dcf184a
How can I get to sign txs with it?
Am I doing right with ECPair?
I wasn't able to get HDNode.... and I really need to get it from this hex pkey

**Comment by dabura667** [comment]
Please be clearer.

What are you trying to do? You mention HDNode but there is no attempt to instanciate an HDNode in your sample code.

**Comment by askz** [comment]
Sorry this is resolved by now. Thanks!
I open another issue for another problem.

**Comment by dcousens** [comment]
For others that find this via Google,  I recommend looking at our example for signing a transaction.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/5b0ccb6f68ed9189dc3e382d78e108046974910f/test/integration/transactions.js#L45-L75
