### ISSUE TITLE
Error: RangeError: value out of range when decoding raw tx

### ISSUE THREAD

**Issue by askz** [bitcoinjs/bitcoinjs-lib#1012]
Hi, I ran into issues when decoding some raw transactions, some will decode, some will not.
```javascript
const bitcoinjs = require('bitcoinjs-lib')

const network = {
  messagePrefix: '\x18Monaize Signed Message:\n',
  bip32: {
    public: 0x0488B21E,
    private: 0x0488ADE4
  },
  pubKeyHash: 0x3c,
  scriptHash: 0x55,
  wif: 0xbc
}

let txValid = 
"0100000001605050d7b78352da4332f5f2798e33b3997a7ae296ff8369edcf1eb52c9ad4d6010000006b483045022100e950b4720dd6d4be823a02a70564a80b0174385e9c5242cb57f9ec1d6ac65ee002205b56ef3323d538b2aaa6579b8a17f3d1f5e6164e6b03873d03e608b2bdf848ba012103668e3368c9fb67d8fc808a5fe74d5a8d21b6eed726838122d5f7716fb3328998ffffffff0200e1f505000000001976a91486c7b9ada0107304932a603f19a57a4478d1a7e988ac00382e1b1f0000001976a91473122bcec852f394e51496e39fca5111c3d7ae5688ac00000000"

let txNonValid = 
"0100000001d6987930e07b72810a4be2b92f057b242e9d503452bee254e39c87e57fc3b4b6000000006b483045022100ce1ca28aa02102fce86c712a4dda983b3285cd78ece7108d4a4865cfaa4199ba022035996623faafef94da3ba4de1def041ac21950e82c9fa8d4ab32bc8f70502046012102300d29dc3ffc0e0b28abc64c04458bb57180a7c280fc65108460e16878d86c19feffffff021ab4ec6cc6b858001976a91438cbde195a5f6f6d3863e9dd33643fbf8d2d315f88acc054d228950000001976a91473122bcec852f394e51496e39fca5111c3d7ae5688acd2e8935a"

let decodedTx = bitcoinjs.Transaction.fromHex(txValid, network)
console.log(decodedTx)

let decodedTxNonValid = bitcoinjs.Transaction.fromHex(txNonValid, network)
console.log(decodedTxNonValid);
```
On the second tx I get this : 
```
/home/xx/src/testbjs/node_modules/bitcoinjs-lib/src/bufferutils.js:8
  if (value > max) throw new Error('RangeError: value out of range')
                   ^

Error: RangeError: value out of range
    at verifuint (/home/xx/src/testbjs/node_modules/bitcoinjs-lib/src/bufferutils.js:8:26)
    at Object.readUInt64LE (/home/xx/src/testbjs/node_modules/bitcoinjs-lib/src/bufferutils.js:17:3)
    at readUInt64 (/home/xx/src/testbjs/node_modules/bitcoinjs-lib/src/transaction.js:69:25)
    at Function.Transaction.fromBuffer (/home/xx/src/testbjs/node_modules/bitcoinjs-lib/src/transaction.js:118:14)
    at Function.Transaction.fromHex (/home/xx/src/testbjs/node_modules/bitcoinjs-lib/src/transaction.js:141:22)
    at Object.<anonymous> (/home/xxx/src/testbjs/index.js:23:47)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

**Comment by dcousens** [comment]
@askz does Monaize match Bitcoin exactly for transaction serialization?

**Comment by junderw** [comment]
@askz your first output has a satoshis value of over `0x001fffffffffffff` which is why the check in bufferutils is mad at you.

Your output amount is within 8 bytes but it is over the check value.

@dcousens why check for that value specifically? because its the next bit mask higher than 21 million BTC?

**Comment by dcousens** [comment]
``` js
> (Math.pow(2, 53) - 1).toString(16)
'1fffffffffffff'

**Comment by junderw** [comment]
oh yeah! I forgot, javascript is special! :-D

**Comment by askz** [comment]
Monaize is Komodo fork, that is Zcash fork, that is Bitcoin fork.. (phew)
It does handle tx serialization the same way for transparent to transparent address, which is the case here.
And I can confirm this issue happens on freshly mined block.. maybe it is the problem?

**Comment by dcousens** [comment]
@askz I recommend you dump the data for the output solely,  and investigate why the `value` amount is encoded incorrectly,  or,  why is it higher than expected.

**Comment by dcousens** [comment]
@askz if you resolved your issue,  please post the solution here for others.  If not,  and you are certain the issue is the fault of `bitcoinjs-lib`,  and not a monero related issue,  then I'd be happy to re-open :+1:

**Comment by askz** [comment]
Hi, Sorry for the late feedback.
It is a real issue, but with v8 engine, since we have high initial supply with our coin(s) the maximum integer isn't enough.
We fixed the issue by dividing supply in many accounts....
But the real solution would be to use something like https://github.com/peterolson/BigInteger.js I guess

**Comment by dabura667** [comment]
Yes... unfortunately, bitcoinjs-lib has a lot of places where amount is used, you would need to modify all those areas to use Bigint style.

**Comment by askz** [comment]
Yes I know @dabura667... 
And yes it shouldn't be so hard ahahaah
But the fact is, when you send even 1 satoshi from an address that has >90M you still have the change at >90M :) take me some minutes to understand it ahah.
I guess for now its not a big deal but later we'll come back

**Comment by dabura667** [comment]
You can split change if you want.

```javascript
if (change > 90M) {
  change1 = Math.ceil(change/2)
  change2 = change - change1
}

txb.addOutput(address, change1)
txb.addOutput(address, change2)
```

hehe

**Comment by askz** [comment]
ahahaha not that bad! thanks : )

**Comment by CherryDT** [comment]
Hi, it's still happening in 2021 - is there any solution to it?

I get this error when I'm trying to add this transaction as input: https://live.blockcypher.com/doge/tx/42ad4da5bf726b8a5502fe2b1eb48a01d8d5fcd0144c184093a5fc867d4a4f28/

It is transacting 100,000,001 DOGE which (plus 8 decimals) is too large to fit into 2^53 - but the thing is, I'm trying to spend the 551.8806549 DOGE and not the 99,999,444.81534509 DOGE, why is it still an issue, and how can I solve it? The problem right now is that whenever somebody sends DOGE to my customer's wallet and the transaction in total processes such a large amount, then randomly outgoing transactions from the same wallet will fail because they might pick this as input...

**Comment by Pheromon** [comment]
LOL, in 2021 people still using joke coins

**Comment by CherryDT** [comment]
Irrelevant to the question, and not my choice...

**Comment by junderw** [comment]
- JavaScript can not handle integers larger than 53 bits.
- Bitcoin's maximum number of satoshis will never be larger than 53 bits.
- This is a Bitcoin library.

The network object interface is merely a convenience thing so that any other coin that can work with us can use us. But no coin other than Bitcoin is officially supported.

---

You are probably running into issues because the new PSBT interface has to parse the full transaction of the parent in order to verify the value.

You can skip this check if you have the value and script of the UTXO you wish to spend.

```js
// delete the full transaction from the input
delete psbt.data.inputs[0].nonWitnessUtxo
// add the "segwit" witnessUtxo
psbt.updateInput(0, {
  witnessUtxo: {
    script: yourUtxoScriptBuffer,
    value: yourUtxoValue,
  }
})
// You will need to use @ts-ignore if you are using TypeScript
psbt.__CACHE.__UNSAFE_SIGN_NONSEGWIT = true

// Now signing will use segwit utxo info even if you are NOT segwit.
// This can be attacked by miners to trick you into paying a larger fee
// than you expect if the miner also hacks the node where you get your UTXO info from.
// But this threat model is the exact same as the previous TransactionBuilder from long ago.
```

**Comment by CherryDT** [comment]
Thank you, I will see if this method works for me. I'm getting the UTXOs from a BlockBook instance, so there's a good chance I can get the necessary data there.

(By the way, JavaScript has `BigInt`s for a while now but I guess there is no reason to fix what ain't broken under the premise that only Bitcoin is supported...)

**Comment by alifarabi** [comment]
@junderw is there any way to add BN to this project ?

**Comment by junderw** [comment]
Yes.

Fork it and make your own fork with BN.

but tbh, BigInt is supported in most browsers and NodeJS for years, so maybe it might be fine to add native BigInt (not a dependency)

That said, it's not a big priority.

**Comment by chendatony31** [comment]
I found that BigInt is already supported in 2024.
