### ISSUE TITLE
Recovering Mnemonic 24 word passphrase from crashed Ledger Nano S

### ISSUE THREAD

**Issue by sjnesbitt** [bitcoinjs/bitcoinjs-lib#1013]
I have a ledger nano s. I have used the device once to receive bitcoin. The device is set up to use multi-signature SEGWIT (P2SH). The nano crashed after I used chrome extension to delete a coin (FIDO) so I could add another coin. It then required me to enter passphrase, I did and it says its invalid. I reviewed passphrase for any misspellings (none).  I then manually switched words from the BIP39 list (my were all on list and no missing letters like 'car' to 'card' etc.   Finally , using pieces of info and code I have gleaned from the web, I have built a Ruby Script that will take a mnemonic passphrase (24 word) and then change each word using every word in the mnemonic English text file.   The code checks each new 24 word phrase to determine if it is valid.  It then outputs the following information, BIP44 - Account Xpub,, Xpub, Xprv, seed , and passphrase to a file which i then read into a php program that will create a series of derivative BIP49 addresses from using bitwasp/bitcoin module.   I then compare the addresses created in the php program against the one receive address ever generated on my nano when I moved my bitcoin onto the device.

Questions

When I compare the output of the ruby script with the output of ian Coleman's BIP39 Mnemonic standalone product, the seed, account xpub, and xpub key matches from the BIP44 output, xprv does not.  When I change tabs on Coleman's product to M49 the following outputs change for the same mnemonic passphrase and seed:

BIP32 Root Key
Account XPrv Key
Account Xpub Key
BIP32 Xpub Key

Mine derivative addresses do not match the m49 derivative addresses from coleman's product.  I am a novice at the crypto issues, are there areas that affect output, such as entropy, is it the private key is causing the problem?

Any help would be appreciated. Thanks

UPDATE: I have recovered my passphrase, wallet, and bitcoin.   I opened a repository on github with code and hopefully explanation of how I did it.  Currently it only works if you have the first received Segwit,-P2SH .address.
https://github.com/sjnesbitt/SegWit-P2SH-PassPhrase-Recovery

**Comment by dcousens** [comment]
@sjnesbitt to clarify,  you resolved your issue?

**Comment by sjnesbitt** [comment]
Yes I did.
Steve Seek ye first the kingdom of God... Matthew 6:33 

    On Tuesday, February 27, 2018, 5:41:22 PM EST, Daniel Cousens <notifications@github.com> wrote:  
 
 
@sjnesbitt to clarify, you resolved your issue?
