### ISSUE TITLE
Merge in bitcoinjs-playground payments API

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#1017]

**Comment by dcousens** [comment]
@junderw as I use this more,  and in its lazy-evaluated form,  I think this may simply replace `bitcoin.script.[templates]` and `bitcoin.address` in its entirety.

Can we have a chat this week to walk through the APIs before I [hopefully] get the PR up here?

**Comment by junderw** [comment]
@dcousens sure. Hit me up on Slack.

**Comment by dcousens** [comment]
Added breaking change label,  as this will likely replace all of the `bitcoin.script.[templates]` code when merged.

**Comment by dcousens** [comment]
Merged https://github.com/bitcoinjs/bitcoinjs-lib/pull/1041 to simplify test transitions for this PR

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bitcoinjs-lib/pull/1096
