### ISSUE TITLE
Explain this code

### ISSUE THREAD

**Issue by gittempo** [bitcoinjs/bitcoinjs-lib#1021]
I found this code in a open source project. What is the use of this code?

`var hdNode = bitcoinjs.HDNode.fromBase58(derivedPubKey);
exports.deriveAddress = function(index) {
    return hdNode.derive(index).pubKey.getAddress().toString();
};`

This line creates a new wallet or it just read the wallet address from address array for index?

>    return hdNode.derive(index).pubKey.getAddress().toString();

**Comment by dabura667** [comment]
It derives the index child key of the derivedPubkey as specified in BIP32.

Then it takes the public key of that child key and generates a P2PKH address from it.
