### ISSUE TITLE
What is tx Hex ?

### ISSUE THREAD

**Issue by prahaladbelavadi** [bitcoinjs/bitcoinjs-lib#1024]
On [line 10](https://github.com/bitcoinjs/bitcoinjs-lib/blob/058fa24e094ce98e6709689210d6c344a16399e3/test/integration/blocks.js#L10) when `txHex` is imported from hex to `tx`

- what does txHex stand for ?

If it stands for Transaction in hex format, where can i find that on the block explorer ?

I'm trying to find that specific transaction in the [block](https://blockchain.info/block-height/498303)

- Is this the same transaction that was propagated to the mempool before being included ?

https://github.com/bitcoinjs/bitcoinjs-lib/blob/058fa24e094ce98e6709689210d6c344a16399e3/test/integration/blocks.js#L10

**Comment by dakk** [comment]
The txhex is the hex format representation of a transaction; txhex is the data which is included in a block if the transaction is valid and broadcasted.

For your tx, you can find it in the raw block:
https://blockchain.info/block/00000000000000000097669cdca131f24d40c4cc7d80eaa65967a2d09acf6ce6?format=hex

**Comment by junderw** [comment]
https://www.smartbit.com.au/tx/1d2dffbfde01eaa01d40bee0d2ec4bbc92c92930984aea8aa4fb65f84f74d6c2

This is the transaction that is being used.

**Comment by prahaladbelavadi** [comment]
Thanks @dakk @junderw 

The TxHex is a portion of the raw block dump [here](https://blockchain.info/block/00000000000000000097669cdca131f24d40c4cc7d80eaa65967a2d09acf6ce6?format=hex).

On using the [tx Decoder](https://live.blockcypher.com/btc/decodetx/), I got the transaction output address that checks out correctly.
The input script, output script, data_hex are a part of the transaction hex.
