### ISSUE TITLE
How to add types for `bitcoinjs.script.nullDataOutput()`?

### ISSUE THREAD

**Issue by vsund** [bitcoinjs/bitcoinjs-lib#1026]
This is partly an issue for the types over in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bitcoinjs-lib), but thought it might be helpful to discuss this here.

This library I currently port uses the function `bitcoinjs.script.nullDataOutput()`, which seems to be dynamically generated (if I understood correctly). I'd like to figure out if it's possible to add TypeScript type declarations for it (then over at DefinitelyTyped) and if yes how it would look like for these generated functions.

Happy to provide a PR (at DefinitelyTyped) after figuring out how.

(cc @dcousens @youssefgh)

**Comment by youssefgh** [comment]
`bitcoinjs.script.nullDataOutput()` no longer exist since v3.0.0
The lib you're trying to port seems to be based on an older version of bitcoinjs-lib (probably 2.x)
I suggest re-basing from the latest version (lot of work for you), fork TS definitions and adapt it to your lib, or just call this missing function unsafely (without adding it to TS def)

**Comment by vsund** [comment]
Not really deep into this low-level Bitcoin stuff (and did not try yet to figure this part of the library out).
Is there a drop-in replacement for this in post-v3.0.0 versions?

Also, just checked, the `package.json` contains a `"bitcoinjs-lib": "^3.3.2"` 🤔

**Comment by vsund** [comment]
Whoops, confused the repository, the library is on `"bitcoinjs-lib": "^2.3.0"`.

Also @kantai just [changed it to `nulldata.output`](https://github.com/blockstack/blockstack.js/commit/11c363f31d5ccb17f2be44b2249d47bea65963d3#diff-0b6492609735eec10d4d7336092466a0) (which seems to be what I searched). Seems to be all good now.

Thanks and sorry for rashly open this issue :)
