### ISSUE TITLE
Bech32 output

### ISSUE THREAD

**Issue by BramdeBoer** [bitcoinjs/bitcoinjs-lib#1029]
How should I create outputs to a native segwit bech32 address? Is it the same as a native address like this (but with a bc1.. addr)?
`txb.addOutput(bitcoin.address.toOutputScript("1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX", network), +value);`

**Comment by dabura667** [comment]
Yes. Try it.

**Comment by BramdeBoer** [comment]
Thanks! just checkin
