### ISSUE TITLE
list transaction using xpub key

### ISSUE THREAD

**Issue by marfintack** [bitcoinjs/bitcoinjs-lib#1030]
I have generated seed and xpub using BIP32 then i have generated multiple addresses from the same seed. So now how can i get the transactions using my xpub key

**Comment by dabura667** [comment]
Any of the block explorer APIs out there will work.

**Comment by marfintack** [comment]
I want to know the technique like how the xpub key fetch transactions.

**Comment by marfintack** [comment]
Another thing is i am not able to get the transaction through blockexplorer
apis

**Comment by dabura667** [comment]
You can’t fetch transactions with an xpub.

You need to derive the addresses and query each address.

**Comment by dabura667** [comment]
Then the easiest way would be yo register all your addresses as watch-only addresses with bitcoind and get the transactions that way.

**Comment by dabura667** [comment]
```
bitcoin-cli importaddress 1addressxxxxx accountName 0
```

Import all your addresses with 0 for rescan.

BUT on the LAST address use 1 instead (1 will rescan all new addresses imported since last rescan.)

I would use the same account (a new one) for all the addresses from a single xpub.

**Comment by marfintack** [comment]
I have 25000 addresses right now, what i understand is i need to import
24999 address with 0 for rescan and the last address with 1 rescan. After
that whenever i need to create a individual address. i will import the
address with 1 rescan. Am i right ? kindly tell me about the rescan feature
what's the logic behind this thing ?

**Comment by junderw** [comment]
rescan scans the whole blockchain for that address.

For my PC a rescan takes about 30 minutes - 1 hour.

If you did 25000 addresses with 1 rescan each, it will take 25000 hours :-X

I don't recommend doing importaddress with 1 address.

I would do it in batches. maybe 500 at a time? (499 with rescan 0 then last 1 with rescan 1)

**Comment by junderw** [comment]
Every time you run importaddress with 1 (or nothing, the default is 1) it scans the blockchain.

Every time you run with 0, it doesn't scan the blockchain.

If you run with 0 for 9 addresses, then after that run it with 1 for one address. It will scan the blockchain for all 10 addresses.

If you run 1 for all 10 addresses. It will scan the blockchain after each address, and take 10 hours.

**Comment by marfintack** [comment]
rescan scan the blockchain for matching the address. what if it found that
address over blockchain ? what next ?

**Comment by junderw** [comment]
..... listtransactions etc...

importaddress = import address into bitcoind account.

Which means you use normal RPC calls as usual.

**Comment by marfintack** [comment]
ok that's find. Thanks for making me undestand this thing. I really
appreciate your effort. Thank you!!

**Comment by junderw** [comment]
http://chainquery.com/bitcoin-api/help/listunspent

`listunspent` seems better. It will give you txid, vout, and amount.

Everything you need to create a transaction.

**Comment by marfintack** [comment]
Thanks man

**Comment by marfintack** [comment]
I want to know another thing like if i import 0.2 million or greater
addresses to my wallet. Will it affect rpc response for other calls like
getbalance and gettransactionlist. In my case i am repeatedly calling
getbalance and transactionlist call.

**Comment by dabura667** [comment]
I have never tried.

Report back with your findings. :-)

**Comment by dcousens** [comment]
For others information,  I highly recommend to **never** provide an extended public key (xpub) to untrusted 3rd parties.

As per the BIP32 specification,  if even one private key is revealed,  you risk all of them being revealed by derivation.

See https://github.com/bitcoinjs/bitcoinjs-lib/blob/93b815c20ea74ce446114e108321cd3d4fb0eede/test/integration/crypto.js#L69 for an example of how this can happen.
