### ISSUE TITLE
Unable to generate Litecoin address

### ISSUE THREAD

**Issue by thEpisode** [bitcoinjs/bitcoinjs-lib#1031]
Hi guys, I'm trying to generate Litecoin address following your example on [this link provided from readme](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/addresses.js#L131) but trown an error:

> TypeError: rng is not a function
...\node_modules\bitcoinjs-lib\src\ecpair.js:94
    var buffer = rng(32)

And checking typeof of rng y an ArrayBuffer (obviously is not a function), example is outdated? or is a real bug? Thanks, awesome library.

**Comment by dcousens** [comment]
@thEpisode notice that `rng` was defined in that file:
https://github.com/bitcoinjs/bitcoinjs-lib/blob/058fa24e094ce98e6709689210d6c344a16399e3/test/integration/addresses.js#L9

You probably don't need to define an `rng` function,  use the default `randombytes` rng as provided.
