### ISSUE TITLE
What format is node variable storing data in ?

### ISSUE THREAD

**Issue by prahaladbelavadi** [bitcoinjs/bitcoinjs-lib#1033]
Ref:https://github.com/bitcoinjs/bitcoinjs-lib/blob/058fa24e094ce98e6709689210d6c344a16399e3/test/integration/bip32.js#L18

I'm trying to log the contents of the node variable but when I do so in its raw format, I'm unable to make much sense out of it.

``typeof(node)`` returns object

What's a good resource to read and understand more about HDnodes ?

**Comment by prahaladbelavadi** [comment]
String converts it to base58 and it's much more comprehensible

but still what would be a good resource to understand HDnodes ?

**Comment by dabura667** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/hdnode.js

Basically the object contains all info needed to generate child keys from the current node.

HDNodes are an implementation of BIP32
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

**Comment by junderw** [comment]
@prahaladbelavadi Let us know if you have any further questions.

**Comment by prahaladbelavadi** [comment]
Thanks @dabura667 
I'm going through the links and I feel there is still a lot I don't understand about BIP32's wallet structure regarding extended keys, child key derivation and so much more.
It'll probably take me some time before I understand it.
Thanks for the support @junderw @dabura667 
I certainly will :)
