### ISSUE TITLE
Remove duck-typing

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#1040]
If possible,  I'd like to try and remove the use of `quacksLike`.
I think any scenario where multiple versions of the underlying cryptographic primitives are being provided should be eliminated by [`4.0.0`](https://github.com/bitcoinjs/bitcoinjs-lib/issues/508),  and if it did happen,  it would truly be an unsafe scenario to not support duck typing anyway.

We can additionally remove the `uglify-js` README disclaimers. :fireworks:

**Comment by dabura667** [comment]
What are the practical benefits?

What would replace it?

quacks_like?

**Comment by dcousens** [comment]
`instanceof`?

**Comment by dcousens** [comment]
Removed in https://github.com/bitcoinjs/bitcoinjs-lib/pull/1070
