### ISSUE TITLE
Proposal for standalone examples

### ISSUE THREAD

**Issue by prahaladbelavadi** [bitcoinjs/bitcoinjs-lib#1044]
Examples references in the repository point to test cases which could potentially act as a barrier to entry to someone that isn't familiar with how testing works.

I've been manually trying to examine each of these functions in standalone js files [here](https://github.com/prahaladbelavadi/bitcoin-js-testing/tree/master/myTest/transaction-operations)

Examples logging outputs at certain places will help with understanding how the library works.

Would like to hear thoughts on preparing separate sample files for making it easier for people to adopt get started with using bitcoinjs library

**Comment by afk11** [comment]
Somewhat agree! I'd say by now things that need tests are already tested.. we could possibly be a little more verbose in example scripts. could execute them during travis the same way we do tests, to make sure we haven't broken something.

**Comment by dcousens** [comment]
> could execute them during travis the same way we do tests, to make sure we haven't broken something.

That was the biggest benefit of the integration approach.
Is there a simple dependency that will test the code used in a `README.md`?

**Comment by prahaladbelavadi** [comment]
Maybe we could adopt a similar structure from [ExpressJS examples](https://github.com/expressjs/express/tree/master/examples) 

Or 

We could use [this](https://github.com/Widdershin/markdown-doctest) to test the example code if we'll be embedding sample code in markdown

Thoughts on this ? @dcousens @afk11

**Comment by afk11** [comment]
I'd just run nodejs over every file in the directory and link to it from a markdown file. Often when I leave a code snippet in markdown, it goes out of date a week later :)

**Comment by prahaladbelavadi** [comment]
lol that's true 
it makes sense
I'll add example files and make an index to reference them

**Comment by dcousens** [comment]
Closing in faovur of #1051,  and if any other new PR comes,  I'll track it from there
