### ISSUE TITLE
Replace HDNode with bitcoinjs/bip32

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#1047]
`.HDNode` will be hard deprecated (removed),  for now replaced with `.bip32`.

The bitcoinjs/bip32 mirrors the `ECPair` API,  however `node.keyPair` does not exist.
To access the private/public key,  you can use `getPrivate`, `getPublic` respectively, or whatever `ECPair` uses respectively.

The 2 interfaces should match.

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bitcoinjs-lib/pull/1073

**Comment by imediabiz** [comment]
how to use bip32 Keypair for signing transaction?

**Comment by dcousens** [comment]
@imediabiz no differently than using an `ECPair`.

**Comment by imediabiz** [comment]
txb.sign(0, keyPair0, p2sh.redeem.output)
TypeError: Inconsistent network
    at TransactionBuilder.sign (/Users/budiyuwono/node_modules/bitcoinjs-lib/src/transaction_builder.js:628:66)

**Comment by dcousens** [comment]
Read the error
