### ISSUE TITLE
Change `TransactionBuilder.prototype.sign` interface

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#1048]
To mirror https://github.com/bitcoinjs/bitcoinjs-lib/issues/508#issuecomment-364828793
To complement the new payments interface flow. 

### Example 1 - P2PKH
``` js
txb.sign(0, SIGHASH_ALL, function (hash) {
  return bitcoin.payments.p2pkh({
    pubkey: keyPair.getPublicKeyBuffer(),
    signature: keyPair.sign(hash, SIGHASH_ALL)
  })
})
```

### Example 2 - P2WPKH
``` js
const bitcoin = require('bitcoinjs-lib')
const pubKey = bitcoin.HDNode.fromBase58('ypub6XMTwf6NSvfzYYgVgdNWRNfMTiQt4rSjZbEk8qoCnBGhUD2rsgZ2A8pexgzaGLKgySZxqxrctDpAVU8QtfxqfX8QUAhtFmGFUFx9B51TVg8')
  .derive(0)
  .derive(27)
  .getPublicKeyBuffer()

const { address } = bitcoin.payments.p2sh({
  redeem: bitcoin.payments.p2wpk({
    pubkey: pubKey
  })
})

// ...

let txb = new Transaction()
txb.addInput(..., ...)
txb.addOutput(..., ...)

txb.signForWitnessV0(0, unspent.value, SIGHASH_ALL, function (hash) {
  let signature = keyPair.sign(hash, SIGHASH_ALL)

  // expects { input, witness } at the least 
  return bitcoin.payments.p2sh({
    redeem: bitcoin.payments.p2wpk({
      pubkey: pubKey,
      signature: signature
    })
  })
}) 
```

#### Example 3 - P2MS
``` js
let signatures = [OPS.OP_0, OPS.OP_0]
let pubkeys = [alice, bob, keyPair.getPublicKeyBuffer()]

txb.sign(0, SIGHASH_ALL, function signFn (hash) {
  let signature = keyPair.sign(hash, SIGHASH_ALL)
  signatures[1] = signature

  // expects { input } at the least 
  return bitcoin.payments.p2sh({
    redeem: bitcoin.payments.p2ms({
      m: 2,
      pubkeys,
      signatures,
      allowIncomplete: true
    })
  })
})
```

Supported by https://github.com/bitcoinjs/bitcoinjs-lib/issues/737#issuecomment-347411394

**Comment by dcousens** [comment]
Related to https://github.com/bitcoinjs/bitcoinjs-lib/issues/1017

**Comment by dcousens** [comment]
> where is the scriptPubKey here? 

Do you mean where is `addOutput`,  or do you mean where is the scriptPubKey being passed for the signing?
I didn't show `addOutput`, as it is independent of signing,  for signing,  it isn't needed at this point,  because `input` was provided verbatim.

>  we should be letting the signer decide what way to add signatures, not pass on yet more primitives to the public api

That is the entire point!  Let the signer (person) decide,   rather than guessing.

**Comment by afk11** [comment]
It just seems the API is going a step backwards, given the scriptPubKey (or the eventual redeemScript/witnessScript) informs how that closure should look anyway.

**Comment by dcousens** [comment]
@afk11 I'm not understanding your argument.
We still control everything? What am I missing?

**Comment by dcousens** [comment]
To include the `prevTxOut`,  you could literally pass it in the payments via `output`.

**Comment by dcousens** [comment]
``` js
txb.sign(0, SIGHASH_ALL, function (hash) {
  return bitcoin.payments.p2pkh({
    output: myTxOut.output,
    pubkey: keyPair.getPublicKeyBuffer(),
    signature: keyPair.sign(hash, SIGHASH_ALL)
  })
})
```

**Comment by afk11** [comment]
> The user is explicitly choosing how their signature is packaged in the above?

Beyond the script type, what things do you see people 'choosing' here? 

We're knee deep in classification issues https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L58 and many would simply disappear if we had the output script, instead of allowing users to tell us what type of script we have. 

Notice in your snippet above, the user needs to call a function called 'bitcoin.payments.p2pkh' - why not just give the scriptPubKey, then the signer knows exactly how the signatures should be represented. (the transaction_builder calls bitcoin.payments.p2pkh() internally)

**Comment by dcousens** [comment]
> We're knee deep in classification issues

My point was,  with the above,  we'd have no classification at all in `TransactionBuilder`.
The `TransactionBuilder` interface would become a wrapper that assembles a raw transaction for you.

> many would simply disappear if we had the output script, instead of allowing users to tell us what type of script we have

Via classification.  We'd be specifying an order of detection,  and the complexity would be similar to now,  with the number of potential error cases remaining the same.

> Notice in your snippet above, the user needs to call a function called 'bitcoin.payments.p2pkh' - why not just give the scriptPubKey, then the signer knows exactly how the signatures should be represented

In that case,  the user would have no idea what they are signing unless the inspect the `scriptPubKey` themselves.  If a user is specifying the script type as an enum,  that is better,  but it still requires a bit of leg work on our part.

> why make it one more thing users need to keep in mind?

In my mind,  you need to keep this in mind already... the difference is whether it is done silently or with the users permission.
The difference is we could trivially add extra support for new scripts / channels using the above method,  with no bounds on the data provided through functions arguments.

> since all of the operations on sigs/pubkeys are based on the script anyway. users don't want to be aware of this stuff, they just want to sign and move on (safely)

I agree with you here,  in the one case it is most apparent: P2PKH/P2WPKH.
I don't think abandoning the entire premise of the above is worth it for those cases though.
Especially in the long term (think 2+ years).

> To me, trying to pass this responsibility onto our users is a sign something is wrong

I think as a library,  we have always favored **power** and **safety** over convenience.
The issues faced with the existing templates API is that the complexity of the incantations required was often dangerous.
I think the above readability improvements counter that,  at the cost of some convenience in a "classical" API that we've had for a while now.

I'm open to suggestions,   but it honestly feels like we're mostly interested in only making P2PKH/P2WPKH a bit more "convenient" via 1 argumenet than the present 2 arguments.
In many other cases, the amount of information required hasn't changed.

**Comment by dcousens** [comment]
FWIW,  I concur that the case presented:

``` js
 return bitcoin.payments.p2sh({
    redeem: bitcoin.payments.p2wpk({
      pubkey: keyPair.getPublicKey(),
      signature: keyPair.sign(hash)
    })
  })
```

Is a pain compared to
``` js
  let redeemScript = bitcoin.payments.p2wpk({
     pubkey: keyPair.getPublicKey()
  }).output

// ... later

  return magicP2SHSigner(redeemScript)
// or
  return magicP2SHSigner(keyPair, { p2wpk: redeemScript })
```

**Comment by dcousens** [comment]
@afk11 how about after merging the payments API,  we have a look at this en-masse when we see the havoc the appears (if any) with cases like

https://github.com/bitcoinjs/bitcoinjs-lib/blob/09c5ff1d6b176d0d051b758043dcc141b3d7c9b5/test/integration/transactions.js#L69-L70

and

https://github.com/bitcoinjs/bitcoinjs-lib/blob/09c5ff1d6b176d0d051b758043dcc141b3d7c9b5/test/integration/transactions.js#L123-L124

**Comment by dabura667** [comment]
Also I’d like to interject that p2ms usually will be sorted canonically, so in the example where it places the signature in signatures[1] the coder using the API will most likely not know which position to place the signature unless they add a step to check the positions of the pubkeys.

But it sounds like everything is going back to the drawing board, so I guess it’s irrelevant.

We can get rid of “FixMSorder” function if the redeemscript is always present for us to check the order. I think that should be done internally as a helper function.

**Comment by afk11** [comment]
The fix MS order function is required though, because you need to compute sighashes when you don't have the helpful zero padding for signature order. For a 2-of-3, it's possible to receive a (partial) scriptSig like sig `0 [sig]` instead of `0 [sig] 0 0`, in which case you need to associate [sig] to one of the pubkeys.

**Comment by dcousens** [comment]
I'm going to change this to `5.0.0`,  as for now this isn't clear.
We can play with some feature-added API interfaces to change this over in the `4.x.y` range if it is worth it.

**Comment by junderw** [comment]
Going to close in favor of Psbt #1425
