### ISSUE TITLE
Signing P2SH inputs

### ISSUE THREAD

**Issue by panpan2** [bitcoinjs/bitcoinjs-lib#1053]
Is there a way to sign non-SegWit P2SH inputs?

Observing [src/transaction_builder.js](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L672) the inputs to the sign function are
vin, keyPair, redeemScript, hashType, witnessValue, witnessScript

Does leaving the witnessValue and witnessScript undefined do what is described? Or is there another way to do this?
Thanks for any help!

**Comment by dcousens** [comment]
> Does leaving the witnessValue and witnessScript undefined do what is described? Or is there another way to do this?

Yes,  they are optional.

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L115

**Comment by panpan2** [comment]
Great, Thanks a lot!
