### ISSUE TITLE
Example links not working

### ISSUE THREAD

**Issue by pankajsy9** [bitcoinjs/bitcoinjs-lib#1056]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/advanced.js#L17

**Comment by dcousens** [comment]
What example is that? It isn't in the README?

**Comment by pankajsy9** [comment]
I took it from README.

Cannot find it now.

**Comment by dcousens** [comment]
It may have been moved.  What was the example?

**Comment by pankajsy9** [comment]
It was related to signing and verification using ECDSA.

**Comment by pankajsy9** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/tree/v2.1.4

In README the example links are not working.

For eg:  Sign a bitcoin message 
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/advanced.js#L9
