### ISSUE TITLE
Bitcoinjs for altcoin

### ISSUE THREAD

**Issue by zhq422194011** [bitcoinjs/bitcoinjs-lib#1058]
I forked the bitcoin 0.16 with little bit changes.
I try to use bitcoinjs sending transaction.
I used the following code:

```
var bitcoin = require('bitcoinjs-lib')
var value = 50*10e7
var alice = bitcoin.ECPair.fromWIF('L5ZRcZeyAh8tU5rYZKEuYggm5is5XiZqdzDS1TMgoudHkgPs1PcR')
var txb = new bitcoin.TransactionBuilder()

txb.setVersion(2)
txb.addInput('7316cb50009743dce660b2dc43742cb63eac43434ff6b5f018578ad3eaf7f803', 0)
txb.addOutput('1A6csP8jrpyruyW4a9tX9Nonv4R8AviB1y', value-10000)
txb.sign(0, alice)
console.log(txb.network)
console.log(txb.build().toHex())

```

However, I got this:

error code: -26
error message:
16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)

Could you help me?

**Comment by zhq422194011** [comment]
I found the reason. Thanks!

**Comment by dabura667** [comment]
Please share the reason.

**Comment by zhq422194011** [comment]
I used wrong private key format.
