### ISSUE TITLE
create addresses by mnemonic  is very slowly

### ISSUE THREAD

**Issue by silence-may** [bitcoinjs/bitcoinjs-lib#1064]
excuse me ,
       i want to create address by mnemonic，
       eg:
      var root = bitcoin.HDNode.fromSeedHex('dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd')

    var child1 = root.derivePath("m/44'/0'/0'/0/0")

    assert.equal(child1.getAddress(), '12Tyvr1U8A3ped6zwMEU5M8cx3G38sP5Au')

    like this ,when i  pass about 20 path,  it's become very slowly , it's spent time about 20 seconds , i want to konw why and  what should i do?  thanks a lot！

**Comment by dabura667** [comment]
Have you tried:

var node = root.derivePath("m/44'/0'/0'/0")

for (var i = 0; i < 20; i++) {
   var child = node.derive(i)
   // do stuff
}

**Comment by silence-may** [comment]
Thanks a lot !!!  it's very helpful !!  It saves about 1/3 of the time
