### ISSUE TITLE
How to work with Altcoins?

### ISSUE THREAD

**Issue by KevinKelbie** [bitcoinjs/bitcoinjs-lib#1065]
In the readme is says

> Altcoin-ready: Capable of working with bitcoin-derived cryptocurrencies (such as Dogecoin).

but what actually goes into working with altcoins such as Dogecoin? Do I just need to update the networks.js or is there more to it?

I found this repository which seems to have all the data that is required: https://github.com/walletgeneratornet/WalletGenerator.net/blob/36cefb15c625f86c1427e9a17c2bb8d5140918a4/src/janin.currency.js#L89

I assume you haven't added more coins for a reason, what are the issues I should expect?

**Comment by dabura667** [comment]
Adding coins to networks.js would sound like an endorsement.

If you are a developer, you can figure out the network info and create your own object

This helps:
https://github.com/cryptocoinjs/coininfo

**Comment by dcousens** [comment]
@dabura667 should we link to `coininfo` in the README?
