### ISSUE TITLE
Exporting my private key , public key and recieving address lists directly from my own seed list 

### ISSUE THREAD

**Issue by vishal2241** [bitcoinjs/bitcoinjs-lib#1071]
Hello ,

I had randomly choosen 10 different mnemonic combinations of 12 words withchecksum validated. Now how should i automatically export  10 private keys , public keys and  address to an txt file with each corresponding combination using bitcoinjs. How to tell the script about using bip44 as derivation path and choosing coin and account as in ian coleman script. Can someone help.

**Comment by dcousens** [comment]
@vishal2241 this borders on asking us to write your code for you.  Have you actually run into any problems?

**Comment by rbndg** [comment]
That repo is powered by bitcoinjs-lib as well. 

If you want to run that in nodejs, i suggest that you fork the lib and make the required changes to make it work in nodejs.

**Comment by dcousens** [comment]
> If you want to run that in nodejs, i suggest that you fork the **repo** and make the required changes to make it work in nodejs.

**Comment by dabura667** [comment]
ECDSA is slow.

A language like golang would be faster imo

**Comment by dcousens** [comment]
@dabura667 `4.0.0` uses the native C library `secp256k1`... I don't think we'll get faster without forgoing the entirely library in JS!
The bindings cost difference between Node/Go is probably different,  but not _that_ different.
If performance matters,  find where it matters,  and put use C below that ha.
