### ISSUE TITLE
How can create child address by the parent privateKey or publickKey??

### ISSUE THREAD

**Issue by silence-may** [bitcoinjs/bitcoinjs-lib#1074]
excuse me,
       I have some problem!  
      eg:
      BTC's:  privateKey:XXXXXXXX,
      BTC's:  publickKey,XXXXXXXX,
      the path is   m/44'/0'/0',
      how  can  create a address of   m / 44' / 0' / 0' / 0 / 0,

      Thanks  a lot!!!

**Comment by junderw** [comment]
```javascript
var bitcoin = require('bitcoinjs-lib')

var hdNode = bitcoin.HDNode.fromBase58('xpub6CEVrVYpttGAoP2v...........c49ZTYSLaW')

var address = hdNode.derive(0).derive(0).getAddress()
```

**Comment by silence-may** [comment]
thanks you answer!
     sorry for that i want to know the  ''xpub6CEVrVYpttGAoP2v...........c49ZTYSLaW''    is   what???

**Comment by junderw** [comment]
Also known as "Extended Key"

xpub is public
xprv is private

https://bitcoin.org/en/developer-guide#term-extended-key
