### ISSUE TITLE
what's the reason of the wrong?

### ISSUE THREAD

**Issue by silence-may** [bitcoinjs/bitcoinjs-lib#1075]
excuse me
    my code:
let seed = bip39.mnemonicToSeed(mnemonic);
let bip32RootKey = bitcoinJS.HDNode.fromSeedBuffer(seed);
when i don't build the code ,it's runing correct,
but,when i webpack the code,there are some wrong,
![image](https://user-images.githubusercontent.com/20940285/40235880-2ff7d4ea-5ade-11e8-853e-9d41b6169ee4.png)
so，can you tell me about the reason?? thanks!

**Comment by dabura667** [comment]
you need to demangle your js when you pass it to uglify-js.

Please read the README to learn how.

**Comment by dabura667** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/issues/959#issuecomment-351040758

For webpack users just add the options inside of plugins `UglifyEsPlugin`

```bash
npm -D install uglify-es-webpack-plugin
```

webpack.config.js
```javascript
const UglifyEsPlugin = require('uglify-es-webpack-plugin');

module.exports = {
  // ・・・
  plugins: [
    new UglifyEsPlugin({
        mangle: {
            reserved: [
                'Buffer',
                'BigInteger',
                'Point',
                'ECPubKey',
                'ECKey',
                'sha512_asm',
                'asm',
                'ECPair',
                'HDNode'
            ]
        }
    }),
  ],
  // ・・・
}
```
