### ISSUE TITLE
Use ES6 classes

### ISSUE THREAD

**Issue by junderw** [bitcoinjs/bitcoinjs-lib#1083]
Just a thought.

**Comment by rbndg** [comment]
It does seem that the JS ecosystem is moving towards using the class syntax over prototype syntax. React being one example.

**Comment by dcousens** [comment]
As pointed out by @rbndg in https://github.com/bitcoinjs/bitcoinjs-lib/issues/1069#issuecomment-389095993

Prefer the ES6 `get/set` syntax if possible.

``` js
class Foo {
  constructor () {}
  get foo () { return 1 }
  set foo () {}
  static boo () { return 2 }
}
```

**Comment by dcousens** [comment]
We don't need to be ubiquitous in this roll-out... and provided the breaking changes are in 4.0.0,  I don't mind if we use either syntax.

**Comment by dcousens** [comment]
What about ES6 import/exports?  How are people going these days with that?
I use babel on my modules so it is ok... But,  it was a horror to set up.

**Comment by rbndg** [comment]
It has more traction on the frontend js than Nodejs. I think most node projects are still using `require` but on the frontend import/export has lots more traction. Especially in React dev.
