### ISSUE TITLE
I want to use this library to create a transaction....

### ISSUE THREAD

**Issue by Yangk030208** [bitcoinjs/bitcoinjs-lib#1098]
I want to use this library to create a transaction that is sent by the A address to the B address, but I don't find the valid document, who can help me and give me some valuable documents. Thanks very much。

**Comment by dcousens** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L46

Let us know if you have any other questions

**Comment by Yangk030208** [comment]
@dcousens   Thank you very much for your reply. I have another question: what does the red mark represent in the picture I uploaded.thanks very much .

![tim 20180612160152](https://user-images.githubusercontent.com/23301914/41277648-654c2134-6e5a-11e8-8d4b-d84fca580645.png)

**Comment by dcousens** [comment]
`L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF2BRUVwy` represents a private key.
You might produce your own using `bitcoin.ECPair.makeRandom()`.

`61d520ccb74288c96bc1a2b20ea1c0d5a704776dd0164a396efec3ea7040349d` represents the `txId` of the transaction output that you are **spending**.

**Comment by junderw** [comment]
https://bitcoin.org/en/developer-guide#transactions

This is a great resource to understand how transactions work.

If you don't understand transactions, you can not send Bitcoin... bitcoinjs-lib does not offer a simple bitcoin.send(fromAddress, toAddress, amount) function... as that is not how bitcoin works.

Good luck on your studies!
