### ISSUE TITLE
bech32 support？

### ISSUE THREAD

**Issue by guotie** [bitcoinjs/bitcoinjs-lib#1102]
does this lib support bech32?

**Comment by dcousens** [comment]
@guotie yes!

https://github.com/bitcoinjs/bitcoinjs-lib/blob/d7eb6c8e77c0d73bdd54a2b4dedfa1055d361c33/test/integration/addresses.js#L59-L64

Or did you mean generic `bech32` encoding of _any_ data?
In which case, use https://github.com/bitcoinjs/bech32
