### ISSUE TITLE
Hello, I have generated the wallet address, how can I import it into other BTC wallet for transfer?

### ISSUE THREAD

**Issue by liuhuanhui** [bitcoinjs/bitcoinjs-lib#1107]
const bitcoin = require("bitcoinjs-lib");
const getRandomWallet = function () {
  const keyPair = bitcoin.ECPair.makeRandom();
  return {
    address: keyPair.getAddress(),
    privKey: keyPair.toWIF(),
  };
};

Hello, I have generated the wallet address, how can I import it into other BTC wallet for transfer?

**Comment by junderw** [comment]
WIF keys are not well supported anymore...

Electrum has a recovery mode called "Import Bitcoin Addresses or private keys"
![_001](https://user-images.githubusercontent.com/11246316/41809574-cdf8c8e4-772a-11e8-9821-b8863b9439ec.png)

Paste only your WIF private key in there, and it will let you spend.

Please re-open if you need more help.

**Comment by junderw** [comment]
You can also do the below, and doing BIP39 restore in Electrum will give you the same first address, and it will be an HD wallet.
```javascript
const bip39 = require('bip39')
const bitcoin = require('bitcoinjs-lib')

function generateNewKeys() {
  let phrase = bip39.generateMnemonic(null, null, bip39.wordlists.chinese_simplified)
  let seed = bip39.mnemonicToSeed(phrase)
  let HDRoot = bitcoin.HDNode.fromSeedBuffer(seed)
  let BIP44FirstKey = HDRoot.derivePath("m/44'/0'/0'/0/0")
  let address = BIP44FirstKey.getAddress()

  return {
    address: address,
    privatePhrase: phrase
  }
}

let result = generateNewKeys()
console.log(result)
// {
//   address: '1KuKX3WqrsgJPCqqCNMc5TsojCXCkjqvZL',
//   privatePhrase: '仇 衣 泡 晋 物 世 蒸 稍 馏 微 圈 缘'
// }
```

**Comment by liuhuanhui** [comment]
@junderw 
const bip39 = require('bip39')
const bitcoin = require('bitcoinjs-lib')

function generateNewKeys() {
  let phrase = bip39.generateMnemonic(null, null, bip39.wordlists.chinese_simplified)
  let seed = bip39.mnemonicToSeed(phrase)
  let HDRoot = bitcoin.HDNode.fromSeedBuffer(seed)
  let BIP44FirstKey = HDRoot.derivePath("m/44'/0'/0'/0/0")
  let address = BIP44FirstKey.getAddress()

  return {
    address: address,
    privatePhrase: phrase
  }
}

let result = generateNewKeys()
console.log(result)
// {
//   address: '1KuKX3WqrsgJPCqqCNMc5TsojCXCkjqvZL',
//   privatePhrase: '仇 衣 泡 晋 物 世 蒸 稍 馏 微 圈 缘'
// }

Thank you for your reply. I tried the code you sent to generate the address, and failed to import in Electrum.

**Comment by liuhuanhui** [comment]
![image](https://user-images.githubusercontent.com/10370625/41814978-fbd544ee-778f-11e8-9ed9-3918ac987405.png)
![image](https://user-images.githubusercontent.com/10370625/41814980-0bcc41cc-7790-11e8-9da5-d0b58a612a0f.png)

**Comment by liuhuanhui** [comment]
```
const bip39 = require('bip39')
const bitcoin = require('bitcoinjs-lib')

function generateNewKeys() {
  let phrase = bip39.generateMnemonic(null, null, bip39.wordlists.chinese_simplified)
  let seed = bip39.mnemonicToSeed(phrase)
  let HDRoot = bitcoin.HDNode.fromSeedBuffer(seed)
  let BIP44FirstKey = HDRoot.derivePath("m/44'/0'/0'/0/0")
  let address = BIP44FirstKey.getAddress()

  return {
    address: address,
    privatePhrase: phrase
  }
}

let result = generateNewKeys()
console.log(result)
// {
//   address: '1KuKX3WqrsgJPCqqCNMc5TsojCXCkjqvZL',
//   privatePhrase: '仇 衣 泡 晋 物 世 蒸 稍 馏 微 圈 缘'
// }
```
Will it happen to produce the same wallet?

**Comment by junderw** [comment]
If you look at the Addresses tab you will see the same address.

The warning will say "There is not money in this wallet" but that is OK.

Also, you must put space (`' '`) between each symbol, not a line break (`'\n'`)

![_001](https://user-images.githubusercontent.com/11246316/41829121-f3bdb5f4-7873-11e8-8afa-f5b58e069bc2.png)

**Comment by junderw** [comment]
You might need to show the "Addresses menu" with the "view" menu option at the top of the window.

**Comment by dcousens** [comment]
@junderw 
>WIF keys are not well supported anymore...

Interesting perspective.
Understandable with BIP32's dominance,  but,  are we helping at all by still providing `ECPair` generally?

**Comment by junderw** [comment]
>  are we helping at all by still providing ECPair generally?

offering it is fine IMO, but I think we should move all tests and examples to only use HDNodes or their equivalent....

Also, I think that HDNodes should be written as a class extending ECPair so that anything taking an ECPair could take an HDNode...

HDNode would need to hold a path attribute and cache the current path's account level...

Perhaps a new instance could default to BIP49, which would grab the private info from xprv, derive m/49'/0'/0'/0 and m/49'/0'/0'/1 and cache them as "receiveNode" and "changeNode". Then when calling "getAddress(4) it will do p2sh(p2wpkh(hdnode.receiveNode.derive(4))) and return the address... etc etc...

Currently, ECPair looks like the main event to any first time programmers... perhaps this paradigm needs a shift...
