### ISSUE TITLE
Trouble getting hex value of custom p2sh redeemscript

### ISSUE THREAD

**Issue by coinables** [bitcoinjs/bitcoinjs-lib#1108]
The hex output of the redeemscript I'm getting is not a valid redeemscript. I presume I am missing something like an encode or a buffer and I'm just getting the hex value from the wrong format. Any ideas?

        let NETWORK = bitcoin.networks.testnet;
        let ecPairInput = bitcoin.ECPair.fromWIF(privateKey, NETWORK);  

        function utcNow () {
		return Math.floor(Date.now() / 1000)
        }
        let lockTimeInput = bip65.encode({ utc: utcNow() + 3600 });
	
        function cltvCheckSigOutput (ecPair, lockTimeInput) {
		return bitcoin.script.compile([
		  bitcoin.opcodes.OP_IF,
		  bitcoin.script.number.encode(lockTimeInput),
		  bitcoin.opcodes.OP_CHECKLOCKTIMEVERIFY,
		  bitcoin.opcodes.OP_DROP,

		  bitcoin.opcodes.OP_ELSE,
		  bitcoin.opcodes.OP_NOP,
		  bitcoin.opcodes.OP_ENDIF,

		  ecPair.publicKey,
		  bitcoin.opcodes.OP_CHECKSIG
		])
	  }		

        let redeemScript = cltvCheckSigOutput(ecPairInput, lockTimeInput);
        let redeemScriptHash160 = bitcoin.crypto.hash160(redeemScript);
        let redeemScriptHex = redeemScript.toString("hex");
	
        let scriptPubKey = bitcoin.script.scriptHash.output.encode(redeemScriptHash160);
        let address = bitcoin.address.fromOutputScript(scriptPubKey, NETWORK);

        //redeemScriptHex output is not valid!
        {address: "2NDfjgkQEJzGJBm49A1rydHDtd7eBhRoup5", redeemScriptHex: "6304af9b2e5bb17567616800ac"}

**Comment by afk11** [comment]
It's perfectly a valid script, besides the superfluous ELSE ENDIF section. What part are you having problems with?

```
bitcoin-cli -regtest decodescript 6304af9b2e5bb17567616800ac
{
  "asm": "OP_IF 1529781167 OP_CHECKLOCKTIMEVERIFY OP_DROP OP_ELSE OP_NOP OP_ENDIF 0 OP_CHECKSIG",
  "type": "nonstandard",
  "p2sh": "2NDfjgkQEJzGJBm49A1rydHDtd7eBhRoup5"
}
```

**Comment by coinables** [comment]
I'm trying to get the output of the redeemcript in hex format so that I could build a transaction using a tool such as coinb.in(https://coinb.in/#newTransaction).  The redeem script "630413fe305bb17567616800ac" does not trace back to the P2SH address.

**Comment by junderw** [comment]
@coinables 

coinb.in doesn't support any random redeemscript.

Here's an excerpt from their coinbin.js file:

As you can see, only a strict set of types of redeemscripts are supported.

```javascript
	/* function to determine what we are redeeming from */
	function redeemingFrom(string){
		var r = {};
		var decode = coinjs.addressDecode(string);
		if(decode.version == coinjs.pub){ // regular address
			r.addr = string;
			r.from = 'address';
			r.redeemscript = false;
		} else if (decode.version == coinjs.priv){ // wif key
			var a = coinjs.wif2address(string);
			r.addr = a['address'];
			r.from = 'wif';
			r.redeemscript = false;
		} else if (decode.version == coinjs.multisig){ // mulisig address
			r.addr = '';
			r.from = 'multisigAddress';
			r.redeemscript = false;
		} else if(decode.type == 'bech32'){
			r.addr = string;
			r.from = 'bech32';
			r.decodedRs = decode.redeemscript;
			r.redeemscript = true;
		} else {
			var script = coinjs.script();
			var decodeRs = script.decodeRedeemScript(string);
			if(decodeRs){ // redeem script
				r.addr = decodeRs['address'];
				r.from = 'redeemScript';
				r.decodedRs = decodeRs.redeemscript;
				r.redeemscript = true;
			} else { // something else
				r.addr = '';
				r.from = 'other';
				r.redeemscript = false;
			}
		}
		return r;
	}


		/* decode the redeemscript of a multisignature transaction */
		r.decodeRedeemScript = function(script){
			var r = false;
			try {
				var s = coinjs.script(Crypto.util.hexToBytes(script));
				if((s.chunks.length>=3) && s.chunks[s.chunks.length-1] == 174){//OP_CHECKMULTISIG
					r = {};
					r.signaturesRequired = s.chunks[0]-80;
					var pubkeys = [];
					for(var i=1;i<s.chunks.length-2;i++){
						pubkeys.push(Crypto.util.bytesToHex(s.chunks[i]));
					}
					r.pubkeys = pubkeys;
					var multi = coinjs.pubkeys2MultisigAddress(pubkeys, r.signaturesRequired);
					r.address = multi['address'];
					r.type = 'multisig__'; // using __ for now to differentiat from the other object .type == "multisig"
				} else if((s.chunks.length==2) && (s.buffer[0] == 0 && s.buffer[1] == 20)){ // SEGWIT
					r = {};
					r.type = "segwit__";
					var rs = Crypto.util.bytesToHex(s.buffer);
					r.address = coinjs.pubkey2address(rs, coinjs.multisig);
					r.redeemscript = rs;

				} else if(s.chunks.length == 5 && s.chunks[1] == 177 && s.chunks[2] == 117 && s.chunks[4] == 172){
					// ^ <unlocktime> OP_CHECKLOCKTIMEVERIFY OP_DROP <pubkey> OP_CHECKSIG ^
					r = {}
					r.pubkey = Crypto.util.bytesToHex(s.chunks[3]);
					r.checklocktimeverify = coinjs.bytesToNum(s.chunks[0].slice());
					r.address = coinjs.simpleHodlAddress(r.pubkey, r.checklocktimeverify).address;
					r.type = "hodl__";
				}
			} catch(e) {
				// console.log(e);
				r = false;
			}
			return r;
		}
```
