### ISSUE TITLE
Address generation is slow (BIP32)

### ISSUE THREAD

**Issue by silence-may** [bitcoinjs/bitcoinjs-lib#1110]
"bitcoinjs-lib": "^3.3.2"
excuse me :
I need to check the balance and transaction through the address. So I need to query the information of 20 addresses at a time(API:https://blockchain.info/multiaddr?active=$address|$address), but the generation address is very slow, which takes about 20 seconds. How can I improve efficiency?
 my way :
    1.first , Generate node  from m / purpose' / coin_type' / account'/change
    2.derivePath(0-20)
Please give me some advice ，Thanks a lot!

**Comment by dcousens** [comment]
@silence-may does https://github.com/bitcoinjs/bitcoinjs-lib/issues/1057#issuecomment-391577731 help you at all?

**Comment by dcousens** [comment]
> 1. Generate node from m / purpose' / coin_type' / account'/change
> 2. derivePath(0-20)

Probably use `derive`, not `derivePath`,  but, even then,  this is the generally advised (and efficient) algorithm that you are using.

I suspect your issue will go away with `4.0.0` being released __very soon__ (this week, or next).
As we are using `libsecp256k1` (native) and `bn.js` in that release,  and you can be assured they are nearly 10x as fast.

**Comment by silence-may** [comment]
Thank you for your answer and look forward to the release of the new version.

**Comment by junderw** [comment]
Very soon! We are just ironing out a few details.

**Comment by silence-may** [comment]
Hello, I see that the latest release is 4.0.1. Will the efficiency of this version be significantly improved? When can I install the latest version with npm?

**Comment by junderw** [comment]
1. Yes.
2. Soon, we just need to publish to npm.
