### ISSUE TITLE
Pay-to-OP_RETURN / P2OR / Null Data / P2ND

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#1115]
Any preference here?

We can remove the `templates*` exports near entirely if we add a payment type for this.

What do we call it?

``` js
let p2null = bitcoin.payments.p2null({
  data: [ // compatible with many data segments
    Buffer.from('deadbeef', 'hex')
  ]
}) 

console.log(bitcoin.script.toASM(p2null.output))
// OP_RETURN deadbeef
```

**Comment by junderw** [comment]
I think the example should be Buffer.from('Hello World!', 'utf8')

but that's just me... lol

`bitcoin.payments.embed` is a little more intuitive

**Comment by dcousens** [comment]
I like `.embed`

But the documentation uses "Null data", ref 
https://bitcoin.org/en/glossary/null-data-transaction
https://bitcoin.org/en/developer-guide#null-data

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bitcoinjs-lib/pull/1120

I went with `.p2data` for now???
