### ISSUE TITLE
lowest amount we can tranfer

### ISSUE THREAD

**Issue by rushabhmadhu18121987** [bitcoinjs/bitcoinjs-lib#1117]
Hello, Can you kindly provide the information. which is lowest amount of BTC we can send using this Node modules.  which api this module will use to transfer BTC from one address to another address

**Comment by dabura667** [comment]
?

Could you please rephrase your question?

**Comment by junderw** [comment]
The smallest output for standard transactions (transactions that are relayed by most nodes on the network) is "1/3 the amount of fees to be paid on a normal txOut and txIn combined at MIN_RELAY_TX_FEE"

However, currently MIN_RELAY_TX_FEE is liquid and can change if the mempool gets too full.

So for a normal P2PKH, that would be:

```javascript
var VARINT_ONEBYTE = 1
var OUT_SATOSHI_SIZE = 8
var OUT_SCRIPTPUBKEY_SIZE = 25 //(DUP, HASH160, PUSHDATA, 20bytes, EQUALVERIFY, CHECKSIG)

var IN_TXHASH_SIZE = 32
var IN_TXVOUT_SIZE = 4
var IN_SIG_SIZE = 73 // include pushbyte
var IN_PUBKEY_SIZE = 34 // include pushbyte
var IN_SEQUENCE_SIZE = 4

var TOTAL_IN_OUT_SIZE = OUT_SATOSHI_SIZE + VARINT_ONEBYTE + OUT_SCRIPTPUBKEY_SIZE + IN_TXHASH_SIZE + IN_TXVOUT_SIZE + VARINT_ONEBYTE + IN_SIG_SIZE + IN_PUBKEY_SIZE + IN_SEQUENCE_SIZE

var MIN_RELAY_TX_FEE = 1000

var MIN_OUT_AMOUNT = (TOTAL_IN_OUT_SIZE * 3) * MIN_RELAY_TX_FEE / 1000

// 546
```
Which means any output less than 546 satoshis will be non-standard.

But this is different for segwit P2WPKH:

```javascript
var VARINT_ONEBYTE = 1
var OUT_SATOSHI_SIZE = 8
var OUT_SCRIPTPUBKEY_SIZE = 22 //(OP_0, PUSHDATA, 20 bytes)

var IN_TXHASH_SIZE = 32
var IN_TXVOUT_SIZE = 4
var IN_SIG_SIZE = 73 // include pushbyte
var IN_PUBKEY_SIZE = 34 // include pushbyte
var IN_SEQUENCE_SIZE = 4

var TOTAL_IN_OUT_SIZE = OUT_SATOSHI_SIZE + VARINT_ONEBYTE + OUT_SCRIPTPUBKEY_SIZE + IN_TXHASH_SIZE + IN_TXVOUT_SIZE + VARINT_ONEBYTE + IN_SEQUENCE_SIZE + Math.ceil((VARINT_ONEBYTE + IN_SIG_SIZE + IN_PUBKEY_SIZE) / 4)

var MIN_RELAY_TX_FEE = 1000

var MIN_OUT_AMOUNT = (TOTAL_IN_OUT_SIZE * 3) * MIN_RELAY_TX_FEE / 1000

// 297
```

297 satoshi is the minimum for a raw P2WPKH output.

**Comment by junderw** [comment]
In general, most software plays it safe, and doesn't make outputs less than 1000 satoshis or so... just in case.

**Comment by dcousens** [comment]
Semi related to https://github.com/bitcoinjs/bitcoinjs-lib/issues/1123
