### ISSUE TITLE
Update CHANGELOG for 4.0.0

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#1121]

**Comment by sneurlax** [comment]
Hey, I'm using this library extensively and will also be forking it to accommodate Decred.  If you need any help in particular, please just @ and/or assign me.

I'm using the latest release currently but awaiting the next one with bated breath--I see some good changes coming.  If there's anything I can do to speed things up, I'd like to contribute.

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bitcoinjs-lib/pull/1130
