### ISSUE TITLE
Dust transaction error

### ISSUE THREAD

**Issue by l0n3w0lf93** [bitcoinjs/bitcoinjs-lib#1123]
When i create a bitcoin transaction ( value:20000 sts, fee: 4000sts) by bitcoinjs-lib, i broadcast rawTX  via (https://www.blockchain.com/en/btc/pushtx, https://live.blockcypher.com/btc/pushtx/  etc ) . But its notify that "dusty". What does this mean? What should me do to broadcast my transaction? Thanks

**Comment by l0n3w0lf93** [comment]
thanks for your answer. So what can I do to broadcast this rawTx? I seen a same transaction but it was confirmed by nodes ( 
https://www.blockchain.com/btc/tx/54a12adcafedc541fd7d4812a33be6dc32b3fc13f3c1058d239cfae72390f2cd )

**Comment by dcousens** [comment]
@l0n3w0lf93 either increase the amounts involved,  or relay it through someone with a lower dust policy (and hope they are 'well connected').

**Comment by dabura667** [comment]
How large was your change output?

**Comment by l0n3w0lf93** [comment]
@dabura667  its about 20000 sts

**Comment by dabura667** [comment]
@l0n3w0lf93 so the transaction looked like:

1. one output definitely 20000 sats
2. a second output for change that's around 20000 sats (ish)

in that case, it should not be dusty by bitcoin standards...

could you paste the raw transaction?

**Comment by l0n3w0lf93** [comment]
@dabura667 
{
    "addresses": [
        "1F8VpBnQ6TYeTYRVFx3SoCgkUJ3TQd7SnV", 
        "15onULVhQcpBVTg1Yh2vxgJmx8BLssQoJQ"
    ], 
    "block_height": -1, 
    "block_index": -1, 
    "confirmations": 0, 
    "double_spend": false, 
    "fees": 9700, 
    "hash": "52ceb56566acd9bad7ac22c2989735a90c3f3c5ff86d36bc85ddf5ffe8bc9b91", 
    "inputs": [
        {
            "addresses": [
                "1F8VpBnQ6TYeTYRVFx3SoCgkUJ3TQd7SnV"
            ], 
            "age": 527552, 
            "output_index": 0, 
            "output_value": 20000, 
            "prev_hash": "54a12adcafedc541fd7d4812a33be6dc32b3fc13f3c1058d239cfae72390f2cd", 
            "script": "48304502210093b92f1513af5b4648b0c331d1e047c97cb9f9d0154ec6cf54326e67bed7214c02203bcdc17e0f7df707b74978f70e9dab438105a2ec2ffa9dd7d54ee2d2e059d86a0121035d84e52b2fe955f63f1f89ce199d520c919abd9f05d947ba7ad469ec2e9347c1", 
            "script_type": "pay-to-pubkey-hash", 
            "sequence": 4294967295
        }, 
        {
            "addresses": [
                "1F8VpBnQ6TYeTYRVFx3SoCgkUJ3TQd7SnV"
            ], 
            "age": 527223, 
            "output_index": 0, 
            "output_value": 15000, 
            "prev_hash": "0ed6a36cbb187d8d355f7d4d2bde508df9b26f35e997b9848914ca47fbd3844a", 
            "script": "47304402201129a6aa6b42ea3336ade5872d5aea504350b20bbb7f4c6fcbccdfb6d3a519c50220778243fc48c2d893c4a76acf91c4851114a420e42c43885072340d8acd3541d20121035d84e52b2fe955f63f1f89ce199d520c919abd9f05d947ba7ad469ec2e9347c1", 
            "script_type": "pay-to-pubkey-hash", 
            "sequence": 4294967295
        }, 
        {
            "addresses": [
                "1F8VpBnQ6TYeTYRVFx3SoCgkUJ3TQd7SnV"
            ], 
            "age": 527222, 
            "output_index": 0, 
            "output_value": 10000, 
            "prev_hash": "ffefd23696f58a2414d1757504d87bb2f7e936ec510d283e6595ee3c4aef7d97", 
            "script": "473044022030f8f61f4a995325a6cb0f045f69f1f3e7df8599b5c76d2f2b5fafce711b920f02204035e30c8cdac75dcedef1abb84dd783364b0cde49cb23b34ac6997542fe68030121035d84e52b2fe955f63f1f89ce199d520c919abd9f05d947ba7ad469ec2e9347c1", 
            "script_type": "pay-to-pubkey-hash", 
            "sequence": 4294967295
        }
    ], 
    "outputs": [
        {
            "addresses": [
                "15onULVhQcpBVTg1Yh2vxgJmx8BLssQoJQ"
            ], 
            "script": "76a91434b9984c8277fd64f9601dddf356433a8135ac7288ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 35300
        }, 
        {
            "addresses": [
                "1F8VpBnQ6TYeTYRVFx3SoCgkUJ3TQd7SnV"
            ], 
            "script": "76a9149afcb99c9a3f8506079d2fb95d74c802fdf4ca8188ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 0
        }
    ], 
    "preference": "medium", 
    "received": "2018-07-10T02:35:04.614655935Z", 
    "relayed_by": "54.91.66.218", 
    "size": 520, 
    "total": 35300, 
    "ver": 1, 
    "vin_sz": 3, 
    "vout_sz": 2
}
Can you help me?

**Comment by MindFy** [comment]
@l0n3w0lf93 remove vout[1]，{
      "value": 0.00000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 9afcb99c9a3f8506079d2fb95d74c802fdf4ca81 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9149afcb99c9a3f8506079d2fb95d74c802fdf4ca8188ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "mueT7EsNuUyuEeu6yX1pd7u5LHeAF17u5i"
        ]
      }
    }

**Comment by junderw** [comment]
Yeah, the second output is 0, which is less than 546, so it's dust.

If you get rid of the second output, your fees are about 20 satoshis/byte... whereas if you keep the second output and give yourself some change above the dust limit you'll be at about 17 satoshis/byte or less...

Since right now 5 satoshis/byte seems reasonable, I would say maybe give yourself 7000 satoshis in change to your second output should be fine.
