### ISSUE TITLE
Cannot parse dogecoin transactions with large values

### ISSUE THREAD

**Issue by karel-3d** [bitcoinjs/bitcoinjs-lib#1126]
This library cannot parse dogecoin transactions with large values

Example

https://dogechain.info/tx/448c11f653c9f9da4d468174f6ff9af024ce537e847e1f545fbaaa5cecb4b5d1

(raw transaction here - https://gist.github.com/karel-3d/55da54d09c09c546cfa7ebdb3383bb8a )

The problem is the amounts in dogecoin are large. The last input in doge is 1,132,715,439.96020007 doge

**Comment by karel-3d** [comment]
Hm, it seems this is unsolvable without completely rewriting amount types, since javascript ints are maximally 2^53-1. OK, closing this.

**Comment by dcousens** [comment]
@karel-3d we aren't adverse to accept `valueBuffer`,  but,  the problem we found before,  is that it will completely throw off `bitcoin` network users if they get a malformed transaction,  and `value` is undefined.
