### ISSUE TITLE
Do we need to specify the network for WIF private keys derived via BIP32 and BIP39?

### ISSUE THREAD

**Issue by sneurlax** [bitcoinjs/bitcoinjs-lib#1136]
Hi, I'm using BIP39 mnemonics to derive addresses via BIP32 as in:

```
      let seed = bip39.mnemonicToSeed(seed, (passphrase) ? passphrase : undefined);
      let root = bip32.fromSeed(seed);
      let node = root.derivePath(`m/${purpose}'/${network}'/${account}'/${change}/${index}`);
      let privateKey = node.toWIF();
      return privateKey;
```

Do I need to specify a network or purpose, or is that accounted-for in the path?

Thanks!

**Comment by dcousens** [comment]
https://github.com/bitcoinjs/bip32/blob/4a08cb91a7772297844dc2136ec6acf130eb5f3b/index.js#L283

> function fromSeed (seed, network) {

Note,  the `network` parameter.

**Comment by sneurlax** [comment]
OK, I will note that if you use `fromSeed` (intending) to generate a testnet seed without the `network` parameter and then `ECPair.fromWIF()` with the `testnet` network passed in, `fromWIF()` will silently fail.

**Comment by dabura667** [comment]
`ECPair.fromWIF()` doesn't need network. the network info is encoded in the WIF key.

**Comment by sneurlax** [comment]
Then I must be doing something wrong, because my code silently fails if I don't provide `fromWIF()` with a `network` object.

**Comment by dabura667** [comment]
If you don't pass network, it defaults to bitcoin mainnet. There should be no silent failure.

If it's silent it should be a bitcoin mainnet ECPair.

What do you mean by "fails"? is the expected object container for the ECPair undefined?

```javascript
function fromWIF (string, network) {
  const decoded = wif.decode(string)
  const version = decoded.version

  // list of networks?
  if (types.Array(network)) {
    network = network.filter(function (x) {
      return version === x.wif
    }).pop()

    if (!network) throw new Error('Unknown network version')

  // otherwise, assume a network object (or default to bitcoin)
  } else {
    network = network || NETWORKS.bitcoin

    if (version !== network.wif) throw new Error('Invalid network version')
  }

  return fromPrivateKey(decoded.privateKey, {
    compressed: decoded.compressed,
    network: network
  })
}
```

**Comment by dabura667** [comment]
If you pass a testnet WIF without a network, this error will throw:

`if (version !== network.wif) throw new Error('Invalid network version')`

**Comment by sneurlax** [comment]
By "fails silently," I mean my app runs until that line--but no further--with no errors given in the console.  No `Invalid network version`, no warning that there isn't a `wif` property (on a nonexistent object,) zip, zilch, nada.  It just silently fails.

**Comment by dabura667** [comment]
> my app

Without looking at your app, I can't say...

Any hints? What version of node? Or is it being browserified? Is your app using webpack? React.js? some weird new hip edgy library some old fart like me has never even heard of? what version? is it on github? where at?

etc. etc.

I'd be glad to take a look if you give us a little more info.

If you'd like to insist that it's something wrong with bitcoinjs-lib, then I can't help you... fromWIF is a very simple function, and there's really no space for a bug to find its way in there from what I can tell. But then of course I'm stupid.

The only thing I could think of is a compatibility issue with some external package / runtime.

**Comment by dabura667** [comment]
I've seen apps that run everything in a giant try statement and do nothing with the catch statement...

an app like that, for instance, would obviously not ever throw an error ever.

**Comment by sneurlax** [comment]
Yeah, I realize there are a lot of factors that weigh in.  Thank you for all of your attention up to this point.  If I were asserting a bug with bitcoinjs-lib itself, I'd report it in a reproducible format... and if I can reproduce it then I can understand it, and at that point the report would come with a pull request fixing it.  

You're right, I haven't done my due diligence to reproducibly identify that the silent failure is due to bitcoinjs-lib.  I'll show code once I clean up my spaghetti mess (I've sprinted from zero to a mostly-functioning wallet in just under a month at this point.)
