### ISSUE TITLE
HDnode BIP49

### ISSUE THREAD

**Issue by imediabiz** [bitcoinjs/bitcoinjs-lib#1137]
How do I able to generate Segwit Address from ypub key on 4.0.0 since its has been removed? 

We cannot use this solution anymore?

`Bitcoin.HDNode.fromBase58('ypub6XMTwf6NSvfzYYgVgdNWRNfMTiQt4rSjZbEk8qoCnBGhUD2rsgZ2A8pexgzaGLKgySZxqxrctDpAVU8QtfxqfX8QUAhtFmGFUFx9B51TVg8', Bitcoin.networks.bitcoin)
    .derive(0)
    .derive(27)
    .getAddress()`

**Comment by dcousens** [comment]
@imediabiz you mention `getAddress` above,  but then said "Segwit Address",  which is it?

**Comment by imediabiz** [comment]
I mean how to generate 3 address just using ypub key without need to given private key?

**Comment by dcousens** [comment]
@imediabiz `3` address, do you mean, 3 addresses? or a P2SH address?

**Comment by imediabiz** [comment]
P2SH address. Thanks

**Comment by dcousens** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/d67e9758c72e587083e2d05fa802e02c76ca99ca/test/integration/addresses.js#L67-L74

**Comment by dcousens** [comment]
A BIP49 example is provided in the README

https://github.com/bitcoinjs/bitcoinjs-lib/blob/d67e9758c72e587083e2d05fa802e02c76ca99ca/test/integration/bip32.js#L71-L84

**Comment by imediabiz** [comment]
I don't want to share any mnemonic or seed to anyone. I just want to share ypub information to generate the address

**Comment by dcousens** [comment]
@imediabiz then change `child` to be a `bip32` node using `fromBase58`.

Aka

``` js
const node = bitcoin.bip32.fromBase58('ypub6XMTwf6NSvfzYYgVgdNWRNfMTiQt4rSjZbEk8qoCnBGhUD2rsgZ2A8pexgzaGLKgySZxqxrctDpAVU8QtfxqfX8QUAhtFmGFUFx9B51TVg8', bitcoin.networks.bitcoin)
```

**Comment by dcousens** [comment]
@imediabiz you should be able to discern how to combine the above code with your existing approach (aka, using a `bip32` node from `fromBase58`).
If any part isn't clear,  let us know.

**Comment by imediabiz** [comment]
Your suggestion it does not work @dcousens. Thanks

**Comment by imediabiz** [comment]
> bitcoin.bip32.fromBase58('ypub6XMTwf6NSvfzYYgVgdNWRNfMTiQt4rSjZbEk8qoCnBGhUD2rsgZ2A8pexgzaGLKgySZxqxrctDpAVU8QtfxqfX8QUAhtFmGFUFx9B51TVg8', bitcoin.networks.bitcoin).derive(0).derive(27).getAddress()
TypeError: Invalid network version

**Comment by dcousens** [comment]
@imediabiz that is because `ypub` is not a valid network version.
How have you been using it previously?

**Comment by imediabiz** [comment]
Its broken since i was upgraded to 4.0.0

**Comment by dcousens** [comment]
@junderw did we support `ypub`??

**Comment by junderw** [comment]
@dcousens no...

we don't have `bitcoin.bip32` in our repo... soooo I'm guessing `bitcoin` is some custom thing they made? Maybe they tagged bip32 object onto the bitcoinjs-lib object...

Without seeing what their bitcoin.networks.bitcoin is...

sounds like maybe this is the problem: https://xkcd.com/1172/

**Comment by imediabiz** [comment]
Do you have any ideas about bitcoin.bip32.keyPair ? @junderw

**Comment by dcousens** [comment]
@imediabiz you don't need `.keyPair` for `bitcoin.bip32` (@junderw `bitcoin.bip32` is `4.0.0`),  you can simply use the object as-is.
