### ISSUE TITLE
Continuous integration testing with browsers

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#1138]
@fanatid I noticed you appear to have a nice browser testing setup in https://github.com/cryptocoinjs/secp256k1-node that you have set up using `karma`.

What is your experience there?
Is it something we could roll-out to all of the `bitcoinjs` dependencies/libraries easily?

Is it possible to target problematic browsers like Safari etc?

**Comment by fanatid** [comment]
It was 2 years ago and I not used `karma` form that time :)
Maybe world have something better right now.
