### ISSUE TITLE
BIP49 cannot sign -  Inconsistent network

### ISSUE THREAD

**Issue by imediabiz** [bitcoinjs/bitcoinjs-lib#1141]
const path = "m/49'/0'/0'/0/0"
const child = root.derivePath(path)

const p2wpkh = bitcoin.payments.p2wpkh({ pubkey: child.publicKey })
const p2sh = bitcoin.payments.p2sh({ redeem: p2wpkh })

console.log(bitcoin.payments.p2sh({redeem: bitcoin.payments.p2wpkh({ pubkey: root.derivePath("m/49'/0'/0'/0/0").publicKey }) }).address )
console.log(p2sh.address)

const txb = new bitcoin.TransactionBuilder()
  txb.addInput('b5d9ac60895038d570bdea2e2e4f6c069f1a2ab0b82c5b9f0b228a8c1bfd9f64', 1)
  txb.addOutput("3GB8jS8QGutd6bJWuSb3gF1WULf2Ut55KA", 18726)

>   txb.sign(0, child, p2sh.redeem.output)
TypeError: Inconsistent network
    at TransactionBuilder.sign (/Users/budiyuwono/node_modules/bitcoinjs-lib/src/transaction_builder.js:628:66)

**Comment by gavinwyf** [comment]
I have the same question.

**Comment by gavinwyf** [comment]
When version 4.x.x  updated

**Comment by sneurlax** [comment]
Have you tried passing a network explicitly?

**Comment by sneurlax** [comment]
After working through this myself, I can confirm that you need to pass a `network` parameter in multiple places (in `bitcoin.payments` methods as well as to the `TransactionBuilder()`).  Try this (haven't run it, but it should work:)

```
const path = "m/49'/0'/0'/0/0"
const child = root.derivePath(path)
const network = bitcoin.networks.bitcoin

const p2wpkh = bitcoin.payments.p2wpkh({ pubkey: child.publicKey, network: network })
const p2sh = bitcoin.payments.p2sh({ redeem: p2wpkh, network: network })

const txb = new bitcoin.TransactionBuilder(network)
txb.addInput('b5d9ac60895038d570bdea2e2e4f6c069f1a2ab0b82c5b9f0b228a8c1bfd9f64', 1)
txb.addOutput('3GB8jS8QGutd6bJWuSb3gF1WULf2Ut55KA', 18726)
```

**Comment by dabura667** [comment]
1. `child` has a network attribute. You pass it when you do something like `fromBase58('xprv....')` and xprv will contain the bitcoin mainnet network information.
2. TransactionBuilder contains a network attribute. You pass it into `new bitcoin.TransactionBuilder(network)`

Those two networks must match. You did not make them match. That is your problem.

You are deriving an Acoin private key but creating a Bcoin TransactionBuilder, so it is telling you "Why are you trying to sign with a different coin's private key?"

Also, you need to pass the input amount to txb.sign.

**Comment by dabura667** [comment]
Since TransactionBuilder is default Bitcoin Mainnet I assume your `child` object was created with a non-bitcoin network. maybe testnet?

**Comment by dcousens** [comment]
`TransactionBuilder.prototype.addOutput` if used with an address,  will use the network provided to the constructor.
If none is provided,  `bitcoin` is assumed.
