### ISSUE TITLE
Classify is not Exported after Templates Export was removed

### ISSUE THREAD

**Issue by OstlerDev** [bitcoinjs/bitcoinjs-lib#1148]
Hello!

Inside of my library I was using the `templates` classes that were being exported/attached onto the `scripts` export, however in a recent commit, `templates` stopped being exported in favor of moving to a new `classify` class (https://github.com/bitcoinjs/bitcoinjs-lib/commit/6cacea6f31aa18cce61bed562d730c55ac3709d3#diff-1fdf421c05c1140f6d71444ea2b27638L2).

It would be great if `classify` could be exported so that I could access/use the new `classify.output` and `classify.input` functions.

I will make a pull request that fixes this issue by adding back in the export that was removed.

Thanks!
Sky Young

**Comment by dcousens** [comment]
Indeed!
We spoke about this at length in https://github.com/bitcoinjs/bitcoinjs-lib/issues/899.
It'd be great to hear your usage @OstlerDev :+1: .

The tl;dr is that classification of inputs is hit and miss,  and may lead to a false sense of security.
Output classification is less of an issue.

We didn't expose `classify` to try and determine if there were better abstractions available,  but I do appreciate you opening the issue so soon after the release :+1:

**Comment by dcousens** [comment]
@OstlerDev if you have any feedback to give,  please do.

We don't want users reverting to older versions if they truly need a feature.

**Comment by OstlerDev** [comment]
My apologies for being absent from this thread, here is some info on the reason I was using the classify import.

I use `bitcoinjs-lib` in my BIP44 wallet to create transactions for multiple different coin versions. As I was attempting to add support for an Altcoin that adds extra data to the end of the Transaction Hex, I ended up needing to modify the Transaction Signature Hash generation functions so that my transactions would be properly signed with the extra hex data appended. [This workaround caused me to copy over a bunch of code from the TransactionBuilder](https://github.com/oipwg/oip-hdmw/blob/master/src/TransactionBuilderHelpers.js), which then forced me to import `classify`.

In thinking more, it isn't likely the best (or a great) solution to export classify to fix my use case. 

It might instead be better to add an option to transaction builder that allows a function to be passed that will modify the generated transaction hex BEFORE it gets used for signatures, or returned from a `.build().toHex()`.

The added option could function something like this maybe:
```js
/**
 * This function should be run in order to modify regular Bitcoin transaction hex into the custom transaction hex for the specific Altcoin
 * @param  {Buffer} built_hex - The transaction hex Buffer built by `bitcoinjs-lib`
 * @return {Buffer} Returns the modified transaction hex Buffer in the Alt-coins format.
 */
var modify_tx_hex = function(built_hex){
	// Do whatever work is needed to modify the tx_hex to be exactly as the alt-coin needs.

	// In this case, the modification is appending extra data to the end of the 
	// regular transaction hex.
	let my_extra_hex = Buffer.from("my extra data", "utf8")
	let my_altcoin_hex = Buffer.concat([built_hex, my_extra_hex])

	// Return the modified hex specific to the Altcoin.
	return my_altcoin_hex
}

// Build a transaction using the custom `modify_tx_hex` function
var tx_builder = new bitcoin.TransactionBuilder(custom_coin_network, undefined, modify_tx_hex)

tx_builder.setVersion(custom_coin_version)

tx_builder.addInput(input.txId, input.vout)
tx_builder.addOutput(output.address, output.value)

// Should use the modified hex inside the `hashForSignature` function
tx_builder.sign(0, alice)

// Should return the hex AFTER it was modified by the function
tx_builder.build().toHex()
```

What would you think about adding functionality like that? Adding this functionality would remove my need to use the `classify` export, as well as the messy code duplication I have done right now.

**Comment by dcousens** [comment]
Are you saying you merely want to change what `Transaction.prototype.toBuffer` returns?  Or what is used in the hash functions there? (hashV0 etc)

**Comment by OstlerDev** [comment]
@dcousens I believe the change would need to take place in both `Transaction.prototype.toBuffer` and in `hashForWitnessV0` as well. It would be needed in `hashForWitnessV0` so that Segwit transactions could also have the signed modified hex.

I can make those changes and send in a pull request if you want.

**Comment by dcousens** [comment]
@OstlerDev why not monkey patch them for your usage only?

**Comment by OstlerDev** [comment]
@dcousens If this feature is outside the scope of the `bitcoinjs-lib` project, I absolutely understand, and I will monkey patch them for my usage only. 

I just figured that it would be best to be able to use the main stable branch for my application, since it will manage funds for many people, and so I thought I would see if this might be a feature that could be added to the main project.

**Comment by dcousens** [comment]
@OstlerDev overriding that one prototype shouldn't prevent you from using the main release.

But,  as it stands,  your feature is very specific to an altcoin and doesn't really benefit the library.   It becomes an unnecessary testing burden for us.

**Comment by OstlerDev** [comment]
No worries, I totally understand. I will just do as you said and override that single prototype 👍 

Thank you for all you do on this project!

**Comment by dcousens** [comment]
@OstlerDev please don't hesitate to put your code here for others.
