### ISSUE TITLE
Can't sign P2SH(P2WPKH) transaction built with CoinSelect and TransactionBuilder not working

### ISSUE THREAD

**Issue by majestic84** [bitcoinjs/bitcoinjs-lib#1154]
I am trying to build a transaction and everything seems to be working well up until the point where I sign the transaction. I keep getting "scripthash not supported" but I am not sure what I am doing wrong. I followed the example from here https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L143 closely, with the main difference being that I am using CoinSelect to choose the utxos for me. I've posted my code below, any help would be greatly appreciated :)

`const bitcoin = require('bitcoinjs-lib')
            let network = bitcoin.networks.bitcoin

            const getUtxos =
                util
                    .promisify(this.network.provider.insight.getUtxos)
                    .bind(this.network.provider.insight)
            const utxos = await to(
                getUtxos({addresses: from, minconf: this.network.provider.minConf})
            )

            if (utxos.data.length === 0)
                return({success: false, error: `No confirmed unspent transactions found: ${from}`})

            let jsonUtxos = []
            utxos.data.forEach(utxo => {
                let jsonUtxo = utxo.toJSON()
                jsonUtxo.value = utxo.satoshis
                jsonUtxos.push(jsonUtxo)
            })

            let keyPair = bitcoin.ECPair.fromWIF(key, network)
            const p2wpkh = bitcoin.payments.p2wpkh({ pubkey: keyPair.publicKey, network })
            const p2sh = bitcoin.payments.p2sh({ redeem: p2wpkh, network })

            let amountInSatoshis = this.network.provider.bitcore.Unit.fromBTC(amount).toSatoshis()

            let coinSelect = require('coinselect')
            let feeRate = 110

            let targets = [{
                    address: _to,
                    value: amountInSatoshis
                }]

            let { inputs, outputs, fee} = coinSelect(jsonUtxos, targets, feeRate)
            if (!inputs || !outputs) return

            let txb = new bitcoin.TransactionBuilder(network)

            inputs.forEach(input => txb.addInput(input.txid, input.vout))
            outputs.forEach(output => {
                if (!output.address) {
                    output.address = from
                }
                txb.addOutput(output.address, output.value)
            })

            txb.sign(0, keyPair, p2sh.redeem.output, null, inputs.value) // <-- scripthash not supported
            
            const tx = txb.build()
            const txid = tx.toHex()`

**Comment by dabura667** [comment]
check p2sh right before sign and show me its contents.

the error you describe would only happen if `p2sh.redeem.output` was a p2sh output and not the redeemscript itself.

**Comment by majestic84** [comment]
Thanks for the quick response. Here's the output of p2sh just before signing.  This attempt is with a Litecoin transaction. Same code as above, but with the valid network parameters for Litecoin Testnet:

```
{ network:
   { messagePrefix: '\u0019Litecoin Signed Message:\n',
     bip32: { public: 70711009, private: 70709117 },
     pubKeyHash: 111,
     scriptHash: 58,
     wif: 239 },
  address: [Getter/Setter],
  hash: [Getter/Setter],
  output: [Getter/Setter],
  redeem:
   { network:
      { messagePrefix: '\u0019Litecoin Signed Message:\n',
        bip32: [Object],
        pubKeyHash: 111,
        scriptHash: 58,
        wif: 239 },
     address: [Getter/Setter],
     hash: <Buffer 69 05 44 d3 2c b7 f0 64 cb ee ae a5 1e af 50 69 b9 f2 4d b2>,
     output: <Buffer 00 14 69 05 44 d3 2c b7 f0 64 cb ee ae a5 1e af 50 69 b9 f2 4d b2>,
     pubkey: <Buffer 03 3e 1b 4c 0b 3d 9f e1 20 3a b0 79 51 e1 be 81 30 82 86 96 86 87 f7 a8 36 87 9c 0d 6e 17 31 e4 23>,
     signature: [Getter/Setter],
     input: undefined,
     witness: undefined },
  input: [Getter/Setter],
  witness: [Getter/Setter] }
```
So p2sh.redeem.output here is a buffer containing `00 14 69 05 44 d3 2c b7 f0 64 cb ee ae a5 1e af 50 69 b9 f2 4d b2`

**Comment by dabura667** [comment]
The only thing I can think of as a pot hole you could be falling into is some sort of scope problem with your variables...

Perhaps keyPair, even though you use it to create p2sh there, is a different key than p2sh...

https://github.com/bitcoinjs/bitcoinjs-lib/blob/d67e9758c72e587083e2d05fa802e02c76ca99ca/src/transaction_builder.js#L187

This seems like the only place in the flow of logic where you would fall through.

basically it grabs the hash from your redeemScript (the last 20 bytes) and hash160s your keyPair object again and compares... if they're not equal it doesn't return a pubkeys attribute, then this error triggers:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/d67e9758c72e587083e2d05fa802e02c76ca99ca/src/transaction_builder.js#L269

expanded is the result returned when those two values aren't correct, and the error is thrown when the pubkeys attribute isn't there.

But it says scripthash... so it looks like it's classifying your redeemScript as a p2sh output instead of a p2wpkh output...

could you inspect the script object right before classification here:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/d67e9758c72e587083e2d05fa802e02c76ca99ca/src/transaction_builder.js#L163

and tell me what it says?

**Comment by majestic84** [comment]
The value of script just before classify.output(script) is `<Buffer 00 14 69 05 44 d3 2c b7 f0 64 cb ee ae a5 1e af 50 69 b9 f2 4d b2>`

**Comment by dabura667** [comment]
> the value of "type" just after it is witnesspubkeyhash

That makes no sense... the only error in the whole library that is of the format `scripthash not supported` would be if that classification in that function gave "scripthash"

> is it possible my "ins" are malformed?

No, they're fine. the code you showed us only uses txid and vout etc. so anything about the formatting of the code in the upper half is irrelevant.

what are the values of `wpkh1` and `wpkh2` a few lines down?

**Comment by majestic84** [comment]
```
Error: scripthash not supported
    at TransactionBuilder.sign (C:\Node\ltc\node_modules\bitcoinjs-lib\src\transaction_builder.js:672:32)
    at send (C:\Node\ltc\tx.js:66:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Of course, now I've modified transaction_builder.js, so line 672 there is just this line:
`if (!canSign(input)) throw Error(input.prevOutType + ' not supported')`

**Comment by dabura667** [comment]
What is the input object just before that line?

**Comment by dabura667** [comment]
canSign might give us some hints if we know what the input is.
```javascript
function canSign (input) {
  return input.signScript !== undefined &&
    input.signType !== undefined &&
    input.pubkeys !== undefined &&
    input.signatures !== undefined &&
    input.signatures.length === input.pubkeys.length &&
    input.pubkeys.length > 0 &&
    (
      input.hasWitness === false ||
      input.value !== undefined
    )
}
```

**Comment by majestic84** [comment]
```
{ redeemScript: <Buffer 00 14 69 05 44 d3 2c b7 f0 64 cb ee ae a5 1e af 50 69 b9 f2 4d b2>,
  redeemScriptType: 'witnesspubkeyhash',
  prevOutType: 'scripthash',
  prevOutScript: <Buffer a9 14 47 4d 4a 55 4d 32 b8 65 fb de 4b e1 09 ec 9a 20 db 6d 78 1d 87>,
  hasWitness: true,
  signScript: <Buffer 76 a9 14 69 05 44 d3 2c b7 f0 64 cb ee ae a5 1e af 50 69 b9 f2 4d b2 88 ac>,
  signType: 'witnesspubkeyhash',
  pubkeys:
   [ <Buffer 03 3e 1b 4c 0b 3d 9f e1 20 3a b0 79 51 e1 be 81 30 82 86 96 86 87 f7 a8 36 87 9c 0d 6e 17 31 e4 23> ],
  signatures: [ undefined ] }
```

So here it's clear that the error is being thrown because the prevOutType is "scripthash", but I can't figure out why.

**Comment by dabura667** [comment]
input is missing value

that's why.

**Comment by dabura667** [comment]
prevOutType is P2SH, that is correct.

**Comment by dabura667** [comment]
check the input a bunch of places and see where the input loses input.value...

Maybe insight is giving a bad value for inputs.value???


shouldn't it be inputs[0].value?

**Comment by majestic84** [comment]
Wow that's all it was. I cannot thank you enough!

**Comment by majestic84** [comment]
If I do this it seems to work:
```
txb.sign(0, keyPair, p2sh.redeem.output, null, inputs[0].value)
txb.sign(1, keyPair, p2sh.redeem.output, null, inputs[1].value)
```
I could handle this with a loop of course, but is correct to sign for each UTXO input like this?

**Comment by dabura667** [comment]
yes. you must loop over the inputs.
