### ISSUE TITLE
bitcoin.payments is undefined in version 3.3.2.

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1155]
Hi. We are told to install bitcoinjs-lib using "npm install bitcoinjs-lib". This installs 3.3.2 version.

In that version there is no bitcoin.payments which is used in the test examples.

What version should I use and where can I find examples compatible with that version? Thanks.
For what version are the examples coded?

**Comment by dcousens** [comment]
@educob are you doing `npm install bitcoinjs-lib` in a folder that already has that library installed?
Otherwise it _should_ install latest.

**Comment by educob** [comment]
You are right. I deleted the folder and reinstall from scratch (after removing the entry in package.json and it installed 4.0.1.

Thanks.
