### ISSUE TITLE
windows install error

### ISSUE THREAD

**Issue by Luncher** [bitcoinjs/bitcoinjs-lib#1157]
when i run` npm install bitcoinjs-lib`

c:\users\叔叔左左\webstormprojects\untitled4\node_modules\nan\nan.h(24): fatal error C1083: 无法打开包括文件: “node_version.h”: No such file or directory

**Comment by junderw** [comment]
Please install the proper build tools.

https://github.com/nodejs/node-gyp#on-windows

**Comment by junderw** [comment]
Also, please use node v8 for best results.

**Comment by dcousens** [comment]
@Luncher please let us know if your problem is **not** resolved with that.
