### ISSUE TITLE
hdNode.keyPair.getPublicKeyBuffer() undefined

### ISSUE THREAD

**Issue by Incuboazaz** [bitcoinjs/bitcoinjs-lib#1158]
Hi all, 
I'm new here so forgive me :)
I've used the following to derive YPUB -> XPUB -> addresses:

```
xpub = ypubToXpub( " YPUB ");

var hdNode = bjs.HDNode.fromBase58(xpub);

nodeToP2shSegwitAddress(hdNode.derive(" yada yada ").derive( " bla bla " ));

function nodeToP2shSegwitAddress(hdNode) {
    var pubkeyBuf = hdNode.keyPair.getPublicKeyBuffer();
    var hash = bjs.crypto.hash160(pubkeyBuf);
    var redeemScript = bjs.script.witnessPubKeyHash.output.encode(hash);
    var hash2 = bjs.crypto.hash160(redeemScript);
    var scriptPubkey = bjs.script.scriptHash.output.encode(hash2);
    return bjs.address.fromOutputScript(scriptPubkey);
}
```

Now, after HDNode was removed I've tried:

``` 
var hdNode = bjs.bip32.fromBase58(xpub);
```
But `var pubkeyBuf = hdNode.keyPair.getPublicKeyBuffer();` throws keyPair is undefined.

What am I missing?
Thanks!

**Comment by dcousens** [comment]
@Incuboazaz try

``` js
let pubKeyBuf = hdNode.publicKey
```

Please let me know if we need to add/explain anything extra in the CHANGELOG.

**Comment by Incuboazaz** [comment]
@dcousens Thank you.

It did work, but now
`var redeemScript = bjs.script.witnessPubKeyHash.output.encode(hash);`
throws that witnessPubKeyHash is undefined.
I also expect that
`var scriptPubkey = bjs.script.scriptHash.output.encode(hash2);`
will throw the scriptHash is undefined.
Any suggestions? 

I think there is room to explain these changes in the CHANGELOG, but it's hard to be sure since I'm new to this type of programming.

**Comment by dcousens** [comment]
Please read the CHANGELOG for `4.0.0`.

> Removed script.*.input/output/check functions (templates) (previously added in #681, #682) (#1119)

**Comment by Incuboazaz** [comment]
I've read it, but not sure what can be done instead, now that they are removed.

**Comment by dcousens** [comment]
@Incuboazaz please see https://github.com/bitcoinjs/bitcoinjs-lib/pull/1160
