### ISSUE TITLE
Failed to minify the code from this file: ./node_modules/bitcoinjs-lib/src/script.js:57

### ISSUE THREAD

**Issue by harrysolovay** [bitcoinjs/bitcoinjs-lib#1159]
I believe this is more related to [an issue](https://github.com/facebook/create-react-app/issues/3734) with [create-react-app](https://github.com/facebook/create-react-app). Still, I wanted to file this issue incase the team has a solution that doesn't involve moving the bitcoinsjs-lib library outside of node_modules. Any suggestions would be appreciated! Sorry in advance if this isn't your domain or if there's a simple solution I'm missing. The bug: attempting "npm run build" results in the following error:

<img width="487" alt="screen shot 2018-08-02 at 5 17 50 pm" src="https://user-images.githubusercontent.com/4893548/43611713-0ab7fd6a-9678-11e8-859d-40cb187bfccd.png">

Here is the npm log:

`

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/Cellar/node/9.10.0_1/bin/node',
    1 verbose cli   '/usr/local/bin/npm',
    1 verbose cli   'run',
    1 verbose cli   'build' ]
    2 info using npm@6.1.0
    3 info using node@v10.6.0
    4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
    5 info lifecycle making-a-template@0.1.0~prebuild: making-a-template@0.1.0
    6 info lifecycle making-a-template@0.1.0~build: making-a-template@0.1.0
    7 verbose lifecycle making-a-template@0.1.0~build: unsafe-perm in lifecycle true
    8 verbose lifecycle making-a-template@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/harrysolovay/Desktop/making-a-template/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    9 verbose lifecycle making-a-template@0.1.0~build: CWD: /Users/harrysolovay/Desktop/making-a-template
    10 silly lifecycle making-a-template@0.1.0~build: Args: [ '-c', 'react-app-rewired build' ]
    11 silly lifecycle making-a-template@0.1.0~build: Returned: code: 1  signal: null
    12 info lifecycle making-a-template@0.1.0~build: Failed to exec build script
    13 verbose stack Error: making-a-template@0.1.0 build: `react-app-rewired build`
    13 verbose stack Exit status 1
    13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
    13 verbose stack     at EventEmitter.emit (events.js:182:13)
    13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    13 verbose stack     at ChildProcess.emit (events.js:182:13)
    13 verbose stack     at maybeClose (internal/child_process.js:961:16)
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
    14 verbose pkgid making-a-template@0.1.0
    15 verbose cwd /Users/harrysolovay/Desktop/making-a-template
    16 verbose Darwin 17.6.0
    17 verbose argv "/usr/local/Cellar/node/9.10.0_1/bin/node" "/usr/local/bin/npm" "run" "build"
    18 verbose node v10.6.0
    19 verbose npm  v6.1.0
    20 error code ELIFECYCLE
    21 error errno 1
    22 error making-a-template@0.1.0 build: `react-app-rewired build`
    22 error Exit status 1
    23 error Failed at the making-a-template@0.1.0 build script.
    23 error This is probably not a problem with npm. There is likely additional logging output above.
    24 verbose exit [ 1, true ]

`

Thank you so much for taking a look at this! Please let me know if you have any questions. And feel free to close the issue immediately if this is the wrong forum for this specific situation 👍

**Comment by harrysolovay** [comment]
The solution was to configure babel-loader to include modules that the console said weren't possible to minify (bitcoinjs-lib being one of them). Would be awesome if you could find a way for bitcoinjs-lib to be consumed in the [CRA](https://github.com/facebook/create-react-app) build process without the need for that additional configuration. Hopefully this is helpful (and not simply me complaining haha) 🥇 

Kind regards,

Harry

**Comment by JackNeto** [comment]
@harrysolovay can you share how you did this specifically?
Thanks

**Comment by harrysolovay** [comment]
Yea for sure:

Here's the relevant section of my webpack.config.prod.js before & after:

#### before:
```js
{
  test: /\.(js|jsx|mjs)$/,
  include: [
    paths.appSrc,
  ],
  loader: require.resolve('babel-loader'),
  options: {
    babelrc: true,
    compact: true,
  },
},
```

#### after:

```js
{
  test: /\.(js|jsx|mjs)$/,
  include: [
    paths.appSrc,
    ...[
      'bitcoinjs-lib',
      'tiny-secp256k1/ecurve',
      'base64url/dist/base64url',
      'base64url/dist/pad-string',
      'bip32',
    ].map(moduleName => `${ paths.appNodeModules }/${ moduleName }`)
  ],
  loader: require.resolve('babel-loader'),
  options: {
    babelrc: true,
    compact: true,
  },
},
```

**Comment by benoror** [comment]
fwiw, this is my CRA config using [timarney/react-app-rewired](https://github.com/timarney/react-app-rewired):


https://github.com/benoror/sundly/blob/de4f3064e2157a77dc86cb34fbfa00b242dfed42/config-overrides.js#L6-L16
