### ISSUE TITLE
Support to get input address for P2PK?

### ISSUE THREAD

**Issue by mmsqe** [bitcoinjs/bitcoinjs-lib#1161]
I try with
```
bitcoin.payments.p2pk({
    input: Buffer.from('48304502210096bf18f3fce1f3ac800f98c12e655240cbdb7127e046a3c1bd72e16d3e16c3fd022030e897e2eea143eca4e87b28ba104625eb316f1a487a72c5aecc93b824c8c74f01', 'hex'), 
    network: bitcoin.networks.bitcoin
}).address
```
but get 'Input is invalid' [error](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/payments/p2pk.js#L75) since chunks length is 1. 
For tx aa2c..., is it possible to get sender '1CjRf1RMrTwyGoBHDbqzXERhVFkPyowt8i' like in [here](https://blockchain.info/rawtx/aa2cb91301d684c443f81db2a623baed5ea657ea33c5fc4d8f995033292ebbd6)

**Comment by dcousens** [comment]
Do you mean `bitcoin.payments.p2pkh`?

**Comment by dcousens** [comment]
If not,  if you actually mean `P2PK`,  `P2PK` __doesn't__ have an address.
You can get `.pubkey` and feed it to a `bitcoin.payments.p2pkh` to get an `.address`,  but,  it isn't a `P2PK` address, its a `P2PKH` address derived from a `P2PK` output script.

**Comment by mmsqe** [comment]
Sorry I was confused, since it's not straight forward. If send tx by using bitcoin-cli `sendtoaddress`, I get P2PK type vin, not sure how I could get `.pubkey`, but I try 
```
bitcoin.payments.p2pkh({
    input: Buffer.from('48304502210096bf18f3fce1f3ac800f98c12e655240cbdb7127e046a3c1bd72e16d3e16c3fd022030e897e2eea143eca4e87b28ba104625eb316f1a487a72c5aecc93b824c8c74f01', 'hex'), 
    network: bitcoin.networks.bitcoin
}).address
```
I get a different addr `1MSMX1hWSV3iucB6KGYFpz1WFqj3A775jd`
