### ISSUE TITLE
Hi! This library is compatible with comman = create react native app  for react native ?

### ISSUE THREAD

**Issue by Joan1590** [bitcoinjs/bitcoinjs-lib#1169]
Hi, i have this error when i used React Native 
![captura de pantalla 2018-08-09 a la s 3 14 41 p m](https://user-images.githubusercontent.com/10948409/43923298-fadc1d6c-9be6-11e8-94af-331d0a5710c2.png)

and this error in the devices:
![captura de pantalla 2018-08-09 a la s 3 15 13 p m](https://user-images.githubusercontent.com/10948409/43923314-09571c2a-9be7-11e8-86f5-8c45efdddf7c.png)

Thank you !

**Comment by dcousens** [comment]
@Joan1590 please read and try the solutions listed in https://github.com/bitcoinjs/bitcoinjs-lib/issues/976

**Comment by Joan1590** [comment]
Hi @dcousens !! I found a repository with that, https://github.com/novalabio/react-native-bitcoinjs-lib this works, but only with "react native init" not with expo !! Thank you !!!
