### ISSUE TITLE
How to derive private keys, from the extended private key for an address?

### ISSUE THREAD

**Issue by bityogi** [bitcoinjs/bitcoinjs-lib#1170]
I've posted this question on [stack-exchange as well](https://bitcoin.stackexchange.com/questions/78093/looking-for-js-node-js-code-example-to-sign-a-transaction-with-multiple-utxos)

However, I thought this probably would be more useful as I'm specifically looking for something in Bitcoin and have a feeling that this library can probably already do this.

I have the extended-private-key and need to sign an unsigned transaction.

Is there a way to derive the private key I need to sign each UTXO, by using this extended private key?

Thanks in advance.

**Comment by dcousens** [comment]
If with "extended-private-key",  you mean,  a BIP32 node,  then,  you can sign __directly__ with that using this library.

**Comment by bityogi** [comment]
Thanks @dcousens , for creating such awesome libraries. 

Actually, I just needed to figure out how to derive the (private) keys first before using them to sign with. We needed it to sign ZenCash transactions.

And it seems your other library `bip32` was able to do the job perfectly!

We were creating addresses based on whether they were used as Receive Addresses or Change addresses. 

`const t = bip32.fromBase58(extPrivateKey, zenCashNetwork);
    
 const derivedIndex = `${utxo.AddrType}/${utxo.AddrIndex}`;
    
const wifKey = t.derivePath(derivedIndex).toWIF();`

and then use that WIF key to sign the transaction with for each UTXO.

Thanks again!
