### ISSUE TITLE
Generate multiple addresses from multisig

### ISSUE THREAD

**Issue by tgcandido** [bitcoinjs/bitcoinjs-lib#1173]
Greetings

I followed the [Generate a 2-of-3 P2SH multisig address](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/addresses.js#L47) example and it worked just fine for generating a single address. I would like to know if it's possible to generate multiple addresses from the same multisig wallet with bitcoinjs-lib, like the Electrum wallet does. 

Thanks

**Comment by dcousens** [comment]
What do you mean by multisig wallet?

**Comment by junderw** [comment]
@tgcandido yes it is.

You would need 3 extended public keys for the 3 signers. But it is possible.

Check the BIP32 repository.

**Comment by junderw** [comment]
Please re-open if you are having trouble.

The question is answered.
