### ISSUE TITLE
Getting the inputs array from a transaction builder - missing getter

### ISSUE THREAD

**Issue by omrip30** [bitcoinjs/bitcoinjs-lib#1179]
When using the 'TransactionBuilder.fromTransaction' method and then trying to access the transaction inputs, the only way to access those inputs is by accessing the '__inputs' private member. A getter method for the inputs should exist for this

**Comment by dcousens** [comment]
What are you actually trying to do?
You shouldn't need to manually access the inputs.

**Comment by omrip30** [comment]
Basically, you can see [https://github.com/bitcoinjs/bitcoinjs-lib/issues/1180](url) for the reason I require the inputs (in the for loop at the bottom).
This issue can be closed, in retrospective I think the issue I mentioned above already covers this one as well.
