### ISSUE TITLE
How many inputs does a TransactionBuilder have?

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#1182]
You can't determine this unless you track it yourself.

What should we name this method? `inputCount`?
What about `outputCount`?

Related https://github.com/bitcoinjs/bitcoinjs-lib/issues/1179, https://github.com/bitcoinjs/bitcoinjs-lib/issues/1180

**Comment by omrip30** [comment]
Also, I think that the TransactionBuilder API should include a getter to return the inputs array

**Comment by dcousens** [comment]
@omrip30 we decided against this as we didn't want to put it as part of the public API,  did you have a particular use case in mind?

It would simplify this issue,  but,  I worry users might start trying to change it or use it for something we didn't predict.

**Comment by omrip30** [comment]
I understand. When [https://github.com/bitcoinjs/bitcoinjs-lib/pull/1181#discussion_r211510641](url) is fixed then 'InputCount' should be enough, so no need for the inputs array getter in this way.

**Comment by dcousens** [comment]
If you think the `.inputs` array is useful, let us know.

But I suspect its desired usage would be purely in *breaking* the `Transaction` into manageable pieces,  which,  should be a separate new feature,  not necessarily the ability to 'peek' into `TransactionBuilder`s internals.

**Comment by valerioleo** [comment]
very helpful feature. I also append a `fee` and `totalInputsValue` properties to the `rawTransaction` object returned by `TransactionBuilder.build()`

**Comment by junderw** [comment]
Psbt class has inputCount getter.

Closing in favor of new Psbt.
