### ISSUE TITLE
Version code of address did not match acceptable versions for network

### ISSUE THREAD

**Issue by mmick66** [bitcoinjs/bitcoinjs-lib#1196]
I am trying to generate an address as:

```
import bitcoin from 'bitcoinjs-lib';
import bip39 from 'bip39';

const mnemonic = bip39.generateMnemonic();
const seed = bip39.mnemonicToSeed(mnemonic);

const master = bitcoin.HDNode.fromSeedBuffer(seed, bitcoin.networks.testnet);
const derived = master.derivePath(Wallet.Defaults.Path);
const address = derived.getAddress();
```

but the resulting address[ is not validated](https://www.blockchain.com/btc/address/mubSzQNtZfDj1YdNP6pNDuZy6zs6GDn61L) by blockchain.info. When I try to query it I get 

Version code of address did not match acceptable versions for network.

The address generated in your [test cases](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/addresses.js#L123) gets the [same error](https://www.blockchain.com/btc/address/LZJSxZbjqJ2XVEquqfqHg1RQTDdfST5PTn).

**Comment by dabura667** [comment]
This site is for testnet.
https://testnet.smartbit.com.au/address/mubSzQNtZfDj1YdNP6pNDuZy6zs6GDn61L

This site is for mainnet.
https://www.blockchain.com/btc/address/1F5VhMHukdnUES9kfXqzPzMeF1GPHKiF64

Your code generates the testnet address because you passed `bitcoin.networks.testnet`

**Comment by dabura667** [comment]
so your issue is with blockchain dot com.

please contact their support.

**Comment by dcousens** [comment]
@dabura667 is right,  this isn't our issue.
But in the interest of making everyones life simpler.

You wanted https://testnet.blockchain.info/

Try
https://testnet.blockchain.info/address/mubSzQNtZfDj1YdNP6pNDuZy6zs6GDn61L
