### ISSUE TITLE
ReferenceError: regtest is not defined

### ISSUE THREAD

**Issue by NoR3s** [bitcoinjs/bitcoinjs-lib#1197]
Hello im getting everytime refrence error or missing imports. 

i follow the examples witch are shown on the git i just try the following code to create a simple random adress  `const alice1 = bitcoin.ECPair.makeRandom({ network: regtest })`

This happends also when using other examples that im missing things.
ReferenceError: regtest is not defined

version im using is "bitcoinjs-lib": "^4.0.1",

**Comment by coinflippa** [comment]
Try

```javascript
const alice1 = bitcoin.ECPair.makeRandom({ network: bitcoin.networks.regtest })
```

**Comment by dcousens** [comment]
@NoR3S it is assumed understand the basics of JavaScript before using this library.

**Comment by dcousens** [comment]
@coinflippa `regtest` in that scenario is undefined too!   Use `testnet`.
