### ISSUE TITLE
Integrated TypeScript definitions

### ISSUE THREAD

**Issue by torkelrogstad** [bitcoinjs/bitcoinjs-lib#1200]
How do you feel about having TypeScript definitions included in this library? Currently, it's managed through DefinitelyTyped. One downside to this is that types have to be installed separately, increasing the risk of user error. It's also more difficult to keep changes JS/TS in sync, instead of being in control of the entire release process.

Another solution would also be to port the JS itself to TS. By adding a build step _(which might even be done currently, for backwards JS compatability?)_, the library could be distributed to JS users as well. It is possible to port to parts of libraries to TS, it doesn't have to be in one big step.

Seeing as this library deals with monetary value, strict and safe programming is paramount. Static typing makes this a great deal safer.

I'd be glad to put in some work to either write definitions or port (parts) of the library, if that's desirable.

**Comment by dcousens** [comment]
I am not against this anymore,  but,  I am now using typescript myself.

If you could add the type definitions such that they are verified against the existing API in an independent test,  I'd be happy to consider them under a `/types` directory.

**Comment by dcousens** [comment]
@torkelrogstad still interested in helping here?

**Comment by jprichardson** [comment]
> I am now using typescript myself.

I figured you would eventually 😛I've also got bit by the TypeScript bug as well recently.

**Comment by torkelrogstad** [comment]
@dcousens I'm interested! I'll try to get some done tomorrow:)

**Comment by zone117x** [comment]
This can be closed now.
Great work on the typescript port!
