### ISSUE TITLE
How get pre-signature transaction message?

### ISSUE THREAD

**Issue by Lursun** [bitcoinjs/bitcoinjs-lib#1202]
How get pre-signature transaction message?
like coinb.in => new => transaction

![image](https://user-images.githubusercontent.com/11616295/44974893-946c9f00-af93-11e8-82c1-79e3e5b459eb.png)

**Comment by dcousens** [comment]
@Lursun what is your code?

**Comment by junderw** [comment]
Do this, but before doing sign, just do `txb.buildIncomplete().toHex()` to get the unsigned value.
https://github.com/bitcoinjs/bitcoinjs-lib/blob/3588d1100f82af1718e0a2b0c91db1d33a4204b0/test/integration/transactions.js#L13-L26

**Comment by junderw** [comment]
But you need to find out the input info by querying an API or something...

Also know that coinbin and bitcoinjs-lib are not cross-compatible.
