### ISSUE TITLE
How to generate address, public key, and private key

### ISSUE THREAD

**Issue by Eithcowich** [bitcoinjs/bitcoinjs-lib#1203]
I need to create accounts for users. Looking at `bitcoinjs-lib` examples I came up with this code: 

``` js
function rng () {
  return Buffer.from('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz')
} // get a much more secure random

const keyPair = bitcoin.ECPair.makeRandom({ rng: rng })
const { address } = bitcoin.payments.p2pkh({ pubkey: keyPair.publicKey })
console.log("address " + address) // 17wqX8P6kz6DrDRQfdJ9KeqUTRmgh1NzSk
var publicKey = keyPair.publicKey.toString('hex')

console.log("public key " + publicKey) // 0279bf075bae171835513be1056f224f94f3915f9999a3faea1194d97b54397219

var wif = keyPair.toWIF()
console.log("private key WIF " + wif) // 200424e3612358db9078760d4f652a105049187c29f2d03d7d65bc9e27a007d0
```

My questions are: 
1. Bitcoin private keys seem to start with 5. The ones I generate with this code does not. Do I need to convert it? Or get it in another way? 
2. In general is this the right way to use `bitcoinjs-lib`?

**Comment by dcousens** [comment]
@Eithcowich I don't get the same results as you.

``` js
address 1F5VhMHukdnUES9kfXqzPzMeF1GPHKiF64
public key 03e05ce435e462ec503143305feb6c00e06a3ad52fbf939e85c65f3a765bb7baac
private key WIF L1Knwj9W3qK3qMKdTvmg3VfzUs3ij2LETTFhxza9LfD5dngnoLG1
```

**Comment by Eithcowich** [comment]
@dcousens Yes, the results I have in the question are from 

    const keyPair = bitcoin.ECPair.makeRandom();

Without the seed. When I use the zzzz... seed I get the same results you get. 

But regardless, the privake key still doesn't start with a 5, and also seem to have one extra character.
