### ISSUE TITLE
Sign message with testnet address invalid network version

### ISSUE THREAD

**Issue by NoR3s** [bitcoinjs/bitcoinjs-lib#1204]
How can i sign a message with bitcoinjs-message when using a testnet address my code looks like this

`var keyPair = bitcoin.ECPair.fromWIF('cUpXbbsJTrrCWnfXujy4W3hGgM4c26g5mG64JgvBxJcptpLbzdbo')
var privateKey = keyPair.privateKey
var message = req.body.message`

`var signature = bitcoinMessage.sign(message, privateKey, keyPair.compressed)`

Error: Invalid network version at Object.fromWIF

**Comment by dcousens** [comment]
Please see the other repository,  not this one.

**Comment by takahser** [comment]
which other repository?
I'm getting exactly the same error
