### ISSUE TITLE
api document for "https://api.dcousens.cloud/1"

### ISSUE THREAD

**Issue by timqian** [bitcoinjs/bitcoinjs-lib#1209]
`https://api.dcousens.cloud/1` is used as 3PBP in the tests, but I can not find documents or introduction for the apis

**Comment by junderw** [comment]
@timqian this API was made solely for the bitcoinjs-lib integration tests. If people start abusing it or using it for other purposes, it will be taken down, so please refrain from attempting to use it for anything else.

**Comment by takahser** [comment]
is there any recommendation on public btc nodes that can be used in replacement of `https://api.dcousens.cloud/1`?

**Comment by junderw** [comment]
There are none that we know of.

Run your own and tell us the URL so that other people can use it.
https://github.com/bitcoinjs/regtest-server

**Comment by junderw** [comment]
@timqian @takahser I made a gist to explain how to set up the server for yourself.

https://gist.github.com/junderw/46ad42ebf2c4863a42aed14df10b0f2f

**Comment by takahser** [comment]
thanks a lot @junderw
