### ISSUE TITLE
A scheme for short, memorable and verifiable public keys

### ISSUE THREAD

**Issue by c4c8c8** [bitcoinjs/bitcoinjs-lib#1212]
Great library you have here. This is more an esoteric question I have, as I have not found much surrounding this use-case other than "short GPG keys are insecure".

Are you aware of any known schemes that can used to construct short memorable usernames/IDs from a key-pair?

The goal, having a "short-code". A 6 to 8 char "username" that can be used to "represent" your identity without having to reveal your public-key.

Why?
- Public keys need to be memorable
- Public keys need to be obfuscated
- A digital identity should be transient

Goals
- One can easily cycle though {n} short-codes **randomly**
- Collisions are OK given new short-code can be generated and verified against the original public key

Have you seen any schemes that support or allude to this idea?

Many thanks,

c4c8c8

**Comment by junderw** [comment]
> 1. Are you aware of any known schemes that can used to construct short memorable usernames/IDs from a key-pair?
> 2. Have you seen any schemes that support or allude to this idea?

The only questions I could find in there are above.

1. No.
2. There was a "cloak" system in Darkwallet for their chat system, but iirc it had nothing to do with your public key... Darkwallet source is available, but the wallet is dead so don't actually use it. (The backend server is dead anyways so you can't)

**Comment by c4c8c8** [comment]
Thanks for the info @junderw
