### ISSUE TITLE
How to import an extended public key?

### ISSUE THREAD

**Issue by MrsBookik** [bitcoinjs/bitcoinjs-lib#1215]
Hi, how can I derive children from a node where I only got the xpubkey?

Initially, I create on my local machine a hd wallet from a mnemonic:

```
const mnemonic = 'praise you muffin lion enable neck grocery crumble super myself license ghost'
const seed = bip39.mnemonicToSeed(mnemonic)
const node = bip32.fromSeed(seed)
const string = node.toBase58()

const xpubkey = node.derivePath('m/44'/0'/0'). neutered().toBase58();
```

On a web server, I would then import the public key to derive new addresses:

```
const node = importFromXPubKey( xpubkey )

const address1 = node.derive(1);
const address2 = node.derive(2);
...

```

I am looking for a proper solution to handle the `importFromXPubKey`-function but can't find any in the examples.

**Comment by dabura667** [comment]
`bip32.fromBase58('xpubusdyfuisdyfiusfyiuyfsiudyfiusd...')`
