### ISSUE TITLE
If you use bitcoinjs.ECPair.fromWIF(publicKeys, mainnet) on the main network; how do you need to modify the mainnet later?

### ISSUE THREAD

**Issue by tangjielong** [bitcoinjs/bitcoinjs-lib#1223]
If you use bitcoinjs.ECPair.fromWIF(publicKeys, mainnet) on the main network; how do you need to modify the mainnet later?
this my code 
 const TestNet = bitcoinjs.networks.testnet;
    var key = new bitcoinjs.ECPair.fromWIF(publicKeys, TestNet);
    var tx = new bitcoinjs.TransactionBuilder(TestNet);
how to use  main network?

**Comment by dcousens** [comment]
Testnet

``` js
const bitcoin = require('bitcoinjs-lib')

// ...
const network = bitcoin.networks.testnet

// ...
const keyPair = new bitcoin.ECPair.fromWIF(..., network)
const txb = new bitcoin.TransactionBuilder(network)
```

Mainnet
``` js
const bitcoin = require('bitcoinjs-lib')

// ...
const network = bitcoin.networks.bitcoin

// ...
const keyPair = new bitcoin.ECPair.fromWIF(..., network)
const txb = new bitcoin.TransactionBuilder(network)
```

Reference https://github.com/bitcoinjs/bitcoinjs-lib/blob/625f5e01ce4241d52ab89993aa501d8b7e6cc999/src/networks.js#L4-L27

**Comment by tangjielong** [comment]
think your very mach!
