### ISSUE TITLE
Decode raw transaction addresses

### ISSUE THREAD

**Issue by brightsider** [bitcoinjs/bitcoinjs-lib#1226]
How to decode input and output addresses in all available formats?

**Comment by dcousens** [comment]
@brightsider you're asking for us to write you code.

But have you even tried anything?

Have you looked at any of the examples?

What does `decode` mean to you?

There is no such thing as an `input` address.

**Comment by junderw** [comment]
> How to decode input and output addresses in all available formats?

The payments API is a good place to start looking.

https://github.com/bitcoinjs/bitcoinjs-lib/tree/master/src/payments

Happy Hunting!

**Comment by brightsider** [comment]
@dcousens I'm decoding addresses for outputs with this:
```
address = bitcoinjs.address.fromOutputScript(out.script, network)
```
for inputs:
```
let p2sh = bitcoinjs.payments.p2sh({
                            witness: input.witness,
                            network: network,
                            input: input.script
                        })
let address = p2sh.address
```

But sometimes get errors for both options.
Input:
- TypeError: Redeem.output too short
- TypeError: Input too short

Output:
- Error: OP_RETURN 6234346636663532643230633665383337333666386336393165643835383832 has no matching Address

Examples of raw transactions with this errors:

> 0200000001a40c436b798305a45d21cb56111d78475b33e0554c140b734fbc7df6e94ae386010000006b483045022100e9c0a43bc187068c2452a7816491bad02c37835217cd5ff996e3941f7b1e9f00022055206e308d36f7cc779470c319b7314a024e5118baa3014813bd46df6b8214d90121021bd9fb009e3b8d1575d46503e1a0e688f3e27252f3a1b665b277cd7a093386acffffffff03102700000000000017a914ffd9114203951f645dbf58354ceddcb1737d8ea087b0690e01000000001976a914ea2b2473ec48af17e0913a6f367100cfeb39be6888ac0000000000000000116a0f62747400536167697474617269757300000000

> 01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff18039194150028000000677569646f20776173206865726500ffffffff017d161605000000001976a9142b2399d24a9e9e35487d2f76b57d6e33e72d522f88ac00000000

Can you help me with decoding this addresses?

**Comment by brightsider** [comment]
@junderw thanks
