### ISSUE TITLE
How do I connect to my local running full bitcoin core node

### ISSUE THREAD

**Issue by shrishjain** [bitcoinjs/bitcoinjs-lib#1227]
Hello there,

I am running full bitcoin core node on my box, and I want to develop Javascript code to createwallet/get Balance/Make transfer.

I wanted to check if I can use bitcoinjs-lib and configure it to connect to my local running node for all transactions?

THanks,
Shrish

**Comment by dcousens** [comment]
`bitcoinjs-lib` is a library, not a software service or application.
You can write your own software to connect to your running node... see https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs
