### ISSUE TITLE
payments.p2ms is overly strict RE signature `OP_0` counts

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#1231]
> Looking back at this, maybe payments.p2ms with { allowIncomplete: true, ... } should be what is doing the special casing (as it does already!), not TransactionBuilder... thoughts @junderw?

ref https://github.com/bitcoinjs/bitcoinjs-lib/pull/1201#discussion_r220427623

Maybe we should move the conditional check from `TransacationBuilder` for this, and instead do it in `payments.p2ms` as part of `allowIncomplete`?

**Comment by junderw** [comment]
Closing due to Psbt and deprecation of TransactionBuilder
