### ISSUE TITLE
Script evaluated without error but finished with a false/empty top stack element

### ISSUE THREAD

**Issue by prettyCoders** [bitcoinjs/bitcoinjs-lib#1235]
I use bitcoinjs-lib-4.0.2/test/integration/transaction.js to Signature transaction，But it can`t work.
reference transaction:dbc1f93b1004a5299a34aba513377c80a104067c50a03eeedb9baca2dcb5ff6a 
send address:3BssaKx2B2SJYUG2wsrYMX3TK6nbRYt4GS
receive address:15uCTMWCRX1zKJH6fvFXdPJNXG5Y5xy7dy  3BssaKx2B2SJYUG2wsrYMX3TK6nbRYt4GS
hex:01000000016affb5dca2ac9bdbee3ea0507c0604a1807c3713a5ab349a29a504103bf9c1db010000006b483045022100bd9422e5af858f3edc53d9ed6aeb513cadd08e642e302bb9892d07eeef91aa0d0220420a046bd942e19ee03e12257b83064d082997bc90cd072ef36f3c8189740a4b01210247cffb6f5ab8693453bfb29c56e27fd1c8a0848c891823fcdcfc14379e679655ffffffff01a0bb0d00000000001976a91435bfb1dccca89bf18e5fc3452bf0e3969c25ddfc88ac00000000
code:
![image](https://user-images.githubusercontent.com/36216120/46241986-d3f0a480-c3f4-11e8-9b0f-0c0d50552333.png)

**Comment by dabura667** [comment]
You're trying to spend a P2SH output with a P2PKH input...

That doesn't work.

I assume your P2SH is a P2SH-P2WPKH?

Then you want to follow the example that spends that... not a normal P2PKH (like in the example you showed)

**Comment by prettyCoders** [comment]
@dabura667 How do I modify it?

**Comment by dabura667** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L136

**Comment by prettyCoders** [comment]
@dabura667 This is just a demo of the test network. Could you please show me the demo of the main network？thanks!

**Comment by dabura667** [comment]
No I will not. Please figure it out yourself.

**Comment by prettyCoders** [comment]
OK,Thanks!
