### ISSUE TITLE
Can't install this package.. tried on mac, ubuntu server and windows 7

### ISSUE THREAD

**Issue by zny2xrG4qYeAMWpc4ef4N9kJFtjtvkPm** [bitcoinjs/bitcoinjs-lib#1237]
Hello, 

all i'm looking for is a small package which can help me generate addresses from an extended public key... thats all I need for my small project. 

Are there other ways or packages to do this?  Something really light-weight, best only made to do this single task.

Can't use https://www.npmjs.com/package/bitcoin-receive-payments
because I don't want to use openexchangerates.

I'm going trough hell installing this, I'd be happy if there is a guide to make this run on a clean install of nodejs and npm but I get errors all over the place, even after installing build tools and node-gyp it still won't install properly.

I find it strange that no one has had the same issues yet.

`> tiny-secp256k1@1.0.1 install /root/btc/node_modules/tiny-secp256k1
> node-gyp rebuild

make: Entering directory '/root/btc/node_modules/tiny-secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/native/addon.o
make: g++: Command not found
secp256k1.target.mk:143: recipe for target 'Release/obj.target/secp256k1/native/addon.o' failed
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 127
make: Leaving directory '/root/btc/node_modules/tiny-secp256k1/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/btc/node_modules/tiny-secp256k1
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/root/btc/package.json'
npm WARN btc No description
npm WARN btc No repository field.
npm WARN btc No README data
npm WARN btc No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiny-secp256k1@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-29T21_19_29_268Z-debug.log
`

**Comment by ceX2MsjvD8Rs7uac** [comment]
> 
> 
> Please check this: https://github.com/cryptocoinjs/secp256k1-node#installation
> 
> For ubuntu you need install next packages: `python build-essential`

works now.
thanks =)

close.
