### ISSUE TITLE
How to attach a message to a transaction?

### ISSUE THREAD

**Issue by fanmeilexiu** [bitcoinjs/bitcoinjs-lib#1240]
How to attach a message to a transaction?

**Comment by fanatid** [comment]
You can use OP_RETURN for this: https://github.com/bitcoinjs/bitcoinjs-lib/blob/582727f6de251441c75027a6292699b6f1e1b8f2/test/integration/transactions.js#L80

**Comment by fanmeilexiu** [comment]
thanks
