### ISSUE TITLE
TypeError: Can't read property 'fromSeedBuffer' of undefined

### ISSUE THREAD

**Issue by fessor10** [bitcoinjs/bitcoinjs-lib#1243]
I installed the latest version and still I'm still having this error

`const bip39 = require('bip39')`
`const bitcoin = require('bitcoinjs-lib')`
`const crypto = require('crypto')`

`let randomBytes = crypto.randomBytes(16)`

`let phase = bip39.entropyToMnemonic(randomBytes.toString('hex')) `
`let phrase = bip39.generateMnemonic()`
`let seedBuffer = bip39.mnemonicToSeed(phrase)`
`let masterNode = bitcoin.HDNode.fromSeedBuffer(seedBuffer)`
`return masterNode;`

**Comment by dabura667** [comment]
`HDNode` was removed and is now a separated package.

`npm install bip32`

**Comment by fessor10** [comment]
> `HDNode` was removed and is now a separated package.
> 
> `npm install bip32`

And also i was looking at how to implement bitcoin cash and i get this error when i want to broadcast a bitcoin cash transaction
```bash
Signature must use `SIGHASH_FORKID`
```

Am i missing something in between?

**Comment by dabura667** [comment]
Yes. You need to sign using SIGHASH_FORKID. This is not supported in bitcoinjs-lib.

I think I found a fork of bitcoinjs-lib that allows bitcoin cash.

https://github.com/Bitcoin-com/bitcoincashjs-lib

**Comment by fessor10** [comment]
> Yes. You need to sign using SIGHASH_FORKID. This is not supported in bitcoinjs-lib.
> 
> I think I found a fork of bitcoinjs-lib that allows bitcoin cash.
> 
> https://github.com/Bitcoin-com/bitcoincashjs-lib

Thanks, but i don't seem to find a way to install that.

**Comment by fessor10** [comment]
> > Yes. You need to sign using SIGHASH_FORKID. This is not supported in bitcoinjs-lib.
> > I think I found a fork of bitcoinjs-lib that allows bitcoin cash.
> > https://github.com/Bitcoin-com/bitcoincashjs-lib
> 
> Thanks, but i don't seem to find a way to install and include that.

**Comment by dabura667** [comment]
npm allows to install from github directly. (I am setting a specific commit hash so that it won't change every time you install if they update github.)
```
npm install --save git+https://github.com:Bitcoin-com/bitcoincashjs-lib.git#12fa5fe9b535816b54b9efedd6caf278d3e55b90
```

**Comment by fessor10** [comment]
We started using this here #921 we found a similar issue to what error we were facing, my colleague already added the issue here. I'll as well add that here as well.

````js
const tx = new bitcoincashjs.TransactionBuilder(network)

var path = var account = root.derivePath("m/44'/145'/0/0")

const keyPair = path.keyPair

const pk = keyPair.getPublicKeyBuffer()

const pkh = bitcoincashjs.crypto.hash160(pk)

const spk = bitcoincashjs.script.pubKeyHash.output.encode(pkh)

tx.addInput(txid, vout, bitcoincashjs.Transaction.DEFAULT_SEQUENCE, spk)

tx.addOutput(receivingAddress, sending_amount_sat)

tx.addOutput(change_address, change_amount)

const hashType = bitcoincashjs.Transaction.SIGHASH_ALL | bitcoincashjs.Transaction.SIGHASH_BITCOINCASHBIP143

tx.sign(0, keyPair, null, hashType, sending_amount_sat)

const transact = tx.build().toHex()
````

I get this error message when i try broadcasting through bch insight

````bash
16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26
````

**Comment by junderw** [comment]
`tx.sign` does not support SIGHASH_FORKID.

A Sighash only signals to the verifier "How was this signature formed?"
We would actually need to form the signature in the method described by the SIGHASH_FORKID spec.

Which we do not do.

However, I have a branch that I rebased on v4.0.2 that includes bitcoin cash signing.

https://github.com/junderw/bitcoinjs-lib/tree/cash402

`keyPair.getPublicKeyBuffer()` is a <v4 function. `keyPair.publicKey` is the correct way for v4.

Also, you will need to use `tx.enableBitcoinCash()` before signing the transactionBuilder.

**Comment by AyacosiDern** [comment]
bip32 is installed, but it's don't work. 😭

**Comment by AyacosiDern** [comment]
![image](https://user-images.githubusercontent.com/115349906/202719732-fa5b43cc-e60b-463b-bbd8-b5a8973afeaf.png)

**Comment by vivekchavan14** [comment]
const root = bitcoin.fromSeedBuffer(seed);
 
 is there any alternative to this?
