### ISSUE TITLE
Get & Apply signatures

### ISSUE THREAD

**Issue by ivands** [bitcoinjs/bitcoinjs-lib#1245]
I want to use bitcoinjs-lib and build a system like bip-0174
https://github.com/bitcoin/bips/blob/973a303edc2cc7a9cc84f3fc84673e606aef68f3/bip-0174.mediawiki@Responsibilities

Where am getting stuck is the signing part.
Is there a way to sign the transaction and get the signature.
Then later apply that signature to the transaction.
The Bitcore API provided that functionality, but I can't find how to do it with bitcoinjs-lib
https://bitcore.io/api/lib/transaction#multisig-transactions

**Comment by junderw** [comment]
Nope. There is no currently supported method for "Get Signature" or "Apply Signature"

PSBT support will likely be added in the future.
