### ISSUE TITLE
Possible to check who signed the transaction in a multi-sig transaction case?

### ISSUE THREAD

**Issue by takunee** [bitcoinjs/bitcoinjs-lib#1251]
Say you have a multi-sig tx that originated from a 2-of-3 P2SH address.

Is it possible to say who signed the transaction? i.e. you can get access to the redeem script once the tx is broadcasted, and thus you have access to all 3 public keys that generated the 2-of-3 P2SH address. Arguably you can identify which public keys signed the transaction?

If yes, then how?

**Comment by dabura667** [comment]
You could do something similar to what TransactionBuilder does for P2SH(P2MS)

https://github.com/bitcoinjs/bitcoinjs-lib/blob/582727f6de251441c75027a6292699b6f1e1b8f2/src/transaction_builder.js#L129-L160

**Comment by dabura667** [comment]
https://www.blockchain.com/btc/tx/3d47a7cdc86532b1cfffb35025e42ee262083e2034849004f7a7b3d2e65e04ab

This tx is:

```
010000000183e3fefbe7fe7d285566fdfd4c6660df1387debae52d8016e7b2542da3a8e67001000000fdfd0000483045022100a9b39c27c98861364ebe9251e65ecc98462be5990873b74163ad046d78ab439802207dd3d3feb63b3adf5c0650b042d8238dbc4823c7ffb0c41595900d6bc4a9d87301473044022048ba57d5446ee43361ff559e8258bc06c089cac8194edb65f8dc7ebc16bb512302207a7b0befc52a552c46273d3904bff6631af4b2fff3f36c3da266c4d2b88547c0014c6952210232adb616613b126e873598deac68f07ea0384020772c07baeef463ab1636b149210253583464fa492a8452d1c04c2840826782c274622923a882accd1fbef4e877062102f42b8b38e9e768dbf2b1ba64d15186e11f91844edd4eaf84a02ccf3ee3aaf1a253aeffffffff027c6421000000000017a91437d7b6cda4848235df5dc697668d8bdb63931cc687470653000000000017a9142ab56d9c6e3c37d312a714ad7981db6da7b939088700000000
```

```javascript
const bitcoin = require('bitcoinjs-lib')

const rawtx = "010000000183e3fefbe7fe7d285566fdfd4c6660df1387debae52d8016e7b2542da3a8e67001000000" +
"fdfd0000483045022100a9b39c27c98861364ebe9251e65ecc98462be5990873b74163ad046d78ab439802207dd3d3fe" +
"b63b3adf5c0650b042d8238dbc4823c7ffb0c41595900d6bc4a9d87301473044022048ba57d5446ee43361ff559e8258" +
"bc06c089cac8194edb65f8dc7ebc16bb512302207a7b0befc52a552c46273d3904bff6631af4b2fff3f36c3da266c4d2" +
"b88547c0014c6952210232adb616613b126e873598deac68f07ea0384020772c07baeef463ab1636b149210253583464" +
"fa492a8452d1c04c2840826782c274622923a882accd1fbef4e877062102f42b8b38e9e768dbf2b1ba64d15186e11f91" +
"844edd4eaf84a02ccf3ee3aaf1a253aeffffffff027c6421000000000017a91437d7b6cda4848235df5dc697668d8bdb" +
"63931cc687470653000000000017a9142ab56d9c6e3c37d312a714ad7981db6da7b939088700000000"

const tx = bitcoin.Transaction.fromHex(rawtx)
const txb = bitcoin.TransactionBuilder.fromTransaction(tx)
```

This works because `fixMultisigOrder` is called in `TransactionBuilder.fromTransaction`

This is possible because the only input of this tx is P2SH(P2MS)...

Note this will not work for P2SH(P2WSH(P2MS)) or P2WSH(P2MS)

**Comment by takunee** [comment]
> https://www.blockchain.com/btc/tx/3d47a7cdc86532b1cfffb35025e42ee262083e2034849004f7a7b3d2e65e04ab
> 
> This tx is:
> 
> ```
> 010000000183e3fefbe7fe7d285566fdfd4c6660df1387debae52d8016e7b2542da3a8e67001000000fdfd0000483045022100a9b39c27c98861364ebe9251e65ecc98462be5990873b74163ad046d78ab439802207dd3d3feb63b3adf5c0650b042d8238dbc4823c7ffb0c41595900d6bc4a9d87301473044022048ba57d5446ee43361ff559e8258bc06c089cac8194edb65f8dc7ebc16bb512302207a7b0befc52a552c46273d3904bff6631af4b2fff3f36c3da266c4d2b88547c0014c6952210232adb616613b126e873598deac68f07ea0384020772c07baeef463ab1636b149210253583464fa492a8452d1c04c2840826782c274622923a882accd1fbef4e877062102f42b8b38e9e768dbf2b1ba64d15186e11f91844edd4eaf84a02ccf3ee3aaf1a253aeffffffff027c6421000000000017a91437d7b6cda4848235df5dc697668d8bdb63931cc687470653000000000017a9142ab56d9c6e3c37d312a714ad7981db6da7b939088700000000
> ```
> ```js
> const bitcoin = require('bitcoinjs-lib')
> 
> const rawtx = "010000000183e3fefbe7fe7d285566fdfd4c6660df1387debae52d8016e7b2542da3a8e67001000000" +
> "fdfd0000483045022100a9b39c27c98861364ebe9251e65ecc98462be5990873b74163ad046d78ab439802207dd3d3fe" +
> "b63b3adf5c0650b042d8238dbc4823c7ffb0c41595900d6bc4a9d87301473044022048ba57d5446ee43361ff559e8258" +
> "bc06c089cac8194edb65f8dc7ebc16bb512302207a7b0befc52a552c46273d3904bff6631af4b2fff3f36c3da266c4d2" +
> "b88547c0014c6952210232adb616613b126e873598deac68f07ea0384020772c07baeef463ab1636b149210253583464" +
> "fa492a8452d1c04c2840826782c274622923a882accd1fbef4e877062102f42b8b38e9e768dbf2b1ba64d15186e11f91" +
> "844edd4eaf84a02ccf3ee3aaf1a253aeffffffff027c6421000000000017a91437d7b6cda4848235df5dc697668d8bdb" +
> "63931cc687470653000000000017a9142ab56d9c6e3c37d312a714ad7981db6da7b939088700000000"
> 
> const tx = bitcoin.Transaction.fromHex(rawtx)
> const txb = bitcoin.TransactionBuilder.fromTransaction(tx)
> ```
> 
> This works because `fixMultisigOrder` is called in `TransactionBuilder.fromTransaction`
> 
> This is possible because the only input of this tx is P2SH(P2MS)...
> 
> Note this will not work for P2SH(P2WSH(P2MS)) or P2WSH(P2MS)

Thanks, but how can I get the input.signatures ?  I'm new here.

the tx hex below is what i want to check on bitcoin testnet.'

02000000013d933ef6b048f52bceaed91a5c38b61f9e6217ed26089696e80095fed12714c600000000fdfe0000483045022100cbc7238e666a2da7f003931fcb1aaf94374e65ec6ff451ba8b23c9447218a97502205903078f2fb191efed62be1271a640e504998d3d042daa35953e72d8e9201b520148304502210090825df3537a961522acbeec601f84f0440bb6d3bbe2a1a6985dcde7ce941f0102206be36e4814e0f5e5217b5d2b0788f3c3f26f8c6e97f82cfbea6371d7264fa238014c695221030de4e7b0aabb37f48823a110beaab3338d2579caf7c0aa42ed4f9eeee7f8e3b621032e69ca747cb8fef336b5ce3bcd9c931f02770ed0eb0be6faad979e4da57cf6ab21034faf57ef5d5b3d92fbdba044a2d04015cbb6b41e84eb8ffae0b09ceecd8d436453aeffffffff011c250000000000001976a9142e209a162f876372a57ed2d5a389fe162a2d0ea588ac00000000

**Comment by junderw** [comment]
inspect things, poke, prod, explore.

We don't want to encourage people to use bitcoinjs-lib in an unsupported way, but if you learn how the internals work you will find a solution.

console.log everything. Maybe you'll get some hints.
