### ISSUE TITLE
Broadcast tx - in regtest integration tests

### ISSUE THREAD

**Issue by Janaka-Steph** [bitcoinjs/bitcoinjs-lib#1252]
Hello!

I am learning Bitcoin by running the integration tests with a local bitcoinjs-regtest server and a local Bitcoin Core in regtest mode. 
I have an issue with the broadcast function in _regtest.js. The current method is PUT and returns me a 404 Cannot PUT. However if I change it for a POST it works fine.
Can you explain the reasons behind choosing PUT?  How can I make it work?

Side question. I don't have any log in bitcoin debug.log when I successfully broadcast a tx. Do you know if I can activate log for that or monitor it in some ways other than the return value of `sendrawtransaction`.
Thank you.

**Comment by dcousens** [comment]
This should be resolved...

> I don't have any log in bitcoin debug.log when I successfully broadcast a tx
Probably need to ask this on the main repository, not here :+1:
