### ISSUE TITLE
Duplicate TxOut

### ISSUE THREAD

**Issue by brightsider** [bitcoinjs/bitcoinjs-lib#1254]
I've 2 wallets with same last transaction (1st sent to 2nd).
When I'm trying to create transaction for send coins from this 2 wallets to 3rd wallet I get "Duplicate TxOut" error.

**Comment by junderw** [comment]
Please show us your code.

Thanks.

**Comment by brightsider** [comment]
You can check latest transaction of used 2 wallets: mpfkqnbEHJ4Zi7WwMCDSdxCPr9iUqa4ttZ, mrJwf6mmJci9B2VTttEJzF1ig57Ursktt2

```
fromWallets.forEach(function (wallet, i, arr) {
    let transaction = wallet.latestTransaction()
    tx.addInput(transaction.txid, 1)
    let balance = Math.round(wallet.balance * divider)
    let value = Math.round(values.get(wallet.id).value * divider)
    let result = balance - value - fees
    if (result < 0) {
        value -= result
        result = 0
    }
    tx.addOutput(wallet.address, result)
})
```

**Comment by junderw** [comment]
https://testnet.smartbit.com.au/tx/f2a0a7b95748b49b67846a424e9ba22263d0ee183ab2fbda3e482bc5641438fc

Looking at this transaction it looks like the output index for each address is:

`mpfkqnbEHJ4Zi7WwMCDSdxCPr9iUqa4ttZ = 0`
`mrJwf6mmJci9B2VTttEJzF1ig57Ursktt2 = 1`

But your code is hard coded with a 1 for the index:

`tx.addInput(transaction.txid, 1)`

`1` is fine for `mrJwf6mmJci9B2VTttEJzF1ig57Ursktt2`
But `mpfkqnbEHJ4Zi7WwMCDSdxCPr9iUqa4ttZ` will need to be `0` and not 1.

You will need to also sign 0 and 1 with the right private keys as well.

**Comment by brightsider** [comment]
Thank you! Now all right :)
