### ISSUE TITLE
Help on spending P2SH with CLTV

### ISSUE THREAD

**Issue by Janaka-Steph** [bitcoinjs/bitcoinjs-lib#1257]
Hello! 
I am trying to run one of the test example of bitcoinjs-lib, creating and spending a P2SH with CLTV. I am stuck at this error when trying to spend the P2SH `mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element) (code 16) (code -26)`. I am playing on regtest, funding the P2SH manually. If someone can have a look at my code I have created a pastebin, with spending rawtx at the end. https://pastebin.com/4SHLPxrU

**Comment by dabura667** [comment]
You need to spend from 2NFdCJc8X2rJwCVUjrFDwTtx8y9CxfsEQyr

your comment says you used a UTXO from Alice's address.

**Comment by junderw** [comment]
No response. Closing. Re-open if you can't figure it out. Thanks.
