### ISSUE TITLE
How to generate addresses from xpub (or ypub) with bitcoinjs-lib4.0.2

### ISSUE THREAD

**Issue by JackWoBCT** [bitcoinjs/bitcoinjs-lib#1258]
I would like to use bitcoinjs-lib to generate addresses with the public key.

The old code(use bitcoinjs-lib 3.3.2):

```
var bjs = require('bitcoinjs-lib')

function nodeToP2shSegwitAddressTestNet(hdNode) {
  var pubkeyBuf = hdNode.keyPair.getPublicKeyBuffer()
  var hash = bjs.crypto.hash160(pubkeyBuf)
  var redeemScript = bjs.script.witnessPubKeyHash.output.encode(hash)
  var hash2 = bjs.crypto.hash160(redeemScript)
  var scriptPubkey = bjs.script.scriptHash.output.encode(hash2)
  return bjs.address.fromOutputScript(scriptPubkey, bjs.networks.testnet)
}

var tpub = 'ypub6XTWVFLfqkFYarn9NArqtBLziffJttqf1Utaur3sTbTGtgfNaTzkGcRpFgiiieBjQ6rV1rJ7iJ9r9oXGpPXZpkq71yfss2mrKLaauxhjXD4'

var hdNode = bjs.HDNode.fromBase58(tpub, [bjs.networks.testnet])

// generate as usual, but instead of getAddress, feed into above function
var address = nodeToP2shSegwitAddressTestNet(hdNode.derive(0).derive(0))

console.log(address)
```

.HDNode be removed from bitcoinjs-lib 4.0.0, I fond the code below(use bitcoinjs-lib 4.0.0).

```
var bjs = require('bitcoinjs-lib')
var b58 = require('bs58check')
var bip32 = require('bip32')

//Assuming it's mainnet for trezors
var network = bjs.networks.bitcoin;

function ypubToXpub(ypub) {
    var data = b58.decode(ypub)
    data = data.slice(4)
    data = Buffer.concat([Buffer.from('0488b21e','hex'), data])
    return b58.encode(data)
}

var ypub = "ypub6XTWVFLfqkFYarn9NArqtBLziffJttqf1Utaur3sTbTGtgfNaTzkGcRpFgiiieBjQ6rV1rJ7iJ9r9oXGpPXZpkq71yfss2mrKLaauxhjXD4"

//If you have a ybup address, convert it first
var xpub = ypubToXpub(ypub)

//First address created for account
var addressIndex = 0;

var payment = bjs.payments.p2sh({ 
    redeem: bjs.payments.p2wpkh({ 
        pubkey: bip32.fromBase58(xpub, network).derive(0).derive(addressIndex).publicKey 
    })
  })

var address = payment.address;

console.log(address)
```

But the same parameters get different results. 
One more thing, the previous code used 'Chain' as parameter but the new one, is this param still useful in the 4.0.+ version?
And how to modify the new code so that get the same result as the old code.

Thanks.

**Comment by junderw** [comment]
This exact same question was asked before... the same exact examples were used...
Please search before asking the exact same question.

I remember because I was the one who answered it. Then someone else asked the same question again. And now you're asking the same question again...

Quick question, where did you copy-paste your first example from? I feel like someone wrote a blog post and is failing to update it or something...

Or you are looking at old issues from this repo.

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/issues/966
https://github.com/bitcoinjs/bitcoinjs-lib/issues/1158
https://github.com/bitcoinjs/bitcoinjs-lib/issues/1137
https://github.com/bitcoinjs/bitcoinjs-lib/issues/1238

**Comment by JackWoBCT** [comment]
The above issues are all similar problems, but they do not solve my problems.

```
const ypub = 'xpub6DCQHRsgSnd7zcfjFejaRYTfsYzaBNAAkDJLVqy4oxAgBTJdVDsYCvYVXkQ7fmYGYGUoN14pUQcCZnMKMUvAhdVm1XVrZnhvPkCoqhVL2Ld';
    const network = bitcoin.networks.bitcoin;

    let data = b58.decode(ypub);
    data = data.slice(4);
    data = Buffer.concat([Buffer.from('0488b21e', 'hex'), data]);
    const xpub = b58.encode(data);

    const payment = bitcoin.payments.p2sh({
      redeem: bitcoin.payments.p2pkh({
        pubkey: bitcoin.bip32.fromBase58(xpub, network).derive(0).derive(0).publicKey
      })
    });

    const addressString = payment.address;
    console.log(`the addressString is ${addressString}`);
```

The expected value of the above code is
"3CEHi9mZ76s8DxHuycnojKZQgBGwXHu2ex".
But in fact, the result is
"3BYGKKNc1N9Vidyvrmty6p9mAMeMxRvHaj".

Can you help me find out where the problem is?

Thanks.

@junderw

**Comment by junderw** [comment]
`p2pkh ⇒ p2wpkh`

**Comment by JackWoBCT** [comment]
Hi junderw,

It works, thank you very much, but it only works on the bitcoin's MainNet, it does not work on the bitcoin's TestNet. The TestNet's addresses all start with "2", but the following code gets the addresses starting with "3". 

```
const ypub = 'xpub6DCQHRsgSnd7zcfjFejaRYTfsYzaBNAAkDJLVqy4oxAgBTJdVDsYCvYVXkQ7fmYGYGUoN14pUQcCZnMKMUvAhdVm1XVrZnhvPkCoqhVL2Ld';
const network = bitcoin.networks.testnet;

let data = b58.decode(ypub);
data = data.slice(4);
data = Buffer.concat([Buffer.from('043587cf', 'hex'), data]);
const xpub = b58.encode(data);

const payment = bitcoin.payments.p2sh({
    redeem: bitcoin.payments.p2wpkh({
      pubkey: bitcoin.bip32.fromBase58(xpub, network).derive(0).derive(0).publicKey
    })
});

const addressString = payment.address;
console.log(`the addressString is ${addressString}`);
```

The expected value of the above code is
"2NBmXMg4pTb5M6SLnKDr3raAj4Y5UN1irLb".
But in fact, the result is
"3LDKHw8nr8ZzteiEe6EBEdBTrBsJZNKavq".

Could you help me find out what went wrong again?

Thanks.

@junderw

**Comment by junderw** [comment]
pass `network` in the object args for both p2wpkh and p2sh.

I didn't get 2NBmXMg4pTb5M6SLnKDr3raAj4Y5UN1irLb, this is probably because you are using the wrong xpub.

BIP44 wallets use `m/44'/1'/0'` as their xpub for testnet but `m/44'/0'/0'` as their xpub for mainnet.

**Comment by JackWoBCT** [comment]
@junderw 
Thank you very much, it works, you save my day.

```
const ypub = 'tpubDCoXW1puhTARDmuk8UXieCYPuVR6GpY7yHLEMoKM1iXfMui8crafMFUbKA6QtjT6RZkajE4nXBNCTNp98rMZQfjdqxLEZrzbmUPY6zAFviU';
const network = bitcoin.networks.testnet;

let data = b58.decode(ypub);
data = data.slice(4);
data = Buffer.concat([Buffer.from('043587cf', 'hex'), data]);
const xpub = b58.encode(data);

const p2wpkh = bitcoin.payments.p2wpkh({ pubkey: bitcoin.bip32.fromBase58(xpub, network).derive(0).derive(0).publicKey, network });
const payment = bitcoin.payments.p2sh({ redeem: p2wpkh, network });

const addressString = payment.address;
console.log(`the addressString is ${addressString}`);
```
