### ISSUE TITLE
Can't create regtest p2wpkh address

### ISSUE THREAD

**Issue by Janaka-Steph** [bitcoinjs/bitcoinjs-lib#1260]
Hello,

I am trying to run the [P2WPKH test](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L165) on my machine, using Bitcoin Core on regtest mode to fund the p2wpkh address manually. 
The address starts with `tb`, which is not what I want because  Core is using `bcrt` address prefix on regtest.

Bitcoinjs doesn't have a regtest object in `bitcoin.networks`, so what am I suppose to do? 
Is bitcoinjs able to produce a regtest p2wpkh address?
Thank you.

**Comment by junderw** [comment]
> Is bitcoinjs able to produce a regtest p2wpkh address?

If you create a custom network, yes.

The network object is not that complicated, you can make a custom one to meet your needs.

**Comment by dcousens** [comment]
Check the integration tests.

`regtest` has the same constants as `testnet`.
We simply use `bitcoin.networks.testnet` for our `regtest` tests.

If you want to put up a PR which aliases `testnet` with `regtest`... I think that would be OK?

**Comment by junderw** [comment]
@dcousens He is saying that regtest has a different bech32 value for segwit.

`bech32: 'bcrt'`

**Comment by dcousens** [comment]
Make a PR please that adds `regtest` :+1:

**Comment by junderw** [comment]
@dcousens https://github.com/bitcoinjs/bitcoinjs-lib/pull/1261

**Comment by dcousens** [comment]
@Janaka-Steph please see #1261,  thanks @junderw
