### ISSUE TITLE
Regtest server backend hosting

### ISSUE THREAD

**Issue by junderw** [bitcoinjs/bitcoinjs-lib#1263]
I have set up a regtest server backend which we could host instead of you using your own personal funds, @dcousens.

I can set your ssh pubkey up so you can ssh in whenever you want.

Just out of curiosity, what specs are your current box using? Right now I have mine set up on a t2.micro with 50GB storage on AWS and it seems to work fine.

**Comment by dcousens** [comment]
Don't bother with the storage... you won't even break a few hundred megabytes with our usage...

**Comment by junderw** [comment]
ok, sounds great.

I'll talk about getting a subdomain ready for it on our exchange's domain.

I'll close once everything is ready to switch over, and I merge the other PR.
