### ISSUE TITLE
Documentation - New BitcoinJS guide

### ISSUE THREAD

**Issue by Janaka-Steph** [bitcoinjs/bitcoinjs-lib#1273]
Hello!

I did this BitcoinJS guide: https://github.com/bitcoin-studio/Bitcoin-Programming-with-BitcoinJS
It would be great if @dcousens or someone with experience have time to review it.
Also, feel free to add a link to it to the readme if you want to.

Also I noticed that some tests are missing in bitcoinjs-lib, like the P2WSH. 

Thanks!

**Comment by junderw** [comment]
> Also I noticed that some tests are missing in bitcoinjs-lib, like the P2WSH.

Good point. I'll make one... the only real example I can think of is multisig though.

**Comment by junderw** [comment]
There are some good examples here already, actually... what exactly do you mean "tests are missing?"

https://github.com/bitcoinjs/bitcoinjs-lib/blob/9a8552acda9c1881c43b3b6a9b42fb6b46ebd424/test/integration/transactions.js#L193-L259

**Comment by Janaka-Steph** [comment]
There is no tests, and as a result no documentation, of native P2WSH.

Do you really think the current tests/documentation is enough?  
It is not. It's really hard for beginners to start Bitcoin programming. 
I think it doesn't have to be this way.

**Comment by dabura667** [comment]
P2WSH is literally the first thing the link is linking to.

Please read the comment before you reply.

**Comment by Janaka-Steph** [comment]
Yes sorry, I was thinking of the use of any non-standard scripts through a P2WSH.
For example, this script using a CLTV. https://github.com/bitcoin-studio/Bitcoin-Programming-with-BitcoinJS/blob/master/09_2_P2WSH_CLTV.md
