### ISSUE TITLE
OP_CHECKLOCKTIMEVERIFY: non-mandatory-script-verify-flag (Locktime requirement not satisfied) 

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1275]
HI.

I have tried the examples but OP_CHECKLOCKTIMEVERIFY always fail with error:
`'non-mandatory-script-verify-flag (Locktime requirement not satisfied) (code 64)',`

I have simplified the example to the bare minimum. I use a fixed locktime number (in the past) so the address is always the same and I know it has bitcoins.

Please help me.

```
    cltvCheckSigOutput2 (aQ, lockTime) {
      return bitcoin.script.compile([
        bitcoin.script.number.encode(lockTime),
        bitcoin.opcodes.OP_CHECKLOCKTIMEVERIFY,
        bitcoin.opcodes.OP_DROP,
        aQ.publicKey,
        bitcoin.opcodes.OP_CHECKSIG
      ])
    },

    send2() {
      this.lockTime = bip65.encode({ utc: 1543938612 }) //this.utcNow() - (3600 * 3) })
      console.log("lockTime:", this.lockTime)
      this.redeemScript = this.cltvCheckSigOutput2(this.alice, this.lockTime)
      const { address } = bitcoin.payments.p2sh({ redeem: { output: this.redeemScript, network: this.network }, network: this.network })
      this.addressId = address
      console.log("address send:", this.addressId)
      const txb = new bitcoin.TransactionBuilder(this.network)
      console.log("using this locktime to run:", this.lockTime)
      txb.setLockTime(this.lockTime)
      txb.addInput(this.address_utxos[0].utxo_tx, this.address_utxos[0].utxo_n) 
      txb.addOutput('mwtnL3jExWXKQ9fh4cwjpiifnEQjQgNDiW', 5e6)
      // change
      const balance = parseInt(this.address_utxos[0].value * 100000000)
      txb.addOutput(this.addressId, balance - 5e6 - 5000) // fee 5000
      const tx = txb.buildIncomplete()
      const signatureHash = tx.hashForSignature(0, this.redeemScript, this.hashType)
      const redeemScriptSig = bitcoin.payments.p2sh({
        redeem: {
          input: bitcoin.script.compile([
            bitcoin.script.signature.encode(this.alice.sign(signatureHash), this.hashType),
          ]),
          output: this.redeemScript
        }
      }).input
      tx.setInputScript(0, redeemScriptSig) 
      // then broadcast
```
this.network is: bitcoin.networks.testnet
Hash is bitcoin.Transaction.SIGHASH_ALL.

I am running it against a regtest running in my computer. Everything works ok except por OP_CHECKLOCKTIMEVERIFY.

Thanks.

**Comment by junderw** [comment]
How many blocks have you mined before submitting the tx?

try mining 500 blocks, then retry.

**Comment by educob** [comment]
I have seen also that I don't enter a locktime-OP_CHECKLOCKTIMEVERIFY-OP_DROP but I enter a locktime at transaction level: `
      txb.setLockTime(this.lockTime)`, it get executed even if the lockTime is in the future.

So nothing related to time is working properly for me.

**Comment by educob** [comment]
Solved by specifying sequence 2^32-1 when adding an input.

**Comment by educob** [comment]
Hi.

After trying with psbt I get the same error.

This is the call:

`psbt.addInput({ hash: utxo.utxo_tx, index: utxo.utxo_n,
          redeemScript,
          witnessScript,
          witnessUtxo: {
            script, 
            value: utxo.value,
          },
          sequence: bitcoin.Transaction.DEFAULT_SEQUENCE - 1 }
        )`

Thanks.
