### ISSUE TITLE
Signature Verification Example for P2SH(P2WPKH)

### ISSUE THREAD

**Issue by ngmiller** [bitcoinjs/bitcoinjs-lib#1278]
Apologies if this has been asked already, but can someone show me a quick example of validating the signature for a P2SH(P2WPKH) transaction? (pay-to-witness-public-key-hash wrapped in a pay-to-script-hash)

The [integration test](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L261) validates a basic P2PKH transaction, but I've been struggling to validate one for P2SH(P2WPKH). Broadcasting my raw transactions to testnet is working, but it's always good to validate this stuff in a test suite.

Thanks!

**Comment by dcousens** [comment]
@ngmiller what is the aim of your validation?

* Verify intent [to send X amount(s) to output(s) Y with Z fee and change W]? (hard)
* Verify ecdsa [signatures are valid for output(s) Y]? (easy)

**Comment by ngmiller** [comment]
@dcousens I got a notification for your follow up, but for some reason I'm not seeing it on GitHub now. Anyway, my aim to simply validate the inputs I've created in my transaction have valid segwit signature (when the UTXO being spent is a P2SH(P2WPKH) output)

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bitcoinjs-lib/pull/1279
