### ISSUE TITLE
Extract output addresses from hex transaction

### ISSUE THREAD

**Issue by devey** [bitcoinjs/bitcoinjs-lib#1282]
**Description:**

I'm trying to retrieve the output addresses from a hex transaction created this way:

```
import {
  TransactionBuilder as bitcoinTransactionBuilder,
  Transaction as BitcoinTransaction,
} from 'bitcoinjs-lib';


let transaction = bitcoinTransactionBuilder.fromTransaction(
  BitcoinTransaction.fromHex(transactionHex),
  network
);
```
as in https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/transaction_builder.js#L106.

On `transaction__tx.outs[0]` I have:

```
{
  script: Uint8Array(25)
  value: number
}
```

Is the output address encoded in `script`?
If so what is the process to extract it?

**Comment by dcousens** [comment]
@junderw and with that... TransactionBuilder shall become a closure...

**Comment by educob** [comment]
Hi junderw,

I tried your code above and I don't get any address for blocks read from hard disk (blkxxxxx.dat) as explained in this issue: [https://github.com/bitcoinjs/bitcoinjs-lib/issues/1286](url)

Please help me to obtain the address.

Thanks.

**Comment by educob** [comment]
This is the tx I get when reading from blk00000.dat

```
Transaction {
version: 1,
locktime: 0,
ins: 
[ { hash: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>,
index: 4294967295,
script: <Buffer 04 ff ff 00 1d 01 04 45 54 68 65 20 54 69 6d 65 73 20 30 33 2f 4a 61 6e 2f 32 30 30 39 20 43 68 61 6e 63 65 6c 6c 6f 72 20 6f 6e 20 62 72 69 6e 6b 20 ... >,
sequence: 4294967295,
witness: [] } ],
outs: 
[ { value: 5000000000,
script: <Buffer 41 04 67 8a fd b0 fe 55 48 27 19 67 f1 a6 71 30 b7 10 5c d6 a8 28 e0 39 09 a6 79 62 e0 ea 1f 61 de b6 49 f6 bc 3f 4c ef 38 c4 f3 55 04 e5 1e c1 12 de ... > } ] }
```
As you can see script is in buffer form so payments classes (p2pk, ...) reject it at the very beginning:
```
function p2pk (a, opts) {
  if (
    !a.input &&
    !a.output &&
    !a.pubkey &&
    !a.input &&
    !a.signature
  ) throw new TypeError('Not enough data')
```
So I get: `'Not enough data'` error.

But when I get a block from the node by calling `client.getBlockByHash` I get:
```
...
vout: 
[ { value: 0.00040514, n: 0, scriptPubKey: [Object] },
 { value: 2.86177728, n: 1, scriptPubKey: [Object] } ],
```
The script is an object so it has the attributes that payments classes expect.

So what it's happening is that when calling `bitcoin.Block.fromBuffer` the scripts are not processed at all and bitcoinjs-lib don't know how to read data from them.

Thanks.

**Comment by educob** [comment]
I made it work!!!!

I had to modify the library.

1) address.js I added:
`try { return payments.p2pk({ output, network }).address } catch (e) {}`

2) payments.p2pk I added:

```
const crypto = require('../crypto')
const bs58check = require('bs58check')
```

after
```
  lazy.prop(o, 'pubkey', function () {
    if (!a.output) return
    return a.output.slice(1, -1)
  })
```
I added:

```
  lazy.prop(o, 'hash', function () {
    if (a.pubkey || o.pubkey) return crypto.hash160(a.pubkey || o.pubkey)
  })
  lazy.prop(o, 'address', function () {
    if (!o.hash) return

    const payload = Buffer.allocUnsafe(21)
    payload.writeUInt8(network.pubKeyHash, 0)
    o.hash.copy(payload, 1)
    return bs58check.encode(payload)
  })
```
It works but I would appreciate a proper update of the library as I did copy/paste and a lot of guessing.
Thanks.

**Comment by junderw** [comment]
P2PK does not have an address.

Your modification is incorrect.

**Comment by educob** [comment]
But how do I know which address the bitcoins were sent to when the script is p2pk?

Doing this modification I got the real addresses (the satoshi 1st address)

Thanks.

**Comment by educob** [comment]
Ok. Thanks.

**Comment by junderw** [comment]
I believe this is concluded. Please re-open if needed.
