### ISSUE TITLE
Can't install in react-native

### ISSUE THREAD

**Issue by hassantauqeer** [bitcoinjs/bitcoinjs-lib#1284]
[fsevents] Success: "/Users/hassankhokhar/Documents/NativeReact/niks10App/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> tiny-secp256k1@1.0.1 install /Users/hassankhokhar/Documents/NativeReact/niks10App/node_modules/tiny-secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/native/addon.o
In file included from ../native/addon.cpp:4:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:340:28: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/hassankhokhar/.node-gyp/10.14.0/include/node/v8.h:5052:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/hassankhokhar/.node-gyp/10.14.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../native/addon.cpp:4:
../../nan/nan.h:1066:44: warning: 'ToString' is deprecated [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/hassankhokhar/.node-gyp/10.14.0/include/node/v8.h:2454:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/hassankhokhar/.node-gyp/10.14.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../native/addon.cpp:4:
../../nan/nan.h:1080:27: warning: 'WriteUtf8' is deprecated [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/hassankhokhar/.node-gyp/10.14.0/include/node/v8.h:2658:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/hassankhokhar/.node-gyp/10.14.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../native/addon.cpp:17:1: error: unknown type name 'secp256k1_context'; did you mean 'secp256k1_context_t'?
secp256k1_context* context;
^~~~~~~~~~~~~~~~~
secp256k1_context_t
/usr/local/include/secp256k1.h:50:41: note: 'secp256k1_context_t' declared here
typedef struct secp256k1_context_struct secp256k1_context_t;
                                        ^
../native/addon.cpp:22:3: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:53:28: error: unknown type name 'secp256k1_pubkey'
        bool isPoint (const T& x, secp256k1_pubkey& pubkey) {
                                  ^
../native/addon.cpp:64:32: error: unknown type name 'secp256k1_ecdsa_signature'
        bool isSignature (const T& x, secp256k1_ecdsa_signature& signature) {
                                      ^
../native/addon.cpp:70:45: error: unknown type name 'secp256k1_pubkey'
        v8::Local<v8::Object> pointAsBuffer (const secp256k1_pubkey& public_key, const uint32_t flags) {
                                                   ^
../native/addon.cpp:79:63: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                            ^
../native/addon.cpp:79:89: error: use of undeclared identifier 'SECP256K1_EC_UNCOMPRESSED'
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                                                      ^
../native/addon.cpp:80:42: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info[index]->IsUndefined()) return SECP256K1_EC_COMPRESSED;
                                                       ^
../native/addon.cpp:81:40: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                return info[index]->BooleanValue() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                     ^
../native/addon.cpp:81:66: error: use of undeclared identifier 'SECP256K1_EC_UNCOMPRESSED'
                return info[index]->BooleanValue() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                               ^
../native/addon.cpp:86:38: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
                                                   ^
../native/addon.cpp:87:42: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info[index]->IsUndefined()) return SECP256K1_EC_COMPRESSED;
                                                       ^
../native/addon.cpp:88:40: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                return info[index]->BooleanValue() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                     ^
../native/addon.cpp:88:66: error: use of undeclared identifier 'SECP256K1_EC_UNCOMPRESSED'
                return info[index]->BooleanValue() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                               ^
../native/addon.cpp:99:2: error: unknown type name 'secp256k1_pubkey'
        secp256k1_pubkey public_key;
        ^
../native/addon.cpp:110:2: error: unknown type name 'secp256k1_pubkey'
        secp256k1_pubkey public_key;
        ^
../native/addon.cpp:133:2: error: unknown type name 'secp256k1_pubkey'
        secp256k1_pubkey a, b;
        ^
../native/addon.cpp:135:19: error: use of undeclared identifier 'b'
        if (!isPoint(pB, b)) return THROW_BAD_POINT;
                         ^
../native/addon.cpp:137:8: error: unknown type name 'secp256k1_pubkey'
        const secp256k1_pubkey* points[] = { &a, &b };
              ^
../native/addon.cpp:137:44: error: use of undeclared identifier 'b'
        const secp256k1_pubkey* points[] = { &a, &b };
                                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
4 warnings and 20 errors generated.
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hassankhokhar/Documents/NativeReact/niks10App/node_modules/tiny-secp256k1
gyp ERR! node -v v10.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hassankhokhar/.npm/_logs/2018-12-10T13_34_04_006Z-debug.log

**Comment by coreyphillips** [comment]
I made a guide to help with the RN setup process for bitcoinjs-lib 4.0.2 here: https://gist.github.com/coreyphillips/928ae27ccea69cd0b494d13ad2b3f27d

There's also a RN compatible repo here (https://github.com/coreyphillips/rn-bitcoinjs-lib) with setup instructions if you ever need it for reference. 

Hope this helps :-)

**Comment by junderw** [comment]
You have `-ferror-limit=` for gcc set to 20. raise this limit.
