### ISSUE TITLE
bitcoin.Block.fromBuffer. How to get the utxo address from scriptPubKey in buffer form.

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1286]
Hello.

I am reading the blockchain from hard disk (the blkxxxxx.dat files)

I run `bitcoin.Block.fromBuffer(rawblock)`
The utxos have the scriptPubKey in buffer form so I cannot run `bitcoin.address.fromOutputScript `which accepts an object.

How do I get the utxo address from the buffer scriptPubKey?

Thanks.

**Comment by junderw** [comment]
Re-open if needed.
