### ISSUE TITLE
Installation fails with tiny-secp256k1 on node v10 for v10.9.0 and earlier

### ISSUE THREAD

**Issue by arik-so** [bitcoinjs/bitcoinjs-lib#1288]
>   CXX(target) Release/obj.target/secp256k1/native/addon.o
> In file included from ../native/addon.cpp:4:
> ../../nan/nan.h:1081:96: error: too many arguments to function call, expected at most 4, have 5
>         length_ = string->WriteUtf8(v8::Isolate::GetCurrent(), str_, static_cast<int>(len), 0, flags);
>                   ~~~~~~~~~~~~~~~~~                                                            ^~~~~

Here is the final output of the error log:

> 5 warnings and 1 error generated.
> make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/Users/ariks/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
> gyp ERR! System Darwin 18.2.0
> gyp ERR! command "/Users/ariks/.nvm/versions/node/v10.9.0/bin/node" "/Users/ariks/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/ariks/Developer/[…]/node_modules/tiny-secp256k1
> gyp ERR! node -v v10.9.0
> gyp ERR! node-gyp -v v3.7.0
> gyp ERR! not ok 
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! tiny-secp256k1@1.0.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the tiny-secp256k1@1.0.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/ariks/.npm/_logs/2018-12-17T18_49_57_607Z-debug.log

**Comment by junderw** [comment]
I'll look into it.

**Comment by junderw** [comment]
This broke as well.
```
$ node -v
v10.9.0
$ node-gyp -v
v3.0.3
```

But this installed fine.
```
$ node -v
v10.13.0
$ node-gyp -v
v3.0.3
```

I also tested against v10.14.2 and it worked.

Could you try installing the latest node?

```
$ nvm install v10 # installs latest v10 variant.
```

**Comment by junderw** [comment]
looks like a bug with v10.9.0...

**Comment by kento1218** [comment]
It seems to be fixed in nan@2.12.1 https://github.com/nodejs/nan/pull/833

**Comment by aminmazi** [comment]
I can not install bitcoinjs-lib too,
environment:
```
node-gyp -v:
v3.8.0
```
 ```
node -v
v11.6.0
```
the error:
```
Error: Command failed: AppData\Local\Programs\Python\Python37-32\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd \node_modules\tiny-secp256k1
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0

npm ERR! tiny-secp256k1@1.0.1 install: `node-gyp rebuild`
```
installing `windows-build-tools` didn't help.
does everybody know that what should I do?

**Comment by kento1218** [comment]
@aminmazi That error is not related to this issue. You may be using python 3 but it’s not supported by node-gyp.

**Comment by aminmazi** [comment]
> @aminmazi That error is not related to this issue. You may be using python 3 but it’s not supported by node-gyp.

Thank you for your reply. 
but my python version is 2.7:
```
python -v 
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
```
I'm totaly stuck now :(

**Comment by johnta0** [comment]
It seems that this issue can be closed.

**Comment by athergeek** [comment]
Just incase anyone is having this issue and wants to fix it witout installing python 3, if you are using Anacode you can switch your env using command **activate env-python-2.7**
Assuming your python 2.7 environemnt name is env-python-2.7

see all available enviornments in Anaconda

**conda env list**

**Comment by dendisuhubdy** [comment]
Python2 seems to be unsupported soon. When are you going to move to Python3?

**Comment by junderw** [comment]
What do you mean "you"?

python 2 is used by node-gyp

we use node-gyp

If you'd like to make a version of node-gyp that uses python 3, let us know.

**Comment by GoodFaithParadigm8** [comment]
Had this same issue with node v12.18.3.

Installing node v10.14.2 corrected the problem.

**Comment by junderw** [comment]
> Had this same issue with node v12.18.3.
> 
> Installing node v10.14.2 corrected the problem.

It installs properly for me:

```
$ node -v
v12.18.3
$ npm -v
6.14.11
$ npm install --no-progress --silent 2>&1 >/dev/null && echo SUCCESS
SUCCESS
```

**Comment by GoodFaithParadigm8** [comment]
> $ npm install --no-progress --silent 2>&1 >/dev/null && echo SUCCESS
> SUCCESS

No npm chatter? Unfortunately I closed all the terminal(s) that had my error messages.  Windows 10 build 19041.985 . Both Windows and WSL2. As stated, installing v10.14.2 corrected the problem - on WSL2, specifically.

**Comment by junderw** [comment]
The problem with npm is that lots of error messages appear, but that doesn't mean the installation failed.
Sometimes post-install scripts of certain dependencies are failing and reverting to some fallback etc.

`npm install --no-progress --silent --no-audit` is the most quiet way to perform npm install...

Then all you need to do is figure out if the command failed or succeeded... in bash (posix shells) that would be adding `&& echo SUCCESS` etc. since the command after && will only perform if the previous succeeded.

For Windows, I don't know how you'd do that.
