### ISSUE TITLE
undefined is not an object (evaluating 'bitcoin.HDNode.fromSeedHex

### ISSUE THREAD

**Issue by prodigaLaugh** [bitcoinjs/bitcoinjs-lib#1295]
generate private key is wrong by path

**Comment by junderw** [comment]
HDNode is for <=v3

Current version (v4.0.2) does not have HDNode

Try:
`npm install bip32`

Then:
```javascript
const HDNode = require('bip32')
```

**Comment by prodigaLaugh** [comment]
it is wrong.code follows:


const bitcoin = require('bitcoinjs-lib'),
    HDNode = require('bip32'),
       bip39 = require('bip39');


let seedBuffer = bip39.mnemonicToSeed(mnemonic);
        let seed = seedBuffer.toString('hex');
        let seedHex = bip39.mnemonicToSeedHex(mnemonic, password);

let root = bitcoin.HDNode.fromSeedHex(seedHex);

**Comment by junderw** [comment]
> let root = bitcoin.HDNode.fromSeedHex(seedHex);

It is wrong because you are using bitcoin.HDNode when I just told you we don't support it anymore. Get rid of the `bitcoin.`

> let root = HDNode.fromSeedHex(seedHex);
