### ISSUE TITLE
HDNode.fromSeedHex is not a function

### ISSUE THREAD

**Issue by prodigaLaugh** [bitcoinjs/bitcoinjs-lib#1296]
Can not generate private key by path. Code follows:

const bitcoin = require('bitcoinjs-lib'),
    HDNode = require('bip32'),
       bip39 = require('bip39');

 let seedBuffer = bip39.mnemonicToSeed(mnemonic);
        let seed = seedBuffer.toString('hex');
        let seedHex = bip39.mnemonicToSeedHex(mnemonic, password);

let root = HDNode.fromSeedHex(seedHex);
let child0 = root.derivePath("m/44'/60'/0'/0");

**Comment by junderw** [comment]
show us your error.

**Comment by junderw** [comment]
also, seed and seedBuffer are not being used.

**Comment by dcousens** [comment]
https://github.com/bitcoinjs/bip32/blob/907ffb6a8ef8e94591804e4786054f5d09776065/index.js#L296-L301

**Comment by prodigaLaugh** [comment]
I want to generate private key by path. My package.json are as follows:
  
"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@tradle/react-native-http": "^2.0.1",
    "assert": "^1.4.1",
    "bip32": "^1.0.2",
    "bip39": "^2.5.0",
    "bitcoinjs-lib": "^4.0.2",
    "browserify-zlib": "^0.1.4",
    "buffer": "^5.2.1",
    "buffer-reverse": "^1.0.1",
    "console-browserify": "^1.1.0",
    "constants-browserify": "^1.0.0",
    "dns.js": "^1.0.1",
    "domain-browser": "^1.2.0",
    "ethereumjs-util": "^6.0.0",
    "ethereumjs-wallet": "^0.6.2",
    "https-browserify": "0.0.1",
    "mocha": "^5.2.0",
    "path-browserify": "0.0.0",
    "prop-types": "^15.6.2",
    "punycode": "^1.4.1",
    "querystring-es3": "^0.2.1",
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera",
    "react-native-crypto": "^2.1.2",
    "react-native-gesture-handler": "^1.0.10",
    "react-native-image-picker": "^0.27.1",
    "react-native-level-fs": "^3.0.1",
    "react-native-modalbox": "^1.6.0",
    "react-native-os": "^1.2.2",
    "react-native-qrcode": "^0.2.7",
    "react-native-qrcode-scanner": "^1.1.0",
    "react-native-randombytes": "^3.5.1",
    "react-native-root-toast": "^3.0.1",
    "react-native-storage": "^1.0.0-beta.0",
    "react-native-swipe-list-view": "^1.5.0",
    "react-native-tcp": "^3.3.0",
    "react-native-udp": "^2.3.1",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^3.0.0",
    "readable-stream": "^1.0.33",
    "stream-browserify": "^1.0.0",
    "string_decoder": "^0.10.31",
    "timers-browserify": "^1.4.2",
    "tty-browserify": "0.0.0",
    "url": "^0.10.3",
    "vm-browserify": "0.0.4"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.2",
    "react-test-renderer": "16.6.1",
    "rn-nodeify": "github:mvayngrib/rn-nodeify"
  },
  "jest": {
    "preset": "react-native"
  },
  "react-native": {
    "zlib": "browserify-zlib",
    "console": "console-browserify",
    "constants": "constants-browserify",
    "crypto": "react-native-crypto",
    "dns": "dns.js",
    "net": "react-native-tcp",
    "domain": "domain-browser",
    "http": "@tradle/react-native-http",
    "https": "https-browserify",
    "os": "react-native-os",
    "path": "path-browserify",
    "querystring": "querystring-es3",
    "fs": "react-native-level-fs",
    "_stream_transform": "readable-stream/transform",
    "_stream_readable": "readable-stream/readable",
    "_stream_writable": "readable-stream/writable",
    "_stream_duplex": "readable-stream/duplex",
    "_stream_passthrough": "readable-stream/passthrough",
    "dgram": "react-native-udp",
    "stream": "stream-browserify",
    "timers": "timers-browserify",
    "tty": "tty-browserify",
    "vm": "vm-browserify",
    "tls": false
  },


Code follows:
    const bitcoin = require('bitcoinjs-lib'),
           HDNode = require('bip32'),
           bip39 = require('bip39');

        const { describe, it } = require('mocha')
        const assert = require('assert')
function getAddress (node, network) {
    return bitcoin.payments.p2pkh({ pubkey: node.publicKey, network }).address
}

        let seedBuffer = bip39.mnemonicToSeed(mnemonic);
        let seed = seedBuffer.toString('hex');
        let seedHex = bip39.mnemonicToSeedHex(mnemonic, password);

        const node = bip32.fromSeed(seedBuffer)
        const string = node.toBase58()
        const restored = bip32.fromBase58(string)

        assert.equal(getAddress(node), getAddress(restored)) // same public key
        assert.equal(node.toWIF(), restored.toWIF()) // same private key

Here is the final output of the error log:
![image](https://user-images.githubusercontent.com/23735606/50209253-40ed5800-03ae-11e9-889d-14d2d69ad0b1.png)

I don't know if it is a configuration problem of the dependency package or a method call.

**Comment by junderw** [comment]
Look at the comment here: https://github.com/bitcoinjs/bitcoinjs-lib/issues/976#issuecomment-425904199

There is a gist someone wrote for react-native
