### ISSUE TITLE
Having hard time generating address from private hex

### ISSUE THREAD

**Issue by KingZee** [bitcoinjs/bitcoinjs-lib#1301]
Tried following this : https://github.com/bitcoinjs/bitcoinjs-lib/blob/4ae06003c4b38aa2335a152e12a003d8f4dee889/test/integration/basic.js#L24

```javascript
it('can generate an address from a SHA256 hash', function () {
  var hash = bitcoin.crypto.sha256('correct horse battery staple')
  var d = bigi.fromBuffer(hash)

  var keyPair = new bitcoin.ECPair(d)
  var address = keyPair.getAddress()

  assert.strictEqual(address, '1C7zdTfnkzmr13HfA2vNm5SJYRK6nEKyq8')
})
```

This is deprecated? I'm getting TypeError: bitcoin.ECPair is not a constructor.
How can I generate a pair using my known private key (in hex)?

**Comment by junderw** [comment]
Look at the tests for the module you're looking for.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/v4.0.2/test/ecpair.js#L41-L46

```javascript
const bitcoin = require('bitcoinjs-lib')
const keyBuffer = Buffer.from('1234abcd......1234abcd', 'hex')
const keyPair = bitcoin.ECPair.fromPrivateKey(keyBuffer)
```

Let me know if you need help finding anything. The tests are easy to read if you take the time to read them.

**Comment by SatStackr** [comment]
I'm sortof struggling with the same thing, when I do this:

> const keyBuffer = Buffer.from('1234abcd......1234abcd', 'hex')

My console shows an error `Buffer is not defined`

I realize this example code is more than 2 years old. Should I use something else instead of 'Buffer' with today's version of bitcoinjs?

**Comment by junderw** [comment]
Nope. Buffers still work.

You just don't have Buffers wherever it is you're trying to run the code.

Buffers are a nodejs standard API, and can only be used in the browser / react etc. when they are packed into your app via webpack etc.
