### ISSUE TITLE
Import the private key into the wallet; how to generate an address based on the private key?

### ISSUE THREAD

**Issue by prodigaLaugh** [bitcoinjs/bitcoinjs-lib#1303]
BTC:
Previously generated private key and address based on path；code show as below：
        let mnemonic = bip39.generateMnemonic();
    
        const seedBuffer = bip39.mnemonicToSeed(mnemonic)

        const seed = seedBuffer.toString('hex');//seed
        let seedHex = bip39.mnemonicToSeedHex(mnemonic, password);//seedHex

        const root = bip32.fromSeed(seedBuffer)
        const rootKey = root.toBase58();//root key 
 
        const BTCChild = root.derivePath("m/44'/0'/0'/0/0")
        const BTCAdress = getAddress(BTCChild)//adress by path
        const BTCPrivateKey = BTCChild.toWIF()//private key 

Now import the private key into the wallet; how to generate an address(BTCAdress) based on the private key(BTCAdress);

**Comment by prodigaLaugh** [comment]
Now import the private key into the wallet; how to generate an address(BTCAdress) based on the private key(BTCPrivateKey)?

**Comment by junderw** [comment]
```javascript
const bitcoin = require('bitcoinjs-lib')
const keyPair = bitcoin.ECPair.fromWIF(BTCPrivateKey)
const BTCAddressFromWIF = getAddress(keyPair, keyPair.network)
```

**Comment by junderw** [comment]
Please format your questions properly.

Thank you.

**Comment by prodigaLaugh** [comment]
Sorry ！ Wallet business is not familiar.   I do not know how to describe. Thank you very much!

**Comment by pegassusbroker** [comment]
> Ahora importa la clave privada en la billetera; ¿Cómo generar una dirección (BTCAdress) basada en la clave privada (BTCPrivateKey)?

LA DIRECCION PUBLICA SE PUEDE GENERAR DESDE LA CLAVE PLIVADA WIF "5KMA1fY8AiDQgc8jgGEQPCTKXHm4FgUQ6rbvSkTsYPNY5sfufRv'  O DESDE UNA CLAVE HEX "cacc96cbe474b7eab87da1b35eac0206193ca2776cabd862450d83835e6b2ae6"

TIENES QUE ESPECIFICAR QUE ES LO QUE QUIERES HACER
