### ISSUE TITLE
Basic Questions: How to validate private key with bitcoinjs-lib?

### ISSUE THREAD

**Issue by rlaace423** [bitcoinjs/bitcoinjs-lib#1306]
Hello, I'm newbie of bitcoinjs-lib. 

I have a function which get private key as a parameter, and I can't find any method to validate private key. 

Is there any method? or any fancy ways?

**Comment by junderw** [comment]
Where are you getting the private key from?

What format is it in? (if you know, if not I can guess from where you got it.)

**Comment by rlaace423** [comment]
I use Private key

WIF, compressed
WIF, uncompressed

both testnet and mainnet!

**Comment by junderw** [comment]
```javascript
const btc = bitcoinjs.networks.bitcoin
const tbtc = bitcoinjs.networks.testnet
let verified
try {
  bitcoinjs.ECPair.fromWIF(yourwif, [btc, tbtc])
  verified = true
} catch() {
  verified = false
}
```

should work.

**Comment by rlaace423** [comment]
Awesome! I'll try :)

**Comment by junderw** [comment]
Please reopen if you had any trouble.
