### ISSUE TITLE
Buffer.alloc is not a function error when run via browserify

### ISSUE THREAD

**Issue by robbsolter** [bitcoinjs/bitcoinjs-lib#1310]
I am trying to run one of the examples in the browser using browserify

I create a new index.js like this

```
bip32 = require('bip32')

let node = bip32.fromBase58('xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi')

let child = node.derivePath('m/0/0')

console.log(child)
```

Then I run browserify
`browserify crypto.js -o crypto-browser.js`

Then I open an html page with `<script src="crypto-browser.js"></script>` in it and see the following error in the browser console `Uncaught TypeError: Buffer.alloc is not a function`

**Comment by dabura667** [comment]
You are using browserify wrong. Please learn how to use browserify before posting an issue.

**Comment by junderw** [comment]
You need to pack NodeJS standard global entries into your output by using the require parameter.

I am not an expert in browserify, but I just tried building another project that uses bitcoinjs-lib 4.0.2 as a dependency and all the parts including bip32 work fine.

Please look up how to use browserify properly, or ask for help on browserify forums.

**Comment by davidapple** [comment]
Your documentation on using Browserify is appalling and your reluctance to support your js library in the browser is baffling. #1220

**Comment by junderw** [comment]
@davidapple Pull requests for documentation are welcome. And our library works with browserify. We are not browserify support so if you have questions on how to use browserify, ask them.

There are a million ways to convert nodeJS into a browser bundle, browserify, webpack, etc. etc... and we can't be expected to know all the ins and outs of each and every method. (Not to mention react-native, which is not even really 1:1 compatible with the browser to begin with, so people run into problems with webpacked browser bundles in react-native all the time)

We support any problems / questions concerning the usage of the library itself, and make no guarantees or support (as in answer questions about) tooling that surrounds the NodeJS ecosystem.

However, a simple `-r bitcoinjs-lib -s bitcoin` with browserify will work, and you will get the bitcoin variable in the browser to use bitcoinjs-lib.

Also, keep things civil, please... calling the library "appalling" and claiming reluctance that we don't have and calling it "baffling" is not the way a grown adult should handle themselves.
