### ISSUE TITLE
Hello, everyone. I have an urgent question.

### ISSUE THREAD

**Issue by liuhuanhui** [bitcoinjs/bitcoinjs-lib#1316]
Hello, everyone. I have a question. Where are the publics and privates of bip32 objects in the network coming from and what are their functions? If my coin is a chain modified from bitcoin, how do these two values be set? Thank you very much.

```
const network = {
	messagePrefix: '\x188BitCoin Signed Message:\n',
	bip32: {
		public: 76067358,
		private: 76066276
	},
	pubKeyHash: pubKeyHash,
	scriptHash: scriptHash,
	wif: wif
}
```

**Comment by junderw** [comment]
those are constants for BIP32 HD key encoding.

most altcoins don't change them, but ask someone who is well knowledged in your coin.

Since this repo is only about Bitcoin, I will close this issue.
