### ISSUE TITLE
Hello, I want to add a time field when I generate the transaction signature. The present object structure is: #20

### ISSUE THREAD

**Issue by liuhuanhui** [bitcoinjs/bitcoinjs-lib#1317]
Hello, I want to add a time field when I generate the transaction signature. The present object structure is:
```
function Transaction () {
  this.version = 1
  this.locktime = 0
  this.ins = []
  this.outs = []
}
```

**Comment by junderw** [comment]
Bitcoin does not have a time field in its transactions.

Any change that can not adequately be implemented by an additional Network object must be implemented by forking this repository.

Implementation details for your specific coin are outside scope for this repository, so please fork us.
