### ISSUE TITLE
Bitcoinjs unable to push transaction,getting script not verified error

### ISSUE THREAD

**Issue by surabhiv** [bitcoinjs/bitcoinjs-lib#1321]
I am newbie to bitcoinjs-lib using it for bitcoin testnet transaction.I am successfully generate the transaction hash on checking that hash getting error Script was NOT verified successfully...Is there any way to verify it. Please guide me.Thanks in advance.

Hash:-

0200000001120d3109f5465e29de173f144845c811261bdac177653b70a47e7cb883a28832010000006b483045022100a82a2069268dff2b76e13163f5cb73f062d7afa9c3f246d32c52280b8bfbdce3022077753e5b2e32835e983a3b56d77a341adf66dbdfe7174109608e53e98e62ea5801210212d52ea28aef968281e4ea669a5020bf3a1a0b11ef2b9209204992e5015b9417ffffffff02e8030000000000001976a914908d238fb958612be0d634060e8d8ef62f780c2188ac357dcb00000000001976a914db26599d6019a93656ff01f5359126ba23adc07888ac00000000

While decoding it I am getting

<pre>
{
    "addresses": [
        "mthGgBTX1kxibjXwXxy5jraBNtTsajpqSx", 
        "n1ViDg2ExYS8HAhvZdn93UE5unRBiVNNiE"
    ], 
    "block_height": -1, 
    "block_index": -1, 
    "confirmations": 0, 
    "double_spend": false, 
    "fees": 0, 
    "hash": "927c5bff320b17d6825cd763266e9e26e88072804209324f8229769750ac2ac7", 
    "inputs": [
        {
            "age": 0, 
            "output_index": 1, 
            "prev_hash": "3288a283b87c7ea4703b6577c1da1b2611c84548143f17de295e46f509310d12", 
            "script": "483045022100a82a2069268dff2b76e13163f5cb73f062d7afa9c3f246d32c52280b8bfbdce3022077753e5b2e32835e983a3b56d77a341adf66dbdfe7174109608e53e98e62ea5801210212d52ea28aef968281e4ea669a5020bf3a1a0b11ef2b9209204992e5015b9417", 
            "script_type": "empty", 
            "sequence": 4294967295
        }
    ], 
    "outputs": [
        {
            "addresses": [
                "mthGgBTX1kxibjXwXxy5jraBNtTsajpqSx"
            ], 
            "script": "76a914908d238fb958612be0d634060e8d8ef62f780c2188ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 1000
        }, 
        {
            "addresses": [
                "n1ViDg2ExYS8HAhvZdn93UE5unRBiVNNiE"
            ], 
            "script": "76a914db26599d6019a93656ff01f5359126ba23adc07888ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 13335861
        }
    ], 
    "preference": "low", 
    "received": "2019-01-17T11:44:46.104823644Z", 
    "relayed_by": "3.84.36.119", 
    "size": 226, 
    "total": 13336861, 
    "ver": 2, 
    "vin_sz": 1, 
    "vout_sz": 2
}
</pre>

but unable to push this hash.Because on pushing it getting 

<b>
 BitcoindException(super=com.neemre.btcdcli4j.core.BitcoindException: Error #-26: 16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation), code=-26)
</b>

**Comment by junderw** [comment]
you signed with the wrong key.

**Comment by junderw** [comment]
also, I don't see your input transaction on testnet.

do you have a link?

**Comment by junderw** [comment]
this is testnet, just post everything.

all your code, private keys, everything.

testnet is not real money.

I can't help you with the amount of information you have given.

**Comment by surabhiv** [comment]
ok...sure

/**code for generating address and  private key start**/
var bitcoin = require('bitcoinjs-lib');
const networks = require('bitcoinjs-lib').networks;
var bip39 = require('bip39');
var bip32 = require('bip32');
var crypto = require('crypto');
var blockexplorer = require('blockchain.info/blockexplorer').usingNetwork(3);
var exchange = require('blockexplorer');
var pushtx = require('blockchain.info/pushtx');

// console.log(networks);

var keyPair = bitcoin.ECPair.makeRandom();
var testnet = bitcoin.networks.testnet;
var {address} = bitcoin.payments.p2pkh({pubkey : keyPair.publicKey, network: testnet});

var mnemonic = bip39.generateMnemonic();
console.log(mnemonic);
var seed = bip39.mnemonicToSeed(mnemonic);
 // var master = bitcoin.HDNode.fromSeedBuffer;

var master=bip32.fromSeed(seed);

console.log(master);
 
 var derived = master.derivePath("m/44'/0'/0'/0/0");

  // var chain=derived.chainCode;
 // var address = derived.getAddress();
 var privateKey = derived.toWIF();

 console.log(address,keyPair.publicKey);

 console.log(privateKey);

/** code for generating address and  private key end **/

O/p:-

**Address**:-**n1ViDg2ExYS8HAhvZdn93UE5unRBiVNNiE**
**Public key**:-**<Buffer 03 79 d4 7a 41 1a ea 72 b3 6e 2b ca 61 b3 a1 07 66 98 dd bb 04 a6 9e 3f a3 75 14 2b b9 31 a6 c0 6d>**
**Private key**:-**Kwer8jcK9BqqkeriwvjaBMQAQyPVRhtBhtaPyHFYd6RDMyAyTaH8**

/**transaction js start**/

var bitcoin = require('bitcoinjs-lib');
const networks = require('bitcoinjs-lib').networks;
var bip39 = require('bip39');
var bip32 = require('bip32');
var crypto = require('crypto');
var blockexplorer = require('blockchain.info/blockexplorer').usingNetwork(3);
var exchange = require('blockexplorer');
var pushtx = require('blockchain.info/pushtx');


var hash = crypto.pbkdf2Sync('amount attack swift fence sister dry together equip jazz rack topic sentence', '123', 2048, 48, 'sha512');
var cipher = crypto.createCipher('aes-256-cbc', hash);
// console.log(cipher);
var encrypted = '';
encrypted+= cipher.update('Kwer8jcK9BqqkeriwvjaBMQAQyPVRhtBhtaPyHFYd6RDMyAyTaH8', 'utf8', 'hex');
encrypted+= cipher.final('hex');
// console.log(encrypted);

var wallet = {
				address:'n1ViDg2ExYS8HAhvZdn93UE5unRBiVNNiE',
				enckey: encrypted, pass:hash,
				coins:0.11232601, utxos: []
};


//var wallet={ address: 'myRG2t2xEA22K2oZLSPp8GhZko4zwQ5SUw',enckey:'c392833e1f13cb0375f795a8c36ba5e91a585b36999be32ff7ca981033719e291a5d31ef2f4b7ddfc852a7f7d332875a5ae02188a134d690c2c25807351e4996',pass:'f92ae55b55c9d7b235c1cc835e5a0f43d15ba203d42f16ecf1696b34e31a5a719eb57e191dd481c9d49bddc07c870123',coins:0.11232601,utxos: [] }


const hash1 = crypto.pbkdf2Sync('amount attack swift fence sister dry together equip jazz rack topic sentence','123',2048, 48,'sha512');
const cipher1 = crypto.createDecipher('aes-256-cbc',hash1);

// console.log(cipher1);
 let decrypted = '';
 decrypted += cipher1.update(encrypted,'hex','utf8');
 decrypted += cipher1.final('utf8');
 const key=bitcoin.ECPair.fromWIF('Kwer8jcK9BqqkeriwvjaBMQAQyPVRhtBhtaPyHFYd6RDMyAyTaH8',bitcoin.networks.testnet);

 //console.log(keyPair.publicKey);

 var unspn=blockexplorer.getUnspentOutputs(wallet.address);
 
 blockexplorer.getUnspentOutputs(wallet.address).then(result => {
      wallet.utxos = result.unspent_outputs;
    

        console.log(wallet);
      
       const sending =1000;  

       const txb = new bitcoin.TransactionBuilder(bitcoin.networks.testnet);
       // console.log(txb);


       txb.setVersion(2);

       var input = 0;

       for(let utx of wallet.utxos){

       	txb.addInput(utx.tx_hash_big_endian,utx.tx_output_n);
       	input += utx.value;
       	if (input >= sending) break;
       }

       console.log(input);

       const change1=13337861-sending;


           //const fee=input-(sending+change1);
           const fee=1000;

          console.log(fee);


          const change = input - (sending + fee);




        console.log(change);


        	txb.addOutput('mthGgBTX1kxibjXwXxy5jraBNtTsajpqSx',sending);

        	
       		if(change) txb.addOutput('n1ViDg2ExYS8HAhvZdn93UE5unRBiVNNiE',change);

         	txb.sign(0,key);

        	const raw = txb.build().toHex();


        	console.log(raw);
        
         const promise = pushtx.usingNetwork(3).pushtx(raw);


        // console.log(promise);
		// const message = 'Transaction Submitted';
		// promise.then(result => {
  //   	if (result === message) { console.log('success') } 
  //   	else { console.log('fail') } 
  //  });


 });

/**Transaction js end**/

**Comment by junderw** [comment]
> Address:-n1ViDg2ExYS8HAhvZdn93UE5unRBiVNNiE
> Public key:-<Buffer 03 79 d4 7a 41 1a ea 72 b3 6e 2b ca 61 b3 a1 07 66 98 dd bb 04 a6 9e 3f a3 75 14 2b b9 31 a6 c0 6d>
> Private key:-Kwer8jcK9BqqkeriwvjaBMQAQyPVRhtBhtaPyHFYd6RDMyAyTaH8

your private key and public key don't match.

for that private key, your public key is :
0212D52EA28AEF968281E4EA669A5020BF3A1A0B11EF2B9209204992E5015B9417

**Comment by surabhiv** [comment]
Many Thanks...Problem solved.Now transaction done successfully.

**Comment by bennji789** [comment]
how was the problem solved? @surabhiv

**Comment by bennji789** [comment]
could you share more on how you resolved the issue, I am having the same issue

**Comment by hasnentai** [comment]
@junderw  Even I am getting the same error can you please explain root cause?
I am new to Crypto world

**Comment by junderw** [comment]
> @junderw Even I am getting the same error can you please explain root cause?
> I am new to Crypto world

The root cause is that the script is invalid. One of the following could be wrong.

- You made the transaction incorrectly.
- You signed using the wrong key.
- You don't have enough signatures (for multisig etc.)

**Comment by hasnentai** [comment]
@junderw Sorry if I am taking your time. But can you verify where I am wrong in the code?

This my code it gives me a HEX but I guess its wrong Hash. I would be great if you help me with this.

++++++Code++++++++++

```
var btcLib = require("bitcoinjs-lib");
var bip39 = require("bip39");


const seed = bip39.mnemonicToSeed(
  "acoustic avoid arrive lens accident damage witness cable interest humor child actress"
);

seed.then((val) => {
  let testnet = btcLib.networks.testnet;

  //console.log(btcLib.ECPair.toWIF())
  var ec = btcLib.bip32.fromSeed(val, testnet);
  var rroot = ec.derivePath("m/44'/0'/0'/0/1");
  console.log(rroot.toWIF());

  var key = btcLib.ECPair.fromWIF(rroot.toWIF(), testnet);

  var tx = new btcLib.TransactionBuilder(testnet);
  tx.addInput(
    "39625eb5990c471e7754b7034f1438cd8191a1b45c306ea37a1b82fd43c5502f",
    1
  );
  tx.addOutput("mqCvHAYLNxkPy3tdtfG59ymcpRJ6XMwZeP", 10512);

  tx.sign(0, key);
  console.log(tx.build().toHex());
});
```


+++++++Decoded Transaction+++++++++++
```
{
    "addresses": [
        "mqaaFZKLunn7RQsKytLsRufqZWdF8PhaE7", 
        "mqCvHAYLNxkPy3tdtfG59ymcpRJ6XMwZeP"
    ], 
    "block_height": -1, 
    "block_index": -1, 
    "confirmations": 0, 
    "double_spend": false, 
    "fees": 9488, 
    "hash": "916437040cc8102cb51585068e1c254d100002cdd077a37cacb2bbc5df2895f3", 
    "inputs": [
        {
            "addresses": [
                "mqaaFZKLunn7RQsKytLsRufqZWdF8PhaE7"
            ], 
            "age": 1697329, 
            "output_index": 1, 
            "output_value": 20000, 
            "prev_hash": "39625eb5990c471e7754b7034f1438cd8191a1b45c306ea37a1b82fd43c5502f", 
            "script": "473044022063bb24d8ee0a6d1a8dfe5ebc25cb4ce3812e1bcda06603fd29543e11490699020220298ac4547f8b2dca2e04ffc869e17cf7d4eb494d519bee886920830cfe49d52b012102c54ce42aeb49788e1b4e17c22f411b23c7d57ff3ad22305d07f3d8d0c1e047c0", 
            "script_type": "pay-to-pubkey-hash", 
            "sequence": 4294967295
        }
    ], 
    "outputs": [
        {
            "addresses": [
                "mqCvHAYLNxkPy3tdtfG59ymcpRJ6XMwZeP"
            ], 
            "script": "76a9146a4816958356fd44e195efa3ca1ae41298aaea4988ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 10512
        }
    ], 
    "preference": "high", 
    "received": "2020-04-12T22:34:42.59397138Z", 
    "relayed_by": "18.208.172.225", 
    "size": 191, 
    "total": 10512, 
    "ver": 2, 
    "vin_sz": 1, 
    "vout_sz": 1
}
```

**Comment by junderw** [comment]
Your input and your key don't match:

Input address: mqaaFZKLunn7RQsKytLsRufqZWdF8PhaE7
Your key address: mkfmusQVXpa9vWS8yLQtmMMzE41NXqHCjV

**Comment by hasnentai** [comment]
@junderw How can I make this work. As I said I am new to this Crypto world and can you help me with a working example of the same.

Thanks for your response.

**Comment by junderw** [comment]
use the correct key..... I don't know which key you used, but whatever it was it isn't the key you are generating.

Your code will work if the input was for the key you had.

**Comment by hasnentai** [comment]
@junderw Thanks a lot I figured out where I was wrong

**Comment by majidkarimizadeh** [comment]
@junderw 
what key we should use for input? i really confused...

**Comment by junderw** [comment]
The key they used and the address that owns the output they are spending in the input do not match.

You should use the key that actually unlocks the locking script of the output that your input spends.

**Comment by ming200825** [comment]
{"error": "Error validating transaction: Error running script for input 0 referencing 4b62a6cd85994a6b5b5b481981a75ae4f0bde484a61f2b742a398f96ccc97f6a at 0: Script was NOT verified successfully.."}

`{
    "addresses": [
        "tb1q5yek0dk7x3lzj83ap5gq7pqukwmzwehn6gedv6",
        "mmFb6Kq8dkrGt7w8V2YCR3FNW4cLQHAuu9"
    ],
    "block_height": -1,
    "block_index": -1,
    "confirmations": 0,
    "double_spend": false,
    "fees": 23052,
    "hash": "8eb0f8dbb2bd56965ff612c7595bab175bd0802388d27f9b2438f6f84d087a55",
    "inputs": [
        {
            "addresses": [
                "tb1q5yek0dk7x3lzj83ap5gq7pqukwmzwehn6gedv6"
            ],
            "age": 2419396,
            "output_index": 0,
            "output_value": 2845730,
            "prev_hash": "4b62a6cd85994a6b5b5b481981a75ae4f0bde484a61f2b742a398f96ccc97f6a",
            "script_type": "pay-to-witness-pubkey-hash",
            "sequence": 4294967295,
            "witness": [
                "30440220409a542cd43443e1ead46cd9341f82d124fed695796f1accef57ec0c1f2d5b6b02204fbbf17783a99a38bcce2fb04ab17af615a249c9dd2c9905f1117384c5e14cac01",
                "033a82c9194962df066c880ef915aa6d19be5d0da9e281e7020800fc2af069a30f"
            ]
        }
    ],
    "outputs": [
        {
            "addresses": [
                "mmFb6Kq8dkrGt7w8V2YCR3FNW4cLQHAuu9"
            ],
            "script": "76a9143ee8d109defca604d9df8909e8f5c10af6a09f2488ac",
            "script_type": "pay-to-pubkey-hash",
            "value": 100000
        },
        {
            "addresses": [
                "tb1q5yek0dk7x3lzj83ap5gq7pqukwmzwehn6gedv6"
            ],
            "script": "0014a13367b6de347e291e3d0d100f041cb3b62766f3",
            "script_type": "pay-to-witness-pubkey-hash",
            "value": 2722678
        }
    ],
    "preference": "high",
    "received": "2023-02-10T02:21:26.506204548Z",
    "relayed_by": "44.200.229.140",
    "size": 225,
    "total": 2822678,
    "ver": 1,
    "vin_sz": 1,
    "vout_sz": 2,
    "vsize": 144
}`
