### ISSUE TITLE
How to watch and respond to a transaction.

### ISSUE THREAD

**Issue by Patrick-W-McMahon** [bitcoinjs/bitcoinjs-lib#1322]
I'm trying to have a call back to change a record in a database by responding to a transaction when I see it on the block chain. The user will send me the txid and I need to confirm that the txid is on the blockchain been confirmed a set amount of times and has the right amount. If all that passes I want to do a call back to update some data on my side. Do you have any tutorials on how to watch for a transaction, confirm the transaction and do an action if the transaction is valid. I want to be able to set the block depth is this possible. That way I know the transaction is valid.

**Comment by junderw** [comment]
unfortunately, such operations are outside of scope for this library.

I would suggest looking into NBXplorer. It can be run on top of bitcoind and give you a nice REST API to interface with and will accept extended public keys to watch potentially unlimited addresses with one call.
