### ISSUE TITLE
Is it safe to represent Satoshi in JS number?

### ISSUE THREAD

**Issue by yuhlau** [bitcoinjs/bitcoinjs-lib#1329]
I am aware that the value argument of `addOutput()` in `Transaction` and `TransactionBuilder` are accepting number, instead of `string` or `BigNumber`. So I would like to know is it safe to simply passing numbers around, will there be any chance of losing precision?

The research I have done so far concludes that the total supply of Bitcoin in unit of Satoshi is still fall inside the max safe integer JS can support:

In `src/types.js`
```
const SATOSHI_MAX = 21 * 1e14
function Satoshi (value) {
  return typeforce.UInt53(value) && value <= SATOSHI_MAX
}
```

And the MAX_SAFE_INTEGER of JS is specified in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
which covers the SATOSHI_MAX

However, I would still like to seek for more opinions on this. Is there measures I should be aware when dealing with the amount value in this lib.

Thanks in advance.

**Comment by junderw** [comment]
You can deal with 4.2 times the total number of Bitcoins that will ever be made in satoshi and you will still get perfect precision.

Some altcoins however have much larger max amounts, so bitcoinjs-lib is not suited for them.
```
> Number.MAX_SAFE_INTEGER.toString(16)
'1fffffffffffff'
> Number.MAX_SAFE_INTEGER.toString(16).length / 2
7
> (21 * 1e6 * 1e8).toString(16)
'775f05a074000'
> (21 * 1e6 * 1e8).toString(16).length / 2
6.5
> Number.MAX_SAFE_INTEGER / (21 * 1e6 * 1e8)
4.289142502257615
```

**Comment by yuhlau** [comment]
Thanks for your detail explanation, closing the issue.
