### ISSUE TITLE
Is it normal for the signed hex of the same transaction to be the same?

### ISSUE THREAD

**Issue by yuhlau** [bitcoinjs/bitcoinjs-lib#1331]
Hi, I am sorry if this question is stupid. But I have came across some articles mentioning that if someone use a weak signature and the two signatures shared the same nonce k, there is a possibility to reveal the private key [1][2]

May I know if this library have used a stronger signature method?

I am not an expert on Cryptography, so the closest is I tried to sign the same transaction multiple times. I realize that the signed hex is always the same. So I wonder does this means it is using the same nonce k when signing? Or it is totally irrelevant?

Thanks in advance.

p.s. Many sites point to the article http://www.nilsschneider.net/2013/01/28/recovering-bitcoin-private-keys.html but the site is now down
[1] https://eprint.iacr.org/2014/848.pdf
[2] https://github.com/tintinweb/ecdsa-private-key-recovery

**Comment by junderw** [comment]
Let me know if you still have any questions.
