### ISSUE TITLE
Signed transactions always reference orphaned blocks

### ISSUE THREAD

**Issue by alex-ppg** [bitcoinjs/bitcoinjs-lib#1332]
Hey everyone,

There appears to be an issue when I am signing outgoing transactions referencing 6+ confirmation inputs. For instance, I am trying to build a transaction with the following input hash: [bcb2927ba3b89681ce54cd93b640c8eb3f5277cbdda3a4feffa01d1ccdc6ba83](https://live.blockcypher.com/btc/tx/bcb2927ba3b89681ce54cd93b640c8eb3f5277cbdda3a4feffa01d1ccdc6ba83/)

The serialized transaction looks like this: 02000000000101bcb2927ba3b89681ce54cd93b640c8eb3f5277cbdda3a4feffa01d1ccdc6ba830100000017160014ec3b80e9ea809cbd8a7ffe6ab5dadbeddc429670ffffffff010e1900000000000017a914d9311982ba4d0cc87ed3586b4a45b39224a2f759870247304402207e517beda0709f465f07af3fb4294429eaeb406ea867d5ecc48a8e04c8dda0ae0220494d09614fded663bd97801763d9f8e7534039f63e3cf9e3536d0bbfd4afc1790121023bfb26e7ab33f11cafbb0ec73d63371a76108182005bb66b757beecfa5f5fd8c00000000

Decoded:
```
{
    "addresses": [
        "3MVRNg5KPzL14kToNVs6ZFpNsLksqSXWgN"
    ], 
    "block_height": -1, 
    "block_index": -1, 
    "confirmations": 0, 
    "double_spend": false, 
    "fees": 0, 
    "hash": "f9b7635597beb6fc117e765b9d8434269c70b24be3c330b5892eaa46531263aa", 
    "inputs": [
        {
            "age": 0, 
            "output_index": 1, 
            "prev_hash": "83bac6cd1c1da0fffea4a3ddcb77523febc840b693cd54ce8196b8a37b92b2bc", 
            "script": "160014ec3b80e9ea809cbd8a7ffe6ab5dadbeddc429670", 
            "script_type": "empty", 
            "sequence": 4294967295, 
            "witness": [
                "304402207e517beda0709f465f07af3fb4294429eaeb406ea867d5ecc48a8e04c8dda0ae0220494d09614fded663bd97801763d9f8e7534039f63e3cf9e3536d0bbfd4afc17901", 
                "023bfb26e7ab33f11cafbb0ec73d63371a76108182005bb66b757beecfa5f5fd8c"
            ]
        }
    ], 
    "outputs": [
        {
            "addresses": [
                "3MVRNg5KPzL14kToNVs6ZFpNsLksqSXWgN"
            ], 
            "script": "a914d9311982ba4d0cc87ed3586b4a45b39224a2f75987", 
            "script_type": "pay-to-script-hash", 
            "value": 6414
        }
    ], 
    "preference": "low", 
    "received": "2019-02-12T09:51:58.224416602Z", 
    "relayed_by": "54.173.242.23", 
    "size": 106, 
    "total": 6414, 
    "ver": 2, 
    "vin_sz": 1, 
    "vout_sz": 1
}
```

When attempting to publish the transaction manually, I am receiving the following error: 
Transaction f9b7635597beb6fc117e765b9d8434269c70b24be3c330b5892eaa46531263aa orphaned, missing reference 83bac6cd1c1da0fffea4a3ddcb77523febc840b693cd54ce8196b8a37b92b2bc

I do not understand how an orphaned issue occurs when the transaction input has 6+ confirmations.

The code segment that generates the transaction is as follows:
```
// Bitcoin (Nested SegWit in P2SH for backwards compatibility): https://bitcoincore.org/en/segwit_wallet_dev/
const keyPair = ECPair.fromPrivateKey(privateKey);
const { address, redeem } = BTCPayments.p2sh({
    redeem: BTCPayments.p2wpkh({ pubkey: keyPair.publicKey })
});
const tx = new BTCTransactionBuilder();
let total = 0;
const outs = 2;
let ins = 0;

do {
    total = total + utxos[ins].value;
    tx.addInput(utxos[ins].tx_hash_big_endian, utxos[ins].tx_output_n);
    ins++;
} while (
    amount + (getTXByteLength(ins, outs) * optimal_fee) > total &&
    utxos.length > ins
);

tx.addOutput(
    address,
    total - amount + (getTXByteLength(ins, outs) * optimal_fee)
);
// Send amount to recipient
tx.addOutput(to, +amount);

tx.sign(0, keyPair, redeem.output, null, +total);
return tx.build().toHex();
```

**Comment by junderw** [comment]
the hash endianness is backwards.

is there a utxos[ins].tx_hash_little_endian available?

**Comment by alex-ppg** [comment]
Shouldn't a different error be shown instead?

I thought big Endian was required, flipping it is a one liner like the following, correct?

```
tx_hash_big_endian.match(/.{2}/g).reverse().join("")
```

**Comment by junderw** [comment]
it's usually called txid or something

I highly doubt your API only gives you the big endian hash which is useless in most cases.

FYI the "transaction ID" is the little endian representation of the transaction hash.

**Comment by alex-ppg** [comment]
Yeah I was indeed reversing it manually as I thought big endian hashes were required by the library. Isn't the error message about orphaned blocks ambiguous though. As the hashes refer to nonexistent (presumably) transactions how were they included in orphaned blocks?

**Comment by junderw** [comment]
The error says nothing about blocks.

You're pointing to a *parent* transaction that doesn't exist.

No parent.

Orphan.

Also, we don't make the errors for whatever API you're using, or Bitcoin Core. So discussing its wording here is off topic.

**Comment by alex-ppg** [comment]
I understand that the error message is unrelated to your library as it was produced by presumably the bitcoind client as the API used provides raw messages. 

I simply stated I found it ambiguous as the message wrote, in verbatim, orphaned block rather than transaction which means a block that was mined but not included in the blockchain. This is not correct in my case at least.

Thank you for your assistance.

**Comment by junderw** [comment]
You wrote:

Transaction f9b7635597beb6fc117e765b9d8434269c70b24be3c330b5892eaa46531263aa orphaned, missing reference 83bac6cd1c1da0fffea4a3ddcb77523febc840b693cd54ce8196b8a37b92b2bc

Which says nothing about blocks. Unless you didn't send the full error.

**Comment by alex-ppg** [comment]
You are correct. It was my misunderstanding as I simply copy pasted the error above and the results were referring to orphaned blocks and how it occurs sometimes. I've edited the original issue closure comment so as to not misguide other readers.

Nonetheless, I think that random hashes should not be considered as orphaned transactions but I understand the technical limitation in discriminating between orphaned and non-existent transactions. Thank you for your time and divulgance in the conversation.
