### ISSUE TITLE
help with pay to script hash spend

### ISSUE THREAD

**Issue by osoese** [bitcoinjs/bitcoinjs-lib#1333]
```
var OP_INT_BASE = 80;
var aliceSecret = require('randombytes')(32);

var aliceSecretHash = bitcoin.crypto.hash160(aliceSecret);

console.log("secret: "+aliceSecret+" "+aliceSecret.toString("hex"));
console.log("secret hash: "+aliceSecretHash+" "+aliceSecretHash.toString("hex"));

var aliceToBobRedeemScript = bitcoin.script.compile([
    bitcoin.opcodes.OP_IF,
    bitcoin.opcodes.OP_HASH160,
    aliceSecretHash,
    bitcoin.opcodes.OP_EQUALVERIFY,
    testnetWIFpk2,
    bitcoin.opcodes.OP_CHECKSIG,
    bitcoin.opcodes.OP_ELSE,
    OP_INT_BASE + 2,
    testnetWIFpk,
    testnetWIFpk,
    OP_INT_BASE + 2,
    bitcoin.opcodes.OP_CHECKMULTISIG,
    bitcoin.opcodes.OP_ENDIF
],bitcoin.networks.testnet);

var aliceToBobP2SHAddress = bitcoin.payments.p2sh({ redeem: { output: aliceToBobRedeemScript, network: bitcoin.networks.testnet }, network: bitcoin.networks.testnet });
console.log("address that redeems "+JSON.stringify(aliceToBobP2SHAddress));
```

I then sent a small transaction to the address that appears in that JSON and would like to now unlock the unspent tx output and send it back to a traditional wallet only using the secret. Can you help me craft the spend transaction? I tried to find it for a while now and am just confused... This is where I stopped

I stored alice secret from step one and recreated the redeem script below...

```
var aliceSecretHash = bitcoin.crypto.hash160(aliceSecret);
console.log(JSON.stringify(aliceSecret));
console.log("secret: "+aliceSecret+" "+aliceSecret.toString("hex"));
console.log("secret hash: "+aliceSecretHash+" "+aliceSecretHash.toString("hex"));

var aliceToBobRedeemScript = bitcoin.script.compile([
    bitcoin.opcodes.OP_IF,
    bitcoin.opcodes.OP_HASH160,
    aliceSecretHash,
    bitcoin.opcodes.OP_EQUALVERIFY,
    testnetWIFpk2,
    bitcoin.opcodes.OP_CHECKSIG,
    bitcoin.opcodes.OP_ELSE,
    OP_INT_BASE + 2,
    testnetWIFpk,
    testnetWIFpk,
    OP_INT_BASE + 2,
    bitcoin.opcodes.OP_CHECKMULTISIG,
    bitcoin.opcodes.OP_ENDIF
],bitcoin.networks.testnet);

var aliceToBobP2SHAddress = bitcoin.payments.p2sh({ redeem: { output: aliceToBobRedeemScript, network: bitcoin.networks.testnet }, network: bitcoin.networks.testnet });

console.log("address that redeems "+JSON.stringify(aliceToBobP2SHAddress));

console.log(aliceToBobRedeemScript);
console.log(aliceToBobRedeemScript.toString("hex"));
console.log(aliceToBobRedeemScript.toString('utf8'));
console.log(JSON.parse(JSON.stringify(aliceToBobRedeemScript))["data"].toString());

const txb = new bitcoin.TransactionBuilder();
txb.addInput("string of tx", 0, null, aliceToBobRedeemScript)
````

how do I sign that transaction with the redeem script and direct the output to any address I want?

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/pull/1185/files

This pull request has a few examples of creating and signing complex p2sh.

But there are also examples in the integration tests currently.

**Comment by osoese** [comment]
I appreciate the reply. My example is probably bad. What I am trying to do is just spend a script puzzle in this case submit the "aliceSecret" without anything else. Is there an example of this?

**Comment by dabura667** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/bd0be2f3430e7a5a81b776129befc004b48635da/test/integration/cltv.js#L97-L114

Here's a good example of how to create a signature and insert it into the scriptSig properly.

Wait, are you asking us to teach you what scriptSig is needed for your "puzzle"?

In which case, assuming someone gave you this puzzle for a reason, no help here.

If you know how to solve it, but you don't know the mechanics of solving it with BitcoinJS, then we can help.

**Comment by dabura667** [comment]
Also, your ELSE statement is a 2-of-2 multisig of the same key `testnetWIFpk`

**Comment by osoese** [comment]
Thank you for the reply - I am using bitcoinlib-js to make my own script puzzle I can cash...

In step one I am making a p2sh with a secret:
```
var aliceSecret = require('randombytes')(32);
var aliceSecretHash = bitcoin.crypto.hash160(aliceSecret);
```
and I store the hash which is then recreated in the redemption step (step 2 below)
I write the redeem script with the sole intention of using the first part of the if condition ONLY WITH THE "aliceSecretHash" and I am pretty confident that part is written incorrectly....I would appreciate seeing how to write it correctly, then I use that redeem script to make a p2sh address that I sent a small transaction to
```
var aliceToBobP2SHAddress = bitcoin.payments.p2sh({ redeem: { output: aliceToBobRedeemScript, network: bitcoin.networks.testnet }, network: bitcoin.networks.testnet }).address;
```
then step 2 I am trying to sign the input of a new transaction using only the "aliceSecretHash" and then enter an output to an address I wish to receive the funds 

Can you help me correct my code to do that?

**Comment by junderw** [comment]
> Can you help me correct my code to do that?

Unfortunately, no. This issue board is for issues with the library itself. Your question is about Script language in general, and you should ask it at a place like StackOverflow:

https://bitcoin.stackexchange.com/

**Comment by osoese** [comment]
Just so you know I followed your link on the main page that says ask for any examples not shown by submitting a request "here" and the request was for a paytoscript hash secret word redeem script.

**Comment by junderw** [comment]
we already have an example of advanced script usage.

You are asking for a specific use that you personally will gain from and not many others will gain anything. It will just make our integration tests longer.

I highly recommend stack exchange for questions about the protocol itself, asking a question here will take much longer to get a response than over there.
