### ISSUE TITLE
Readable private key?

### ISSUE THREAD

**Issue by mesqueeb** [bitcoinjs/bitcoinjs-lib#1337]
I'm still new to bitcoin and experimenting a lot with bitcoinjs-lib.
How do I create a readable string from a private key?
This is my current setup:

```js
      const seed = bip39.mnemonicToSeed(seedPhrase) // you'll use this in #3 below
      const bitcoinNetwork = bitcoin.networks.testnet
      const hdMaster = bitcoin.bip32.fromSeed(seed, bitcoinNetwork) // seed from above
      const keyPair = hdMaster.derivePath('m/0')
      // try to get private key as readable string
      const privateKeyBuffer = Buffer.from(keyPair.privateKey)
      const privateKey = privateKeyBuffer.toString('utf8')
      console.log('privateKey → ', privateKey)
      // fail to get private key as readable string
      const { address } = bitcoin.payments.p2pkh({ pubkey: keyPair.publicKey })
```
any ideas for me?

**Comment by junderw** [comment]
1. Don't export / import individual private keys when you are using BIP32 HD keys. IT IS DANGEROUS.
2. `.toString('hex')` and `.toString('base64')` are readable string representations of Buffers, but no crypto apps use them. The accepted format for individual private keys are WIF. But like I said, IF YOU ARE USING HD KEYS, ONLY STORE/EXPORT/IMPORT YOUR SEEDPHRASE OR AN XPUB.

This is important. You will lose money.

**Comment by mesqueeb** [comment]
Thanks so much for the info! With `HD KEYS` do you mean the _mnemonic seed phrase_?

**Comment by junderw** [comment]
Yes. The string in `seedPhrase` in your example is the only private data you should be exporting / importing.

**Comment by vipertechofficial** [comment]
https://www.npmjs.com/package/bs58
