### ISSUE TITLE
p2sh(p2wpkh) get correct hash to sign offline

### ISSUE THREAD

**Issue by blmalone** [bitcoinjs/bitcoinjs-lib#1342]
I've written code that will allow me to get the hash of the data that I need to sign, retrieve the signature and add it back to the transaction (this is for a p2pkh utxo).

```javascript
        const txb = new btc.TransactionBuilder(test);
        const utxos = await sendRequest(`${addressDataURL}${bitcoinTestNetAddress}/?unspentOnly=true`, "GET");
        const p2pkh = btc.payments.p2pkh({ pubkey: Buffer.from(compressedPublicKey, "hex"), network: test });
        txb.setVersion(1);
        txb.addInput(utxos.txrefs[0].tx_hash, utxos.txrefs[0].tx_output_n);
        txb.addOutput(aliceP2pkh.address, 500000); 
        const inCompleteTransaction = txb.buildIncomplete();
        // We want to get the hash of the whole tx (SIGHASH_ALL)
        const inputHash = inCompleteTransaction.hashForSignature(0, p2pkh.output, SIGHASH_ALL);
        
        //Get the signature and serialise it while producing the scriptSig

        inCompleteTransaction.setInputScript(0, Buffer.from(scriptSig, "hex"));
        const tx = inCompleteTransaction.toHex();
```

I'd like to do the exact same for p2sh(p2wpkh). Here's some code:

```javascript
        const utxosBob: Utxo[] = requestReponseBob.txrefs;

        const txb1 = new btc.TransactionBuilder(currentNetwork);
        txb1.addInput(utxosBob[0].tx_hash, utxosBob[0].tx_output_n);
        txb1.addOutput(aliceCompatibilityAddress, utxosBob[0].value - 2500);
        const txIncomplete = txb1.buildIncomplete();

        // arg 2 of hashForWitnessV0 needs the locking script value
        const hashForTS = txIncomplete.hashForWitnessV0(0, Buffer.from(utxosBob[0].script, "hex"), utxosBob[0].value, SIGHASH_ALL);

        //Get signature with the above hash as <digestSignature>

        const encodedSig = btc.script.signature.encode(Buffer.from(digestSignature, "hex"), SIGHASH_ALL);

        txIncomplete.setWitness(0, [
            encodedSig,
            Buffer.from("0348eeec6c4dd1f191867cc990f00a2154cd83e922837d279511e81afa80101d54", "hex")
        ]);
        const transaction = txIncomplete.toHex();
```

HEX: `02000000000101bf1c38cad67003b5179ad3f4f470ea35716a4917a3e02d8eb2b489f103e8e94c0000000000ffffffff0129307b000000000017a91451fe6a095ebb3fef83884d97435f8929696a6fdd8702473044022013a842c5c965e925c46edd220d8910886f28c35ef965d372afdf1923a8b941c002202dec8fe88324051bfaf051ac2914a5ffc60abce0f960d768a8c8c12b910bafb101210348eeec6c4dd1f191867cc990f00a2154cd83e922837d279511e81afa80101d5400000000`

I get the following error when I try to push it via blockcypher: `Error validating transaction: Rejected script for input 0 referencing 4ce9e803f189b4b28e2de0a317496a7135ea70f4f4d39a17b50370d6ca381cbf at 0..`

**Comment by junderw** [comment]
You also need to set the input script as well for the P2SH part:

setInputScript should have a script that looks like 160014xxxxxxxx (16 means "push 22 bytes", and the 0014xxxx is the p2wpkh output... which becomes the redeemscript in this transaction.)

Let me know if you have any other questions.
