### ISSUE TITLE
cors error with blockexplorer from blockchain.info

### ISSUE THREAD

**Issue by ShabanGomaa** [bitcoinjs/bitcoinjs-lib#1355]
With reactjs, when I use  blockexplorer from "blockchain.info";
I got error:
Access to fetch at 'https://testnet.blockchain.info/unspent?active=address' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by junderw** [comment]
disable CORS as the error suggests.

This is a problem with your client code or bci's server, so I will close this issue, as it has nothing to do with this library.

Thanks for the report.
