### ISSUE TITLE
TypeError: bitcoin.ECPair is not a constructor

### ISSUE THREAD

**Issue by cancerts** [bitcoinjs/bitcoinjs-lib#1359]
var keys   = new bitcoin.ECPair(bigi.fromHex(my_hex_private_key));

**Comment by junderw** [comment]
please read the examples.

That usage is old and outdated.

**Comment by cancerts** [comment]
> please read the examples.
> 
> That usage is old and outdated.

how used ?

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/ecpair.js

**Comment by galki** [comment]
The above link is outdated and I assume the new one is [https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/ecpair.spec.ts]()

Example:
```js
import { ECPair } from 'bitcoinjs-lib';

const keys = ECPair.fromPrivateKey(Buffer.from(my_hex_private_key, 'hex'));
```
If you want to sign a transaction, for instance, you can then:
```js
tmpTx.pubkeys = [];
tmpTx.signatures = tmpTx.tosign.map(function (tosign, _n) {
  tmpTx.pubkeys.push(keys.publicKey.toString('hex'));
  return keys.sign(Buffer.from(tosign, 'hex')).toString('hex');
});
```

**Comment by Akkii4** [comment]
> The above link is outdated and I assume the new one is https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/ecpair.spec.ts
> 
> Example:
> 
> ```js
> import { ECPair } from 'bitcoinjs-lib';
> 
> const keys = ECPair.fromPrivateKey(Buffer.from(my_hex_private_key, 'hex'));
> ```
> 
> If you want to sign a transaction, for instance, you can then:
> 
> ```js
> tmpTx.pubkeys = [];
> tmpTx.signatures = tmpTx.tosign.map(function (tosign, _n) {
>   tmpTx.pubkeys.push(keys.publicKey.toString('hex'));
>   return keys.sign(Buffer.from(tosign, 'hex')).toString('hex');
> });
> ```
> 
> However, this results in a signature with the wrong length... any solutions?

Try this it worked for me, actually your methods create signature of length 128 chars while this is 140 chars-:
` tmptx.pubkeys = [];
                tmptx.signatures = tmptx.tosign.map(function (tosign, _n) {
                        tmptx.pubkeys.push(keys.publicKey.toString('hex'));
                        let signature = keys.sign(Buffer.from(tosign, "hex"));
                        let encodedSignature = bitcoin.script.signature.encode(signature,bitcoin.Transaction.SIGHASH_ALL);
                        let hexStr = encodedSignature.toString("hex").slice(0, -2); 
                        return hexStr;
                        //return keys.sign(Buffer.from(tosign, 'hex')).toString('hex');
                      });`
