### ISSUE TITLE
Typeforce error

### ISSUE THREAD

**Issue by fire-lizard** [bitcoinjs/bitcoinjs-lib#1365]
I am trying to send satoshis from one wallet to another. Here is what I am doing:

```javascript
    let tx = new Btc.TransactionBuilder(RegTest);
    let keyPair1 = generateAddressFromSHA256Hash('J@vaScr1pt');
    let keyPair2 = generateAddressFromSHA256Hash('B*tc0in');
    let amountWeHave = 5000000000;
    let amountToKeep = 4900000000;
    let transactionFee = 1000;
    let amountToSend = amountWeHave - amountToKeep - transactionFee;
    let s = '2d742aa8409ee4cd8afcb2f59aac6ede47b478fafbca2335c9c04c6aedf94c9b';
    tx.addInput(s, 0);
    let pk2 = { pubkey: keyPair2.publicKey };
    let pk1 = { pubkey: keyPair1.publicKey };
    tx.addOutput(Btc.payments.p2pkh(pk2), amountToSend);
    tx.addOutput(Btc.payments.p2pkh(pk1), amountToKeep);
    tx.sign(0, keyPair1);
    let tx_hex = tx.build().toHex();
    console.log('our beautiful transaction: ', tx_hex);
```

And here what I get on tx.addOutput (any of those two):

> C:\Users\SOVA\Desktop\node_modules\bitcoinjs-lib\node_modules\typeforce\index.js    :190    

> throw tfSubError(e, i)                                                              ^                           

> Error: Expected property "0" of type Buffer, got Object
--

Any ideas what should I do in order to fix the issue?

Thanks in advance.

**Comment by junderw** [comment]
use `Btc.payments.p2pkh(pk2).output`

payments return objects. addOutput needs a string (address) or a Buffer (output)

Let me know if this doesn't fix it.
