### ISSUE TITLE
"Inconsistent  Network" error when using RegTest network

### ISSUE THREAD

**Issue by fire-lizard** [bitcoinjs/bitcoinjs-lib#1366]
I am new to blockchain and bitcoin, and I am trying to make a simple transaction:

``` JavaScript
function generateAddressFromSHA256Hash(passphrase) { 
    let hash = Btc.crypto.sha256(passphrase); 
    const keyBuffer = Buffer.from(hash, { network: RegTest });
    const keyPair = Btc.ECPair.fromPrivateKey(keyBuffer);
    return keyPair; 
}

const RegTest = Btc.networks.regtest;
let tx = new Btc.TransactionBuilder(RegTest);
let keyPair1 = generateAddressFromSHA256Hash('J@vaScr1pt');
let keyPair2 = generateAddressFromSHA256Hash('B*tc0in');
let amountWeHave = 5000000000;
let amountToKeep = 4900000000;
let transactionFee = 1000;
let amountToSend = amountWeHave - amountToKeep - transactionFee;
let s = '2d742aa8409ee4cd8afcb2f59aac6ede47b478fafbca2335c9c04c6aedf94c9b';
tx.addInput(s, 0);
let pk2 = { pubkey: keyPair2.publicKey, network: RegTest };
let pk1 = { pubkey: keyPair1.publicKey, network: RegTest };
tx.addOutput(Btc.payments.p2pkh(pk2).output, amountToSend);
tx.addOutput(Btc.payments.p2pkh(pk1).output, amountToKeep);
tx.sign(0, keyPair1); // I am getting error here
let tx_hex = tx.build().toHex();
console.log('our beautiful transaction: ', tx_hex);
```

When I am trying to sin it I am getting the following error:

> TypeError: Inconsistent network
>                                                         at TransactionBuilder.sign 
> (C:\Users\SOVA\Desktop\node_modules\bitcoinjs-lib\sr c\transaction_builder.js:644:66)
--

Any ideas how to sign the transaction?

**Comment by junderw** [comment]
generateAddressFromSHA256Hash

it looks like it returns an ECPair
ECPair also has a network. Default is mainnet.

change the function to return a regtest ECPair

**Comment by fire-lizard** [comment]
Thank you so much! Solved the issue.

**Comment by vipertechofficial** [comment]
If you still encounter some issues with the network object trough using one outside of this library remind you that in one line of this library a comparison of the keypair's network prop and the transaction  builder one is of the "===" nature, thus if it is not the same variable, in fact you can't get it on the fly otherwise it will not be equals for JS.

Think about declaring the network variable once ONLY.
