### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by blmalone** [bitcoinjs/bitcoinjs-lib#1367]
`const p2pkh = bitcoin.payments.p2pkh({ pubkey: p2wpkh.pubkey }) // because P2WPKH is annoying`

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L305

The scriptCode does not make sense to me. Could this be clarified for P2SH-P2WPKH.

Thanks

**Comment by junderw** [comment]
Read the segwit BIP.

It says the prevout script for p2wpkh is p2pkh when generating the preimage.

Which is annoying when verifying.

**Comment by blmalone** [comment]
I've read bip143, but as far as I know this scriptCode is never executed. Am I right?

I understand the sequence of execution as:

1. `witness <signature> <pubkey>` and `scriptSig <0 <20-byte-key-hash-compressed-pub-key>> ` are pushed onto the stack.
Then the scriptPubKey: `HASH160 <20-byte-script-hash> EQUAL` is executed with redeemScript (`<0 <20-byte-key-hash-compressed-pub-key>>`) as the arg, eventually resulting in the execution of `CHECKSIG`.

**Comment by junderw** [comment]
not executed.

**Comment by blmalone** [comment]
Thank you, closing issue.
