### ISSUE TITLE
Clarify ECPair vs keyPair

### ISSUE THREAD

**Issue by mesqueeb** [bitcoinjs/bitcoinjs-lib#1370]
Hi!
Most examples use the term `ECPair`, but the readme doesn't talk about what that is. It might be good to add one sentence in the readme stating that it stands for **Elliptic Curve pair**.

I also wanted to ask what exactly the difference between an ECPair and a keyPair is as shown in the example below:
```js
const seed = await bip39.mnemonicToSeedAsync(seedPhrase)
const hdMaster = bitcoin.bip32.fromSeed(seed, network)
const keyPair = hdMaster.derivePath(path)
```
Is the `keyPair` above the same thing as an `ECPair` in this library?

**Comment by mmvphil** [comment]
There really is no help in this fkn git.  Very frustrating.   I bet nobody with knowledge will answer you .. some elitist bullshit.. IMO

**Comment by dabura667** [comment]
ECPair is the name of a class in this library.

keyPair is just a common variable name used for any object that contains a private key and a public key.

An ECPair object contains both a private key and a public key... so most people would name an instance of the ECPair class something like keyPair etc.

The BIP32 object you give in your example, also has a private key and a public key inside of it... so the thought process is the same.
