### ISSUE TITLE
[Question] How does bitcoin wallets and / or transaction synchronization work?

### ISSUE THREAD

**Issue by someApprentice** [bitcoinjs/bitcoinjs-lib#1384]
I'm new to bitcoins, and I don't understand how this library works. Do I need to run a working node (bitcoind) to synchronize this library with the entire internet?

I saw an example with testnet, and it was mentioned there that instead of testnet should be specified bitcoin network. Does it really work all over the internet? Why there is no need to register any connection settings?

**Comment by educob** [comment]
This library is not used to connect with a bitcoin node.
With this library you create private keys, sign transaccions, etc.
