### ISSUE TITLE
Elements/Liquid support

### ISSUE THREAD

**Issue by tiero** [bitcoinjs/bitcoinjs-lib#1386]
Any plans on iterate on this?

Anyhow can be added in the same way of litecoin or additional machinery for the confidential/blinded asset is needed?

**Comment by junderw** [comment]
Liquid support is outside of scope for this library.

Yes, a bit of reworking would be needed.

Addresses can have more than just hashes.
Transaction format would change, TransactionBuilder would need to support blinding.

This would best be managed as a fork.
