### ISSUE TITLE
Proposal for a core lib that allows configuring the secp256k1 dependency

### ISSUE THREAD

**Issue by zone117x** [bitcoinjs/bitcoinjs-lib#1393]
The `node-gyp` environment requirements are causing an increasing amount of issues for devs using our lib, which is heavily dependent on `bitcoinjs-lib` (which is dependent on `tiny-secp256k1`). 

Requiring the secp256k1 C source to be pulled and compiled is a good idea for the `don't trust, verify` security model. It makes sense to leave that as the default way that `bitcoinjs-lib` is packaged. 

However, it would be helpful for libs that consume `bitcoinjs-lib` to have the ability to easily configure the `tiny-secp256k1` dependency. For example, a consuming lib may only be intended for web usage and the native code could just be removed. Or, a consuming lib with a different security model could bundle in the pre-compiled native blobs for common platforms, or use a WASM compiled libsecp256k1. 

The current options for consumers libs to achieve this appear to be:
A) Fork `bitcoinjs-lib`, make the desired change, then upload and maintain a forked npm package, or
B) Try to manipulate child package dependencies with package lock files which is brittle, doesn't work with yarn, and has a slew of other issues. 

### Proposal

This approach has the goals: 
* Preserve the current behavior and security model of the `bitcoinjs-lib` and `tiny-secp256k1` packages. 
* Relatively easy to implement. 

Create a `secp256k1-interface` package that simply formalizes the existing implicit interface that is implemented by both `https://github.com/bitcoinjs/tiny-secp256k1/blob/master/native.js` and `https://github.com/bitcoinjs/tiny-secp256k1/blob/master/js.js`. 

Create a `bitcoinjs-lib-core` package. This could be the same source as the current lib but with two minor changes:
1. Depends on `secp256k1-interface` rather than a specific implementation (currently `tiny-secp256k1`).
1. Minor change that require an implementation of `secp256k1-interface` to be provided by a consuming lib. 

This original `bitcoinjs-lib` package would then have a dependency tree looking something like:
```
bitcoinjs-lib
├─┬ bitcoinjs-lib-core
│ └── secp256k1-interface
└── tiny-secp256k1
```

A consumer lib that wanted, for example, a web/js-only version of secp256k1 would look something like:
```
example-lib
├─┬ bitcoinjs-lib-core
│ └── secp256k1-interface
└── web-secp256k1-js
```

The libs consuming the `bitcoinjs-lib-core` lib would do something like:
```ts
//  bitcoinjs-lib/index.ts

import { configureSecp256k } from 'bitcoinjs-lib-core'
import secp256k1 from `tiny-secp256k1`

configureSecp256k(secp256k1)
```

```ts
// example-lib/index.ts

import { configureSecp256k } from 'bitcoinjs-lib-core'
import secp256k1 from `web-secp256k1-js`

configureSecp256k(secp256k1)
```

There are other projects with a similar "interface / core" lib structure from which to draw inspiration from, for example, the ipfs project has https://github.com/ipfs/interface-js-ipfs-core with a few implementation libs:
https://github.com/ipfs/js-ipfs
https://github.com/ipfs/js-ipfs-http-client

_(I'll update if I come across some other libs that fit this structure)_

 ----

Thoughts?

**Comment by junderw** [comment]
We were considering splitting off the native part to tiny-secp256k1-native and making it an optionalDependency of tiny-secp256k1.

I think we'll still do that.

However, your proposal sounds good.

I would like to do it in a way where backwards compatibility is maintained.

**Comment by zone117x** [comment]
Any idea how the git repo & npm lib structure should look in the github org? This might need to determine before submitting PRs. 

I see two reasonable options: 
1. This repo `bitcoinjs-lib` ends up containing the code for two npm packages -- the `bitcoinjs-lib-core` package and the current backwards-compatible `bitcoinjs-lib` package. Likewise, the `tiny-secp256k1` repo could follow same pattern -- contain the code for both `tiny-secp256k1-interface` and original lib. 
1. Create new repositories for `bitcoinjs-lib-core` and `tiny-secp256k1-interface`. 

I'm partial to option 1, but would understand if org would want to maintain a 1 repo per package setup. 
We should also keep in mind the git history preservation and unit test implications. 

Consider that the `bitcoinjs-lib-core` package would be something like 99% the same code as this current repo, and then this repo representing the original `bitcoinjs-lib` package will then contain the minimal amount of code described in the proposal. Seems like we want to preserve git history and github's url redirection feature for repo renames. 

Consider unit tests if the `bitcoinjs-lib-core` code is in a new repo. One way this could be done is having the core package keep `tiny-secp256k1` as a `devDependency` -- so that existing unit tests don't really need changed. 

The few ways to implement the proposal all seem relatively simple, just need the org maintainers to make the requisite decisions on organizing the libs/repos and guidance on where to submit the PRs.

**Comment by junderw** [comment]
Yes, I am the org maintainer for now.

I am currently on vacation and will sit down and discuss with some colleagues once I get home.

It's a great idea, but the devil is in the details.

**Comment by junderw** [comment]
tiny-secp256k1 starting from 1.1.2 now calls native bindings via an optionalDependency.
A current install will fallback on the JS implementation properly now.

It's not exactly what you propose, but for now it will work.

![スクリーンショット_2019-05-22_13-24-09](https://user-images.githubusercontent.com/11246316/58147428-5fc18480-7c95-11e9-99a1-b5dc7d760349.png)

**Comment by junderw** [comment]
I went ahead and wrote up the interface it would need to fulfill.
```typescript
interface Secp256k1EccLib {
  // checks if given DER encoded point is on the secp256k1 curve
  // returns true if on curve false if not
  isPoint(derEncodedPoint: Buffer): boolean;
  // checks if the given 32 byte buffer is between 1 and n - 1 where n
  // refers to the order of the curve
  // returns true if a valid private key
  isPrivate(privateKey: Buffer): boolean;
  // Takes a scalar 32 bytes, multiplies it by the generator to get a point
  // then takes the given DER encoded point and adds it to that point
  // if toCompressed is given and true the returned value is DER compressed
  // if toCompressed is not given, then copy the compressed-ness state of the
  // first argument given (DER encoded point)
  // returns the point resulting in the addition of the given point and the
  // calculated point from the given scalar
  pointAddScalar(
    derEncodedPoint: Buffer,
    scalar32Bytes: Buffer,
    toCompressed?: boolean,
  ): Buffer;
  // Given a DER encoded point, convert the encoding to compressed-ness based on
  // the second argument's boolean value
  // returns a DER encoded public key point
  pointCompress(derEncodedPoint: Buffer, toCompressed: boolean): Buffer;
  // Given a 32 byte scalar, calculate the point (pubkey).
  // if toCompressed is not given, treat it as true.
  // returns a DER encoded public key
  pointFromScalar(scalar32Bytes: Buffer, toCompressed?: boolean): Buffer;
  // Adds together two 32 byte Buffers and checks that
  // the result is a valid private key.
  // returns the sum modulo the curve order as a Buffer
  privateAdd(privateKey: Buffer, scalar32Bytes: Buffer): Buffer;
  // Signs the hash using the privateKey. (no hashing is performed inside)
  // Returns a 64 byte Buffer where the first 32 bytes are the r value
  // the last 32 bytes are the s value. r and s are both big endian.
  sign(hash: Buffer, privateKey: Buffer): Buffer;
  // Same as sign, but with extra entropy added into the RFC6979 nonce
  // generation. See RFC6979 and libsecp256k1 for details
  signWithEntropy(
    hash: Buffer,
    privateKey: Buffer,
    extraEntropy: Buffer,
  ): Buffer;
  // Given a hash, DER encoded public key buffer, and 64 byte signature Buffer
  // It returns true if the verification of the signature passes.
  verify(hash: Buffer, publicKey: Buffer, signature: Buffer): boolean;
}
```

I might add something like a new ecc.ts file with something like:

```typescript
let ecc: Secp256k1EccLib = require('tiny-secp256k1');

export function configureSecp256k1(newLib: Secp256k1EccLib): boolean {
  if (
    typeof newLib.isPoint !== 'function' ||
    typeof newLib.isPrivate !== 'function' ||
    typeof newLib.pointAddScalar !== 'function' ||
    typeof newLib.pointCompress !== 'function' ||
    typeof newLib.pointFromScalar !== 'function' ||
    typeof newLib.privateAdd !== 'function' ||
    typeof newLib.sign !== 'function' ||
    typeof newLib.signWithEntropy !== 'function' ||
    typeof newLib.verify !== 'function'
  ) {
    return false;
  }
  ecc = newLib;
  return true;
}

export { ecc };
```

Then use the ecc export internally and expose the configureSecp256k1 function...

Though checking the existense of functions doesn't seem like enough... I might want to run a test or two on each function to make sure the data I expect is returned.

(ie. this would be a great way to force people to use RFC6979 in their implementations)

However, down the road, ECC options should probably become async operations to allow for WASM implementations down the line...

But that would break backwards compatibility... so v6.

imo we should eventually utilize WASM... but WASM is still a bit far off...

Even if a WASM implementation doesn't make it into v6 we can at least change the interface to be async in preparation.

**Comment by junderw** [comment]
upon further consideration... I have decided against adding the ability to change the ECC library at runtime.

Instead, perhaps gathering the interface and the module require into one file will allow people to easily fork the library, and keep the patch maintaining to a minimum.

Either way, in the future we will look into adding an Async version of crypto operations that could potentially take advantage of WASM.
