### ISSUE TITLE
TS2694: Namespace '"..../node_modules/bitcoinjs-lib/types/index"' has no exported member 'ECPair'.

### ISSUE THREAD

**Issue by tkeidar** [bitcoinjs/bitcoinjs-lib#1403]
I'm getting this build error on ECPair although everything seems to work fine.

working with bitcoinjs-lib@5.0.3

**Comment by junderw** [comment]
This is a problem with your app.

ECPair is not exported.

please use one of the exported functions to create an ECPair object and the interface is ECPairInterface.

**Comment by junderw** [comment]
index does export the bundle of functions as ECPair.

Could you show sample code and sample tsconfig.json that gives this error?

**Comment by junderw** [comment]
aha, nvm, I understand the issue.

```typescript
import * as bitcoin from 'bitcoinjs-lib';

// this is incorrect, ECPair is not an interface or type
let keyPair: bitcoin.ECPair;

// this is an interface that you can use
let keyPair2: bitcoin.ECPairInterface;

**Comment by junderw** [comment]
This should fix the issue. I'll make a PR to export ECPairInterface on the top level.
