### ISSUE TITLE
Question about bl9cks

### ISSUE THREAD

**Issue by bobsaggit** [bitcoinjs/bitcoinjs-lib#1406]
Can you create blocks using this library And push them to the network if it supports external block adding same way as bitcoin rawtxs?

**Comment by junderw** [comment]
Yes.

Try it on bitcoind in regtest mode, where usually one or two attempts at the nonce will produce a valid block.

**Comment by bobsaggit** [comment]
Thanks @junderw Il have a look about see if I can't find an example of this.
