### ISSUE TITLE
How to sign transaction with hex private key

### ISSUE THREAD

**Issue by jeansouza** [bitcoinjs/bitcoinjs-lib#1407]
I'm trying to create a transaction using bitcoinjs-lib but Isn't working. I'm creating an address and using the hex private key:

```
keyPair.privateKey.toString('hex')
```

I need to use the hex private key because I already have hex private keys for existent addresses.

After creating the address (and using a faucet to send tBTC to it) I'm trying to create a transaction using the balance of this address, and I'm signing the inputs like this:

```
const ecPair = bitcoin.ECPair.fromPrivateKey(Buffer.from(privateKey, 'hex'), { network: bitcoin.networks.testnet })
...
txb.sign(0, ecPair)
```

When I try to broadcast the hex transaction to BlockCypher I get this error:

```
Error validating transaction: Error running script for input 0 referencing dfe0b24f207a167ad408028751392a34de70f3474d6d16c377b837c7d0e6e8d2 at 1: Script was NOT verified successfully..
```

Am I doing something wrong?

Thanks!

**Comment by junderw** [comment]
You seem to be using a p2sh address.

Is it a p2sh-p2pkh address?

`txb.sign(0, ecPair)` is not sufficient.

Please look at the integration tests.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/b3def6b4006683190657ef40efa7a8bcbb78b5cd/test/integration/transactions.js#L126

**Comment by jeansouza** [comment]
Awesome!

Now it's working perfectly.

Thank you very much for the help, and you were very fast! :grin:
