### ISSUE TITLE
Error: <address> has no matching Script

### ISSUE THREAD

**Issue by tiehm** [bitcoinjs/bitcoinjs-lib#1409]
Hey! 

I am trying to create a transaction but fail to build it due to the error `Error: <addr> has no matching Script`. I am using the testnet and also specifying that.

```ts
const txb = new TransactionBuilder(network);
txb.setVersion(1);
for (const transaction of previous) {
    txb.addInput(transaction.txid, transaction.vout);
}
txb.addOutput(to, toSend);
``` 
The error points to `txb.addOutput(to, toSend);`
`network` is the exported testnet network by bitcoinjs-lib.

**Comment by junderw** [comment]
What is "to"?

That error means "to" is not a valid address.

Give it a valid address.

**Comment by tiehm** [comment]
> 
> 
> What is "to"?
> 
> That error means "to" is not a valid address.
> 
> Give it a valid address.

It is correct. When looked up it is a valid address (https://live.blockcypher.com/btc-testnet/address/2MvvviSm2c8r9UugpvLxusB9QKRdAzqupEf/)

**Comment by junderw** [comment]
which version of bitcoinjs-lib are you using

**Comment by junderw** [comment]
copy pasted your code in the middle of some of my code just to test it.

it works fine:

```js
const { TransactionBuilder, networks } = require('bitcoinjs-lib');
const network = networks.testnet;
const previous = [
  {
    txid: '194a41826ac93d574db654154d00db9e227431c9a0c0202593eaa4479e29ef90',
    vout: 1,
  },
]
const to = '2MvvviSm2c8r9UugpvLxusB9QKRdAzqupEf'
const toSend = 900000

// your code starts here

const txb = new TransactionBuilder(network);
txb.setVersion(1);
for (const transaction of previous) {
    txb.addInput(transaction.txid, transaction.vout);
}
txb.addOutput(to, toSend);

// your code ends

const incompleteTx = txb.buildIncomplete()
console.log(incompleteTx.toHex())
// prints
// 010000000190ef299e47a4ea932520c0a0c93174229edb004d1554b64d573dc96a82414a190100000000ffffffff01a0bb0d000000000017a914286a98d37345a4cd6952f8dd81db294c92f47f758700000000
```

**Comment by junderw** [comment]
Can you please reply once you figure out the issue.

**Comment by tiehm** [comment]
I have to admit that I do not have that error currently because another one popped up which I have no idea about. 

```
Error: Invalid network version
    at Object.fromWIF (D:\...\node_modules\bitcoinjs-lib\src\ecpair.js:86:40)

```
at 
```
const sender = ECPair.fromWIF(WIF, network);
``` 
I logged network and it is 

```
{ messagePrefix: '\u0018Bitcoin Signed Message:\n',
  bech32: 'tb',
  bip32: { public: 70617039, private: 70615956 },
  pubKeyHash: 111,
  scriptHash: 196,
  wif: 239 } 
``` so the testnet with which I also generate the pairs. I have no idea what the issue is (as this is testnet the WIF is `Boqtxn8YNc5EqW7AqA7ANQdX2CQDpxj71uP79r66MDn2E7NCngu7`)

**Comment by junderw** [comment]
WIF is invalid.

You must have messed up a character somewhere.

it should start with a c iirc.

looks like no issue with the library, so closing.

**Comment by rommzestz** [comment]
> 

also it mean, check network type
