### ISSUE TITLE
Can't toBase58Check bech32

### ISSUE THREAD

**Issue by haydencarlson** [bitcoinjs/bitcoinjs-lib#1417]
var addrBuffer = btcjs.address.fromBech32(output.address);  
var base58 = btcjs.address.toBase58Check(new_addr.data, btcjs.networks.bitcoin.pubKeyHash);

toBase58Check throws an error 
Error: Expected property "0" of type Buffer(Length: 20), got Buffer(Length: 32)

**Comment by junderw** [comment]
Don't ever do this.

You will lose money.

Whatever use case you think this is good for, it isn't.
