### ISSUE TITLE
Need help upgrading from 3.3.2

### ISSUE THREAD

**Issue by JeffWScott** [bitcoinjs/bitcoinjs-lib#1423]
The below code is intended to take a raw transaction string, and sign it with a private key.  It was created using bitcoinjs-lib v3.3.2 and I get multiple errors trying to run it with v4.0.2.

I can kind of get it worked out all the way down to this line " bitcoin.script.scriptHash.output.encode" and I cannot find the replacement for that string as I get an error that basically the encode method no longer exists.

I've googled a bunch and tried to look at what examples there are but I don't see any examples that get me where I want to be.  I'm posting here in hopes of some help

Thanks in advance.

```js
exports.getBitcoinTx = (rawTransaction) => {
  try {
    return bitcoin.Transaction.fromHex(rawTransaction);
  } catch (e) {
    throw new Error('Invalid transaction');
  }
};

exports.getBitcoinKey = (privateKey, network) => {
  try {
    return bitcoin.ECPair.fromWIF(privateKey, network);
  } catch (e) {
    if (e.message === 'Invalid checksum' || e.message === 'Non-base58 character') {
      throw new Error('Invalid private key');
    }
    throw e;
  }
};

exports.signBitcoinTx = (rawTransaction = '', privateKey = '', network) => {
  const tx = exports.getBitcoinTx(rawTransaction);

  const txb = bitcoin.TransactionBuilder.fromTransaction(tx, network);

  const key = exports.getBitcoinKey(privateKey, network);

  if (txb.inputs[0].prevOutType === 'nonstandard') {
    const contract = bitcoin.script.decompile(tx.ins[0].script).pop();
    txb.inputs[0].prevOutScript =
      bitcoin.script.scriptHash.output.encode(bitcoin.crypto.hash160(contract));
    txb.inputs[0].prevOutType = bitcoin.script.types.P2SH;
    txb.inputs[0].signScript = contract;
    txb.inputs[0].signType = bitcoin.script.types.P2SH;

    txb.inputs[0].pubKeys = [key.getPublicKeyBuffer()];
    txb.inputs[0].signatures = [undefined];

    txb.sign(0, key, contract);

    const sig = bitcoin.script.scriptHash.input.encodeStack(
      txb.inputs[0].signatures[0],
      txb.inputs[0].pubKeys[0],
    );

    sig.push(...bitcoin.script.decompile(tx.ins[0].script));
    txb.tx.setInputScript(0, bitcoin.script.compile(sig));
    return txb.tx.toHex();
  }

  txb.inputs.forEach((input, i) => {
    if (!('signatures' in input) || input.signatures.length === 0) {
      txb.sign(i, key);
    }
  });
  return txb.build().toHex();
};
```

**Comment by junderw** [comment]
Read the changelog, then read the integration transaction tests. (extremely easy to read)

Then come back if you have any questions.

Also, you should use the latest version, since not much has changed since v4.

we bumped v5 just in case when adding Typescript support.

**Comment by junderw** [comment]
txb.inputs and txb.tx should not be accessed.

If you are doing something like this, you must do the following:

1. Use Transaction and not TransactionBuilder.
2. Verify the script before signing.

The code you have posted is dangerous.

I highly recommend you reconsider your methods.

**Comment by JeffWScott** [comment]
Thanks for the help.  I'll revisit.

**Comment by JeffWScott** [comment]
@junderw 

Looks like your integration tests use Transaction Builder. 
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js

**Comment by junderw** [comment]
yes.

If you're going to use TransactionBuilder, follow those examples.

If you look at the CSV tests you'll see some advanced use cases that don't use TransactionBuilder, but you're on your own, since any "nonstandard" stuff has a high probability of you losing money to a blackhole.

What kind of script are you trying to use?

I see it's p2sh, but what's your redeemscript like?

**Comment by JeffWScott** [comment]
@junderw I feel like I'm pretty close.  I created a tx from the raw tx using the "fromRaw" function. 
I then turned that into a txb using "TransactionBuilder.fromTransaction".

It's now failing on txb.sign with this error.

```
if (keyPair.network && keyPair.network !== this.network) throw new TypeError('Inconsistent network')
              ^

TypeError: Cannot read property 'network' of undefined
```

This is the code for signing the txb.

```
const key = bitcoin.ECPair.fromWIF(privateKey)
txb.sign({
    prevOutScriptType: 'p2pkh',
    vin: 0,
    keyPair: key
})
```

'private key' is defined elsewhere.

**Comment by JeffWScott** [comment]
> yes.
> 
> If you're going to use TransactionBuilder, follow those examples.
> 
> If you look at the CSV tests you'll see some advanced use cases that don't use TransactionBuilder, but you're on your own, since any "nonstandard" stuff has a high probability of you losing money to a blackhole.
> 
> What kind of script are you trying to use?
> 
> I see it's p2sh, but what's your redeemscript like?

The function of this app is to just sign a raw transaction.  The creation of the transaction content is external.

**Comment by junderw** [comment]
- Please look at the tests for the version you are using. All versions are tagged and can be switched on the file viewing screen. txb.sign with a single object parameter is not released yet.
- Your old code is signing a p2sh blindly, your new code is trying to sign a p2pkh. What format is your prevoutScript?
- TransactionBuilder, when used correctly, has many sanity checks to make sure you're not signing something dangerous. Your old code seems like TransactionBuilder got mad at you and you just told it to squash and errors and just sign blindly.
- There is no "blindly sign transaction" with TransactionBuilder. You need to pass certain parameters depending on the type of prevoutScript. Since wallets usually don't deal with multiple types, this should not be a problem.
- Why not use bitcoin.networks.bitcoin?

**Comment by JeffWScott** [comment]
> * bitcoin.networks.bitcoin

Looks like I was able to get a signed transaction. This is all it took.  Thanks @junderw for all the assistance.

```
  const tx = bitcoin.Transaction.fromHex(rawTransaction)
  const key = bitcoin.ECPair.fromWIF(privateKey)
  const txb = new bitcoin.TransactionBuilder.fromTransaction(tx, network)
  txb.sign(0, key)

  return txb.build().toHex();
```

A bit of history. We hired a 3rd party contractor to do the first code.  He used 3.3.2. Then we upgraded the package to 4.0.2 and added some functionality which then broke the 3.3.2 code.

So there was a but of a learning curve to get this to work, but I think I have what I need.  Again, their is an upstream application that crates the raw transaction and scripts, this code is just used in an external app to sign the transaction using a private key that only it knows.

@junderw I do have 1 more issue.  it seems that I can get over the 'Inconsistent network'  error using bitcoin.networks.bitcoin explicitly.  

But passing in the network in object notation, like this:
```
{
    messagePrefix: '\x18Bitcoin Signed Message:\n',
    bech32: 'bc',
    bip32: {
      public: 0x0488b21e,
      private: 0x0488ade4
    },
    pubKeyHash: 0x00,
    scriptHash: 0x05,
    wif: 0x80
  }
```

Or what we had in the previous code
```
{
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x0,
    scriptHash: 0x5,
    wif: 0x80,
  }
```

throws that network error.

What's the difference?

**Comment by junderw** [comment]
Glad to hear.
