### ISSUE TITLE
multisig

### ISSUE THREAD

**Issue by Keerthana-Jayakumaran** [bitcoinjs/bitcoinjs-lib#1426]
I have created a multisig address in  regtest using the bitcoinjs-lib. When I try to send to some coins to the address using bitcoin-cli (command line tool). I am getting error code -5 , invalid address.
P.S: node(bitcoind in regtest) is running locally.

**Comment by Keerthana-Jayakumaran** [comment]
Node version : Bitcoin Core RPC client version v0.17.1.0

**Comment by junderw** [comment]
1. Show me your code.
2. Did you read the examples in the tests? https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js

**Comment by Keerthana-Jayakumaran** [comment]
I have created a multisig address in  regtest using the bitcoinjs-lib. When I try to send to some coins to the address using bitcoin-cli (command line tool). I am getting error code -5 , invalid address.
P.S: node(bitcoind in regtest) is running locally.

Yes I read. But i was using  this one "https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/addresses.js" .

First i would like to check the created address using bitcoinjs-lib will work with local bitcoin node or not.

Below shows the things which i have tried


So i created a multi-sig with using bitcoin-cli tool

these are the two address

1.  bitcoin-cli -rpcport=8000 getaddressinfo n2zn3RUzXQAz7Sth3AVfJUrvAbBxuhZ7XF
{
  "address": "n2zn3RUzXQAz7Sth3AVfJUrvAbBxuhZ7XF",
  "scriptPubKey": "76a914eb9dbaf0972944c7af4c5073a61ff13e7c1269a188ac",
  "ismine": true,
  "iswatchonly": false,
  "isscript": false,
  "iswitness": false,
  "pubkey": "03353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd439",//(string, optional) The hex value of the raw public key, 
                                                                                 for single-key addresses (possibly embedded in P2SH or P2WSH)
  "iscompressed": true,
  "timestamp": 1553671905,
  "hdkeypath": "m/0'/0'/48'",
  "hdseedid": "3ab9903498147fb86e24053435a403f71f0fb87a",
  "hdmasterkeyid": "3ab9903498147fb86e24053435a403f71f0fb87a",
  "labels": [
  ]
}

2.
bitcoin-cli -rpcport=8000 getaddressinfo n47DhtmbfZuxSBYpNkWxXMyxy7seDoWfWo
{
  "address": "n47DhtmbfZuxSBYpNkWxXMyxy7seDoWfWo",
  "scriptPubKey": "76a914f7cdc6404ab1cf2ddbd1d126b56a94c44aa47b7e88ac",
  "ismine": true,
  "iswatchonly": false,
  "isscript": false,
  "iswitness": false,
  "pubkey": "037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c1",
  "iscompressed": true,
  "timestamp": 1553671905,
  "hdkeypath": "m/0'/0'/61'",
  "hdseedid": "3ab9903498147fb86e24053435a403f71f0fb87a",
  "hdmasterkeyid": "3ab9903498147fb86e24053435a403f71f0fb87a",
  "labels": [
  ]
}


3. Creation of multisig using bitcoin-cli ---->(p2sh type)

bitcoin-cli -rpcport=8000  createmultisig 2 "[\"03353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd439\",\"037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c1\"]"

Result:

{
  "address": "2N67w5qCUrLYzwt5AZatudJeDNxmQgHw4oL",
  "redeemScript": "522103353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd43921037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c152ae"
}

4. when we decode redeemscript of step 3,

bitcoin-cli -rpcport=8000 decodescript 522103353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd43921037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c152ae
{
  "asm": "2 03353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd439 037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c1 2 OP_CHECKMULTISIG",
  "reqSigs": 2,
  "type": "multisig",
  "addresses": [
    "n2zn3RUzXQAz7Sth3AVfJUrvAbBxuhZ7XF",
    "n47DhtmbfZuxSBYpNkWxXMyxy7seDoWfWo"
  ],
  "p2sh": "2N67w5qCUrLYzwt5AZatudJeDNxmQgHw4oL",
  "segwit": {
    "asm": "0 368fd32bcb1cc3d3dce1ba9a4205da1ad2d5940d8e5372394c1c63463ba8bff0",
    "hex": "",
    "reqSigs": 1,
    "type": "witness_v0_scripthash",
    "addresses": [
      "bcrt1qx68ax27trnpa8h8ph2dyypw6rtfdt9qd3efhyw2vr335vwaghlcq5qqh79"
    ],
    "p2sh-segwit": "2MvWyQ4VjaxnR8GEMD2RFH6PGgxZqXgevFb"
  }
}
-->created address info 

bitcoin-cli -rpcport=8000 getaddressinfo 2N67w5qCUrLYzwt5AZatudJeDNxmQgHw4oL
{
  "address": "2N67w5qCUrLYzwt5AZatudJeDNxmQgHw4oL",
  "scriptPubKey": "a9148d389cc77018232c5a1dff246d2f37a9e50e19cc87",
  "ismine": false,
  "iswatchonly": false,
  "isscript": true,
  "iswitness": false,
  "labels": [
  ]
}



5. Creation of multisig using bitcoin-cli ---->(p2sh-segwit type)

bitcoin-cli -rpcport=8000  createmultisig 2 "[\"03353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd439\",\"037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c1\"]" "p2sh-segwit"
{
  "address": "2MvWyQ4VjaxnR8GEMD2RFH6PGgxZqXgevFb",
  "redeemScript": "522103353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd43921037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c152ae"
}

-->created address info 

keerthana@keerthi-HP-EliteBook-745-G2:~$ bitcoin-cli -rpcport=8000 getaddressinfo 2MvWyQ4VjaxnR8GEMD2RFH6PGgxZqXgevFb
{
  "address": "2MvWyQ4VjaxnR8GEMD2RFH6PGgxZqXgevFb",
  "scriptPubKey": "a91423e2da8437edcdd589582aaf3c76926349d0591087",
  "ismine": false,
  "iswatchonly": false,
  "isscript": true,
  "iswitness": false,
  "labels": [
  ]
}



6. Then i want to achieve the same (creating same address using bitcoinjs lib).
So i created a multi-sig with public keys which i created using bitcoin-cli tool



  6.1.

  const pubkeys = [
        '03353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd439',
        '037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c1'
      ].map((hex) => Buffer.from(hex, 'hex'));

    var address1  = (bitcoin.payments.p2wsh({
      redeem: bitcoin.payments.p2ms({ m: 2, pubkeys })
    })).address
    console.log("P2WSH (SegWit), pay-to-multisig (2-of-2) address",address1);



6.2.

    const pubkeys1 = [
        '03353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd439',
        '037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c1'
    ].map((hex) => Buffer.from(hex, 'hex'))

    const address2  = (bitcoin.payments.p2sh({
      redeem: bitcoin.payments.p2wsh({
        redeem: bitcoin.payments.p2ms({ m: 2, pubkeys:pubkeys1 })
      })
    })).address
    console.log(" P2SH(P2WSH(...)), pay-to-multisig (2-of-2) address",address2);


result:

P2WSH (SegWit), pay-to-multisig (2-of-2) address bc1qx68ax27trnpa8h8ph2dyypw6rtfdt9qd3efhyw2vr335vwaghlcqw3u73s
 P2SH(P2WSH(...)), pay-to-multisig (2-of-2) address 34xmLKZhyWH4vUboXtoNf9Q1UcMffzxncD



the addresses are not the same which are creating using bitcoin-cli and bitcoinjslib


P.S:
Everything is in regtest mode. And when i created using below (random keypair)

const keyPair = bitcoin.ECPair.makeRandom({ network: REGTEST })
const addressdetails  = bitcoin.payments.p2pkh({ pubkey: keyPair.publicKey, network: REGTEST })

result: msgD8ctEYRKAfzanmAP1hm9osP1EhVZyy7 which able to recognise by the local node(using bitcoin-cli).


Could you please guide me?

**Comment by junderw** [comment]
You solved your own problem: pass network parameter to all payments objects.

```js
  const pubkeys = [
        '03353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd439',
        '037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c1'
      ].map((hex) => Buffer.from(hex, 'hex'));

    var address1  = (bitcoin.payments.p2wsh({
      redeem: bitcoin.payments.p2ms({ m: 2, pubkeys, network: REGTEST }),
      network: REGTEST,
    })).address
    console.log("P2WSH (SegWit), pay-to-multisig (2-of-2) address",address1);

    const pubkeys1 = [
        '03353af9812268e35dd8f230a1136c8560b50b0a4fabb83f601e96d94b4c9dd439',
        '037a9caf6c6ef8a3e1bd9fe49ad06ddca5cb6c7af7a41d03db8d50847632cce4c1'
    ].map((hex) => Buffer.from(hex, 'hex'))

    const address2  = (bitcoin.payments.p2sh({
      redeem: bitcoin.payments.p2wsh({
        redeem: bitcoin.payments.p2ms({ m: 2, pubkeys:pubkeys1, network: REGTEST }),
        network: REGTEST,
      }),
      network: REGTEST
    })).address
    console.log(" P2SH(P2WSH(...)), pay-to-multisig (2-of-2) address",address2);
```

**Comment by Keerthana-Jayakumaran** [comment]
Thank you Jonathan ;) .
