### ISSUE TITLE
Creating Multisig HD wallet

### ISSUE THREAD

**Issue by gabril785** [bitcoinjs/bitcoinjs-lib#1427]
I have been looking to create a Multisig HD wallet for a project I am doing using this library. 
I was wondering if this is possible with this library and how if can be done ? Is there any examples as cant find anything in the code that helps with this apart from having 1 address from multisig wallet but nothing about multisig hd wallet.

**Comment by junderw** [comment]
How will your participants communicate?

If you will allow all participants to generate addresses independently read BIP45. It will give you an idea of some problems you may face.

If address generation will be centralized in one entity you can use anything you want as long as it is consistent.

HD multisig also has the problem of verifying xpubs.

If your xpub cache is compromised, you need to be able to catch it. So sign the other xpubs with your private key.

This is very sensitive, and if you aren't sure what I'm talking about I would highly recommend against implementing something without thinking it through.

What is secure for one HD multisig could be dangerous for another.

We will not make any recommendations for such a sensitive topic.
