### ISSUE TITLE
1-1 transaction signing issue

### ISSUE THREAD

**Issue by SajadSeyedzadeh** [bitcoinjs/bitcoinjs-lib#1428]
I want to create following 1-1 transaction :
` const key=bitcoin.ECPair.fromWIF('cQfGwBoeAvvP44VsoMHj58yMQaGdbayMX9w25bZuRhepEfCu1otR')`
`tx.addInput("'46239fe8ad925e7c68c06a1130e2789f62b0604f26084e5e6b6164db4c1238d8",1)
 txb.setVersion(1);`
`tx.addOutput("mjhPuscBrsmRYRXtKZUA3ZAkCHzWtue9vK", 10000);`
` var key = bitcoin.ECPair.fromWIF(wif, bitcoin.networks.testnet);`
 `tx.sign({
          prevOutScriptType: "p2pkh",
          vin: 0,
          keyPair: key
        });`
But I'm getting following error :
`TypeError: Cannot read property 'network' of undefined
    at TransactionBuilder.sign (node_modules\bitcoinjs-lib\src\transaction_builder.js:123:1`
Also I checked `key.network` and It's not `undefined`.
Thanks.

**Comment by junderw** [comment]
That sign parameter is not published yet.

If you would like to test it, use Github master, but not in production.

Otherwise, take a look at the integration tests for the version you are using. (Github lets to specify a tag when looking at a file, select the tag for your version.)
