### ISSUE TITLE
HTLC

### ISSUE THREAD

**Issue by Keerthana-Jayakumaran** [bitcoinjs/bitcoinjs-lib#1430]
Hi,
I want to P2SH transaction ( HTLC or WIth time lock as well as hash lock).
Following things i should do,
1. For that, I want to create an address from a particular redeem script (for now I have included hash lock and I ignored public key in the redeem script ).
2. I should pay to the address.
3. Then try to redeem the bitcoins if I give correct hash as input otherwise it should not unlock the coins.

step 1 and 2 , i have done.
Now I am trying to do the 3rd. Could you please guide me ?

P.S: I have gone through the transactions using payment p2pkh,p2sh,etc. But if i create a address from a user defined redeem script , how will i sign a output or give signature for input ?

Here is the code:
`
var bitcoin = require("bitcoinjs-lib");
const REGTEST = bitcoin.networks.regtest;

//get the hex of  redeem script using btcc cmd tool
//     btcc OP_IF "1ca35897540ec7ae7294a8cacd11caf2c09f95f026c925c6ce4e4c29b20e3c41" OP_EQUAL
// 63201ca35897540ec7ae7294a8cacd11caf2c09f95f026c925c6ce4e4c29b20e3c4187
    
  const { address } = bitcoin.payments.p2sh({
      
      redeem:{output: Buffer.from("63201ca35897540ec7ae7294a8cacd11caf2c09f95f026c925c6ce4e4c29b20e3c4187", 'hex')},
    network: RETEST

      
    });
    console.log("address ",address);
`

address 2NBbLHzd3M77y256CdkdLPLSumLNRzBi8DY

And trying to send coins to the address using bitcoin-cli

`
bitcoin-cli -rpcport=8000 sendtoaddress  2NBbLHzd3M77y256CdkdLPLSumLNRzBi8DY 0.001
baf5266bc06531ce15118186cde53308fd56fa4deb1c0b2d297203b67d16ac4d
`

I got in the bitcoin log as

 CommitTransaction:
CTransaction(hash=baf5266bc0, ver=2, vin.size=1, vout.size=2, nLockTime=626)
    CTxIn(COutPoint(c64f07bf70, 1), scriptSig=473044022004d501dae91797, nSequence=4294967294)
    CScriptWitness()
    CTxOut(nValue=0.00100000, scriptPubKey=a914c93fd8c6edf4e994099275c52e)
    CTxOut(nValue=0.42295580, scriptPubKey=a9147fdf4ffe590e7331c1474063a8)
2019-07-08T05:30:14Z [default wallet] keypool keep 1013
2019-07-08T05:30:14Z [default wallet] AddToWallet baf5266bc06531ce15118186cde53308fd56fa4deb1c0b2d297203b67d16ac4d  new
2019-07-08T05:30:14Z [default wallet] Relaying wtx baf5266bc06531ce15118186cde53308fd56fa4deb1c0b2d297203b67d16ac4d
2019-07-08T05:30:14Z [default wallet] AddToWallet baf5266bc06531ce15118186cde53308fd56fa4deb1c0b2d297203b67d16ac4d

**Comment by junderw** [comment]
Here is an example of how to sign some complex script manually.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/csv.js

Be careful. You can lose money.

**Comment by Keerthana-Jayakumaran** [comment]
thanks. I am trying to do this
`
var bitcoin = require("bitcoinjs-lib");
const REGTEST = bitcoin.networks.regtest;

const keyPair = bitcoin.ECPair.makeRandom({ network: REGTEST });
const hashType = bitcoin.Transaction.SIGHASH_ALL
// console.log("keypair");
// console.log(keyPair);
// console.log(keyPair.publicKey);
// console.log(keyPair.privateKey);





//     btcc OP_IF "1ca35897540ec7ae7294a8cacd11caf2c09f95f026c925c6ce4e4c29b20e3c41" OP_EQUAL
// 63201ca35897540ec7ae7294a8cacd11caf2c09f95f026c925c6ce4e4c29b20e3c4187
    
    const { address } = bitcoin.payments.p2sh({
      // redeem: bitcoin.payments.p2ms({ m: 2, pubkeys })
      
      redeem:{output: Buffer.from("63201ca35897540ec7ae7294a8cacd11caf2c09f95f026c925c6ce4e4c29b20e3c4187", 'hex')},
    // redeem:{output: Buffer.from("a9148d389cc77018232c5a1dff246d2f37a9e50e19cc87", 'hex')},
    network: REGTEST

      
    });
    // console.log("address ",address);



    function hashlock(hash)
    {
      console.log("hash",hash);
      console.log(bitcoin.script.fromASM(`OP_IF ${hash} OP_EQUAL`))
     
      return bitcoin.script.fromASM(`OP_IF ${hash} OP_EQUAL`);

    }

    function redeeming()
    {
      var hash = "1ca35897540ec7ae7294a8cacd11caf2c09f95f026c925c6ce4e4c29b20e3c41";
      const redeemScript = hashlock("1ca35897540ec7ae7294a8cacd11caf2c09f95f026c925c6ce4e4c29b20e3c41");
      // const redeemScript = hashlock(Buffer.from("hanuman","hex"));
      console.log("redeem script ",(redeemScript).toString("hex"));
      const {address} = bitcoin.payments.p2sh({redeem:{output:redeemScript,network:REGTEST},network:REGTEST});
      console.log("address",address);
      /* paid to the address 2NBbLHzd3M77y256CdkdLPLSumLNRzBi8DY
      and the txid is 371db8adbc0b1fab62ab84484a562a8c24e84c5e58a76c12ac0c1864a57629a2
      and the vout 
      "vout": [
    {
      "value": 0.00100000,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_HASH160 c93fd8c6edf4e994099275c52e07e58d5650e402 OP_EQUAL",
        "hex": "a914c93fd8c6edf4e994099275c52e07e58d5650e40287",
        "reqSigs": 1,
        "type": "scripthash",
        "addresses": [
          "2NBbLHzd3M77y256CdkdLPLSumLNRzBi8DY"
        ]
      }
    }
  ]


      */
      
      const utx0 = {
        txid:"371db8adbc0b1fab62ab84484a562a8c24e84c5e58a76c12ac0c1864a57629a2",
        vout:0

      }
      const txb = new bitcoin.TransactionBuilder(REGTEST)
      txb.addInput(utx0.txid,utx0.vout);
      var randomAddress = "n42H3y8wBHtdynxwLzUYYFaapchgNab2v8";
      txb.addOutput(randomAddress,1e4);

      const tx = txb.buildIncomplete()
      const signatureHash = tx.hashForSignature(0,redeemScript,hashType);
      const redeemScriptSig = bitcoin.payments.p2sh({
        redeem:{
          // input: bitcoin.script.fromASM(`OP_IF ${hash} OP_EQUAL`),
        //   input: bitcoin.script.compile([
        //     bitcoin.opcodes.OP_IF,
        //     hash,
        //     bitcoin.opcodes.OP_EQUAL
        //   ]),
        input: bitcoin.script.compile([
            bitcoin.opcodes.OP_IF,
            hash,
            bitcoin.opcodes.OP_EQUAL,
            bitcoin.opcodes.OP_TRUE]),
          output: redeemScript

        }
      }).input

      tx.setInputScript(0,redeemScriptSig);
      console.log("tx");
      console.log(tx);

    }
    redeeming();


    

`



 I am getting the error as   throw new TypeError('Non push-only scriptSig')

**Comment by junderw** [comment]
I can't understand it.

an input can not have any op codes in it.

**Comment by Keerthana-Jayakumaran** [comment]
When we are trying to unlock the redeem script, we have to give  key (here it is random hash) and also the while script right?
like  hash redeemscript

**Comment by Keerthana-Jayakumaran** [comment]
For a multi sig, we will give the redeemscript and also the signature in the input(vin) as script sig , the same way we have to give the hash and redeemscript. If i am wrong, can you please guide me?

**Comment by junderw** [comment]
We do not support this.

But we offer the tools for you to make it yourself.

Good luck.

If you would like personal lessons on how to create a script, this is not the place.

If you would like to ask questions on how to use the tools you are welcome.

I can tell you how to use a hammer, but I can not help you build a house.

**Comment by Keerthana-Jayakumaran** [comment]
ok, thanks @junderw

**Comment by ghuang123** [comment]
I believe the question is valid and not sure the reason why it is closed.

**Comment by junderw** [comment]
@ghuang123 Asking a hammer manufacturer "How do I build a house with your hammer?" is not a valid question.

I sometimes answer invalid questions:

1. If I can understand the question, and it sounds like the person understands their own question.
2. It is easy enough to answer.
3. It has a simple answer.
4. The answer has a low chance of losing people's money.

So for the above (invalid) question, here's my evaluation:

1. I can't understand the question. Attempts to clarify or point out logical errors with the code given were met with further misunderstandings. It seems like the person doesn't understand the question they are trying to ask as well.
2. An HTLC example would be hard to give without also implementing the surrounding modules/app.
3. No simple answer.
4. An HTLC if done incorrectly (and again, this has less to do with our library than the implementation of the app surrounding the script generation) will lose money.

So I decided to close the issue.

Issues are strictly for issues (problems and questions) dealing with this library's interfaces.

A lot of other repositories ignore issues for years OR close every issue strictly as off topic. I try to make an effort to answer questions even if they are off topic, but in this case I felt answering this issue was not helping the asker or anyone else, and would only hurt them if they misused my answer.

**Comment by junderw** [comment]
If you would like to re-phrase the question into a valid question, or a smaller less-dangerous question that is hard to cause money loss, you are welcome to open a new issue.
