### ISSUE TITLE
bitcoin.script.witnessPubKeyHash undefined

### ISSUE THREAD

**Issue by dwasyluk** [bitcoinjs/bitcoinjs-lib#1444]
Trying to run this code and getting error that bitcoin.script.witnessPubKeyHash is undefined:

```
 const keypair = bitcoin.ECPair.fromPrivateKey(masterNode.privateKey);
  const scriptPubKey = bitcoin.script.witnessPubKeyHash.output.encode(bitcoin.crypto.hash160(keypair.publicKey));
  const bech32 = bitcoin.address.fromOutputScript(scriptPubKey);
```

`TypeError: Cannot read property 'output' of undefined`

Using bitcoinjs-lib 5.1.2. This code is just a slightly modified version of the answer here: https://github.com/bitcoinjs/bitcoinjs-lib/issues/1104 so I'm confused as to why its reporting `witnessPubKeyHash` is undefined?

**Comment by junderw** [comment]
Script templates were removed in favor of a "payments" API in v4.0.0

check the examples in the readme. (they link to the integration tests)
