### ISSUE TITLE
66: insufficient priority. Code:-26

### ISSUE THREAD

**Issue by lee149205** [bitcoinjs/bitcoinjs-lib#1445]
i submit rawtx to https://test-insight.bitpay.com/api/tx/send ---> error "66: insufficient priority. Code:-26". I already tried fee 0.00001 -> 0.01 ---> but still fail
Plz help me, thanks

"01000000026d345c8208050759a5d656e86d726b70e67ee3361d64b06aa296e0cd05884ee2000000006b48304502210086dd702e57ec9cb1cfec6fc360781048739bcc5b53f02e4568549c9fc8b8289a02200c0414c9eff5d7f9acb7271ba2eabfb3ec194e0cdd4330f0f141e7b2d871f5bf0121026ec2a698bc3deebf921014932abc84596bd41fca04ebd787cfb85f7638c1d540fffffffff8ff16ade54feda8707cacaa4e10ccdd45e4a50b5ca75f492ef0f7d80b2ad9d9010000006b4830450221009b1349a7caefbd9eaea7189fc90365a03539e2e3662b1436374f51f62f10ba9e0220020c55c18569ab227eef893124ea02b2c92e9b28f9157109bc9ab3358eccfe200121026ec2a698bc3deebf921014932abc84596bd41fca04ebd787cfb85f7638c1d540ffffffff02229b2c00000000001976a914a311d23147068b89ff633545734803ebdc30bc7c88ac40420f00000000001976a91465eeb956e99379940a6a4cee7032c73304237f4f88ac00000000"

**Comment by junderw** [comment]
(3903298+20000)−(2923298+1000000) = 0

Your transaction has 0 fee.

try lowering the 1000000 output down to about 999000 so you'll add 1000 satoshis in fee.
