### ISSUE TITLE
[Question] 2 letters prefix on altcoin

### ISSUE THREAD

**Issue by ricgby** [bitcoinjs/bitcoinjs-lib#1446]
Hello,

I am trying to add an altcoin which has a 2 letter prefix in their addresses. I am sending the following information:

```
  bech32 = null;
  bip32 = { public: 0x0488b21e, private: 0x0488ade4 };
  messagePrefix = '\x18SnowGem Signed Message:\n';
  pubKeyHash = 0x1c28;
  scriptHash = 0x1c2d;
  wif = 0x80;
```

I am getting an "out of bounds error" with the pubkeyhash  when trying this, is there a way around it? Or is it not supported?

**Comment by junderw** [comment]
two byte versions are not currently supported.
