### ISSUE TITLE
How to sign 1-1 transaction  with transactionBuilder but found previous transaction value < currently value

### ISSUE THREAD

**Issue by athlona64** [bitcoinjs/bitcoinjs-lib#1447]
How to sign 1-1 transaction  with transactionBuilder but found previous transaction value < currently value

```js
txb.setVersion(2);       
txb.addInput('bf69290574e4af72dab8872ac2d3e574a31ec82c7a6513e349ea3629ed0d7d22', 1);
txb.addOutput('dest address', 'balance to send');
txb.addOutput('old address', 'balance send to owner');
txb.sign(0, alice);
var rawTrasaction = txb.build().toHex();
```
```
32|bitcoin |   message: 'bad-txns-in-belowout, value in (0.04499104) < value out (0.06498208) (code 16)',
32|bitcoin |   code: -26,
32|bitcoin |   name: 'RpcError' }
32|bitcoin | undefined
```

**Comment by junderw** [comment]
1. Before adding the input you should know how much value each input has. Every time you add an input, keep a total value of inputs.
2. Add all the outputs to outside people you need, make sure that your output total doesn't go over your input total.
3. Calculate how much fees you want to put on the transaction.
4. Check `total_input - total_output - fee` (let's call it leftover) and if leftover is > 600 satoshis, then add one more output sending to yourself and send the leftover.

Your error is because you are sending more bitcoin than you are spending...

If this transaction were valid, you would be creating new bitcoins out of nothing :smile:

**Comment by athlona64** [comment]
> 1. Before adding the input you should know how much value each input has. Every time you add an input, keep a total value of inputs.
> 2. Add all the outputs to outside people you need, make sure that your output total doesn't go over your input total.
> 3. Calculate how much fees you want to put on the transaction.
> 4. Check `total_input - total_output - fee` (let's call it leftover) and if leftover is > 600 satoshis, then add one more output sending to yourself and send the leftover.
> 
> Your error is because you are sending more bitcoin than you are spending...
> 
> If this transaction were valid, you would be creating new bitcoins out of nothing

ok i'm clear 


but now i can sign to hex for broadcast to network 

but found err can't decode hex to rawtransaction 

when i'm get all input UXTO and 1 output looks like work

but when i'm try 3 inputs and 2 outputs(to myself and other address) is not to decode to rawtransaction and failed 


this is my sign 

   

>          txb.addInput('5446905f72ac46078cd1d97fca05506d43282f5b952698954c4c721f0b928607', 1);
>             txb.addInput('23ffca9a36d5f9597735c982e2b918c83080e14df7694212079e0c475075bde1', 1);
>             txb.addInput('bf69290574e4af72dab8872ac2d3e574a31ec82c7a6513e349ea3629ed0d7d22', 1);
> 
> 
>             
>             txb.addOutput(this.address, sendBalance);
>             txb.addOutput(this.destAddress, userInputBalance);
>             for(var i=0;i<txb.tx.ins.length;i++){
>               txb.sign(i, alice);
>             }
>             var rawTransaction = txb.build();
>             var rawTransactionToHex = rawTransaction.toHex();

**Comment by junderw** [comment]
The hex you have pasted is cut off at the end.

Perhaps you did not copy the whole thing.

Maybe there is a limit of characters to be displayed on whatever UI you are using.

**Comment by athlona64** [comment]
> The hex you have pasted is cut off at the end.
> 
> Perhaps you did not copy the whole thing.
> 
> Maybe there is a limit of characters to be displayed on whatever UI you are using.

Ok sir i will tried and keep in variable to send raw and will report to you 

thank you sir

**Comment by junderw** [comment]
Where is your code running?

- Browser?
- Node JS process?
- React Native?
- Electron App?

etc. etc.
