### ISSUE TITLE
Error: witnesspubkeyhash not supported trying to sign p2wpkh transaction

### ISSUE THREAD

**Issue by dwasyluk** [bitcoinjs/bitcoinjs-lib#1458]
I know I'm making a rookie error here and would appreciate any help. I'm trying to sign a transaction which I believe is well-formed and no matter what I try I get `Error: witnesspubkeyhash not supported`. Its a transaction with a single pkwpkh address input and 2 p2wpkh address outputs. The error occurs when calling TransactionBuilder.sign. 

Here is the rawtx unsigned:
`020000000195bec09901cf1f17508ae44f4280fe69296642d3fe40346ecc416dcd7a3a48b3000000001600142b9d0ca8a17efc35d75f64c1c7465ef4c14069e2ffffffff02a08601000000000016001491883b6cd2f42b0905eff3373ec08d7b79dd780824af4a00000000001600142b9d0ca8a17efc35d75f64c1c7465ef4c14069e200000000`

**Comment by junderw** [comment]
Show me your code.

did you pass the arg `type: 'p2wpkh',`?

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L192

did you look at the example btw?

**Comment by dwasyluk** [comment]
@junderw thanks for your help- what you linked to was exactly what I needed. For those who may stumble upon this in the future the trick was manually specifying `prevOutScriptType` and `witnessValue` in the way @junderw's link demonstrates. Make sure to get the witnessValue right or it won't broadcast! Thanks again for your help.
