### ISSUE TITLE
Expected property "1" of type Satoshi, got Number 6999.999999999999

### ISSUE THREAD

**Issue by idoor88** [bitcoinjs/bitcoinjs-lib#1460]
Hi all, I am trying to use the following code to send BTC transaction, the toAmount is 0.00007 of BTC, since my total amount is 0.00027 btc, I leave 0.0002 as mining fee, but I got error message:
Expected property "1" of type Satoshi, got Number 6999.999999999999
when the code is executing the line of: 
  txb.addOutput(toAddress, amount);

the amount is toAmount * precision, which is 0.00007 * 100000000 = 7000, which equals 6999.999999999999, but why I got this error?  it is because I have too little of BTC balance?

` 
let precision = 1e8;
............
const txb = new bitcoin.TransactionBuilder();

          let resultData = await fetchUnspentList(fromAddress);
          if(resultData && resultData.status == 200){
                const unspentList = resultData.data;
                // calculate total unspentList
                const totalUnspent = unspentList.reduce(
                    (a, b) => a + b.satoshis,
                    0,
                );
                // add tx input
                unspentList.forEach(({ txid, vout }) => txb.addInput(txid, vout));
                let changeValue = 0;
                if (btcTx) {
                    //btc transaction
                    const amount = toAmount * precision;
                    txb.addOutput(toAddress, amount);
                    // calculate fee value
                    feeValue = calculateTxFee(txb, fromAddress, fromPrivateKey, feeRate);
                    changeValue = totalUnspent - feeValue - amount;
                    feeValue = feeValue + amount;
                }
............`

**Comment by junderw** [comment]
> the amount is toAmount * precision, which is 0.00007 * 100000000 = 7000, which equals 6999.999999999999, but why I got this error? it is because I have too little of BTC balance?

JavaScript is bad with decimals.

My suggestions:
- Use a Big-number library to guarantee precision.
- Use an API that gives you satoshis and does not give you BTC (decimal values)

**Comment by junderw** [comment]
![スクリーンショット_2019-08-19_13-07-12](https://user-images.githubusercontent.com/11246316/63238620-47f0a100-c282-11e9-829e-7177e8c4931b.png)

**Comment by junderw** [comment]
![スクリーンショット_2019-08-19_13-08-00](https://user-images.githubusercontent.com/11246316/63238636-5fc82500-c282-11e9-860e-44532af28275.png)

Welcome to the world of JavaScript :-D
