### ISSUE TITLE
Extended Public Key

### ISSUE THREAD

**Issue by MehrdadKhnzd** [bitcoinjs/bitcoinjs-lib#1466]
Hey there! I have a problem with `BitcoinLib.bip32.fromSeed(seed, network).neutered().toBase58()`. I have different types of custom networks, other than Bitcoin. In some cases, the `bip32.public` of those networks are all the same. So, I get the same Extended Public Key for Bitcoin and Litecoin and some other coins. Is this correct? Is there something I'm missing? For example, I know that Litecoin BIP 32 Extended Public Key starts with `Ltub` but now it gives me the same XPub as Bitcoin, starting with `xpub`. It couldn't be correct and I don't know what to do! Is the problem with my network specifications and `bip32.public` of different networks? I use networks from here:
https://github.com/iancoleman/bip39/blob/master/src/js/bitcoinjs-extensions.js
Or it's about something else?

**Comment by junderw** [comment]
Show me your code.

The more you show me the better.

**Comment by MehrdadKhnzd** [comment]
The whole functionality is here, in my `BitcoinFamily` class:
```
static hdMaster (seed, network) {
  return BitcoinLib.bip32.fromSeed(seed, network)
}

static xPub (seed, network) {
  const hdMaster = BitcoinFamily.hdMaster(seed, network)
  const xPub = hdMaster.neutered().toBase58()
  return xPub
}
```
The seed is generated like this: `bip39.mnemonicToSeedSync(mnemonic)`
And the network properties is passed form a class, for example for `Litecoin`:
```
static get mainnet () {
  return {
    insightApi: 'https://insight.litecore.io/api/',
    properties: {
      messagePrefix: '\x19Litecoin Signed Message:\n',
      bip32: {
        public: 0x0488b21e,
        private: 0x0488ade4,
      },
      pubKeyHash: 0x30,
      scriptHash: 0x32,
      wif: 0xb0
    }
  }
}

static get testnet () {
  return {
    insightApi: 'https://testnet.litecore.io/api/',
    properties: {
      messagePrefix: '\x19Litecoin Signed Message:\n',
      bip32: {
        public: 0x043587cf,
        private: 0x04358394,
      },
      pubKeyHash: 0x6f,
      scriptHash: 0xc4,
      wif: 0xef
    }
  }
}
```
That's it. I followed my funcition call into `.toBase58()`, and everything was correct. The seed and the chain code are the same for every mnemonic, the only difference is in the network which was correct for different coins, but as their `bip32.public` are the same for Bitcoin and Litecoin, it produces the same XPub. Tell me if I can provide more info.

**Comment by dabura667** [comment]
I don't know where you got your info, but the correct info is here:

https://github.com/cryptocoinjs/coininfo/blob/master/lib/coins/ltc.js

**Comment by MehrdadKhnzd** [comment]
You're correct, my network info was false! Thanks for your help! But it's really weird! As I mentioned before, I used this https://github.com/iancoleman/bip39/blob/master/src/js/bitcoinjs-extensions.js which is a popular repository, and the website which demos this repository (https://iancoleman.io/bip39/) is also working fine! Besides that, I'm still confused. With that incorrect network info, I could generate valid addresses in Litecoin and others, how's that possible? Aren't they important in creating addresses? And another question, just to make sure. So you say that all of the coins are different in both `bip32.public` and `bip32.private` and if I find two of them which are the same that's incorrect? Cause I still see a lot of duplicates in `bip32` info in this file I used! (https://github.com/iancoleman/bip39/blob/master/src/js/bitcoinjs-extensions.js)

**Comment by junderw** [comment]
> a popular repository

This doesn't mean it is correct.

> I'm still confused.

https://github.com/iancoleman/bip39/blob/e440d504fbc80fe11366e24dccf945c43aaf52df/src/js/bitcoinjs-3.3.2.js#L9775-L9784

It's because you are looking at the wrong place.

> Cause I still see a lot of duplicates in `bip32` info in this file I used!

There is no "rule" on version reuse. It's not like the police will come and arrest you if your coin reuses a version from another coin or if your source code is incorrect.

It is a "standard" that versions SHOULD be unique. But many people don't understand what they are doing and make duplicates.

> Aren't they important in creating addresses?

In the BitcoinJS network format:

- `bip32` info is only used when exporting a bip32 object to string (xpub xprv etc)
- `pubKeyHash` is used for p2pkh addresses
- `scriptHash` is used for p2sh addresses
- `bech32` is used for p2wpkh and p2wsh addresses

It is possible that someone accidentally got some of those data points correct and some of them incorrect.

**Comment by MehrdadKhnzd** [comment]
Thanks, I got the point. Your help is really appreciated!
