### ISSUE TITLE
Psbt: 'address' does not exist in type 'PsbtOutputExtended'

### ISSUE THREAD

**Issue by dakk** [bitcoinjs/bitcoinjs-lib#1468]
I'm trying to migrate my wallet from TransactionBuilder to Psbt, but I'm unable to add an output using an address.

The problem is on types, since addOutput wants PsbtOutputExtended
```typescript
interface PsbtOutputExtended extends PsbtOutput, TransactionOutput {
}
```
and
```typescript
export interface TransactionOutput {
    script: Buffer;
    value: number;
}
```

So it needs always a script, even if I pass the address. 

```
Argument of type '{ address: any; value: number; }' is not assignable to parameter of type 'PsbtOutputExtended'.
  Object literal may only specify known properties, and 'address' does not exist in type 'PsbtOutputExtended'.
```

**Comment by junderw** [comment]
Please review #1469 and let me know if there are any other problems.

**Comment by dakk** [comment]
That pr corrects the problem

**Comment by dakk** [comment]
(Thank you @junderw )
