### ISSUE TITLE
Add support for SLIP-0039

### ISSUE THREAD

**Issue by arnavvohra** [bitcoinjs/bitcoinjs-lib#1471]
Trezor has been working on a Shamir implementation (SLIP-0039) that can be used to generate shamir shares of a mnemonic phrase.
They have provided an implementation in Python : https://github.com/trezor/python-shamir-and a reference implementation in JS : https://github.com/ilap/slip39-js .
How should we go about adding this to bitcoinjs-lib? Would it make sense to write our own JS implementation of the same or add the slip39-js in the list of complementing libraries.

**Comment by junderw** [comment]
If they already have a JS library just use that.

No need to reinvent the wheel.

bip39 is a separate package, so if we did make one it'd be a separate package anyways.

**Comment by arnavvohra** [comment]
Makes sense. Would it be beneficial to add  https://github.com/ilap/slip39-js in README.md as a complementing library?
