### ISSUE TITLE
Determine a used and unused btc address?

### ISSUE THREAD

**Issue by johnanisere** [bitcoinjs/bitcoinjs-lib#1480]
Is it possible to use this library to determine if an address has been used or unused  ?

**Comment by junderw** [comment]
No. Unfortunately not. This library only deals with:

1. Address creation etc. (including key derivation)
2. Transaction creation and signing

Bitcoin Core has a scanutxoset RPC command which might help, but it is rather slow.

The quickest way is to use a block explorer API. There are many public ones that are free to use, but it requires you to trust that they do not lie to you.

Some open source block explorers exist as well. Also, server side software like ElectrumX offers a transaction history API.

**Comment by johnanisere** [comment]
@junderw Thanks mate
