### ISSUE TITLE
domain separation of merkle tree

### ISSUE THREAD

**Issue by peterson674** [bitcoinjs/bitcoinjs-lib#1481]
Can someone  help....

I have been reading the code and I can't find the implementation of domain separation in the merkle tree between leaf nodes and internal nodes.
How domain separation is taken into account?

Regards

**Comment by junderw** [comment]
This is the code used for our merkleroot calculation:

https://github.com/bitcoinjs/merkle-lib/blob/3d2205c0130c664bb19f6aa39fecf6d92e9bd8a8/fastRoot.js#L1-L24

**Comment by peterson674** [comment]
I am sorry does it seems to me that this code doesn't take into account domain separation.
Please correct me if I am wrong

**Comment by junderw** [comment]
Bitcoin's merkle tree design doesn't have such considerations.

It is not an implementation problem.

Are you sure you're not confusing Bitcoin with something else?

**Comment by peterson674** [comment]
Thank you for providing us the bitcoinjs source code and thank you for the help.
I am sorry I didn't know that bitcoin merkle tree didn't have domain separation.
Thanks again!
