### ISSUE TITLE
How to create private key, cash address, sign transaction for bitcoin cash

### ISSUE THREAD

**Issue by thoth-ibl** [bitcoinjs/bitcoinjs-lib#1484]
Hello @dcousens, @junderw, @weilu  
I don't know how to create private key, cash address (bitcoincash:xxxxxxx), sign transaction for bitcoin cash.

Can you help me?
Thanks.

**Comment by dakk** [comment]
@thoth-ibl bitcoinjs does not support bitcoincash; you can use https://bitcoincashjs.github.io/ and ask to them if you have problems with it

**Comment by thoth-ibl** [comment]
bitcoincashjs project is no longer maintained.

**Comment by junderw** [comment]
I have a branch on my account's fork called cashv5.

You can use that, but the official repo will not support it.

npm install allows github links, branches can be specified with a pound sign.

**Comment by junderw** [comment]
As far as usage is concerned, TransactionBuilder has a method to activate forkid.

Psbt does it based on sighashes.
