### ISSUE TITLE
psbt.addBip32DerivationToInput() does not seem implemented

### ISSUE THREAD

**Issue by noudsnelder** [bitcoinjs/bitcoinjs-lib#1488]
Since I am new to this I may be completely wrong, but the example code on https://github.com/bitcoinjs/bip174 shows the psbt.addBip32DerivationToInput() function that I believe is not (yet) implemented since it returns TypeError: psbt.addBip32DerivationToInput is not a function. I am using "bitcoinjs-lib": "^5.1.6",

Am I missing something?

**Comment by junderw** [comment]
use `psbt.updateInput(index, { bip32Derivation })` for bitcoinjs-lib's Psbt.

**Comment by junderw** [comment]
you can see an example in the transaction integration tests.
