### ISSUE TITLE
P2WPKH signature fails

### ISSUE THREAD

**Issue by noudsnelder** [bitcoinjs/bitcoinjs-lib#1494]
If the output script in a P2WPKH transaction is a "pay-to-witness-pubkey-hash" then transaction fails with Script not verified successfully. But if I change output script to "pay-to-pubkey-hash" then transaction succeeds. I do not understand why, what can be wrong?

This transaction fails (to "tb1qsgtuc27y7jsa49a7c4yqd2fl7v5rye0ad258lh"):
020000000001012f53089c7ac89eeea9f46e16eebabe7082c872b687203117a9683d57313e901a0100000000ffffffff01c0570100000000001600148217cc2bc4f4a1da97bec54806a93ff3283265fd024730440220541df1a55c69524761be15efa5926dfcbbd3ea26f892c308f960f43f7834f923022066ed7bd7b754b529d1a9a3c40c3370e558c2270699aacb50c73b8396a4f30224012102715fdfa4cb9f272ac35470c6a59a23e7ba01951853c34f702d88b984e8df314300000000

And this transaction succeeds (to n3tBof7Tiq8WBW1TXiYpg6QKmpi95MJbA6):
020000000001012f53089c7ac89eeea9f46e16eebabe7082c872b687203117a9683d57313e901a0100000000ffffffff01c0570100000000001976a914f556c7c5f8cc38eafa556164e5163a6271b823b988ac02483045022100972525d6bd9766ccb1b8a318f09f1304b1ea5680858afd9a8a708fe3a476e07402205c703396bd584195a4e74ea054e6d4423efeb1cad2fe5af17e4302a946f5b296012102715fdfa4cb9f272ac35470c6a59a23e7ba01951853c34f702d88b984e8df314300000000

**Comment by junderw** [comment]
Show me your code, please.

**Comment by noudsnelder** [comment]
Showing code is rather complex since I make a PSBT file and sign it with offline device. But it could help if I understand psbt.addInput better: 

When I call psbt.addInput who should convert the witnessUtxo.script from '0014{hash160}' to '76a914{hash160}88ac' ?

Is this done by bitcoinjs? The example code suggests that bitcoinjs does not do this and I should do it. But I am not sure.

**Comment by junderw** [comment]
What does addInput have to do with changing the output?

I think you are getting confused.

**Comment by junderw** [comment]
Let me know if you still can't figure out your issue.
