### ISSUE TITLE
[Question] How can I know if a tx signature is ok without sending the tx to the blockchain?

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1497]
Hi.

Let's say I have a multisignature script. When each of the signers sign a tx I need to know whether the transaction was correctly signed (for instance that the real passphrase was used) so I can alert the signer that he made a mistake.

Thanks.

**Comment by junderw** [comment]
Psbt has verifySignature method.

But it won't verify anything other than the signature (ie. formatting, script, standardness rules etc.)

**Comment by junderw** [comment]
@educob Bitcoin Core has an RPC called `testmempoolaccept` since v0.17.0

You can send the raw transaction signed to that RPC and if you have a fully synched node it will fail if the signature is invalid or if something else is wrong (like the coins are already spent etc)

**Comment by junderw** [comment]
Let me know if you still have any questions.
