### ISSUE TITLE
Rounded value of feeRate, no public virtualSize property

### ISSUE THREAD

**Issue by JosipSylo** [bitcoinjs/bitcoinjs-lib#1500]
More of a question than an issue report.

I was wondering why the `feeRate` was rounded here:
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/psbt.js#L1143

It could also be useful to have a getter for the `virtualSize`. Similar to `getFeeRate`.

**Comment by junderw** [comment]
1. Bitcoin Core rounds fee rate down. It is better to under-measure your rate and pay an extra 0.0023 satoshi/byte than be over-measuring and miss some cut off for some miner etc.
2. Using `psbt.extractTransaction().virtualSize()` is sufficient. Creating a proxy for it will just create a cached Transaction internally anyways, so why bother?

**Comment by JosipSylo** [comment]
Thank you for a great and detailed explanation once again.
