### ISSUE TITLE
Is there a method for test if exists a tx in the memorypool using a determinate address?

### ISSUE THREAD

**Issue by soyjavi** [bitcoinjs/bitcoinjs-lib#1501]
Hi there,

I would like to know if there is the possibility to find out if a certain address has a transaction in memory pool (or at least know the last transaction made with that address).

Thank you very much (and sorry if this question has already been resolved).

best

**Comment by junderw** [comment]
NBXplorer is a good project. You run it on top of a Bitcoin node and it will tell you the transactions of specific addresses, including the mempool.

https://github.com/dgarage/NBXplorer
