### ISSUE TITLE
Used same pub key twice to create in p2ms

### ISSUE THREAD

**Issue by amantoor** [bitcoinjs/bitcoinjs-lib#1502]
I used the same pubkey twice to generate a multi signature address, now i am not able to spend, I can sign transaction fine but its give error :: 64: non-mandatory-script-verify-flag (Dummy CHECKMULTISIG argument must be zero) while broadcasting. I got funds locked, how can i spend

let pubkeys = [
    '02180d73b99486aa591398f970fa64ca56385bca28ad78b9c38daecfde454a57b1',
    '02180d73b99486aa591398f970fa64ca56385bca28ad78b9c38daecfde454a57b1'
].map(hex => Buffer.from(hex, 'hex'));

let p2ms = bitcoin.payments.p2ms({ m: 1, pubkeys });
let p2sh = bitcoin.payments.p2sh({ redeem: p2ms });

**Comment by junderw** [comment]
show the code you used to spend your coins. There's likely a bug.

**Comment by amantoor** [comment]
let pubkeys = [
'02180d73b99486aa591398f970fa64ca56385bca28ad78b9c38daecfde454a57b1',
'02180d73b99486aa591398f970fa64ca56385bca28ad78b9c38daecfde454a57b1'
].map(hex => Buffer.from(hex, 'hex'));

let p2ms = bitcoin.payments.p2ms({ m: 1, pubkeys });
let p2sh = bitcoin.payments.p2sh({ redeem: p2ms });    
let txb = new bitcoin.TransactionBuilder(bitcoin.networks.bitcoin);
    txb.addInput(TXID, 1, null, p2sh.pubkey);
    txb.addInput(TXID, 0, null, p2sh.pubkey);
    txb.addInput(TXID, 0, null, p2sh.pubkey);
    txb.addOutput(ADDRESS, 2382000);
    tx = txb.buildIncomplete();
    for (var i = 0; i < tx.ins.length; i++) {
        tx.ins[i].script = p2sh.redeem.output;
    }
    tx = tx.toHex();

**Comment by amantoor** [comment]
the same method worked for me in past when i used 2 of 3 and 2 were same pubkey and 3rd and different, but now only 2 same keys its not working

**Comment by amantoor** [comment]
It is indeed a bug the script is signing the transaction twice where it should check and ignore second time. I managed to spend the funds using python bitcoinutils.

**Comment by junderw** [comment]
you aren't signing anywhere.

This code by itself can never create a valid transaction.

**Comment by junderw** [comment]
This example, when added to `test/integration/transactions.spec.ts` it passes.

So it seems like the answer was just "sign once, then build"

Let me know if you have any further questions.

```js
it(
  'can create (and broadcast via 3PBP) a Transaction, w/ a ' +
    'P2SH(P2MS(2 of 2)) input with nonWitnessUtxo',
  async () => {
    const myKey = bitcoin.ECPair.makeRandom({ network: regtest });
    const myKeys = [
      myKey,
      bitcoin.ECPair.fromPrivateKey(myKey.privateKey!, { network: regtest }),
    ];
    const p2sh = createPayment('p2sh-p2ms(2 of 2)', myKeys);
    const myRedeemScript = p2sh.payment.redeem.output;
    const inputData = await getInputData(5e4, p2sh.payment, false, 'p2sh');

    const txb = new bitcoin.TransactionBuilder(regtest);
    txb.addInput(inputData.hash, inputData.index);
    txb.addOutput(regtestUtils.RANDOM_ADDRESS, 2e4);
    // only need to sign once, since .build()
    // will copy any signatures for multiple pubkeys.
    txb.sign({
      vin: 0,
      prevOutScriptType: 'p2sh-p2ms',
      keyPair: myKey,
      redeemScript: myRedeemScript,
    });
    const tx = txb.build();
    await regtestUtils.broadcast(tx.toHex());
    await regtestUtils.verify({
      txId: tx.getId(),
      address: regtestUtils.RANDOM_ADDRESS,
      vout: 0,
      value: 2e4,
    });
  },
);
```
