### ISSUE TITLE
Error: Input #0 has witnessUtxo but non-segwit script

### ISSUE THREAD

**Issue by aniketdivekar** [bitcoinjs/bitcoinjs-lib#1503]
Hi Guys, I'm trying to sign a transaction using the library but I'm getting below error:

`Error: Input #0 has witnessUtxo but non-segwit script: a914d82952189f437226406ec17c8c397a34af177cd187`

Could someone please help me understand where am I going wrong? 

Below is my code:
```
  const network = bitcoin.networks.testnet
  const psbt = new bitcoin.Psbt({ network })

  const amount0 = UNSPENT_OUTPUTS[0].amount * 100000000
  const amount1 = UNSPENT_OUTPUTS[1].amount * 100000000
 
  // input 1
  psbt.addInput({
    hash: UNSPENT_OUTPUTS[0].txid,
    index: UNSPENT_OUTPUTS[0].vout,
    witnessUtxo: {
      script: Buffer.from(UNSPENT_OUTPUTS[0].scriptPubKey, 'hex'),
      value: amount0
    }
  })

  // input 2
  psbt.addInput({
    hash: UNSPENT_OUTPUTS[1].txid,
    index: UNSPENT_OUTPUTS[1].vout,
    witnessUtxo: {
      script: Buffer.from(UNSPENT_OUTPUTS[1].scriptPubKey, 'hex'),
      value: amount1
    }
  })

  const totalAmount = amount0 + amount1
  const withdrawAmount = 0.0001 * 100000000
  const fee = 0.00001 * 100000000
  const change = totalAmount - (withdrawAmount + fee)

  psbt.addOutput({
    address: '2NF3WNhdXJzgChaAZgdYjHWaAvYG25Nhz58',
    value: withdrawAmount
  })

  psbt.addOutput({
    address: CHANGE_ADDRESSES[0],
    value: change
  })

  await psbt.signInputAsync(0, bitcoin.ECPair.fromWIF(PRIVATE_KEYS[UNSPENT_OUTPUTS[0].address], network))
  await psbt.signInputAsync(1, bitcoin.ECPair.fromWIF(PRIVATE_KEYS[UNSPENT_OUTPUTS[1].address], network))

  console.log('valid signature: ', psbt.validateSignaturesOfAllInputs()) // This prints true

  psbt.finalizeAllInputs()
  const rawHex = psbt.extractTransaction().toHex()
  console.log(rawHex)
```

Below is the list of Unspent transactions:
```
[
  {
      "txid": "a919fa237493c3479bd940adf73678293ed5dad673d00f465e7c76d5eeef2063",
      "vout": 1,
      "address": "2NCxBSjMaVeBFyxmGcD2X428v6k5n3pCQKN",
      "account": "payment",
      "redeemScript": "001495a994a417c45f97c87d03efb21997452d4c782f",
      "scriptPubKey": "a914d82952189f437226406ec17c8c397a34af177cd187",
      "amount": 0.00150000,
      "confirmations": 93,
      "spendable": true,
      "solvable": true,
      "safe": true
  },
  {
      "txid": "932e90d17b7d0db8a058bf8714e2db3dde5e74d5d3a6d1ea1d7efba39bd218a5",
      "vout": 1,
      "address": "2MzaZzn4cuAByJrNRpDHEgE8Z55Y7dsi3Gq",
      "account": "payment",
      "redeemScript": "00143c40cfa9281ac0f01b248cdaa33afe46fca00a4a",
      "scriptPubKey": "a91450717c6c3e59b94312fe5effe58e5d50edb8f69e87",
      "amount": 0.00150000,
      "confirmations": 90,
      "spendable": true,
      "solvable": true,
      "safe": true
  }
]
```

Thanks in advance :)

**Comment by aniketdivekar** [comment]
I had to add `redeemScript` in input.. It works now!

**Comment by rohitsahu21** [comment]
const bitcoin = require('bitcoinjs-lib');
const request = require('request-promise-native');

// const net = bitcoin.networks.bitcoin;
const net = bitcoin.networks.testnet;

const API = net === bitcoin.networks.testnet
    ? `https://test-insight.swap.online/insight-api`
    : `https://insight.bitpay.com/api`

const fetchUnspents = (address) =>
    request(`${API}/addr/${address}/utxo/`).then(JSON.parse);

(async () => {
    const psbt = new bitcoin.Psbt({ network: net });
    const alice_pair = bitcoin.ECPair.fromWIF('cR6RdGAojE4TuzRSY16a92vPfKgdjUj3tjHmoaPRcHvxRpTMr8gy', net);
    const pubkeys = [alice_pair.publicKey].map(hex => Buffer.from(hex, 'hex'));
    const { address } = bitcoin.payments.p2sh({ redeem: bitcoin.payments.p2ms({ m: 1, pubkeys, network: net }), });
    console.log('From Address:', address);

    const unspents = await fetchUnspents(address);
    console.log("++++++++++UTXO+++++++++++++", unspents, '\n\n');

    const totalAmount = unspents.reduce((summ, { satoshis }) => summ + satoshis, 0);
    const withdrawAmount = 0.001 * 100000000;
    const fee = 0.00001 * 100000000;
    const change = totalAmount - (withdrawAmount + fee);
    console.log(totalAmount, '+', withdrawAmount, '+', change);

    unspents.forEach(element => {
        psbt.addInput({
            hash: element.txid,
            index: element.vout,
            witnessUtxo: {
                script: Buffer.from(element.scriptPubKey, 'hex'),
                value: element.amount * 100000000
            },
            // redeemScript:Buffer.from(element.scriptPubKey)
        })
    });

    psbt.addOutput({
        address: '2NBJtjiL8kHb3vGW4b945rgSbh9zasAq7qB',
        value: withdrawAmount
    });

    psbt.addOutput({
        address: address,
        value: change
    });

    psbt.signInput(0, alice_pair);

    console.log('valid signature: ', psbt.validateSignaturesOfAllInputs()); // This prints true

    psbt.finalizeAllInputs();
    const rawHex = psbt.extractTransaction().toHex();
    console.log(rawHex);
})();


Same Error Plese help me where am I going wrong?

**Comment by junderw** [comment]
https://mempool.space/docs/api/rest#get-address-utxo
