### ISSUE TITLE
Is there example which get block information in Bitcoin?

### ISSUE THREAD

**Issue by hyunsooda** [bitcoinjs/bitcoinjs-lib#1509]
In the REAME.md file, it is not described how get block information in Bitcoin.

Where can I get the code or information?

**Comment by junderw** [comment]
Block information from what?

If you have a block's data as Buffer, you can just do Block.fromBuffer()

**Comment by hyunsooda** [comment]
Hi @junderw :)

The block information what I want to get is block size(WU or bytes), timestamp, height or # of txs, etc..

You said, `Block.fromBuffer()` function for block data query but there is no document in README.md. where is the entire document that describes data structure, function, etc?

**Comment by junderw** [comment]
The Block class is not documented outside of the source code itself.

ts_src/block.ts

It is also not well maintained, I recently added the ability to verify witness commit against the segwit transactions in the block, but I have yet to update byteLength to account for segwit yet.

Pull requests are welcome.

**Comment by hyunsooda** [comment]
Thanks for friendly replying @junderw :) have a nice day.
