### ISSUE TITLE
Issues with sending transaction based on Electrum format on testnet

### ISSUE THREAD

**Issue by tonychew1986** [bitcoinjs/bitcoinjs-lib#1511]
Here's my code to test sending a transaction:

---

const bip32 = require('bip32');
const bip39 = require('bip39');
const bitcoin = require('bitcoinjs-lib');
var bip32utils = require('bip32-utils')

const axios = require('axios');

var mnemonic = < mnemonic seed >
const seed = bip39.mnemonicToSeed(mnemonic)
const root = bip32.fromSeed(seed, bitcoin.networks.testnet);
const wif = root.toWIF({ network: bitcoin.networks.testnet });

console.log("seed", seed)
console.log("root", root)
console.log("wif", wif)

const key = bitcoin.ECPair.fromWIF(
  wif,
  bitcoin.networks.testnet
);

console.log("key", key)

var tx = new bitcoin.TransactionBuilder(bitcoin.networks.testnet);
tx.addInput("6c78ffa6471d10c7f49ec8a3a99bf2fa6f320f8980030caadb34b3546ca5444e", 24);
tx.addOutput("mxwzo8HoTf9pz9daguCCscyUkWvSmmpNzS", 17295837);
tx.sign(0, key);
console.log(tx.build().toHex());

---

UXTO:
<img width="943" alt="Screenshot 2019-11-25 at 3 10 47 PM" src="https://user-images.githubusercontent.com/6251226/69519790-d8cbcc80-0f95-11ea-86ed-131de7ad06ca.png">

---

Signed transaction i got with Transaction Builder:
020000000001014e44a56c54b334dbaa0c0380890f326ffaf29ba9a3c89ef4c7101d47a6ff786c18000000171600145b97e45461322289c9a67de56c5b23f509d04070ffffffff01dde90701000000001976a914bf36a0141ec7fe9f3e3f053bb9241443b5c49e0b88ac02483045022100d8f6a15a904bdef30cb159908d592272d39c692117666079e2cf4898278b44840220664243ac609047d3e6ac5dbc48337d3a424cce5e287d86a3446f98ca21af8c830121021538dfed059ef7f831e53a5c233b73921eb6cc1e09d4c45ae94a9260ca2f17ca00000000

--- 

Error when pushing transaction:
"Error validating transaction: Error running script for input 0 referencing 6c78ffa6471d10c7f49ec8a3a99bf2fa6f320f8980030caadb34b3546ca5444e at 24: Script was NOT verified successfully.."

**Comment by junderw** [comment]
1. The TX you posted is a segwit TX. The code you posted does not create a segwit TX. So I am guessing you made that TX with different code. Could you show me the code that creates that TX?
2. You likely need to derive a child key instead of just using the root key.

Please add a step to create the address and assert that the address of your ECPair key matches the address you expect it to be. And if it doesn't work then, let me know and post your updated code.

**Comment by junderw** [comment]
Yes, it looks like your were trying to sign with the private key for `mosFk9QMSdQSTtJRwz5fXFzoqx3GJhqpPa` when your UTXO is for the address `msjFmUD2R4PMvjW5o8s1ZsJVMwcQuHAejt`...

so you need to derive the correct key... I have no idea how you made `msjFmUD2R4PMvjW5o8s1ZsJVMwcQuHAejt` so I can't help you there unless you tell me how you made it.

Also, your transaction is segwit formatted....... but your code doesn't create a segwit transaction (when I run it)...

So just use your code above but be sure to derive the root to the correct address.

**Comment by tonychew1986** [comment]
I just realised that I forgot to use the child key. Let me try and get back on this. Will feedback regardless.

**Comment by tonychew1986** [comment]
Got it working. Issue is with child derivation path that I missed out. Working code below.

----

const bip32 = require('bip32');
const bip39 = require('bip39');
const bitcoin = require('bitcoinjs-lib');
var bip32utils = require('bip32-utils')

const axios = require('axios');

var mnemonic = < mnemonic >
const seed = bip39.mnemonicToSeed(mnemonic)
const root = bip32.fromSeed(seed, bitcoin.networks.testnet);
path = root.derivePath("m/44'/1'/0'/0/0")
const wif = path.toWIF({ network: bitcoin.networks.testnet });

const key = bitcoin.ECPair.fromWIF(
  wif,
  bitcoin.networks.testnet
);

console.log("key", key)

var tx = new bitcoin.TransactionBuilder(bitcoin.networks.testnet);
tx.addInput("6c78ffa6471d10c7f49ec8a3a99bf2fa6f320f8980030caadb34b3546ca5444e", 24);
tx.addOutput("mxwzo8HoTf9pz9daguCCscyUkWvSmmpNzS", 17295837);
tx.sign(0, key);
console.log(tx.build().toHex());

---

Signed Transaction:
02000000014e44a56c54b334dbaa0c0380890f326ffaf29ba9a3c89ef4c7101d47a6ff786c180000006b483045022100f61ac2217a1e898480c8b95f63a36ee60f6eef14a6a419660250fb71c221ac29022078c7e280df8a45dea158aa7e2873769eeed5963209cd9dd4759ff8ba0536964a012103e81dd9026de1ebb1599e46fe2443499525cb135bfb32e1353e5c2626b6dfcf09ffffffff01dde90701000000001976a914bf36a0141ec7fe9f3e3f053bb9241443b5c49e0b88ac00000000

---

Actual transaction:
https://live.blockcypher.com/btc-testnet/tx/c9eaf5225b7dd2baa56210d416bd817c24eb56e70bd2921773447b03cbd1047a/

---

Would have actually preferred to used PSBT but couldn't figure out how to get the "nonWitnessUtxo" bit under addInput().
