### ISSUE TITLE
It breaks existing ts configuration

### ISSUE THREAD

**Issue by kenshyx** [bitcoinjs/bitcoinjs-lib#1512]
Because `@types/node` is specified as a dependency, it breaks my existing project configuration: 
```
"@types/node": "12.12.12"
"typescript": "3.7.2"
```
Error:
> node_modules/@types/node/index.d.ts:200:11 - error TS2300: Duplicate identifier 'IteratorResult'.

The solution would be to move `@types/node` under `devDependencies`.

**Comment by junderw** [comment]
I wonder why this hasn't come up until now... You're not the only person using this library with TypeScript...

Could you explain why you are certain that the problem exists with us and not your app? (And if it is us, why are you the first one to report it after all this time?)

**Comment by kenshyx** [comment]
This might be because most of the projects don't use incremental builds for typescript. In the `tsconfig.tsbuildinfo` generated by [ts --build](https://www.typescriptlang.org/docs/handbook/project-references.html#build-mode-for-typescript) it overrides all the references for `@types/node`.
