### ISSUE TITLE
Warnings on install

### ISSUE THREAD

**Issue by ekkis** [bitcoinjs/bitcoinjs-lib#1527]
installing on OSX 10.14.6 (Mojave) I get the following warnings.  The "unused function" warnings I guess are just a matter of cleaning up the code but the integer comparisons I would think are of concern.  I'm guessing that's a platform dependent thing.  is there some way to tweak the meaning of "int" to "unsigned long"?  this should get cleaned up no?

~/dev $ npm i bitcoinjs-lib

> > tiny-secp256k1@1.1.3 install /Users/ekkis/dev/node_modules/tiny-secp256k1
> > npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."
> 
> 
> > tiny-secp256k1@1.1.3 build /Users/ekkis/dev/node_modules/tiny-secp256k1
> > node-gyp rebuild
> 
>   CXX(target) Release/obj.target/secp256k1/native/addon.o
> ../native/addon.cpp:240:2: warning: ignoring return value of function declared with 'warn_unused_result'
>       attribute [-Wunused-result]
>         secp256k1_ec_privkey_negate(context, tweak_negated); // returns 1 always
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
> ../native/addon.cpp:80:21: warning: comparison of integers of different signs: 'int' and 'unsigned long'
>       [-Wsign-compare]
>                 if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : S...
>                     ~~~~~~~~~~~~~ ^  ~~~~~
> ../native/addon.cpp:142:21: note: in instantiation of function template specialization '(anonymous
>       namespace)::assumeCompression<2, Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested
>       here
>         const auto flags = assumeCompression<2>(info, pA);
>                            ^
> ../native/addon.cpp:80:21: warning: comparison of integers of different signs: 'int' and 'unsigned long'
>       [-Wsign-compare]
>                 if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : S...
>                     ~~~~~~~~~~~~~ ^  ~~~~~
> ../native/addon.cpp:174:21: note: in instantiation of function template specialization '(anonymous
>       namespace)::assumeCompression<1, Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested
>       here
>         const auto flags = assumeCompression<1>(info, p);
>                            ^
> ../native/addon.cpp:87:21: warning: comparison of integers of different signs: 'int' and 'unsigned long'
>       [-Wsign-compare]
>                 if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
>                     ~~~~~~~~~~~~~ ^  ~~~~~
> ../native/addon.cpp:189:21: note: in instantiation of function template specialization '(anonymous
>       namespace)::assumeCompression<1, Nan::FunctionCallbackInfo<v8::Value> >' requested here
>         const auto flags = assumeCompression<1>(info);
>                            ^
> ../native/addon.cpp:21:32: warning: unused variable 'ZERO' [-Wunused-const-variable]
>         const std::array<uint8_t, 32> ZERO = {};
>                                       ^
> 5 warnings generated.
>   CC(target) Release/obj.target/secp256k1/native/secp256k1/src/secp256k1.o
> In file included from ../native/secp256k1/src/secp256k1.c:13:
> ../native/secp256k1/src/group_impl.h:686:12: warning: unused function 'secp256k1_gej_has_quad_y_var'
>       [-Wunused-function]
> static int secp256k1_gej_has_quad_y_var(const secp256k1_gej *a) {
>            ^
> ../native/secp256k1/src/group_impl.h:113:13: warning: unused function 'secp256k1_ge_set_gej_var'
>       [-Wunused-function]
> static void secp256k1_ge_set_gej_var(secp256k1_ge *r, secp256k1_gej *a) {
>             ^
> ../native/secp256k1/src/group_impl.h:267:12: warning: unused function 'secp256k1_gej_is_valid_var'
>       [-Wunused-function]
> static int secp256k1_gej_is_valid_var(const secp256k1_gej *a) {
>            ^
> In file included from ../native/secp256k1/src/secp256k1.c:15:
> ../native/secp256k1/src/ecmult_const_impl.h:123:13: warning: unused function 'secp256k1_ecmult_const'
>       [-Wunused-function]
> static void secp256k1_ecmult_const(secp256k1_gej *r, const secp256k1_ge *a, const secp256k1_scalar *scalar) {
>             ^
> 4 warnings generated.
>   SOLINK_MODULE(target) Release/secp256k1.node
> npm WARN proxy@1.0.0 No repository field.
> 
> + bitcoinjs-lib@5.1.6
> added 36 packages from 47 contributors and audited 328 packages in 8.87s
> found 0 vulnerabilities
>

**Comment by junderw** [comment]
This is an issue with tiny-secp256k1. Please open this issue over there when you get the chance.

Thanks.
