### ISSUE TITLE
bitcoinjs-lib在5.1.6版本中无法生成地址

### ISSUE THREAD

**Issue by DingGeng-GitHub** [bitcoinjs/bitcoinjs-lib#1528]
const bitcoin = require("./node_modules/bitcoinjs-lib");
const TestNet = bitcoin.networks.testnet;
let keyPair = bitcoin.ECPair.makeRandom({ network: TestNet });
let address = keyPair.getAddress();

报错：
let address = keyPair.getAddress();
                      ^

TypeError: keyPair.getAddress is not a function
    at Object.<anonymous> (E:\phpStudy\PHPTutorial\WWW\npm\bit.js:11:23)
?[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)?[39m

请问这个是什么原因导致的？怎么解决？

**Comment by longhoangwkm** [comment]
`getAddress` has already been removed at version 4, use `payments.p2pkh` instead. Please check examples for more information https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/addresses.spec.ts#L14
