### ISSUE TITLE
How to generate a BIP32 xpub from a mnemonic for segwit accounts?

### ISSUE THREAD

**Issue by borxes** [bitcoinjs/bitcoinjs-lib#1535]
I use the following code to generate a bip32 xpub:

```
function getXpub(mne: string, format: string) {
  const seed = bip39.mnemonicToSeedSync(mne) 
  const root = bip32.fromSeed(seed)
  const purpose = format === 'p2pkh' ? '44' : format === 'p2sh-segwit' ? '49' : '84'
  const path = `m/${purpose}'/1'/0'`
  const node = root.derivePath(path)
  return node.neutered().toBase58()
}
```

It generates a correct xpub for legacy p2pkh addresses, but not for segwit addresses. How can I fix it to work with segwit properly?

**Comment by borxes** [comment]
Found the answer here https://github.com/bitcoinjs/bitcoinjs-lib/pull/927

**Comment by youfoundron** [comment]
@yuradmt mind sharing the snippet that worked?
