### ISSUE TITLE
Examples on how to read private key from a wallet and create a wallet from a private key

### ISSUE THREAD

**Issue by calidion** [bitcoinjs/bitcoinjs-lib#1544]
Examples on how to read private key from a wallet and create a wallet from a private key

**Comment by junderw** [comment]
Using a combination of BIP39, BIP32 and a derivation path scheme such as BIP44 BIP49 or BIP84 should be fine.

Some examples are here:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/a543f5aa6b58dc92b5b4dd89b953353d9f99894a/test/integration/bip32.spec.ts

**Comment by calidion** [comment]
@junderw 

It seems the example use no private key and no wallet is generated?

**Comment by junderw** [comment]
Yes it does. Please read BIP32 to understand how HD key generation is used in wallets, then read BIP39 to understand how mnemonic phrases are used to store secret data for use in generating private keys then read BIP44 to understand the logic behind specific derivation paths and read BIP49 and BIP84 which are basically drop in replacements for BIP44 but with p2sh-p2wpkh and p2wpkh in mind respectively.
