### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by stevenKirill** [bitcoinjs/bitcoinjs-lib#1545]
Hello! I would like to ask about how can I connect this library to my current project. I don't use node in my project. It's just kinda old system maybe if we can call it. So basically, my project is just a bunch of HTML files and a folder CSS with files and JS folder with those files. Usually I either download directly JS file with library and put it in the HTML file , so then I can use abstractions of this file, or I use CDN link. But here the only one option I can do that is installing it through npm? Could anybody please help me how can I download or using maybe other ways to connect this lib into my project. Thank you! Best wishes!

**Comment by junderw** [comment]
use browserify to package this library into a standalone js file.

webpack also works.
