### ISSUE TITLE
Simple Generate Address

### ISSUE THREAD

**Issue by Pedroxam** [bitcoinjs/bitcoinjs-lib#1548]
I need a simple code to generate wallet address:

Please complete following code

```
var express = require('express');
var app = express();
var server = require('http').Server(app);
var bitcoinjs = require('bitcoinjs-lib');

app.get('/', function (req, res, next) {
    res.send(); // i need wallet address here
});

server.listen(3000);
```

**Comment by junderw** [comment]
generate a wallet address from what?

**Comment by Pedroxam** [comment]
> generate a wallet address from what?

For pay

**Comment by junderw** [comment]
> > generate a wallet address from what?
> 
> For pay

To what? Trezor? Ledger? BIP44/49/84?

**Comment by Pedroxam** [comment]
Look, this code

var derivedPubKey = ```
'xpub6AHA9hZDN11k2ijHMeS5QqHx2KP9aMBRhTDqANMnwVtdyw2TDYRmF8PjpvwUFcL1Et8Hj59S3gTSMcUQ5gAqTz3Wd8EsMTmF3DChhqPQBnU';

var hdNode = bitcoinjs.HDNode.fromBase58(derivedPubKey);

exports.deriveAddress = function(index) {
    return hdNode.derive(derivedPubKey).keyPair.getAddress().toString();
};
```
deriveAddress  Result is:

`Cannot read property 'fromBase58' of undefined`


What's problem ?

**Comment by Pedroxam** [comment]
problem was solved. thanks for your help.
