### ISSUE TITLE
Turning an unsigned transasction into a PSBT

### ISSUE THREAD

**Issue by KayBeSee** [bitcoinjs/bitcoinjs-lib#1550]
I am trying to take an unsigned transaction and turn it into PSBT format so I can sign it with my cold card hardware wallet.

I have an unsigned transaction `0100000003701d805440cc9883a4791c0dc660e38064cd805983cdabb7ac88aa78ce1837000000000000ffffffffb16a8a95d0e5f28d30833f45478a4f63a79dde6b2412c4443acf81749e903a6d0000000000ffffffff02e90615d330ae57c2dfcd9f7b8c22d6b872c4f49fd74d14025515576c9a5ea70000000000ffffffff02204e00000000000017a914013b3ecc4de17f26f4035d1c4e17976a4776daa7876e1f00000000000017a9141282b344adde09f7f86a1969e639a2ad231d7f6e8700000000`

Is there a way to turn that into a PSBT? I tried passing it into the constructor of PSBT and Transaction but both didn't seem to accept it.

**Comment by junderw** [comment]
Two ways to do this:

1. (Hard) Use bip174 library's Psbt class and create your own class that implements ITransaction for it, then plug it in. (If you look at ts_src/psbt.ts you can see how we implement it. Importing the bip174 Psbt as PsbtBase and implementing our own PsbtTransaction)

2. (Easier) Create a Transaction object using Transaction.fromHex() and then create a new Psbt object, and loop through the Transaction.ins and Transaction.outs and place the info into the PSBT as needed.

However, an unsigned transaction lacks the needed information for signing, so you must also include that information while you are looping the inputs and outputs to create the PSBT.

**Comment by junderw** [comment]
I highly recommend 2, since 1 will leave you with a PSBT with no input tags, and a PSBT without any input information is worthless... defeating the purpose of PSBT.

But it really depends on your needs. 2 will be best for 99.999% of cases.

**Comment by KayBeSee** [comment]
Thanks for the fast response Jonathan.

I am still struggling with this. I've tried these two ways:

```
const tx = new Transaction("0100000002b16a8a95d0e5f28d30833f45478a4f63a79dde6b2412c4443acf81749e903a6d0000000000ffffffff02e90615d330ae57c2dfcd9f7b8c22d6b872c4f49fd74d14025515576c9a5ea70000000000ffffffff02102700000000000017a914013b3ecc4de17f26f4035d1c4e17976a4776daa787b82100000000000017a9141282b344adde09f7f86a1969e639a2ad231d7f6e8700000000");

```

```
const tx = new Transaction();
const populatedTx = tx.fromHex("0100000002b16a8a95d0e5f28d30833f45478a4f63a79dde6b2412c4443acf81749e903a6d0000000000ffffffff02e90615d330ae57c2dfcd9f7b8c22d6b872c4f49fd74d14025515576c9a5ea70000000000ffffffff02102700000000000017a914013b3ecc4de17f26f4035d1c4e17976a4776daa787b82100000000000017a9141282b344adde09f7f86a1969e639a2ad231d7f6e8700000000");
```

but haven't been able to get anything populated. Do you see what I'm doing wrong here?

**Comment by junderw** [comment]
Transaction.fromHex("...")

static methods exist on the class and not on the object made from the class...

**Comment by KayBeSee** [comment]
That worked!
