### ISSUE TITLE
Missing bower_components/bitcoinjs-lib/build folder after bower install

### ISSUE THREAD

**Issue by coopci** [bitcoinjs/bitcoinjs-lib#1552]
I was setting up a [project()](https://github.com/OmniLayer/omniwallet) using bitcoinjs-lib as a dependency, it accesses [http://54.169.233.199/bower_components/bitcoinjs-lib/build/bitcoinjs-lib.js](url) from browser.  So I assume there should be a "build" subfolder under bower_components/bitcoinjs-lib/, but there actually isn't. How do I generate this "build" subfolder?

**Comment by junderw** [comment]
We don't support bower and precompiled js files.

Please read #1220 and #314 etc. to understand why.

**Comment by coopci** [comment]
My understanding is a precompiled min js introduces security issue. But the Nov 17, 2014 comment in [https://github.com/bitcoinjs/bitcoinjs-lib/issues/314](url) gives me an impression that it is possible for me to build it myself, how do I do that?
