### ISSUE TITLE
Get hash for signature in PSBT context

### ISSUE THREAD

**Issue by Janaka-Steph** [bitcoinjs/bitcoinjs-lib#1554]
Hello,

I would like to use the methods `hashForSignature` and `hashForWitnessV0` to get a hash to sign, in a PSBT context, but I can't find a way. Is that possible? Are there other similar methods?

Thank you

**Comment by junderw** [comment]
No, unfortunately there is not.

However, you can create a class for your signing process that adheres to the Signer / SignerAsync interface

https://github.com/bitcoinjs/bitcoinjs-lib/blob/dfda8c5ef3ccacc55ce3398399568da0466b7689/ts_src/ecpair.ts#L22-L34

With this, you can pass the object to signInput / signInputAsync etc. and the hash will be passed to the sign method on your object.

**Comment by junderw** [comment]
in the context of PSBT, only publicKey and sign() are used.

publicKey must be a 33 or 65 byte DER encoded pubkey Buffer and sign takes a 32 byte hash, signs it and returns a 64 byte signature (32 byte R value then 32 byte S value)

**Comment by junderw** [comment]
so you could make a dummy that will just eavesdrop on the hash and throw an error, then catch the error when you run signInput etc. and use that method to pull out the hash.

However, there is really no use case for these hashes outside of signing, so exposing them externally is not wise on our part.

I would be curious to hear your use case though.

**Comment by junderw** [comment]
So for instance:

```js
let inputHash;
const mySigner = {
  publicKey: Buffer.concat([Buffer.from([3]), Buffer.alloc(32)]),
  sign: (hash) => {
    inputHash = hash;
    return Buffer.alloc(64);
  },
};
psbt.signInput(n, mySigner)
console.log(inputHash);
```

But to be honest, if you're going to sign the hash eventually just implement that function inside the sign function or create a class that has a `this.publicKey` and a `sign` method.

**Comment by Janaka-Steph** [comment]
Hello,

Thank you for your detailed answer. I would like to reproduce this CLTV example (https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/cltv.spec.ts) using PSBT. 

My finalizer code looks like this. To get Alice's signature I wanted to use ECPair.sign(signatureHash). 

```
const getFinalScripts = (inputIndex, input, script) => {

  const inputScript = bitcoin.payments.p2sh({
    redeem: {
      input: bitcoin.script.compile([
        bitcoin.script.signature.encode(ECPairAlice.sign(signatureHash), hashType),
        bitcoin.opcodes.OP_TRUE,
      ]),
      output: redeemScript
    }
  }).input

  const payment = bitcoin.payments.p2sh({input: inputScript})

  return {
    finalScriptSig: payment.input
  }
}

psbt.finalizeInput(0, getFinalScripts)
```

Can I get Alice's signature to construct the unlocking script in another way?

Thank you

**Comment by junderw** [comment]
Please look at how we do this here:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/csv.spec.ts

You can sign just normally using psbt.signInput() and then you can access the signature via input.partialSig[0].signature.

**Comment by Janaka-Steph** [comment]
Oh great thank you, I will give it a try!

**Comment by makstr** [comment]
> So for instance:
> 
> ```js
> let inputHash;
> const mySigner = {
>   publicKey: Buffer.concat([Buffer.from([3]), Buffer.alloc(32)]),
>   sign: (hash) => {
>     inputHash = hash;
>     return Buffer.alloc(64);
>   },
> };
> psbt.signInput(n, mySigner)
> console.log(inputHash);
> ```
> 
> But to be honest, if you're going to sign the hash eventually just implement that function inside the sign function or create a class that has a `this.publicKey` and a `sign` method.

I have a very similar HSM use case, where the signer is only generating signatures, does not deal with PSBT and I need to extract the hashes from the psbt myself :) I tried your suggested approach Signer / SignerAsync eavesdropping on the hash with catch, but unless the signer ecpair is valid im hardly getting anywhere with this: 

```
err Can not sign for this input with the key 02fe804de2dee1e0257277ed049a3a2293b589600345b974d91e9db15d5c537aae
```

As I am reviving the problem after over 2 years since last activity I took a look at the underlying getHashForSig. And I found out it's not exported from the module and secondly it is rather broad in its context. So back again to eavesdropping

- am I missing something in my approach?
- has something changed which does not allow me to catch the "hash"
- why not offer the utxo hash extraction functionality? from the discussions I see this is is still a common requirement especially when dealing with legacy systems


Thanks

**Comment by junderw** [comment]
1. You need to include the actual pubkey for a/the script that you're signing so it knows when to run the sign method.
2. getHashForSig is not an external function.
3. For HSMs, you should actually build a SignerAsync interface that wraps your HSM logic.

ie.
```js
class HSMWrapper /* implements SignerAsync */ {
  constructor(keyId: string) {
    this.keyId = keyId;
  }
  async init() {
    // 33 byte or 65 byte DER Public Key Buffer
    this.publicKey = await HSMLibrary.getPublicKeyFromKeyId(this.keyId);
  }
  async sign(hash) {
    return HSMLibrary.signHashForKeyId(this.keyId);
  }
}

const signer = new HSMWrapper('myKeyLabel');
// assuming in async context
await signer.init();

psbt.signAsync(0, signer);
```

**Comment by makstr** [comment]
1.  I figured the pubkey was required on my own but was unsure if there was a better way :)
3. 100% this is the way to go, perfect, thank you!
