### ISSUE TITLE
[Typescript] Decode base64 PSBT and inspect outputs 

### ISSUE THREAD

**Issue by tiero** [bitcoinjs/bitcoinjs-lib#1555]
Hello!

I want to import a psbt from base64 string with `fromBase64()` and being able to inspect the outputs. If I try to access it via `psbt.data.outputs` it returns an array of empty objects.

Without typescript, I would have used `psbt.__CACHE.__TX` directly, but it's declared as private. 
The only way I found is to do the following:

```js
const psbt = Psbt.fromBase64(psbtBase64);
const bufferTx = psbt.data.globalMap.unsignedTx.toBuffer();
const tx = Transaction.fromBuffer(bufferTx)
console.log( tx.outs )
```

Is this the correct way to decode and inspect base64 psbt?

**Comment by junderw** [comment]
Yes. That would be the correct way to do this currently.

I would be up for a suggestion on how to make the PSBT easier to inspect.

(Perhaps a lazy getter that will return the outs with an added address attribute that will encode the output script according to the network object passed to the PSBT etc.)

If you have a good idea, let me know.
