### ISSUE TITLE
Add browser bundle policy to README

### ISSUE THREAD

**Issue by xloem** [bitcoinjs/bitcoinjs-lib#1557]
It hurts to have my threads locked when I am trying to find ways to support the project that are in line with your needs.

I'm still trying to negotiate my original desire to share with users of this project (the form of which was at first a browser bundle), with the unadvertised policy of encouraging more source review by discouraging shared browser bundling.

I want to support you.  Please don't lock my threads.  It prevents and discourages further communication, not to mention disheartening possible support for the project.

Would you be willing to plan or gather around work to clarify the browser bundle policy in the README?  I am happy to write up a summary of the policy in an attempt to make peace.

(EDIT: previous threads: #1556 #965 #1220 #314 and others)

**Comment by xloem** [comment]
Thinking about this, it sounds like it is of utmost importance to spread the library in ways that encourage security, and that needs to be upheld above anything else in any work.

I'm thinking on how best to sustain security in an environment of browser app development.

**Comment by junderw** [comment]
Regarding your suggestion to add something to the README:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/README.md#can-i-trust-this-code

and

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/README.md#browser

This is already in the README, and this topic has been discussed ad nauseam in various issues.

Any attempt at providing a pre-bundled js file, linking to one on any issue or pull request will be moderated. This point is not up for discussion. Regardless of how secure anyone thinks they can make it.

----

Also, a few points:

- Closing/locking your issues is nothing personal or anything you should feel you need to defend yourself against.
- Passive aggressive titles are also frowned upon. (Not to mention issue titles that don't match up with the issue contents)
- Creating new issues to circumvent issue locking is grounds for a ban on most online forums. I'm not one to jump to banning quickly, but let this serve as a warning. Circumventing moderation is the quickest way to get yourself banned/reported.

**Comment by xloem** [comment]
@junderw, thank you for not locking the issue, so I have a chance to say these thanks.  We have different ideas, but what is most important is that pain has flowed between us, and we are both simply struggling to do what is best in our hearts.  I am only trying to say that I love you and your project, and it hurts to be sent away so thoroughly.  Thank you again.

Don't let the workaholic norms make you forget how important your heart and those hearts you touch, really are.
