### ISSUE TITLE
Cannot sign according to BIP143, when using PSBT with custom scripts in P2SH(P2WSH)

### ISSUE THREAD

**Issue by CodeForcer** [bitcoinjs/bitcoinjs-lib#1558]
I'm trying to spend from a P2SH(P2WSH) input, which requires a witness stack to unlock with some custom parameters including a signature of the entire transaction.

However, in all the PSBT examples I can't see any way of dealing with custom locking/unlocking scripts, and no way to produce valid signatures for P2SH(P2WSH) inputs according to the BIP143 standard.

I've seen a few examples online of calling setWitness in the transaction builder object, but that appears to be deprecated. Also, the examples don't cover situations where we need to provide a signature of the transaction as part of the witness stack.

Can anyone point me in the right direction here? I've been reading the source code for psbt but I can't see anywhere that handles this. I've been able to do this entire process in Python using the Electrum libraries so I know it is possible.

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/c95e15de01519b30c5eeb0f89700d03e49afb0e1/test/integration/csv.spec.ts

This is an example of custom scripts.

However, the checks I put in there are extremely dumb (I am merely checking if the first OP is OP_IF) but if you create one for any serious app you want to make one that is more thorough in checking things.

By default, signInput (etc.) just runs through every chunk of the witnessScript, redeemScript, and scriptPubkey and if it finds your pubkey or pubkey hash anywhere it will sign. The checks you add in will be performed during the finalize step.

(I am thinking of adding a method for adding custom checks to signing too... not sure which way to go about it though.)

**Comment by junderw** [comment]
Specifically:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/c95e15de01519b30c5eeb0f89700d03e49afb0e1/test/integration/csv.spec.ts#L118-L171

Which passes the checking function to finalizeInput: (When you make yours just match the args and return values)

https://github.com/bitcoinjs/bitcoinjs-lib/blob/c95e15de01519b30c5eeb0f89700d03e49afb0e1/test/integration/csv.spec.ts#L431-L514

**Comment by CodeForcer** [comment]
Thanks @junderw, I've been able to correctly build my transactions to replicate the verified results from Electrum.
