### ISSUE TITLE
TODO: Psbt add methods to access Tx info

### ISSUE THREAD

**Issue by junderw** [bitcoinjs/bitcoinjs-lib#1559]
Could be getters:
inputs: hash, index, sequence
outputs: script, value

New method:
CheckForPubkey = pass it an index and a pubkey, it will take the hash160 and decompile the scriptPubkey, redeemScript (if any) and witnessScript (if any) to search for the pubkey or its hash160 and return true or false if it finds it. This method should also be available for outputs as well. Should throw an error if it sees a P2SH/P2WSH without the corresponding script.

**Comment by atlantic-blockchain** [comment]
I would also like to see functionality that allows me to query the blockchain. I want to pass it an address or hash, and receive back the result.

**Comment by dakk** [comment]
@atlantic-blockchain that is beyond the skills of this library; there are other libraries that you can use to obtain blockchain data

**Comment by junderw** [comment]
Solved in #1561 and #1563
