### ISSUE TITLE
How to calculate fee

### ISSUE THREAD

**Issue by amirh3n** [bitcoinjs/bitcoinjs-lib#1566]
I have a transaction with 3 inputs and 2 outputs. 1output is the recipient and the other output is change address. How should I calculate the fee and apply it to output?

**Comment by junderw** [comment]
To calculate fee you need 2 numbers:

1. feeRate (usually in satoshis/byte or BTC/kilobyte)
2. byte count (or vSize for segwit)

You can get 1 from many different places. One being the `estimatesmartfee` RPC for bitcoind.

2 is tricky. Most people do one of two things:

1. create a transaction with no fee (change output value = input total - send total) sign it, then when you get the Transaction object, do `tx.virtualSize()` to get the byte count (vSize for non-segwit transactions is the same as byte size, so always use virtualSize()) Then throw away that signed transaction, and use the virtualSize only. But when doing this you should be careful to add 1 byte for every signature just in case. So if you have 3 inputs of 2-of-3 multisig, that is 2 signatures x 3 inputs, so 6 signatures, so add 6 to the virtualSize.
2. Estimate the size of your inputs and outputs by looking at the size of similar scripts.

Once you get the two data points

```js
const fee = feeRate * vSize // where feeRate is satoshi / byte
const changeValue = totalInputValue - totalSendValue - fee
```

Then change the value for the change output, then sign each input again, and broadcast this time.
