### ISSUE TITLE
Is `bitcoinjs-lib` available as a server?

### ISSUE THREAD

**Issue by msafi** [bitcoinjs/bitcoinjs-lib#1569]
I want to use `bitcoinjs-lib` but I don't want to mix it in with my UI code for security reasons. I prefer to have my UI interact with `bitcoinjs-lib` through RPC or some such mechanism. Is `bitcoinjs-lib` available this way? If not, I may have build this server-wrapper around it myself..

**Comment by junderw** [comment]
bitcoinjs-lib is not a server daemon, nor is it a client application.

It is a library which can be called from a client application or a server daemon.
