### ISSUE TITLE
javascript:  keypair.getAddress is not a function

### ISSUE THREAD

**Issue by escapefelicity** [bitcoinjs/bitcoinjs-lib#1571]
var bitcoin = require('bitcoinjs-lib'); 
var keypair = bitcoin.ECPair.makeRandom()

var address = keypair.getAddress().toString();

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/CHANGELOG.md#400

"removed" bullet point 3.

It was removed in v4 almost 2 years ago. Please read the examples linked in the README for examples pertaining to the current version.

**Comment by escapefelicity** [comment]
Thank you Jonathan.  I was tearing my hair out.  I'll buy you a beer.  Send
your BTC or DGB address.
