### ISSUE TITLE
Any interest in an RPC Add On?

### ISSUE THREAD

**Issue by abunsen** [bitcoinjs/bitcoinjs-lib#1576]
Hi! Wondering if there is any interest for the library to be extended to support making RPC calls? As it stands now, I'd need to create an address, then a transaction and sign it with bitcoinjs-lib, then I'd need to use fetch or axios or some other http lib to send it to my bitcoind node, after that, I'd need to make more calls by hand to make sure its in the mempool, that its confirmed, etc. 

Would be really sweet if this lib let me do all the things - I'm happy to write the code + tests. But didn't want to go through the effort if there is no interest from the maintainers.

**Comment by junderw** [comment]
This library should not have an RPC add on.

However, we are looking into creating a wallet abstraction library that will use this library as a dependency.

That library could use such a library as an optional dependency. But currently I haven't started on the wallet abstraction library yet.
