### ISSUE TITLE
txOutputs of PSBT fails for nonstandard outputs

### ISSUE THREAD

**Issue by sidhujag** [bitcoinjs/bitcoinjs-lib#1577]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/85ee2a3c5d1cdbf111232e6eb00ce0ce3bc398a6/src/psbt.js#L123

Seems to have an issue with nonstandard outputs, is it supposed to support OP_RETURN outputs? We should be able to get all outputs even nonstandard ones.

**Comment by lukechilds** [comment]
@sidazhang good catch, yes we should definitely be handling that.

@junderw what do you think we should we do here?

- try/catch and return undefined for scripts that fail.
- Remove the address property completely if we know it can't always reliable exist.

**Comment by junderw** [comment]
> try/catch and return undefined for scripts that fail

Do this. I'll push out a patch.

**Comment by junderw** [comment]
update to patched v5.1.9.

Thanks for the report.
