### ISSUE TITLE
Creating one transaction FAILED

### ISSUE THREAD

**Issue by cezarlacatus** [bitcoinjs/bitcoinjs-lib#1584]
Hello,

I want to make a nodejs script that takes a mnemnotic as input and it will generate an address with a custom deviation path(m/49'/1'/0'/0/0) then it will generate a transaction hex.
 
I've tried combining multiple outdated codes from different sources and I've come up with the following code:

```js
var bip39 = require("bip39"); // npm i -S bip39
var bip32 = require("bip32");
const axios = require("axios");
var bitcoin = require("bitcoinjs-lib");
const qs = require("querystring");
const network = bitcoin.networks.testnet;

mnemonic =
  "alcohol follow plastic spot leg define virus response tuna garment eternal return";

var seed = bip39.mnemonicToSeedSync(mnemonic);
const root = bip32.fromSeed(seed);

const child = root.derivePath("m/49'/1'/0'/0/0");

var key = bitcoin.ECPair.fromPrivateKey(child.privateKey, { network: network });

const test = bitcoin.payments.p2sh({
  redeem: bitcoin.payments.p2wpkh({
    pubkey: key.publicKey,
    network: network,
  }),
  network: network,
});
console.log(test.address); // 2NG5JsiMnYkj4nJAbaLNbBnMYD6zUpgY3Ay

var tx = new bitcoin.TransactionBuilder(network);
tx.addInput(
  "a7a17aab74725f9b3249660c6c9205bb9ca4518e962c833b2209cc648c380093", // https://live.blockcypher.com/btc-testnet/tx/a7a17aab74725f9b3249660c6c9205bb9ca4518e962c833b2209cc648c380093/
  1
);
tx.addOutput("2MxiwvpXw4UvZGDUw7BYP8abXfGFqsxei8K", 5000);
tx.sign(0, key);
console.log(tx.build().toHex());
//Submited to https://live.blockcypher.com/btc-testnet/pushtx/
//ERROR: Error validating transaction: Error running script for input 0 referencing a7a17aab74725f9b3249660c6c9205bb9ca4518e962c833b2209cc648c380093 at 1: Script was NOT verified successfully..
```

Output transaction hex : 02000000019300388c64cc09223b832c968e51a49cbb05926c0c6649329b5f7274ab7aa1a7010000006b483045022100c1e8909d99d15e2975c01458141d1d8a842c7b2c006f3ac93e06d27a3abc0d560220510266edf488e39917d98f4bd690d058139c6b5eeed2e8fcd9252a1c965afaa10121039f9a080198404852f8619a493d8aebad5f68b11e9677e320eb144bcea18dd9b5ffffffff01881300000000000017a9143c16deaff20ce5c8d7b62394fd99d21547c90ae28700000000

I got one error when I submit the hex to blockcypher:  Error running script for input 0 referencing a7a17aab74725f9b3249660c6c9205bb9ca4518e962c833b2209cc648c380093 at 1: Script was NOT verified successfully..

And I don't know where is the mistake.I couldn't find anything that can help me make this code working....

Please, if anybody could help me, I would be grateful....

**Comment by junderw** [comment]
TransactionBuilder is deprecated. Use Psbt.
```js
var tx = new bitcoin.Psbt({ network })
  .addInput({
    hash: "a7a17aab74725f9b3249660c6c9205bb9ca4518e962c833b2209cc648c380093",
    index: 1,
    redeemScript: test.redeem.output, // redeemScript needed for P2SH
    witnessUtxo: {
      script: test.output, // the script of the output pointed by this input
      value: 1e6, // the value of the output pointed by this input
    },
  })
  .addOutput({
    address: '2MxiwvpXw4UvZGDUw7BYP8abXfGFqsxei8K',
    value: 5000,
  })
  .signInput(0, key)
  .finalizeInput(0)
  .extractTransaction(true);
// extractTransaction(true) this `true` ignores "high-fee" error.
// (This transaction is paying a super high fee, so without true it will Error... 
// you should not use this on mainnet in production)
// This is the Error you would normally see:

// Warning: You are paying around 0.00994950 in fees, which is 
// 7425 satoshi per byte for a transaction with a VSize of 134 bytes 
// (segwit counted as 0.25 byte per byte). Use setMaximumFeeRate 
// method to raise your threshold, 
// or pass true to the first arg of extractTransaction.

console.log(tx.toHex());
```

**Comment by junderw** [comment]
You can also use the maximumFeeRate parameter when creating your Psbt instead of ignoring the high-fee error.

`var tx = new bitcoin.Psbt({ network, maximumFeeRate: 7500 })`

**Comment by junderw** [comment]
Default is 5000

**Comment by cezarlacatus** [comment]
@junderw Omg, you saved me.The code is working.
I have a question: From where do I get the value: 1e6  for the witnessUtxo?
I really don't know from where do I get that.....

**Comment by junderw** [comment]
`1e6` is shorthand for `1000000` which is the satoshi value for `0.01 BTC` which is the amount of money in the output that is referenced by the input. (The second output of `a7a17aab74725f9b3249660c6c9205bb9ca4518e962c833b2209cc648c380093` )
