### ISSUE TITLE
Setting a custom feerate requires creating two transactions.

### ISSUE THREAD

**Issue by pedr0-fr** [bitcoinjs/bitcoinjs-lib#1591]
I'm still new to bitcoinJS so this might rather be a question/suggestion. I noticed that if I want to set a custom feerate, I need to create the transaction twice, the first time to get the transaction size and a second time to set the correct amount of change calculated from the transaction size. Notice that I am concerned about feerate and not absolute fee which is easier (and has already been asked - eg. [here](https://stackoverflow.com/questions/45465787/how-to-set-amount-of-transaction-fee-using-bitcoinjs)) 

AFAIK there is no transaction size calculator and I prefer to know the exact size rather than using some heuristic. Psbt.updateOutput() can't be used to update the value of the change output since PsbtOutputUpdate doesn't allow for these updates (these would require signing again, but it still sounds much more cleaner to me).

Here is some working code (with a fake input, just to demonstrate), any suggestions to simplify setting a custom feerate are welcome:

```
import bitcoin = require("bitcoinjs-lib");
import bip32 = require("bip32");
import bip39 = require("bip39");

const btcMainnet = bitcoin.networks["mainet"];

let mnemonic = bip39.entropyToMnemonic("07d48e843e67c57148f91b2ae5eb92a4");
let seed = bip39.mnemonicToSeedSync(mnemonic);
let master: bip32.BIP32Interface = bip32.fromSeed(seed, btcMainnet);
let child: bip32.BIP32Interface = master.derivePath(`m/44'/0'/0'/0/0`);
let segwit_address = bitcoin.payments.p2wpkh({ pubkey: child.publicKey });

let desired_feerate: number = 10.0;
let input_total: number = 9000;
let amount_to_send: number = 3000;
let change_amount: number = 566; // on the dust limit for now, will be set later

function make_transaction(change: number): bitcoin.Psbt {
  let tx: bitcoin.Psbt = new bitcoin.Psbt();
  tx.addInput({
    hash: "2d2450af851880c4b940ada9e7db2d8cee9a06352504411c020aa084b5008287",
    index: 0,
    sequence: 0xfffffffd,
    witnessUtxo: {
      script: bitcoin.address.toOutputScript(
        segwit_address.address,
        btcMainnet
      ),
      value: input_total,
    },
  });

  tx.addOutput({
    address: "1BitcoinEaterAddressDontSendf59kuE",
    value: amount_to_send,
  });
  tx.addOutput({
    address: segwit_address.address,
    value: change,
  });

  tx.signAllInputs(child);
  tx.validateSignaturesOfAllInputs();
  tx.finalizeAllInputs();
  return tx;
}

let preliminary_tx: bitcoin.Psbt = make_transaction(change_amount);

// CAN'T UPDATE OUTPUT AMOUNT
// preliminary_tx.updateOutput(1, {
//  address: segwit_address.address,
//  value: change_amount + 100,
//});

let tx_size: number = preliminary_tx.extractTransaction().virtualSize();
change_amount = input_total - tx_size * desired_feerate - amount_to_send;
let final_tx = make_transaction(change_amount);

console.log(
  "preliminary feerate=" +
    preliminary_tx.getFeeRate() +
    ", final feerate=" +
    final_tx.getFeeRate()
);
```

**Comment by lukechilds** [comment]
This is an inherent property of Bitcoin transactions, not specific to BitcoinJS.

You don't know the size of a transaction until you've signed it, since the signatures vary in size. You could make a reasonably accurate guess without creating duplicate transactions by just assuming each sig will be a certain size.

**Comment by lukechilds** [comment]
Although maybe we could make this easier with some sort of method where you pass a fee rate and the change output index and we reduce its value by the approximate amount to reach the desired fee rate.

```js
psbt.setFee(feeRate: number, changeOutputIndex: number)
```

where `feeRate` is the sat/b value and `changeOutputIndex` is the index of the output to be reduced.

Maybe directly modifying the output value isn't a good idea but a helper method that does the calculations and returns the amount of satoshis that need to be deducted could be useful.

@junderw thoughts?

**Comment by junderw** [comment]
1. Modifying script/value after adding: This encourages bad coding practices and should be avoided. (Psbt data is update-able because it is merely metadata)
2. Estimating fee is fully possible if you have an understanding of how transactions work at a low level. `coinselect` library (ours) works well, but it really needs a re-vamping... it doesn't support segwit.

Maybe adding a addDummySig method could help... but you could just do that with updateInput and constructing your own partialSig object... you'd need the correct pubkey though.

**Comment by Aman9723** [comment]
@junderw need help. I can't find any way around my problem instead of updating the output address in 1st index of PSBT. I have studied how unisat implements the PSBT and I came to observation that they also update the output for the nft marketplace. Below is the design of the PSBT. Please guide me to the solution. Thanks.

![image](https://github.com/bitcoinjs/bitcoinjs-lib/assets/65977764/37e01342-5c63-48b5-b02a-5b6a7968a001)

**Comment by junderw** [comment]
Your diagram makes no sense. I'm sorry I can't help you with the information you've given.

**Comment by Aman9723** [comment]
I want to update the output address at 1st index once the PSBT  is signed with sighash 131 at index 2.

```js
const psbt = new bitcoin.Psbt({ network })

        psbt.addInput({
            hash: psbtSignerUtxo[1].txid,
            index: psbtSignerUtxo[1].vout,
            witnessUtxo: {
                value: psbtSignerUtxo[1].satoshi,
                script: Buffer.from(psbtSignerUtxo[1].scriptPk, 'hex'),
            },
        })
        psbt.addInput({
            hash: psbtSignerUtxo[2].txid,
            index: psbtSignerUtxo[2].vout,
            witnessUtxo: {
                value: psbtSignerUtxo[2].satoshi,
                script: Buffer.from(psbtSignerUtxo[2].scriptPk, 'hex'),
            },
        })
        // NFT UTXO
        psbt.addInput({
            hash: utxo.txid,
            index: utxo.vout,
            witnessUtxo: {
                value: utxo.satoshi,
                script: Buffer.from(utxo.scriptPk, 'hex'),
            },
            sighashType: 131,
        })

        psbt.addOutput({
            address: this.psbtSigner,
            value: 2,
        })
        psbt.addOutput({
            address: this.psbtSigner,
            value: utxo.satoshi,
        })
        psbt.addOutput({
            address: utxo.address,
            value: price,
        })

        this.market[inscriptionId] = {
            lister,
            buyer: undefined,
            price,
            listerPsbt: undefined,
        }

        console.log(psbt.toHex())
```

**Comment by Aman9723** [comment]
1. I will create a PSBT then send to lister. 
2. He will sign and return the PSBT hex.
3. When the buyer will come we will present the same PSBT with _updated output_.

The problem is in step 3 in the below code. I know you have told not to update output (bad coding practise) but we don't have any other option.

```js
purchaseOrder(inscriptionId, buyer, utxo = buyerUtxo) {
        const order = this.market[inscriptionId]
        if (!order) throw new Error('Order not found.')

        const psbt = bitcoin.Psbt.fromHex(order.listerPsbt, { network })

        // check if 0 and 1 inputs are altered
        // nft utxo unaltered
        psbt.addInput({
            hash: buyerUtxo.txid,
            index: buyerUtxo.vout,
            witnessUtxo: {
                value: buyerUtxo.satoshi,
                script: Buffer.from(buyerUtxo.scriptPk, 'hex'),
            },
        })
        psbt.addInput({
            hash: psbtSignerUtxo[0].txid,
            index: psbtSignerUtxo[0].vout,
            witnessUtxo: {
                value: psbtSignerUtxo[0].satoshi,
                script: Buffer.from(psbtSignerUtxo[0].scriptPk, 'hex'),
            },
        })

// -----------------------------------------------HERE IS PROBLEM-----------------------------------------------
        psbt.updateOutput(1, {
            address: buyer,
            value: nftUtxo.satoshi,
        })
        // lister output unaltered
        psbt.addOutput({
            address: this.platformWallet,
            value: this.platformFee,
        })
        psbt.addOutput({
            address: buyer,
            value:
                buyerUtxo.satoshi - this.fee - this.platformFee - order.price,
        })
        psbt.addOutput({
            address: this.psbtSigner,
            value: 1,
        })
        psbt.addOutput({
            address: this.psbtSigner,
            value: 1,
        })

        this.market[inscriptionId].buyer = buyer
        // psbt.signAllInputs(this.#psbtSignerKeyPair)
        console.log(psbt.toHex())
    }
```

**Comment by junderw** [comment]
`psbt.data.globalMap.unsignedTx.tx.outs[1]` is the location of the 2nd output.

Modification of it is not supported, but if you do it. You do it at your own risk.

We will not offer support or take any responsibility for anything you do with that information.

**Comment by Aman9723** [comment]
I am aware of this, don't worry. One last question about security.

If I signt the psbt with `psbt.signAllInputs(this.#psbtSignerKeyPair)`. Anyone will be able to modify the PSBT inputs/outputs and broadcast it? After this sign I want to give the PSBT to buyer for the last signature at index 3. I don't want the buyer to mutate it.

**Comment by junderw** [comment]
It depends on which sighash you use. The default sighash will sign all inputs and outputs, so unless you change that, any changes will invalidate your signature.

**Comment by ctarbide** [comment]
I had to come up with something like this:

```javascript
const dummyPubKey = keyPair.publicKey;

// create a dummy signature and fill some DER shenanigans
const dummySig = new Uint8Array(72);
dummySig[0] = 0x30;
dummySig[1] = dummySig.length - 3;
dummySig[2] = 0x02; // r type, 0x2=integer
dummySig[3] = 33; // rLen, 33 bytes (includes 1-byte padding)
dummySig[4] = 0x00; // r value 0x00 padding byte, makes a large 'r' positive
dummySig[5] = 0x80; // mimic an integer with the 256th msb set
dummySig[37] = 0x2; // s type, 0x2=integer
dummySig[38] = 32; // sLen, 32 bytes (no padding)
dummySig[39] = 1; // mimic an integer with the 256th msb clear
dummySig[71] = 1; // SigHash Flag, SIGHASH_ALL
```

then later on do:

```javascript
psbt.updateInput(index, {
    partialSig: [{
        pubkey: dummyPubKey,
        signature: dummySig,
    }]
});
```

after that all validations passed and I was able to create a dummy transaction for the sole purpose of computing a precise fee
