### ISSUE TITLE
I having trouble creating a multiSig transaction using redeemScript (Newbie)

### ISSUE THREAD

**Issue by nbass** [bitcoinjs/bitcoinjs-lib#1594]
Hi.

I already have redeemScript and I want to make multiSig Transaction using this. But I am not sure how to use this.

redeemScript:
`2 029ad39c94e79693b1235017b218e64e75de6da6e17d8e3ab57b442c0708a2755b 0299364817a1f7b342a2ae788d7c9a407b18e63ae50b2d83351f653eba47b26aa6 2 OP_CHECKMULTISIG`

```js
const utxo = [{
    Amount: 0.0010612,
    Confirmations: 104775,
    Index: 1,
    ReservedFundsRedeemScript: "2 029ad39c94e79693b1235017b218e64e75de6da6e17d8e3ab57b442c0708a2755b 0299364817a1f7b342a2ae788d7c9a407b18e63ae50b2d83351f653eba47b26aa6 2 OP_CHECKMULTISIG",
    Tx: "0200000001f03747bbd19f3a4572e83be32368ab9d1f01ba54211a26988245460068aab19f010000006a47304402206a96f27bc00f1785faf61bdab56c18a04f004e83def07a3cb66e0d31bd0eac8e022045c8a6e09a1fcc36f5fcbdbdd1e9bf3b015bf866f43bfab6e02ee0659e9c3bd0012103919069dbe0fb81cdadbad46f54ee33b07a46384294ed9d0b0d9dbdf9cc2ca765ffffffff0250710700000000001976a914f3c2b1fe22fdd18becbe7865f3afbbe6431e4fbf88ac889e01000000000017a914ddc0725194410517a78539ca18296d7a0597addb8700000000",
    TxHash: "72eed3dda4f0ea8e83a93761e41b40f4f8818b4699252c96d00b60b01ae05fc1",
}];

const bitcoinjsLib = require('bitcoinjs-lib');
const satoshi = require('satoshi-bitcoin');
const bigInt = require('big-integer');
const network = bitcoinjsLib.networks.testnet;
const keyPair = bitcoinjsLib.ECPair.fromWIF(myPrivate, network);
const tx = new bitcoinjsLib.Psbt({ network });
const amount = bigInt(satoshi.toSatoshi(AMOUNT));

const targetOutput = utxo[0];

const inputParam = {
    hash: targetOutput.TxHash,
    index: targetOutput.Index,
    nonWitnessUtxo: Buffer.from(targetOutput.Tx, 'hex'),
    redeemScript: ???,
};
tx.addInput(inputParam);
tx.addOutput({ address: args.receiversAddress, value: amount.toJSNumber() });
tx.signInput(0, keyPair);

tx.finalizeAllInputs();
const rawTx = tx.extractTransaction().toHex();
```

Can you give me some hints to help me solve this problem? Thank you very much.

**Comment by junderw** [comment]
if you change 2 to OP_2 you can use script fromASM.

I would think whatever api you use to get the redeemscript should just have the redeemscript hex as one big blob somewhere though.

Where are you getting your utxo info from?

**Comment by junderw** [comment]
Is this the API? https://docs.gluwa.com/

**Comment by nbass** [comment]
Thanks for your answer.
I got this UTXO from https://docs.gluwa.com, as you said.

```javascript
function getRedeem(redeem) {
    const a = redeem.split(' ');
    return `OP_${a[0]} ${a[1]} ${a[2]} OP_${a[3]}`;
}

const targetOutput = utxo[0];
const redeemScript = getRedeem(targetOutput.ReservedFundsRedeemScript);

const inputParam = {
    hash: targetOutput.TxHash,
    index: targetOutput.Index,
    nonWitnessUtxo: Buffer.from(targetOutput.Tx, 'hex'),
    redeemScript: bitcoinjsLib.script.fromASM(redeemScript),
};

tx.addInput(inputParam);
tx.addOutput({ address: args.receiversAddress, value: amount.toJSNumber() });
tx.signInput(0, keyPair);

tx.finalizeAllInputs();
const rawTx = tx.extractTransaction().toHex();
```

I modified the code as above as your advice, and I got the following error message.
`Redeem script for input #0 doesn't match the scriptPubKey in the prevout`

**Comment by nbass** [comment]
What am I missing? Can you let me know?

**Comment by nbass** [comment]
My error occured this block:
```javascript
function hasSigs(neededSigs, partialSig, pubkeys) {
  if (!partialSig) return false;
  let sigs;
  if (pubkeys) {
    sigs = pubkeys
      .map(pkey => {
        const pubkey = ecpair_1.fromPublicKey(pkey, { compressed: true })
          .publicKey;
        return partialSig.find(pSig => pSig.pubkey.equals(pubkey));
      })
      .filter(v => !!v);
  } else {
    sigs = partialSig;
  }
  if (sigs.length > neededSigs) throw new Error('Too many signatures');
  return sigs.length === neededSigs;
}
```

`sigs.length` is `1`
`needed.Sigs` is `2`

Is there something I am missing while making a transaction?

**Comment by junderw** [comment]
**Your `getRedeem` function is dangerous.** You have created it to accommodate only one specific type of redeemScript, and if a new type of redeemScript is added later, your code will break and potentially lead to people sending money to a black hole.

I highly recommend talking to the API developers and asking them to offer the redeemScript as a hex blob instead of an ASM string. And if they do, they should follow the ASM spec. numbers between 0 and 16 should use OP_0 - OP_16 and anything above 16 should be hex encoded little-endian bytes (so 17 would be `11` but 16 is `OP_16`, and 260 would be `0401`) a number by itself with string length of 1 is invalid ASM. if the string length was multiple of 2, it would be read as base-16 hex bytes.

-------

You can't finalize a 2-of-2 multisig input with only one signature.

After using `tx.signInput` you should do `tx.toBase64()`, send the encoded PSBT to the second signer, they will use `Psbt.fromBase64`, signInput, then THEY will do finalizeInput and extract the fully valid transaction.

**Comment by nbass** [comment]
@junderw 
I modified my code according to your advice and had them sign my transaction further.
Thank you very much for your support. :)
