### ISSUE TITLE
Allowing both nonWitnessUtxo and witnessUtxos on inputs to allow creating PSBTs for Trezor signing

### ISSUE THREAD

**Issue by KayBeSee** [bitcoinjs/bitcoinjs-lib#1595]
I am trying to send a transaction and sign it with a Trezor One hardware wallet. With the latest firmware, they require including the previous transaction hex to prevent the recent fee attack that could happen on hardware wallets.

I read through [this](https://github.com/bitcoinjs/bitcoinjs-lib/issues/1507) thread that had a similar issue, but this was before the bug was announced.

When I try to add the nonWitnessUtxo I get `Error: Can not add duplicate data to input`

Some other links I found relating to it:
https://blog.trezor.io/details-of-firmware-updates-for-trezor-one-version-1-9-1-and-trezor-model-t-version-2-3-1-1eba8f60f2dd
https://github.com/bitcoin-core/HWI/issues/338

**Comment by junderw** [comment]
remove the witnessUtxo first.

Why are both required? nonWitnessUtxo contains all the information in witnessUtxo.

**Comment by junderw** [comment]
Nowhere does it say on their blog it needs both.

They say to supply nonWitnessUtxo in all cases. So instead of adding witnessUtxo only add nonWitnessUtxo. If some other app is adding it and sending it to your app, tell them to only have one.

**Comment by KayBeSee** [comment]
Hey John, thanks for your prompt response per usual.

I went ahead and removed the witnessUtxo and the witnessScript and replaced them with the nonWitnessUtxo and redeemScript. I then sent the PSBT to the Trezor using the newest version of HWI but kept getting `{"error": "DataError: Transaction must have at least one input", "code": -13}`

I went and commented out [lines 98-100 in the BIP174 package](https://github.com/bitcoinjs/bip174/blob/master/src/lib/utils.js#L98), added the witnessUtxo, witnessScript back and removed the redeemScript, constructed the PSBT and sent it to the Trezor using HWI and it worked flawlessly.

You are right from my understanding, I don't know why I would need both the nonWitnessUtxo in addition to the witnessUtxo and witnessScript since those should both be in the nonWitnessUtxo. From the conversations I have read about it I think there is some sort of detection of Segwit inputs that happens and if it detects that it also checks for nonWitnessUtxo? (basically the they decided to just throw the full tx on the nonWitnessUtxo field to make sure there isn't a massive fee).

Again, I'm not super well versed in what is going on behind the scenes. It seems that because of this recent BIP174 bug, and the patch that Trezor has decided to employ, we need both in order for the Trezor to be able to sign (which sucks).

https://github.com/bitcoin-core/HWI/pull/340
https://github.com/btcpayserver/btcpayserver/issues/1631

**Comment by junderw** [comment]
You should not change witnessScript to redeemScript.

That is your problem.

**Comment by KayBeSee** [comment]
So are you saying I should have the nonWitnessUtxo and a witnessScript?

My current code:
```
psbt.addInput({
          hash: utxo.txid,
          index: utxo.vout,
          sequence: 0xffffffff,
          // witnessUtxo: {
          //   script: Buffer.from(transactionMap.get(utxo.txid).vout[utxo.vout].scriptpubkey, 'hex'),
          //   value: utxo.value
          // },
          nonWitnessUtxo: Buffer.from(prevTxHex, 'hex'),
          // redeemScript: utxo.address.redeem.output,
          witnessScript: Buffer.from(scriptToHex(multisigWitnessScript(utxo.address)), 'hex'),
          bip32Derivation: utxo.address.bip32derivation
        })
```

This works when I'm broadcasting a multisig transaction and sign with a Ledger and Coldcard.

However I am getting:

```
{
"code": -26,
"message": "non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)"
}
```

when I attempt to broadcast the transaction when signed by a Trezor. Very weird. 

From what I read online that is caused by having imprecise input values, but I don't think that's the case since the same transaction is signed and broadcast fine when signed by the other hardware wallets.

Example tx: `0200000000010195a551158853cc55edf94b8d51a5b7aef84a5914e46f8f3e49efef4e6b7d20900000000000ffffffff02a0bb0d0000000000160014880b07e6f256909547c458ab40bbc12edf6aa73fd06301000000000022002028cc913e3df3fe2884468a809cf4f33cf75b13bc00cc7c9aa0b9aa601ab604290400483045022100a60fe96725fb2eecdf4f7247fe7b44b3f1d67abb763748cd70055fcd96db00f502207f15588ca2a2e66dcc636dfa205c2ef264a83a1028039151bfece321302d7d5b01473044022005d94c71bf3ea698d40b2f44795302964b2e50067d28f720931f2900e4f748a2022016aacbf1115e41a8577c9a4f104c38f938ec3c9ca32abc2769ec0435749374160169522102424c63fbad3613a0b3aa2b39cbb5b5baa9284830e964302a988fc97dda27a0f021034ee30903a71f35d112a5f366b780f2d7aa3d658c53710a27630bfc44f8dc22892103b076f139c148a783459f5531811eee1779c158c1923c2b36f818bef79102568a53ae00000000`

Maybe @prusnak can help out? I have hit a wall.
