### ISSUE TITLE
Check Transaction signed

### ISSUE THREAD

**Issue by Droppix** [bitcoinjs/bitcoinjs-lib#1596]
Hi,

Is it possible from a signed transaction (hex) to retrieve (not yet sent) : 
- the blockchain used (BTC/BCH/BTG/LTC/DASH/ZEC)?
- network type ?(MAINNET or TESTNET)

The goal is to verify that the sending of a raw transaction is done on the right blockchain.

Thanks

**Comment by junderw** [comment]
No. There is nothing contained in the serialized transaction format that denotes which chain the transaction belongs to.

The best way to do this is to look at the hash contained in each input and if the transaction the input points to exists on that blockchain then it should be from that chain.

Another way to deal with it is to create some sort of proprietary JSON format with the signed transaction as a single attribute, and include all the info you need.
