### ISSUE TITLE
Example transaction with Psbt class

### ISSUE THREAD

**Issue by PraneshASP** [bitcoinjs/bitcoinjs-lib#1597]
Currently I'm using the TranasctionBuilder class to sign the transaction. But, during execution I'm getting these two deprecation warnings.
```
Deprecation Warning: TransactionBuilder will be removed in the future. (v6.x.x or later) Please use the Psbt class instead. Examples of usage are available in the transactions-psbt.js integration test file on our Github. A high level explanation is available in the psbt.ts and psbt.js files as well.
DEPRECATED: TransactionBuilder sign method arguments will change in v6, please use the TxbSignArg interface
```

Is there any migration guide to move from Transaction Builder class to Psbt class?...also how to sign with the TxbSignArg interface?

Currently I'm creating transactions like this (for p2pkh addresses) :

```
txrefs.forEach( (transaction) => {
          txb.addInput(transaction.tx_hash, transaction.tx_output_n);
        });
        txb.addOutput(dest_address, amount_to_spend);
        for (var j = 0; j < txrefs.length; j++) {
          txb.sign(j, keyPair);
        }
```

How will the implementation with Psbt class and TxbSignArg interface  affect this syntax?

**Comment by educob** [comment]
I hope this helps.

```
    let keyPair = root.derivePath('m/49'/0'/0'/0/0')
    const p2sh = bitcoin.payments.p2sh({
      redeem: bitcoin.payments.p2wpkh({ pubkey: keyPair.publicKey, network }),
      network
    })
    // recipients
    for(let i=0; i<recipients; i++) {
      psbt.addOutput({ address: '2MyA3tn5CD5uK8spYiRTxgm47NG6sYbHZ2B', value:  100 })
    }
      psbt.addInput({ hash: 'xxxx', index: 0,  
        redeemScript: p2sh.redeem.output,
        witnessUtxo: {
          script: p2sh.output, 
          value: 10000,
        }}
      )
    }
    psbt.signAllInputs(keyPair)
    psbt.finalizeAllInputs()
    const tx = psbt.extractTransaction()
```

**Comment by Laziemo** [comment]
@educob Please help me understand this.

Correct me if I am wrong: 
- The redeem script is change, returning to the sender.
- The witness Utxo is the miner fee
- If the above two are true, then we do not have to explicitly add change address to inputs

**Comment by educob** [comment]
No and no.
Miner fee is the different between inputs amount and outputs amount.
Change is given to the sender by explicitly adding an output (change amount = total_utoxs - total_sending - fees)

About the specifics in the redeems script and witness utxo the person to answer that is Jonathan.
You could read Jimmy Song's book Programming Bitcoin which is free in this github.

**Comment by Laziemo** [comment]
Right, change and fee as outputs!
Cheers for the response! Will check out the book! This has been gradually making more sense over the day.

**Comment by Laziemo** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/fixtures/psbt.json

from this file, so far ive concluded the equivalent bitcoin-core cli commands to be
nonWitnessScript = gettransaction -> hex
witnessScript = decoderawtransaction -> vin[n].scriptSig.hex
redeemScript = decoderawtransaction -> txinwitness[n]

**Comment by Laziemo** [comment]
wondering why value is a field for witnessUtxo

**Comment by educob** [comment]
"Right, change and fee as outputs!" Only change is an outout. Fees the amounto spent not send to outputs.

"nonWitnessScript = gettransaction -> hex". Tx is all the information combined not just nonWitnessScript. nonWitnessScript is for non-segwit addresses. Don't use them.

"wondering why value is a field for witnessUtxo". You are providing the unlocking script and the utxo amount. With that information the library can calculate fees, etc.

**Comment by PraneshASP** [comment]
> I hope this helps.
> 
> ```
>     let keyPair = root.derivePath('m/49'/0'/0'/0/0')
>     const p2sh = bitcoin.payments.p2sh({
>       redeem: bitcoin.payments.p2wpkh({ pubkey: keyPair.publicKey, network }),
>       network
>     })
>     // recipients
>     for(let i=0; i<recipients; i++) {
>       psbt.addOutput({ address: addresses[i], value:  values[i] })
>     }
>       psbt.addInput({ hash: 'xxxx', index: 0,  
>         redeemScript: p2sh.redeem.output,
>         witnessUtxo: {
>           script: p2sh.output, 
>           value: 10000,
>         }}
>       )
>     }
>     psbt.signAllInputs(keyPair)
>     psbt.finalizeAllInputs()
>     const tx = psbt.extractTransaction()
> ```

What if the address is  in p2pkh format?

**Comment by educob** [comment]
It won't work. You have to take a look at the examples por p2pkh format.

**Comment by PraneshASP** [comment]
ok. It works :+1: . Thanks !
