### ISSUE TITLE
Can PSBT be used to create P2FKH output?

### ISSUE THREAD

**Issue by mctrivia** [bitcoinjs/bitcoinjs-lib#1598]
Can PSBT be used to create P2FKH output?

I am looking to create colored coin transaction and need to be able to create 1 of 3 P2FKH transaction.

**Comment by junderw** [comment]
Yes. `addOutput` param accepts `script` or `address`... so if you just make the Buffer for the P2FKH and put it in the output you're fine.

**Comment by junderw** [comment]
To make the Buffer just build a Payment object and access its `output` attribute for the Buffer of the outputScript.

**Comment by junderw** [comment]
See this example: Notice the first addOutput uses `script` to pass the `embed.output` (Which is a Buffer)

https://github.com/bitcoinjs/bitcoinjs-lib/blob/c0718a9f7c41f8235e46e2d015ada2c32021e0c7/test/integration/transactions.spec.ts#L162-L191

**Comment by junderw** [comment]
The example is kind of bad. an OP_RETURN (embed) should have `value: 0` and not 1000

**Comment by mctrivia** [comment]
Yes an op_return script would be 0.  P2FKH wouldn't so for a generic example it is actually very good.  Thank you for your help.
