### ISSUE TITLE
[Question] Is virtualSize the method to use to calculate a tx fees?

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1599]
Hi. I am still using the old library to create txs and it's time to upgrade.

I need to calculate the fees the tx should pay according to both the current satoshis/byte and the tx size.

Does the formula would be tx.virtualSize() * feePerByte?

Thanks.

**Comment by junderw** [comment]
Yes. If the Transaction is fully signed (aka ready to broadcast) then the needed fees would be `tx.virtualSize() * feePerByte`
If the transaction is not fully signed, `virtualSize()` will not include the size of the signature data.

Some possible work-arounds to the dilemma of "I can't sign if I don't know the fee":

1. Set a super-inaccurate fee, sign it, then get the virtualSize and re-create and re-sign the tx with the correct fee.
2. Use something like https://gist.github.com/junderw/b43af3253ea5865ed52cb51c200ac19c
