### ISSUE TITLE
Error broadcasting tx with pbst.

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1600]
Hi. I'm trying to translate from transactionBuilder to pbst and I am completely lost.

This is the code (a simplification):

```
this.psbt = new bitcoin.Psbt({ network: this.$bitcoin_network() })
let root = bip32.fromSeed(seed, this.$bitcoin_network())
let keyPair = root.derivePath(this.$bitcoin_path + "/" + utxo.index)
const p2wpkh = bitcoin.payments.p2wpkh( { pubkey: keyPair.publicKey, network: this.$bitcoin_network() } )
this.psbt.addInput({ hash: utxo.utxo_tx, index: utxo.utxo_n,  
              witnessScript: p2wpkh.output,
              witnessUtxo: {
                script: p2wpkh.output, // the script of the output pointed by this input
                value: utxo.value, // the value of the output pointed by this input
              },})
this.psbt.addOutput({ address: recipient.addressTo, value: recipient.satoshis}) // receiver
this.psbt.signInput(counter, keyPair)
this.psbt.finalizeAllInputs()
let tx = this.psbt.extractTransaction()
const tx_hex = tx.toHex()
```

When broadcaste it gives error` rpcError -26 mandatory-script-verify-flag-failed (Operation not valid with the current stack size) (code 16)`
I've seen in the test examples that both witnessScript and redeemScript are populated from payment.redeem but p2wpkh does't have a reddem field so I am completely lost.

Thanks.

And this is the simplest code I have to upgrade to pbst. I also have multisignature and generic scripts to adapt.

**Comment by junderw** [comment]
raw P2WPKH does not need `witnessScript`

Remove the witnessScript line and it should work. Here's an example, notice how inputData only has `hash, index, witnessUtxo`

https://github.com/bitcoinjs/bitcoinjs-lib/blob/7622c58365e09ff26002b56d4a4e7fd13251c949/test/integration/transactions.spec.ts#L315-L347

**Comment by educob** [comment]
Thanks for answering that fast.

I frist tried without the witnessScript, but as it didn't work I tried all the combinations I could.

Your examples are very difficult for me to understand. I have a hard time  trying to understand what createPayment and getInputData do for each tx type.

createPayment, when called from a tx with a "-" seem to ignore one of the two words as payment is not an array and there is no push. 

I'm willing to pay to have my code working. Do you know of anyone who could help me?

Thanks.

**Comment by educob** [comment]
More digging: This the utxo I am trying to spend:

```
    {
      "txid": "fe9fc0ba670f613808f9fcb7d44e702256ce82ccf5986ecc84deab04ad7aa0d5",
      "vout": 1,
      "scriptPubKey": "a914cfd4602ba99bf82f53ab6f5dd4f9e848af14cd1f87",
      "desc": "addr(2NCC8H7VpSXnTLh86CdRSLXe9DhJ99JkEct)#j0wv8fly",
      "amount": 0.25000000,
      "height": 212
    },
```
If I addInput with: `witnessUtxo.script(Buffer.from('a914cfd4602ba99bf82f53ab6f5dd4f9e848af14cd1f87', 'hex'))`

I get this error:` Input #0 has witnessUtxo but non-segwit script: a914cfd4602ba99bf82f53ab6f5dd4f9e848af14cd1f87

Does this make sense?
`

**Comment by junderw** [comment]
I do not understand anything you just said.

Please rephrase.

**Comment by educob** [comment]
I have run "bitcoin-cli decodescript" on the script in unspent.txId returned from regtestUtils.faucetComplex and got:
`"type": "witness_v0_keyhash",`

If I run decodescript on the script in the utxo in my regtest node I get:` "type": "scripthash",`

How do I create utxos with type witness_v0_keyhash?

Thanks.

**Comment by educob** [comment]
One more thing, I have check the utxos scripts I receive in my testnet node and they script are also of type scripthash

**Comment by educob** [comment]
I made it work.

Thanks.

**Comment by sheradoo** [comment]
> I made it work.
> 
> Thanks.

Please I am having the same issue and I have been trying to fix it for months now . Please how did you make it work. Can I have your email so I can send you my code

**Comment by sheradoo** [comment]
@educob please how did you make it work , I am stuck with the same problem for months now . Which solution did you apply
