### ISSUE TITLE
How to create a bip32 node from zpriv key?

### ISSUE THREAD

**Issue by axeldomingues** [bitcoinjs/bitcoinjs-lib#1609]
Hi,

I would like to know how to create bip32 node from zpriv key, all examples I have seen cover zpub to xpub, but I haven't seen any example from zpriv key.

Thank you in advance.

Cheers

**Comment by junderw** [comment]
Take the code example here: https://github.com/bitcoinjs/bitcoinjs-lib/issues/1238#issuecomment-426880691

But change the following:

```js
Buffer.concat([Buffer.from('0488b21e','hex'), data]);
```

Into this:

```js
Buffer.concat([Buffer.from('0488ade4','hex'), data]);
```

Be careful to check that the input starts with zprv before changing, as you don't want to convert zpub into xprv accidentally.

**Comment by junderw** [comment]
(Note: these hex values are taken from `network.ts`

**Comment by axeldomingues** [comment]
Thank you so much. Appreciated.

**Comment by brinzi** [comment]
@junderw I am a bit late to this party but why doesn't the replacement of the version bytes from the key break the checksum when re-encoding?

**Comment by junderw** [comment]
`require('bs58check')` is the key; bs58 is just a base58 encoder/decoder, but bs58check is an encoder/decoder that checks+removes the checksum on decode and adds the new checksum on encode.

**Comment by brinzi** [comment]
@junderw Thanks a lot for explaining. I also took a look into the implementation and it behaves exactly as you said.
