### ISSUE TITLE
PSBT nonWitnessUTXO

### ISSUE THREAD

**Issue by Laziemo** [bitcoinjs/bitcoinjs-lib#1610]
Hello

wagyu - a rust bitcoin lib, generates the following testnet pk:

const pk = "cVpisAGxrGszWhA8X4Tjfaki3zY3T5mtpg9qwPVWeWCGcFq44Rbs"

**Command**
const TESTNET = bitcoin.networks.testnet;
bitcoin.ECPair.fromPrivateKey(Buffer.from(pk),{network: TESTNET});
**Result**
501: Expected Buffer(Length: 32), got Buffer(Length: 52)

**Command**
bitcoin.ECPair.fromWIF(pk,TESTNET);
**Result**
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds

Could someone please help in shedding more light on this private key format and how we can import it?

Cheers.

**Comment by Laziemo** [comment]
Sorry, figured I  had the WIF format all along. 
The range Error is reagarding the addInputs function in a  PSBT. 
I am current

**Comment by junderw** [comment]
You are signing with two keys... does that mean the input is for multisig?

If so, is it P2SH? ---> then you need to pass redeemScript into addInput.
Is it P2WSH? ---> then you need to pass witnessScript into addInput.
Is it P2SH-P2WSH? ---> then you need to pass both redeemScript and witnessScript into addInput.

**Comment by Laziemo** [comment]
yes, it is a multi sig. 
thanks for the response. 
the idea began to make sense when I implemented this requirement with bitcoin-core + watched learnmeabitcoin on youtube (recommended watch).
will have to put off  bitcoin-js lib for later.
