### ISSUE TITLE
outputHasHDKey for change indexes?

### ISSUE THREAD

**Issue by sidhujag** [bitcoinjs/bitcoinjs-lib#1619]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/f1d04cec002f8c4203389c80d259ad33656ad6f1/test/psbt.spec.ts#L795

Shows how to get an output based on Index for HD key using derivations, I guess this would be or receiving address indexes? How to get it for change or receive? Is it analogous to change/recv paths somehow?

I think maybe its the wrong call for what I need to do:

I need to know based on a path or change index(or not) + address index if that path exists as an output in the psbt or tx. This way I can detect if my latest HD change index/receiving address index exists and increment indexes for subsequent transactions in HD one time address use strategy. I can get all outputs and compare addresses but would love if that function already exists similar to outputHasHDKey, maybe outputHasHDIndex (taking in change as bool and index) or outputHasHDPath?

**Comment by sidhujag** [comment]
I found that key management is better suited outside the scope, so I have implemented my own version of it [here](https://github.com/syscoin/syscoinjs-lib/blob/master/utils.js#L373) if anyone is interested

**Comment by junderw** [comment]
The bip32Derivation should have the change info contained in its path string.

**Comment by sidhujag** [comment]
@junderw according to you, what is the correct strategy or pattern you would apply to do this sort of thing? I ended up just calling my backend to fetch all used addresses which gives paths then finding the highest value path for change and receiving, using that. Once memory pool tx is entered that endpoint is updated, but I guess there are better ways without having to resort to an API call for truth.

**Comment by junderw** [comment]
If your wallet has the following two assumptions it is easy:

1. Your wallet is BIP44/49/84 derivation style (all end in `.../{isChange}/{keyIndex}` )
2. All outputs contain bip32Derivation

```js
const match = output.bip32Derivation[0].path.match(/^m\/(?:44|49|84)'\/\d+'\/\d+'\/(\d+)\/\d+$/);
if (!match) throw new Error('This output is not BIP44/49/84')
const isChange = match[1] === '1' // first capture group is '1', we only capture the change layer
```

**Comment by sidhujag** [comment]
@junderw I meant strategy around keeping indexes up-to-date so when new addresses are needed it will always be the "next" unused one. I wonder if you know how wallets generally are doing it because right now as I was saying I reset back to backend (global truth) on every send transaction as well as on new address (if indexes are not initialized yet)

**Comment by junderw** [comment]
In that case, yes, you will need to create logic to manage your tx history to find which change address is next.

That is not something the PSBT class should handle.
