### ISSUE TITLE
Adjust Output value (Change Address)

### ISSUE THREAD

**Issue by Droppix** [bitcoinjs/bitcoinjs-lib#1622]
Hi,

I try to optimize the calculation of the fees, for this, I created my transaction signed and finalized:
- 1 input + 2 outputs (Destination + ChangeAddress)

Now, I was able to get the virtualSize from transaction (psbt.extractionTransaction()), and make a more accurate recalculation of the fees (feeRate * virtualSize), and I would like to adjust the "output" value of the changeAddress.

How is it possible to proceed, do I have to completely rebuild the transaction or is it possible to just only change the value of output (ChangeAddress) ?

Thanks

**Comment by junderw** [comment]
You should re-build the psbt.
