### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Droppix** [bitcoinjs/bitcoinjs-lib#1623]
Hello,

Is it possible from an address and master keys (public/private -> xpub/xpriv) :

1/ Check if that the address come (belongs to) from the master?
Public Key: tpubDCXxxxx...
Private Key: tprivXxxxxx...
address: musN5XxyaojLZeAvCrmZzDfJqfuPsjiFLx / path: m/44'/1'/0'/0/0

2/ From the address get the path? (function("musN5XxyaojLZeAvCrmZzDfJqfuPsjiFLx") -> "m/44'/1'/0'/0/0" ) 

Thanks

**Comment by junderw** [comment]
1. If you have the address, path, and tpub/tpriv you can verify the address is derivable from the tpub/tpriv.
2. Not realistically. You would need to brute force. Though the number of commonly used paths is smaller, the number of total possible paths is larger than a private key... so it is not practical... you could make a function to check the 10 most common derivation types for 100 addresses each (etc.)... but not "find if this address is any path"...
