### ISSUE TITLE
Outdated secp256k1

### ISSUE THREAD

**Issue by dignifiedquire** [bitcoinjs/bitcoinjs-lib#1624]
The commit that tiny-secp256k1 pulls in on `master` is currently 3 years old, any reason not to update this to a more recent version? For example https://www.npmjs.com/package/secp256k1 has a much newer version and fallbacks for the brower as well

**Comment by motorina0** [comment]
- `tiny-secp256k1` updated to latest (v.1.1.5) in PR https://github.com/bitcoinjs/bitcoinjs-lib/pull/1656
- issue can be closed once PR is merged

**Comment by junderw** [comment]
I think he's talking about libsecp256k1

it's not in 1.1.5, but it's merged to master.

**Comment by junderw** [comment]
I have published 1.1.6 which uses the up-to-date secp256k1.
