### ISSUE TITLE
Urgent help to migrate to Bitcoinjs-lib

### ISSUE THREAD

**Issue by bush4u** [bitcoinjs/bitcoinjs-lib#1626]
This is a call for help.
I am desperately trying to move away from bitcore-lib and bitcore-explorer.

I have gone through the bitcoinjs-lib documentation and honestly, they seem too technical for me.

The operation i perform on bitcore-lib/bitcore-explorer are

- Getting unspent transaction (with bitcore-explorer)
- Sign and publish a transaction (with single inputs) to a single beneficiary address on the network (bitcore-lib bitcore.Transaction(), and bitcore-explorer broadcast() )
- Sign and publish a transaction (with multiple inputs)  to a single beneficiary address on the network  (bitcore-lib bitcore.Transaction())
- Sign and publish a transaction (with single inputs) to a multiple beneficiary addresses on the network (bitcore-lib bitcore.Transaction())
- Sign and publish a transaction (with multiple inputs)  to a multiple beneficiary addresses on the network  (bitcore-lib bitcore.Transaction())

Any help i can get right now would save my day and my job.

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/c0718a9f7c41f8235e46e2d015ada2c32021e0c7/test/integration/transactions.spec.ts

This is where you'll find examples on how to do what you want.

regtestUtils is a library we use for regtest mode. It can't be used with mainnet.

but really all you need to do is find some sort of API (bitcore used insight) and send the signed tx to their broadcast API.

---

I can answer any specific questions you have about the API. Broad questions can be answered by looking at the tests.
