### ISSUE TITLE
react native wallet and security best practices

### ISSUE THREAD

**Issue by vesparny** [bitcoinjs/bitcoinjs-lib#1628]
Hi, first of all thanks a lot for this amazing library.
I am building a wallet with react native and I am wondering what is the best way to integrate bitcoinjs-lib in order to have reliable unit and e2e test suites.

### approach 1
I have started using the approach explained in [this gist](https://gist.github.com/coreyphillips/4d45160fed016417a5f583f179c2cbdb) which relies on `rn-nodeify` to shim node native modules and `react-native-randombytes`.

It works well but I see 2 main issues with this approach:

1. it feels a bit hacky and I have the feeling I am not exactly sure which nested dependencies are actually being used
2. even though I run tests using jest [with react native presets](https://jestjs.io/docs/en/tutorial-react-native), I am actually loading libraries and nested dependencies supposed to work in a browser environment + some react native specific modules for random bytes generation. This leaves me a little bit uncertain about my tests.

### approach 2
After some days of work I realized all my bitcoin related logic is basically based on top of few packages being:
```
"bignumber.js": "9.0.1",
"bip39": "3.0.2",
"bitcoinjs-lib": "5.2.0",
"bitcoinjs-message": "2.1.3",
"bs58check": "2.1.2"
```
...I extracted my bitcoin related logic to its own npm package bundled with `browserify` with the following script

```js
const browserify = require('browserify')
const fs = require('fs')

browserify(['./src/index.js'], {
  builtins: [
    'buffer',
    '_process',
    'events',
    'util',
    'stream',
    'timers',
    'string_decoder'
  ],
  standalone: 'mylib'
})
  .bundle()
  .pipe(fs.createWriteStream('/dist/index.js'))
```
...and started consuming the library as my react native app direct dependency.

It seems to work pretty well and I see few benefits with this approach:

1. I ALWAYS exactly know what libraries my app is loading and leveraging
2. I can write unit tests for my lib using ava or tape and run them against both browser and node environments as well as run them directly against the browserify build (just to be sure)
3. I can simply write integration and e2e test on my react native in order to make sure what tested in my lib tests, also works in the app 
4. my react native doesn't need to use "hacky" solutions which rewrites package.json files in my deps tree
5. I do not need `react-native-randombytes` or any other library which attempt to mimic the node `crypto` module

I still have some doubts though:

1. the rng implementation used is the one in here https://github.com/crypto-browserify/randombytes/blob/f18ded32b209f0d4c637608a11ae042ae96b4c2e/browser.js#L19. Is it ok?
2. I still need to find a way to instruct browserify to use specific package versions for `builtins` for more control 

What do you think of the second approach? Is it something that makes sense or I'd be better to stick with option 1 which seems the one being suggested in few other threads?

Thanks

**Comment by junderw** [comment]
I like 2. Then of course I'm biased towards using browserify.

as for the rng question, it should work assuming react mimics the browser's crypto API

**Comment by vesparny** [comment]
@junderw thanks for the quick feedback.
I like 2 very much as it feels more "under control".
As per the rng, I can confirm it's working, I just do not know how acceptable is the randomness

**Comment by vesparny** [comment]
@junderw 

I managed it:

```js
const browserify = require('browserify')
const fs = require('fs')

// https://github.com/browserify/browserify/blob/5113ea39833a0d6eed3ae3dadddb770efb0cf364/lib/builtins.js
// https://github.com/browserify/browserify/blob/5113ea39833a0d6eed3ae3dadddb770efb0cf364/lib/builtins.js
browserify('./src/index.js', {
  builtins: {
    buffer: require.resolve('buffer/'),
    _process: require.resolve('process/browser'),
    events: require.resolve('events/'),
    util: require.resolve('util/util.js'),
    stream: require.resolve('stream-browserify'),
    timers: require.resolve('timers-browserify'),
    string_decoder: require.resolve('string_decoder/')
  },
  standalone: 'planb'
})
  .bundle()
  .pipe(fs.createWriteStream('dist/index.js'))
```
