### ISSUE TITLE
p2sh create transaction missing inputs

### ISSUE THREAD

**Issue by VolckaertAchiel** [bitcoinjs/bitcoinjs-lib#1629]
Hi
When i try to create a transaction with the builder(yes i need the builder, since i will need other coins asswell, but most of them dont support pbst yet) the broadcast says they are missing an input?

```js
const bitcoin = require("bitcoinjs-lib");


let NETWORK = bitcoin.networks.testnet; 
let txb = new bitcoin.TransactionBuilder(NETWORK);

//get unspent output details
let txid = "5ec8e57d487efea757eb28d7c936c05d31fbd19844dffdc658a4f0a9f2ab59ea"; //transaction id
let outn = 1;  // n out

//add input
txb.addInput(txid, outn);
// txb.addInput(, );

//add output
txb.addOutput("mkHS9ne12qx9pS9VojpwU5xtRd4T7X7ZUt",20000); //first argument is address that will receive the funds, the second is the value to send in satoshis after deducting the mining fees. In this example there are 5000 satoshis in mining fees (40000-35000=5000)
console.log(txb.buildIncomplete().toHex())
```
signed: 
0200000001ea59abf2a9f0a458c6fddf4498d1fb315dc036c9d728eb57a7fe7e487de5c85e010000006b483045022100c33d47b0e4347d16191ec171b4034761cfa0ae3d4626cdd1f2bcedeb47952dab022051dbbc11e5849d81eb2922bd39bbcc7e7fe4f2669b87d51af486d4c78e24c8120121027a264340edbf21fd3c7587461f39514bd002986c18077b96afc1f76cf85088cbffffffff01204e0000000000001976a914344a0f48ca150ec2b903817660b9b68b13a6702688ac00000000

**Comment by junderw** [comment]
> but most of them dont support pbst yet

PSBT has nothing to do with consensus, it is ONLY a method for storing and serializing input and output information. All bitcoin related coins support PSBT. If anyone told you otherwise, they are wrong.

> broadcast says they are missing an input

"Missing Input" error means "the output referenced by one of your inputs is already spent, and you are trying to double spend it."

Use a different output.

**Comment by VolckaertAchiel** [comment]
@junderw can you point me to an example for p2sh transactions?

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/533d6c2e6d0aa4111f7948b1c12003cf6ef83137/test/integration/transactions.spec.ts#L193

The other examples in the same file will give you an idea as to how PSBT works in general.

Do not copy paste code from tests into your app. Use the tests as a learning tool.

helper functions are there to hide away code not related to understanding Psbt.

If you don't understand payments etc. look at their tests.
