### ISSUE TITLE
fees stays 0, whatever i change

### ISSUE THREAD

**Issue by VolckaertAchiel** [bitcoinjs/bitcoinjs-lib#1630]
with the code below(which seem to be widely used) it creates a transaction, but the fee is 0 while there is a fee calculated.
  
```
import * as grjs from 'groestlcoinjs-lib';
const { transactions, balance } = await groestlcoinExternalApiService.getGroestlcoinHistory(from);

  const tx = new grjs.TransactionBuilder(testnet);

  console.log(from)
  console.log(to)
  console.log(transactions)
  console.log(balance)

  const amountWeHave = transactions[0].value * 100000000;
  const amountToSend = (amount * 100000000);
  const transactionFee = fee * 100000000;
  const amountToKeep = amountWeHave - amountToSend - transactionFee;
  console.log(amountWeHave)
  console.log(amountToSend)
  console.log(transactionFee)
  console.log(amountToKeep)
  tx.addInput(transactions[0].hash, 0);
  tx.addOutput(to, amountToSend);
  tx.addOutput(from, amountToKeep);

  return tx.buildIncomplete().toHex();
```
output:

```
mr9L1pWBwkSRY6ptCWQSWY9oJEHZXW4nA7
mz8aVCEGVZGbjc7xGVEMEVNF427Awd7k19
[
  {
    value: 23.99539169,
    timeStamp: '2020-10-08T10:54:28Z',
    hash: '2f2cffae36ea14496914bb209334fe00c80efb85dfbbf8abebc4f9559d7ec88c'
  },
  {
    value: 10.37729567,
    timeStamp: '2020-10-08T10:54:28Z',
    hash: 'd34aa16eed47c6c188ee4218fbac5871411dc017975524f650668db8c30cfa97'
  }
]
3437268736
2399539169
2399000000
20000
519169
```

transaction:

`02000000018cc87e9d55f9c4ebabf8bbdf85fb0ec800fe349320bb14694914ea36aeff2c2f0000000000ffffffff02c0d5fd8e000000001976a914cc2f08ce0c07a5f77ca73142162cae09c614608b88ac01ec0700000000001976a91474925d0d9ae1a7e68521fc515de5bfd08635d8c788ac00000000`

**Comment by junderw** [comment]
Where are you getting the variable `fee` in the line `const transactionFee = fee * 100000000;` ???

I can't see it being created anywhere, and uninitialized variable in context of math operations is treated as 0.

**Comment by junderw** [comment]
Looks like `null * 1000` is 0, but `undefined * 1000` is `NaN`...

So maybe you are passing `null` to the `fee` variable?

**Comment by VolckaertAchiel** [comment]
@junderw i have a const in my controller   const fee = 0.0002; that is passed through

**Comment by junderw** [comment]
You are using `0` for the input index, but according to this block explorer, your output is `1` (the second output)
![Screenshot_20201008_212034](https://user-images.githubusercontent.com/11246316/95457687-3699b500-09ac-11eb-8fe5-676807698f07.png)

**Comment by junderw** [comment]
Should be `tx.addInput(transactions[0].hash, 1);` instead.

**Comment by VolckaertAchiel** [comment]
`02000000018cc87e9d55f9c4ebabf8bbdf85fb0ec800fe349320bb14694914ea36aeff2c2f0100000000ffffffff02c0d5fd8e000000001976a914cc2f08ce0c07a5f77ca73142162cae09c614608b88ac01ec0700000000001976a91474925d0d9ae1a7e68521fc515de5bfd08635d8c788ac00000000`
 i saw, thats the tx, still empty fee

**Comment by junderw** [comment]
I see a fee...... why can't you see the fee?

**Comment by VolckaertAchiel** [comment]
how do you check?

**Comment by junderw** [comment]
How did YOU check? Where are you seeing 0?

**Comment by VolckaertAchiel** [comment]
https://live.blockcypher.com/bcy/decodetx/

```
{
    "addresses": [
        "mz8aVCEGVZGbjc7xGVEMEVNF427Awywa8h",
        "mr9L1pWBwkSRY6ptCWQSWY9oJEHZYgM42d"
    ],
    "block_height": -1,
    "block_index": -1,
    "confirmations": 0,
    "double_spend": false,
    "fees": 0,
    "hash": "def9b35b01a1939e129e71360e9ef19c717ba00c6c527d7c14f958d0354ca3c0",
    "inputs": [
        {
            "age": 0,
            "output_index": 1,
            "prev_hash": "2f2cffae36ea14496914bb209334fe00c80efb85dfbbf8abebc4f9559d7ec88c",
            "script_type": "empty",
            "sequence": 4294967295
        }
    ],
    "outputs": [
        {
            "addresses": [
                "mz8aVCEGVZGbjc7xGVEMEVNF427Awywa8h"
            ],
            "script": "76a914cc2f08ce0c07a5f77ca73142162cae09c614608b88ac",
            "script_type": "pay-to-pubkey-hash",
            "value": 2399000000
        },
        {
            "addresses": [
                "mr9L1pWBwkSRY6ptCWQSWY9oJEHZYgM42d"
            ],
            "script": "76a91474925d0d9ae1a7e68521fc515de5bfd08635d8c788ac",
            "script_type": "pay-to-pubkey-hash",
            "value": 519169
        }
    ],
    "preference": "low",
    "received": "2020-10-08T12:28:38.163685384Z",
    "relayed_by": "3.92.204.192",
    "size": 119,
    "total": 2399519169,
    "ver": 2,
    "vin_sz": 1,
    "vout_sz": 2
}
```

**Comment by junderw** [comment]
Your transaction is on GRS-TEST... that is for the BCY testnet... of course it won't know how much coins the input is worth, since the input tx doesn't exist on BCY testnet.

Decode using a GRS-TEST node.

But since fee is just `sum of inputs - sum of outputs` you already know your fee is there. Don't worry.

**Comment by VolckaertAchiel** [comment]
{"result":null,"error":{"code":-8,"message":"Second argument must be numeric (maxfeerate) and no longer supports a boolean. To allow a transaction with high fees, set maxfeerate to 0."},"id":1}

this is what i get when i try broadcasting

**Comment by junderw** [comment]
That error has nothing to do with the transaction................... you called the API incorrectly.
