### ISSUE TITLE
Is there a sinrawtransactionwithkey function available in bitcoinjs?

### ISSUE THREAD

**Issue by neocarmack** [bitcoinjs/bitcoinjs-lib#1634]
Bitcoin core provides the function sinrawtransactionwithkey, which accepts a private key to sign the input hexstring:

https://developer.bitcoin.org/reference/rpc/signrawtransactionwithkey.html

I searched bitcoinjs, could not find a similar function to do so. I need a sinrawtransactionwithkey in javascript. Could anyone please give me some info about this? 

Gratitude

**Comment by junderw** [comment]
bitcoinjs is not a full node.

it's a toolbox from which you could make your own signrawtransactionwithkey if you wanted.
