### ISSUE TITLE
How to create Bech32 addresses with the Electrum Wallet zpub

### ISSUE THREAD

**Issue by mumi** [bitcoinjs/bitcoinjs-lib#1636]
Hey, I want to generate Bech32 (P2WPKH) addresses (every time a unique address) on a Node.js webserver with the zpub key from electrum. I already read into https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/bip32.spec.ts but didn't understand it very well. I want to see all transactions, that are made on addresses from my zpub key, in my Elecetrum wallet.

**Comment by junderw** [comment]
The search function brings up many examples.

https://github.com/bitcoinjs/bitcoinjs-lib/issues/1238#issuecomment-426880691

**Comment by mumi** [comment]
[https://github.com/bitcoinjs/bitcoinjs-lib/issues/966#issuecomment-353763100](url)

Already tried this, but HDNode was removed and if i replace bjs.HDNode with bjs.bip32, error message: Cannot read property 'getPublicKeyBuffer' of undefined
