### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Solidity2026** [bitcoinjs/bitcoinjs-lib#1638]
I want to show real time Blockchain data in my website

**Comment by itsMikeLowrey** [comment]
I think that your goal is outside of the scope of this library. This library helps decode and process bitcoin transactions in JavaScript. If I understand you question correctly, you would first need to get an api such as [blockcypher](https://www.blockcypher.com/dev/bitcoin/) to get the blockchain to your website. Then you would display the data how you wish on your website. I hope I understood your goals correctly.
