### ISSUE TITLE
signInputHD() cant sign input if I have only account level Xprv

### ISSUE THREAD

**Issue by Overtorment** [bitcoinjs/bitcoinjs-lib#1643]
Im working on multisig compatibility with Electrum.  Everything was fine, I used that code to sign inputs with mnemonic seeds I have:

```
            const hdRoot = bitcoin.bip32.fromSeed(seed);
            psbt.signInputHD(cc, hdRoot);
```

Im aware that we are providing root HD node here, so internals see the PSBT input, path, fingerprint, match it all together and do the signature.

Then I stumbled upon Electrum desktop which in some cases throws away mnemonic seed and keeps only Xpub & Xprv in backup, which are account level (fingerprint is present as well). 
So I hacked some code to do the signing:

```
            if (MultisigHDWallet.isXprvString(cosigner)) {
              hdRoot = bitcoin.bip32.fromBase58( MultisigHDWallet.convertMultisigXprvToRegularXprv(cosigner) );
            }
            psbt.signInputHD(cc, hdRoot);
```

Which throws

    `Need one bip32Derivation masterFingerprint to match the HDSigner fingerprint`

And I dont know how to let `signInputHD` know that the hd node I have is account level, but I do have a fingeprint and path, everything is correct and I know what Im doing.

**Comment by junderw** [comment]
One possible thing we can do is:

1. Look at the depth and index encoded in the xprv, find the depth, and check that the index matches. If the index at depth doesn't match, skip.
2. Derive the remainder of the path only, get the publicKey
3. Match the publicKey, if the publicKey doesn't match, skip.

However, this is extremely expensive... if you have 400 inputs of a 2-of-15 multisig with 15 bip32Derivations in each input with a derivation path that is 103 depths deep, and your xprv is the 3rd depth, and we look at the worst case.

```
masterFingerPrint check method = (1 bs58check decode op + 1 compare Buffer op) x 400 x 15
above "new" method = (1 bscheck decode op x 400 x 15) + (derivation op x 100 x 400 x 15) + (ECmult op x 400 x 15)
```

ie:

```
pubkey: 03de8a543bba0ab8c0eddd5c7d7eadb31a5d093387762096ee7441d04eea1c1dab
path: f7e6ce72/84'/0'/0'/0/0

xprv @ m/84'/0'/0'
xprv9y6gMzqWBWEyzBr5pWaj5DwiHFVxWhXRjP8wb6btuYp1Muctd39AN1djHfdJ74ZpbVRmpNF4tC7YQh8RVvPq5VNJibFsgFeNXBveBrM7FYH

xprv-encoded depth: 3
xprv-encoded index: 0x80000000 (0 hardened)
```

I could look at the 3rd depth of the path (in the above case, the last `0'`) and skip any path that isn't 0'... then I can derive `0/0` (the remainder of the path) causing 2 derivation operations. Then generate the publicKey, one ECmult operation, then compare the pubkey with the pubkey in the bip32Derivation, skip if not matching. If matches, sign.

But the question remains:

How would you get the masterFingerprint if you don't have access to the master xprv? It is required by BIP174.

**Comment by junderw** [comment]
Not to mention the above scenario could contain a path `ffffffff/57878/435'/0'/0/0` which any human looking at it would say "that's invalid, this PSBT is phishy, I don't wanna sign it" but our above method would ignore the weirdness and have no way of verifying it.

**Comment by Overtorment** [comment]
ok, what if I wont use `signInputHD()`, and use plain old `psbt.signInput(cc, keyPair)` ?
ofcourse I would need to manually get correct keypair from xpriv on hand.

**Comment by junderw** [comment]
That is possible.

I tried to get a non-root xprv from electrum but I can't find any.

The only secret data it lets me export is a mnemonic seed.

**Comment by Overtorment** [comment]
FYI, I did exactly what I proposed and I think it works (will do more testing).
if `signInputHD()` fails I do some manual matching and use `signInput()`.
the source of PSBTs with bogus fingerprints and paths is Electrum desktop

https://github.com/BlueWallet/BlueWallet/pull/2466
