### ISSUE TITLE
Cant add ltc segwit output

### ISSUE THREAD

**Issue by harusurv** [bitcoinjs/bitcoinjs-lib#1644]
I can't use segwit ltc outputs, is there any plan on supporting it?

**Comment by junderw** [comment]
segwit LTC outputs are supported.

Please show your code, show your errors etc.

**Comment by junderw** [comment]
Examples:
https://github.com/bitcoinjs/bitcoinjs-lib/blob/533d6c2e6d0aa4111f7948b1c12003cf6ef83137/test/integration/transactions.spec.ts

Just replace the `regtest` network object with the following object:

```js
const litecoin = require('coininfo').litecoin.main.toBitcoinJS()
```

**Comment by harusurv** [comment]
You are right, i used that object as network and it worked perfectly. Thank you so much!
