### ISSUE TITLE
double_spend functionality

### ISSUE THREAD

**Issue by joadr** [bitcoinjs/bitcoinjs-lib#1645]
Hello, 
The service that gave us the recommended fees for BTC started throwing us a fee of 2 sat/byte. The thing is a lot of transactions got stuck in mempool. As the library by default sends nSequnce to MAX, I'm unable to do some replace by fee, and sending a new one with bigger fees results in the block rejecting it with `258: txn-mempool-conflict. Code:-26`. I'm thinking of trying to double spend. I found out that when decoding the transaction with blockcypher it shows that there is a parameter of double_spend set to false. Also found out that bitcorelib [has such thing](https://bitcoinlib.readthedocs.io/en/latest/source/bitcoinlib.transactions.html#bitcoinlib.transactions.Input), but I've not found such a thing in this library. Any idea how could I achieve this?

Thanks in advance

**Comment by junderw** [comment]
https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki#spending-wallet-policy

As you can see if you read the Spending Wallet policy, RBF is more complicated than flipping a switch.

Sure, I could add a boolean that makes sure all input sequences are 0xfffffffd or less.

But then the other policies like "don't spend a replaceable tx as non-replacable" etc. could be ignored by abstraction.

Please read the BIP.
