### ISSUE TITLE
Export witnessStackToScriptWitness

### ISSUE THREAD

**Issue by monokh** [bitcoinjs/bitcoinjs-lib#1648]
For PSBT signing, the [`witnessStackToScriptWitness`](https://github.com/bitcoinjs/bitcoinjs-lib/blob/f67aab371c1d47684b3c211643a39e8e0295b306/ts_src/psbt.ts#L1418) and [`witnessStackToScriptWitness`](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/csv.spec.ts#L477) functions are useful for apps trying to spend from custom scripts.

As it is not exported, it is being duplicated for the users of `bitcoinjs-lib`. Is it a good idea to export these?

**Comment by sisou** [comment]
We are signing HTLC redeem transaction at Nimiq, and we are duplicating these methods in our code. If they can be exported, that would be great!

**Comment by jasonandjay** [comment]
More discussion welcome in #1862, close this issue
