### ISSUE TITLE
fee is higher than output

### ISSUE THREAD

**Issue by amirh3n** [bitcoinjs/bitcoinjs-lib#1649]
I create a transaction with 1 input and 2 output, the input UTXO amount is 75720 satoshi and I want to spent 73000. The transaction `virtualSize()` is 225 and get the fee rate from [bitcoinfees.earn.com](https://bitcoinfees.earn.com/api) which is around 380 so `225*380=85500` the result is even higher than my unspent value. what did i do wrong?

**Comment by junderw** [comment]
The highest fee rate you can pay is 12 satoshis per byte.

Currently there's about 7-8 blocks worth of transactions waiting at 12 and above, so adding a 12 sat/byte fee will take some time to get in a block.

If you want to pay 380 satoshis per byte you need to add another input with a UTXO of 82780 satoshis or more.

Basically, what happened was:

"I have $13, I want to spend $10 but the fee I want to add on to it is $15, so I need $25 but I don't have it... so I can go find another $12 and add it to the fee, or I can pay a $3 fee and wait longer."

**Comment by junderw** [comment]
Also, 380 is extremely high. You are almost guaranteed to get into the next block, but it's over-shooting that by a huge margin (just to be safe)

Right now it's clearing around 60... so if you add a fee rate of 60, you might get in the next few blocks, or it might take a few hours.

A fee rate of 12 might take a few hours or it might take a few days, not sure.

**Comment by amirh3n** [comment]
@junderw Thanks, How Can I calculate to reach the number `60`  from the [bitcoin fee API](https://bitcoinfees.earn.com/api/v1/fees/recommended)?

**Comment by junderw** [comment]
you can't.

Run a node and watch your mempool to see the fees of the transactions waiting for a block.

Or use the estimatesmartfee RPC call to your node.
