### ISSUE TITLE
Created basic UI using bitcoinjs-lib (PSBT, Transaction, Payment)

### ISSUE THREAD

**Issue by motorina0** [bitcoinjs/bitcoinjs-lib#1654]
I have created a small web app that uses `bitcoinjs-lib`.
You can find it here: https://bitcoincoretech.github.io/apps/bitcoinjs-ui/index.html
Github Repo [here](https://github.com/bitcoincoretech/bitcoinjs-ui)

It covers _most_ of the `psbt.ts`, `transaction.ts` and `p2*.ts` APIs.

I have also created a wiki with some [UI Samples](https://github.com/bitcoincoretech/bitcoinjs-ui/blob/main/README.md) using the `bitcoinjs-lib` test data.
For the [PSBT Wiki](https://github.com/bitcoincoretech/bitcoinjs-ui/wiki/PSBT-Tests) I have used one of the **BIP 174 Test Vectors**.

If anyone has time to check the app, it would be great!
Any kind of feedback is welcome, as I plan to improve the UI in the future.

**Notes**:
  - this is an alpha version
  - it can also be used as a standalone html file, no need for build process or a local server
    - clone the repo and open the `index.html` file
  - I'm not sure if an issue is the right place to post this message

**Comment by motorina0** [comment]
I have also added a video tutorial, click for full version.

[![psbt-test-vector-30-seconds](https://user-images.githubusercontent.com/2951406/103563117-e0fa7900-4ec4-11eb-979f-d09013df5283.gif)](https://youtu.be/I4o5b9IhWEA)

**Comment by AndreasGassmann** [comment]
I just wanted to say thanks for this amazing tool. It helped me a lot to understand how PSBTs work and debug the PSBT implementation in our wallet. 🎉

**Comment by junderw** [comment]
You should put a link in the README

**Comment by motorina0** [comment]
Thanks! 

I see 3 places where the link could be inserted. Please let me know which one you prefer:
  1. on top, just above the "Released under the terms of..." (most visible)
  2. on the **Documentation** section (visble, but the user has to scroll)
  3. on the **Browser** section (less visible) 

**Suggested text**:
You can find a [Web UI](https://bitcoincore.tech/apps/bitcoinjs-ui/index.html) that covers most of the `psbt.ts`, `transaction.ts` and `p2*.ts` APIs [here](https://bitcoincore.tech/apps/bitcoinjs-ui/index.html).

**Comment by junderw** [comment]
2, Documentation seems best

**Comment by motorina0** [comment]
> I just wanted to say thanks for this amazing tool. It helped me a lot to understand how PSBTs work and debug the PSBT implementation in our wallet. 🎉

@AndreasGassmann thanks for the positive feedback!
If you find bugs or have any sugestions for features please [submit an issue on the app repo](https://github.com/bitcoincoretech/bitcoinjs-ui/issues)

**Comment by motorina0** [comment]
PR created: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1669

**Comment by motorina0** [comment]
I have added annotation support for Transactions. You can add notes inputs, outputs and scripts and share them with others, or reference them from a tutorial/documentation/blog.

Sample [here](https://bitcoincore.tech/apps/bitcoinjs-ui/index.html?&tx_note=Sample%20of%20a%20Commitment%20Transaction%20used%20in%20Lightning%20Network.&tx_input_0_note=Spend%20from%20the%20Funding%20Transaction&tx_input_0_script_note=This%20script%20unlocks%20a%20P2WSH.%20Click%20the%20%27Edit%27%20button%20and%20manually%20set%20the%20type%20to%20P2WSH%20in%20order%20to%20view%20the%202-of-2%20multisig%20script.&tx_output_0_note=[To%20Local]%20Output%20sends%20funds%20back%20to%20the%20owner%20(Alice)%20of%20this%20commitment%20transaction%20and%20thus%20must%20be%20timelocked%20using%20`OP_CHECKSEQUENCEVERIFY`.%20It%20can%20be%20claimed,%20without%20delay,%20by%20the%20other%20party%20if%20they%20know%20the%20revocation%20private%20key.&tx_output_0_script_note=This%20is%20the%20%22naked%22%20unwrapped%20Revocable%20Sequence%20Maturity%20Contract%20(RSMC).%20In%20order%20to%20see%20the%20final%20form,%20click%20the%20%27Edit%27%20button%20and%20%27Wrap%20in%20P2WSH%27.&tx_output_1_note=[To%20Remote]%20Output%20sends%20funds%20to%20the%20other%20party.%20If%20`option_anchor_outputs`%20applies%20to%20the%20commitment%20transaction,%20the%20`to_remote`%20output%20is%20encumbered%20by%20a%20one%20block%20csv%20lock.%20Otherwise,%20this%20output%20is%20a%20simple%20P2WPKH%20to%20remotepubkey.&tx_output_1_script_note=This%20is%20the%20%22naked%22%20unwrapped%20Contract%20that%20pays%20Bob%20with%20no%20restrictions.%20In%20order%20to%20see%20the%20final%20form,%20click%20the%20%27Edit%27%20button%20and%20%27Wrap%20in%20P2WSH%27.&tx_output_2_note=[Local%20Anchor]%20Output%20can%20be%20spent%20by%20the%20local%20node%20to%20provide%20incentive%20to%20mine%20the%20transaction,%20using%20child-pays-for-parent.&tx_output_3_note=[Remote%20Anchor]%20Output%20can%20be%20spent%20by%20the%20remote%20node%20to%20provide%20incentive%20to%20mine%20the%20transaction,%20using%20child-pays-for-parent.&tx_hex=02000000000101bef67e4e2fb9ddeeb3461973cd4c62abb35050b1add772995b820b584a4884890000000000ffffffff04e48d6a00000000004d63210212a140cd0c6539d07cd08dfe09984dec3251ea808b892efeac3ede9402bf2b1967029000b2752103fd5960528dc152014952efdb702a88f71e3c1653b2314431701ec77e57fde83c68acc0c62d00000000002521032c0b7cf95324a07d05398b240174dc0c2be444d96b159aa6c7f7b1e668680991ad51b24a010000000000002200202b1b5854183c12d3316565972c4668929d314d81c5dcdbb21cb45fe8a9a8114f4a01000000000000220020e9e86e4823faa62e222ebc858a226636856158f07e69898da3b0d1af0ddb39940340ca3e2b815f7bf548fa59a79002d8093ee786b38803704130a589f749c33552145a36440a0d7d407dee948c85c2f20e4892479075cf2f166e94c2e6309907971440f89034eba16b2be0e5581f750a0a6309192b75cce0f202f0ee2b4ec0cc39485076c65dc507fe42276152b7a3d90e961e678adbe966e916ecfe85e64d430e75f3475221023da092f6980e58d2c037173180e9a465476026ee50f96695963e8efe436f54eb21030e9f7b623d2ccc7c9bd44d66d5ce21ce504c0acf6385a132cec6d3c39fa711c152ae00000000)

Wiki Page: https://github.com/bitcoincoretech/bitcoinjs-ui/wiki/Annotations
