### ISSUE TITLE
Unable to serialize and deserialize PSBT 

### ISSUE THREAD

**Issue by tharunprabhakaran** [bitcoinjs/bitcoinjs-lib#1658]
Hi, I am trying to serialise a PSBT object using PSBT class toHex()  function, which generates a hex string. But When I try to deserialise, the deserialised PSBT is empty.

`var psbt = bitcoin.Psbt`
`var  p2 = new psbt({ network: testnet })`
`p2.addInput({`
 `   hash: "593f6fbcf2e431ec81fe0933da9fa798e917edce4cd51eb11e8f0fcf0bf050b7",`
 `   index: 0,`
 `   redeemScript: Buffer.from("53210349580e997e1d72de1477e977b30666244aa4d0a88e304d534f2e95a70e34302021034fa14346884d5be836dabf4e1f471159d6ad91497bbb3a3e32d5366faee41ca021028d86a754c25593e5fb4a894ee370628680a15e13b13cf0c87d1a35e0876298ed21038ccba599433b9db259fd3389cb9d6964b1d2de81944535d849a60c8f481940f054ae", "hex"),`
  `nonWitnessUtxo: Buffer.from("020000000001013875bfb56bc827409addef8409633317b0ebc7e04d01e5d2a480d29bdf1b357c00000000171600146c87d59cbe80a92baee4a8980158c4f3cfdad89affffffff02204e00000000000017a914cae2b7c201577076c94e77c1bc6fe801f3ccb3b987f82401000000000017a914a1d0abf0095285ad3a8f701ddda5ece44cb1760e870247304402248a478f89d063f62a9cd7fcb42a726f974db61f15a983c7de8a740b223ea4ff702207e3f1340db833b2d1357ca1530bfcc2ba6d226aa6d3ec8c35c4362e7d3ff01f5012102fbccce1ac521ac243fdb1b6850f546510979f38dd0266c10908239a1f4d7a82000000000", "hex")`
`})`

`p2.addOutput({`
 `  address: "2ND1cF83N6CscRw379i1xJ5Xcp4EkfAAdrK",`
  ` value: parseInt(0.00001*100000000)`
`})`
`p2.addOutput({`
  `  address: "2NBjz5fQCCTyqp84BNYzoc9X2nm324qDMpG",`
   ` value:  parseInt(0.00011*100000000)`
`})`

`console.log(p2)`
`console.log("----")`
`var p2hex = p2.toHex()`
`var p3 = new psbt(p2hex)`
`console.log(p3)`

p2 prints the object with multiple 1 input objects and 2 output objects.
p3 prints the object with 0 input object and 2 output objects.
<img width="404" alt="Screenshot 2020-12-04 at 7 10 36 PM" src="https://user-images.githubusercontent.com/40835224/101170392-655aa180-3664-11eb-94aa-cfb107bb87ad.png">

**Comment by junderw** [comment]
`var p3 = psbt.fromHex(p2hex)`
