### ISSUE TITLE
I need help recovering my wallet pasword on bitgo i have full access to my account ans have several other wakkets but one of them says thw password is incorrect and the are all the same. Please help me

### ISSUE THREAD

**Issue by heidibit** [bitcoinjs/bitcoinjs-lib#1665]
I need help recovering my wallet pasword on bitgo i have full access to my account ans have several other wakkets but one of them says thw password is incorrect and the are all the same. Please help me

_Originally posted by @heidibit in https://github.com/bitcoinjs/bitcoinjs-lib/issues/842#issuecomment-756974781_

**Comment by junderw** [comment]
Can't help you.

If the password is incorrect, then you can't decrypt the private key.

This library has nothing to do with cracking lost passwords.

Please contact Bitgo support.
