### ISSUE TITLE
Segwit native multisg with electrum as a peer not generating same addresses

### ISSUE THREAD

**Issue by chiguireitor** [bitcoinjs/bitcoinjs-lib#1667]
Hi everyone, i'm trying to get bitcoinjs-lib and electrum to play nicely on segwit-multisig, however i'm running into an issue regarding the address generation.

Here's a gist with the code i'm using to test:

https://gist.github.com/chiguireitor/927cb2b4d83d1c0f0254c8d431d4b4ea

And here's a screenshot of electrum and my test side by side:
![imagen](https://user-images.githubusercontent.com/453214/105276945-d4d71280-5b78-11eb-920e-65fe927733a0.png)

The issue, it seems, stems from the bitcoin.payments.p2wsh code, as the redeemscript (witness script on electrum) are the same on both sides.

Am i doing anything wrong here? As you can see electrum generates the first address as "bc1qgrtuq9ud8kxxm2cj5nlq5nk4q86hw3dyx8lav60e5tjraxk8ax5qp38r6c" but my code generates "bc1qrlze0drf7m2244h8fu90tsap62pza4cd08jzhqu2hv7rhckm2naqkrjt9d" (and from the electrum detail dialog, it's using path m/0/0 for derivation).

**Comment by CodeForcer** [comment]
Bitcoinjs will generate the same addresses from public key as Electrum, here is a working derivation of p2sh(p2wpkh):
```
const { address } = bitcoin.payments.p2sh({
  redeem: bitcoin.payments.p2wpkh({
    pubkey: publicKey
  })
})
```

**Comment by junderw** [comment]
Electrum lexicographically sorts the pubkeys of its multisig scripts.

Notice how pubkey 0258... was last in the list of pubkeys, but is first in the witnessScript (52210258...)

Since we are a library, we should allow people to decide whether they want to sort or not, but Electrum (an end user application) should definitely sort, since you don't want the order Zpubs are registered to affect the address outcome.

The following change will fix the issue.

```diff
diff --git a/segwit-multisig-electrum.js b/segwit-multisig-electrum.js
index 5c6168c3..4b133967 100644
--- a/segwit-multisig-electrum.js
+++ b/segwit-multisig-electrum.js
@@ -44,7 +44,7 @@ function test() {
 
   const redeemScript = bitcoin.payments.p2ms({
     m: 2,
-    pubkeys: derivedPubkeys,
+    pubkeys: derivedPubkeys.sort(),
     network
   })
 

```

**Comment by chiguireitor** [comment]
Awesome! Thanks for pointing that out!
