### ISSUE TITLE
Hey! Please tell me what I'm doing wrong.

### ISSUE THREAD

**Issue by NZWhale** [bitcoinjs/bitcoinjs-lib#1674]
I am a beginner developer, doing a test task for an employer and working with blockchain for the first time, but everything was clear up to a certain point. Here is my code and error, thanks!

```
export const BLOCKCYPHERTOKEN = "here is my api key"
const TESTNET = bitcoin.networks.testnet
const keyPair = bitcoin.ECPair.makeRandom({ network: TESTNET });
const psbt = new bitcoin.Psbt({ network: TESTNET });
const pubkeys = [keyPair.publicKey]
const p2shObj = bitcoin.payments.p2sh({ redeem: bitcoin.payments.p2ms({ m: 1, pubkeys, network: TESTNET }) })


const fetchHexTx = (address: string) => {
    const data = fetch(`https://api.blockcypher.com/v1/btc/test3/txs/${address}?includeHex=true&token=${BLOCKCYPHERTOKEN}`)
        .then(response => response.json())
        .then(data => data)
    return data
}
const fetchTxs = (address: string) => {
    const data = fetch(`https://api.blockcypher.com/v1/btc/test3/addrs/${address}?token=${BLOCKCYPHERTOKEN}`)
        .then(response => response.json())
        .then(data => data)
    return data
}

export async function sendCrypto(address: Address, outputAddress: string, amount: number) {
    const keyPair = bitcoin.ECPair.fromWIF(address.privateKey, TESTNET)
    let txsData: Array<any> = []
    const tx = await fetchTxs(address.address)
    const txs = tx.txrefs?tx.txrefs:tx.unconfirmed_txrefs
    for(let i = 0; i<txs.length; i++){
        let txData = await fetchHexTx(txs[i].tx_hash)
        txsData.push(txData)
    }
    console.log(txsData)
    txsData.forEach(function(tx: any) {
        console.log(p2shObj.redeem?.output)
        psbt.addInput({
            hash: tx.hash,
            index: tx.vout_sz,
            nonWitnessUtxo: Buffer.from(
                tx.hex,
                'hex'
            ),
            redeemScript: p2shObj.redeem?.output
        })
    })
    psbt.addOutput({
        address: outputAddress,
        value: amount
    })
    console.log(psbt.inputCount)
    psbt.signInput(0, keyPair)
    console.log(psbt.toBase64())
    psbt.validateSignaturesOfInput(0)
    psbt.finalizeAllInputs()
}
```

`Unhandled Rejection (TypeError): Cannot read property 'script' of undefined
`

**Comment by junderw** [comment]
`tx.vout_sz` is incorrect. You need to use the index of the output which is attributed to your key.

vout_sz is the "size (number count) of outputs" so if you tell PSBT "I am using index 2" but there are only 2 outputs ([0, 1]) you are passing an index that is out of bounds, and therefore is undefined.

**Comment by NZWhale** [comment]
> `tx.vout_sz` is incorrect. You need to use the index of the output which is attributed to your key.
> 
> 
> 
> vout_sz is the "size (number count) of outputs" so if you tell PSBT "I am using index 2" but there are only 2 outputs ([0, 1]) you are passing an index that is out of bounds, and therefore is undefined.

Thank u so much!!!

**Comment by NZWhale** [comment]
@junderw 
Sorry, but I'm stuck again. If I use validateSignaturesOfAllnputs I get the error:
`Uncaught (in promise) Error: No signatures to validate`
If I don't use validateSignaturesOfAllnputs, but use psbt.signAllInputs():
`Can not modify transaction, signatures exist`
And if I don't use both of this methods, i get:
`Uncaught (in promise) Error: Can not finalize input #0`

I also tried specifying a signature for each input inside the forEach (psbt.signInput (0, keyPair)), but I got an error:
Error: Can not sign for this input with the key 028ecdde1bfcb73c3dd4c794fbd9fb8fad2c622086fe0e42c5f36783aebee003ab

Here is my corrected code:
```
 txsData.forEach(function (tx: any, index) {
            console.log(p2shObj.redeem?.output)
            psbt.addInput({
                hash: tx.hash,
                index: index,
                nonWitnessUtxo: Buffer.from(
                    tx.hex,
                    'hex'
                    ),
                    redeemScript: p2shObj.redeem?.output
                })
            })
psbt.addOutput({
                address: outputAddress,
                value: amount
            })
psbt.signAllInputs(keyPair)
// psbt.validateSignaturesOfAllInputs()
psbt.finalizeAllInputs()
```

Thank you!

**Comment by junderw** [comment]
Your index is wrong again.

**Comment by NZWhale** [comment]
I don't understand if this is the first transaction - index 0, if the second is index 1. Is that correct?

**Comment by junderw** [comment]
No.

https://developer.bitcoin.org/devguide/transactions.html#:~:text=An%20input%20uses%20a%20transaction%20identifier%20(txid)%20and%20an%20output%20index%20number

**Comment by NZWhale** [comment]
thanks!
