### ISSUE TITLE
Question: How to indentify segwit input?

### ISSUE THREAD

**Issue by brinzi** [bitcoinjs/bitcoinjs-lib#1675]
Is there any standard way to determine if a UXTO is segwit or not?

I have a bunch of uxto's and want to pass them to coin select.

```
let utxos = [
  ...,
  {
    txId: '...',
    vout: 0,
    ...,
    value: 10000,
    // For use with PSBT:
    // not needed for coinSelect, but will be passed on to inputs later
    nonWitnessUtxo: Buffer.from('...full raw hex of txId tx...', 'hex'),
    // OR
    // if your utxo is a segwit output, you can use witnessUtxo instead
    witnessUtxo: {
      script: Buffer.from('... scriptPubkey hex...', 'hex'),
      value: 10000 // 0.0001 BTC and is the exact same as the value above
    }
  }
]
```

My approach to this issue is to fetch the raw transaction and check  if the 5byte has the segwit marker. As described here
https://bitcoin.stackexchange.com/questions/77286/how-to-verify-if-its-segwit-transaction-or-not

Is this sufficient?

PS. Also do you think I can achieve this just by using the ```dec``` property coming from ```listunspent``` RPC call;

```[
  {
    txid: '00c8285180861183722308533dbfa7993e7e89c7c1bca9822c30c3eaa46f2600',
    vout: 0,
    address: 'bcrt1qcel48mt863qwntwv9rc68yxdtqjyta2vj6l2nm',
    label: '',
    scriptPubKey: '0014c67f53ed67d440e9adcc28f1a390cd582445f54c',
    amount: 25,
    confirmations: 153,
    spendable: true,
    solvable: true,
    desc: "wpkh([d69c9e10/0'/0'/24']03b9cbac56dea4089211b38bf5ae8f8ed716ab5642a990b6d46c5a4c050faf2076)#jyv9xn6x",
    safe: true
  }
]
```

**Comment by junderw** [comment]
The transaction is segwit if any one of the inputs is segwit. All outputs can be non-segwit and the transaction will still be segwit.

Therefore you should not use the transaction marker to tell if the output you wish to spend is segwit or not.

`desc` will be sufficient. If you see a `wpkh(` or a `wsh(` somewhere in there (Note: the following open parenthesis will always follow it, you should match this to prevent random "wsh" string somewhere)

```js
const isSegwit = utxo => !!utxo.desc.match(/wpkh\(|wsh\(/)
```

In general, though, wallets don't mix types. If you made a custom wallet that you will have no idea what type of scripts you are managing...

Either way, if you are spending a utxo, you will need to know all scripts, the previous scriptPubkey and any redeemScripts or witnessScripts.

If you don't have all 1, 2, or 3 of these (depending on the type of script nesting you use) you can't spend anything. If you have all of them, 1. if you have a witnessScript, it's segwit. 2. If the meaningful script (the redeemScript if p2sh) is a p2wpkh script, then it's segwit.

**Comment by brinzi** [comment]
Hey, is it possible to use the rpc `decodescript` without calling the rpc on a given `scriptPubKey` ?
