### ISSUE TITLE
Signature results are different

### ISSUE THREAD

**Issue by caster1213** [bitcoinjs/bitcoinjs-lib#1681]
Java and JS execution results are different

```  javascript
let hash = bitcoin.crypto.sha256(new Buffer('123','utf-8'))
let keyPair = new bitcoin.ECPair(bigInteger.fromBuffer(Buffer.from(priKey, 'hex')))
let sign = keyPair.sign(hash).toDER()
console.log(sign.toString('hex'))
```

```  java
byte[] sha256 = TransactionUtil.Sha256("123".getBytes(StandardCharsets.UTF_8));
Sha256Hash sha256Hash = Sha256Hash.wrap(sha256);
ECKey ecKey = ECKey.fromPrivate(priKey);
ECKey.ECDSASignature ecdsas = ecKey.sign(sha256Hash);
byte[] bytes = ecdsas.encodeToDER();
```

**bitcoinj-core:0.14.7**
**bitcoinjs-lib:3.1.1**

Java code cannot be modified how to make the result of the front-end signature the same as in Java?

**Comment by junderw** [comment]
bitcoinjs-lib v3.1.1 uses RFC6979 nonce generation.
bitcoinj-core:0.14.7 does not.

This is not something that can be changed.

With a given private key and a given message, there are almost infinite number of valid signatures.

If you use the same key, message, AND nonce. Then the same signature will always be output.
