### ISSUE TITLE
payments.p2pkh doesn't return the same address as Armory

### ISSUE THREAD

**Issue by Tatuck** [bitcoinjs/bitcoinjs-lib#1686]
Hello. I am trying to create a: Public Key, Private Key and an Address. I did it using this:
```
let keypair = bitcoin.ECPair.makeRandom()
let res = {
        address: bitcoin.payments.p2pkh({pubkey:keypair.publicKey}).address, // 15QBpPmGiUjBpmAxd55rah552RCad9jG94
        privKeyWIF: keypair.toWIF(), // KwH1sh2J3uLUBA9s4G37YuhXQtWRjZvy3wBFBSnUBAz4ZSpVH6mE
        privKewHex: keypair.privateKey.toString("hex"), // 01b3418f5ed6aa77553edf67c4396ffc68aca96265b49e93f800d04a74f03be5
        pubKey: keypair.publicKey.toString("hex")
}
```
I wanted to know if the values were valid so I installed the program Armory, then I created a new wallet and imported the `privKeyWIF` but it told me that I had to use an Hex one, so I did, but the program say that the corresponding address is this: `1MhQUxKBEr7a6RpGuSU32Ui4ws1vjR6an` and not `15QBpPmGiUjBpmAxd55rah552RCad9jG94` as it should be (right?).
Why am I getting this error? Any help? Thanks!

**Comment by junderw** [comment]
Armory is reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeally old.

`let keypair = bitcoin.ECPair.makeRandom({ compressed: false })`

This should fix the issue. But you shouldn't use uncompressed p2pkh.

**Comment by junderw** [comment]
if you use compressed: false you should get

```
{
  address: '1MhQUxKBEr7a6RpGuSU32Ui4ws1vjR6an',
  privKeyWIF: '5Hq31cMENxMixKPQ85mS3hVDL1LoqcZAXa7rS2K1GSppUkZ8sZ2',
  privKewHex: '01b3418f5ed6aa77553edf67c4396ffc68aca96265b49e93f800d04a74f03be5',
  pubKey: '049ca2c87776acb8aab307a78c1e520f19750e7b388ccc8b92d5902a8c246adc22225f080dda8a5738d804800299603d6fe921a538c660f4041b193bb80bc0e2af'
}
```
