### ISSUE TITLE
Which Node version is the 'Maintenance LTS version' ?

### ISSUE THREAD

**Issue by SatStackr** [bitcoinjs/bitcoinjs-lib#1688]
The project's description says:

> Typically we support the [Node Maintenance LTS version](https://github.com/nodejs/Release).

However the linked [Node Release Schedule](https://github.com/nodejs/Release) only mentions several 'Maintenance' versions and one 'Active LTS' version. Which one is the 'Maintenance LTS' version?

Apologies if this is a stupid question (I'm not very familiar with Node) but I want to make sure I'm not confusing things.

**Comment by junderw** [comment]
From the document:

> There are three phases that a Node.js release can be in: 'Current', 'Active Long Term Support (LTS)', and 'Maintenance'. Odd-numbered release lines are not promoted to LTS - they will not go through the 'Active LTS' or 'Maintenance' phases.

Therefore:

Even numbered major versions are LTS. Odd numbered are non-LTS and will not go through Maintenance phase.

![スクリーンショット_2021-03-26_07-07-25](https://user-images.githubusercontent.com/11246316/112550030-1054be00-8e02-11eb-8c9d-3ada8126887e.png)

The answer is the highest version in the "Maintenance" phase.

v12 currently.
