### ISSUE TITLE
The BTC testnet BECH32 addresses (tb1q) fail when used in a Psbt.addOutput

### ISSUE THREAD

**Issue by lucysmithhome** [bitcoinjs/bitcoinjs-lib#1691]
/**
 * The testnet BECH32 address works fine with the TransactionBuilder.
 *       Note that as TransactionBuilder is deprecated it is not recommended for use any longer.
 * So, the new technique of using Psbt only seems to work with mainnet BTC BECH32 addresses.
 * Psbt does not recognize testnet BECH32 addresses and the code breaks.
 * 
 * As you can see the psbt is constructed with the "bitcoin.networks.testnet" option so it
 * should work for test BECH32 addresses.
 * 
 *       "Error: tb1qtgxz8rpe6r7tgmf7tp2ngf29793zyfnw6zlmrg has an invalid prefix"
 */

const bitcoin = require('bitcoinjs-lib')
const network = bitcoin.networks.testnet

const txb = new bitcoin.TransactionBuilder(network)
     // valid testnet address works CORRECTLY with TransactionBuilder
txb.addOutput("tb1qtgxz8rpe6r7tgmf7tp2ngf29793zyfnw6zlmrg", 13e5)

const psbt = new bitcoin.Psbt(network)
     // valid mainnet address works CORRECTLY with Psbt
psbt.addOutput({address: "bc1qlxnhccvdn9pcecg52z8m3ar6wplwng36u9kqu0", value: 13e5})
     // valid testnet address FAILS with Psbt (but the same address DOES work with TransactionBuilder above)
psbt.addOutput({address: "tb1qtgxz8rpe6r7tgmf7tp2ngf29793zyfnw6zlmrg", value: 13e5})

**Comment by junderw** [comment]
Use `new bitcoin.Psbt({ network })` not `new bitcoin.Psbt(network)`

**Comment by lucysmithhome** [comment]
Awesome, that got it! Thank you.
