### ISSUE TITLE
How does this lib to sign ltc,bch,bchv...etc

### ISSUE THREAD

**Issue by coboywei** [bitcoinjs/bitcoinjs-lib#1698]
does this lib can sign  ltc,bch,bchv..., if yes ,how can i configure it .thank you very much @

**Comment by junderw** [comment]
ltc: just change the network parameter

bch etc.: requires a fork. There are many out there.

These are not officially supported, so you're on your own.

(fyi: I have a fork on my personal repo for `cashv5` that supports BCH and BTG etc... but again, I don't support it officially. You can read the tests to figure out how to use it compared to the main repo.)
