### ISSUE TITLE
Troubles migrating to Psbt from TransactionBuilder

### ISSUE THREAD

**Issue by jhartzell** [bitcoinjs/bitcoinjs-lib#1703]
I have been trying to understand the difference between the two and why I cannot get Psbt to work properly for me.

I have a limited understanding of Bitcoin transactions as-is and the TransactionBuilder class made it possible for me to get started pretty quickly.

I am currently using Electrum as my wallet for testing.

My working TransactionBuilder code:
```js
  const mnemonic = config.depositWalletHd;
  const seed = bip39.mnemonicToSeedSync(mnemonic);
  const root = bip32.fromSeed(seed, testnet);
  
  const keyPair = root as BIP32Interface;

  const tx = new TransactionBuilder(testnet);

  tx.addOutput(
    'tb1q5sensemta6akmtytycxf9dzz8elym8tyu0udq3',
    amountToSend - 1000
  );

  console.log(deposits.length);
  for (let i = 0; i < deposits.length; i++) {
    const deposit = deposits[i];
    tx.addInput(deposit.txid, deposit.nout);
    tx.sign(i, ECPair.fromWIF(deposit.privateKey, testnet));
    console.log(`Signed Input: ${deposit.txid}:${deposit.nout}`);
  }

  // I can broadcast this and receive the funds correctly.
  console.log(tx.build().toHex());
```

My failing Psbt code:
```js
const tx = new Psbt({ network: networks.testnet });

  const p2wpkh = payments.p2pkh({
    pubkey: keyPair.publicKey,
    network: networks.testnet,
  });

  console.log(deposits.length);
  for (let i = 0; i < deposits.length; i++) {
    const deposit = deposits[i];
    console.log(deposit);
    tx.addInput({
      hash: deposit.txid,
      index: deposit.nout,
      // witnessUtxo: {
      //   script: p2wpkh.output as Buffer, // the script of the output pointed by this input
      //   value: deposit.amount, // the value of the output pointed by this input
      // },
    });
  }

  tx.addOutput({
    address: 'tb1q5sensemta6akmtytycxf9dzz8elym8tyu0udq3',
    value: amountToSend - 1000,
  });

  tx.signAllInputs(keyPair);

  console.log(tx.validateSignaturesOfAllInputs());

  let txfinal = tx.extractTransaction();

  console.log(txfinal.toHex());
```

The error I get
```js
Error: No inputs were signed
```

I believe that I am failing to understand how to properly add inputs with the Psbt method. I apologize if this is a dumb and obvious answer, I have attempted to look at all the tests surrounding my use-case but cannot come to a conclusion.

I assume that this is a problem with my knowledge of input scripts.

Thanks in advance for any insight

**Comment by junderw** [comment]
1 question: You use `const p2wpkh = payments.p2pkh({` so I'm confused, do you want to create p2pkh or p2wpkh?

If you meant to use `p2wpkh` then all you need is to change the payments p2pkh to p2wpkh and then un-comment the witnessUtxo. (the one you have should be fine)

If you want the p2pkh (as is) I would recommend renaming the variable, and then you need to add a `nonWitnessUtxo`

`nonWitnessUtxo` is the FULL raw transaction of the tx pointed to by the `deposit.txid` id. Passed as a Buffer.

**Comment by junderw** [comment]
To add some context:

In order to sign, you need to know the output script of the output you're spending.

In a witnessUtxo you just pass the script itself.

In a nonWitnessUtxo, you pass the whole transaction so that the PSBT logic can hash the tx, check it matches the txid passed in the hash value, then check the n-th output for the value n passed to the index value, and gets the script from there directly.

A nonWitnessUtxo can be used with both segwit and non-segwit. But a witnessUtxo can only be used when spending a segwit output. (However, it is recommended to use nonWitnessUtxo wherever possible if you plan on receiving PSBTs to sign from untrusted sources. But since you're just creating the PSBT and signing it immediately, it's fine to use witnessUtxo if you use segwit.)

**Comment by jhartzell** [comment]
@junderw Thanks so much for your response! I'd like to say first off that I am not entirely sure if I want to be using p2pkh or p2wpkh. This is pretty much where my knowledge fades and I just try several things to try and experiment and learn, which is not working well for me at the moment :)

Secondly, I went ahead and tried what you suggested by using nonWitnessUtxo, here is my resulting code
```js
try {
  const tx = new Psbt({ network: networks.testnet });

  for (let i = 0; i < deposits.length; i++) {
    const deposit = deposits[i];
    tx.addInput({
      hash: deposit.txid,
      index: deposit.nout,
      nonWitnessUtxo: Buffer.from(deposit.rawTx, 'hex'),
    });
    tx.signInput(i, ECPair.fromWIF(deposit.privateKey, testnet));
    // tx.signInput(i, keyPair);
  }

  // tx.signAllInputs(keyPair);
  // tx.signAllInputsHD(keyPair);

  tx.addOutput({
    address: 'tb1q5sensemta6akmtytycxf9dzz8elym8tyu0udq3',
    value: amountToSend - 1000,
  });

  console.log(tx.validateSignaturesOfAllInputs());

  let txfinal = tx.extractTransaction();

  console.log(txfinal.toHex());
} catch (ex) {
  console.log(ex);
}
```

```
Error: Can not sign for this input with the key 03e17ca78ca1f28312e5............
```

I tried signing with the root keyPair of the HD wallet and also the keypair for the derived address in my case `"m/44'/0'/0'/29"`

Both resulting in this same error.. I am using the same privateKey as I did in the transaction builder example so I'm sure I'm using the right keys.

Here's a little bit about my scenario;

I have an electrum wallet and a few test accounts, these test accounts have addresses derived from my HD wallet. I make a deposit with one of these test accounts and wait for the funds come in. Once the funds clear, I run a utility that is meant to "sweep" the funds off that derived address and into the root address of the electrum wallet.

I'm not sure if the above explanation helps at all but I'm just trying to understand where my disconnect is here. Thanks again!

**Comment by jhartzell** [comment]
I managed to solve this problem but I'm actually quite puzzled as to why this resolved it.

Final (Working) code:

```js
try {
  const tx = new Psbt({ network: networks.testnet });

  tx.addOutput({
    address: 'tb1q5sensemta6akmtytycxf9dzz8elym8tyu0udq3',
    value: amountToSend - 1000,
  });

  for (let i = 0; i < deposits.length; i++) {
    const deposit = deposits[i];
    tx.addInput({
      hash: deposit.txid,
      index: deposit.nout,
      nonWitnessUtxo: bitcoin.Transaction.fromHex(deposit.rawTx).toBuffer(),
    });
    tx.signInput(i, bitcoin.ECPair.fromWIF(deposit.privateKey, testnet));
  }

  tx.validateSignaturesOfAllInputs();
  tx.finalizeAllInputs();

  const finalTx = tx.extractTransaction();
  const txHex = finalTx.toHex();

  console.log(txHex);
} catch (ex) {
  console.log(ex);
}
```

I made one simple change, I moved the `tx.addOutput` call above the portion that adds and signs the inputs. I'm guessing that part of the signing process expects the outputs be provided before signing? 

I'd love to understand a little more as to why this fixed the problem so I guess it's time to dig into the source to try and understand more about what is happening.

Thanks @junderw

**Comment by junderw** [comment]
> I'm assuming that you have to provide the outputs to the transaction before signing it, because signing the transaction with outputs would result in different bytecode than signing it without? I'd love to understand this a little better.

Yes. Also, you need to add all the inputs before signing any of them.

Your current code will only work if there is only 1 deposit.

So you need one loop to add inputs and a separate loop to sign the inputs.

**Comment by Nisthar** [comment]
@jhartzell can you tell me where you get the `rawTx` in the 
```js
  tx.addInput({
      hash: deposit.txid,
      index: deposit.nout,
      nonWitnessUtxo: Buffer.from(deposit.rawTx, 'hex'),
    });
    ```

**Comment by jhartzell** [comment]
@Nisthar sorry for the late response, but I query my core node for "getrawtransaction" for the given txid
