### ISSUE TITLE
How to create an address from a mnemonic phrase

### ISSUE THREAD

**Issue by maizenalegal** [bitcoinjs/bitcoinjs-lib#1705]
title

**Comment by junderw** [comment]
Here's an example for BIP49 P2SH-P2WPKH.

By looking at this you can probably figure out how to generate any other type of address.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/27a840aac4a12338f1e40c54f3759bbd7a559944/test/integration/bip32.spec.ts#L103-L120
