### ISSUE TITLE
Get address using vpub

### ISSUE THREAD

**Issue by aitorjs** [bitcoinjs/bitcoinjs-lib#1706]
Hello,

I want to get an address of a derivePath using vpub (testnet) for that. I get it using tpub successfully:

```js
const bitcoin = require('bitcoinjs-lib');
const { generateMnemonic, mnemonicToSeedSync } = require('bip39');
const b58 = require('bs58check');

const xpub = "tpubD6NzVbkrYhZ4X7Ra2C2cQFiyarGbv7xZhmh55bUmmCoW2ctUoaqwfBY7kGmgsfxzKeydHW3QGHNngjhDykvZAEmZKomfjaB8VfThsXwt4gP";
function getWalletAddress(chainNumber = 0) {
  const root = bitcoin.bip32.fromBase58(
    xpub,
    bitcoin.networks.testnet,
  );
  const child = root.derivePath(`m/0/${chainNumber}`);
  const { address } = bitcoin.payments.p2pkh({
    pubkey: child.publicKey,
    network: bitcoin.networks.testnet
  });

  return address;
}
const address = getWalletAddress(6);
console.log("address", address);

if (address === "mvQyJF37Wefqp64i4GAZJ1kBMz598tUA2k") {
  console.log("EQUALS")
}
```

I get "EQUALS", so goes well. When I change xpub with vpub (vpub5V4pBj27qZNwHvoCNoqsD1gUZe3opU9inN67yVPZqVt5GxBxHukc3meSbxHzijxSFXFmpuBZKWUb64QMtjA783XNguyh7VX4U3p5or82T5H) inside bitcoin.bip32.fromBase58, I get this error: "Invalid network version". If I change vpub to xpub using this function:

```js
function anypubToXpub(xyzpub) {
  let data = b58.decode(xyzpub)
  data = data.slice(4)
  data = Buffer.concat([Buffer.from('043587cf', 'hex'), data])
  return b58.encode(data)
}
```
and use the resulted vpub instead of xpub inside bitcoin.bip32.fromBase58, I get this error: "Expected master, got child".

¿What I'm doing wrong?

Thanks! :)

**Comment by junderw** [comment]
1. You must pass a network object with the proper extended public and private key info.

2. derivePath starting with "m" can only use a root key (depth 0) so your vpub probably has a depth of >0. by removing the leading m/ it should work, but you should be aware of what you are deriving.
