### ISSUE TITLE
Custom OP code

### ISSUE THREAD

**Issue by dekadentno** [bitcoinjs/bitcoinjs-lib#1712]
I am working on a Bitcoin fork where I have some other OP codes that are not mentioned in [bitcoin-ops](https://github.com/bitcoinjs/bitcoin-ops/blob/master/index.json). Is there a way to programmatically add a custom OP code without the need to fork bitcoin-ops and add it there?

The real use case is something like this: my script pub key looks something like this
```
...
asm: "0046ced10000014666dec9df7d06d26a32f7 OP_BLAH"
...
```
but ```OP_BLAH``` gets replaced od ignored somehow after the build. How can I handle this and where should I look for the problem?

Just in case the tx hex is needed: 
```
04000000013012a1502cc70f777767ffeb0e384187326addc7130a7c93a1a6537f2d1b473e010000006a473044022013915233daf475add2d3a5302e3f134b7a038b1bef96483dcc30874b89de47870220747a49c9ca47d6ecebd15d4cf18da1dcb51c99db27613a5b12ebc277223c328c012102a54a2fd3812683e43a8d539ec9d12cea26d6455311cbe265294434fb1cc1e573ffffffff0340420f00000000001976a914eb17309d2b052ba186d97331e880acf2040bbe0a88ac0000000000000000fdcb017b2261736d223a22303034363931383130303030303134366131383933636134373531326466383265316236204f505f464545574f524b222c22686578223a2231303030343639313831303030303031343661313839336361343735313264663832653162366431222c2274797065223a22666565776f726b222c22686569676874223a343632343736392c22626c6f636b5f68617368223a2235333731333334323533313162383737353335636338396637303064623931306434633734396632366531323234313935616265323764383964353161323635222c226d636f7374223a3332362e36353539393939393939393939352c226279746573223a3136312c226c696d69745f686578223a2230303036666666666666666666666666222c226c696d69745f64656e617279223a313937303332343833363937343539312c22776f726b5f686578223a226131383933636134373531326466383265316236222c22776f726b5f64656e617279223a22373632383332353737343236333733343633393537393432222c22686173685f686578223a2230303031306666383037386264616134222c22686173685f64656e617279223a22323939303332393239363232363932227da0782d00000000001976a9144fb61040e5dbc5c9b0c1b423ee2526765dea014b88ac00000000
```

**Comment by junderw** [comment]
It looks as if you are replacing pushdata op codes.

If you are changing any of the 97 ops between 0x00 ~ 0x60 and how they work, the changes are much larger than just adding a few ops to bitcoin-ops.

The only strange data I can find in your tx is the second output's script.

These are the ops it reads in order.

```
OP_ROT
PUSHDATA length 34
OP_NOTIF
OP_VERNOTIF
PUSHDATA length 56
OP_VERNOTIF
PUSHDATA length 56
PUSHDATA length 34
OP_IF
PUSHDATA length 55
PUSHDATA length 53
OP_2DUP
OP_NOP
OP_2SWAP
OP_PICK
PUSHDATA length 34
PUSHDATA length 51
PUSHDATA length 53
PUSHDATA length 57 <- This PUSHDATA pushes the counter beyond the upper bound. causing an error.
```

This indicates to me that your scripting language has extra rules, OR you have replaced something between 0x00~0x60 and are causing parsing errors in the library. A simple addition to bitcoin-ops will not fix either of these issues.

Sorry I couldn't help any further.
