### ISSUE TITLE
How create a partially sign multisig transaction using Psbt

### ISSUE THREAD

**Issue by yatogamidev** [bitcoinjs/bitcoinjs-lib#1714]
I can sign a multisig transaction with two private keys, but I need to sign with only one key and send the partially signed transaction to the next sign, **how to create a partially signed multisig transaction?**

```
const bitcoin = require("bitcoinjs-lib")
const network = bitcoin.networks.testnet

const keyPairAlice = bitcoin.ECPair.fromWIF("cQPKbLJwChEXHLbdPq5BEGCWErTxwtuVMaqaxD7DooQPPbxo5yQi", network)
const keyPairBob = bitcoin.ECPair.fromWIF("cSXHt1RSmr4cps1FGXjSx4nu71dn7hkxMqrQ6kbaBDhKWAeMr4LQ", network)
const keyPairKira = bitcoin.ECPair.fromWIF("cPrwok7NntxviTPFmnGdcGqfc8ReHUjQUNoGrMssScHwUUMhGoo1", network)

const psbt = new bitcoin.Psbt({ network })

const pubkeys = [
  keyPairAlice.publicKey.toString("hex"),
  keyPairBob.publicKey.toString("hex"),
  keyPairKira.publicKey.toString("hex"),
].map(hex => Buffer.from(hex, "hex"))

const p2ms = bitcoin.payments.p2ms({
  m: 2, pubkeys, network
})

const hash160sha256 = bitcoin.crypto.hash160(
  Buffer.from('0020' + bitcoin.crypto.sha256(p2ms.output).toString('hex'),
    'hex'))

const p2wsh = bitcoin.payments.p2wsh({ redeem: p2ms, network })
const p2sh = bitcoin.payments.p2sh({ redeem: p2wsh, network })

console.log('P2SH address:')
console.log(p2sh.address)
console.log()

const fee = 300
const amount = 1000

psbt.addInput({
  hash: 'eb117e79b0523946af5165601493c40350a88c7baeddecc2ac275b014c97d53f',
  index: 1,
  redeemScript: Buffer.from('0020' + bitcoin.crypto.sha256(p2ms.output).toString('hex'), 'hex'),
  witnessScript: p2wsh.redeem.output,
  witnessUtxo: {
    script: Buffer.from('a914' + hash160sha256.toString('hex') + '87', 'hex'),
    value: 49000,
  }
})
  .addOutput({
    address: "2N5HDPVvFp3jHm2XjNvtvf9Jik69G992pyC",
    value: 49000 - amount - fee,
  })
  .addOutput({
    address: "mkHS9ne12qx9pS9VojpwU5xtRd4T7X7ZUt",
    value: amount,
  })


try {
  psbt
    .signInput(0, keyPairAlice)
    .signInput(0, keyPairKira)
} catch (error) {
  console.log(error)
}

psbt.finalizeAllInputs()
const tx = psbt.extractTransaction().toHex()
console.log(tx)
console.log()
```

**Comment by junderw** [comment]
This is a good example of how you could export and import a PSBT and transport between people.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/27a840aac4a12338f1e40c54f3759bbd7a559944/test/integration/transactions.spec.ts#L75-L160

The same concept applies, except instead of two people signing two inputs, your version would be two people signing the same input (because it's multisig)

**Comment by junderw** [comment]
Also:

1. Why are you converting `pubkeys` to hex and back? Just don't convert to hex to begin with.
2. Why are you using `crypto.hash160` etc. `witnessUtxo.script` is `p2sh.output` and `redeemScript` is `p2sh.redeem.output`

**Comment by yatogamidev** [comment]
> Além disso:
> 
> 1. Por que você está convertendo `pubkeys`para hexadecimal e vice-versa? Só não converta para hexadecimal para começar.
> 2. Por que você está usando `crypto.hash160`etc. `witnessUtxo.script`é `p2sh.output`e `redeemScript`é`p2sh.redeem.output`

it's because I'm following this tutorial, it was the only one that worked for me, so I'm lost, the code you sent me above doesn't work for me

https://bitcoinjs-guide.bitcoin-studio.com/bitcoinjs-guide/v5/part-three-pay-to-script-hash/multi_signatures/multisig_np2wsh_2_4.html#_creating_and_funding_the_p2sh

**Comment by yatogamidev** [comment]
it's because I'm following this tutorial, it was the only one that worked for me, so I'm lost, the code you sent me above doesn't work for me

https://bitcoinjs-guide.bitcoin-studio.com/bitcoinjs-guide/v5/part-three-pay-to-script-hash/multi_signatures/multisig_np2wsh_2_4.html#_creating_and_funding_the_p2sh

**Comment by yatogamidev** [comment]
my code is working, the only problem is I don't know how to do it partially signed

**Comment by junderw** [comment]
In the example I gave you, what method did it use to export psbt data to "send out to the signers"?

What static method did each signer use to import psbt data into `signer1` and `signer2` objects?

After they signed, and re-exported using the same method in question 1, what did the person receiving the exported text from signer1 and signer2 do with the text (s1text, s2text)?

Once you can answer these questions you'll understand what you need to do.
