### ISSUE TITLE
How to get uncompressed address from Private Key in this example?

### ISSUE THREAD

**Issue by boypush** [bitcoinjs/bitcoinjs-lib#1715]
Hello,
I'm using the BitcoinJS. May i know how to get an uncompressed address?

priv_key = getPrivKey(numbers[i])
address = bitcoin.payments.p2pkh({ pubkey: bitcoin.ECPair.fromPrivateKey(Buffer.from(getPrivKey(numbers[i]), 'hex')).publicKey }).address
addresses.push(address)

**Comment by junderw** [comment]
The second arg in bitcoin.ECPair.fromPrivateKey is an object which you can pass false to compressed.

`bitcoin.ECPair.fromPrivateKey(key, { compressed: false })`

**Comment by boypush** [comment]
> The second arg in bitcoin.ECPair.fromPrivateKey is an object which you can pass false to compressed.
> 
> `bitcoin.ECPair.fromPrivateKey(key, { compressed: false })`

Thanks for the answer, I tried to do this with my example:
address = bitcoin.payments.p2wpkh({ pubkey: bitcoin.ECPair.fromPrivateKey(Buffer.from(getPrivKey(numbers[i]), { compressed: false }, 'hex')).publicKey }).address
But I get an error in the console:
Uncaught a {message: "Expected Buffer(Length: 32), got Buffer(Length: 64)", __type: "Buffer(Length: 32)", __value: {…}, __valueTypeName: "Buffer(Length: 64)", stack: "Error: Expected Buffer(Length: 32), got Buffer

**Comment by junderw** [comment]
You're passing the object to Buffer.from()...

**Comment by junderw** [comment]
(In JavaScript it's usually a good idea to multi-line when there's tons of nested functions as arguments to nested functions so you don't get confused)

**Comment by boypush** [comment]
> (In JavaScript it's usually a good idea to multi-line when there's tons of nested functions as arguments to nested functions so you don't get confused)

Here is the function that affects, but I do not understand what value to set:
`function getPrivKey(number) {
				key = decToHex(number).padStart(64, '0')
				return key
			}`

**Comment by boypush** [comment]
> You're passing the object to Buffer.from()...

And how to correctly prescribe that: { compressed: false }

**Comment by junderw** [comment]
I added some whitespace and comments so you can see better.

You are passing it to `Buffer.from`. That is not `bitcoin.ECPair.fromPrivateKey`.

`bitcoin.ECPair.fromPrivateKey` and `Buffer.from` are different functions. The first one is a function for bitcoin, the second one is a function for NodeJS.

```js
address = bitcoin.payments.p2pkh(
  {
    pubkey: bitcoin.ECPair.fromPrivateKey( // fromPrivateKey start
      Buffer.from( // Buffer.from start
        getPrivKey(numbers[i]), // Buffer.from argument 1
        { compressed: false }, // Buffer.from argument 2
        'hex', // Buffer.from argument 3
      ), // Buffer.from end
    ).publicKey, // fromPrivateKey end
  },
).address
```

**Comment by boypush** [comment]
> I added some whitespace and comments so you can see better.
> 
> You are passing it to `Buffer.from`. That is not `bitcoin.ECPair.fromPrivateKey`.
> 
> `bitcoin.ECPair.fromPrivateKey` and `Buffer.from` are different functions. The first one is a function for bitcoin, the second one is a function for NodeJS.
> 
> ```js
> address = bitcoin.payments.p2pkh(
>   {
>     pubkey: bitcoin.ECPair.fromPrivateKey( // fromPrivateKey start
>       Buffer.from( // Buffer.from start
>         getPrivKey(numbers[i]), // Buffer.from argument 1
>         { compressed: false }, // Buffer.from argument 2
>         'hex', // Buffer.from argument 3
>       ), // Buffer.from end
>     ).publicKey, // fromPrivateKey end
>   },
> ).address
> ```
Thank you very much for the detailed explanation, I will look for a solution.

**Comment by junderw** [comment]
It might be easier to see if you split into multiple steps using variables:

```js
const privKeyHex = getPrivKey(numbers[i])
const privKey = Buffer.from(privKeyHex, 'hex')
const ecPair = bitcoin.ECPair.fromPrivateKey(privKey) // <-- Add { compressed: false } as second argument here
const p2pkhPayment = bitcoin.payments.p2pkh({ pubkey: ecPair.publicKey })
const address = p2pkhPayment.address
```
