### ISSUE TITLE
How to broadcast transactions to the testnet and mainet networks?

### ISSUE THREAD

**Issue by Adoliin** [bitcoinjs/bitcoinjs-lib#1719]
[This line](https://github.com/bitcoinjs/bitcoinjs-lib/blob/7b753caad6a5bf13d40ffb6ae28c2b00f7f5f585/test/integration/transactions.spec.ts#L159) supposedly contains a Github issue that explains that but its no longer accesible.

**Comment by junderw** [comment]
#839 I can still see it.

1. Set up a node, or find a free public API
2. Send a RPC request to your node with sendrawtransaction OR use whatever API (REST etc.) for pushing tx that you can find.
