### ISSUE TITLE
Whether to support BCH transfer?

### ISSUE THREAD

**Issue by sxbjy** [bitcoinjs/bitcoinjs-lib#1720]
I want to use this library to realize BCH transfer，but an error occurred during transfer。Error："bitcoincash:xxxxxxx has no matching Script" 。What should i do？

**Comment by dakk** [comment]
Read here https://github.com/bitcoinjs/bitcoinjs-lib/issues/1698

**Comment by junderw** [comment]
I have a small fork I maintain as a side-project located here: https://github.com/junderw/bitcoinjs-lib/tree/cashv5

You can install with npm using `npm install bitcoinjs-lib@git+https://github.com/junderw/bitcoinjs-lib.git#cashv5`

Installing in this way will give you my personal fork whenever you `require('bitcoinjs-lib')`

This library has no plans to support any forkcoins of BTC.

**Comment by junderw** [comment]
Be warned though, I make no guarantee that branch will always exist, so if you must rely on it for something, I recommend creating your own fork so you can keep that branch alive even if I delete it.
