### ISSUE TITLE
 Error: Can not sign for this input with the key <keys>

### ISSUE THREAD

**Issue by mosesadeyinka** [bitcoinjs/bitcoinjs-lib#1725]
Hello i created a testnet address. 
```
private key: "cQNr2RTfTjo4c5R9pyGm2CNRpRbJxKLpkm2JedbyC5dH9F33MKa4",
address: "n4iRvNhWXup6gqu2C25K83KiQcoKrSoR1x"
```

here is my code
  
```js
const TESTNET = bitcoin.networks.testnet;
const alice = bitcoin.ECPair.fromWIF(
  'cQNr2RTfTjo4c5R9pyGm2CNRpRbJxKLpkm2JedbyC5dH9F33MKa4',TESTNET
);
const psbt = new bitcoin.Psbt({network: TESTNET});

psbt.setVersion(2); // These are defaults. This line is not needed.
psbt.setLocktime(0); // These are defaults. This line is not needed.
psbt.addInput({
  // hash is gotton from here https://api.blockcypher.com/v1/btc/test3/addrs/2N1uzcCxmVxRFVtwCtsJLVGbUZbSG3syZsE/full?limit=50?unspentOnly=true&includeScript=true
  hash: 'c3be915b6a725c890d80d48027423bdb947ca180bbcc2f5a006eee654acf4af5',
  index: 0,
  sequence: 0xffffffff, // These are defaults. This line is not needed.
  witnessUtxo: {
    script: Buffer.from(
      'a9147171cb5d4454a8335604230cb0e0e46f5200cfb387',
      'hex',
    ),
    value: 90000,
  },
  // Not featured here:
  redeemScript: Buffer.from(
    '001425f0b6587bddbe23cf9a87828d655df31ab28b99',
    'hex',
  ),
  //   witnessScript. A Buffer of the witnessScript for P2WSH
});
psbt.addOutput({
  address: 'mv4rnyY3Su5gjcDNzbMLKBQkBicCtHUtFB',
  value: 80000,
  network: TESTNET
});
psbt.signInput(0, alice);
psbt.validateSignaturesOfInput(0);
psbt.finalizeAllInputs();

const rawTx = psbt.extractTransaction().toHex();
console.log(rawTx);
```
but i keep getting this error.    Error: Can not sign for this input with the key

**Comment by junderw** [comment]
Exactly how the error states, your keys don't match.

1. The key of the private key for alice
2. The key that you mention in the comment (all UTXOs are spent)
3. Some other key (that you are referencing the script in witnessUtxo)

| Private | Address | Script |
|:---:|:---:|:---:|
| cQNr2RTfTjo4c5R9pyGm2CNRpRbJxKLpkm2JedbyC5dH9F33MKa4 | 2N4KUfKqvbBZzw1RjWs54mh8yk9v7vAcCyt | a91479774bc599362faa7deabfc342623e16d2d4320487 |
| ??? | 2N1uzcCxmVxRFVtwCtsJLVGbUZbSG3syZsE | a9145f160f26e702212ac2520000c89171caac3e8a2d87 |
| ??? | 2N3b4fXunecA3pgRGFwpdKUtzFFwFDifXp3 | a9147171cb5d4454a8335604230cb0e0e46f5200cfb387 |

You need to figure out what is what before it will work.

Also, none of those three addresses have any coins left. (2 had some coins but they've already been spent.)

**Comment by mosesadeyinka** [comment]
Any idea or link on how to generate private key

**Comment by junderw** [comment]
It might be better to make a simple wrapper class that lets you keep everything together in one place.

<details><summary>Wallet class</summary>
<p>

```js
const crypto = require('crypto');
const { ECPair, networks, payments } = require('bitcoinjs-lib');
const WALLET_TYPES = ['p2wpkh', 'p2sh-p2wpkh'];
class Wallet {
  constructor(privateKey, type, network = networks.bitcoin) {
    this.privateKey = privateKey;
    this.type = type;
    this.network = network;
    if (!Buffer.isBuffer(this.privateKey) || this.privateKey.length !== 32) {
      throw new Error(`privateKey must be 32 byte Buffer`);
    }
    if (!WALLET_TYPES.includes(type)) {
      throw new Error(
        `Wrong type ${type}, type must be in [${WALLET_TYPES.join(', ')}]`,
      );
    }
    this.keyPair = ECPair.fromPrivateKey(this.privateKey, {
      network: this.network,
    });
    switch (this.type) {
      case 'p2wpkh': {
        this.payment = payments.p2wpkh({
          pubkey: this.keyPair.publicKey,
          network: this.network,
        });
        break;
      }
      case 'p2sh-p2wpkh': {
        this.payment = payments.p2sh({
          redeem: payments.p2wpkh({
            pubkey: this.keyPair.publicKey,
            network: this.network,
          }),
          network: this.network,
        });
        break;
      }
      default: {
        throw new Error('no type');
      }
    }
  }
  static import(importData) {
    const { wif, type, network } = importData;
    const pair = ECPair.fromWIF(wif, network);
    return new Wallet(pair.privateKey, type);
  }
  static makeRandom(type = 'p2sh-p2wpkh', network = networks.bitcoin) {
    return new Wallet(crypto.randomBytes(32), type, network);
  }
  export() {
    return {
      wif: this.keyPair.toWIF(),
      type: this.type,
      network: this.network,
    };
  }
  get script() {
    return this.payment.output;
  }
  get address() {
    return this.payment.address;
  }
  get redeemScript() {
    if (this.payment.redeem) {
      return this.payment.redeem.output
    }
  }
  // Implement Signer interface
  get publicKey() {
    return this.keyPair.publicKey;
  }
  getPublicKey() {
    return this.keyPair.publicKey;
  }
  sign(hash, lowR) {
    return this.keyPair.sign(hash, lowR);
  }
}
```

</p>
</details>

This can be used like this:
("p2wpkh" is pure Segwit, "p2sh-p2wpkh" is Segwit wrapped in a more-compatible address format)
("p2wpkh" is cheaper fees to spend since it uses less space)

<details><summary>Usage</summary>
<p>

```js
const wallet = Wallet.makeRandom('p2sh-p2wpkh', networks.testnet);

console.log(wallet.address);
// outputs the address

console.log(wallet.export());
// This outputs a data object like this
// { wif: '...', type: 'p2sh-p2wpkh', network: { ... } }

// now you can use the wallet class to create your script and redeemScript for you
psbt.addInput({
  hash: '...',
  index: 0,
  sequence: 0xffffffff,
  witnessUtxo: {
    script: wallet.script,
    value: 90000,
  },
  redeemScript: wallet.redeemScript, // wallet.redeemScript will be undefined if the wallet is "p2wpkh"
  // But that is ok, since p2wpkh doesn't need a redeemScript
})

// You can also pass this wallet directly in as a signer for PSBT, because it implements the Signer interface.
psbt.signInput(0, wallet);
```

</p>
</details>

**Comment by junderw** [comment]
(FYI: You can click "Wallet class" and "Usage" to open the code examples in the comment above)

**Comment by mosesadeyinka** [comment]
I followed the example classes perfectly but am getting error "sendrawtransaction RPC error: {"code":-25,"message":"bad-txns-inputs-missingorspent"}"

`

const WALLET_TYPES = ['p2wpkh', 'p2sh-p2wpkh'];
const { ECPair, networks, payments } = require('bitcoinjs-lib');
const crypto = require('crypto');

class Wallet {
    constructor(privateKey, type, network = networks.bitcoin) {
      this.privateKey = privateKey;
      this.type = type;
      this.network = network;
      if (!Buffer.isBuffer(this.privateKey) || this.privateKey.length !== 32) {
        throw new Error(`privateKey must be 32 byte Buffer`);
      }
      if (!WALLET_TYPES.includes(type)) {
        throw new Error(
          `Wrong type ${type}, type must be in [${WALLET_TYPES.join(', ')}]`,
        );
      }
      this.keyPair = ECPair.fromPrivateKey(this.privateKey, {
        network: this.network,
      });
      switch (this.type) {
        case 'p2wpkh': {
          this.payment = payments.p2wpkh({
            pubkey: this.keyPair.publicKey,
            network: this.network,
          });
          break;
        }
        case 'p2sh-p2wpkh': {
          this.payment = payments.p2sh({
            redeem: payments.p2wpkh({
              pubkey: this.keyPair.publicKey,
              network: this.network,
            }),
            network: this.network,
          });
          break;
        }
        default: {
          throw new Error('no type');
        }
      }
    }
  
  
  
  
  
    static import(importData) {
      const { wif, type, network } = importData;
      const pair = ECPair.fromWIF(wif, network);
      return new Wallet(pair.privateKey, type, network);
    }
     makeRandom(type = 'p2sh-p2wpkh', network = networks.bitcoin) {
      return new Wallet(crypto.randomBytes(32), type, network);
    }
    export() {
      return {
        wif: this.keyPair.toWIF(),
        type: this.type,
        network: this.network,
      };
    }
    get script() {
      return this.payment.output;
    }
    get address() {
      return this.payment.address;
    }
    get redeemScript() {
      if (this.payment.redeem) {
        return this.payment.redeem.output
      }
    }
    // Implement Signer interface
    get publicKey() {
      return this.keyPair.publicKey;
    }
    getPublicKey() {
      return this.keyPair.publicKey;
    }
    sign(hash, lowR) {
      return this.keyPair.sign(hash, lowR);
    }
  }


  

module.exports = Wallet;
`
`

        const TESTNET = bitcoin.networks.testnet;


          const psbt = new bitcoin.Psbt({network: TESTNET});
        
          
          




      psbt.addInput({
          hash: '266c68e8c85349956cce274159bfbad46ab913f4484ee733a6b9b48632efaad1',
          index: 0,
          sequence: 0xffffffff,
          witnessUtxo: {
            script: wallet.script,
            value: 90000,
          },
          redeemScript: wallet.redeemScript, // wallet.redeemScript will be undefined if the wallet is "p2wpkh"
          // But that is ok, since p2wpkh doesn't need a redeemScript
        })
 

          psbt.addOutput({
            address: 'mv4rnyY3Su5gjcDNzbMLKBQkBicCtHUtFB',
            value: 80000,
            network: TESTNET
          });
           psbt.signInput(0, wallet);
          psbt.validateSignaturesOfInput(0);
          psbt.finalizeAllInputs();

        const rawTx = psbt.extractTransaction().toHex();


        console.log(rawTx);`

**Comment by mosesadeyinka** [comment]
[wallet.txt](https://github.com/bitcoinjs/bitcoinjs-lib/files/7201711/wallet.txt)

**Comment by junderw** [comment]
I looked at the transaction here: https://blockstream.info/testnet/tx/266c68e8c85349956cce274159bfbad46ab913f4484ee733a6b9b48632efaad1?expand

1. You are trying to spend output 0 (first output) but it is already spent.
2. Your witnessUtxo has value of 90000 but the neither of the two outputs have that value.

Perhaps you want to use `index: 1,` and `value: 1969075,` which is the value to the 2nd (index 1) output.

The keys must be the same though.

**Comment by junderw** [comment]
I have updated the Wallet class and Usage comment above with some useful features using blockstream API.

Be careful when doing things quickly, since blockstream API is replicated across many load balancers, so if you run the get utxos query right after sending a tx, it will return different results every time for a few seconds.

Please use the example above to help in your understanding.

Note: redeemScript can not be defined as undefined. If you do so, the library throws an error, so I made it only add redeemScript if it exists.

**Comment by mosesadeyinka** [comment]
I modified some codes in the wallet class that was throwing an error

[wallet.txt](https://github.com/bitcoinjs/bitcoinjs-lib/files/7204728/wallet.txt)


the execution
  let res = await wallet.sendCoins("mv4rnyY3Su5gjcDNzbMLKBQkBicCtHUtFB", "1909075","2N4K9pEkDWWrsfYMx5jmVUrPg7zJXj4xaWm");

      console.log(res);

the broadcast throw error "mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)"

**Comment by junderw** [comment]
Your modifications won't work.

1. You aren't incrementing totalInputAmount
2. You are trying to sign using a function parameter when the class is trying to use this.script and this.redeemScript from the internal key.

If you want to use your own key, use my code as is, and import the WIF private key along with the key type and network.

**Comment by mosesadeyinka** [comment]
i think there's a misunderstanding with your code, how do you identify which address you are sending from since you aren't passing it from the `sendcoin()`

This fetch is for new address that was generated? 
What of the one that contains the money?
`this.address`
    `const response = await fetch(`${this.apiUrl}/address/${this.address}/utxo`);`

so i modified the code to accept the parameter  (address)of  which contains the money & get the txtid

**Comment by mosesadeyinka** [comment]
i solved the code & broadcast the BTC by using a unique private key

**Comment by junderw** [comment]
you don't have to use makeRandom every time.

you can use import.

If you want to see what to pass import, look at the  Usage example I added.

**Comment by junderw** [comment]
For example:
```js
  const wallet = Wallet.import({
    wif: 'cQNr2RTfTjo4c5R9pyGm2CNRpRbJxKLpkm2JedbyC5dH9F33MKa4',
    type: 'p2sh-p2wpkh',
    // This is testnet network info
    network: {
      messagePrefix: '\u0018Bitcoin Signed Message:\n',
      bech32: 'tb',
      bip32: { public: 70617039, private: 70615956 },
      pubKeyHash: 111,
      scriptHash: 196,
      wif: 239,
    },
  });
  await wallet.getUtxos();
  if (wallet.utxos.length === 0) {
    throw new Error(`Need coins. Please send to ${wallet.address}`);
  }

  console.log(
    `Current balance: ${wallet.calculateBalanceFromUtxos() / 1e8} tBTC`,
  );
  console.log(`Current utxos:`);
  console.log(wallet.utxos);

  const txid = await wallet.sendCoins(toAddress, value);
  console.log(`Sent ${value / 1e8} tBTC coins at txid ${txid}`);
```
