### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [bitcoinjs/bitcoinjs-lib#1728]
hello everyone 

i want to only compile ECPair module for browser  to use in reactjs , i used browserify and uglify but when i use only ECPair  module , then all other modules will be add to compiled code , that bundle size is big for reactjs and webpack i want to separate module to reduce the bundle size 

please help to do it 

thank you.

**Comment by junderw** [comment]
ecpair.js
networks.js
types.js

copy these files into a new package and make the main file ecpair.js

add dependencies for

tiny-secp256k1@^1.0.0
wif
typeforce
randombytes

then package that into your webpack. it should be much smaller.

**Comment by Johnsavadkuhi** [comment]
thank you man , 
there are some problems when i use compiled bitcoinjs-lib file with browserify in webpack 5 and reactjs
