### ISSUE TITLE
How to get value from nonWitnessUtxo input and how to add change address derivation path to output

### ISSUE THREAD

**Issue by AndreasGassmann** [bitcoinjs/bitcoinjs-lib#1730]
I have the following PSBT with a nonWitnessUtxo input:

(This PSBT was generated by Sparrow Wallet).

`70736274ff01005202000000017395e9912a36a3caf6d753b8dca0512f498f1c143a6516c6f5458c18e00b72310100000000fdffffff015615000000000000160014e83d36778b655dc2bc7ee6cbbdd62dac8c792c179dc00a000001009d020000000233e0aaebcb18169e1e6b0f0ef0aaeddd059b219b813551934f39bf7c2843051d0000000000ffffffffe5ed81f9c881f973e00e61c8edbf0498a33525498d1608e0bf244b50a72f31b40100000000ffffffff02e8030000000000001976a914b0b559a4f6e52d88b70dfef746373b0615a7e67988acc4150000000000001600143d2b21c137ea1bbe3115723e6c889ad6613b1d3100000000010304010000002206038c381ca1cbd86bd1bc88587e02522fd4369b599341583b78dc17b34a7180b091186f01ffc85400008000000080000000800100000003000000002202036a278537493c3cdceb9f88c13a15e8354a66a156d27441a199264135aaea8706186f01ffc8540000800000008000000080000000000500000000`

I am trying to calculate the fee of the transaction, but I don't know how to get the value of input `nonWitnessUtxo`s.

```typescript

    const decodedPSBT = bitcoinJS.Psbt.fromHex(psbt)

    let feeCalculator = new BigNumber(0)

    for (const txIn of decodedPSBT.data.inputs) {
      if (txIn.witnessUtxo) {
        feeCalculator = feeCalculator.plus(new BigNumber(txIn.witnessUtxo.value ?? 0))
      } else if (txIn.nonWitnessUtxo) {
        // How to access the value here?
      }
    }

    for (const txOut of decodedPSBT.txOutputs) {
      feeCalculator = feeCalculator.minus(new BigNumber(txOut.value))
    }
```

---

Then I have another question. I would like to check/verify that certain outputs actually belong to the users wallet, meaning that he has control over it. But I can't find the derivation path of the outputs anywhere if I prepare the PSBT like this (obviously):

```
psbt.addOutput({ address: out.recipient, value: parseInt(out.value) })
```

If I use Sparrow for example, the derivation paths are located under `psbt.data.outputs`, which contains an array of "bip32Derivations" with the path. How can I add the derivation path to the outputs like that?

**Comment by junderw** [comment]
1. Use Transaction.fromBuffer to turn it into a Transaction. then grab tx.outs[index].value where index is the psbt.txInputs[i].index. (where i is the input you are parsing)
2. bip32Derivations contains the pubkey of the derived key, the master fingerprint, and the path. You will likely need to get the fingerprint from the user, or if you plan to use the same HD wallet as Sparrow, one look at the psbt will tell you the master fingerprint.
