### ISSUE TITLE
ETA on release with Taproot support

### ISSUE THREAD

**Issue by pajasevi** [bitcoinjs/bitcoinjs-lib#1731]
Hi, I would like to ask what is the ETA on `bitcoin-js` release containing updated `bech32` library with `bech32m` support.

Is it coming before Taproot activation?

Thanks

**Comment by motorina0** [comment]
Hi, I have just open this PR https://github.com/bitcoinjs/bitcoinjs-lib/pull/1742 with the first version of p2tr (not 100% complete)

**Comment by pajasevi** [comment]
@motorina0 Thank you very much for your work 👍 

I will close this now as the release looks to be coming in a few days hopefully.
