### ISSUE TITLE
Is there a way to make Psbt.combine just *ignore* extra signatures?

### ISSUE THREAD

**Issue by ztane** [bitcoinjs/bitcoinjs-lib#1741]
We're doing decentralized k-of-n multisig where all automated nodes try to verify and sign the Psbt simultaneously and broadcast them to other nodes... this works nicely with Psbt.combine, other than right now if we already have more than k one-signed Psbts, we cannot use all of them, because of having *too many* signatures? Is there a way to mitigate this?

**Comment by junderw** [comment]
No. PSBT does not and should not care about what data you decide to put into it.

Your app should be concerned with that.

If I already have k signatures, just don't combine anymore PSBTs.

If you need to combine other data, combine, then delete one of the signatures from partialSig using .pop() etc.
