### ISSUE TITLE
Cannot read property 'fromWIF' of undefined error

### ISSUE THREAD

**Issue by arlong87** [bitcoinjs/bitcoinjs-lib#1748]
Im trying create and sign a raw transaction with bitcoinjs-lib.

```
const assert = require('assert');
const ecpair = require('ecpair');
const bitcoin = require('bitcoinjs-lib');
var keys    =new bitcoin.ecpair.fromWIF('cMvPQZiG5mLARSjxbBwMxKwzhTHaxgpTsXB6ymx7SGAeYUqF8HAT', bitcoin.networks.testnet);
```

this is my code and i get error "Cannot read property 'fromWIF' of undefined error" message. i think i am making a mistake while adding the libraries. bitcoinjs-lib version is 6 and using nodejs. thank you.

**Comment by junderw** [comment]
Use `npm install ecpair` or `npm install bip32`

bitcoinjs-lib v6 does not have any public key cryptography.

**Comment by junderw** [comment]
You require `ecpair` but then use `bitcoin.ecpair` which doesn't exist.

fromWIF is a static method, you don't need `new`

**Comment by arlong87** [comment]
i install and import ecpair and bip32 still error.
const assert = require('assert');
const ECPair = require('ecpair');
const bip32 = require('bip32');

const bitcoin = require('bitcoinjs-lib');

const network = bitcoin.networks.testnet;

const keyPair = bitcoin.ECPair.fromWIF('cMvPQZiG5mLARSjxbBwMxKwzhTHaxgpTsXB6ymx7SGAeYUqF8HAT', network)
const keyPair = ECPair.fromWIF('cMvPQZiG5mLARSjxbBwMxKwzhTHaxgpTsXB6ymx7SGAeYUqF8HAT', network) //same error

**Comment by junderw** [comment]
That's not valid JavaScript. These problems you are having are irrelevant to this library and born of your lack of understanding of JavaScript.

`bitcoin` does not contain a member `ECPair` so `bitcoin.ECPair` is `undefined`... calling any member on undefined will get you an error of "Cannot read property xxx of undefined"

The next thing you would look at: "What is inside this variable?"

Write some `console.log` statements like `console.log(ECPair)`

You will see:

```js
{
  networks: {
    bitcoin: {
      messagePrefix: '\x18Bitcoin Signed Message:\n',
      bech32: 'bc',
      bip32: [Object],
      pubKeyHash: 0,
      scriptHash: 5,
      wif: 128
    },
    testnet: {
      messagePrefix: '\x18Bitcoin Signed Message:\n',
      bech32: 'tb',
      bip32: [Object],
      pubKeyHash: 111,
      scriptHash: 196,
      wif: 239
    }
  },
  ECPair: [class ECPair]
}
```

What does that tell you? 

The thing you are calling ECPair is not actually the ECPair class. it's an object that contains the ECPair class and some networks.

`const { ECPair } = require('ecpair');` or `const ECPair = require('ecpair').ECPair;` would work.

**Comment by junderw** [comment]
From https://github.com/bitcoinjs/ecpair#example

```ts
import { Signer, SignerAsync, ECPairInterface, ECPair } from 'ecpair';
```

Which translated into `require` semantics would be:

```js
const { ECPair } = require('ecpair');
```

Since all other members besides ECPair in the example are TypeScript types and interfaces.

**Comment by arlong87** [comment]
thanks its work!
