### ISSUE TITLE
Can I build My own cryptocurrency on this source 

### ISSUE THREAD

**Issue by dungdamquoc1993** [bitcoinjs/bitcoinjs-lib#1749]
Hi, I just don't know how to generate a wallet how mining working and how to send a transaction. it just so unimplicity

**Comment by miketery** [comment]
You could interface with that implements the same interface for transactions. This software provides client / wallet functionality (e.g. creating a wallet, and creating transactions). The blockchain that you interface with can be the real bitcoin, or your own fork, that's up to you.

There's many things this library doesn't implement (e.g. mining, block validation).

Read mastering bitcoin to understand more.

Should close this issue as not relevant.
