### ISSUE TITLE
TypeError: ECPair.makeRandom is not a function

### ISSUE THREAD

**Issue by moblizeitllc** [bitcoinjs/bitcoinjs-lib#1751]
i am using typescript and code looks like below:
const ECPair = require('ecpair');
      

const keyPair = ECPair.makeRandom();
          const { address } = bitcoin.payments.p2pkh({ pubkey: keyPair.publicKey });
          functions.logger.log("DIVI wallet address is:", address)

the package.json has
 "dependencies": {
    "basic-auth": "^2.0.1",
    "bitcoinjs-lib": "^6.0.0",
    "ecpair": "^1.0.1",
    "firebase-admin": "^9.8.0",
    "firebase-functions": "^3.14.1",
    "joi": "^14.3.1"
  },

The error i see is

TypeError: ECPair.makeRandom is not a function

**Comment by junderw** [comment]
```js
const ECPair = require('ecpair');
const keyPair = ECPair.ECPair.makeRandom();
// or
const { ECPair } = require('ecpair');
const keyPair = ECPair.makeRandom();
```
