### ISSUE TITLE
How can I define the transaction fee on PSBT transaction?

### ISSUE THREAD

**Issue by kelvinwong116** [bitcoinjs/bitcoinjs-lib#1756]
Hello all, I am trying to create a psbt transaction and It seems work. However, I cannot define a custom transaction fee in this case. How can I define the transaction fee on PSBT transaction?

test result: https://live.blockcypher.com/btc-testnet/tx/435f1365b633ac61cef317bdd112aee6bf0dc5c159c971fd0be0bf6bca3ecf3e/

It created 0.00009679 BTC transaction fee.

````
const bitcoin = require("bitcoinjs-lib");
const { ECPair } = require("ecpair");

const testnet = bitcoin.networks.testnet;

const senderAddress = "mojjTfQ9xHmVC2So6T5gdcjByrwRqvPnTE";
const privateKey = "cMvSMgMLHH1GzKdaDNW52UZ3z7AcQ3jEQ1noc2QrYYA61AHUJcrA";

const recipientAddress = "mzkGaYD6iiTsdaEx99avGvCJTHq8B4Azd2";

const sendAmount = 321;

const psbt = new bitcoin.Psbt({ network: testnet });

let txid = "814897d7506345b3d68bc0c10f5867a199c33cda9af10d634a57bcaecedc9e4c"; // Get from API

let rawTx =
  "020000000001015df950ad7bd9fcbeab0e627de182e2843dc7189857a1688725f5299201f2413e0100000000feffffff0210270000000000001976a9145a2bb3413cdebf9ea10f2420ac34f6af63f3156188acd59b17ba00000000160014793342bf134cea3dc716b15023c0e5fe3e5fccaa024730440220511ed34d0f94b65ca0246d357010cdbaf894bd7b0b2255967e0c8b1dd4c7d26c0220019810146d6f54e7c3cd09836d8bbdf54441b3614a78d62dbf63ae0d4a2ccceb012103429c0684a03ea44c84e0f3060feb20e059ec6f1a33693593688491077a523927bb212000";

let index = 0; // Get from API

psbt.addInput({
  hash: txid,
  index: index,
  nonWitnessUtxo: Buffer.from(rawTx, "hex"),
});

psbt.addOutput({
  address: recipientAddress,
  value: sendAmount,
});

let keypair = ECPair.fromWIF(privateKey, testnet);

psbt.signInput(0, keypair);

psbt.finalizeAllInputs();

let transactionHex = psbt.extractTransaction().toHex();

console.log({ transactionHex });
````

**Comment by junderw** [comment]
Fees in Bitcoin are implicit.

`sumOfInputValues - sumOfOutputValues === fee`

If you only have 1 output (like your example) you raise the fee by lowering `sendAmount` and you lower the fee by raising `sendAmount`

**Comment by junderw** [comment]
In the transaction you posted the link to:

your input total was 0.0001 BTC
your output total was 0.00000321 BTC

0.00010000
-
0.00000321
=
your fee of 0.00009679 BTC

The way you prevent paying lots of fees: You add a new output that sends to your own address. and you modify the amount of that output to modify the fee.

Example: Look at this transaction.

https://live.blockcypher.com/btc-testnet/tx/eb0fdf60ed25a30f6d62cd2b95d722441413e0669ec1d66dff01d0cb73ca30d6/

It has 2 outputs, one is 0.00031 BTC and one is 0.00724653 BTC.

You can usually tell by looking at the amount which one was modified to fine-tune the fee. (the later one since the numbers are more random)

Think of it like I spend a $5 bill, then I give you a $1 dollar bill and put 4 $1 bills back in my pocket.

Your transaction is like saying "I take $5 out of my pocket, pay you $1, then drop the $4 on the ground so the park manager can come pick it up and keep it"

**Comment by kelvinwong116** [comment]
> In the transaction you posted the link to:
> 
> your input total was 0.0001 BTC your output total was 0.00000321 BTC
> 
> ```
> 0.00010000
> -
> 0.00000321
> =
> your fee of 0.00009679 BTC
> ```
> 
> The way you prevent paying lots of fees: You add a new output that sends to your own address. and you modify the amount of that output to modify the fee.
> 
> Example: Look at this transaction.
> 
> https://live.blockcypher.com/btc-testnet/tx/eb0fdf60ed25a30f6d62cd2b95d722441413e0669ec1d66dff01d0cb73ca30d6/
> 
> It has 2 outputs, one is 0.00031 BTC and one is 0.00724653 BTC.
> 
> You can usually tell by looking at the amount which one was modified to fine-tune the fee. (the later one since the numbers are more random)
> 
> Think of it like I spend a $5 bill, then I give you a $1 dollar bill and put 4 $1 bills back in my pocket.
> 
> Your transaction is like saying "I take $5 out of my pocket, pay you $1, then drop the $4 on the ground so the park manager can come pick it up and keep it"


Thank you Jonathan!

I just modify my code and using another address. I am trying to set the remain amount on output 2.
But It return an error **Outputs are spending more than Inputs**. I think it is because I used transaction amount on `nonWitnessUtxo`. How can I get the address balance and the code can know the amount is correct? Thank you!

Here is modified code:
`const bitcoin = require("bitcoinjs-lib");
const { ECPair } = require("ecpair");

const testnet = bitcoin.networks.testnet;

const senderAddress = "n1K38U5szF5C4qDLX5PEcoWWvFs2CXMkAe";
const privateKey = "cPfuLikejKpMkmFP9rKZCcAsg2NoWcvGtsSvmAfdmeuv9peh79z6";

const recipientAddress = "mojjTfQ9xHmVC2So6T5gdcjByrwRqvPnTE";
const sendAmount = 123;
const fee = 456;
const balance = 255490;

const psbt = new bitcoin.Psbt({ network: testnet });

let txid = "32e9e2e01f408848193779d58bee6f5370c5f2b078ddf3e684b04303cf51175a"; // Get from API, amount: 78000
let rawTx =
  "02000000000101211a61dc356420b336fb5ae621fd2d3a90f574f53ee4d8b85b98cbdc8916bdd40000000000feffffff02b0300100000000001976a914d9218f59385bd8798c212b5e080a642d8732a02888ac861daab900000000160014fa861050afb9c002cb27a08be6468fd70b3276c00247304402200cd3d054c31aff1fc1eca66676090cc326e1640afc460cb392e7decde033c260022044d5de848ce10ac058f372c69146f9c6031d30f5474410189371f7a4891f38e40121038dc94234f950aa73a1ddab2f586a5551423d94fe131fd9b3320b6b7ae7d94524e2212000";
// From https://blockstream.info/testnet/api/tx/32e9e2e01f408848193779d58bee6f5370c5f2b078ddf3e684b04303cf51175a/hex
let index = 0; // Get from API

psbt.addInput({
  hash: txid,
  index: index,
  nonWitnessUtxo: Buffer.from(rawTx, "hex"),
});

// Output 1
psbt.addOutput({
  address: recipientAddress,
  value: sendAmount,
});
// Output 2 (Send back remain bitcoin to own address for transaction fee)
psbt.addOutput({
  address: senderAddress,
  value: balance - sendAmount - fee,
});

let keypair = ECPair.fromWIF(privateKey, testnet);

psbt.signInput(0, keypair);
psbt.signInput(1, keypair); // For Output 2

psbt.finalizeAllInputs();

let transactionHex = psbt.extractTransaction().toHex();

console.log({ transactionHex });
`

And here is the error:
`Error: Outputs are spending more than Inputs`

**Comment by junderw** [comment]
> `// Get from API, amount: 78000`

If the 1 input you add is worth 78000 then you must do:
`value: 78000 - sendAmount - fee,`

You should subtract from the total value of all the inputs in your current building transaction. NOT every input you own and COULD use, but are not using right now (aka your entire balance)

**Comment by kelvinwong116** [comment]
> > `// Get from API, amount: 78000`
> 
> If the 1 input you add is worth 78000 then you must do: `value: 78000 - sendAmount - fee,`
> 
> You should subtract from the total value of all the inputs in your current building transaction. NOT every input you own and COULD use, but are not using right now (aka your entire balance)

May I know is it a correct correct approach of subtracting transactions (even they are from same address)? Thank you!
https://live.blockcypher.com/btc-testnet/tx/7a997d19233a0731eafea43cf15732713c06a958e354223ec340df9d1f1efb7a/

**Comment by junderw** [comment]
I don't understand your question.

**Comment by kelvinwong116** [comment]
> I don't understand your question.

![image](https://user-images.githubusercontent.com/88305443/144154110-367939ea-38e7-4bdb-8e72-6db90d9bc9a4.png)

Sorry for my bad presentation.

In the above case, I have 2 inputs from same testnet address(n1K38U5szF5C4qDLX5PEcoWWvFs2CXMkAe).

The amounts of these inputs are from 2 transaction hashes:
input1 (0.00078 BTC) > (67e09dc0f50009d4b1ed210dd88d8a03b1f9964653594adce3b850ea6f3be577)
input2 (0.001 BTC) > (20e9269fd37f20f81567e33e5b13e34fd905d9089ce68546d33c8bf40b763436)

==============================================================================

In this case, can we create the transaction by using only 1 input (Amount equals 0.00178 BTC and address is n1K38U5szF5C4qDLX5PEcoWWvFs2CXMkAe)? Thank you!

**Comment by junderw** [comment]
Yes, in this case you can choose to only include input1 and leave input2 alone (do not spend)

In that case you must make your change output (output2) 0.0007749 BTC if you wish to pay the same fee.

**Comment by kelvinwong116** [comment]
Thank for your help Jonathan!

Is my understanding correct?
For creating input:
We use txid to find the unspent amount and get the input value.
If we want to pay an address' total balance, we need to get all txids of that address and create the inputs(the number of the inputs are equal number of transactions of that address).
And we cannot pay the address' total balance by only creating 1 input (If this address contains more than 1 transaction).

**Comment by junderw** [comment]
Yes. You are correct.
