### ISSUE TITLE
Question: Pass string of pubkey instead of ECPair.makerandom

### ISSUE THREAD

**Issue by niteshbalusu11** [bitcoinjs/bitcoinjs-lib#1757]
Hello!

How do we just pass a regular pubkey like this "upub5Eu3qtiZTNzbVR3NwBWafpFHFEhXTiSLAKtnQSz9FoMRMxBc2tk1o6KTcPdZDWBospQmtAvPJGKoA7oKxvwGqytSixaVN5qLqcJmEDygM5y" without using ECPair.random and generate an address from it?

replacing `keyPair.publickey` with a string is causing errors.

`Error: Expected property "pubkey" of type ?isPoint, got String`

```
const bitcoin = require('bitcoinjs-lib');
const {ECPair} = require('ecpair')

const keyPair = ECPair.makeRandom();
const { address } = bitcoin.payments.p2pkh({ pubkey: keyPair.publicKey });
console.log(address)
```

**Comment by niteshbalusu11** [comment]
I tried this as well. and ending up with a type error:

```
pubkey: bip32.fromBase58(xpub).derive(0).derive(1).publicKey,
TypeError: bip32.fromBase58 is not a function
```

```
const bjs = require('bitcoinjs-lib');
const bip32 = require('bip32');

const xpub = 'xpub6CzDCPbtLrrn4VpVbyyQLHbdSMpZoHN4iuW64VswCyEpfjM2mJGdaHJ2DyuZwtst96E16VvcERb8BBeJdHSCVmAq9RhtRQg6eAZFrTKCNqf';

const { address } = bjs.payments.p2pkh({
      pubkey: bip32.fromBase58(xpub).derive(0).derive(1).publicKey,
});

console.log(`the addressString is ${address}`);
```

**Comment by junderw** [comment]
Your code was correct for old versions of bip32.

Be careful with older tutorials based on older versions.
The latest version of bip32 would be:

```js
const bjs = require('bitcoinjs-lib');

// You need to wrap bip32 around a crypto interface
const ecc = require('tiny-secp256k1');
const { BIP32Factory } = require('bip32');
const bip32 = BIP32Factory(ecc);

const xpub = 'xpub6CzDCPbtLrrn4VpVbyyQLHbdSMpZoHN4iuW64VswCyEpfjM2mJGdaHJ2DyuZwtst96E16VvcERb8BBeJdHSCVmAq9RhtRQg6eAZFrTKCNqf';

const { address } = bjs.payments.p2pkh({
      pubkey: bip32.fromBase58(xpub).derive(0).derive(1).publicKey,
});

console.log(`the addressString is ${address}`);
```

**Comment by niteshbalusu11** [comment]
> Your code was correct for old versions of bip32.
> 
> Be careful with older tutorials based on older versions. The latest version of bip32 would be:
> 
> ```js
> const bjs = require('bitcoinjs-lib');
> 
> // You need to wrap bip32 around a crypto interface
> const ecc = require('tiny-secp256k1');
> const { BIP32Factory } = require('bip32');
> const bip32 = BIP32Factory(ecc);
> 
> const xpub = 'xpub6CzDCPbtLrrn4VpVbyyQLHbdSMpZoHN4iuW64VswCyEpfjM2mJGdaHJ2DyuZwtst96E16VvcERb8BBeJdHSCVmAq9RhtRQg6eAZFrTKCNqf';
> 
> const { address } = bjs.payments.p2pkh({
>       pubkey: bip32.fromBase58(xpub).derive(0).derive(1).publicKey,
> });
> 
> console.log(`the addressString is ${address}`);
> ```

Thank you! that worked.

One last question, how do we make derive a new address every single time for receiving funds? this one derives the same address always.

**Comment by niteshbalusu11** [comment]
I suppose just change `derive(1)` to other numbers?

**Comment by junderw** [comment]
Yes. You are correct.

Though, I might add that p2pkh is an old format for addresses which will cost more money in fees to manage.

If you are worried that people might be using older wallet software that can not send to newer address formats, the best option would be a P2SH wrapped P2WPKH.

```js
const bjs = require('bitcoinjs-lib');

// You need to wrap bip32 around a crypto interface
const ecc = require('tiny-secp256k1');
const { BIP32Factory } = require('bip32');
const bip32 = BIP32Factory(ecc);

const xpub = 'xpub6CzDCPbtLrrn4VpVbyyQLHbdSMpZoHN4iuW64VswCyEpfjM2mJGdaHJ2DyuZwtst96E16VvcERb8BBeJdHSCVmAq9RhtRQg6eAZFrTKCNqf';

const { address } = bjs.payments.p2sh({
      redeem: bjs.payments.p2wpkh({
            pubkey: bip32.fromBase58(xpub).derive(0).derive(1).publicKey,
      }),
});

console.log(`the addressString is ${address}`);
```

Also, `bip32.fromBase58(xpub).derive(0)` is an expensive computation, so if you are going to do a loop, you should cache it.

```js
const cache = bip32.fromBase58(xpub).derive(0);
const addresses = [];
for (let i = 0; i < xxxx; i++) {
  const { address } = bjs.payments.p2sh({
      redeem: bjs.payments.p2wpkh({
            pubkey: cache.derive(i).publicKey,
      }),
  });
  addresses.push(address);
}
```

**Comment by niteshbalusu11** [comment]
> Yes. You are correct.
> 
> Though, I might add that p2pkh is an old format for addresses which will cost more money in fees to manage.
> 
> If you are worried that people might be using older wallet software that can not send to newer address formats, the best option would be a P2SH wrapped P2WPKH.
> 
> ```js
> const bjs = require('bitcoinjs-lib');
> 
> // You need to wrap bip32 around a crypto interface
> const ecc = require('tiny-secp256k1');
> const { BIP32Factory } = require('bip32');
> const bip32 = BIP32Factory(ecc);
> 
> const xpub = 'xpub6CzDCPbtLrrn4VpVbyyQLHbdSMpZoHN4iuW64VswCyEpfjM2mJGdaHJ2DyuZwtst96E16VvcERb8BBeJdHSCVmAq9RhtRQg6eAZFrTKCNqf';
> 
> const { address } = bjs.payments.p2sh({
>       redeem: bjs.payments.p2wpkh({
>             pubkey: bip32.fromBase58(xpub).derive(0).derive(1).publicKey,
>       }),
> });
> 
> console.log(`the addressString is ${address}`);
> ```
> 
> Also, `bip32.fromBase58(xpub).derive(0)` is an expensive computation, so if you are going to do a loop, you should cache it.
> 
> ```js
> const cache = bip32.fromBase58(xpub).derive(0);
> const addresses = [];
> for (let i = 0; i < xxxx; i++) {
>   const { address } = bjs.payments.p2sh({
>       redeem: bjs.payments.p2wpkh({
>             pubkey: cache.derive(i).publicKey,
>       }),
>   });
>   addresses.push(address);
> }
> ```

Thank you for that. Is there any thumb rule as to the maximum number one can go for generating addresses? Like 1500 or 2000 etc. If someone has to ever do a rescan of the wallet on the blockchain, would that cause issues?

**Comment by junderw** [comment]
> Is there any thumb rule as to the maximum number one can go for generating addresses?

Not really. It depends on what your constraints are. The maximum index for bip32 is 2147483647... so you can only generate 2147483648 addresses max per `derive()` layer.

> If someone has to ever do a rescan of the wallet on the blockchain, would that cause issues?

"Cause issues" depends on whether a heavy load will cause issues for you. Bitcoin Core doesn't crash easily. But it will take a while if you give it 500 billion addresses to rescan. I work for an exchange, and we've never had Bitcoin Core crash on us.

> Also, is there a way to detect the type of master pubkey entered and generate the address accordingly

There is no standard. However, a wallet called "Electrum" has created a method to tell the difference. [Read about it here](https://electrum.readthedocs.io/en/latest/xpub_version_bytes.html#version-bytes-for-bip32-extended-public-and-private-keys). However, since this is not standard practice, some wallets support it, and some don't. Since this library strives to be based on standards agreed upon by the entire community, we do not implement this. You will need to bs58check decode, replace the first 4 bytes (version) with the xpub version bytes, then re-encode using bs58check.

**Comment by niteshbalusu11** [comment]
Thanks a lot for answering all my questions, I really appreciate it.

**Comment by niteshbalusu11** [comment]
> There is no standard. However, a wallet called "Electrum" has created a method to tell the difference. [Read about it here](https://electrum.readthedocs.io/en/latest/xpub_version_bytes.html#version-bytes-for-bip32-extended-public-and-private-keys). However, since this is not standard practice, some wallets support it, and some don't. Since this library strives to be based on standards agreed upon by the entire community, we do not implement this. You will need to bs58check decode, replace the first 4 bytes (version) with the xpub version bytes, then re-encode using bs58check.

Hey! 
I have seen one of your replies from another older issue, the right way to do this is something like this? Which is basically convert everything to xpub before generating an address? 

https://github.com/bitcoinjs/bitcoinjs-lib/issues/1334#issuecomment-578009074

**Comment by junderw** [comment]
That is one way to do it, yes.

**Comment by niteshbalusu11** [comment]
Thanks!

**Comment by niteshbalusu11** [comment]
> That is one way to do it, yes.

Hey Jonathan!

I have issues with derivation paths, I am doing some testing with LND onchain wallets. I have also added the code I have written, it does generate addresses but I think they are not pointing to the right path. Can you help with how to set the right path?

**Some addresses generated by LND**
```
lncli newaddress p2wkh
{
    "address": "bcrt1qkdkckx0526q5zm9990fl5csgznsa30qhj05fu4"
}
bash-5.1$ lncli newaddress np2wkh
{
    "address": "2N8tQnEmoVd5gpKBPiQucefEdvq2BrH3jdV"
}
```


**Wallet Public Keys from LND**
```
     {
            "name": "default",
            "address_type": "HYBRID_NESTED_WITNESS_PUBKEY_HASH",
            "extended_public_key": "upub5EVAe3vZSqnmCWoHMiycbvUUvGqfB9A8C9K4kWQ22TMZEavtisJibyqgoHK6hTvPCPeSCcuYjnSsR8ejWuvtm4KQvVyX9NomFmUDwpAkdtF",
            "master_key_fingerprint": null,
            "derivation_path": "m/49'/0'/0'",
            "external_key_count": 0,
            "internal_key_count": 0,
            "watch_only": false
        },
        {
            "name": "default",
            "address_type": "WITNESS_PUBKEY_HASH",
            "extended_public_key": "vpub5Z61xkzysYw56vFAwh242W621gwGvD5L4dY5Y2FSH79rVR6LDK1x47VPPGJYvCx6sp8zg5VygPS4cznLfiq6VxE2Pgtfi3vnwcrsSMA3D1R",
            "master_key_fingerprint": null,
            "derivation_path": "m/84'/0'/0'",
            "external_key_count": 27,
            "internal_key_count": 64,
            "watch_only": false
        },
        {
            "name": "default",
            "address_type": "WITNESS_PUBKEY_HASH",
            "extended_public_key": "tpubDDmuoBFm5xfkNqRfhAoryJviPuBmSNqW4SSoXGzAg8NoEQqNuUdeoSYWutxDfZckmV56KEvgvpqVbjDc4Rqb7tjyb5jXjFd3P4vPBRJFwZJ",
            "master_key_fingerprint": null,
            "derivation_path": "m/1017'/1'/0'",
            "external_key_count": 74,
            "internal_key_count": 0,
            "watch_only": false
        },

```


**My Code**
```
  const ypub = "upub5EVAe3vZSqnmCWoHMiycbvUUvGqfB9A8C9K4kWQ22TMZEavtisJibyqgoHK6hTvPCPeSCcuYjnSsR8ejWuvtm4KQvVyX9NomFmUDwpAkdtF";
  const address1 = getYpubAddress(ypub);

  console.log(`the addressString is ${address1}`);

  function getYpubAddress(ypub, index = 0, isChange = false, network = bjs.networks.regtest) {
    const xpub = anypubToXpub(ypub);
    const address = bjs.payments.p2sh({
      redeem: bjs.payments.p2wpkh({
        pubkey: bip32
          .fromBase58(xpub)
          .derive(isChange ? 1 : 0)
          .derive(index).publicKey,
        network,
      }),
      network,
    }).address;

    return address;
  }
  function anypubToXpub(xyzpub) {
    let data = b58.decode(xyzpub);
    data = data.slice(4);
    data = Buffer.concat([Buffer.from("0488b21e", "hex"), data]);
    return b58.encode(data);
  }
```

**Comment by junderw** [comment]
I don't understand your question, but it is irrelevant to this library, so I would recommend asking on Bitcoin stack exchange https://bitcoin.stackexchange.com/

**Comment by niteshbalusu11** [comment]
> I don't understand your question, but it is irrelevant to this library, so I would recommend asking on Bitcoin stack exchange https://bitcoin.stackexchange.com/

Sorry for the confusion, I updated my comment, guess my question is to able to just generate a p2wkh address.

**Comment by junderw** [comment]
Remove the p2sh wrapper.

**Comment by niteshbalusu11** [comment]
Thank you sir!
