### ISSUE TITLE
bitcoinCash  cashaddr

### ISSUE THREAD

**Issue by regazeri** [bitcoinjs/bitcoinjs-lib#1763]
Hi 
I use this lib to create random addresses for `bch` 
    const address = address.toBase58Check(.., ..);
    but it's legacy address and I need cashaddr  , does this library support it?
    thanks in advance

**Comment by junderw** [comment]
Unfortunately we only support Bitcoin.

For BCH I have used https://www.npmjs.com/package/cashaddrjs before and it works very well. I highly recommend it.
