### ISSUE TITLE
Testnet transaction w/o regutils?

### ISSUE THREAD

**Issue by mbarbas11** [bitcoinjs/bitcoinjs-lib#1764]
How do I do a transaction with testnet and not regutiils? Sorry if I'm just not understanding it correctly. Thanks.

**Comment by mbarbas11** [comment]
All the broadcast transaction examples use getInputData which references the RegUtils. How can I work around it for testnet?

**Comment by junderw** [comment]
regutils is just a library for interacting with regtest-server.

the inputData info is explained thoroughly in the test's comments.

**Comment by mbarbas11** [comment]
Thanks Jonathan. Sorry I was very new to this. I get it now, referenced through previous issues to get an understanding on how the code works. You've been a great help.
