### ISSUE TITLE
[Request] Add the examples with OP_CHECKSEQUENCEVERIFY for taproot.

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1773]
Could you please add examples of taproot for the examples with OP_CHECKSEQUENCEVERIFY?

Thanks.

**Comment by motorina0** [comment]
I will try to add some examples next week as part of the integration tests for this PR: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1742

**Comment by motorina0** [comment]
@educob you can find a `OP_CHECKSEQUENCEVERIFY` example (`taproot.spec.ts`) on the branch for this PR: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1742
