### ISSUE TITLE
Issue following the examples in a react app

### ISSUE THREAD

**Issue by birimbau** [bitcoinjs/bitcoinjs-lib#1777]
Hello,

I'm developing a BTC wallet using bitcoinjs-lib. Following the examples this peace of code breaks my FE: 

``` 
import * as assert from 'assert';
import BIP32Factory from 'bip32';
import * as ecc from 'tiny-secp256k1';

const bip32 = BIP32Factory(ecc);

```

I receive the following error in the console: 

![image](https://user-images.githubusercontent.com/7563100/156879371-3ad520cb-b675-49f0-b0c8-c6c602c833bd.png)

Please let me know if you need more information, I just tried to add the minimum necessary info in order to avoid unecessary noise.

Thanks in advance.

**Comment by junderw** [comment]
Versions of:

- webpack
- react (and any react plugins / react related things)
- tiny-secp256k1

**Comment by junderw** [comment]
If you are using React Native, the runtime has poor WASM support.

tiny-secp256k1 v2 uses WASM.

**Comment by birimbau** [comment]
@junderw 
Im using this in the browser in a simples Create React App application.

The versions I'm using:

"tiny-secp256k1": "^2.2.1",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-hook-form": "^7.27.1",
"react-router-dom": "^6.2.1",
"react-scripts": "5.0.0",
webpack: 5.69.1
webpack-cli: 4.9.2
webpack-dev-server 4.7.4

Im also using Craco to overrride the default React CRA webpack configs whith the following configuration in `craco.config.js`: 

``` 
const webpack = require("webpack");

module.exports = {
    webpack: {
        configure: {
            resolve: {
                fallback: {
                    process: require.resolve("process/browser"),
                    zlib: require.resolve("browserify-zlib"),
                    stream: require.resolve("stream-browserify"),
                    util: require.resolve("util"),
                    buffer: require.resolve("buffer"),
                    asset: require.resolve("assert")
                },
            },
            plugins: [
                new webpack.ProvidePlugin({
                    Buffer: ["buffer", "Buffer"],
                    process: "process/browser",
                }),
            ],
        },
    },
};
```

**Comment by junderw** [comment]
What browser are you using?

The error is saying that WebAssembly.Module doesn't have `memory` member, which it does.

Maybe your browser is old?

**Comment by birimbau** [comment]
@junderw I'm using Chrome Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by junderw** [comment]
Nah, that's not the problem.

Oh well, I have no clue. All I can say is that this is more of an issue with your react config or something most likely. ([We use webpack and react for our tiny-secp256k1 example site and it works perfectly.](https://github.com/bitcoinjs/tiny-secp256k1/tree/v2.2.1/examples/react-app))

**Comment by junderw** [comment]
Please ask around on React forums / issues.

I'm closing this because it's not an issue with bitcoinjs-lib.

**Comment by junderw** [comment]
I noticed you're not using the webpack WebAssembly features in your config file.

**Comment by junderw** [comment]
```
experiments: {
  asyncWebAssembly: true,
},
```

**Comment by junderw** [comment]
Also, if you do figure it out, please post your solution here in case someone finds this issue.

**Comment by birimbau** [comment]
Found the issue. It seems that webpack v5 doesnt pollyfil by default NodeJs core modules (such as buffer).

**Comment by birimbau** [comment]
Found the issue. It seems that webpack v5 doesnt pollyfil by default NodeJs core modules (such as buffer).

**Comment by suricata3838** [comment]
To see the overview of polyfill due to webpack v5, which is used inside react-script v5, 
I checked this article written by alchemy.
[how-to-polyfill-node-core-modules-in-webpack-5](https://www.alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5)
