### ISSUE TITLE
extract BIP341 interface

### ISSUE THREAD

**Issue by motorina0** [bitcoinjs/bitcoinjs-lib#1780]
Start the conversation about what this interface should contain.

Initially suggested by @tiero here: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1742#issuecomment-1059258075

**Comment by tiero** [comment]
In our LiquidJS fork we have moved all the taproot [utils in a dedicated file](https://github.com/vulpemventures/liquidjs-lib/blob/master/ts_src/bip341.ts)

We are exporting all the function as for now, I guess they can be helpful for developers and the interfaces as well `TaprootLeaf` and `HashTree`
