### ISSUE TITLE
Need help setting up a basic script to generate key and address

### ISSUE THREAD

**Issue by JamesCodes0** [bitcoinjs/bitcoinjs-lib#1783]
Need help setting up a basic script to generate key and address help appreciated. anyone know of a good working recent tutorial or video? would anyone be willing to help a learning dev?

**Comment by junderw** [comment]
```bash
npm install bip32 bitcoinjs-lib bip39 tiny-secp256k1
```

```js
// mnemonics
const bip39 = require('bip39')

// HD keys
const { BIP32Factory } = require('bip32')
const ecc = require('tiny-secp256k1')
const bip32 = BIP32Factory(ecc)

// Address creation
const bitcoin = require('bitcoinjs-lib')

// main function
async function main(args) {
    // example command:
    // node thisScript.js "my mnemonic here with quotes" mySuperStrongPassword
    // or you can leave out the password
    let [ mnemonic, optionalPassword ] = args;
    const network = bitcoin.networks.bitcoin;

    if (!mnemonic) {
        // If no mnemonic generate 12 word mnemonic
        // (use 256 instead of 128 if you want 24 words)
        // THIS IS YOUR PRIVATE KEY
        mnemonic = bip39.generateMnemonic(128);
        console.log('New mnemonic')
        console.log(mnemonic)
    }

    // Validating the mnemonic to make sure it's valid
    if (!bip39.validateMnemonic(mnemonic)) {
        console.error(
            'WARNING: Unable to validate mnemonic, your addresses may be incorrect! ' +
            'This could be due to using an unknown wordlist, and your mnemonic may also be ' +
            'correct. So please proceed with caution only if you 100% sure your mnemonic is correct.'
        );
    }

    // If you don't want to use async/await, bip39.mnemonicToSeedSync can be used
    const seed = await bip39.mnemonicToSeed(mnemonic, optionalPassword);
    const root = bip32.fromSeed(seed, network);

    // BIP84 pw2pkh addresses
    const interim = root.derivePath("m/84'/0'/0'/0")
    const addresses = []
    for (let i = 0; i < 20; i++) {
        const node = interim.derive(i);
        const { address } = bitcoin.payments.p2wpkh({
            pubkey: node.publicKey,
            network,
        })
        addresses.push(address)
    }

    console.log('Your addresses')
    console.log(addresses.join('\n'))
}

// Accept command args, exit process with non-zero if error
main(process.argv.slice(2)).catch(err => {
    console.error(err);
    process.exit(1);
});
```

**Comment by JamesCodes0** [comment]
> ```shell
> npm install bip32 bitcoinjs-lib bip39 tiny-secp256k1
> ```
> 
> ```js
> // mnemonics
> const bip39 = require('bip39')
> 
> // HD keys
> const { BIP32Factory } = require('bip32')
> const ecc = require('tiny-secp256k1')
> const bip32 = BIP32Factory(ecc)
> 
> // Address creation
> const bitcoin = require('bitcoinjs-lib')
> 
> // main function
> async function main(args) {
>     // example command:
>     // node thisScript.js "my mnemonic here with quotes" mySuperStrongPassword
>     // or you can leave out the password
>     let [ mnemonic, optionalPassword ] = args;
>     const network = bitcoin.networks.bitcoin;
> 
>     if (!mnemonic) {
>         // If no mnemonic generate 12 word mnemonic
>         // (use 256 instead of 128 if you want 24 words)
>         // THIS IS YOUR PRIVATE KEY
>         mnemonic = bip39.generateMnemonic(128);
>         console.log('New mnemonic')
>         console.log(mnemonic)
>     }
> 
>     // Validating the mnemonic to make sure it's valid
>     if (!bip39.validateMnemonic(mnemonic)) {
>         console.error(
>             'WARNING: Unable to validate mnemonic, your addresses may be incorrect! ' +
>             'This could be due to using an unknown wordlist, and your mnemonic may also be ' +
>             'correct. So please proceed with caution only if you 100% sure your mnemonic is correct.'
>         );
>     }
> 
>     // If you don't want to use async/await, bip39.mnemonicToSeedSync can be used
>     const seed = await bip39.mnemonicToSeed(mnemonic, optionalPassword);
>     const root = bip32.fromSeed(seed, network);
> 
>     // BIP84 pw2pkh addresses
>     const interim = root.derivePath("m/84'/0'/0'/0")
>     const addresses = []
>     for (let i = 0; i < 20; i++) {
>         const node = interim.derive(i);
>         const { address } = bitcoin.payments.p2wpkh({
>             pubkey: node.publicKey,
>             network,
>         })
>         addresses.push(address)
>     }
> 
>     console.log('Your addresses')
>     console.log(addresses.join('\n'))
> }
> 
> // Accept command args, exit process with non-zero if error
> main(process.argv.slice(2)).catch(err => {
>     console.error(err);
>     process.exit(1);
> });
> ```
I ran npm install bip32 bitcoinjs-lib bip39 tiny-secp256k1
and then opened a node console from my command prompt is this how i can run this script?

**Comment by junderw** [comment]
Paste the javascript contents into a js file named `generate.js` or whatever.

Then run:

`node generate.js` if you want to generate a new phrase AND the keys.

`node generate.js "my mnemonic here with quotes"` with your phrase (generated the first time) and it will always give the same addresses.
