### ISSUE TITLE
Get simnet address from output script 

### ISSUE THREAD

**Issue by steliosrammos** [bitcoinjs/bitcoinjs-lib#1784]
I use the following command to get the`output` addresses from the `output script`: 

```
addresses = Transaction.fromHex(tx).outputs.map(({ script}) => address.fromOutputScript(script, network))
```

It works when the network is `regtest` but it doesn't for `simnet` transactions, for which the `bech32` prefix is `sb1q` instead of `bcrt`. 

How could I make this work for simnet as well?

**Comment by junderw** [comment]
make your own network object.

**Comment by steliosrammos** [comment]
Well, turns out the correct prefix for simnet `bech32` is `sb` and not `sb1q`. With the correct prefix and all other values in the network object equal to regtest, it works!

It's a small addition, may be worth adding this to the lib?

**Comment by junderw** [comment]
PRs are welcome :-D
