### ISSUE TITLE
psbt.fromHex is missing outputs

### ISSUE THREAD

**Issue by barbas-gen** [bitcoinjs/bitcoinjs-lib#1787]
I created a hex of a psbt unsigned in my builder.
`const unsigned_tx = psbt.toHex();`

It returns... 
`Psbt {
  data: Psbt {
    inputs: [ [Object] ],
    outputs: [ [Object], [Object] ],
    globalMap: { unsignedTx: PsbtTransaction {} }
  }
}`

When I recreate that psbt with
`const psbt = bitcoin.Psbt.fromHex(unsigned_tx , { network: TESTNET });`

It returns...
`Psbt {
  data: Psbt {
    inputs: [ [Object] ],
    outputs: [ {}, {} ],
    globalMap: { unsignedTx: PsbtTransaction {} }
  }
}`

How do I recreate the psbt from my builder program correctly?

**Comment by junderw** [comment]
please share an example.

**Comment by barbas-gen** [comment]
Sorry for late resp.

``` javascript
const buildTransaction = async (wallet_data) => {

  const forward_address = "mkHS9ne12qx9pS9VojpwU5xtRd4T7X7ZUt";
  const forward_value = 5000;
  const fee = 300;

  if (wallet_data.balance < forward_value + fee) {
    console.log("\nNot enough funds to complete transaction...");
    return process.exit(1);
  }

  let psbt = new bitcoin.Psbt({ network: TESTNET });

  let utxoValueSum = 0,
    signatures_paths = [],
    inputs = [],
    utxos = wallet_data.utxos;

  for (let x in utxos) {
    if (utxoValueSum >= forward_value + fee) {
      break;
    }
    utxoValueSum += utxos[x].value;
    inputs.push({
      hash: utxos[x].tx_hash,
      index: utxos[x].txix,
      nonWitnessUtxo: Buffer.from(utxos[x].nonWitnessUtxo, "hex"),
    });

    signatures_paths.push(utxos[x].derivationPath);
  }

  inputs.forEach((input) => {
    psbt.addInput(input);
  });

  psbt
    .addOutput({
      address: forward_address,
      value: forward_value,
    })
    .addOutput({
      address: wallet_data.change,
      value: utxoValueSum - (forward_value - fee),
    });

  const unsigned_tx = psbt.toHex();
  console.log(unsigned_tx);

  const unsigned_tx_data = { tx: unsigned_tx, paths: signatures_paths };

  fs.writeFileSync(
    "./database/unsigned_tx.json",
    JSON.stringify(unsigned_tx_data)
  );
};
```

Here I gather all necessary inputs and outputs for the current transaction. The psbt created is turned to hex. The psbt looks like this...
`Psbt { data: Psbt { inputs: [ [Object] ], outputs: [ [Object], [Object] ], globalMap: { unsignedTx: PsbtTransaction {} } } }`
I then write that to a json file "unsigned_tx".

In another file where the transaction will then be signed externally, I read the value of the hex and display it:

``` javascript
const signTx = async () => {
  //regen psbt from hex
  let psbt = bitcoin.Psbt.fromHex(transaction_data.tx, { network: TESTNET });
  console.log(psbt);
  //signing, etc....
}
```

When printing the psbt, the result is,
`Psbt { data: Psbt { inputs: [ [Object] ], outputs: [ {}, {} ], globalMap: { unsignedTx: PsbtTransaction {} } } }`

I am not sure where the other data is going. I checked the hex strings and they are the same. Shouldnt the values of psbt be the same if its the same hex?

**Comment by junderw** [comment]
I don't understand your problem... but then I think I finally understand.

Are you trying to say `[Object]` has data but `{}` does not?

This is not true. `[Object]` is just a way that console output decides to show `{}` under certain conditions in JavaScript.

If you `.toHex()` one and the other and they are the same, the same data is contained.

---

Also, when someone asks for an example, they are not asking to see your code. They are asking to see a piece of code they can run to verify your issue.

If I don't have `wallet_data` I can not verify your issue.

If your issue is not the `[Object]` vs `{}` thing, then please give me code I can run to verify the issue.

**Comment by barbas-gen** [comment]
My issue was what you said. I was not aware that `{}` is shown under certain conditions. I was attempting to sign a transaction externally and was running into errors, so when I printed out the psbt to make sure it was being created the same way, I saw that `{}` and figured it was empty and that the psbt was the main issue. I was wrong. Everything is good now, thanks.
