### ISSUE TITLE
Signing a multisig transaction using a BIP39 seed phrases and derivation path

### ISSUE THREAD

**Issue by dykstranet** [bitcoinjs/bitcoinjs-lib#1789]
I'm looking for an example to do this.
Here is my code so far
```js
import * as bitcoin from 'bitcoinjs-lib'
import * as bip39 from 'bip39'
import { BIP32Factory } from 'bip32'
import * as ecc from 'tiny-secp256k1'

const bip32 = BIP32Factory(ecc)
const transactionBase64 = "base64stuff"
const mnemonic = "abort abort"
const seed = bip39.mnemonicToSeedSync(mnemonic)
const node = bip32.fromSeed(seed)
let psbt = bitcoin.Psbt.fromBase64(transactionBase64)

console.log("Before:")
// console.log(psbt.toBase64())
console.log(psbt.txInputs)
console.log(psbt.txOutputs)

const masterFingerprint = node.fingerprint
const path = "m/48h/1h/0h/2h"
const childNode = node.derivePath(path)
const pubkey = childNode.publicKey
const updateData = {
    bip32Derivation: [
        {
            masterFingerprint,
            path,
            pubkey,
        }
    ],
}
psbt = psbt.updateInput(0, updateData)
// psbt.signAllInputs(node)
psbt.signInput(0, node)
console.log("After:")
console.log(psbt.toBase64())
```

But I got this error:
```
TypeError: Expected BIP32Path, got String "m/48h/1h/0h/2h"
```

Any help would be appreciated!

See also https://github.com/btcguide/btcguide.github.io/issues/106.

**Comment by junderw** [comment]
Replace `h` with `'`

**Comment by dykstranet** [comment]
@junderw thank you for the answer. Replacing `h` with `'` solved that particular error message. But I encountered another error message:
```
Error: Can not sign for this input with the key xxx
```
The psbt base64-encoded transaction was generated by Specter desktop, which has a multi-sig wallet, where one of the keys is already specified in the code above.

Do you have a link to an example code that solves my particular use case?

**Comment by junderw** [comment]
You are trying to sign, which means you are writing the Signer role code as per BIP174.
The Creator role (which is Spector) should be including the `bip32Derivation` data.

Why are you trying to add it?

Your signing code has no idea which path it uses to sign, so why are you hard-coding it? (You are only giving the path down to the Script level as per BIP48, as well.)

In general, for an HD based multisig wallet where the Creator includes all `bip32Derivation` data properly, all you need to do is pass `node` (the root key) to `psbt.signAllInputsHD(node)`

**Comment by dykstranet** [comment]
Thanks for your reply. I was not aware that Specter already includes the `bip32Derivation` in the PSBT file. 

I removed `psbt = psbt.updateInput(0, updateData)`.

I added ` psbt.signAllInputs(node)`.

But unfortunately I have another error than I cannot figure out. 

```
/home/user1/code/bitcoin/js_signer/node_modules/bitcoinjs-lib/src/psbt.js:479
      throw new Error('No inputs were signed');
            ^

Error: No inputs were signed
    at Psbt.signAllInputs (/home/user1/code/bitcoin/js_signer/node_modules/bitcoinjs-lib/src/psbt.js:479:13)
    at file:///home/user1/code/bitcoin/js_signer/signer.js:37:6
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

My intention is use seed words as cold wallet storage, and sign PSBTs with those words as input (on an offline computer)

I want to keep cold storage cold instead of entering into Electrum or some such. 

Hopefully I'm on the right track. If you know a better way, I'm open to try.

Thanks for your input and help.

**Comment by junderw** [comment]
Since you won't be signing with your root node, you need to use `signAllInputsHD`

**Comment by dykstranet** [comment]
That's the ticket! Thanks for your speedy reply. 

Here is the code that worked:
```
import * as bitcoin from 'bitcoinjs-lib'
import * as bip39 from 'bip39'
import { BIP32Factory } from 'bip32'
import * as ecc from 'tiny-secp256k1'

const bip32 = BIP32Factory(ecc)

const transactionBase64 = "YOURBASE64PSBT"
const mnemonic = "abort ...YOUR WORDS ... abort"
const seed = bip39.mnemonicToSeedSync(mnemonic)
const node = bip32.fromSeed(seed)
const psbt = bitcoin.Psbt.fromBase64(transactionBase64)

console.log("Master fingerprint:", node.fingerprint.toString("hex"))
//console.log(psbt.txInputs)
//console.log(psbt.txOutputs)
psbt.signAllInputsHD(node)
console.log("Output:")
console.log(psbt.toBase64())
```
Thanks a million!
