### ISSUE TITLE
Can somebody help me to understand witnessUtxo?

### ISSUE THREAD

**Issue by masanaka** [bitcoinjs/bitcoinjs-lib#1793]
I have a testnet address 2N6wWN22BV8Gfd26VVt8f6K9PuqFNFh2zQa, and with a tx c60de52f8ace31ed00c99a5e388329d4efbc5e4459fe6c29dd4727a627c7a368.
I think I should follow the sample 'can create (and broadcast via 3PBP) a Transaction, w/ a P2SH(P2WPKH) input' in https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.spec.ts to create a tx.
But when I read getInputData function I don't know how to handle with witnessUtxo because the regtestUtils.fetch return 502 Bad Gateway error. So I don't know what is utx.outs looks like.
Can somebody help me out?

**Comment by junderw** [comment]
As it says in the comment: `{ script: Buffer; value: Satoshis; }`

script Buffer is the script of the output you are spending.

value is the number of satoshis the output you are spending is worth. 1 BTC is 1e8 satoshis.

**Comment by junderw** [comment]
For your testnet example:

```js
{
  hash: 'c60de52f8ace31ed00c99a5e388329d4efbc5e4459fe6c29dd4727a627c7a368',
  index: 1,
  witnessUtxo: {
    script: Buffer.from('a9149637f14e24555fb99c23d43c5c982ad35527df2187', 'hex'),
    value: 1605429,
  },
}
```

**Comment by junderw** [comment]
Also, I fixed the regtest integration server. It should work now.

**Comment by masanaka** [comment]
@junderw 
Thanks a lot! Thanks a million!
I successfully created the transaction and broadcasted it.

**Comment by brinzi** [comment]
Does the `value` need to match the exact satoshi's locked in that UTXo?
