### ISSUE TITLE
P2PKH to bech32

### ISSUE THREAD

**Issue by random9brat** [bitcoinjs/bitcoinjs-lib#1794]
Sry if this is a dumb questions. But as title says. 

I have for example 1LKp8CTu2b4VDvybY9iMn3DoV1cm6ZLsrR address created from bitcoinjs-lib/coinjs-lib/bip39 and i want to convert it to bech32?

How can i do it? Thanks for the responses in advance <3

**Comment by junderw** [comment]
You should avoid doing this.

Taking a hash value from one address type and placing it into another format is the quickest way to get coins stuck in a black hole.

If the hash is of an uncompressed public key, you will be creating an invalid output by using that hash as a P2WPKH address.

This is dangerous and should not be attempted.

The opposite (bech32 P2WPKH to P2PKH) is safe.

**Comment by random9brat** [comment]
Thanks, I will look to create directly bech32 from the lib here... Im kinda struggling to create a simple bech32 public address output

**Comment by motorina0** [comment]
@random9brat you might want to try this UI build on top of `bitcoinjs-lib` (for learning purposes only)
Just go to the `Payments` tab here: https://bitcoincore.tech/apps/bitcoinjs-ui/index.html
