### ISSUE TITLE
Error: Inconsistent redeemScript ? How to sign this multiSig transcation ?

### ISSUE THREAD

**Issue by stefaniepei** [bitcoinjs/bitcoinjs-lib#1797]
```
const data = {
    "btcVinBOList": [{
            "address": "2N4o19RPamhpKbHz55ctmfN8Ybb79jMSppD",
            "addressType": "p2sh",
            "amount": "0.000874",
            "hex": "0200000001c43cda61a5171da48c1fecd44860715a25975cb7994e8409e6c5955685bff9e600000000d9004730440220337d0ca6d4529acba65424763c6a4dfe43cfb63884294a1e2c7eb0a241a6d716022007eae7a63ddeffda1c83c6706280fc3fc57e643580466abb7d8df4ed9218ec650147304402204cf15f6f323d477f55a97b4ac328d11e2159c2de832daeda5ab26ac7ff21a0cb0220287ebf263a945cfb1fb59ba53f35d160fbaf03574d8f456d0e4b2e1d8c8253300147522103a22f646f375f7b4da865643e9c5bec286c8ec43835176971a7861f75a590ca742103061c80153f8e4be3013d37b3ef9103cd3f477615d52f001a130425d97c4eb95e52aeffffffff02102700000000000017a914748d81aa676b2b464d7a2d5c6cf4af7f7f2bad1487685501000000000017a9147eabf95b9700eefe66efe4dbf1a15b27117dbef68700000000",
            "scriptPubKey": "a9147eabf95b9700eefe66efe4dbf1a15b27117dbef687",
            "txId": "4fbdc3579911938abfd1a9fe35873f7d33f31be9a792f69a4e0a445a91e74739",
            "vout": 1,
            "witnessScript": "522103a22f646f375f7b4da865643e9c5bec286c8ec43835176971a7861f75a590ca742103061c80153f8e4be3013d37b3ef9103cd3f477615d52f001a130425d97c4eb95e52ae"
        },
        {
            "address": "2N3sVtadmqqzV9X8GgxoKLGFQps4BmxbxJX",
            "addressType": "p2sh",
            "amount": "0.0001",
            "hex": "0200000000010105ca190252cb7ca1380e3dd61a21a179faa5f0e8b494abdc9c1a73a3f38018a20000000000feffffff029954230000000000160014ac68a4e25875320e3abc6caf6821a1142b412a45102700000000000017a914748d81aa676b2b464d7a2d5c6cf4af7f7f2bad148702473044022063234c6a41eb2db6e772713816af036da258eefa530cc6336aa18d2e50f9639f02200a1081f0b29afc9dec9c0915c31b383c1d454cebc80b42258bcef453c08a78b3012102ad8f812e0027e95788ee56d16d07d9d2ca455432e2496b00b3ae1dc9e2ce7be7dc832100",
            "scriptPubKey": "a914748d81aa676b2b464d7a2d5c6cf4af7f7f2bad1487",
            "txId": "6a11235a3cac10c0db36c99388ff205a764b456cb2d8da7889a0ab8d42ebb4b9",
            "vout": 1,
            "witnessScript": ""
        }
    ],
    "btcVoutBOList": [{
            "address": "2N3sVtadmqqzV9X8GgxoKLGFQps4BmxbxJX",
            "amount": 0.0001099
        },
        {
            "address": "2NBo6PXsJ9qTRXUitABQnrvyRuoe78DM5th",
            "amount": 0.0000001
        },
        {
            "address": "2N4o19RPamhpKbHz55ctmfN8Ybb79jMSppD",
            "amount": 0.000864
        }
    ],
    "hex": "02000000023947e7915a440a4e9af692a7e91bf3337d3f8735fea9d1bf8a93119957c3bd4f01000000920047304402205dfe6f30e503ead93711655bf16dd296c70d323edd5fd37434908401ea74269d022016bab9e6a4e2d39cdbb72451e80d71e442066cf06479bfd2374d9351300a15c1010047522103a22f646f375f7b4da865643e9c5bec286c8ec43835176971a7861f75a590ca742103061c80153f8e4be3013d37b3ef9103cd3f477615d52f001a130425d97c4eb95e52aeffffffffb9b4eb428daba08978dad8b26c454b765a20ff8893c936dbc010ac3c5a23116a0100000000ffffffff03ee2a00000000000017a914748d81aa676b2b464d7a2d5c6cf4af7f7f2bad14870a0000000000000017a914cb793b3f0c560cb95c0b4d941bc06289484ebfce87805101000000000017a9147eabf95b9700eefe66efe4dbf1a15b27117dbef68700000000"
}

let addresses = ['addressA','addressB']
let publicKeys = ['publickeyA','publicKeyB']
let privateKeys = ['privatekeyA','privatekeyB']
let privateKey = privateKeys[0]
```

data.hex has been signed once with 'cRf3TT6PLEBVbBgsceS75ToPVur35cirsvvcWhySfrvQfYCmfkmW', and then signed with this private key 'cRjoxaw6Db3VTAoGNuMfELc4bym9ht4WdpBr36NtsvkGKMLcNsNq' to report this error

**Error: Inconsistent redeemScript**

Where could the problem be?

`
```javascript
// bitcoinjs-lib@6.0.1  Not finalized
const tx = new bitcoin.Psbt({ network: bitcoin.networks.regtest })
const keyPair = ECPair.fromWIF(privateKey,bitcoin.networks.regtest)
            const p2shP2wpkh= bitcoin.payments.p2sh({
                redeem: bitcoin.payments.p2wpkh({
                    pubkey: keyPair.publicKey,
                    network: bitcoin.networks.regtest,
                }),
                network: bitcoin.networks.regtest,
            });
            const pubkeys = publicKeys.map(item => Buffer.from(item,'hex'))
            const p2ms = bitcoin.payments.p2ms({
                m: pubkeys.length,
                pubkeys,
                network: bitcoin.networks.regtest
            })
            const p2shP2ms = bitcoin.payments.p2sh({ redeem: p2ms,network: bitcoin.networks.regtest })

data.btcVinBOList.forEach((item) => tx.addInput(item.address == '2N3sVtadmqqzV9X8GgxoKLGFQps4BmxbxJX' ? {
                hash: item.txId,
                index: item.vout,
                redeemScript: p2shP2wpkh.redeem.output, 
                witnessUtxo: {
                    script: P2WSH.output, 
                    value: (item.amount*1e8), 
                },
            } : item.address == '2N4o19RPamhpKbHz55ctmfN8Ybb79jMSppD' ? {
                hash: item.txId,
                index: item.vout,
                redeemScript: p2shP2ms.redeem.output, //Buffer.from(item.script, 'hex'), 
                witnessUtxo: {
                    script: Buffer.from(item.scriptPubKey,'hex'), 
                    value: (item.amount*1e8), 
                },           
            } : {}))
            data.btcVoutBOList.forEach((item,index) => {
                tx.addOutput({ address: item.address,value: (item.amount*1e8) })
            })

            console.error('addOutput over!',tx)
            data.btcVinBOList.map((item,index) => {
                tx.signInput(index,keyPair)
            })

            tx.finalizeAllInputs()
            const transaction = tx.extractTransaction()
            const signedTransaction = transaction.toHex()
            const transactionId = transaction.getId()
            console.error('signInput over!',signedTransaction,transactionId)
            return signedTransaction
```
`

`
```javascript
// bitcoinjs-lib@5.2.0  **Error: Inconsistent redeemScript**
const transaction = bitcoin.Transaction.fromHex(data.hex)
            const pubkeys = publicKeys.map(item => Buffer.from(item,'hex'))
            const p2ms = bitcoin.payments.p2ms({ m: 2,pubkeys,network: bitcoin.networks.regtest })
            const p2wsh = bitcoin.payments.p2wsh({ redeem: p2ms,network: bitcoin.networks.regtest })
            const p2shP2ms = bitcoin.payments.p2sh({ redeem: p2ms,network: bitcoin.networks.regtest })
            const keyPair = bitcoin.ECPair.fromWIF(privateKey,bitcoin.networks.regtest)

            const p2shP2wpkh = bitcoin.payments.p2sh({
                redeem: bitcoin.payments.p2wpkh({
                    pubkey: keyPair.publicKey,
                    network: bitcoin.networks.regtest,
                }),
                network: bitcoin.networks.regtest,
            })
            const p2sh = bitcoin.payments.p2sh({
                redeem: keyPair.publicKey,
                network: bitcoin.networks.regtest
            });

            const txBuild = bitcoin.TransactionBuilder.fromTransaction(transaction,bitcoin.networks.regtest)
            data.btcVinBOList.forEach((input,index) => {
                if (input.address == '2N3sVtadmqqzV9X8GgxoKLGFQps4BmxbxJX') {
                    txBuild.sign(index,keyPair,p2shP2wpkh.redeem.output,undefined,(input.amount*1e8))
                } else {
                    txBuild.sign(index,keyPair,p2sh.redeem.output,undefined,(input.amount*1e8),undefined)
                }
            })
            const txId = txBuild.__build(true).toHex()
            return txId
```

`

Thanks

**Comment by junderw** [comment]
Your logic for deciding which one to use for `addInput` doesn't make any sense.

The middle of the three also makes no sense, you are using the same script for the previous output script and the redeemScript.

Also, your first input says `witnessScript` when it really means redeemScript.

isSegwit is undefined.

address in  `address == item.address` is undefined.

NumberUtils is undefined.

---

It's probably a mixture of one or more of the above problems. Most likely the logic around `addInput`.

**Comment by stefaniepei** [comment]
> Your logic for deciding which one to use for `addInput` doesn't make any sense.
> 
> The middle of the three also makes no sense, you are using the same script for the previous output script and the redeemScript.
> 
> Also, your first input says `witnessScript` when it really means redeemScript.
> 
> isSegwit is undefined.
> 
> address in `address == item.address` is undefined.
> 
> NumberUtils is undefined.
> 
> It's probably a mixture of one or more of the above problems. Most likely the logic around `addInput`.

I removed all undefined content including isSegwit。

**Comment by junderw** [comment]
`address` is still undefined.

**Comment by junderw** [comment]
The middle option for your addInput logic makes no sense.

If you have a p2ms as your redeemScript then there is no possible way to have a witnessScript.

A redeemScript means there is P2SH.

A P2SH can only exist as `P2SH(segwit-P2WPKH), P2SH(non segwit script), or P2SH(P2WSH(some script))`

The only P2SH that can hold a P2MS in the redeemScript is P2SH(P2MS)... which is not segwit. Which means witnessScript is impossible.

---

So your middle option is trying to do 2-3 things that are all mutually exclusive and impossible to coexist.

Please figure out which thing you want them to do.

**Comment by stefaniepei** [comment]
> 

Do you mean this transaction cannot be signed successfully?

**Comment by stefaniepei** [comment]
`
Fox example
const data = {
		"btcVinBOList": [{
				"address": "2MuqQbwG93exqBqpZN87V2zdB74e3NmdYGc",
				"amount": "0.004",
				"scriptPubKey": "a9141c674145c4cb740dcfdd2d94679e5f7bc35e2dba87",
				"txId": "f23052f183b3bfd1538eb1cd54da8d855993b174da30d4d8f012e508400846b4",
				"vout": 0,
				"witnessScript": "5221031bc1009638abc476f433f24b454fd8dd57f551f32ecc88c3dd21373c0b0901d6210334f162b0deb1bcbf1364b5421e523bc79a104584600c2e391fc4465bcb3b1e8452ae"
			},
			{
				"address": "n2xfuAjqfHtUH9u65AFVkm4dk9FisKs5aZ",
				"amount": "0.003",
				"scriptPubKey": "76a914eb37c55def88e902882cb33446f988d6b1f27f7388ac",
				"txId": "0ae87a6a6ea3265b3d8a5108810d7ae6a4851b98a7b26fe406359534ff766aa3",
				"vout": 2,
				"witnessScript": ""
			}
		],
		"btcVoutBOList": [{
				"address": "2MuqQbwG93exqBqpZN87V2zdB74e3NmdYGc",
				"amount": 0.00199
			},
			{
				"address": "n2xfuAjqfHtUH9u65AFVkm4dk9FisKs5aZ",
				"amount": 0.005
			}
		],
		"hex": "0200000002b446084008e512f0d8d430da74b19359858dda54cdb18e53d1bfb383f15230f20000000000ffffffffa36a76ff34953506e46fb2a7981b85a4e67a0d8108518a3d5b26a36e6a7ae80a0200000000ffffffff02580903000000000017a9141c674145c4cb740dcfdd2d94679e5f7bc35e2dba8720a10700000000001976a914eb37c55def88e902882cb33446f988d6b1f27f7388ac00000000"
	}
  `
const data = {
		"btcVinBOList": [{
				"address": "2MuqQbwG93exqBqpZN87V2zdB74e3NmdYGc",
				"amount": "0.004",
				"scriptPubKey": "a9141c674145c4cb740dcfdd2d94679e5f7bc35e2dba87",
				"txId": "f23052f183b3bfd1538eb1cd54da8d855993b174da30d4d8f012e508400846b4",
				"vout": 0,
				"witnessScript": "5221031bc1009638abc476f433f24b454fd8dd57f551f32ecc88c3dd21373c0b0901d6210334f162b0deb1bcbf1364b5421e523bc79a104584600c2e391fc4465bcb3b1e8452ae"
			},
			{
				"address": "n2xfuAjqfHtUH9u65AFVkm4dk9FisKs5aZ",
				"amount": "0.003",
				"scriptPubKey": "76a914eb37c55def88e902882cb33446f988d6b1f27f7388ac",
				"txId": "0ae87a6a6ea3265b3d8a5108810d7ae6a4851b98a7b26fe406359534ff766aa3",
				"vout": 2,
				"witnessScript": ""
			}
		],
		"btcVoutBOList": [{
				"address": "2MuqQbwG93exqBqpZN87V2zdB74e3NmdYGc",
				"amount": 0.00199
			},
			{
				"address": "n2xfuAjqfHtUH9u65AFVkm4dk9FisKs5aZ",
				"amount": 0.005
			}
		],
		"hex": "0200000002b446084008e512f0d8d430da74b19359858dda54cdb18e53d1bfb383f15230f20000000000ffffffffa36a76ff34953506e46fb2a7981b85a4e67a0d8108518a3d5b26a36e6a7ae80a0200000000ffffffff02580903000000000017a9141c674145c4cb740dcfdd2d94679e5f7bc35e2dba8720a10700000000001976a914eb37c55def88e902882cb33446f988d6b1f27f7388ac00000000"
	}

let addresses = ['n2xfuAjqfHtUH9u65AFVkm4dk9FisKs5aZ','mfpSXuZtXVr8QK7VUXBPBv9MumR4Cmgx6V','2NGUZ8Lsr5UXnuhqTM4e4LnhC2L7hMh1vxP','2NAwijBFYVtcvK2c3ThQXqwpxivAAkkqCVg']
            let publicKeys = ['031bc1009638abc476f433f24b454fd8dd57f551f32ecc88c3dd21373c0b0901d6','02a5e0abed404482bf53b46a416d47b177171cab419bc473c70afeb8a215296477','0334f162b0deb1bcbf1364b5421e523bc79a104584600c2e391fc4465bcb3b1e84','0321c36c2ff5522cf3be16ac17201b82da0a901a367ea6031ecc096fe0f7689511']
            let privateKeys = ['cVNKFBweQ7dmqpRfQcunJUFwJWsBWpdv3FxcvpnaWHGL9pUZ9S8r','cV5aJ5CMdB4dLVXzFLTPn2xQGMZ9jNwRu1sW4tjpmNxvcURzz2Pv','cQuAJQ54bEx4i6EDXGK3q2wpcTAbdud6kg3UkV9zpKav9haeVrmi','cV7K6QHxYSebnjS73kVjz4AKsHKacSQCwfv3VKf4iqpPuWeMxLKJ']
            let multi = {
                address: '2MuqQbwG93exqBqpZN87V2zdB74e3NmdYGc',
                redeemScript: '5221031bc1009638abc476f433f24b454fd8dd57f551f32ecc88c3dd21373c0b0901d6210334f162b0deb1bcbf1364b5421e523bc79a104584600c2e391fc4465bcb3b1e8452ae',
                scriptPubKey: 'a9141c674145c4cb740dcfdd2d94679e5f7bc35e2dba87',
                publicKeys: [publicKeys[0],publicKeys[2]],
                privateKeys: [privateKeys[0],privateKeys[2]],
                addresses: [addresses[0],addresses[2]],
            }

    Java sign
    1. use multi.privateKeys[0] sign this trancation get hex 0200000002b446084008e512f0d8d430da74b19359858dda54cdb18e53d1bfb383f15230f200000000920047304402202f7e923b6bba28c9a759af78ab693976c7d9599011be947fb21528506c94471802207b7d8d2c03f4f29bd2b123da24893f9c16ab501bba6d6ff0d4ed76c3fb8a84140100475221031bc1009638abc476f433f24b454fd8dd57f551f32ecc88c3dd21373c0b0901d6210334f162b0deb1bcbf1364b5421e523bc79a104584600c2e391fc4465bcb3b1e8452aeffffffffa36a76ff34953506e46fb2a7981b85a4e67a0d8108518a3d5b26a36e6a7ae80a020000006a4730440220616bbc0cba9b736938b931177611e7799b2bd4ec14618c86ac881ae64e23a2e902206d728397e80bd276aedafa28f8b049f607477e60f1cce95aee25273c54691d250121031bc1009638abc476f433f24b454fd8dd57f551f32ecc88c3dd21373c0b0901d6ffffffff02580903000000000017a9141c674145c4cb740dcfdd2d94679e5f7bc35e2dba8720a10700000000001976a914eb37c55def88e902882cb33446f988d6b1f27f7388ac00000000
    2. use multi.privateKeys[1] sign this trancation get hex 
0200000002b446084008e512f0d8d430da74b19359858dda54cdb18e53d1bfb383f15230f200000000d90047304402202f7e923b6bba28c9a759af78ab693976c7d9599011be947fb21528506c94471802207b7d8d2c03f4f29bd2b123da24893f9c16ab501bba6d6ff0d4ed76c3fb8a84140147304402204acdd15a4f4515dc0bc285ba89bd85674354d6fa8cad090f26688847c399d6d402200bf4a7dc5f1f10a4bd3a321ff6d7ef683271ba1df7969f5b28eb5b9eb37ec79901475221031bc1009638abc476f433f24b454fd8dd57f551f32ecc88c3dd21373c0b0901d6210334f162b0deb1bcbf1364b5421e523bc79a104584600c2e391fc4465bcb3b1e8452aeffffffffa36a76ff34953506e46fb2a7981b85a4e67a0d8108518a3d5b26a36e6a7ae80a020000006a4730440220616bbc0cba9b736938b931177611e7799b2bd4ec14618c86ac881ae64e23a2e902206d728397e80bd276aedafa28f8b049f607477e60f1cce95aee25273c54691d250121031bc1009638abc476f433f24b454fd8dd57f551f32ecc88c3dd21373c0b0901d6ffffffff02580903000000000017a9141c674145c4cb740dcfdd2d94679e5f7bc35e2dba8720a10700000000001976a914eb37c55def88e902882cb33446f988d6b1f27f7388ac00000000

  Javascript sign with bitcoinjs-lib
1. use multi.privateKeys[0] sign this trancation get hex 
02000000000102b446084008e512f0d8d430da74b19359858dda54cdb18e53d1bfb383f15230f200000000920047304402202f7e923b6bba28c9a759af78ab693976c7d9599011be947fb21528506c94471802207b7d8d2c03f4f29bd2b123da24893f9c16ab501bba6d6ff0d4ed76c3fb8a84140100475221031bc1009638abc476f433f24b454fd8dd57f551f32ecc88c3dd21373c0b0901d6210334f162b0deb1bcbf1364b5421e523bc79a104584600c2e391fc4465bcb3b1e8452aeffffffffa36a76ff34953506e46fb2a7981b85a4e67a0d8108518a3d5b26a36e6a7ae80a0200000017160014eb37c55def88e902882cb33446f988d6b1f27f73ffffffff02580903000000000017a9141c674145c4cb740dcfdd2d94679e5f7bc35e2dba8720a10700000000001976a914eb37c55def88e902882cb33446f988d6b1f27f7388ac0002483045022100ad04837e27bacba990462efce40e11e4e192c74651a605daa33fc0011b9f92d9022047df9c71ed6616330599ffa99999dd92f2e804484b507a69a6808d0a9e8bf0b90121031bc1009638abc476f433f24b454fd8dd57f551f32ecc88c3dd21373c0b0901d600000000
 2. use multi.privateKeys[1] sign this trancation get hex 
Inconsistent redeemScript



`

**Comment by junderw** [comment]
There is something wrong with what you wrote on a fundamental level.

If the redeemScript is p2ms, then it is impossible to have a witnessScript.

**Comment by junderw** [comment]
Do you understand what Pay To Script Hash (P2SH) and Pay To Witness Hash (P2WSH) mean and how they differ?

redeemScript is the meaningful script that is encapsulated inside a P2SH script.

witnessScript is the meaningful script that is encapsulated inside a P2WSH script.

The only possible combination of redeemScript AND witnessScript is if you are using a P2SH(P2WSH(xxxx)) type script. In that case, the scriptPubkey would be the P2SH script, the redeemScript would be the P2WSH script, and the witnessScript would be the meaningful script.

But your code (on the middle option of the 3 options in addInput) says that redeemScript === p2ms (which is not P2WSH), but that also witnessScript can exist... which is impossible.

**Comment by junderw** [comment]
When I look at the two input data you show me, there is no P2WSH anywhere.

You only have 1 P2SH(P2MS) and 1 P2SH(P2WPKH)... `witnessScript` should not exist anywhere, at all.

**Comment by junderw** [comment]
The only other possibility:

- Your wallet manages other scripts that you are not showing me.

In which case, I can't help you... because I can't see what you don't show me.

**Comment by stefaniepei** [comment]
Error: Inconsistent redeemScript
The reason is that the public key sequence of the multi-signature address is the problem. If the public key sequence is arranged correctly, this problem will not occur. But for the signature of multiple addresses, the signature already exists

**Comment by junderw** [comment]
If the problem has resolved, please close the issue. Thanks.

**Comment by stefaniepei** [comment]
> If the problem has resolved, please close the issue. Thanks.

Thank you very mush
