### ISSUE TITLE
decompiling bip68 locktimes behaves differently using blocks/seconds

### ISSUE THREAD

**Issue by landabaso** [bitcoinjs/bitcoinjs-lib#1799]
I'm confused how is script.decompile/script.number.decode supposed to use to read bip68 encoded locktimes.

See this minimal example:

```javascript

          const encodedLockTime = bip68.encode({
            //blocks: 10
            seconds: 512
          });
          const compiled = script.fromASM(
            `${script.number.encode(encodedLockTime).toString('hex')}`
              .trim()
              .replace(/\s+/g, ' ')
          );
          console.log(
            bip68.decode(script.number.decode(script.decompile(compiled)[0]))
          );

```

This works as expected when setting {seconds: 512}.

However, it throws when setting blocks: 10.

` Catched an error, stoping testing environment Error: Non-minimally encoded script number
        at Object.decode ( ... MY PATH ... /node_modules/bitcoinjs-lib/src/script_number.js:13:15)`

It looks like `script.fromASM` produces a `Buffer` when compiling bip68 times using seconds, and it produces `number` when compiling bip68 times using blocks.

Any ideas how to properly address this issue?

**Comment by junderw** [comment]
When setting blocks between 1 and 16. `fromASM` will reduce `"0a"` hex into OP_10 (which is `0x5a`)

This is because script conversions will always automatically convert to minimally encoded lengths.

This means numbers 1 - 16 will be encoded as OP_1 - OP_16 which are technically not "script numbers"

```js
function decompiledToScriptNumberBuffer(decompiled) {
    return typeof decompiled === 'number' &&
        decompiled >= 0x51 && // OP_1 (or OP_TRUE)
        decompiled <= 0x60    // OP_16
            ? Buffer.from([decompiled - 0x50])
            : decompiled // this is a Buffer
}

console.log(
  bip68.decode(script.number.decode(decompiledToScriptNumberBuffer(script.decompile(compiled)[0])))
);
```

**Comment by landabaso** [comment]
I understand. It's tricky. Would it make sense to handle OP_1...OP_16 internally in script.number.decode?
Technically these OPS are not numbers, so I understand why it is not implemented this way. On the other hand, script.number.decode will never receive integers from 0 to 16, and it's easy to write bad code that doesn't take into account how fromASM will behave.

Thanks anyway for providing an explanation and some code to handle the situation!

**Comment by landabaso** [comment]
I am still finding edge cases and it may be a good idea to keep track them here in case someone else bumps into them in the future.

Numbers are usually passed to fromASM in the tests like this:

```javascript
     script.fromASM(
      `${script.number.encode(myNumber).toString('hex')}`.trim().replace(/\s+/g, ' ')
    );
```

But
```javascript
${script.number.encode(0).toString('hex')}
```
is an empty string (note the Zero).

In fact, this is fully expected to be like this by looking at [the tests](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/fixtures/script_number.json): `{ "hex": "", "number": 0}`.

I believe zeros should be encoded like this:
`0100` or `OP_0`.

I guess it's the responsibility of the parent function to make sure that number.encode/number.decode are used accordingly depending on the number. But it's kind of easy to create buggy scripts if not careful with these details so, we must be extra careful!

The thing is I'm still not 100% sure if `number.encode(0)` should be producing an empty Buffer. What's the reason for that @junderw ?

**Comment by junderw** [comment]
This part of the library assumes you know how the Script language works.

OP_0 pushes a 0 byte length Buffer to the stack. It is the minimal way to represent 0.

**Comment by landabaso** [comment]
> This part of the library assumes you know how the Script language works.
> 
> OP_0 pushes a 0 byte length Buffer to the stack. It is the minimal way to represent 0.

I understand. My point is that some people may end up using `number.encode(num).toString('hex')` as in the tests to create locking scripts.

They may inadvertently use it for num = 0.

It's tricky because number.encode(0) will produce an empty Buffer that .toString('hex') will transform into an empty string "" and not into an "OP_0". And the final locking script will not be as expected.

I guess there's not much that can be done apart from mentioning it here.

To others that read this in the future, I'd suggest using something like this:

```javascript
function numberEncodeAsm(number) {
  if (number === 0) {
    return 'OP_0';
  } else return script.number.encode(number).toString('hex');
}
```
Then, to produce `0 1 OP_ADD` use it like this:
```javascript
fromASM(
`${numberEncodeAsm(0)} ${numberEncodeAsm(1)} OP_ADD`
  .trim().replace(/\s+/g, ' ')
)
```
And you will get : `<Buffer 00 51 93>` (instead of getting `<Buffer 51 93>`)
