### ISSUE TITLE
Reduce warnings about future segwit version when parsing output scripts

### ISSUE THREAD

**Issue by woofbotapp** [bitcoinjs/bitcoinjs-lib#1800]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/93af5afe67dbc491e36bdfc8d48a00179093f7d1/ts_src/address.ts#L52

I'm writing an app that continuously parses lots of transactions (for analysis purposes) This warning is printed every time such output-script is parsed, and it really spams my logs.

Please make it possible to avoid this warning, maybe via an environment variable.
Another reasonable option is to print the warning only after the first time such an output-script is found, and not in following occurrences.

Thanks!

**Comment by junderw** [comment]
A few thoughts:

1. This will be fixed for segwit v1 addresses in an upcoming release (once we finish taproot support)
2. That said, console.warn was meant primarily for wallet developers to be sure that they don't show versions they can't guarantee are safe.
3. However, we have no way programmatically to relay that info back to the program, and the program has no way to tell us "ok, I made my GUI understandable so the end user is not in danger".
4. Also, we want to respect the BIP and DO NOT THROW on parsing unknown segwit versions.

Perhaps we should add a new set of functions for to/fromOutputScript and deprecate the current ones for removal in the next major version bump?

**Comment by junderw** [comment]
As a temporary solution, though super hackey, the consuming app could do something like:

```js
function wrappedFromOutputScript(script, network) {
  const oldWarn = console.warn
  console.warn = () => {}
  const result = fromOutputScript(script, network)
  console.warn = oldWarn
  return result
}
```

**Comment by woofbotapp** [comment]
> As a temporary solution, though super hackey, the consuming app could do something like:
> 
> ```js
> function wrappedFromOutputScript(script, network) {
>   const oldWarn = console.warn
>   console.warn = () => {}
>   const result = fromOutputScript(script, network)
>   console.warn = oldWarn
>   return result
> }
> ```

![giphy](https://user-images.githubusercontent.com/101908620/168442116-145c1948-7c67-42e4-bb92-1bc224208a78.gif)

**Comment by PatrickGeyer** [comment]
Is there an ETA on this at all?

**Comment by motorina0** [comment]
> Is there an ETA on this at all?

Please help review this PR https://github.com/bitcoinjs/bitcoinjs-lib/pull/1742, and [the rest will follow](https://www.youtube.com/watch?v=i7iQbBbMAFE) 🎵

**Comment by pedrobranco** [comment]
This also happens when parsing some Litecoin transactions. 
Maybe adding an optional argument in `fromOutputScript` to disable these warnings?

**Comment by junderw** [comment]
I guess we can just do it once. See PR.

**Comment by fabiobaiao** [comment]
Can this be merged and published, please?
