### ISSUE TITLE
P2SH Custom RedeemScript using PSBT

### ISSUE THREAD

**Issue by Sudz24** [bitcoinjs/bitcoinjs-lib#1803]
Hi, 

I am working on a problem statement that will require some conditional withdrawals. 

The examples from the link below have been great with helping me understand how to construct custom locking scripts.
https://github.com/bitcoinjs/bitcoinjs-lib/blob/c95e15de01519b30c5eeb0f89700d03e49afb0e1/test/integration/csv.spec.ts

However, I am unable to implement a P2SH redeemScript using PSBT. The above link has examples that uses custom scripts using TxBuilder only (which is now deprecated I believe). 

Can you kindly guide me with some snippets that uses a custom redeemScript for unlocking the balance using PSBT?
Thanks!

**Comment by junderw** [comment]
This example uses a custom finalizer for `finalizeInput`
https://github.com/bitcoinjs/bitcoinjs-lib/blob/c95e15de01519b30c5eeb0f89700d03e49afb0e1/test/integration/csv.spec.ts#L118-L171

This is how you would use Psbt.

`csvGetFinalScripts` function is defined at the bottom of the same file.
