### ISSUE TITLE
Silent Payments example

### ISSUE THREAD

**Issue by motorina0** [bitcoinjs/bitcoinjs-lib#1806]
### Silent Payments
> Receive private payments from anyone on a single static address without requiring any interaction or extra on-chain overhead.

I have added a `Silent Payment` integration test in [this PR (more details here)](https://github.com/bitcoincoretech/bitcoinjs-lib/pull/9)

Does it make sense  to have it as a integration test here?
I'm opening this issue in order to keep the discussion on this repo.

**Comment by junderw** [comment]
Hmm, this sounds cool.

**Comment by motorina0** [comment]
Opened PR against this repo: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1848
