### ISSUE TITLE
Support for Discreet Log Contracts

### ISSUE THREAD

**Issue by Sudz24** [bitcoinjs/bitcoinjs-lib#1807]
Hi, 

Does the current version of the library support in working with some latest developements such as Discreet Log Contract?
I know the Taproot support is being added as of now, would be helpful to understand the scope of DLC too.

Thanks!

**Comment by junderw** [comment]
We do not have a safe interface for DLCs.

However, all the building blocks are there.

Adding Taproot support will just make it easier to hide used paths.
