### ISSUE TITLE
Uncaught TypeError: Bitcoin.ECPair is undefined

### ISSUE THREAD

**Issue by ayushch80** [bitcoinjs/bitcoinjs-lib#1809]
hey there im getting `Uncaught TypeError: Bitcoin.ECPair is undefined` my code in browser

        ```const wallet = bitcoin.ECPair.makeRandom()
        const address = wallet.pub.getAddress().toString()
        const wifKey = wallet.toWIF() ```

also i have added bitcoinjs.min.js in script tag

**Comment by motorina0** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib#installation

> Previous versions of the library included classes for key management (ECPair, HDNode(->"bip32")) but now these have been separated into different libraries. This lowers the bundle size significantly if you don't need to perform any crypto functions (converting private to public keys and deriving HD keys).

**Comment by ayushch80** [comment]
Do I have to make their browser compatible scripts with browserify
