### ISSUE TITLE
Psbt getFinalScripts feeds incorrect isP2WSH=true parameter for P2SH-P2WSH inputs

### ISSUE THREAD

**Issue by landabaso** [bitcoinjs/bitcoinjs-lib#1810]
When using `P2SH-P2WSH` inputs, `getFinalScripts` will incorrectly pass `isP2WSH = true`.

The problem is here:

[https://github.com/bitcoinjs/bitcoinjs-lib/blob/59b21162a2c4645c64271ca004c7a3755a3d72fb/src/psbt.js#L1079](https://github.com/bitcoinjs/bitcoinjs-lib/blob/59b21162a2c4645c64271ca004c7a3755a3d72fb/src/psbt.js#L1079)

Note that `!!witnessScript === true` for `P2SH-P2WSH`.

An easy fix could be:

```javascript
res.isP2WSH = !res.isP2SH && !!input.witnessScript;
```

The user can later infer whether it is `P2SH-P2WSH` using the combination of `isSegwit === true && isP2SH === true`.

BTW, If you agree I can submit a PR for this fix and (another different one?) for [the one here](https://github.com/bitcoinjs/bitcoinjs-lib/issues/1805).

**Comment by junderw** [comment]
This is correct. `isP2WSH` is true because it is a P2WSH script.

You could alternatively name them `isP2SH -> hasRedeemScript` and `isP2WSH -> hasWitnessScript` but tbh I don't find them hard to understand.

**Comment by landabaso** [comment]
> This is correct. `isP2WSH` is true because it is a P2WSH script.
> 
> You could alternatively name them `isP2SH -> hasRedeemScript` and `isP2WSH -> hasWitnessScript` but tbh I don't find them hard to understand.

I see! I thought `isP2WSH`, `isP2SH`, ... referred to the input (not the script). I got confused because `getFinalScripts` gets both `isSegwit` and `isP2WSH` and thought it was there to differentiate P2WSH from nested segwit script inputs.

Thanks for the clarification. I wasn't sure about using them in case there was a bug and there were changes to the API in the future. All clear now!
