### ISSUE TITLE
Taproot sample code

### ISSUE THREAD

**Issue by Dujon4444** [bitcoinjs/bitcoinjs-lib#1813]
Hi,

I am new to this, your library is extremely helpful. Am stuck with Taproot though. I have created a customized conditional spending transaction with PSBT and P2SH but want to change it to Taproot. Is there a sample code for creating addresses and conditional spending transactions with Taproot? Will be extremely helpful. 

Thank you in advance!

**Comment by motorina0** [comment]
The taproot functionality still under review (not merged yet).
You can find it in this PR: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1742

The taproot integration-tests and unit-tests should be a good starting point.

**Comment by motorina0** [comment]
The taproot PR is merged.
Please check the unit tests and the integration tests.
