### ISSUE TITLE
I need help asap 

### ISSUE THREAD

**Issue by Lutnerd** [bitcoinjs/bitcoinjs-lib#1817]
Good day guys I hope you guys are doing good I’m having a problem I can’t broadcast a transaction it’s giving me Error validating transaction: Rejected script for input 0 referencing f73f407dcb4d4d7f0570a615e2fdde1f6fc5bf75f7183e7dd39b428286d75670
 at 1.. I don’t know what to do which website can I use for my broadcast transaction to work.

**Comment by motorina0** [comment]
Duplicate. Closing.
