### ISSUE TITLE
Issue with tapInternal key

### ISSUE THREAD

**Issue by Dujon4444** [bitcoinjs/bitcoinjs-lib#1821]
Thank you so much for the response @junderw . However, some of the functions like 'getTaprootHashesForSig' in the psbt.js require tapInternalKey as part of the input structure. If tapInternalKey is  currently not being saved in the input, how are these functions accessing it?

_Originally posted by @Dujon4444 in https://github.com/bitcoinjs/bitcoinjs-lib/issues/1819#issuecomment-1165187180_

**Comment by motorina0** [comment]
> the tapInternalKey is being saved as part of the PSBT structure

You can find an example [here](https://github.com/bitcoincoretech/bitcoinjs-lib/blob/p2tr-v1/test/integration/taproot.spec.ts#L86)

```ts
    psbt.addInput({
      hash: unspent.txId,
      index: 0,
      witnessUtxo: { value: amount, script: output! },
      tapInternalKey: toXOnly(internalKey.publicKey),
    });
```
