### ISSUE TITLE
[Question] How to spend a Bitcoin Script utxo from P2WSH

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1838]
Hi.

At the moment I am using P2sh to generate the address and to spend it.

This is the code:

```
// address creation
const script = this.generateBitcoinScript(tree, signers)
const redeemScript = bitcoin.script.compile(script) 
const p2wsh = bitcoin.payments.p2wsh({ redeem: { output: redeemScript, network }, network )
const p2sh = bitcoin.payments.p2sh({ redeem: p2wsh, network})
 const address = p2sh.address

// spend bitcoins
 const script = p2sh.output
const redeemScript = p2sh.redeem.output
const witnessScript = p2sh.redeem.redeem.output
... create psbt, addOputs.
psbt.addInput({ hash, index,  
          redeemScript,
          witnessScript,
          witnessUtxo: {
            script, 
            value,
          }}
        )
psbt.signInput(i, keyPair)
.etc.
```

How do I use just P2WSH (not using P2SH)?

With multisignature it has been as easy as removing redeemScript from addInput. 
```
psbt.addInput({ hash, index,
     witnessScript: p2wsh.redeem.output,
    witnessUtxo: { script: p2wsh.output, value }})
```

Thanks.

**Comment by junderw** [comment]
I have no idea what the script is, but if the witnessScript contains either your DER pubkey or the HASH160 hash of the pubkey for `keyPair`, this should work.

```js
// address creation
const script = this.generateBitcoinScript(tree, signers)
const redeemScript = bitcoin.script.compile(script) 
const p2wsh = bitcoin.payments.p2wsh({ redeem: { output: redeemScript, network }, network )
// REMOVE const p2sh = bitcoin.payments.p2sh({ redeem: p2wsh, network})
const address = p2wsh.address

// spend bitcoins
const script = p2wsh.output
// REMOVE const redeemScript = p2sh.redeem.output
const witnessScript = p2wsh.redeem.output
// ... create psbt, addOputs.
psbt.addInput({ hash, index,  
          // REMOVE redeemScript,
          witnessScript,
          witnessUtxo: {
            script, 
            value,
          }}
        )
psbt.signInput(i, keyPair)
```

**Comment by educob** [comment]
Thanks for answering.

I get error:
`RpcError: non-mandatory-script-verify-flag (Witness requires empty scriptSig) (code 64)`

Regards.

**Comment by junderw** [comment]
Can you show the complete code?

You are probably doing something else that is placing data in the scriptSig (P2WSH will never touch the scriptSig unless it's inside a P2SH)

**Comment by educob** [comment]
Hi Jonathan.

This is the real code:

variable tree is an internal representation of a bitcoin script for inheritance purpose.

address creation: 

`const script = this.generateBitcoinScript(tree, inheritance.signers)
    const redeemScript = bitcoin.script.compile(script) // REDEEM Script
    const p2wsh = bitcoin.payments.p2wsh({ redeem: { output: redeemScript, network: this.bitcoin_network }, network: this.bitcoin_network })
    const output = this.encrypt(p2wsh.output.toString('hex'), jwtToken)
    const redeem = this.encrypt(p2wsh.redeem.output.toString('hex'), jwtToken)
    const address = p2wsh.address`

output & redeem (wrong name. I'll change when this works) are stored in database

`const script = Buffer.from(this.inheritance.output)
 const witnessScript = Buffer.from(this.inheritance.redeem)

psbt.addInput({ hash: utxo.utxo_tx, index: utxo.utxo_n,  
          witnessScript,
          witnessUtxo: {
            script, 
            value: utxo.value,
          }}
        )`

Unless you tell me otherwise, the rest shouldn't change:
`psbt.signInput(i, keyPair)
sigs.push( psbt.data.inputs[i].partialSig[0].signature )

function pathF(inputIndex) {
        return bitcoin.script.compile([  // path inversed
          sigs[inputIndex],
          bitcoin.opcodes.OP_FALSE,
        ])
      }
      sigs.forEach((s, i) => {//      console.log("____________ finalizeInput:", i)
        psbt.finalizeInput(i, this.$generate_path_function(pathF))
      })
`

generate_path_function of course I took it from your code:

`Vue.prototype.$generate_path_function = function(pathF) { 
    const network = this.$bitcoin_network()
    function getFinalScripts(inputIndex, input, script, isSegwit, isP2SH, isP2WSH) {
      const redeemScript =  { input: pathF(inputIndex), output: script,  network }
      const p2wsh = bitcoin.payments.p2wsh({ redeem: redeemScript, network })
      const payment = bitcoin.payments.p2sh({ redeem: p2wsh, network })
      //console.log("payment:", payment)
    
      function witnessStackToScriptWitness(witness) {
        let buffer = Buffer.allocUnsafe(0)
    
        function writeSlice(slice) {
          buffer = Buffer.concat([buffer, Buffer.from(slice)])
        }
        function writeVarInt(i) {
          const currentLen = buffer.length
          const varintLen = varuint.encodingLength(i)
    
          buffer = Buffer.concat([buffer, Buffer.allocUnsafe(varintLen)])
          varuint.encode(i, buffer, currentLen)
        }
        function writeVarSlice(slice) {
          writeVarInt(slice.length)
          writeSlice(slice)
        }
        function writeVector(vector) {
          writeVarInt(vector.length)
          vector.forEach(writeVarSlice)
        }
        writeVector(witness)
        return buffer
      }
  
      return {
        finalScriptSig: payment.input,
        finalScriptWitness: witnessStackToScriptWitness(payment.witness)
         // payment.witness && payment.witness.length > 0
         //   ? witnessStackToScriptWitness(payment.witness)
         //   : undefined,
      }
    }`

You didn't document how to do generic bitcoin scripts with segwit and I made it work by trial & error for weeks.

Thanks for your generous help.
