### ISSUE TITLE
How to get input/output addresses and amounts from a psbt?

### ISSUE THREAD

**Issue by sebastianmontero** [bitcoinjs/bitcoinjs-lib#1840]
I'm trying to get the information of a trx from a psbt to display it to the user, mainly:

- input addresses 
- input amounts
- output addresses 
- output amounts

Is this possible? How would I go about it?

I've loaded the psbt using `Psbt.fromBase64(psbtText)` and I can see the inputs and outputs in the data property, but I don't know how to decode them.

Thanks

**Comment by junderw** [comment]
You might want to pass in a network to `bitcoin.address.fromOutputScript` but this should be fine if you're doing Bitcoin mainnet (the default network)
```js
function inputsOutputs(psbt) {
    const inputs = psbt.data.inputs.map((input, index) => {
        if (input.witnessUtxo) {
            return {
                address: bitcoin.address.fromOutputScript(input.witnessUtxo.script),
                value: input.witnessUtxo.value,
            }
        } else if (input.nonWitnessUtxo) {
            const txin = psbt.txInputs[index];
            const txout = bitcoin.Transaction.fromBuffer(input.nonWitnessUtxo).outs[txin.index];
            return {
                address: bitcoin.address.fromOutputScript(txout.script),
                value: txout.value,
            }
        } else {
            throw new Error('Could not get input of #' + index);
        }
    });
    const outputs = psbt.txOutputs.map(o => ({
        address: o.address,
        value: o.value,
    }))
    return {
        inputs,
        outputs,
    }
}
```

**Comment by sebastianmontero** [comment]
Thank you very much @junderw!

**Comment by sebastianmontero** [comment]
@junderw quick question is it possible to get the txId and fee without the psbt being finalized?

Thanks,
