### ISSUE TITLE
How to add string as input while redeem (p2tr)

### ISSUE THREAD

**Issue by Sudz24** [bitcoinjs/bitcoinjs-lib#1843]
Hi, 

I am following the method to construct a custom redeem script as shown by the function `buildLeafIndexFinalizer` in https://github.com/bitcoincoretech/bitcoinjs-lib/blob/p2tr-v1/test/integration/taproot.spec.ts
This however shows how a number like 123 is added as input. Can you help me how to add a string - say "secret" as input, so that it can be used by the leafScript?

I have a leaf script as follows:
const leaf1Asm = `OP_SHA256 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b OP_EQUALVERIFY ${toXOnly(publicKey).toString('hex')} OP_CHECKSIG`

I am expecting the redeem script to provide a string on which OP_SHA256 will be applied and compared to encoded string in the leafScript using OP_EQUALVERIFY. 
`2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b` in the leafScript is the SHA encode of string "secret".

Thanks a lot!!

**Comment by Sudz24** [comment]
Oh sorry, by number I meant the `leafIndex`. I understand redeemVersion will be constant ofcourse.

I actually have tried various ways of adding a string instead of `leafIndex` in that example, but I always get back an error during broadcast that 'OP_EQUALVERIFY' failed - which means the expected string is not included correctly and hence its SHA is not matching. I was wondering if there's some util function to do that? Like how we had bitcoin.number.encode

**Comment by junderw** [comment]
There is no concept of strings in Bitcoin Script.

You could convert the string to a buffer using `Buffer.from("some string", "utf8")`
