### ISSUE TITLE
ECPair Is always giving me error 

### ISSUE THREAD

**Issue by ClamaBsc** [bitcoinjs/bitcoinjs-lib#1844]
Anytime I am using .ECPair It gives me error
I am using node js 

example code
`
const bitcoin = require('bitcoinjs-lib');

let testnet = bitcoin.networks.testnet;
let keypair = bitcoin.ECPair.makeRandom(testnet);

let addr = keypair.getAddress();
let pk = keypair.toWIF();
`

how can I run it without error.

.

**Comment by junderw** [comment]
Use the old version which still contains ECPair with getAddress.

It's a very old version. Your cold must be very old.

**Comment by ClamaBsc** [comment]
Thanks for the answer, junderw
How do i use old version I just installed this library as 'npm install bitcoinjs-lib' 
How can i install old version.

**Comment by junderw** [comment]
https://docs.npmjs.com/cli/v8/commands/npm-install#:~:text=Install%20the%20specified%20version%20of%20the%20package

**Comment by ClamaBsc** [comment]
Which version have ECpair with these functions
.fromPublicKey, getAddress

 I'm struggling to find.

**Comment by junderw** [comment]
Looks like your code uses [3.3.2](https://github.com/bitcoinjs/bitcoinjs-lib/commit/f4caaf42e7b58332d74c1540f88bcda7e55b82e6) which is 5 years old now.
