### ISSUE TITLE
[Question]How to encode a signature

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1845]
Hi. My website uses graphql-apollo to send and receive information and signatures and everything are encoded ok with apollo-client.

But I am writing jest tests on the server so I am using node library "fetch" to send the graphql calls to the server.

When tyring to send an object with tx signatures I get errors.

What would be the equivalent  toBase64 & fromBase64 methods for just a signature?
And for any object?

Thanks.

**Comment by junderw** [comment]
It looks like GraphQL does not plan to support any binary formats: https://github.com/graphql/graphql-spec/issues/432

The best alternative would be: `bufferSignature.toString('base64')` and `Buffer.from(stringSignature, 'base64')`

For any object that might contain Buffers, I recommend https://www.npmjs.com/package/buffer-json (buffer-json is made by one of the bitcoinjs maintainers)
