### ISSUE TITLE
hash160 the publickey 

### ISSUE THREAD

**Issue by ClamaBsc** [bitcoinjs/bitcoinjs-lib#1846]
I am trying to get the publickey hash using this library, Does anyone know if it is possible .
 
Example
publickey  = 02b4632d08485ff1df2db55b9dafd23347d1c47a457072a1e87be26896549a8737;
hash160(publickey) = 93ce48570b55c42c2af816aeaba06cfee1224fae;

How do i  perform hash160 on a publickey like the example above.

**Comment by motorina0** [comment]
I have small example here of deriving different address types from the public key:

https://github.com/bitcoincoretech/bip32-check/blob/main/src/check-addresses.mjs

Short version:
```js

import { payments } from 'bitcoinjs-lib'

const myPublicKey = ... // Buffeer
const p = payments.p2wpkh({ pubkey: myPublicKey })
console.log(`address: ${p.address}`)

```

**Comment by motorina0** [comment]
There is also an UI here (check the `Payments` tab): https://bitcoincore.tech/apps/bitcoinjs-ui/index.html

**Comment by ClamaBsc** [comment]
Thanks for the answer motorina0, How can i get hash160 of the address

**Comment by junderw** [comment]
the payment for p2wpkh has the hash.

In @motorina0 example: `p.hash` would give you a 20 byte Buffer of the hash160.

**Comment by junderw** [comment]
An example of what you could do is here:

```js
import { payments, networks } from 'bitcoinjs-lib'

const address = '...... some address string ....'
const network = networks.bitcoin

const hash160Payments = [
  payments.p2sh,
  payments.p2pkh,
  payments.p2wpkh,
]

let hash160
for (let i = 0; i < hash160Payments.length; i++) {
  const payment = hash160Payments[i]
  try {
    const p = payment({ address, network })
    hash160 = p.hash
    break
  } catch (e) {}
}
if (hash160 === undefined) {
  throw new Error('No matching payment pattern found for address')
}
```
