### ISSUE TITLE
[Question] Can a mainnet wallet created with path: m/84'/1'/0'/0 work?

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1850]
Hi thanks..

By mistake I have created a mainnet wallet with 1 as coin (but with network: bitcoin.networks.bitcoin) so it creates mainnet bitcoin addresses. (no funds on the wallets so no danger)

Is that wallet able to send bitcoin?

I think the answer is yes but I want to confirm.

Thanks.

**Comment by motorina0** [comment]
The answer is yes.
The path is a convention in order for different wallets to be compatible (create seed in one, restore in another)
If you do not respect the path then (some) wallets will not detect the funds.

**Comment by junderw** [comment]
Some wallets (like Electrum) have advanced features where you can specify any path for deriving addresses for any network.

So some wallets will always allow you to recover, but you need to know what you're doing.

This question is answered. Closing.
