### ISSUE TITLE
How to send a transaction

### ISSUE THREAD

**Issue by Fengggggggggg** [bitcoinjs/bitcoinjs-lib#1860]
Why the error is reported:Error validating transaction: Transaction 2347a7f78b52d6c1f8a0712a4f315ccd25e789f9d78cda8b0ddaf2325817ee39 referenced by input 0 of 1bf7c41c45e8f0bc14bdad50dd33bf5dd24bb71e9eb04da26765987f9ad833ca has already been spent..

**Comment by motorina0** [comment]
Please provide more details (steps to reproduce, code-sample, ...)

**Comment by Fengggggggggg** [comment]
> 请提供更多详细信息（重现步骤、代码示例……）

const sign = async () => {
  const res = await axios.get(
    `https://api.blockcypher.com/v1/btc/test3/addrs/${addr}/full?includeHex=true`
  );
  const hash = res.data.txs[1].hash;
  const hex = res.data.txs[1].hex;
  console.log(hash);
  console.log(hex, "hex");
  const privateKeyWif = keyPair.toWIF();
  const signer = ECPair.fromWIF(privateKeyWif);
  console.log(signer);
  const validator = (pubkey, msghash, signature) =>
    ECPair.fromPublicKey(pubkey).verify(msghash, signature);
  const psbt = new bitcoin.Psbt({ network });
  psbt.setVersion(2);
  psbt.addInput({
    hash: hash,
    index: 0,
    sequence: 0xffffffff,
    nonWitnessUtxo: Buffer.from(hex, "hex"),
  });
  psbt.addOutput({
    address: "mx8HFEoW6gnZ3993N5p2B2hAgQwW85biLd",
    value: 8000,
  });
  psbt.signInput(0, signer);
  psbt.validateSignaturesOfInput(0, validator);
  psbt.finalizeAllInputs();
  const witeBroadcastTx = psbt.extractTransaction(true).toHex();
  alert(witeBroadcastTx);
  console.log(witeBroadcastTx);
  var pushtx = {
    tx: witeBroadcastTx,
  };
  axios
    .post(
      "https://api.blockcypher.com/v1/bcy/test/txs/push",
      JSON.stringify(pushtx)
    )
    .then((e) => {
      console.log(e);
    });
};
