### ISSUE TITLE
Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by bubu59** [bitcoinjs/bitcoinjs-lib#1865]
When importing bitcoinjs-lib into my react project, I get the following error: 

          `Uncaught TypeError: Cannot read properties of undefined (reading 'call')
              at Hash.CipherBase (index.js:6:1)
              at new Hash (browser.js:9:1)
              at createHash (browser.js:23:1)
              at sha256 (crypto.js:26:1)
              at crypto.js:40:1
              at Array.map (<anonymous>)
              at ./node_modules/bitcoinjs-lib/src/crypto.js (crypto.js:39:1)
              at options.factory (react refresh:6:1)
              at __webpack_require__ (bootstrap:24:1)
              at fn (hot module replacement:62:1)`

I have referenced to this repo [https://github.com/crypto-browserify/cipher-base/issues/11](url) but it doesn't seem to solve the issue.

**Comment by bubu59** [comment]
Referring to my own question above,  when I looked into `Hash.Cipherbase`, it points to the error highlighted in the screenshot below.  

<img width="339" alt="Screenshot 2023-01-31 at 2 48 09 PM" src="https://user-images.githubusercontent.com/74093051/215687058-f3dfcf56-b7b0-4985-9435-4e9dcf03eeaa.png">

I have tried to polyfill it with stream(refer to screenshot below) but to no avail.. I have also installed `stream` which is present in my package.json.

<img width="990" alt="Screenshot 2023-01-31 at 2 53 29 PM" src="https://user-images.githubusercontent.com/74093051/215688011-22a1af79-0835-4234-be13-4b3ddc9094d8.png">

**Comment by Hyunhum** [comment]
Change the second line of index.js of Cipherbase, 
from 
`require('stream').Transform` 
to 
`require('readable-stream')`

**Comment by bubu59** [comment]
Thank you! Will give it a shot!

**Comment by junderw** [comment]
Fixed by switching over to noble crypto.

**Comment by imfaker** [comment]
fix it by use 'vite-plugin-node-polyfills'. when use vite

**Comment by leviduan** [comment]
I meet the same issue, and then I change 
Change index.js of Cipherbase,
from
require('stream').Transform
to
require('readable-stream')

the issues is fixed, thanks @ChrisCho-H
