### ISSUE TITLE
Can not sign for this input with the key

### ISSUE THREAD

**Issue by Thankgod20** [bitcoinjs/bitcoinjs-lib#1872]
I am trying to create a bitcoin transaction from a p2wpkh address to any address. The issue i am having is that i cant sign the transaction .

It gives the error below

`[Error: Can not sign for this input with the key 024482b7a8183a957ccc6869df7bd5ddce606e0d50178900a9fd91979a190da292]`

`UTXos source:- https://api.blockcypher.com/v1/btc/test3/txs/506bb2fa1fe7dedf65227d29f286f26ff9c9028b438bb5ef8e69acc036f14767?includeHex=true`
`
Address : tb1qg3clk4hg6ee4afcp66myz3wg52z9gwjtf4384u, mnemonics: stone average inherit endorse cloth tomato tree vital review shrug process shove

below is my code on react native

    let hdNode = bip32.fromSeed(seed)

    const masterFingerprint = hdNode.fingerprint

    const path = "m/84'/0'/0'/0/0";

    let childNode = hdNode.derivePath(path)

    const pubkey = childNode.publicKey;

    const prvKey = childNode.privateKey

    let external = childNode.derive(1)

    console.log("_____",pubkey.toString('hex'))

    let redeemScript = (bitcoin.payments.p2wpkh({pubkey: external.publicKey,network:bitcoin.networks.testnet}))

    console.log("++++++",redeemScript.address,"From",from)

    const psbt = new bitcoin.Psbt({ network: bitcoin.networks.testnet }) 

    const updateData = {
      bip32Derivation: [
        {
          masterFingerprint,
          path,
          pubkey,
        },
      ],
    };
    fetch('https://api.blockcypher.com/v1/btc/test3/addrs/'+redeemScript.address)
                .then((response)=>response.json()) 
                .then(async(response)=> {
                    
                 let trxhash = response.txrefs[0].tx_hash
                    
                 fetch('https://api.blockcypher.com/v1/btc/test3/txs/'+trxhash+'?includeHex=true')
                    .then((resp)=>resp.json())
                    .then(async(resp)=> {
             
                     const isSegwit = resp.hex.substring(8, 12) === '0001'
                   
                     let utxo = resp
                     if (isSegwit) { 
                          psbt.addInput({
                            hash: utxo.hash,
                            index: utxo.vout_sz,
                            witnessUtxo: { 
                              
                              script: Buffer.from(p2sh.output),//Buffer.from(utxo.inputs[1].script,'hex'),
                              value: Number(parseInt(response.final_balance))
                            },
                            redeemScript:Buffer.from(p2sh.redeem.output)
                          })
                     } else {
                          let vout =0;
                          utxo.outputs.forEach(x=>{
             
                            psbt.addInput({
                              hash: utxo.hash,
                              index: vout,//utxo.vout_sz,
                              
                              nonWitnessUtxo: Buffer.from(resp.hex,'hex') , 
                              redeemScript:Buffer.from(x.script)
                            })  
                            vout+=1
                          })
                          
                        }
                        psbt.updateInput(0,updateData)

                        let vl = (parseFloat(value)*100000000)
                        psbt.addOutput({ address: to, value: vl })

                      
                        let vl2 = parseInt(Number(parseInt(response.final_balance))-((parseFloat(value)-0.005)*100000000))

                        psbt.addOutput({ address: from, value: vl2})
                        
                        
                       psbt.signInputHD(0,hdNode)
                       
                        
                        
                        
                    }).catch((error)=>{
                        alert("Error Occured" + error);
                        console.log(error)
                    })
                }
                )
                .catch((error)=>{
                    alert("Error Occured" + error);
                    console.log(error)
                })`

**Comment by junderw** [comment]
Your path is `m/84'/0'/0'/0/0` but you are deriving an extra `derive(1)` which will make `external` into `m/84'/0'/0'/0/0/1`

Don't do the extra derive.
