### ISSUE TITLE
How to create a Taproot address from a mnemonic seed and then an output script example?

### ISSUE THREAD

**Issue by BasedOrg** [bitcoinjs/bitcoinjs-lib#1873]
Can we please get an example of how to go from creating a seed/mnemonic to a taproot address and then a p2tr with that address?

It would be a huge help to see it go from end to end and then finally spend that output.

Thanks in advance

**Comment by junderw** [comment]
Added an example. Let me know if you have any questions.

**Comment by BasedOrg** [comment]
This works great! Quick question... How can we get the xpub from the xprv (rootKey)?
