### ISSUE TITLE
Upgrade to different hashing library

### ISSUE THREAD

**Issue by paulmillr** [bitcoinjs/bitcoinjs-lib#1878]
Continuing discussion in #1781. I suggest to replace those:

    "create-hash": "^1.1.0",
    "ripemd160": "^2.0.2",

With audited noble-hashes. Would you merge the PR if everything is smooth?

create-hash is at least 5 dependencies: https://bundlephobia.com/package/create-hash@1.2.0

**Comment by junderw** [comment]
I've already personally audited noble-hashes with the merge into bip32, I would be fine merging it here too.

**Comment by paulmillr** [comment]
gh-1879
