### ISSUE TITLE
Preventing the change outputs in a Psbt

### ISSUE THREAD

**Issue by brinzi** [bitcoinjs/bitcoinjs-lib#1882]
Let's say we have the following scenario.  

Alice and Bobb want to split the funds from a multi-signature UTXo holding 1BTC. The flow is that Allice would receive 60% of the funds while Bob receives the rest.

Is it possible for Bob to create the transaction saying that the Input UTXO would go to:
-- output 0 --> Would go to Alice's public key, and have a value of 0.6BTC
-- output 1 --> would go to Bob's public key, and have a value of 0.4BTC.

Bob would partially sign this transaction and send it to Alice. But how does bob make sure Alice will not change the output structure?

**Comment by junderw** [comment]
The default sighash for the signature covers the outputs.

After one person signs, no one can add inputs or add outputs or change the outputs unless the sighash allows that.
