### ISSUE TITLE
Official reproducible builds using subresource integrity?

### ISSUE THREAD

**Issue by RobinLinus** [bitcoinjs/bitcoinjs-lib#1887]
Have you considered using [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) and reproducible builds for a browser library? 

Developers could use for example

```html
<script src="https://my-cdn.com/bitcoinjs-lib.min.js"
  integrity="sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"
  crossorigin="anonymous"></script>
```

assuming that there is a relatively stable version such that the corresponding hash `sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC` has time to spread across the internet which increases confidence in the sense of how many eyeballs have seen this exact version.

**Comment by junderw** [comment]
Many years ago we managed an "official" built version, which was immediately cloned with similar looking builds that had backdoors in them.

We realized that people who don't want to put in the effort to build the minimized JS themselves are usually 99% of the time not going to verify some SRI hash against our github etc.

So our policy is:
Verify the source yourself, then build it yourself.
