### ISSUE TITLE
Ordinals inscriptions example

### ISSUE THREAD

**Issue by PoW-chain** [bitcoinjs/bitcoinjs-lib#1888]
Please post an example of how to create an ordinals inscription with different media types.

**Comment by junderw** [comment]
There have been dozens of protocols for storing various data and NFTs on the Bitcoin blockchain for many years.

We have never created an example for those, examples for those protocols are best left to related repos.

See #1176 discussion.

That said. People who find this issue when searching are free to post examples as a reply to this issue.

**Comment by junderw** [comment]
Oh btw someone posted an example here: https://github.com/bitcoinjs/bitcoinjs-lib/issues/1883#issuecomment-1747448779
