### ISSUE TITLE
No ECC Library provided. You must call initEccLib() with a valid TinySecp256k1Interface instance

### ISSUE THREAD

**Issue by MadhuraJoshi1** [bitcoinjs/bitcoinjs-lib#1889]
I am able to get transaction hex to send bitcoins from native segwit address to legacy , nested segwit and native segwit address but when i try to send bitcoin from native segwit to taproot address I am not able to add the outputs.

Here I am trying to add output for taproot address but it throws " No ECC Library provided. You must call initEccLib() with a valid TinySecp256k1Interface instance " error .

psbt.addOutput({
address: tb1p.......,
value: amount
});

**Comment by junderw** [comment]
As you can see here:
https://github.com/bitcoinjs/bitcoinjs-lib/blob/v6.1.0/test/integration/taproot.spec.ts#L3-L15

You need to import an ecc library that is compatible with bitcoinjs-lib, and call initEccLib (which is at the root of this library) to load in an ecc library to calculate the address correctly.

If you can't use WASM in your project, then other people have suggested alternative implementations.
https://github.com/bitcoinjs/bitcoinjs-lib/issues/1781#issuecomment-1302025310

**Comment by Mprogrammer2020** [comment]
Hello @junderw ,

I'm encountering the following error while using `BabylonBtcStakingManager` from the `@babylonlabs-io/btc-staking-ts` package:

```
Error: No ECC Library provided. You must call initEccLib() with a valid TinySecp256k1Interface instance
```

I’ve already initialized the ECC library at the root of my application like this:

```
// In my app entry file (_app.tsx)
import * as bitcoin from "bitcoinjs-lib";
import * as ecc from "tiny-secp256k1";

bitcoin.initEccLib(ecc);
```

And I’m using the staking manager like this:

```
import { BabylonBtcStakingManager } from "@babylonlabs-io/btc-staking-ts";

const stakingManager = new BabylonBtcStakingManager(...);

const { signedBabylonTx } = await stakingManager.postStakeRegistrationBabylonTransaction(...);
```


Despite initializing `bitcoinjs-lib` with `tiny-secp256k1`, I’m still receiving the same ECC error when calling `postStakeRegistrationBabylonTransaction`.


Let me know if this flow is correct. and let me know that how this will work.
