### ISSUE TITLE
Where are store the private keys?

### ISSUE THREAD

**Issue by A2DNEW** [bitcoinjs/bitcoinjs-lib#1895]
Hi,
I want to use this library.
After create new wallet address, where are save the private keys?
I know if I run a `bitcoind` server, the keys save on my own server.
But this library use which server for store the keys?

**Comment by junderw** [comment]
This library doesn't have any key storage.

You need to figure out how/where to store the keys yourself. Every project is different.

Usually you want to encrypt your private keys when storing them.

**Comment by A2DNEW** [comment]
Thank you.
So, if private keys not store anywhere, how new wallet address will add to blockchain?

**Comment by junderw** [comment]
They are stored somewhere.

Key storage is outside the scope of this library.

You can look at some Bitcoin wallet applications that are open source and see how they store the keys.
