### ISSUE TITLE
psbt taproot with sighash flags fails to finalize

### ISSUE THREAD

**Issue by jlautner** [bitcoinjs/bitcoinjs-lib#1902]
When creating a taproot input (p2tr) that has any sigHash flags set, the signing produces a tapKeySig that is 65 bytes.
This causes an error when trying to finalize the psbt.  65 bytes should be allowed according to the standard.
Not sure how to get this to work, as it won't finalize, please help:

```
	psbt.addInput({ 
		hash: utxo.txid, 
		index: utxo.vout, 
		sequence: 1, //RBF BIP125 allows resending transaction with higher gas
		witnessUtxo: { value: utxo.value, script: addressObj.key.output },
		tapInternalKey: addressObj.key.childNodeXOnlyPubkey,
 		sighashType: bitcoin.Transaction.SIGHASH_SINGLE | bitcoin.Transaction.SIGHASH_ANYONECANPAY
	});
	
	psbt.addOutput({
		address: paymentAddress,
		value: price
	});
	
	psbt.signInput(0,tweakSigner,[bitcoin.Transaction.SIGHASH_SINGLE|bitcoin.Transaction.SIGHASH_ANYONECANPAY]);

	psbt.finalizeAllInputs();
```
error is:
'Expected property "signature" of type Buffer(Length: 64), got Buffer(Length: 65)'

According to BIP 174: https://bips.dev/174/ it should allow for 64 or 65 bytes:

<html>
<body>

Taproot Key Spend Signature | PSBT_IN_TAP_KEY_SIG = 0x13 | None | No key data | <64 or 65 byte signature> | The 64 or 65 byte Schnorr signature for key path spending a Taproot output. Finalizers should remove this field after PSBT_IN_FINAL_SCRIPTWITNESS is constructed.
-- | -- | -- | -- | -- | --

</body>
</html>

TfPropertyTypeError {message: 'Expected property "signature" of type Buffer(Length: 64), got Buffer(Length: 65)', __label: undefined, __property: 'signature', __type: 'Buffer(Length: 64)', __value: {…}, …}
message
: 
"Expected property \"signature\" of type Buffer(Length: 64), got Buffer(Length: 65)"
__label
: 
undefined
__property
: 
"signature"
__type
: 
"Buffer(Length: 64)"
__value
: 
{}
__valueTypeName
: 
"Buffer(Length: 65)"
stack
: 
"Error: Expected property \"signature\" of type Buffer(Length: 64), got Buffer(Length: 65)\n    at captureStackTrace (chrome-extension://ohokmabhgknbbgienmbdbkbiieaaiblc/js/bitcoinjs-lib.js:16139:11)\n    at tfSubError (chrome-extension://ohokmabhgknbbgienmbdbkbiieaaiblc/js/bitcoinjs-lib.js:16218:3)\n    at _object (chrome-extension://ohokmabhgknbbgienmbdbkbiieaaiblc/js/bitcoinjs-lib.js:16443:15)\n    at typeforce (chrome-extension://ohokmabhgknbbgienmbdbkbiieaaiblc/js/bitcoinjs-lib.js:16559:9)\n    at typeforce (chrome-extension://ohokmabhgknbbgienmbdbkbiieaaiblc/js/bitcoinjs-lib.js:16565:10)\n    at Object.p2tr (chrome-extension://ohokmabhgknbbgienmbdbkbiieaaiblc/js/bitcoinjs-lib.js:4499:25)\n    at Psbt._finalizeTaprootInput (chrome-extension://ohokmabhgknbbgienmbdbkbiieaaiblc/js/bitcoinjs-lib.js:5461:32)\n    at Psbt.finalizeInput (chrome-extension://ohokmabhgknbbgienmbdbkbiieaaiblc/js/bitcoinjs-lib.js:5402:19)\n    at chrome-extension://ohokmabhgknbbgienmbdbkbiieaaiblc/js/bitcoinjs-lib.js:5396:56\n    at Array.forEach (<anonymous>)"
[[Prototype]]
: 
Error

**Comment by junderw** [comment]
See existing PR #1884

**Comment by roadbuilder** [comment]
> See existing PR #1884

thank you so much!  I had already been doing something similar, but this is even better.  My quick javascirpt fix in bitcoinjs-lib is :
