### ISSUE TITLE
Checking address balance (mainnet or testnet)

### ISSUE THREAD

**Issue by abdurahmanshiine** [bitcoinjs/bitcoinjs-lib#1906]
Hi there,

I'm building a Bitcoin wallet with this library and for that I need to be able to check addresses balances. Currently, I'm in the testing face so I would need to query account balances against the testnet. How can I accomplish that with this library?

**Comment by junderw** [comment]
You can't. This library only deals with data structures and key signing etc.

We have an unmaintained chain indexer in another repository, but for testing using mempool's testnet API should be sufficient.
