### ISSUE TITLE
how to run on web browser

### ISSUE THREAD

**Issue by ocvcoin** [bitcoinjs/bitcoinjs-lib#1908]
`npm install bitcoinjs-lib browserify`
 `npx browserify --standalone bitcoin - -o bitcoinjs-lib.js <<<"module.exports = require('bitcoinjs-lib');"`

hi
I ran these commands given in the instructions. bitcoinjs-lib.js packed without any problem. but I couldn't find any documentation. how can i use it? i tried as follows but i get `Uncaught ReferenceError: require is not defined` error.

```

<script type="module">import "./bitcoinjs-lib.js"</script>

<script>

var bitcoin = require('bitcoinjs-lib');

// generate a new random key pair
var keyPair = bitcoin.ECPair.makeRandom();

// create a new Bitcoin address from the public key
var { address } = bitcoin.payments.p2pkh({
  pubkey: keyPair.publicKey
});

console.log('New Bitcoin address:', address);

</script>


```

**Comment by junderw** [comment]
`--standalone bitcoin` means that you `<script src="./bitcoinjs-lib.js"></script>` once and then there is a `bitcoin` object in the global scope.

**Comment by ocvcoin** [comment]
error again `Uncaught TypeError: bitcoin.ECPair is undefined`

```
<script src="./bitcoinjs-lib.js"></script>

<script>


// generate a new random key pair
var keyPair = bitcoin.ECPair.makeRandom();

// create a new Bitcoin address from the public key
var { address } = bitcoin.payments.p2pkh({
  pubkey: keyPair.publicKey
});

console.log('New Bitcoin address:', address);

</script>

```

**Comment by junderw** [comment]
ECPair was removed many..... many years ago...
