### ISSUE TITLE
What is causing the 'Cannot read properties of undefined (reading 'fromPrivateKey')'

### ISSUE THREAD

**Issue by ghasemsabery** [bitcoinjs/bitcoinjs-lib#1911]
What could be causing the "Cannot read properties of undefined (reading 'fromPrivateKey')" error in the following code using bitcoinjs-lib version "^6.1.0"? The code provided is:
`const privateKey = Buffer.from('cTd1r5BSCZKPeNPVt7K4jfbqGqyok7zUcfwvgKk48WfweTYnhkPN', 'hex');
console.log(privateKey);
const keyPair = bitcoin.ECPair.fromPrivateKey(privateKey);
console.log(keyPair);
return false;`
error :
TypeError: Cannot read properties of undefined (reading 'fromPrivateKey')
    at BtcService.<anonymous> (D:\project\wallet-management\src\modules\bitcoin\btc.service.ts:114:36)

**Comment by junderw** [comment]
bitcoinjs-lib hasn't included ECPair since v3 which is over 5 years old at this point.

ChatGPT tends to recommend very VERY old versions of libraries, so be careful blindly copy pasting it.
