### ISSUE TITLE
Error signing input

### ISSUE THREAD

**Issue by erbelion** [bitcoinjs/bitcoinjs-lib#1916]
I have a bip32 api object `root` created like this:
```
import bip39 from 'bip39'
const seed = bip39.mnemonicToSeedSync(‘your twelve word seed phrase…’)
const root = bip32.fromSeed(seed)
```
and I need to sign inputs in psbt transaction.

```
const keypair = ECPairFactory(ecc).fromWIF(root.toWIF(), network)

psbt.signInput(0, keypair)
psbt.signInput(1, keypair)

psbt.finalizeAllInputs()
```

It outputs with error `Error: Can not sign for this input with the key xxxxxxxx`. Am I doing something wrong with conversion from bip32 to ecpair?

...

I realized that i need to use p2sh-p2wpkh, like in https://github.com/bitcoinjs/bitcoinjs-lib/issues/1454#issuecomment-631115171 so that derived addresses could be signed.
I copied getAddress function, like this:
```
function getAddress(node, network) {
	return bitcoin.payments.p2sh({
		redeem: bitcoin.payments.p2wpkh({ pubkey: node.publicKey, network }),
		network,
	}).address;
}
```
but now i get error `Error: scriptPubkey is P2SH but redeemScript missing`

**Comment by erbelion** [comment]
When i sign inputs this way:
```
psbt.signAllInputs(keypair)

psbt.finalizeAllInputs()
```
`signAllInputs()` doesn't throw any error, but `finalizeAllInputs()` does:
```
Error: Can not finalize input #0
```

**Comment by erbelion** [comment]
I realized that i need to use p2sh-p2wpkh, like in https://github.com/bitcoinjs/bitcoinjs-lib/issues/1454#issuecomment-631115171 so that derived addresses could be signed.
I copied getAddress function, like this:
```
function getAddress(node, network) {
	return bitcoin.payments.p2sh({
		redeem: bitcoin.payments.p2wpkh({ pubkey: node.publicKey, network }),
		network,
	}).address;
}
```
but now i get error `Error: scriptPubkey is P2SH but redeemScript missing`

**Comment by junderw** [comment]
1. It is not conventional to use the root of an HD wallet for anything. Various derivation schemes (BIPs 44, 49, 84 are the most popular for single sig, with 84 being recommended (for now)) exist to figure out how to get the keys for your wallet.
2. Your inability to sign is irrelevant to the derivation scheme. As long as your address generation and your signing key derivation use the same path for derivation, it does not matter. It seems like you're getting confused by p2sh from your final comment.
3. In the case of P2SH, you need a redeemScript for any input that contains P2SH anywhere in it... same thing for P2WSH and witnessScript. In the case of p2sh-p2wpkh, the redeemScript should be the p2wpkh locking script, which can be taken from the p2wpkh payment object.

If you sign using the same key derivation you used when generating the address, and you use the same scripts, then all you need is to make sure that all the necessary scripts are in the input and you will be able to sign the input.
