### ISSUE TITLE
Help with signing Multisig 2-3 P2WSH PSBT transaction

### ISSUE THREAD

**Issue by puskin94** [bitcoinjs/bitcoinjs-lib#1921]
Hi all!  
I am struggling to create , sign and broadcast a Multisig P2WSH transaction... I tried many different variants but I am always ending up with the `{"code":-22,"message":"TX decode failed. Make sure the tx has at least one input."}` error when I try to broadcast it.  
Here you can find a "working" example, running on the testnet:

```js
const bitcoin = require('bitcoinjs-lib');
const ecc = require('tiny-secp256k1');
const {ECPairFactory} = require('ecpair');
const mempoolJS = require("@mempool/mempool.js");

const NETWORK = bitcoin.networks.testnet;
const MEMPOOL_NETWORK = 'testnet'; // signet, testnet, mainnet

const ORIGINAL_TRANSACTION_ID = 'bee812cd4eaeefbcd6f7859e496ebdd5c9eda7199c9ae8a233c2ed09a2b5e199';
const ORIGINAL_TRANSACTION_VOUT = 1;

const BYTES_PER_P2SH_ADDRESS = 177;
const TRANSACTION_INPUT_AMOUNT = 1040;
const TRANSACTION_OUTPUT_BUYER_ADDRESS = 'tb1q7mu5sv44cde4lhq2rmlk68qyyvvn39rvxvj895';
const TRANSACTION_OUTPUT_BUYER_AMOUNT = 500;

const mempool = mempoolJS({hostname: 'mempool.space', network: MEMPOOL_NETWORK});

const ECPair = ECPairFactory(ecc);
const validator = (pubkey, msghash, signature,) => ECPair.fromPublicKey(pubkey).verify(msghash, signature);

const keys = {
    sellerKeys: {
        privateKey: '0794bb8053abc751d8dbc3905782c2342d9182df07e35ddd136f14a9e8a78ee3',
        publicKey: '035486868be8968643d7ac686fbe93db127dc9265e629132cf6887cf2cd1c4ec2e'
    },
    buyerKeys: {
        privateKey: '09af5c1d447d7e8db0621df9162b6176c1f236d017ef893fe144f290cd883c8f',
        publicKey: '02cc69a1feb2e9ab5b4ef4001cfa54b3641e383bb16d076fb7c46f2445a7bb6422'
    },
    systemKeys: {
        privateKey: '5J19N7WUBGwvjoa1Cs5bNeiQeTFUkpRysVhM6zSVBq7UpB1GHjP',
        publicKey: '0397b424b104690877e2be37e3180791811e7c86441185a15da169b2ab4cb89ebf'
    }
};

function bufferFromHex(str) { return Buffer.from(str, 'hex'); }

const pubkeys = [keys.sellerKeys.publicKey, keys.buyerKeys.publicKey, keys.systemKeys.publicKey].map(bufferFromHex);

async function main() {
    const p2ms = bitcoin.payments.p2ms({m: 2, pubkeys, network: NETWORK});

    const p2wsh = bitcoin.payments.p2wsh({redeem: p2ms, network: NETWORK});

    const {halfHourFee} = await mempool.bitcoin.fees.getFeesRecommended();

    const psbt = new bitcoin.Psbt({network: NETWORK});
    console.log(1, {hex: psbt.toHex()});

    console.log({witnessScript: p2wsh.redeem.output.toString('hex')});
    psbt.addInput({
        hash: ORIGINAL_TRANSACTION_ID,
        index: ORIGINAL_TRANSACTION_VOUT,
        witnessScript: p2wsh.redeem.output,
        witnessUtxo: {
            script: p2wsh.output, // https://github.com/bitcoin-studio/Bitcoin-Programming-with-BitcoinJS/pull/6/files
            value: TRANSACTION_INPUT_AMOUNT,
        }
    });
    console.log(2, {hex: psbt.toHex()});

    psbt.addOutput({
        address: TRANSACTION_OUTPUT_BUYER_ADDRESS,
        value: TRANSACTION_OUTPUT_BUYER_AMOUNT - (halfHourFee * BYTES_PER_P2SH_ADDRESS),
    });
    console.log(3, {hex: psbt.toHex()});
    
    psbt.signInput(0, ECPair.fromPrivateKey(bufferFromHex(keys.sellerKeys.privateKey)));
    console.log(5, {hex: psbt.toHex()});
    psbt.signInput(0, ECPair.fromPrivateKey(bufferFromHex(keys.buyerKeys.privateKey)));
    console.log(6, {hex: psbt.toHex()});

    psbt.validateSignaturesOfInput(0, validator, bufferFromHex(keys.sellerKeys.publicKey));
    console.log(7, {hex: psbt.toHex()});
    psbt.validateSignaturesOfInput(0, validator, bufferFromHex(keys.buyerKeys.publicKey));
    console.log(8, {hex: psbt.toHex()});

    psbt.finalizeAllInputs();
    console.log(9, {hex: psbt.toHex()});

    const txHex = psbt.extractTransaction(true).toHex();
    console.log(10, {hex: psbt.toHex()});

    try {
        const txid = await mempool.bitcoin.transactions.postTx({txHex});

        console.log({txid});
    } catch (e) {
        if (e.isAxiosError) {
            console.log('axios error', e?.response?.data);
        } else {
            console.log('error', e);
        }
    }
}

main();
```

I am using the [Bitcoin-JS web UI](https://bitcoincore.tech/apps/bitcoinjs-ui/index.html) to validate each step.  
This is what the UI is looking like after Inputs and the Output is added to the PSBT:  

![image_2023-05-20_11-23-08](https://github.com/bitcoinjs/bitcoinjs-lib/assets/8344987/df8d484f-a065-4035-8f7d-653daab4c596)

And this is how it looks like after the first signature (the one from the seller keys):

![image_2023-05-20_11-20-02](https://github.com/bitcoinjs/bitcoinjs-lib/assets/8344987/07fa2159-110f-41fc-adf0-3b2a1b1c8e4f)

In the provided code, the calls to `validateSignaturesOfInput` are returning `true`, so this would tell me that the signing process is correct, but the broadcasting is still telling me that it is not indeed true.

The code above can be ran and executed installing those few dependencies, it is already coming with a real transaction id and all the required keys (don't worry, those are testing keys)

Link to the transaction in the testnet network: https://mempool.space/testnet/tx/bee812cd4eaeefbcd6f7859e496ebdd5c9eda7199c9ae8a233c2ed09a2b5e199

**Comment by junderw** [comment]
Post the code that doesn't work.

Also, post the tx hex that gives you that error.

**Comment by puskin94** [comment]
@junderw the posted code is the code that does not work.

and this is the tx hex:

```
0200000000010199e1b5a209edc233a2e89a9c19a7edc9d5bd6e499e85f7d6bcefae4ecd12e8be0100000000ffffffff014301000000000000160014f6f94832b5c3735fdc0a1eff6d1c04231938946c0400483045022100e11fb6fb5db4f4b22e7ef5ef715584a2e574d4c941adcf4eec63e7d7d7f785e6022024b066b00aeb4275a7e966eca7a98a78b64e61346e9d2a5e7e8f07705cdf2e79014730440220366a8f426a25f491ae037739168ec3b66c0c75f30c5b180504c6a31fbe2c50890220051471ce792fabf9a9ce32c8429234f208f845528086d0e6634453102162974601695221035486868be8968643d7ac686fbe93db127dc9265e629132cf6887cf2cd1c4ec2e2102cc69a1feb2e9ab5b4ef4001cfa54b3641e383bb16d076fb7c46f2445a7bb6422210397b424b104690877e2be37e3180791811e7c86441185a15da169b2ab4cb89ebf53ae00000000
```

**Comment by junderw** [comment]
There is nothing wrong with your tx.

Just to make sure I tried broadcasting to my local testnet node and it was broadcasted to the network.

https://mempool.space/testnet/tx/c0d12078b8988ce5fbe6f7d5db0ec65f3851e3fb54485617c5cd6c679f48a28a

**Comment by junderw** [comment]
It is now in block 2434628 on testnet.

**Comment by junderw** [comment]
Just to clarify. I asked you to give the code that doesn't work because I looked at the code and it looked like it should work.

Then I saw the tx and it was valid.

**Comment by puskin94** [comment]
@junderw this does not make any sense tho... why would I receive that error then? I tried for 3 days straight before posting in here... what is the reason why it would be working now?

**Comment by junderw** [comment]
https://github.com/mempool/mempool.js/blob/HEAD/README-bitcoin.md#post-tx-outspends

Your code:

```js
const txid = await mempool.bitcoin.transactions.postTx({txHex});
```

The example code on the library page:

```js
const postTx = await transactions.postTx({ txhex });
```

Do you see the difference? (look at the `h`)

**Comment by junderw** [comment]
Using TypeScript will catch these types of errors.

**Comment by junderw** [comment]
It is trying to send `undefined` which shows up as `""` an empty string... which will give a parse error.

**Comment by puskin94** [comment]
@junderw I cannot believe this. So much wasted time! Thank you so much for catching it tho.

And, FYI,I am using typescript in the project holding this code but the error was not caught

**Comment by junderw** [comment]
Ahhh, I see mempool.js doesn't have type definitions.

If you use any JS dependencies, it might be a good idea to write your own type definitions. It will give you an opportunity to look into the API to double check you're using the right types.

**Comment by puskin94** [comment]
@junderw you are right... but I was sooo sure I messed up something in the psbt generation that I overlooked the actual failing step... thank you again

**Comment by junderw** [comment]
I usually work backwards.

The first thing I would look at: "What am I sending the API and why would it say I have no inputs?"

Maybe I would go to a website that decodes raw transactions, see it DOES have inputs, then ask myself "Why does the API say I don't have inputs, when I CLEARLY have inputs?"

It immediately narrows the problem down to somewhere in mempool.js or my usage of it.

I would check my usage first before digging into the library to see if the library has a bug... then I would find the typo.

**Comment by puskin94** [comment]
@junderw I am sorry to announce the problem has not been fixed tho... I just tried to adjust the code fixing the typo , but trying another time with another transaction is throwing the same error... this is the txhex:

```
02000000000101afbe6c76e0644ef2e5c20d9bea372ff070ffb693b7425e9e839e2800ab3b0a520000000000ffffffff01eb1d000000000000160014ae20c10c805c812f11ebaaa9bce44b1a936df1070400473044022003b98b8461343ee2492ab4d371435e370babb59bddc58d341fcb6cc0ebdff79a0220572a3f42505c71f4be48e4b3e8e0d257ee8ffab6d777770479a21e080026bd6b0147304402205bb5f9f16a61419fba3d7cb5d9c2939b3eef21ff272cbbdbe8f953a4390bf9f602205100662f0cfe310e693eb1e9f2cbbbde152b7bcec905005514fd086b9eb8728a0169522103204be3a94735803ffa9f94e07bead774ff8dde8de605deb82b638178209cfb0d2102494550dadd1c40cbcf76ee845cdfae315a8aa2c09e24995063481387b2e8a9b3210397b424b104690877e2be37e3180791811e7c86441185a15da169b2ab4cb89ebf53ae00000000
```

the script changed a tiny bit, I am just added another output (as you can see from the decoded hex), but I am still getting the {"code":-22,"message":"TX decode failed. Make sure the tx has at least one input."} error

Any clue on what I am missing this time?

**Comment by junderw** [comment]
Your tx is fine. I just broadcasted it.

Good luck finding the other issues in your code

**Comment by puskin94** [comment]
@junderw thanks for the overview, again. I just wanted to let you know I will give my code the additional look but this is the documentation for mempool.js:

https://mempool.space/testnet/docs/api/rest#post-transaction

as you can see, the documentation is wrong  :) they are saying you should be using `txHex` in the example, but in the source it is `txhex`

**Comment by puskin94** [comment]
@junderw as you mentioned, the tx was correct. I tried to use the apis from `blockstream.info` to broadcast it, and everything is working fine. I guess the documentation is not the only thing that `mempool.space` has.

Thank you again so much for your time
