### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by purpleIQ** [bitcoinjs/bitcoinjs-lib#1925]
Please, I do not know which of the codes I am supposed to edit my parameters into & input in my inspect element. Someone please help me.

**Comment by junderw** [comment]
Please be more specific. I will close this if there's no further clarification.

**Comment by purpleIQ** [comment]
Uhm I meant to divert unconfirmed BTC transactions, I need to input the hash, my wallet & all of that. I do not know where the code I need to copy is located.

**Comment by purpleIQ** [comment]
I clarified further 🙇.

**Comment by junderw** [comment]
I don't understand what you mean...

Try writing some code and asking a specific question about the code, maybe?
