### ISSUE TITLE
Can Support mint、deploy and transfer BRC20 Token ?

### ISSUE THREAD

**Issue by xiaoshengaimm** [bitcoinjs/bitcoinjs-lib#1928]
Can Support mint、deploy and transfer BRC20 Token ?

**Comment by junderw** [comment]
Yes.

**Comment by xiaoshengaimm** [comment]
Some one can write a test case or demo?

**Comment by junderw** [comment]
Is BRC20 not clear enough? Perhaps you should open an issue on the repository where BRC proposals are being managed and ask for clarification.

There are plenty of examples in the repository to show how to manipulate transactions, and BRC20 is merely a specific type of transaction with extra restrictions added on top.

If you have specific questions on how to manipulate transactions in a specific way, I can answer them.

**Comment by wangtao19911111** [comment]
> Some one can write a test case or demo?

wait for you demo
