### ISSUE TITLE
How to use validateSignaturesOfAllInputs

### ISSUE THREAD

**Issue by timechainz** [bitcoinjs/bitcoinjs-lib#1930]
Hi,

I'm trying to verify the signatures of a psbt using validateSignaturesOfAllInputs as described here.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/5d2ff1c61165932e2814d5f37630e6720168561c/ts_src/psbt.ts#L116

The function requires a validator function of type ValidateSigFunction.  Where can I find ValidateSigFunction implementations and/or examples of how to do this?  

I searched for answers and it seems that in the past validateSignaturesOfAllInputs did not require any params but I was unable to find any recent examples of how to validate all signatures. 
https://github.com/bitcoinjs/bitcoinjs-lib/issues/1580

Can someone please point me in the right direction?

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/v6.1.1/test/integration/transactions.spec.ts#L14-L18

In the examples it shows a simple validator, and shows many examples on how to validate (throughout the file. search for the validator variable)

```ts
import * as ecc from 'tiny-secp256k1';
import ECPairFactory from 'ecpair';
const ECPair = ECPairFactory(ecc);

const validator = (
  pubkey: Buffer,
  msghash: Buffer,
  signature: Buffer,
): boolean => ECPair.fromPublicKey(pubkey).verify(msghash, signature);
```

**Comment by timechainz** [comment]
Ahh, perfect.  Thank you!
