### ISSUE TITLE
sign psbt error , Can not finalize taproot input #2. No tapleaf script signature provided.

### ISSUE THREAD

**Issue by cuinima** [bitcoinjs/bitcoinjs-lib#1940]
**### I don't know why this is causing the error, can you help me with the answer, thanks**
![image](https://github.com/bitcoinjs/bitcoinjs-lib/assets/65176389/b7f47908-9721-40b8-99cc-51a95c441c2f)
![image](https://github.com/bitcoinjs/bitcoinjs-lib/assets/65176389/2d617e1b-e031-4538-9c2b-6c4bab0bacf2)
const bip39 = require('bip39')
const bitcoin = require('bitcoinjs-lib')
const ecc = require('tiny-secp256k1')
const { BIP32Factory } = require('bip32')
const bip32 = BIP32Factory(ecc)
const {ECPairFactory} = require('ecpair')
const axios = require('axios');

function base64ToHex(base64) {
    // 将Base64字符串转换为字节数组
    const bytes = atob(base64)
      .split('')
      .map(char => char.charCodeAt(0));
  
    // 将字节数组转换为十六进制字符串
    let hex = '';
    for (let i = 0; i < bytes.length; i++) {
      const byteHex = bytes[i].toString(16).padStart(2, '0');
      hex += byteHex;
    }
    return hex;
  }

function main(psbt_hex){
    const ECPair = ECPairFactory(ecc);
    //设置生成测试or正式环境的钱包
    const network = bitcoin.networks.bitcoin
    // 计算seed:
    const mnemonic = "test test test test test test test test test test test test";
    const seed = bip39.mnemonicToSeedSync(mnemonic);
    const root = bip32.fromSeed(seed,network);
    const path = "m/84'/0'/0'/0/0";
    const keyPair = root.derivePath(path);
    const privateKey = keyPair.toWIF();
    console.log("BTC私钥：", privateKey);
    const publicKey = keyPair.publicKey.toString("hex");
    console.log("BTC公钥：", publicKey);
    let address = bitcoin.payments.p2wpkh({ pubkey: keyPair.publicKey , network:network});
    console.log("BTC地址：", address.address, "\n");

    let psbt = bitcoin.Psbt.fromHex(psbt_hex);
    // 签名该交易
    psbt.signAllInputs(keyPair);
    // 获取完全签名的交易
    psbt.finalizeAllInputs();
    psbt.extractTransaction();
    const rawHex = psbt.extractTransaction().toHex();
    console.log("rawHex",rawHex);
    

}
psbt_base64 ="...";
psbt_hex = base64ToHex(psbt_base64);
main(psbt_hex);

**Comment by junderw** [comment]
The error is clear. Your PSBT is incomplete.

Post the PSBT and maybe I can tell you what's missing.

**Comment by junderw** [comment]
Your inputs are already spent here: https://mempool.space/tx/42272c23589a33f9a4c81511f69e2129065423a5b7c19af883c514b32f25a802

**Comment by junderw** [comment]
Closing due to no response from OP.

**Comment by Taha-daboussi** [comment]
Thanks for the help @junderw  , but are the inputs being already spent related to this error ?
