### ISSUE TITLE
Invalid txHex when trying to perform a transaction

### ISSUE THREAD

**Issue by VanderTrip** [bitcoinjs/bitcoinjs-lib#1942]
Hello!
I am trying to carry out a bitcoin transaction on the testnet network, which involves two p2wpkh type wallets.
For some reason the whole process seems to be fine, except when I send the txHex generated by Psbt to an API like for example: `https://blockstream.info/testnet/api/tx`

Which indicates this API returns: sendrawtransaction RPC error: `{"code":-22,"message":"TX decode failed. Make sure the tx has at least one input."}`

I am not sure if it is the exact error that the response of this API mentions, since I have searched a lot of information and I still cannot solve it, therefore I would like to know the opinion of another person to try to get another point of view.

I leave the essential code involved.

```
    // In this case the transactions starts from getting the sender wallet mnemonics and the receiver wallet address.
    // This process should be the same as perform the transaction directly with the sender PrivateKey.
    setTransaction = async (fromMnemonic: string, toAddress: string, amount: number) => {
        // amount should be in satoshis (100.000.000 satoshis = 1.0 BTC)
        const bip32 = BIP32Factory(ecc);
        const seed = bip39.mnemonicToSeedSync(fromMnemonic);
        const node: BIP32Interface = bip32.fromSeed(seed);
        const child: BIP32Interface = node.derivePath(path);
        const wallet = bitcoin.payments.p2wpkh({ pubkey: child.publicKey, network: network });

        const address = wallet.address;
        if(!address) {
            return;
        }

        const psbt = new bitcoin.Psbt({ network });

        const unspentTransaction = await this.getUnspentTransaction(address);
        if (!unspentTransaction) {
            console.log("error!")
            return;
        }
        if(unspentTransaction.value < amount) {
            console.log("Trying to send more than what the from wallet have.")
            return;
        }

        psbt.addInput({
            hash: unspentTransaction.txid,
            index: 0,
            witnessUtxo: {
                script: Buffer.from(unspentTransaction.scriptPubKey, 'hex'),
                value: unspentTransaction.value
            }
        });

        psbt.addOutput({
            address: toAddress,
            value: amount
        });

        const privateKey = ECPair.fromWIF(child.toWIF());
        await psbt.signInputAsync(0, privateKey);

        psbt.validateSignaturesOfInput(0, validator);
        psbt.finalizeAllInputs();

        const transactionHex = psbt.extractTransaction().toHex();
        this.sendTransaction(transactionHex);
    }

    getUnspentTransaction = (address: string): Promise<LastTransaction> => {
        return new Promise((resolve, reject) => {

            fetch("https://blockstream.info/testnet/api/address/" + address + "/utxo")
                .then(response => response.json())
                .then((transactions: TransactionsResponse[]) => {

                    const firstTransaction = transactions[0];
                    if(!firstTransaction) {
                        reject();
                        return;
                    }

                    fetch("https://blockstream.info/testnet/api/tx/" + firstTransaction.txid)
                        .then(response => response.json())
                        .then((response: VoutsResponse) => {

                            const vout = response.vout[firstTransaction.vout];
                            if(!vout || !firstTransaction.txid || !vout.scriptpubkey) {
                                reject();
                                return;
                            }

                            resolve({
                                txid: firstTransaction.txid,
                                scriptPubKey: vout.scriptpubkey,
                                value: firstTransaction.value
                            });

                        })
                        .catch(error => {
                            console.error('Error al obtener las transacciones no gastadas:', error);
                            reject();
                        });

                })
                .catch(error => {
                    console.error('Error al obtener las transacciones no gastadas:', error);
                    reject();
                });
        });
    }

    sendTransaction = async (txHex: string): Promise<string> => {
        return new Promise((resolve, reject) => {
            fetch(
                'https://blockstream.info/testnet/api/tx',
                {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        tx: txHex
                    })
                })
                .then(response => response.text())
                .then(result => {
                    resolve(result);
                })
                .catch(error => {
                    console.error('Error al obtener las transacciones no gastadas:', error);
                    reject('Error sending transaction: ' + error);
                });
        });
    }
```

An example API response ("https://blockstream.info/testnet/api/address/" + address + "/utxo") is:
`[{"txid":"7cd247189d4d73a25d4f946801426ad4dc636ea8133e38c1225011c673b8f1fe","vout":1,"status":{"confirmed":true,"block_height":2438094,"block_hash":"000 0000000001a58bb96313ee4c681167b1b489541095e86875dbebe8fe762cf","block_time":1687053434},"value ":12700}]`

An example API response ("https://blockstream.info/testnet/api/tx/" + firstTransaction.txid) is:
`{"txid":"7cd247189d4d73a25d4f946801426ad4dc636ea8133e38c1225011c673b8f1fe","version":2,"locktime":2438093,"vin":[{"txid":"a993e02b5980c47e107e33df2c1572058adfbd9aac7a81d04612c05b57aed921","vout":0,"prevout":{"scriptpubkey":"00148684d9165a4f29234ef9783a5e40e7fcda0d64e7","scriptpubkey_asm":"OP_0 OP_PUSHBYTES_20 8684d9165a4f29234ef9783a5e40e7fcda0d64e7","scriptpubkey_type":"v0_p2wpkh","scriptpubkey_address":"tb1qs6zdj9j6fu5jxnhe0qa9us88lndq6e88k2uh9z","value":3787881},"scriptsig":"","scriptsig_asm":"","witness":["304402201b0dcc33ff1885989ad7abf89cf07e015278e5384c854da9f648aeea42518d2a0220249c8dfad15141f2c33cf6940364bd41f6702285a7afa688836988d4f9cb2f0f01","020d90c2d94bf65a9518442620d61199e20ce6391f76123dc95bfdc309699d49cd"],"is_coinbase":false,"sequence":4294967294}],"vout":[{"scriptpubkey":"00149afeafb227408096630cfe7406f3d27796b69cb0","scriptpubkey_asm":"OP_0 OP_PUSHBYTES_20 9afeafb227408096630cfe7406f3d27796b69cb0","scriptpubkey_type":"v0_p2wpkh","scriptpubkey_address":"tb1qntl2lv38gzqfvccvle6qdu7jw7ttd89scfpstv","value":3775040},{"scriptpubkey":"0014ae25736da157c8a3b589c7fa5ab386125624cc48","scriptpubkey_asm":"OP_0 OP_PUSHBYTES_20 ae25736da157c8a3b589c7fa5ab386125624cc48","scriptpubkey_type":"v0_p2wpkh","scriptpubkey_address":"tb1q4cjhxmdp2ly28dvfcla94vuxzftzfnzgr53k55","value":12700}],"size":222,"weight":561,"fee":141,"status":{"confirmed":true,"block_height":2438094,"block_hash":"0000000000001a58bb96313ee4c681167b1b489541095e86875dbebe8fe762cf","block_time":1687053434}}`

Thank you in advance for anyone who offers another opinion.
Greetings!!

**Comment by junderw** [comment]
From https://github.com/Blockstream/esplora/blob/896ea83f8448dc1c17d3189c734c235b42740a9a/API.md#post-tx

> The transaction should be provided as hex in the request body. The txid will be returned on success.

You are providing a JSON object with the tx hex in the "tx" key of the JSON... which is completely random, and the API documents make no mention of this format of POST request anywhere.

Simply:

```
{
  method: 'POST',
  body: txHex,
}
```
