### ISSUE TITLE
How to generate infinite BTC addresses from XPUB?

### ISSUE THREAD

**Issue by ruben2k1** [bitcoinjs/bitcoinjs-lib#1955]
I don't know how to do it

I have tried this but it always returns the same

```
const generateAddress = (XPUB) => {
    const publicKeyBuffered = Buffer.from(XPUB, 'hex');
    const { address } = bitcoin.payments.p2wpkh({ pubkey: publicKeyBuffered });

    return address;
}

const address = generateAddress('0265e921f70360fc6013bcba62798ba02da6d959ab990739e56dcd3c0b308872df');

console.log(address);
```

**Comment by junderw** [comment]
`0265e921f70360fc6013bcba62798ba02da6d959ab990739e56dcd3c0b308872df` is not an xpub...

I am confused. What are you asking?

**Comment by junderw** [comment]
Take a look at this:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/v6.1.3/test/integration/bip32.spec.ts

`tprv` is the testnet private key version of xpub. So all you need to do is not use testnet and input an xpub and you'll get an HD keypair for derivation.

**Comment by ruben2k1** [comment]
What is `0265e921f70360fc6013bcba62798ba02da6d959ab990739e56dcd3c0b308872df`?

I mean, when you create a Bitcoin wallet you create the private key, the public master key (XPUB) and from the XPUB all the BTC addresses are created.

It's like that, isn't it?

**Comment by junderw** [comment]
pieter has a nice example here:

https://github.com/bitcoinjs/bitcoinjs-lib/issues/1454#issuecomment-631115171

The example after he says "Found it, I think." should help explain things.
