### ISSUE TITLE
Considering Output/s in Fee Calculation

### ISSUE THREAD

**Issue by muhammad-fahim-asim** [bitcoinjs/bitcoinjs-lib#1960]
@junderw  From the calculation you've mentioned with "fee cost of the input" at https://github.com/bitcoinjs/bitcoinjs-lib/issues/1867 ,  why did you skip "output/s fee"? as it also will be paid through value in input/s. So in this regard, I assume the calculations will be:

1 P2PKH input = 148 vBytes
1 P2PKH output (receiver address) = 34 vBytes
1 P2PKH output (change address) = 34 vBytes

if the current fee rate is 15 then we should consider UTXO to add worth 15*(148+34+34) = 3240 satoshis, also, all inputs worth less than 3x the fee would be ignored so 3 * 15 * (148+34+34) = 9720. for 2 inputs it'll be 2 * 9720, for 3 inputs, 3 * 9720.

If it's all correct then the dust amount you've mentioned is 600, such dust UTXOs can never be considered even fee rate is 1 as 3 * 1 * (148+34+34) = 648 which is less than 600

Please let me know if my calculations are wrong, where I'm mistaken, and how can be tackled, Thank you

**Comment by junderw** [comment]
The question of "is this UTXO large enough to include in this transaction and still have any meaning" is separate from "do I have enough UTXO value in my inputs to cover the fees of all the outputs?" are two separate questions.
