### ISSUE TITLE
Uncaught TypeError: payload.readUint8 is not a function at fromBase58Check in browser environment.

### ISSUE THREAD

**Issue by bomzj** [bitcoinjs/bitcoinjs-lib#1969]
The following call to `payload.readUint8(0);` fails since readUint8 doesn't exist in browser environment. Browser has `readUInt8` instead that differs in Capital 'I', compare 'Uint8' vs 'UInt8', so it's a kind of typo issue.

bitcoinjs-lib/src/address.js
```js 
function fromBase58Check(address) {
  const payload = Buffer.from(bs58check.decode(address));
  // TODO: 4.0.0, move to "toOutputScript"
  if (payload.length < 21) throw new TypeError(address + ' is too short');
  if (payload.length > 21) throw new TypeError(address + ' is too long');
  const version = payload.readUint8(0);
  const hash = payload.slice(1);
  return { version, hash };
}

```

**Comment by junderw** [comment]
Which package are you using for `Buffer` support in the browser.

This is an issue with that package.

**Comment by junderw** [comment]
https://github.com/feross/buffer/blob/v6.0.3/index.js#L1163-L1168

This package (which is commonly used in the browser to add Buffer support) supports both.

NodeJS also supports both.

Supporting both is spec for the Buffer API, so if your shim doesn't support both, please raise an issue with them.

Thanks.

**Comment by bomzj** [comment]
@junderw there is no problem with `Buffer.prototype.readUint8` from https://github.com/feross/buffer in browser, so I can't raise an issue in Buffer repository.

The problem is with bitocoinjs-lib as I described above. As a workaround I have to use:
```js
Uint8Array.prototype.readUint8 = Buffer.prototype.readUint8
```
before calling to bitcoinjs-lib API.

**Comment by junderw** [comment]
> there is no problem with Buffer.prototype.readUint8 from https://github.com/feross/buffer in browser

I never said there was. Obviously you are not using that package, since that package has the `readUint8` method.

I am telling you to raise an issue at the package that *you are using*.

---

Please create a repository that reproduces the error and demonstrates your issue. Until then there's nothing we can do.

**Comment by junderw** [comment]
I can't see what bundler `stackblitz` is using. I don't know their bundler settings. I don't know how they are introducing their shims.

Please create a local project that can be installed with `npm install` and built with `npm run build` etc. and that I can load in a browser on my machine and verify the issue.

**Comment by junderw** [comment]
6.1.4 has been released, which will fix the issue with broken bundlers.
