### ISSUE TITLE
Error: Input #0 has witnessUtxo but non-segwit script: 

### ISSUE THREAD

**Issue by zikyfranky** [bitcoinjs/bitcoinjs-lib#1973]
I keep getting hit with this error message, I've gone through other issues, googled, and tried everything possible, I can't seem to solve the error.

I'm making use of Psbt to create my transaction, when I try adding an input, it throws that error, now every input if made from the utxo that's gotten from blockchain.info API, so it's safe to say the values are not hardcoded which would be prone to user(me) mistake.

This is what my code looks like 

```
// unspent_outputs is an array of `address` utxos, with keys `tx_hash_big_endian`, `value` and `tx_output_n`
const {data: { unspent_outputs }} = await axios.get(`https://blockchain.info/unspent?active=${address}`);
...
...
for (const unspent of unspent_outputs) {
    let innerAmount = BigInt(unspent.value);

    // Fetching the raw transaction hex so I can determine if the transaction is a segwit or not
    const { data: rawTransaction } = await axios.get(`https://blockstream.info/api/tx/${unspent.tx_hash_big_endian}/hex`);
    
    const witnessUtxo =Transaction.fromHex(rawTransaction).outs[unspent.tx_output_n];
    const nonWitnessUtxo = Buffer.from(rawTransaction, "hex");

   // check if it's a Segwit or Non-Segwit transaction
   const isSegwit = rawTransaction.substring(8, 12) === "0001";
   const witnessData = isSegwit ? { witnessUtxo } : { nonWitnessUtxo };

    inputs.push({hash: unspent.tx_hash, index: unspent.tx_output_n, ...witnessData});
}
```

The problem gets triggered when I try adding the input using the `transaction.addInput(inputs[0])`

**Comment by junderw** [comment]
That's not how it works...

The decision between "non" or non-"non" utxo is not based on whether or not the input's referred transaction contains a segwit input (which is what you're detecting with your code), it is decided based on whether your unlocking script uses the segwit data region to store its witness data.

ie. If you are spending an output that was send to any of P2WPKH, P2SH-P2WPKH, P2WSH, P2SH-P2WSH, P2TR then you must use witnessUtxo (Which, by the way, is not just the full transaction, it is the amount and script only), and if it is anything else it should only use non-segwit data regions and therefore requires nonWitnessUtxo.

**Comment by zikyfranky** [comment]
> (Which, by the way, is not just the full transaction, it is the amount and script only)

Perhaps an oversight, but `Transaction.fromHex(rawTransaction).outs[unspent.tx_output_n];` does that.

Also, thanks for the help. I got it working!
