### ISSUE TITLE
Error due to wrong method call inside fromBase58Check method

### ISSUE THREAD

**Issue by wakqasahmed** [bitcoinjs/bitcoinjs-lib#1974]
The method `fromBase58Check` produces an error due to a wrong method call `const version = payload.readUint8(0);`

Here is the error:

```
bitcoinjs-lib.js:5184 Uncaught TypeError: payload.readUint8 is not a function
    at Object.fromBase58Check (bitcoinjs-lib.js:5184:27)
    at <anonymous>:1:17
```

**Comment by junderw** [comment]
Duplicate #1969

Please make sure you use the proper Buffer version.
