### ISSUE TITLE
address has no matching Script  (psbt.addOutput)

### ISSUE THREAD

**Issue by edsonPrimo** [bitcoinjs/bitcoinjs-lib#1977]
I am struggling adding output to psbt, this is my code: 

    const NETWORK = bitcoin.networks.testnet;
    const psbt = new bitcoin.Psbt({ network: NETWORK });
    psbt.addOutput({
      address: "2N61c19hwjR2TjFMvBsBk81avdYynKSjzcm",
      value: Number(this.toSatoshi(0.00004645)),
    });
    
Only works if i use this type of address: tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx
Is this supposed to work only with bech32 addresses?

I am using 6.1.3 version.
What can i do to send BTC to any type of wallet using PSBT?

Thanks!

**Comment by junderw** [comment]
I ran this code:

```js
const NETWORK = bitcoin.networks.testnet;
const psbt = new bitcoin.Psbt({ network: NETWORK });
psbt.addOutput({
  address: "2N61c19hwjR2TjFMvBsBk81avdYynKSjzcm",
  value: 4645,
});
console.log(psbt.txOutputs)
```

And got this output without errors:

```
[
  {
    script: <Buffer a9 14 8c 06 30 5a 3d 11 be ed 26 af 49 8f 16 56 25 fb 71 37 c1 2d 87>,
    value: 4645,
    address: '2N61c19hwjR2TjFMvBsBk81avdYynKSjzcm'
  }
]
```

Please post steps to reproduce.

**Comment by edsonPrimo** [comment]
Not sure if it's related, but I updated the library version to 6.1.4 using the same code, and now it's working.

 Anyway, thank you so much!
