### ISSUE TITLE
Error sending Bitcoin transaction: Error: mi9QdM3LnGR5hMVVT9B3hHLw5QyjVPMV2B has no matching Script

### ISSUE THREAD

**Issue by TechLateef** [bitcoinjs/bitcoinjs-lib#1982]
i tried all possible way out but am still getting this 

code sample
  const psbt = new bitcoin.Psbt(bitcoin.networks.testnet);

      // Add inputs
      for (const utxo of utxos) {
        const rawTransaction = await this.getRawTransactionHex(utxo.txid);
        psbt.addInput({
          hash: utxo.txid,
          index: utxo.vout,
          nonWitnessUtxo: Buffer.from(rawTransaction, "hex"),
        });
      }

      // Calculate the total input amount
      const totalInputAmount = utxos.reduce(
        (total, utxo) => total + utxo.value,
        0
      );

      const totalInputAmountSatoshis = Math.floor(totalInputAmount * 100000000);

      const transactionSize = psbt.toBuffer().length; // Get the size of the transaction in bytes
      const transactionFee = transactionSize * feeRate;
      console.log("Transaction fee:", transactionFee);

      // Calculate the maximum available amount for the outputs without exceeding the total input amount
      const maxOutputAmountSatoshis =
        totalInputAmountSatoshis - Math.floor(transactionFee);

      // Calculate the output amount for the recipient's address, ensuring it doesn't exceed the maximum
      const recipientOutputSatoshis = Math.min(
        Math.floor(amount * 100000000),
        maxOutputAmountSatoshis
      );

      // Calculate the change amount
      const changeOutputSatoshis =
        maxOutputAmountSatoshis - recipientOutputSatoshis;

      console.log("Change Amount", changeOutputSatoshis);
      // Calculate the total output amount
      const totalOutputAmount = Math.floor(
        recipientOutputSatoshis + changeOutputSatoshis + transactionFee
      );
      console.log("totalOutputAmount1", totalOutputAmount);
      // Add the recipient's address as an output
      psbt.addOutput({ address: toAddress, value: recipientOutputSatoshis });

      if (changeOutputSatoshis > 0) {
        try {
          const changeAddress = await this.generateNewAddressWithMnemonic(mnemonic,10,1);
          psbt.addOutput({ address: changeAddress, value: changeOutputSatoshis });
        } catch (error) {
          console.error('Error generating change address:', error);
        }
      }
     console.log("totalInsatosh", recipientOutputSatoshis + changeOutputSatoshis)  
      // Sign inputs
      const keyPair = ECPair.fromWIF(userPrivateKey, network);
      for (let i = 0; i < utxos.length; i++) {
       
        try {
          psbt.signInput(i, keyPair);
        } catch (error) {
          console.error("Error signing input", i, ":", error);
        }
      }

**Comment by junderw** [comment]
Update to latest version.

Thanks.

**Comment by junderw** [comment]
`new bitcoin.Psbt(bitcoin.networks.testnet);` is incorrect.

`new bitcoin.Psbt({ network: bitcoin.networks.testnet });` is correct.

These types of mistakes are easily caught with TypeScript. I highly recommend it.

**Comment by TechLateef** [comment]
i will try converting my code to typescript and see because after changing it to this new bitcoin.Psbt({ network: bitcoin.networks.testnet }); . am still having same issue

**Comment by junderw** [comment]
`const transactionSize = psbt.toBuffer().length;` This is not the transaction size. This is the PSBT size (which is much larger).

You can't know the transaction size without building the full transaction first, but you can estimate the transaction size as long as you know which types of inputs and outputs are used.
