### ISSUE TITLE
How to generate addresses from xpub?

### ISSUE THREAD

**Issue by pAulseperformance** [bitcoinjs/bitcoinjs-lib#1988]
All I am trying to do is build a donation link on my website. So when someone clicks a "Donate" button, a bitcoin address is generated from my Xpub, and they can donate to an address and I don't have to reuse a bitcoin address.

I feel like this should be something that is super simple, and pretty much copy and paste for everyone at this point as a widget...
I understand my Xpub should be protected and I intend to secure it, but figuring out how to derive the child addresses from my xpub is proving to be difficult.

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/b65513a8d1abe66323d0601d9422dc84f0fbbd39/test/integration/bip32.spec.ts#L103-L120

Except: Use `fromBase58` instead of `fromSeed` and use the path from the xpub instead of the path from the xprv, (so in the example you would shorten `"m/49'/1'/0'/0/0"` to `"m/0/0"`... since the xpub would be generated at `"m/49'/1'/0'"`

**Comment by pAulseperformance** [comment]
I keep running into an issue where there is no function `fromBase58` or `fromSeed`

```
const root = bip32.fromBase58(xpub);
                   ^

TypeError: bip32.fromBase58 is not a function
    at Object.<anonymous> 
```

### My Code
```
const bip39 = require('bip39');
const bip32 = require('bip32');
const bitcoin = require('bitcoinjs-lib');

const xpub = 'xpubYOURXPUBHERE';
const path = "m/49'/1'/0'/0/0";

// Derive the child key from the xpub
const root = bip32.fromBase58(xpub);
const child = root.derivePath(path);

// Generate the P2SH-P2WPKH address
const { address } = bitcoin.payments.p2sh({
  redeem: bitcoin.payments.p2wpkh({
    pubkey: child.publicKey,
    network: bitcoin.networks.testnet,
  }),
  network: bitcoin.networks.testnet,
});

console.log('Generated Address:', address);

```

### package.json
```{

  "dependencies": {
    "bip32": "^4.0.0",
    "bip39": "^3.1.0",
    "bitcoinjs-lib": "^6.1.5"
  }
}
```

**Comment by junderw** [comment]
Read the tests carefully.

Look at the imports.

You need to wrap an ecc implementation with the Bip32Factory function.
