### ISSUE TITLE
Unlocking Transaction for Custom Redeem Script (P2SH)

### ISSUE THREAD

**Issue by Domson97** [bitcoinjs/bitcoinjs-lib#1999]
Ich have the following function für creating redeem script:

```ts
export function createCustomP2SHRedeemScript(
  publicKeyMain: Buffer,
  participantAAddress: string,
  participantBAddress: string,
  timelockTimestamp: number
): Buffer {
  const OPS = bitcoin.script.OPS;

  // Convert the provided Bitcoin addresses to hash160 format
  const hash160A = bitcoin.address.fromBase58Check(participantAAddress).hash;
  const hash160B = bitcoin.address.fromBase58Check(participantBAddress).hash;

  const redeemScript = bitcoin.script.compile([
    OPS.OP_IF,
    publicKeyMain, OPS.OP_CHECKSIGVERIFY,
    bitcoin.script.number.encode(timelockTimestamp), OPS.OP_CHECKLOCKTIMEVERIFY, OPS.OP_DROP,
    OPS.OP_DUP, OPS.OP_HASH160, hash160A, OPS.OP_EQUALVERIFY, 
    OPS.OP_ELSE,
    publicKeyMain, OPS.OP_CHECKSIGVERIFY,
    OPS.OP_DUP, OPS.OP_HASH160, hash160B, OPS.OP_EQUALVERIFY, 
    OPS.OP_ENDIF
  ]);
```

  
  this is my function for creating the unlockingTransaction:
  
```ts
export async function createUnlockingTransaction(
  utxoP2SH: UTXO,
  redeemScript: Buffer,
  destinationAddress: string, 
  amountSatoshis: number,
  privateKeyOfMain: string,
  network: bitcoin.Network,
  timelockTimestamp: number,
  useFirstScenario: boolean 
): Promise<string> {
  
  if (!utxoP2SH.txHex) {
    utxoP2SH.txHex = await fetchTxHex(utxoP2SH.txid);
  }

  const lockingTxHex = utxoP2SH.txHex;
  console.log('Locking Tx Hex:', lockingTxHex);
  const tx = bitcoin.Transaction.fromHex(lockingTxHex);

  const keyPair = ECPair.fromWIF(privateKeyOfMain, network);
  const psbt = new bitcoin.Psbt({ network: network });
  psbt.setLocktime(timelockTimestamp);
  psbt.addInput({
    hash: tx.getId(),
    index: utxoP2SH.vout,
    sequence: useFirstScenario ? 0xffffffff : 0,
    nonWitnessUtxo: Buffer.from(lockingTxHex, 'hex'),
    redeemScript: redeemScript
  });

  psbt.addOutput({
    address: destinationAddress, // In hexadezimalem Format
    value: amountSatoshis,
  });

  // Sign the input
  psbt.signInput(utxoP2SH.vout, keyPair);

  psbt.finalizeAllInputs();

  return psbt.extractTransaction().toHex();
}
```

i constantly getting this error:

Can not finalize input #0

      347 |   psbt.signInput(utxoP2SH.vout, keyPair);
      348 |
    > 349 |   psbt.finalizeAllInputs();
          |        ^
      350 |
      351 |   return psbt.extractTransaction().toHex();
      352 | }
      
      what i am doing wrong?

**Comment by junderw** [comment]
You need to provide your own finalizer:

```ts
function getFinalScriptsForMyCustomScript(
  inputIndex: number,
  input: PsbtInput,
  script: Buffer,
  isSegwit: boolean,
  isP2SH: boolean,
  isP2WSH: boolean,
): {
  finalScriptSig: Buffer | undefined;
  finalScriptWitness: Buffer | undefined;
} {
  // ... put your finalizer logic in here
}

// ...

psbt.finalizeInput(0, getFinalScriptsForMyCustomScript); // 1st input is custom script
psbt.finalizeInput(1); // 2nd input is normal script, not custom
psbt.finalizeInput(2, getFinalScriptsForMyCustomScript); // 3rd input is also custom
```

etc.

**Comment by junderw** [comment]
Also, your script doesn't check any signatures from `participantAAddress` or `participantBAddress`..... so the `publicKeyMain` can redeem this script at any time by itself.

**Comment by Domson97** [comment]
Thank you very much for the fast answer! Do i really have to finalize all 3 inputs (0,1,2) ?
publicKeyMain should be the only one unlocking the script, because the only ones who can receive the funds are participantAAddress or participantBAddress anyway. 
( OPS.OP_DUP, OPS.OP_HASH160, hash160B, OPS.OP_EQUALVERIFY ) i think this line is checking if the output address in the unlocking script matches the hash160B.

**Comment by junderw** [comment]
> Do i really have to finalize all 3 inputs (0,1,2) ?

You need to finalize all inputs. If there's 3, you need to finalize all three.

> publicKeyMain should be the only one unlocking the script, because the only ones who can receive the funds are participantAAddress or participantBAddress anyway.
( OPS.OP_DUP, OPS.OP_HASH160, hash160B, OPS.OP_EQUALVERIFY ) i think this line is checking if the output address in the unlocking script matches the hash160B.

That's not what this means. It means "if the signer of publicKeyMain knows the publicKey for participantBAddress, then publicKeyMain can spend the input immediately and send to any output they want"

**Comment by Domson97** [comment]
Is there a way to check the output address in the unlocking transaction with an provided address in the redeemscript? Or is there antoher way to restrict the p2sh only to payout a provided address in the redeemscript? Thank you in advance!

**Comment by junderw** [comment]
Require the signature of that pubkey as well, and that pubkey's owner will only sign if it sees its own address in the outputs.
