### ISSUE TITLE
When I use the DOGE chain to create and sign a transaction I got this error:

### ISSUE THREAD

**Issue by 04-26** [bitcoinjs/bitcoinjs-lib#2002]
Warning: You are paying around 0.09999822 in fees, which is 44247 satoshi per byte for a transaction with a VSize of 226 bytes (segwit counted as 0.25 byte per byte). Use setMaximumFeeRate method to raise your threshold, or pass true to the first arg of extractTransaction.
How to solve this?

**Comment by junderw** [comment]
> Use setMaximumFeeRate method to raise your threshold, or pass true to the first arg of extractTransaction.

The error message tells you what to do.
