### ISSUE TITLE
How to get the private key for the payments.p2tr generated address?

### ISSUE THREAD

**Issue by ekmanss** [bitcoinjs/bitcoinjs-lib#2003]
I transferred BTC into the address generated by payments.p2tr, but I can't find where the private key is for this address, please help!

**Comment by junderw** [comment]
Take all the private keys you know of and run them through the same code to get the p2tr address and find which one matches.

**Comment by ekmanss** [comment]
I'm not familiar with the BTC network, I'm learning, I know the address is generated here, different atomicsPayload will generate a different address, I don't know how to print out the address of the private key
[https://github.com/atomicals/atomicals-js/blob/c1d9047ec62446db383371413eab539836150527/lib/commands/command-helpers.ts#L158](url)

**Comment by junderw** [comment]
getKeypairInfo seems to be taking in an ECPair object and generating the needed information from that.

So just take the childNode.privateKey as a hex string or something.

Ideally, there should probably be a bip32 master key or BIP39 seed phrase to manage keys, but I haven't looked too deep into your code.

**Comment by ekmanss** [comment]
The getKeypairInfo uses the funding.WIF from the wallet.json file in the project root directory (generated by the `yarn cli wallet-init` command) as the WIP. It then uses payments.p2tr to generate a new address. What confuses me is how to obtain the WIP for this new address.

[the code](https://github.com/atomicals/atomicals-js/blob/c1d9047ec62446db383371413eab539836150527/lib/utils/atomical-operation-builder.ts#L408)

**Comment by junderw** [comment]
There is no WIF for taproot addresses.

The WIF private key format only supports compressed P2PKH and uncompressed P2PKH.

Historically, some wallets have added support to WIF so it can be used with P2WPKH addresses, but this is not adhering to the WIF standard.

If all you have is a WIF private key, then you must figure out a way to encode the information that "this is a taproot key-spend key that uses the xOnlyPublicKey tweak method" somehow. Whether that is some JSON format you make, or some other way to encode it... that is up to you.

There is no way to encode that information into the WIF format.

**Comment by junderw** [comment]
If you use BIP32 (HD keys) then you could use BIP86 to encode the information in the derivation path, but you'd still need to know that your wallet uses P2TR, similar to how a wallet using BIP84 would need to know it is P2WPKH.

https://github.com/bitcoin/bips/blob/master/bip-0086.mediawiki
