### ISSUE TITLE
Example to create a derivatives address from the wallet's public key

### ISSUE THREAD

**Issue by dawadam** [bitcoinjs/bitcoinjs-lib#2008]
Hi, thanks for the work,
I'm trying to generate an alternative, derived, public key address from the wallet's first public key.
And of course, without the private key, for security reasons.
I found a lot of code for this, but not a lot of conclusions. I'm confused.
Can you add this case as an example documentation please?

**Comment by junderw** [comment]
It is highly discouraged to "roll your own" key derivation schemes.

That includes bitcoinjs-lib "rolling its own scheme" and putting it in our examples.

Why do you feel that bip32 is insufficient for your use case? What are you trying to do?

**Comment by dawadam** [comment]
I just want to create a derived key from the master key.
bip32 can work, I just need the example to achieve it.

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/1f92ada3fda587c1c0a6aa93649afa04e8382b93/test/integration/bip32.spec.ts

Here you go!

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/1f92ada3fda587c1c0a6aa93649afa04e8382b93/test/integration/bip32.spec.ts#L26-L49

These two tests show exporting and importing from xpub and xprv.

fromBase58 can import either one, public or private. However, when imported from public, you can not derive hardened derive paths (anything with a `'` on one of the numbers, or any calls to deriveHardened)

**Comment by dawadam** [comment]
Thanks, I'll investigate.
It's possible that I'm so new to it that I don't understand.

Is it risky to use the derived key from public key (not to use deriveHardened) ?

**Comment by junderw** [comment]
> Is it risky to use the derived key from public key (not to use deriveHardened)?

Read up on the topic. https://btcinformation.org/en/developer-guide#hierarchical-deterministic-key-creation

**Comment by miguilimzero** [comment]
@junderw I have been searching through this topic and came up with a doubt. I cannot generate derivate hardened from an xpub key. 

But when I put the xpub in the https://www.blockchain.com/explorer/, the explorer found all my used addresses from an  `m84'/0'/0'/0/2` path.

How is this even possible?

**Comment by junderw** [comment]
A bug maybe? I am not familiar with their website anymore.

**Comment by junderw** [comment]
Where did you get the xpub from?

Which wallet? What menu buttons did you press to display the xpub?

**Comment by miguilimzero** [comment]
I get the xpub from my Ledger wallet. I also tested with https://btc1.trezor.io/ and it worked.

I found this guide on Ledger website: https://support.ledger.com/hc/en-us/articles/6275459128989-How-to-analyze-a-Bitcoin-BTC-account-xPub?docs=true

**Comment by junderw** [comment]
The keys you are seeing are `m/84'/0'/0'/0/N` where N is 0 to however many keys you used.

The XPUB is of depth 3 or 4, and from the xpub, the code is deriving `0/N` or just `N` from the xpub.

**Comment by miguilimzero** [comment]
Yes, I just found the xpub key is `m/84'/0'/0'`. Now everything makes sense. Thanks for the help!
