### ISSUE TITLE
Error: Can not sign for this input with the key xxxxxxxxxxxxxxxxx

### ISSUE THREAD

**Issue by SwatX18** [bitcoinjs/bitcoinjs-lib#2011]
Hello everyone!

I've come to ask for your help because I'm stuck.
I'm trying to sign a PSDT (PSBT but for dogecoin) but I have the following error: 

> Error: Can not sign for this input with the key xxxxxxxxxxxxxxxxx

The key here, is my private key.

**My code:**
```
const dotenv = require('dotenv');
dotenv.config();

const coininfo = require("coininfo");
var curr = coininfo.dogecoin.main;
var frmt = curr.toBitcoinJS();

const dogecoinNetwork = {
    messagePrefix: '\x19' + frmt.name + ' Signed Message:\n',
    bip32: {
        public: frmt.bip32.public,
        private: frmt.bip32.private
    },
    pubKeyHash: frmt.pubKeyHash,
    scriptHash: frmt.scriptHash,
    wif: frmt.wif
}

const psdtHex = MY_DOGE_HEX_PSDT;

const bip39 = require('bip39');
const bitcoin = require('bitcoinjs-lib');

const mnemonic = process.env.MNEMONIC;
const derivationPath = process.env.DERIVATION_PATH;

// Generate a seed from the mnemonic phrase
const seed = bip39.mnemonicToSeedSync(mnemonic);

// Create a master key instance from seed
const masterNode = bitcoin.bip32.fromSeed(seed, dogecoinNetwork);

// Function to derive a private key from the path
function derivePrivateKey(path) {
  const childNode = masterNode.derivePath(path);
  return childNode.privateKey;
}

// Specify derived private key for signing
const privateKey = derivePrivateKey(derivationPath);

// Create a key pair from the private key in the specified network
const keyPair = bitcoin.ECPair.fromPrivateKey(privateKey, { network: dogecoinNetwork });
console.log('Private Key:', keyPair.toWIF());

// Debug to see if the address is good
const publicKeyHash = bitcoin.crypto.hash160(keyPair.publicKey);
const p2pkhBuffer = Buffer.from(publicKeyHash, 'hex');
const payment = bitcoin.payments.p2pkh({ hash: p2pkhBuffer, network: dogecoinNetwork });
const address = payment.address;
console.log('Address Dogecoin:', address);

// Create a PSBT transaction from PSBT hex
const psbt = bitcoin.Psbt.fromHex(psdtHex, { network: dogecoinNetwork });
psbt.signInput(2, keyPair, [bitcoin.Transaction.SIGHASH_ALL]);

// Finalizing the PSBT
psbt.finalizeInput(2);

// Get tx & raw tx
const tx = psbt.extractTransaction();
const rawTx = tx.toHex();
console.log('Transaction hex:', rawTx);
```

**My PSBT give me 3 inputs :**
```
[
  { sighashType: 2 },
  { sighashType: 2 },
  {
    nonWitnessUtxo: <Buffer 02 00 00 00 02 82 00 ee 9d 69 de ae 44 44 46 69 30 d4 80 7c e1 fd 80 d2 11 30 2c 08 38 cc 0f f7 af f2 3a c6 8f 00 00 00 00 ca 03 6f 72 64 51 17 74 65 ... 452 more bytes>,
    finalScriptSig: <Buffer 48 30 45 02 21 00 e0 75 66 67 b0 2b e5 09 75 6d 63 bd cc fa 30 5f 3b ba 3c ef 0f 53 51 5d 79 89 97 c4 1b 26 91 c4 02 20 2e 25 f8 de ad 76 1d b0 49 17 ... 57 more bytes>
  }
]
```

If I try to sign the first 2 inputs whit [bitcoin.Transaction.SIGHASH_NONE] (required for doge), I get an error :

> Error: Need a Utxo input item for signing

That's why I'm only signing the third one.

**My aim in all this, is to sign and send a transaction via a PSBT Hex input. Any help is welcome!**

**Comment by junderw** [comment]
> The key here, is my private key.

It's your public key. Not your private key. This error happens when you use the wrong private key to sign for an input. PSBT will search every script it can find and if it can't find your public key (or the public key hash) anywhere, then it throws that error. You need to make sure it's the right mnemonic and the right path, otherwise you'll have this error.

> Error: Need a Utxo input item for signing

Yeah... the error is very clear. See that `nonWitnessUtxo` data on input 2? You need something like that for 0 and 1 as well.

**Comment by SwatX18** [comment]
Thank you for your reply!
Yes, I was talking about my public key, I made a mistake.

But the fact is, I want to sign this HEX PSBT that comes from a marketplace, to execute the order in a script and not manually, so my public key will never be in it, right?

And for the 2nd error, I agree with the nonWitnessUtxo thing but what I'm showing you are the entries in the PSBT HEX, so I don't have more in the 0 and 1 entries.

**Comment by SwatX18** [comment]
> > The key here, is my private key.
> 
> It's your public key. Not your private key. This error happens when you use the wrong private key to sign for an input. PSBT will search every script it can find and if it can't find your public key (or the public key hash) anywhere, then it throws that error. You need to make sure it's the right mnemonic and the right path, otherwise you'll have this error.
> 
> > Error: Need a Utxo input item for signing
> 
> Yeah... the error is very clear. See that `nonWitnessUtxo` data on input 2? You need something like that for 0 and 1 as well.

Thank you for your reply!
Yes, I was talking about my public key, I made a mistake.

But the fact is, I want to sign this HEX PSBT that comes from a marketplace, to execute the order in a script and not manually, so my public key will never be in it, right?

And for the 2nd error, I agree with the nonWitnessUtxo thing but what I'm showing you are the entries in the PSBT HEX, so I don't have more in the 0 and 1 entries.

**Comment by Skr1pt** [comment]
> @junderw
> 
> > > The key here, is my private key.
> > 
> > 
> > It's your public key. Not your private key. This error happens when you use the wrong private key to sign for an input. PSBT will search every script it can find and if it can't find your public key (or the public key hash) anywhere, then it throws that error. You need to make sure it's the right mnemonic and the right path, otherwise you'll have this error.
> > > Error: Need a Utxo input item for signing
> > 
> > 
> > Yeah... the error is very clear. See that `nonWitnessUtxo` data on input 2? You need something like that for 0 and 1 as well.
> 
> Thank you for your reply! Yes, I was talking about my public key, I made a mistake.
> 
> But the fact is, I want to sign this HEX PSBT that comes from a marketplace, to execute the order in a script and not manually, so my public key will never be in it, right?
> 
> And for the 2nd error, I agree with the nonWitnessUtxo thing but what I'm showing you are the entries in the PSBT HEX, so I don't have more in the 0 and 1 entries.

can u text me telegram? @skr1pt_0

**Comment by junderw** [comment]
> I want to sign this HEX PSBT that comes from a marketplace, to execute the order in a script and not manually, so my public key will never be in it, right?

Without explaining the protocol in detail, I can't help you.

The sign methods are meant for normal use cases. Anything else will require different consideration depending on your protocol.
