### ISSUE TITLE
Sign Input with different keys

### ISSUE THREAD

**Issue by edsonPrimo** [bitcoinjs/bitcoinjs-lib#2012]
Hello
I want to finalize a PSBT to determine the transaction size, but I don't have access to the private key associated with the input. This is because I'm constructing a transaction that will be signed within a browser extension. Is it possible to use the function psbt.signAllInputs with a key pair that doesn't 'own' the input?

**Comment by junderw** [comment]
No, unfortunately not.

However, it is possible to know the size of an input and output based on the information you have about it.

ie. This is a very rough example: https://gist.github.com/junderw/b43af3253ea5865ed52cb51c200ac19c
