### ISSUE TITLE
Use case request: Signature verification 

### ISSUE THREAD

**Issue by AusDavo** [bitcoinjs/bitcoinjs-lib#2016]
Could you verify a signature using a public key and specified message content? Your help with this would be immensely appreciated.

**Comment by junderw** [comment]
What is the content?

There are a few "protocols" for signing and verifying signatures of arbitrary messages. But if the usage is for a specific protocol, it might be better to tailor a specific protocol for that protocol you are trying to use it with.

1. https://github.com/bitcoinjs/bitcoinjs-message (This is the method used in Bitcoin Core and Trezor wallets etc)
2. BIP322 is a protocol for signing and verifying messages... but it's not widely used. I have made a toy implementation https://github.com/bitcoinjs/bitcoinjs-lib/issues/1918#issuecomment-1555229330 here. Please verify the code on your own if you wish to use it. I take no responsibility for it.

**Comment by AusDavo** [comment]
Thanks for the advice. Purpose is to provide an interface for testing multi-sig wallet participants. I made progress eventually. My problem was related to scope following bundling.

**Comment by tanzile789** [comment]
So does every transaction require a private key to complete？
