### ISSUE TITLE
Network used testnet，Wallet used p2wpkh Until the last step, they couldn't generate it，I don't know what the problem is Please help me, I'm a novice

### ISSUE THREAD

**Issue by tanzile789** [bitcoinjs/bitcoinjs-lib#2017]
```js
  const p2wpkhSender = bitcoin.payments.p2wpkh({
    pubkey: keyPair.publicKey,
    network
  });
  
  const p2wpkhReceiver = bitcoin.payments.p2wpkh({
    address: receiverAddress,
    network
  });

  const psbt = new bitcoin.Psbt({ network: network })
    .addInput({
      hash: lastTransaction.txid,
      index: lastTransaction.vout,
      // nonWitnessUtxo: reconstructedTx.toBuffer(),
      witnessUtxo: {
        script: p2wpkhSender.output,
        value: lastTransaction.satoshi
      }
    })
    .addOutput({
      address: p2wpkhReceiver.address,
      value: 10000
    })
    .signInput(0, keyPair)
    .finalizeInput(0)
    .extractTransaction();

  console.log(" ============================= this is newww ");
  console.log(psbt.toHex());
  ```

**Comment by junderw** [comment]
The code looks fine. What's the issue?

**Comment by tanzile789** [comment]
I thought it worked, but it didn't generate pbt.tohex ()，Unable to console

**Comment by junderw** [comment]
I can't see anything wrong with your code.

I would need more information to diagnose this issue.

**Comment by tanzile789** [comment]
I think I got the question.，witnessUtxo.script is error
It suggests    Warning: You are paying around 0.01722930 in fees, which is 15663 satoshi per byte for a transaction with a VSize of 110 bytes (segwit counted as 0.25 byte per byte). Use setMaximumFeeRate method to raise your threshold, or pass true to the first arg of extractTransaction

**Comment by junderw** [comment]
Please search for existing issues first:

Locking as duplicate: https://github.com/bitcoinjs/bitcoinjs-lib/issues/1971
