### ISSUE TITLE
fromWIF error

### ISSUE THREAD

**Issue by tanzile789** [bitcoinjs/bitcoinjs-lib#2018]
const alice = await ECPair.fromWIF(privateKeyWIF, network);
console.log(alice)

![微信截图_20231229174015](https://github.com/bitcoinjs/bitcoinjs-lib/assets/52699298/58382260-7d02-4fc9-8542-9b495320753c)

I made a mistake when I signed with the private key, I was sure the key was in wif format

**Comment by junderw** [comment]
Please use the search bar.

https://github.com/bitcoinjs/bitcoinjs-lib/issues/1865
