### ISSUE TITLE
Inconsistent output adresses vs sparrow wallet

### ISSUE THREAD

**Issue by j-5-s** [bitcoinjs/bitcoinjs-lib#2019]
I'm attempting to scan a multisig wallet and seeing mostly the same address but not all the same.  This is specifically for a 2-2 multisig.  Code is:
```ts
const addresses = Array.from({ length: limit }).map((_, i) => {
  const pubkeys = xpubs
    .map((xpub) => {
      const node = bitcoinjs.bip32
        .fromBase58(xpub)
        .derive(isChange ? 1 : 0)
        .derive(start + i).publicKey;
      return node;
    })
    .sort();

  const redeemScript = bitcoinjs.payments.p2ms({
    m: 2,
    pubkeys: pubkeys,
  });

  const { address } = bitcoinjs.payments.p2wsh({
    redeem: redeemScript,
  });
  return address;
});
```
The first two adresses returned match what is in sparrow wallet, however the 3rd address does not match sparrow and the 4th and so on then does. Any idea what could be going on here?

Here is a[ codesandbox](https://codesandbox.io/p/sandbox/recursing-wind-9knlzm?file=%2Fsrc%2Fstyles.css%3A9%2C2) showing the first 5 receive and 5 change addresses. In this example you can see that the 2nd and 3rd change addresses dont match sparrow:

![Screen Shot 2023-12-30 at 9 33 08 PM](https://github.com/bitcoinjs/bitcoinjs-lib/assets/666455/63929490-f74e-4e3e-8748-f8f901406072)

<img width="1062" alt="Screen Shot 2023-12-30 at 9 34 30 PM" src="https://github.com/bitcoinjs/bitcoinjs-lib/assets/666455/dab44bf1-f4db-4c55-a902-575e200926fb">

I'm building the library with this - https://github.com/TJKoury/bitcoinjs-single-file

**Comment by junderw** [comment]
sort() doesn't work on Buffers properly. sort treats a and b as strings and compares the strings... (yaaay JS)

pass a compare fn to the sort function ie. `sort((a, b) => a.compare(b))` as Buffer has a compare method.
