### ISSUE TITLE
how to construct input addresses

### ISSUE THREAD

**Issue by tanzile789** [bitcoinjs/bitcoinjs-lib#2020]
const bitcoin = require('bitcoinjs-lib');
const network = bitcoin.networks.testnet;
const ecpair = require('ecpair');
const ecc = require('tiny-secp256k1');
const ECPair = ecpair.ECPairFactory(ecc);

1、
const keyPair = ECPair.makeRandom({network:network})
const p2wpkhSender = bitcoin.payments.p2wpkh({pubkey:keyPair.publicKey})

2、
const keyPair = await ECPair.fromWIF(privateKeyWIF, network);
const p2wpkhSender = bitcoin.payments.p2wpkh({pubkey:keyPair.publicKey,network})

I only understand these two methods now。
The first type of random generation; But the address entered when initiating the transaction is not the wallet address I logged in to。
The second type of private key generation;If each user can only use their private key for transactions, is it secure。
If I am developing a product and want to initiate a transaction using the currently logged in wallet address without exposing the private key, what actions should I take

**Comment by tanzile789** [comment]
Now I am currently a front-end developer，I cannot obtain the private keys of all users。Is there a way to create transactions without the need for a private key？

**Comment by tanzile789** [comment]
But this code，const keyPair = await ECPair.fromWIF(privateKeyWIF, network)。Now I am currently a front-end developer，Do we need each user to pass the private key to the front-end, and then the front-end uses the code to initiate transactions？

**Comment by junderw** [comment]
These questions are out of scope for this issues board.

I would recommend asking them on bitcoin stack exchange, and you will get better answers for how to make a secure wallet.

https://bitcoin.stackexchange.com/

**Comment by tanzile789** [comment]
So does every transaction require a private key to complete？

**Comment by tanzile789** [comment]
So does every transaction require a private key to complete？
Because， I am a front-end developer，I'm constructing a transaction that will be signed within a browser extension.
