### ISSUE TITLE
raw transaction to json

### ISSUE THREAD

**Issue by AyoAyomide** [bitcoinjs/bitcoinjs-lib#2022]
It would be helpful if there is an example that shows how raw transaction 
eg "01000000000101ac7db8b6b2369b8c33f4080f01e24ddf222bee2a044a739d29936a22feccbbaa0100000000c4a300f002ef7e0000000000002251201da8cede1ae34abec31cee05a9f4f69542a9c184c19564cb366ae037462eb514c7950d0000000000225120b3ddd9208c8725f8b4db6f92f36f910101ff9b6101cb60489d0c648644a270da014021f3f3ebd1a252842abed72afba7341a2edddb3af225fee6f2287f3d6eff6d35bd77ac6113d926bf153792b17264500be268877b96dcaa36d64a9b5e89036cc300000000
"

can be converted to JSON-readable output working on this presently but no clear progress yet

**Comment by junderw** [comment]
Everything in the Transaction class is Buffers and numbers. The only hard part is dealing with JS's poor Buffer JSON serialization.

You could just pass in a resolver to JSON.stringify that detects Buffers and calls `toString('hex')`

```js
const txhex = '01000000000101ac7db8b6b2369b8c33f4080f01e24ddf222bee2a044a739d29936a22feccbbaa0100000000c4a300f002ef7e0000000000002251201da8cede1ae34abec31cee05a9f4f69542a9c184c19564cb366ae037462eb514c7950d0000000000225120b3ddd9208c8725f8b4db6f92f36f910101ff9b6101cb60489d0c648644a270da014021f3f3ebd1a252842abed72afba7341a2edddb3af225fee6f2287f3d6eff6d35bd77ac6113d926bf153792b17264500be268877b96dcaa36d64a9b5e89036cc300000000';

const tx = bitcoinjs.Transaction.fromHex(txhex);
console.log(JSON.stringify(
  tx,
  (key, value) => {
    if (value.type === 'Buffer') {
      return Buffer.from(value.data).toString('hex')
    } else if (key === 'ins' && Array.isArray(value)) {
      // input hashes (that point to the previous tx) are reversed before being shown as a txid.
      value.forEach((input) => input.hash.reverse());
      return value
    } else {
      return value
    }
  },
  2, // Number of spaces for JSON pretty print
));
```

**Comment by AyoAyomide** [comment]
Hi @junderw thanks for the response it works however I need a little help 
any idea how to get the address from the value of the script ?
eg
`"outs": [
    {
      "value": 32495,
      "script": "51201da8cede1ae34abec31cee05a9f4f69542a9c184c19564cb366ae037462eb514",
      ""address: "the btc address"
    },
    {
      "value": 890311,
      "script": "5120b3ddd9208c8725f8b4db6f92f36f910101ff9b6101cb60489d0c648644a270da",
      "address: "the btc address"
    }
  ]`
