### ISSUE TITLE
Transfer BRC-20 tokens with bitcoinjs-lib

### ISSUE THREAD

**Issue by gixen222** [bitcoinjs/bitcoinjs-lib#2023]
I'm looking for a solution to transfer BRC-20 tokens programatically, but I'm not sure this lib work for me for that usecase. Is there any specific SDK for that or I can use this lib?

**Comment by junderw** [comment]
This is a low level library for managing Bitcoin transactions.

You can make BRC-20 tokens with it as long as you are knowledgeable in both this library and the BRC-20 protocol.

Think of it like this:

If we pretend that bitcoinjs-lib = TCP connection library... your question is like `"I am looking for a solution to create an HTTP REST server, I'm not sure if this library with work for that use case."`

So yes. You can make BRC-20 transactions with this library, but it would be better to create your own library that uses this library as a dependency to allow for easier management of BRC-20.

BRC-20 is out of scope for this library, but this library will likely be used in some BRC-20 library.

Think of it like "HTTP REST server code is out of scope for a TCP connection library"
