### ISSUE TITLE
Unable to broadcast transaction, even after validating the inputs

### ISSUE THREAD

**Issue by adityanithariya** [bitcoinjs/bitcoinjs-lib#2026]
[Issue](https://github.com/bitcoinjs/bitcoinjs-lib/issues/2021) posted previously for error due to not signing all the inputs, after executing `signAllInputs()`, and `validateAllInputs()` successfully, still unable to broadcast transaction, using [blockstream](https://blockstream.info/testnet/api/tx) API to broadcast transaction.
Error message from API:
sendrawtransaction RPC error:
```json
{"code":-25,"message":"bad-txns-inputs-missingorspent"}
```
Please let me know if further details are required.
Thanks in Advance!

**Comment by adityanithariya** [comment]
@junderw Please look into it!!

**Comment by junderw** [comment]
`bad-txns-inputs-missingorspent` explains the error.

You are trying to spend inputs that are already spent.

Maybe you broadcasted the same transaction 2 times and the error is from the 2nd time, after it is already spent?

I don't know, but the error is clear. You are trying to send coins that are already sent.

**Comment by adityanithariya** [comment]
But when checking the history of the account used to do the transfer, is not having any such transaction

**Comment by adityanithariya** [comment]
Please provide a solid source by which I can learn about creating btc transaction. from fetching UTXOs to broadcasting transactions
