### ISSUE TITLE
BRC-20 Support

### ISSUE THREAD

**Issue by tothstevee** [bitcoinjs/bitcoinjs-lib#2031]
I'm looking for a solution to transfer BRC-20 tokens programatically, but I'm not sure this lib work for me for that usecase. If it's works can i have a sample code for it?

**Comment by sachinsinghjagawat** [comment]
Hey @tothstevee , I am also struggling to do a BRC20 token transfer. I see that you closed this issue; maybe you found the solution. If you are comfortable, then can you please share the code with me too? I tried to do a lot of research for it, but couldn't find a solution to it. Any help will be greatly appreciated. ❤️
