### ISSUE TITLE
Send a Transaction with SegWit P2PKH Keypair

### ISSUE THREAD

**Issue by 0xCrispy** [bitcoinjs/bitcoinjs-lib#2039]
Hi,

I'm new to bitcoinjs-lib and am having a hard time of creating a simple node.js script to send BTC on testnet. A lot of the resources online use outdated method names (e.g., bitcoin.Transaction() vs bitcoin.TransactionBuilder(), need to import ECPair, etc..)

If someone can assist with a working script it would be much appreciated. Currently, I have something along the lines of:

```
const bitcoin = require('bitcoinjs-lib');
const ECPairFactory = require('ecpair').default;
const ecc = require('tiny-secp256k1');

const ECPair = ECPairFactory(ecc);
const TESTNET = bitcoin.networks.testnet

const privateKey = '';
const toAddress = '';
const keyPair = ECPair.fromWIF(privateKey, TESTNET);

const account = bitcoin.payments.p2pkh({ pubkey: keyPair.publicKey, network: TESTNET })
const psbt = new bitcoin.Psbt({ network: keyPair.network });

psbt.addOutput({
  address: toAddress,
  value: 1500,

psbt.signAllInputs(keyPair.signSchnorr)
  psbt.finalizeAllInputs();

const transaction = psbt.extractTransaction();
console.log(transaction)
```

**Comment by Aamir0890** [comment]
@junderw i am getting error   [Error: Can not finalize input #0]
import * as bitcoin from 'bitcoinjs-lib';


 const keyPaird = bitcoin.ECPair.fromWIF(privateKey,network);
    const payment = bitcoin.payments.p2sh({  redeem: bitcoin.payments.p2wpkh({ pubkey: keyPaird.publicKey, network: network }) });
      console.log(payment)
    const { address } = payment;
    const redeemScript = payment.redeem?.output;
    
    console.log('bro')
    if (!redeemScript || !address) return null;
      console.log('redde,')
      const psbt = new bitcoin.Psbt({ network });
      
//       // Fetch the source address UTXO data
      const utxoData = await axios.get(`https://api.blockcypher.com/v1/btc/test3/addrs/${sourceAddress}/full`);
     console.log(utxoData.data)
     let balance=utxoData.data.balance
     console.log(balance)
      const utxos = utxoData.data.txs.flatMap((tx) => {
        let voutIndex = 0;
        return tx.outputs.map((output) => {
            const utxo = {
                txid: tx.hash,
                vout: voutIndex++,
                scriptPubKey: output.script,
                amount: output.value,
            };

            if (!output.spent_by) {
                return utxo;
            }
        });
    }).filter(Boolean);
    console.log(utxos,'utox')
  
       console.log(utxos)
      const fee = 10000; // Set an appropriate fee (in satoshis)
     
for (const element of utxos) {
  const response = await axios.get(`https://api.blockcypher.com/v1/btc/test3/txs/${element.txid}?includeHex=true`);
  const previousTx = response.data.hex;
   console.log(previousTx,'dasds')
  psbt.addInput({
      hash: element.txid,
      index: element.vout,
      nonWitnessUtxo: Buffer.from(previousTx, 'hex'),
     redeemScript:redeemScript
  });
}  


const feeRate = 1; // Adjust this value based on the current network conditions

const left=balance-feeRate-amountToSend
    
//       // Add output
      psbt.addOutput({
        address: destinationAddress,
        value: amountToSend+feeRate
      });
      psbt.addOutput({
        address:sourceAddress,
        value:left
      })
      // psbt.signAllInputs(keyPaird)
     try {
      console.log(psbt.data.inputs)
      for (let i = 0; i < utxos.length; i++) {
        psbt.signInput(i, keyPaird);
      }
      // Finalize all inputs
      psbt.finalizeAllInputs();
     } catch (error) {
      console.log(error)
     }
     
      // Sign each input
     try {
      
      psbt.signAllInputs(keyPaird)
     
      console.log(psbt.data.inputs)

      // Finalize all inputs
      psbt.finalizeAllInputs();
       
      // Extract transaction
      const tx = psbt.extractTransaction().toHex();
      
      console.log('Transaction:', tx);
      
      //getTransactionId(tx);
      
     } catch (error) {
      console.log(error)
     }

**Comment by Aamir0890** [comment]
@junderw i am getting error [Error: Can not finalize input #0] 
  import * as bitcoin from 'bitcoinjs-lib';
 const keyPaird = bitcoin.ECPair.fromWIF(privateKey,network);
 const payment = bitcoin.payments.p2sh({  redeem: bitcoin.payments.p2wpkh({ pubkey: keyPaird.publicKey, network: network }) });
      console.log(payment)
    const { address } = payment;
    const redeemScript = payment.redeem?.output;
    
    console.log('bro')
    if (!redeemScript || !address) return null;
      console.log('redde,')
      const psbt = new bitcoin.Psbt({ network });
      
//       // Fetch the source address UTXO data
      const utxoData = await axios.get(`https://api.blockcypher.com/v1/btc/test3/addrs/${sourceAddress}/full`);
     console.log(utxoData.data)
     let balance=utxoData.data.balance
     console.log(balance)
      const utxos = utxoData.data.txs.flatMap((tx) => {
        let voutIndex = 0;
        return tx.outputs.map((output) => {
            const utxo = {
                txid: tx.hash,
                vout: voutIndex++,
                scriptPubKey: output.script,
                amount: output.value,
            };

            if (!output.spent_by) {
                return utxo;
            }
        });
    }).filter(Boolean);
    console.log(utxos,'utox')
  
       console.log(utxos)
      const fee = 10000; // Set an appropriate fee (in satoshis)
     
for (const element of utxos) {
  const response = await axios.get(`https://api.blockcypher.com/v1/btc/test3/txs/${element.txid}?includeHex=true`);
  const previousTx = response.data.hex;
   console.log(previousTx,'dasds')
  psbt.addInput({
      hash: element.txid,
      index: element.vout,
      nonWitnessUtxo: Buffer.from(previousTx, 'hex'),
     redeemScript:redeemScript
  });
}  


const feeRate = 1; // Adjust this value based on the current network conditions

const left=balance-feeRate-amountToSend
    
//       // Add output
      psbt.addOutput({
        address: destinationAddress,
        value: amountToSend+feeRate
      });
      psbt.addOutput({
        address:sourceAddress,
        value:left
      })
   
    //  }
     
      // Sign each input
     try {
      
      psbt.signAllInputs(keyPaird)
     
      console.log(psbt.data.inputs)

      // Finalize all inputs
      psbt.finalizeAllInputs();
       
      // Extract transaction
      const tx = psbt.extractTransaction().toHex();
      
      console.log('Transaction:', tx);
      
      getTransactionId(tx);
      
     } catch (error) {
      console.log(error)
     }

**Comment by junderw** [comment]
You need to make sure that every output is actually your output.

**Comment by Aamir0890** [comment]
[{"nonWitnessUtxo": [Object], "redeemScript": [Object], "unknownKeyVals": []}, {"nonWitnessUtxo": [Object], "partialSig": [[Object]], "redeemScript": [Object], "unknownKeyVals": []}, {"nonWitnessUtxo": [Object], "redeemScript": [Object], "unknownKeyVals": []}] is the response I am getting from 

psbt.signAllInputs(keyPaird
 console.log(psbt.data.inputs)
 I think I don't have a partialSig for first element of array and I am getting error. I am not able to resolve it.

**Comment by junderw** [comment]
That's because it's not your UTXO.

**Comment by Aamir0890** [comment]
how do i resolve   const payment = bitcoin.payments.p2sh({  redeem: bitcoin.payments.p2wpkh({ pubkey: keyPaird.publicKey, network: network }) }); to get correct address and redeemScript from 

const { address } = payment;
    const redeemScript = payment.redeem?.output;
    
    console.log('bro')

**Comment by junderw** [comment]
You are misunderstanding me. I didn't say your address or redeemScript are wrong.

You are trying to sign a utxo which is not yours.

Your code is adding EVERY utxo. You only want to add the utxo which **actually has your address**.

You can not spend Bitcoin that was not sent to you.

Bitcoin transactions have multiple outputs, and each output might be sent to a different address.

Do you understand now? Please let me know if something is not clear.
