### ISSUE TITLE
TypeError: Argument must be a Buffer when signing input

### ISSUE THREAD

**Issue by damiandizeo** [bitcoinjs/bitcoinjs-lib#2040]
Hello guys, I have a crash in React Native here `if (toXOnly(pubkey).equals(outputKey)) {` when I need sign an input with a tweak signer

[https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/ts_src/psbt.ts#L1757](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/ts_src/psbt.ts#L1757) 
`const outputKey = getPrevoutTaprootKey(inputIndex, input, cache) || Buffer.from([]);`

it seams `getPrevoutTaprootKey` is not returning a Buffer, it is returning an Array, I could fix it by doing `Buffer.from(outputKey)`, after that was able to sign the inputs without any problem.

Would be great if that can be cast in the next release, thanks in advance!

**Comment by junderw** [comment]
Out of curiosity, what does this give you?

`console.log(Buffer.isBuffer(Buffer.from([1,2,3]).subarray(0,2)))`

I think whatever Buffer polyfill you're using is returning a `number[]` for `Buffer.prototype.subarray` which is incorrect, it should return `Buffer`.

The test suite doesn't crash, which is evidence that something is wrong with your environment.

**Comment by MovsesDev** [comment]
I got false

**Comment by ty-bt** [comment]
@damiandizeo Hi, I have the same problem. Have you found a solution?

**Comment by coderkhalide** [comment]
@ty-bt @damiandizeo did you solve it? and how?

**Comment by coderkhalide** [comment]
This worked for me:

https://github.com/bitcoinjs/bitcoinjs-lib/issues/2005#issuecomment-2571574307
