### ISSUE TITLE
Bitcoin build transaction

### ISSUE THREAD

**Issue by MovsesDev** [bitcoinjs/bitcoinjs-lib#2041]
Hi i try to build transaction but i the method BuildTransaction does not exist in bitcoinjs-lib(in new virsion)

**Comment by junderw** [comment]
> the method BuildTransaction

There has never been a function named `BuildTransaction` in any version of this library.

Please look at the integration tests for examples on how to send coins.

**Comment by MovsesDev** [comment]
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
const bip32 = require('bip32');
exports.bip32 = bip32;
const address = require('./address');
exports.address = address;
const crypto = require('./crypto');
exports.crypto = crypto;
const ECPair = require('./ecpair');
exports.ECPair = ECPair;
const networks = require('./networks');
exports.networks = networks;
const payments = require('./payments');
exports.payments = payments;
const script = require('./script');
exports.script = script;
var block_1 = require('./block');
exports.Block = block_1.Block;
var psbt_1 = require('./psbt');
exports.Psbt = psbt_1.Psbt;
var script_1 = require('./script');
exports.opcodes = script_1.OPS;
var transaction_1 = require('./transaction');
exports.Transaction = transaction_1.Transaction;
var transaction_builder_1 = require('./transaction_builder');
exports.TransactionBuilder = transaction_builder_1.TransactionBuilder;

I meant TransactionBuilder class sorry. in 6.1.5 no such class

**Comment by junderw** [comment]
TransactionBuilder was replaced by the Psbt class.

There are links in the README that link to the integration tests for creating transactions using Psbt.
