### ISSUE TITLE
How can I create inscription psbt with this library?

### ISSUE THREAD

**Issue by devlancer412** [bitcoinjs/bitcoinjs-lib#2044]
I'm going to build a NFT project with this library. There would be two signer - one is user and one is backend privatekey.
And backend builds psbt and user pays fee for that, ofc owner of ordinal after create is user.
and ordinal should be include some metadata and parent inscription.

maybe inputs of this psbt would be utxos of user
and outputs are inscription and platform fee.

Please help me. Short example code would be very helpful

**Comment by jasonandjay** [comment]
This can be done with PSBT, you can visit some example here：https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/psbt.spec.ts

**Comment by hoangndm3139** [comment]
Hi @devlancer412, i have same issue. I'm creating psbt to send inscription. As i know, psbt structure is: 
 - 2 input 
 - 2 output
 Right?
Can you please guide me on this?
