### ISSUE TITLE
Can not sign for this input with the key `03...`

### ISSUE THREAD

**Issue by bormisov1** [bitcoinjs/bitcoinjs-lib#2047]
Hello @junderw!
I hope my message finds you well 🙂

Been stuck with this problem for several days already, so creating this issue. I try to construct a Psbt and extract the input hashes for signature on the client side to later insert the signatures received from the client.

I have a code that provides me the input hashes for signing for a pair of this address and public key: `bc1qsv7fkvgz3afaux0rtvvjdz2g57wyt99vfatsf5` and `02e9fe11a2f18637b8aa6ceb85a02fefda1801cab59c6512a2fd7cb91e8e3e7fab`. The same code doesn't work for `bc1qdlxcmcncy059gw0my604y35s5257mxua6ttlje` and `03163883cf37d71960982ee74ad91168160322688a78769f9c3db9bc72ab1142a9`. The way it doesn't work is throwing this error `Can not sign for this input with the key 03163883cf37d71960982ee74ad91168160322688a78769f9c3db9bc72ab1142a9`.
When simplified my code is:
```
const senderPubKeyBuffer = Buffer.from('03163883cf37d71960982ee74ad91168160322688a78769f9c3db9bc72ab1142a9', 'hex')
const input = {
  hash: '0170d05bf1a64e36020363b9fd4afc64d391a29ed1ffac58cff33ad5a0afe15d',
  value: 21403,
  index: 0,
  nonWitnessUtxo: Buffer.from('010000000001017a5d1fd9635a4fe15beff85a18fc32651ff07736abc24d07afa9d0d8b66c656d0000000000ffffffff02b80b0000000000001600142e212c99d59342f463726ea8f0340a48f56fde049b530000000000001600146fcd8de27823e85439fb269f524690a2a9ed9b9d02483045022100ecab202e666a63668a1b68dcd873be4d57d61e2cbdd8f39b895e70d384b3e143022031ca826e45e944f38d4c9e95dc23ecf97035ed4b73b094feee84f057e0c1e721012103163883cf37d71960982ee74ad91168160322688a78769f9c3db9bc72ab1142a900000000', 'hex')
}
const psbt = new bitcoin.Psbt({ network: bitcoin.networks.bitcoin })
psbt.addInput(input)
const res = await new Promise<Buffer>(
  (resolve, reject) => psbt.signInputAsync(
    0,
    new HashForSignatureExtractorService(
      network,
      senderPubKeyBuffer,
      resolve
    )
  ).catch(reject)
)
```
Where `HashForSignatureExtractorService` is my class that simply gives the hash received for signature to `resolve` of my promise instead of signing that hash. This trick I saw in other issue of this repository.

At the same time, if I replace the `senderPubKeyBuffer` with `Buffer.from('02e9fe11a2f18637b8aa6ceb85a02fefda1801cab59c6512a2fd7cb91e8e3e7fab', 'hex')` and `input` with this object:
```
{
  hash: 'c9881e634ab233507117027689b9de076f66b3f3720d3f90ac661860f9ed5de4',
  value: 1000,
  index: 0,
  nonWitnessUtxo: Buffer.from('010000000001019455a1410f24af41962e0f411defa55f8e80598045a178f5509e408facd1585c0100000000ffffffff02e803000000000000160014833c9b31028f53de19e35b19268948a79c4594acbf0f000000000000160014e1f5b7ec8260da4591fed2e9f8d8ffa97ee522e60247304402202c60e12bb2528ecd5f9f764c486a4f996c02751ef296693c72a56a67fa7c21c402206c9649ff2b34ea3ac38e72c8d02dc75faa22b41d2936c0aba4542735c78f9965012103fd0d1b4909fc660161530ac963583c8561cb169ff01c4cf08bc292578757146500000000', 'hex')
}
```
, then it magically works. I tried comparing the [working utxo transaction](https://www.blockchain.com/explorer/transactions/btc/c9881e634ab233507117027689b9de076f66b3f3720d3f90ac661860f9ed5de4) with a [failing one](https://www.blockchain.com/ru/explorer/transactions/btc/0170d05bf1a64e36020363b9fd4afc64d391a29ed1ffac58cff33ad5a0afe15d), and couldn't find any significant difference as far as I can judge with my understanding of bitcoin.

Would appreciate any help! Thank you 🙂

**Comment by junderw** [comment]
The error is pretty clear.

It can’t sign for that input with that pubkey because that pubkey is unrelated to that input.

**Comment by 2jumper3** [comment]
> The error is pretty clear.
> 
> It can’t sign for that input with that pubkey because that pubkey is unrelated to that input.

Hi @junderw. 

But how it can be possible if we got 3 different addresses, we have the exact same algorithm for obtaining the public address; in the end, two addresses work, but the third one does not?

**Comment by bormisov1** [comment]
> The error is pretty clear.
> 
> It can’t sign for that input with that pubkey because that pubkey is unrelated to that input.

Sorry, what do you mean unrelated? This [txn](https://www.blockchain.com/ru/explorer/transactions/btc/0170d05bf1a64e36020363b9fd4afc64d391a29ed1ffac58cff33ad5a0afe15d) has `bc1qdlxcmcncy059gw0my604y35s5257mxua6ttlje` as output address, which can be derrived as p2wpkh from `03163883cf37d71960982ee74ad91168160322688a78769f9c3db9bc72ab1142a9` pubkey

**Comment by junderw** [comment]
The `bc1qdlxcmcncy059gw0my604y35s5257mxua6ttlje` output is at `index: 1,` but you're using `index: 0,`...

I don't understand what you're talking about. Your input is clearly pointing to a different UTXO.

**Comment by bormisov1** [comment]
> The `bc1qdlxcmcncy059gw0my604y35s5257mxua6ttlje` output is at `index: 1,` but you're using `index: 0,`...
> 
> I don't understand what you're talking about. Your input is clearly pointing to a different UTXO.

Oh sorry, that was so stupid of me. Indeed this `index: 0` caused the issue, and the code worked by coincidence when I had output mint index match an index at which this output would go in a new transaction. Sorry for wasting your time.

At least might be a hint for somebody as heedless as me in future... Thank you for your help and for this repository!
