### ISSUE TITLE
Does bitcoinjs-lib support MuSig2 signature ?

### ISSUE THREAD

**Issue by zhngzck** [bitcoinjs/bitcoinjs-lib#2049]
Does bitcoinjs-lib support MuSig2 signature ?

**Comment by junderw** [comment]
Creation: No. There is no easy to use API, so in that sense we don't support creation.

Verification: Yes. A MuSig2 signature is just a normal signature (that's the whole point) so we can verify it obviously.

**Comment by zhngzck** [comment]
i get it , thank you
