### ISSUE TITLE
SIGHASH_SINGLE | ANYONECANPAY input signed but can't update the unsigned inputs

### ISSUE THREAD

**Issue by elRaulito** [bitcoinjs/bitcoinjs-lib#2050]
I created a psbts with the following inputs:

0 Coming from segwit timelock multisig script, signature SIGHASH_SINGLE | ANYONECANPAY  
1 Placeholder that will be filled later 

I sign 0 and works fine, however as soon as I try to update input 1 as follows 

```
    psbtPartial.updateInput(1,{
      hash: "34466a1f38495b4bc7db5aa07168dddf2c304f535a604a3104a0b610b2b91fc9",
      index: parseInt(0),
      witnessUtxo: {
        script: p2sh.output,
        value: parseInt(30000),
      },
      redeemScript: p2shBorrower.redeem.output
  });
```

I get the error:

![image](https://github.com/bitcoinjs/bitcoinjs-lib/assets/42917076/920c189f-c79c-4ad6-8c6e-7d098ea5e230)

**Comment by junderw** [comment]
Are you sure you don't mean to `addInput`?

**Comment by jasonandjay** [comment]
@elRaulito 
It's obvious that input1 doesn't exist, you should use addInput to add it

If you have no further questions I will close this PR
