### ISSUE TITLE
Mention error toBase58Check on Browser

### ISSUE THREAD

**Issue by fwx5618177** [bitcoinjs/bitcoinjs-lib#2070]
Snapshoot:
![image](https://github.com/bitcoinjs/bitcoinjs-lib/assets/25654385/563b6f0d-9f88-4fda-8dac-544fdaf3392a)

Reason:
When I wanna use this toBase58Check on Browser it would mention error as above.

**Comment by fwx5618177** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/pull/2069

**Comment by junderw** [comment]
Closing in favor of #1855
