### ISSUE TITLE
Error: Cannot find module 'node:crypto'

### ISSUE THREAD

**Issue by wangtao19911111** [bitcoinjs/bitcoinjs-lib#2074]
i use node v16.20.1
any solution for this bug?
`Error: Cannot find module 'node:crypto'
`

**Comment by junderw** [comment]
Unfortunately, node v16 is End of Life. We will not offer support.

https://nodejs.org/en/blog/announcements/nodejs16-eol/

**Comment by wangtao19911111** [comment]
thanks ,but i used aws ec2 ,it`s cann`t support >node v16, what can i do for this?
