### ISSUE TITLE
Transferring runes

### ISSUE THREAD

**Issue by ambitious922** [bitcoinjs/bitcoinjs-lib#2080]
I wanna transfer runes on my node.js backend.
Any help would be appreciated.

**Comment by ambitious922** [comment]
Actually wanna make a psbt for transferring runes.

**Comment by lcovar** [comment]
@ambitious922 did you figure this out? if so can you share the script.

**Comment by TroyMa1990** [comment]
bro how to do it, i want to transfer runes in nodejs too
