### ISSUE TITLE
Apply for manage issues

### ISSUE THREAD

**Issue by jasonandjay** [bitcoinjs/bitcoinjs-lib#2089]
We still have many questions that have not been closed, some of which have been completed through our answers, such as #2084、#2043、#2040、#2024、#2016、 #1910 and so on.If we can close some invalid issues in time, we can focus on some bugs or feats.

Maybe some core contributors or maintainers are busy and have less time. 

If so, I think I can help, not only by managing the issues, but also by taking on some of the problem handling. And of course, I have the time and willingness to maintain this repo. If the time comes, I want to become a member of bitcoinjs and participate in related development and maintenance work at a deeper level.

**Comment by junderw** [comment]
I invited you to triage issues on this repo. Feel free to close issues you feel are irrelevant.

Thank you.
