### ISSUE TITLE
258: txn-mempool-conflict

### ISSUE THREAD

**Issue by A2DNEW** [bitcoinjs/bitcoinjs-lib#2093]
Hi
I use this code to send dogecoin:

```
('sendrawtransaction', [
      psbt.extractTransaction().toHex(),
      true,
    ]);
```

And i get this result:

`6dcdfb42022c829eca72a61267b1bae8621bcc2922201ab347bef66675aa0aa3`

but this TX not found on blockchain

I change my FEE and try to generate again, but i get error:

`error: { code: -26, message: '258: txn-mempool-conflict' },`

Note: I set fee `3000`

**Comment by jasonandjay** [comment]
From error "txn-mempool-conflict" indicate your transaction has been broadcast

**Comment by jasonandjay** [comment]
By the way
1. You can try to search you transaction with your address
2. It seems this issue has no relation with bitcoinjs

**Comment by A2DNEW** [comment]
> From error "txn-mempool-conflict" indicate your transaction has been broadcast

But this txid not found in dogescan: Sorry, '6dcdfb42022c829eca72a61267b1bae8621bcc2922201ab347bef66675aa0aa3' is not a valid transaction or block hash for doge

**Comment by A2DNEW** [comment]
> By the way
> 
> 1. You can try to search you transaction with your address
> 2. It seems this issue has no relation with bitcoinjs

how can i search by address?
because i don't see anything
and i can't create new transaction because i don't have the data

**Comment by jasonandjay** [comment]
> > From error "txn-mempool-conflict" indicate your transaction has been broadcast
> 
> But this txid not found in dogescan: Sorry, '6dcdfb42022c829eca72a61267b1bae8621bcc2922201ab347bef66675aa0aa3' is not a valid transaction or block hash for doge

bitcoinjs is designed for bitcoin and i am not familar with doge chain. So i don`t know txid generate is right or this libs suitable for doge chain.

**Comment by A2DNEW** [comment]
> > > From error "txn-mempool-conflict" indicate your transaction has been broadcast
> > 
> > 
> > But this txid not found in dogescan: Sorry, '6dcdfb42022c829eca72a61267b1bae8621bcc2922201ab347bef66675aa0aa3' is not a valid transaction or block hash for doge
> 
> bitcoinjs is designed for bitcoin and i am not familar with doge chain. So i don`t know txid generate is right or this libs suitable for doge chain.

but i use your recommend code:

const dogecoin = { // <-------- ADD THIS
    messagePrefix: '\x19Dogecoin Signed Message:\n',
    bech32: 'doge',
    bip32: {
        public: 0x02facafd,
        private: 0x02fac398,
    },
    pubKeyHash: 0x1e,
    scriptHash: 0x16,
    wif: 0x9e,
}

at this: https://github.com/bitcoinjs/bitcoinjs-lib/issues/1990#issuecomment-1755940168

**Comment by jasonandjay** [comment]
@junderw might need your help here.
