### ISSUE TITLE
toASM throws TypeError: Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by O2rki** [bitcoinjs/bitcoinjs-lib#2096]
Happens when `decompile` returns a null object, then `toASM` tries to `map`. 
https://github.com/bitcoinjs/bitcoinjs-lib/blob/6396fb488df79dd7cb27eb1b5f9fb56318055ff5/src/script.js#L158-L162

Do I have to check myself (in my code) if `decompile` returns a null before calling `toASM`?.

**Comment by jasonandjay** [comment]
We can optimize decomplie return value to avoid type error.

But you should check your logic why get incorrect chunks to exec toASM?

**Comment by O2rki** [comment]
I was debugging the lib. Incorrect chunks may get there for whatever reason.

**Comment by jasonandjay** [comment]
OK, we will fix it.

**Comment by O2rki** [comment]
Thanks @jasonandjay
