### ISSUE TITLE
offline signing with multiple utxos from different addresses

### ISSUE THREAD

**Issue by dev-dantealighieri** [bitcoinjs/bitcoinjs-lib#2098]
hi,

I want to create a transaction with different Utxos coming from different addresses(and private keys) and sign them offline. How can I use `bitcoinjs` for this? I have a signer that is using `elliptic` with `secp256k1` function, how can i create a transaction and its data to sign, can you provide an example for it?

thanks, dante

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/6396fb488df79dd7cb27eb1b5f9fb56318055ff5/test/integration/transactions.spec.ts#L86
