### ISSUE TITLE
How to use Testnet

### ISSUE THREAD

**Issue by jcrubino** [bitcoinjs/bitcoinjs-lib#21]
How can I use this lib to work with testnet?

**Comment by mixdev** [comment]
From the integration tests
`    var network = bitcoin.networks.testnet
    var alice = bitcoin.ECPair.makeRandom({ network: network })
    var bob = bitcoin.ECPair.makeRandom({ network: network })
    var alicesAddress = alice.getAddress()
    var bobsAddress = bob.getAddress()`

**Comment by mixdev** [comment]
If you want to create the ECPair from a hash:

      var hash = bitcoin.crypto.sha256('correct horse battery staple')
      var d = bigi.fromBuffer(hash)
      var keyPair = bitcoin.ECPair(d, null, {network: bitcoin.networks.testnet});

**Comment by takahser** [comment]
@mixdev this doesn't work anymore, see https://github.com/bitcoinjs/bitcoinjs-lib/pull/1085 and [changelog](https://github.com/bitcoinjs/bitcoinjs-lib/blob/6378a06db06f52e984205632705ec1707be40449/CHANGELOG.md#L33):

- Removed `ECPair.prototype.getAddress`, use `payments.p2pkh` instead (#1085)

However, `payments.p2pkh` doesn't return a testnet address (starting with `m` or `n`), but obviously a p2pkh address that isn't valid on the testnet address (correct me if I'm wrong). Is there still a way to get testnet addresses using bitcoinjs-lib?

**Comment by junderw** [comment]
pass network to p2pkh and all portions inside it.

**Comment by dcousens** [comment]
@junderw is the `.network` information on `ECPair` still useful?

**Comment by junderw** [comment]
with the new payments API, no... not really.

**Comment by dtaipov** [comment]
> pass network to p2pkh and all portions inside it.

@junderw Could you suggest how to pass network to p2pkh? This code still returns mainnet address:
`const { address } = bitcoin.payments.p2pkh({ pubkey }, {network: bitcoin.networks.testnet});`

**Comment by junderw** [comment]
```js
const { address } = bitcoin.payments.p2pkh({ pubkey, network: bitcoin.networks.testnet})
```

this works.

one arg, not two.

**Comment by pavoltravnik** [comment]
I had to pass it directly as a parameter
https://github.com/bitcoinjs/bitcoinjs-lib/issues/1259
`let script = bitcoin.address.toOutputScript(address, bitcoin.networks.testnet);`
