### ISSUE TITLE
Faucet for P2PKH testnet

### ISSUE THREAD

**Issue by A2DNEW** [bitcoinjs/bitcoinjs-lib#2117]
Hi
How can I get faucet for P2PKH testnet?

**Comment by junderw** [comment]
I have no idea. This is not the proper place to ask such a question.

Surely reddit or discord or something should be able to tell you.

**Comment by acsonservice** [comment]
Hi. Always remember that we were not aware of many issues. So let's know that asking is okay but not knowing the problem. I am very happy to answer.   To obtain testnet coins for P2PKH addresses, you can use a Bitcoin testnet faucet. Here's how you can do it:

1. **Set Up a Testnet Wallet**: Ensure you have a Bitcoin wallet that supports the testnet. Popular wallets like Electrum, Bitcoin Core, and others have testnet options. 

2. **Generate a Testnet Address**:
   - For Electrum, you can start it in testnet mode by running `electrum --testnet`.
   - For Bitcoin Core, you can start it in testnet mode by running `bitcoin-qt -testnet` or `bitcoind -testnet`.

3. **Find a Testnet Faucet**: There are several online testnet faucets that provide free testnet BTC. Some reliable ones include:
   - [CoinFaucet.eu](https://coinfaucet.eu/en/btc-testnet/)
   - [Bitcoin Testnet Faucet](https://testnet-faucet.mempool.co/)

4. **Request Testnet Coins**:
   - Visit the faucet website.
   - Enter your testnet Bitcoin address (P2PKH format starts with 'm' or 'n').
   - Complete any captcha or verification process required.
   - Click the button to request testnet BTC.

5. **Receive Testnet BTC**: The requested testnet BTC should be sent to your address within a few minutes. You can verify the receipt by checking your wallet or using a testnet block explorer like [Blockstream Testnet Explorer](https://blockstream.info/testnet/).

Here’s a step-by-step example using the CoinFaucet.eu:

1. Go to [CoinFaucet.eu](https://coinfaucet.eu/en/btc-testnet/).
2. Enter your testnet Bitcoin address.
3. Solve the CAPTCHA.
4. Click on the "Get Testnet Coins" button.

By following these steps, you should be able to get testnet BTC for your P2PKH address and start testing your transactions on the Bitcoin testnet.
