### ISSUE TITLE
Is the tapMerkleRoot required in the input during a key-spend?

### ISSUE THREAD

**Issue by jiffies** [bitcoinjs/bitcoinjs-lib#2130]
I find code in testcase "can create (and broadcast via 3PBP) a taproot key-path spend Transaction (with unused scriptTree".
`    psbt.addInput({
      hash: unspent.txId,
      index: 0,
      witnessUtxo: { value: amount, script: output! },
      tapInternalKey: toXOnly(internalKey.publicKey),
      tapMerkleRoot: hash,
    });`
    Even without the tapMerkleRoot, it still executed successfully.

**Comment by jasonandjay** [comment]
Yes, its not required in the input during a key-spend

**Comment by jasonandjay** [comment]
In addition, we all know that
In Taproot, we can use tweakPrivateKey and Script to unlock UTXO

The first method does not require tapMerkleRoot, we only need to tweak the private key with TaggedHash("tapTweak", P | hash)

The second method requires tapMerkleRoot, we need to verify that the unlocked script is invalid on the MAST tree
