### ISSUE TITLE
Now

### ISSUE THREAD

**Issue by Futuresso** [bitcoinjs/bitcoinjs-lib#2133]
All difficulties

**Comment by jasonandjay** [comment]
If you can describe the specific issue, we can help you better.

**Comment by Futuresso** [comment]
You have some errors you need to fixed that is why you can’t access or fix
them. This is our telegram channel. Text is now so we can fixed and rectify
it thank you

👎👎👎
t.me/devotee00

There is errors and bad network we need to rectify and fixed .this is our
telegram server channel. Text us and indicate your issues so we rectify it
👇👇👇
t.me/devotee00
