### ISSUE TITLE
Add/Remove Co-Signer from Multi Sig Wallet

### ISSUE THREAD

**Issue by FCBtc1116** [bitcoinjs/bitcoinjs-lib#2152]
I created Taproot and Native Segwit MultiSig wallet use bitcoin js lib.
But if I want to update MultiSig co-signer from 3-4, I need to create another MultiSig wallet use 4 pubkeys and send all assets to new generated MultiSig Wallet.
Is it possible to update MultiSig wallet cosigner list use bitcoinjs lib?
So I do not need to send all assets from old wallet to new wallet.

**Comment by junderw** [comment]
That's not possible.
