### ISSUE TITLE
Fractal Bitcoin

### ISSUE THREAD

**Issue by ambitious922** [bitcoinjs/bitcoinjs-lib#2154]
How can I use bitcoinjs-lib on Fractal Bitcoin?
Or when is it going to be available?

**Comment by junderw** [comment]
Bitcoin is not fractal, and it can only be subdivided into 100 million parts known as satoshis.

I hope this answers your question.

**Comment by jasonandjay** [comment]
@junderw @ambitious922 
Fractal Bitcoin forked from bitcoin: https://github.com/fractal-bitcoin/fractal

Bitocinjs-lib is fully supported and can work well

However, I still recommend that you post related questions to Fractal's repo

**Comment by junderw** [comment]
Altcoins usually only pose problems in 2 cases.

1. The coin supply cap is larger than 53 bits (the maximum integer value for JavaScript numbers)
2. The address version bytes are variable length etc.

Litecoin has mweb scripts which use high segwit version numbers, but recent versions of this library support higher segwit versions with a warning.

> Bitocinjs-lib is fully supported

This is untrue. `bitcoinjs-lib` does not support altcoins, and any problems that arise are 100% the responsibility of the implementor.

"bitcoinjs-lib works out of the box with most altcoins, but that is just a coincidence, it can break at any time without notice"

**Comment by jasonandjay** [comment]
> Altcoins usually only pose problems in 2 cases.
> 
> 1. The coin supply cap is larger than 53 bits (the maximum integer value for JavaScript numbers)
> 2. The address version bytes are variable length etc.
> 
> Litecoin has mweb scripts which use high segwit version numbers, but recent versions of this library support higher segwit versions with a warning.
> 
> > Bitocinjs-lib is fully supported
> 
> This is untrue. `bitcoinjs-lib` does not support altcoins, and any problems that arise are 100% the responsibility of the implementor.
> 
> "bitcoinjs-lib works out of the box with most altcoins, but that is just a coincidence, it can break at any time without notice"

Got it
