### ISSUE TITLE
How to handle TAP assets with bitcoinjs-lib

### ISSUE THREAD

**Issue by GreyRabbitty** [bitcoinjs/bitcoinjs-lib#2156]
Nowadays, I am trying to handle TAP assets with bitcoinjs-lib but couldn't find any docs or reference link.
Someone said that it is not implemented to handle TAP assets with bitcoinjs-lib but I am curious about that.
Let me know this is possible and how to do that.

P.S: Also hope to know which wallet support TAP assets.
Thanks.

**Comment by junderw** [comment]
bitcoinjs-lib is a low level Bitcoin library.

You should be able to implement the BIP using this library as a dependency.

https://github.com/Roasbeef/bips/blob/bip-tap/bip-tap.mediawiki#specification

However, this protocol is not something that should ever be merged into bitcoinjs-lib.

**Comment by GreyRabbitty** [comment]
Thanks for your advice.
One more question.
Do you know how to handle TAP assets?
Is there any endpoint to deploy, mint or transfer?
