### ISSUE TITLE
sighashType: bitcoin.Transaction.SIGHASH_DEFAULT return error when `tapLeafScript` is not present

### ISSUE THREAD

**Issue by jrwbabylonlab** [bitcoinjs/bitcoinjs-lib#2157]
Some what related to issue https://github.com/bitcoinjs/bitcoinjs-lib/issues/2046 but not entirely.

The bug we are facing is that we can not set the `sighashType: bitcoin.Transaction.SIGHASH_DEFAULT` when `tapLeafScript` is not present.
It will throw the error of `Cannot add duplicate data to input`

Digger further, the error seems to come from https://github.com/bitcoinjs/bip174/blob/master/src/lib/converter/input/sighashType.js#L29-L31

In our case, the currentData is

```
 {
      unknownKeyVals: [],
      witnessUtxo: {
        script: <Buffer 00 14 59 93 0a fa a8 6b 8d 8c 65 81 d3 55 d5 1f ee f0 e8 d5 b6 c8>,
        value: 33130211
      }
    }
```

whereas the newData is 0

Due to !!0 is false in js, this canAdd method is false as well. hence throw at the bitcoinjs method of

```
if (!canAdd(mainData, data)) {
            throw new Error(`Can not add duplicate data to ${typeName}`);
}
```

**Comment by junderw** [comment]
`newData` should be `{ sighashType: 0 }`

**Comment by junderw** [comment]
If this is a miscommunication of the problem, then it might be easier if you can write a small example showing the issue with actual code.

**Comment by junderw** [comment]
I'm still not sure what the issue is, but it seems like in your OP you found the issue.

Please create a PR on the bip174 repository and get it to pass all the tests. Also add a test if you can that will fail with the current code but is fixed with your new code.

I'll look it over and merge it if the tests pass and the change is small.
