### ISSUE TITLE
BIP174 error caused CommonJS require to fail

### ISSUE THREAD

**Issue by koa202405** [bitcoinjs/bitcoinjs-lib#2166]
Why you decide to set `"type": "module",` in package.json, this a huge broken change.

**Comment by junderw** [comment]
Can you be more specific about your issue?

**Comment by junderw** [comment]
I fixed the issue in bip174 causing the error.

https://github.com/bitcoinjs/bip174/releases/tag/v3.0.0-rc.1

Since bitcoinjs-lib uses ^ dependencies, a re-install (or refresh of lockfile if you install from lockfiles) of bitcoinjs-lib will fix the issue.
