### ISSUE TITLE
bitcoin.script.number.encode behaviour has changed

### ISSUE THREAD

**Issue by rbndg** [bitcoinjs/bitcoinjs-lib#2168]
Previously bitcoin.script.number.encode(32).toString("hex") would return "20" which is what i expected.
in the new version of the lib now it returns "32". 
what happened?

**Comment by jasonandjay** [comment]
This problem does exist, let me fix it

**Comment by jasonandjay** [comment]
We replace Buffer with Uint8Array to enhance compatibility

and `toString('hex')` does not have effect with Uint8Array

Maybe you can try this
```
function toHexString(uint8Array) {
  return Array.from(uint8Array)
    .map(byte => byte.toString(16).padStart(2, '0')) 
    .join(''); 
}

toHexString(bitcoin.script.number.encode(32))
```

It seems like a big change, what suggestions do you have? @junderw @Nesopie

**Comment by junderw** [comment]
We are currently releasing a RC for a new major version.

If you'd like to stay on the previous version please use at least `^` version naming in your package.json to stay on the last major version.

In regards to UInt8Array hex conversion, we have a tool for that here: https://github.com/bitcoinjs/uint8array-tools

We are moving away from Buffer and using Uint8Array only from future versions. Future versions will also use BigInt for satoshi amounts etc.

Once we get enough feedback on the RC we will release an official version with migration guide and everything.
