### ISSUE TITLE
Add stripWitnesses to Transaction

### ISSUE THREAD

**Issue by junderw** [bitcoinjs/bitcoinjs-lib#2169]
Replaces #1951

Iterate through ins and replace witness with EMPTY_WITNESS.

@JacksonDMiller wanna take a crack at it?

**Comment by junderw** [comment]
I made a `v6` branch for backporting.

Please make the PR towards v6 for now and I'll release it as a minor version bump.

If you want to make a second PR against master as well that would be appreciated.

**Comment by JacksonDMiller** [comment]
@junderw Yeah, I would. I'll start reading up and try to get something in soon.

**Comment by JacksonDMiller** [comment]
@junderw no rush at all, but I made a [pull request](https://github.com/bitcoinjs/bitcoinjs-lib/pull/2170) whenever you have time.

**Comment by junderw** [comment]
I'll leave this issue open until we backport to v6.

(Pull the v6 branch, do essentially the same commit on top, then open a PR against the v6 branch instead of master)

**Comment by JacksonDMiller** [comment]
> I'll leave this issue open until we backport to v6.
> 
> (Pull the v6 branch, do essentially the same commit on top, then open a PR against the v6 branch instead of master)

Oops, thanks for reminding me. Some tests are failing on V6 at the moment, so it was easier for me to work against Master while I'm still trying to learn the codebase. I meant to swing back to v6, but it slipped my mind. 

Here is the [PR](https://github.com/bitcoinjs/bitcoinjs-lib/pull/2171), but I have one question.

**Comment by JacksonDMiller** [comment]
@junderw are we good to close this one out now?
