### ISSUE TITLE
How to set witness data in PSBT

### ISSUE THREAD

**Issue by hanakannzashi** [bitcoinjs/bitcoinjs-lib#2175]
I want to spend a P2WSH UTXO which needs two signatures. Alice sign the PSBT, then send partial signed PSBT to Bob, Bob sign the PSBT. Now If I want to build a transaction, I need to hack the `PSBT`
```
const transaction = (psbt as any).__CACHE._TX
```
then build witness data with
```
const witness = buildWitnessData(
  psbt.data.inputs[0].partialSig[0].signature,
  psbt.data.inputs[0].partialSig[1].signature
)
```
then set witness data with
```
transaction.setWitness(0, witness)
```

Is there any PSBT API to do this?

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/32e08aa57f6a023e995d8c4f0c9fbdc5f11d1fa0/test/integration/csv.spec.ts#L145-L160

Here's an example of using a simple CSV script.

It has an example of using a custom finalizer.

Please let me know if you have any other questions, but for now this answers your question; yes, there is an API to do that.

**Comment by junderw** [comment]
If you'd like to post your locking script I could write an example and add it to the integration tests for you.

**Comment by koa202405** [comment]
[witnessStackToScriptWitness](https://github.com/bitcoinjs/bitcoinjs-lib/blob/32e08aa57f6a023e995d8c4f0c9fbdc5f11d1fa0/test/integration/csv.spec.ts#L482) seems pretty complex, is there any existing tool to do this, or we must implement it manually?

**Comment by hanakannzashi** [comment]
@junderw Hello, I have another question, if I have a partial signature (Buffer), how can I set it into PSBT? Currently I do following:
```ts
const input = psbt.data.inputs[0];

if (!input.partialSig) {
  input.partialSig = [];
}

input.partialSig.push({
  pubkey,
  signature,
});
```
But it doesn't seem very good

**Comment by jasonandjay** [comment]
> [@junderw](https://github.com/junderw) Hello, I have another question, if I have a partial signature (Buffer), how can I set it into PSBT? Currently I do following:
> 
> const input = psbt.data.inputs[0];
> 
> if (!input.partialSig) {
>   input.partialSig = [];
> }
> 
> input.partialSig.push({
>   pubkey,
>   signature,
> });
> But it doesn't seem very good

What do you think is inappropriate? Welcome to provide relevant test cases

**Comment by hanakannzashi** [comment]
> > [@junderw](https://github.com/junderw) Hello, I have another question, if I have a partial signature (Buffer), how can I set it into PSBT? Currently I do following:
> > const input = psbt.data.inputs[0];
> > if (!input.partialSig) {
> > input.partialSig = [];
> > }
> > input.partialSig.push({
> > pubkey,
> > signature,
> > });
> > But it doesn't seem very good
> 
> What do you think is inappropriate? Welcome to provide relevant test cases

Since I didn't use a public API to do this, it makes me feel like I'm hacking the PSBT object lol.
