### ISSUE TITLE
How to get psbt from transaction id

### ISSUE THREAD

**Issue by milojeBtc** [bitcoinjs/bitcoinjs-lib#2182]
Recently, I need to get the psbt from transaction id to check all inout and output of transaction (especially tapkeysig vaule on psbt).
How can I get it from tx id.
Is there any api or method to do it?

**Comment by jasonandjay** [comment]
No, you can`t get psbt from transaction id.

**Comment by milojeBtc** [comment]
Thanks for your reply,
Can you check your email?
I sent msg

**Comment by jasonandjay** [comment]
not receive
