### ISSUE TITLE
How to set locking time and unlock of PSBT

### ISSUE THREAD

**Issue by ptc-bink** [bitcoinjs/bitcoinjs-lib#2187]
I'd like to set lock-time PSBT. I can do it but don't know how to unlock psbt. Plz let me know if this is possible

**Comment by jasonandjay** [comment]
Do you mean use nLockTime to lock?

no way to unlock, either psbt or transaction

**Comment by ptc-bink** [comment]
[image: image.png]

**Comment by ptc-bink** [comment]
I need function to unlock token or utxo such as staking in solana.

**Comment by jasonandjay** [comment]
There is no smart contract on BTC, so you can’t actively engage in staking like Solana. 

If it is a time-locked UTXO, you need to wait for it to expire.
