### ISSUE TITLE
Error adding inputs and outputs, unknownKeyVals, RangeError: value out of range

### ISSUE THREAD

**Issue by Divya1129** [bitcoinjs/bitcoinjs-lib#2194]
Using 6.1.6, when creating a psbt for Evrmore coin, adding inputs and outputs, the object is missing properties hash and index for inputs and value, address and script for outputs, instead having an empty array: unknownKeyVals: [].
```input
`{"inputs":[{"unknownKeyVals":[],"witnessUtxo":{"script":{"type":"Buffer","data":[118,169,20,177,22,11,183,65,23,236,167,132,112,61,187,0,151,146,137,213,32,179,161,136,172,192,19,101,118,114,116,6,83,65,84,79,82,73,10,0,0,0,0,0,0,0,117]},"value":10}}]`
```
```output
`"outputs":[{"unknownKeyVals":[]},{"unknownKeyVals":[]},{"unknownKeyVals":[]}]`
```

Sample code

`
    const psbt = new bitcoin.Psbt({ network: evrmoreNetwork() });
    
//adding 2 inputs
    const inputObj = {
              hash: Buffer.from(utxo.tx_hash, 'hex'),
              index: utxo.tx_pos,
              witnessUtxo: {
                script: Buffer.from(voutObject.scriptPubKey_hex, 'hex'),
                value: utxo.value
              }
            };

        psbt.addInput(input);

// adding 3 outputs same way
const changeOutputObj = {
        address: changeSource,
        value: changeOutputAmount,
        script: bitcoin.script.compile([
        bitcoin.opcodes.OP_RVN_ASSET,
        Buffer.from(outputElem.asset, 'utf8'),
        bitcoin.script.number.encode(changeOutputAmount)
      ]);
      };
      
      psbt.addOutput(changeOutputObj);

console.log('decode :: ',psbt);
`

output
`{"data":{"inputs":[{"unknownKeyVals":[],"witnessUtxo":{"script":{"type":"Buffer","data":[118,169,20,177,22,11,183,65,23,236,167,132,112,61,187,0,151,146,137,213,32,179,161,136,172,192,19,101,118,114,116,6,83,65,84,79,82,73,10,0,0,0,0,0,0,0,117]},"value":10}},{"unknownKeyVals":[],"witnessUtxo":{"script":{"type":"Buffer","data":[118,169,20,90,168,76,102,172,149,253,91,136,123,173,230,91,180,82,15,104,120,251,243,136,172]},"value":72064000}}],"outputs":[{"unknownKeyVals":[]},{"unknownKeyVals":[]},{"unknownKeyVals":[]}],"globalMap":{"unsignedTx":{}}}}`

`
console.log('decode :: ', bitcoin.Transaction.fromHex(psbt.toHex()));

output :: RangeError: value out of range
`

Network object
`{
    messagePrefix: '\x15Evrmore Signed Message:\n',
    bech32: 'ev',
    bip32: {
      public: 0x0488b21e,
      private: 0x0488ade4
    },
    pubKeyHash: 33,
    scriptHash: 92,
    wif: 0x80,
    derivationAccountPath:"---some value---"
  }`

**Comment by junderw** [comment]
Psbt is not JSON serializable. The JSON serialization of Psbt is not part of the public API interface, and the only supported serializations are the official BIP174 serialization.
