### ISSUE TITLE
Replace jsbn.js

### ISSUE THREAD

**Issue by arasmussen** [bitcoinjs/bitcoinjs-lib#24]
```
var eckey = new Bitcoin.ECKey(secretKey);
var curve = getSECCurveByName('secp256k1');
var g = curve.getG();
var curvePoint = g.multiply(eckey.priv);
```

This last line takes about 20 milliseconds on my computer, which is a bottleneck for the product I'm developing. Would love to see if we can make it faster.

**Comment by hasanmehmood** [comment]
Hi everyone, I have a question ? 

I am using bitcoinJS library and I want to create less compressed pub key via private key ? 
any help would be appreciated, Please help!
