### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#272]
Just a stub issue, but we really need to start focusing on this.

**Comment by tnishimura** [comment]
I've started a simple [doc/reference file](https://github.com/tnishimura/bitcoinjs-lib/blob/master/doc.md) on my fork, mostly to serve as notes during my development). if people are interested i'll submit a pull request when it is a little more complete.

**Comment by dcousens** [comment]
Thoughts on an inline documentation format?

**Comment by jprichardson** [comment]
> Thoughts on an inline documentation format?

"inline" as in a folder named "docs" or something like that right? You don't mean "inline" as in line with the code a la JSDocs, right?

**Comment by dcousens** [comment]
@jprichardson either or.  I'd want the documentation to be as deterministic as possible,  and not something we have to keep in sync.

**Comment by jprichardson** [comment]
> something we have to keep in sync.

I'm of the school of mind that that's what it takes to produce quality software, however, I don't see any reason why this couldn't be automated to some degree.

I really despise inline documentation (inline with the code/ like JSDocs) as it really bloats source files. I wouldn't mind Flow comment annotations as that's at least useful and it would improve the quality of the software. I don't have any problem or issue with documenting tests though.

I have some thoughts on a building a tool to automate the process of building documentation. The number one principle of the tool would be that tests serve as the ultimate source of documentation, however expecting users of the library to dig into the test files is unreasonable. The main requirement of this tool would be to have a 'standard' sort of way to layout test files. Would changing the layout/renaming test files be something that you're opposed to?

**Comment by dcousens** [comment]
> I really despise inline documentation (inline with the code/ like JSDocs) as it really bloats source files. 

Agreed,  but it can still be simpler than maintaining external documentation IMHO.

>  I wouldn't mind Flow comment annotations as that's at least useful and it would improve the quality of the software.

There only a few cases,  namely around more complex classes such as `TransactionBuilder` that the "bloat" part of inline documentation would really become painful.
For most of the code base, simply specifying the types and referencing behaviour from tests would be more than enough.

> I have some thoughts on a building a tool to automate the process of building documentation. The number one principle of the tool would be that tests serve as the ultimate source of documentation, however expecting users of the library to dig into the test files is unreasonable. The main requirement of this tool would be to have a 'standard' sort of way to layout test files. Would changing the layout/renaming test files be something that you're opposed to?

What did you have in mind?  This sounds intriguing,  but,  I'd rather not re-write our entire testing infrastructure for something experimental (both technically and socially).

**Comment by bhollan** [comment]
@dcousens @jprichardson 
I actually would love to help with this.  I have tons of time on my hands right now, I've worked with documentation a bunch at my last job, and I love the idea that the tests should show the way without having to dig through them.

**Comment by dcousens** [comment]
@bhollan did you have any ideas on how we could move forward?
I mean, we could easily settle on one thing and leave it at that, but it might be worth just a few more minutes discussion.

**Comment by bhollan** [comment]
@dcousens  I sent an e-mail to @jprichardson to discuss his idea, but haven't heard back yet.  We can discuss here if it would be better.  Your response to his idea seemed favorable enough I assumed it was moving forward.
I really like underscore's side-by-side layout.  http://underscorejs.org/docs/underscore.html
I think it should probably be easy enough to generate one document that is all the tests stitched together, and the another that is all the 'examples' with each test.  There would be a bit of work to create a baseline of examples, but it would be pretty simple to upkeep after that.  Just make an example every time a new test is created and re-run the script with every re-release.

I also like the loaclized examples on bootstrap.  http://getbootstrap.com/css/
This would be a lot more work, but it's something.

I was thinking like a bitcoinjs.org/docs or /examples or something.  I think it should be something that gets built from the test source code with every official release.

Just some thoughts.

**Comment by weilu** [comment]
How about whoever __actually__ makes a PR gets to decide which doc format we use? ;) I'm happy to live with any inline doc format. Any doc is better than no doc.
