### ISSUE TITLE
The minified file used for the client side should be included in this lib

### ISSUE THREAD

**Issue by totty90** [bitcoinjs/bitcoinjs-lib#314]
As every proper repo, the min file should be already included. Don't expect every dev can build it (might use win and missing some build tools). 

Put the min file in this folder '/dist' and can be named 'bitcoinjs-lib.min.js'.

Edit: Seems like you have already talked about this: https://github.com/bitcoinjs/bitcoinjs-lib/pull/252 but you closed. I have to say that I've never found a bower component that requires any build step before use. Take a look at every client side javascript lib (not only bower) and you will see that they all have a min file bundled. You can create a script to run every time you want to publish a new version that creates the min file and do other stuff you need. 

If you don't put a min file then many client side dev will not use this (I don't know if you care or not, but I hope you do).

**Comment by davidapple** [comment]
I understand your security concerns. However, having to compile this locally is a massive pain. I am a proficient web developer, however, I routinely work on machines that throw errors when running npm. This is a massive barrier to entry for a lot of developers and a huge time sponge.

Please make a compiled version of bitcoinjs-lib v4.0.2 available from somewhere. Even if it's from another repository. Nearly all other js libraries include a dist folder with a minified version of the library pre-compiled. It's standard and saves a huge amount of time.

I'm sure people using this for serious financial applications are aware of the risks. But forcing people to compile every time is blocking the majority of developers that want to play.

**Comment by dcousens** [comment]
Half the libraries interface is using a Buffer.  How do you expect to use it?

**Comment by dcousens** [comment]
I don't think any new argument has been presented.
Should we lock this one?

**Comment by jprichardson** [comment]
> Should we lock this one?

Yes. 

@davidapple A new issue should be created to discuss this. Including a bundled version carries an additional audit burden for consumers of the package. Also, there's a lot of packaged overlap due to the reliance upon Node.js specific libs which means the payload size would generally be quite large and unnecessary for most. I realize it's painful for you, but these days it's inescapable for web devs to avoid using npm; so much tooling depends upon it.
