### ISSUE TITLE
Optional network considered harmful

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#325]
Reference: https://github.com/bitcoinjs/bitcoinjs-lib/pull/321

Should the interfaces `ECPair.fromWIF` and `HDNode.fromBase58` always require a `network` parameter?
We could use auto-detect based on the version flag, but there comes up the problem that networks recently added to the network constants have duplicate constants that would mean auto detection may be misleading for those unaware.

In this sense, it is considered harmful in its current state, where the bitcoin default can regularly throw off users (especially with `.getAddress()` in <2.0.0) and the auto detect can cause incredibly difficult-to-trace bugs.

**Comment by dcousens** [comment]
My conclusion here was to remove `optional network parameter(s) that default to Bitcoin`, and to provide an `optional network parameter when network information may already be
present` that a user can use to force a certain network.

As for #278,  I think we should simply add instructions for how to add your own network information easily,  and then remove all non top 5? networks.

``` javascript
var networks = require('bitcoinjs-lib').networks

networks.viacoin = {
  magicPrefix: '\x18Viacoin Signed Message:\n',
  bip32: {
    public: 0x0488b21e,
    private: 0x0488ade4
  },
  pubKeyHash: 0x47,
  scriptHash: 0x21,
  wif: 0xc7,
  dustThreshold: 560,
  dustSoftThreshold: 100000,
  feePerKb: 100000
}
```

With `estimateFee` being moved to `Transaction`.

**Comment by weilu** [comment]
Works for me. We should make it clear in our docs that the additional networks should be defined before other function calls to bitcoinjs-lib, alongside what are compulsory/optional fields for a network object.

**Comment by dcousens** [comment]
I vote we remove `estimateFee` entirely, it is misleading, and with the introduction of `Transaction.prototype.byteLength`, you can just do the `Math.ceil(byteLength / feePerKb)` very easily yourself.

Given `feePerKb` now needs to be changed due to https://bitcoin.org/en/developer-reference#estimatefee being a protocol level, non-constant, I think this also makes sense.

This complexity isn't something that should be hidden away.

**Comment by jprichardson** [comment]
> I vote we remove estimateFee entirely, it is misleading, and with the introduction of Transaction.prototype.byteLength, you can just do the Math.ceil(byteLength / 1000) * feePerKb very easily yourself.

Seems reasonable to me.

**Comment by dcousens** [comment]
The remaining part of this issue should be resolved with the merging of `ECPair`.
