### ISSUE TITLE
TransactionBuilder.fromTransaction

### ISSUE THREAD

**Issue by bezreyhan** [bitcoinjs/bitcoinjs-lib#331]
I'm running into an interesting issue. 

If I add inputs to a TransactionBuilder I do not get any errors. However, when I add inputs to a transaction and then run TransactionBuilder.fromTransaction(tx) I get this error: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L90

The problem arises here: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L90

when I console.log the result of classifyInput I get:      
   
     "nonstandard"

Am I doing something incorrectly or is there a bug here? Should we be running classifyOutput instead of classifyInput? 

Thanks

**Comment by dcousens** [comment]
@bezreyhan fixed in https://github.com/bitcoinjs/bitcoinjs-lib/pull/329

**Comment by bezreyhan** [comment]
@dcousens  Yup, fixed it.

 It hasn't been merged into master yet right? It only worked "txbmerge" but not "master"

Thanks.

**Comment by weilu** [comment]
No not merged in master yet
