### ISSUE TITLE
Error in HEX when combining two inputs for transaction

### ISSUE THREAD

**Issue by adityapatadia** [bitcoinjs/bitcoinjs-lib#339]
When I use the TransactionBuilder for building one transaction, it works fine but when I add two input transactions, the blockchain says that generated hex is not valid. Code:

```javascript
tx = new bitcoin.TransactionBuilder();
tx.addInput(txn.txnId, 0); // this is one transaction id from database

transactionIds.forEach(function(txid, index) { // these are unspent transaction from another address
	index = index + 1
	tx.addInput(txid, index);
});

tx.addOutput(someAddr, someValue);
tx.addOutput(reserveAddress, unspentValue - someValue); // extra back to same acc
				
tx.tx.ins.forEach(function(input, index) {
	var privKey;
	if(index == 0){
		privKey = bitcoin.ECKey.fromWIF(privKeyForFirstInput);
	} else {
		privKey = bitcoin.ECKey.fromWIF(privKeyForOtherInputs);
	}
	tx.sign(index, privKey);
});
tx.build().toHex(); // the hex is generated but blockchain gives invalid hex error.
```

**Comment by dcousens** [comment]
What version are you using?  Is this on master?
Do you have any test data you can provide us?

**Comment by adityapatadia** [comment]
I use 1.4.x from npm. I am trying to achieve very simple thing. Just take two unspent transaction on two different address and send btc on third address. Let me know which kind of data would help you.

**Comment by dcousens** [comment]
You're transaction input `vout`'s are wrong.  Remember, they need to correspond to the output index in the transaction specified by `txid`.

**Comment by adityapatadia** [comment]
Ok I corrected that problem of vout. I get this error when I post transaction to blockchain: ```Transaction contains none standard zero output```

**Comment by dcousens** [comment]
I'm going to need more data to be able to help you with that.

**Comment by adityapatadia** [comment]
Ok, I found the problem. One of the output was for 0 bitcoins. I removed that output and it worked. Thanks.
