### ISSUE TITLE
example on bitcoinjs homepage is outdated

### ISSUE THREAD

**Issue by kevinmartinmauro** [bitcoinjs/bitcoinjs-lib#347]
take out the new Transaction() example on the homepage.
spent hours before i realized it was deprecated with my version of bitcoin core

**Comment by dcousens** [comment]
@kyledrake are you able to get to this?

**Comment by olalonde** [comment]
The integration examples are also outdated: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/advanced.js#L9

This doesn't work with bitcoinjs-lib 1.5.6

**Comment by dcousens** [comment]
Master branch is our dev branch.  They are the latest (2.0.0pre) actually.

**Comment by dcousens** [comment]
Fixed with https://github.com/bitcoinjs/bitcoinjs.github.com/commit/269385a2893b44da1fc030e8026cdeabba7fa886
