### ISSUE TITLE
Integrate faster libsecp256k1 library

### ISSUE THREAD

**Issue by Polve** [bitcoinjs/bitcoinjs-lib#361]
Latest version of bitcoin-core has integrated https://github.com/bitcoin/secp256k1 by Sipa.
The greenaddress team has made some test converting it to JS with emscripten and from a quick test the result is from 10x (on chrome) to 20x (on FireFox) faster then bitcoinjs-lib (!!).

For this reason they are integrating it in bitcoinjs in their wallet:
https://github.com/greenaddress/WalletCrx/commit/c9a514beea23b1f4889e929acb43099a40fd4d4f

It would be great to have it officially (and cleanly) included in your library :)

**Comment by jprichardson** [comment]
I'm very much against including any emscripten output into bitcoinjs-lib
since emscripten output is hard for a human to read and comprehend (AFAIK),
as such, it'd be more difficult to audit. Given previous principled stances
taken by existing project maintainers and contributors - specifically
regarding minification / uglifiying, this stance is very much idealogical
consistent with their views.

We can achieve significant performance increases by switching from
ecurve/bigi to elliptic/bn.js.

On Sun, Feb 15, 2015 at 1:27 PM, Alessandro Polverini <
notifications@github.com> wrote:

> Latest version of bitcoin-core has integrated
> https://github.com/bitcoin/secp256k1 by Sipa.
> The greenaddress team has made some test converting it to JS with
> emscripten and from a quick test the result is from 10x (on chrome) to 20x
> (on FireFox) faster then bitcoinjs-lib (!!).
>
> For this reason they are integrating it in bitcoinjs in their wallet:
> greenaddress/WalletCrx@c9a514b
> <https://github.com/greenaddress/WalletCrx/commit/c9a514beea23b1f4889e929acb43099a40fd4d4f>
>
> It would be great to have it officially (and cleanly) included in your
> library :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoinjs/bitcoinjs-lib/issues/361>.
>



-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson

**Comment by Polve** [comment]
Of course I understand your concern: yes, emscripten output is totally unreadable, but of course you can audit the C sources.
Inclusion of the optimized low leverl lib just on build/minification/uglification phase would be great.

**Comment by dcousens** [comment]
@Polve I agree with @jprichardson that it is very important that the code is easily auditable.  I also feel that there is no reason that @indutny and the elliptic/bn.js wouldn't be able to be on par, if not significantly surpass the performance of the emscripten build of `libsecp256k1`.

@rubensayshi had a point about consensus in #350, however most of the consensus related parts of our ECDSA were ironed out a while ago.  We also would need to ensure feature parity.

**Comment by Polve** [comment]
I missed pull req #350, thanks for the link.

**Comment by dcousens** [comment]
This was slightly different to #350 because you wanted emscriptem over a
native fallback.

**Comment by Polve** [comment]
You are right, sorry.
I prefer to keep it open then, if it's ok for you.

**Comment by indutny** [comment]
Spent some time on benchmarks: http://jsperf.com/jsbn-vs-sjcl-ecc/24.

Results: slower on chrome, faster on firefox.

**Comment by indutny** [comment]
And on latest chrome situation is very sad: elliptic is 2x faster than libsecp256k1, while on firefox it is in reverse.

**Comment by rubensayshi** [comment]
@indutny wouldn't `verify` or `sign` be more relevant to benchmark?

**Comment by indutny** [comment]
@rubensayshi it might be, but the cornerstone of all ECC benchmarks is scalar multiplication of points

**Comment by indutny** [comment]
@rubensayshi though, if you'll do a `.sign()`/`.verify()` benchmark - it would be interesting too

**Comment by dcousens** [comment]
Closing in favour of #394, whatever that library may be.
