### ISSUE TITLE
Readme listing "Justchain"

### ISSUE THREAD

**Issue by ensby** [bitcoinjs/bitcoinjs-lib#365]
Besides having the wrong name for Justcoin Exchange, Justcoin was taken over recently by ANX, who uses their own code, so I don't think it makes sense anymore to list them as an example for implementation of bitcoinjs. (For all I know, ANX might use bitcoinjs, but in any case the whole site has been replaced)

**Comment by dcousens** [comment]
Thanks for pointing this out @ensby, fixed in https://github.com/bitcoinjs/bitcoinjs-lib/commit/27d10c0853865437502e03c357e686585d718e67

**Comment by dcousens** [comment]
If they want to add it back, I'm sure ANX will follow up.
