### ISSUE TITLE
Problem (Buffer out of range) with tx.fromBuffer when decoding output script

### ISSUE THREAD

**Issue by p2pmining** [bitcoinjs/bitcoinjs-lib#367]
This transaction with a non standard/bad output scripts throws error when decoding from buffer.  

`ebc9fa1196a59e192352d76c0f6e73167046b9d37b8302b6bb6968dfd279b767`
 
Blocks at heights 265453-265458 have transactions like this one.

**Comment by dcousens** [comment]
@p2pmining thanks for reporting, investigating now

**Comment by dcousens** [comment]
This is an interesting bug.

The essence is that [bitcoin/bitcoin](https://github.com/bitcoin/bitcoin) allows transactions with `scriptPubKey`s that do not follow the chunking rules set out by bitcoin `Script` at all.
There are `IsStandard` checks, but, other than that, its up to the miner.

Further reading:

https://bitcointalk.org/index.php?topic=315509.5
https://bitcointalk.org/index.php?topic=575142.msg7724851#msg7724851

I'll have a fix for this soon enough...

**Comment by dcousens** [comment]
Resolved in #375.

**Comment by dcousens** [comment]
@p2pmining would you be able to verify independently that this fixes your issue?

@weilu review as soon as possible, I'd like to merge into `1.5.x` soon,  happy for post-merge review if you are.

**Comment by p2pmining** [comment]
#375 took care of the issue. Thanks :)
