### ISSUE TITLE
Patches for `1.x.y`

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#371]
Just curious how did we want to handle bug fixes and patches for `1.x.y` after we release the `2.0.0` tag?

I have set up a `1.5.x` branch for now which I'll rebase some fixes on to, but naturally I don't want to spending all my time back-porting changes.

@weilu ?

**Comment by dcousens** [comment]
This has come to light after the merge of #317 and committing of https://github.com/bitcoinjs/bitcoinjs-lib/commit/bcf8d0177dfb9b7c859b010aec695293372bf764 to master.

**Comment by weilu** [comment]
> I have set up a 1.5.x branch for now which I'll rebase some fixes on to

That's the way I'd suggest

> but naturally I don't want to spending all my time back-porting changes.

Agreed. How about we set an end-of-life for 1.x.x? say 3 months after 2.0.0 comes out?

**Comment by dcousens** [comment]
@weilu I think that is fair, but that could become harder as time goes on and the internals change.

**Comment by dcousens** [comment]
Currently being tracked by https://github.com/bitcoinjs/bitcoinjs-lib/pull/376,  will close this.
