### ISSUE TITLE
Add missing tests (see included list)

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#382]
- [x] Add tests for `Transaction` with no signatures
- [x] Add/verify tests for `TransactionBuilder.fromTransaction` that cover the situations specified in #404
- [x] Add tests to verify #415 is not an issue
- [x] https://github.com/bitcoinjs/bitcoinjs-lib/pull/447#issuecomment-133856729

**Comment by dcousens** [comment]
@jprichardson you want to do this? haha
The issue was that we don't have any tests for an empty `scriptSig`, that is, nothing signed.

**Comment by jprichardson** [comment]
> @jprichardson you want to do this? haha

Possibly. I'm still waiting for an email response from you about the project standards, protocol, etc :p

**Comment by dcousens** [comment]
All resolved,  closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/pull/460 for the last point.
