### ISSUE TITLE
How to use bitcoinjs to create my own web wallet for my Altcoin?

### ISSUE THREAD

**Issue by coingeek** [bitcoinjs/bitcoinjs-lib#386]
Is there any document for that?

also is there to make this library generate address for altcoin?.

thanks

**Comment by dcousens** [comment]
See the example for mo https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/basic.js#L8 

`bitcoin.ECKey.makeRandom().pub.getAddress(bitcoin.networks.testnet).toString()`
