### ISSUE TITLE
how we get this parmeters from bitcoin?

### ISSUE THREAD

**Issue by coingeek** [bitcoinjs/bitcoinjs-lib#387]
litecoin:{
magicPrefix:"Litecoin Signed Message:\n",
bip32:{
"public":27108450,
"private":27106558},
pubKeyHash:48,
scriptHash:5,
wif:176,
dustThreshold:0,
dustSoftThreshold:1e5,
feePerKb:1e5,
estimateFee:estimateFee("litecoin")},

i need to know  how extract this from bitcoin??

**Comment by dcousens** [comment]
`require('bitcoinjs-lib').networks.litecoin`

Does this help?

**Comment by coingeek** [comment]
thanks, 
thanks, it works,
but there is another issue,
my balance: 5 coin.
when i create transaction to send for example .5 coin.
the system take fees = 4.5 the rest of my balance??
how to resolve the transaction fees problem.

**Comment by dcousens** [comment]
Send the rest to a change address.   See https://en.bitcoin.it/wiki/Change
for an explanation.   Feel free to ask any further questions.

**Comment by coingeek** [comment]
when i sent coin from wallet, it sent only what i need and send with it the fees?
when i do the bitcoinjs.
this is my code:

 var key2 ='xxtCx8Ug5j1bEW7paTpmTRnV5A3HEVXSBYies9FXQr9uk211Bcxx';
               var key = Bitcoin.ECKey.fromWIF(key2);   
                var PubKey =  key.pub.getAddress().toString();
                var PrivKey = key.toWIF();                            
                    document.write('<br>');                        
                    document.write('(WIF format)= '+ key.toWIF());                       
                    document.write('<br>');                        
                    document.write('Public Key= '+ PubKey.toString());
                    document.write('<br>');                
                    var tx =  new Bitcoin.Transaction();               
                    tx.addInput("xx12d483ce950abf0719da448a9449f2a1bec9301842db321e9684df3d143dxx", 0);
                    tx.addOutput('xxJqhLzywMxh5xywBLPQKH7Na1M29szuxxx', 5500000);
                    tx.sign(0, key);
                    var txh = tx.toHex().toString();       
                    document.write('<br>'); 
                    document.write('txh= ' + txh);

**Comment by dcousens** [comment]
@coingeek perhaps the following stack exchange question will help: http://bitcoin.stackexchange.com/questions/1629/why-does-bitcoin-send-the-change-to-a-different-address#1637

**Comment by dcousens** [comment]
Closing, if you need any help, feel free to still ask.
As for the above, if that is a real private key, replacing several letters with `xx` does not improve the situation that you are revealing it publically.
