### ISSUE TITLE
TX rejected (code -22)

### ISSUE THREAD

**Issue by coingeek** [bitcoinjs/bitcoinjs-lib#388]
Is there any way to know this errore
I test the first transaction it works, then i create another one based in the last previous transaction hash.
it not works and get this error.
Can any one help in that?

**Comment by jprichardson** [comment]
Unfortunately this an error produced by `Bitcoin-qt` (`bitcoind`) that indicates that the transaction isn't valid. It'd be very helpful if `Bitcoin-qt` was more descriptive, but unfortunately it's not at the moment. But what you can do is use the RPC (debug) command `decoderawtransaction` and inspect your transaction closely.

Look for the following:

1. Do the sum of the inputs cover the sum of the outputs? i.e. input amount >= output amount
2. Are you reusing an unspent output (input / UTXO), is it listed twice?
3. Make sure that the transaction is actually signed.

I'm sure there's more... but these are the common ones off the top of my head.

**Comment by coingeek** [comment]
how to make sure it is signed? is there command?

**Comment by jprichardson** [comment]
I'd encourage you to browse through these: https://github.com/bitcoinjs/bitcoinjs-lib#examples more specifically, this one: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/basic.js#L36. If you're still having issues, you may want to actually paste the raw transaction. You won't actually reveal anything sensitive by doing that, just don't paste your private keys, or better yet, use testnet. Also, pasting the snippets of code that you're using and getting stuck on would be helpful for us to help diagnose the problem.

**Comment by dcousens** [comment]
Closing, @coingeek if you solved this, it might be helpful to others to post your solution here.
A canonical method of signing a transaction using this library can be [found here](https://github.com/bitcoinjs/bitcoinjs-lib/blob/b0e1d0d9c3f16d09e8addeb5f803322c78144e18/test/integration/basic.js#L50-L59).
