### ISSUE TITLE
Parameterize network information detection

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#402]
Remaining aspects of https://github.com/bitcoinjs/bitcoinjs-lib/issues/325

We should add `network` to all parts of the API that need it~~, with no defaulting~~.

~~That means `ECPair.fromWIF` would require a target network, with an `Error` thrown if the wrong network is given.~~
Same with `HDNode.fromBase58`.

**Comment by dcousens** [comment]
This part of #325 was probably the most controversial,  and likely demands more discussion.
I know as a user of this library, in any cases where I alternate between testnet and mainnet for testing anyway, my code is littered with the network information anyway, so this just enforces that behaviour for me.

But it does make the examples a little more verbose.

**Comment by jprichardson** [comment]
Disagree with not having a default `network`. Maybe it's just a matter of taste for me. But it seems that it should always default to the bitcoin network. I understand that it may add more clarity, but at the cost of verbosity, that's for sure.

**Comment by dcousens** [comment]
@jprichardson its an interesting problem to be sure.   Defaults are powerful.   But in this case they can also be a source of error.

I know for a fact that they would be useful in avoiding little frustrating errors that pop up often,  but they don't appear to be too harmful as the error is usually immediately obvious.

**Comment by dcousens** [comment]
I think defaults are usually acceptable if the result is still correct, but maybe just not ideal.  In this case, the result is not ideal nor correct.

**Comment by dcousens** [comment]
Ping @weilu, @rubensayshi for any further discussion and thoughts?  Yay or nay on this?

**Comment by rubensayshi** [comment]
I like having a default network, 

but I have to admit, I've personally build everything I did so far to support both testnet and mainnet and thus specify the network all the time.  
So my regular argument of 'if 90+% of the use cases are X then it should be the default' doesn't seem to apply as much.

regardless I think a default doesn't hurt and makes life easier for a group of users, including most likely people who try out the library for the first time

**Comment by weilu** [comment]
Provide a consistent default network when possible. In case of detection of a network, require a list of possible networks passed in.

**Comment by dcousens** [comment]
> In case of detection of a network, require a list of possible networks passed in.

That is an interesting approach.
I guess that would absolve the use of the global networks object entirely making extending the library to alt coins quite simple to explain.

**Comment by dcousens** [comment]
Unless there is further discussion,  I'm actually thinking the best approach for the auto-detected networks will be as @weilu outlined above:

> Provide a consistent default network when possible. In case of detection of a network, require a list of possible networks passed in.

And for the default network, maintain the behaviour as it currently stands.

**Comment by dcousens** [comment]
Resolved in #425
