### ISSUE TITLE
Redundant blank signatures are added when signing incomplete multisig transaction

### ISSUE THREAD

**Issue by nixoid** [bitcoinjs/bitcoinjs-lib#404]
My goal is to sign pre-generated 3-of-5 transaction with 1 signature and transmit it to other 2 signers.

Transaction is somewhat custom (omnilayer extension to be specific) so i cannot build it from scratch using bitcoinjs. So i'm getting pre-constructed unsigned transaction from another place.

Pre-constructed transaction comes with 3 OP_FALSE codes, supposed to be replaced by signatures, but after signing with bitcoinjs i'm there is a signature and 4 to-be-replaced OP_FALSE codes are there.

Steps to reproduce:

    privateKeyWIF = 'L1NCkTfLgduMYtLkXgVGgskYfPYkN23MCHDSukStcV8d1i1EwWjz'
    // transaction with no signatures
    txHex = '01000000019c1c878eff34fb9262a02b8490fd0efb59bbd8b083170dc24ff10e99c742ffda03000000b3000000004cad532103832abbe9737befa67ea259fe06541c2585ba29462bc86f4fc67ac8235600984a2103dd0cc537865c5f04eadd58812b63a2fcf39fcb8158673ef794608af57ebd58c721029db58dbf054452422f0b51d68f93b8ff4160f2f7a44edc2a7f3103ec3d872e222102d89857b54f59b58726560c6de7db15c787fbd2b2bb0c0b615351366de96b91712103fc035bc6f1336c82ac1cb6d6928f3d21cf3c0610f577551b8d565a001297ab4b55aeffffffff04ac02000000000000475121030c28fe5f18c699a30b62b7d67de92b7493658f2bab2a1806fbf5f0ea7f28e8db21022ac1c2aa5600b2e8e68126945bf9ac83aa663357c8018fdea271a4886e2e2b6852ae22020000000000001976a914946cb2e08075bcbaf157e47bcb67eb2b2339d24288ac22020000000000001976a9149e0070a1aaa842e95f5fb4639d26802526c6304a88ac601100000000000017a9146d73e76d90cfdf438f6b394fb6ff8f08b6bf2d198700000000'

    key = BitcoinJs.ECKey.fromWIF(privateKeyWIF)
    tx = BitcoinJs.Transaction.fromHex(txHex) 
    var txb = BitcoinJs.TransactionBuilder.fromTransaction(tx)
    txb.inputs[0].hashType = BitcoinJs.Transaction.SIGHASH_ALL
    txb.sign(0, key, txb.inputs[0].redeemScript, BitcoinJs.Transaction.SIGHASH_ALL)
    console.log(txb.buildIncomplete().toHex())

1) copy & paste unsigned tx (provided above) to the raw transaction parser
https://brainwallet.github.io/#tx (raw transaction mode).
Notice that there is  4 OP_FALSE at the beginning of scriptsig - 1st is by protocol and other 3 are to be replaced with signatures

2) sign transaction using the code above
copy & paste result to the transaction parser and notice that 2 redundant OP_FALSE were added:
OP_FALSE 30440220111f4eca646ea76abd4fac6700e033c9cae6136f278e3b8edc3a8bea241686e202201cbf064fa22b653858b965e1904398c1a00c279147878c99a57adb7cef6e538901 OP_FALSE OP_FALSE OP_FALSE OP_FALSE 

exptected result:
OP_FALSE 30440220111f4eca646ea76abd4fac6700e033c9cae6136f278e3b8edc3a8bea241686e202201cbf064fa22b653858b965e1904398c1a00c279147878c99a57adb7cef6e538901 OP_FALSE OP_FALSE

I've spent 2 days debugging this and believe that bug is in TransactionBuilder.prototype.sign method, this block of code specifically:
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L376-L398

after matching the number of signatures to the number of public keys for validation purposes it does not reduce it back to required minimum. Like it expects to get 5 signatures for 3-of-5 transaction. And that is unlikely to be a case.
 
Proposed fix is to reduce the number of signatures back to required minimum after doing the "order enforcement". 

As a temporary workaround i've just commented out mentioned block and it works for me.

**Comment by nixoid** [comment]
@rubensayshi you was the one who added this check 
@dcousens you was the last one who touched it

Thoughts?

**Comment by rubensayshi** [comment]
bitcoinjs prefills the signatures with `OP_0`s for every pubKey (so total of 5), that way if the for example the 4th `OP_0` is already replaced with a real signature you will know that it is the signature for the 4th pubKey.  
this way if you get a transaction with an equal amount of signatures (or `OP_0`s) to the pubKeys you know you can leave it untouched and asume the order is already correct.

**Comment by dcousens** [comment]
@nixoid it is as @rubensayshi says.

I guess it could go either way, but it shouldn't have any functional difference.  Is there a specific problem?

I'm not sure if there is a specific standard around this other than trying to comply with other implementations.

**Comment by dcousens** [comment]
@nixoid I'm going to close this,  as its not really a problem.
The extra `OP_0`s should be compliant with implementations that don't support it,  however for us it means we can optimize public key verification in `TransactionBuilder.sign`.
