### ISSUE TITLE
Replace the tip4commit with bountysource

### ISSUE THREAD

**Issue by smithb1994** [bitcoinjs/bitcoinjs-lib#409]
We should replace the tip4commit icon with the bountysource icon... bountysource allows people to put bounties for specific features they would like to see, or bugs they want to see fixed. It also attracts new coders to come in and work on the code. Best of all, they pay in bitcoin! What do you guys think?

**Comment by dcousens** [comment]
@smithb1994 an interesting idea,  however it is a fair bit of set up just to get it started.
Has this model had success elsewhere by comparison?

**Comment by smithb1994** [comment]
@dcousens I saw it here https://github.com/sequelize/sequelize and it had a few bounties... Also, if you check the homepage, you can see that some fairly big players use it and set some fairly big bounties... In this way, people can fund a specific feature they would like to see rather than paying for general commits.

**Comment by dcousens** [comment]
I'm definitely open to this idea,  but it'd be good to gauge interest from potential developers (if any) who might be watching this issue.  Please pipe in if you think this is worth your while.

**Comment by smithb1994** [comment]
Here's a better link to open bounties, and who's using it. https://www.bountysource.com/bounties/search

**Comment by dcousens** [comment]
Was an interesting idea,  but right now if people want to do this,  I'd be happy for them to just open up issues asking for specific features first.
The [last tip](https://tip4commit.com/github/bitcoinjs/bitcoinjs-lib/deposits) for `tip4commit` was on 13 Apr 01:45,  and it was the transfer of funds we'd collected publicly on the multi signature address to the tip4commit account.

**Comment by dcousens** [comment]
Going to close this issue for now,  feel free to continue commenting if you think its worth while putting something up on bounty source.
