### ISSUE TITLE
Generate keypair from salt?

### ISSUE THREAD

**Issue by ThePixelPony** [bitcoinjs/bitcoinjs-lib#422]
I'd like to say that I do love this library but have been having a little trouble lately.
> var bkey = bitcoin.ECKey.makeRandom();
The code above generates a random key-pair but I'd like to always generate the same key-pair from the same salt.

Is this possible? If so, how? Thank you!

**Comment by jprichardson** [comment]
You can pass in your own random generator function like this:

```js
var bkey = bitcoin.ECKey.makeRandom(true, function(numBytes) { return /* */ })
```
See full method signature here: https://github.com/bitcoinjs/bitcoinjs-lib/blob/1.5.x/src/eckey.js#L49

Feel free to reopen if you have anymore questions related to this.
