### ISSUE TITLE
Typechecking fails in uglified script

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/bitcoinjs-lib#427]
When I use uglify in a script, the "type forcing" fails when creating HDNode.

What goes into typeforce is "Point" and an actual point, but the Point constructor is minified as `r` and typeforcing fails, and the whole creation fails.

Is that normal/expected?

**Comment by runn1ng** [comment]
Nevermind, I found the note in the readme. Sorry!

**Comment by dcousens** [comment]
Thanks @runn1ng :),   we'll see if we can avoid some of these issues by removing the duck-typing via https://github.com/bitcoinjs/bitcoinjs-lib/issues/407 in `2.0.0`.
