### ISSUE TITLE
Not exactly clear how we're getting utxo

### ISSUE THREAD

**Issue by smithb1994** [bitcoinjs/bitcoinjs-lib#429]
How do we get the utxo for a transaction? The docs aren't exactly clear how to do this. Do we need third party tools to find the utxo for an address? What would the code look like to do a 2/3 multisig transaction. The example in the tests are used for test net coins.

Sorry for the stupid question, this should be pretty trivial.

**Comment by dcousens** [comment]
>  Do we need third party tools to find the utxo for an address?

Yes,  `bitcoinjs-lib` is just a library for helping you do *things* in bitcoin,  it is not software that connects to the bitcoin network in any way.
