### ISSUE TITLE
How to add two data(OP-Return) by tx.addOutput ?

### ISSUE THREAD

**Issue by kimisan** [bitcoinjs/bitcoinjs-lib#430]
After i got the HEX string, I use bitcoin-qt to sendrawtransation
But i got the "64: multi-op-return (code -26)" from console
Anyone have a idea?
Thanks

    var data1 = new Buffer("kimi1");
    console.log(data1);
    var dataScript1 = bitcoinjs.scripts.nullDataOutput(data1);

    var data2 = new Buffer("kimi2");
    console.log(data2);
    var dataScript2 = bitcoinjs.scripts.nullDataOutput(data2);

    var tx = new bitcoinjs.TransactionBuilder();
    tx.addInput(test1[0].txid, test1[0].vout);
    tx.addOutput(send_to, send_Satoshi);
    tx.addOutput(dataScript1, 1000);
    tx.addOutput(dataScript2, 1000);
    tx.sign(0, keyPair);
    tx.build().toHex();

**Comment by jprichardson** [comment]
AFAIK, it's because a transaction with more than one `OP_RETURN` is non-standard and will be rejected by most nodes.

**Comment by kimisan** [comment]
@jprichardson  Thanks, I understand now
