### ISSUE TITLE
Slow signing and verifying a bitcoin message

### ISSUE THREAD

**Issue by ghost** [bitcoinjs/bitcoinjs-lib#433]
For some reason there is a delay in the signing process, it should be pretty quick, but I've noticed a significant delay (1 second). In comparison to bitcore-message signing, bitcoinjs-lib is going significantly slower. Not sure what the issue is that causes the difference.

**Comment by dcousens** [comment]
@smithb1994 do you have a test case?

https://github.com/bitpay/bitcore will be slightly faster due to its use of https://github.com/indutny/bn.js. 
`bitcoinjs-lib` has not switched to this yet due to several bugs emerging in that library that would have lost users funds.
It is an eventual goal to migrate to `bn.js` however, see https://github.com/bitcoinjs/bitcoinjs-lib/issues/394 for more information and progress.

**Comment by smithb1994** [comment]
Here's a test case to illustrate what I'm talking about
`npm install bitcore bitcore-message https://github.com/bitcoinjs/bitcoinjs-lib`

```javascript
var bjs = require('bitcoinjs-lib');
var bitcore = require('bitcore');
var bitcoreMsg = require('bitcore-message');

var message = 'This is a test message to be signed';

//bitcoinjs-lib
console.time('Bitcoinjs'); //start time
var keyPair = bjs.ECPair.fromWIF('5KYZdUEo39z3FPrtuX2QbbwGnNP5zTd7yyr2SC1j299sBCnWjss');
var signature = bjs.message.sign(keyPair, message);
console.timeEnd('Bitcoinjs'); //end time

//bitcore
console.time('Bitcore'); //start time
var keyPair2 = bitcore.PrivateKey.fromWIF('5KYZdUEo39z3FPrtuX2QbbwGnNP5zTd7yyr2SC1j299sBCnWjss');
var signature2 = bitcoreMsg(message).sign(keyPair2);
console.timeEnd('Bitcore'); //end time
```
``` javascript
Bitcoinjs: 217ms
Bitcore: 44ms
```

**Comment by dcousens** [comment]
Thanks @smithb1994,  if you're interested in helping out with #394,  it would be of great help if you could start building up extra test cases that we can add to ensure stability.

**Comment by dcousens** [comment]
Related to https://github.com/cryptocoinjs/ecurve/issues/27

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/pull/623
