### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#435]
We can decide 1 of two things,  we can add a CHANGELOG to the repository.
Or we can put it in the changes in the milestone itself?

Thoughts?

**Comment by jprichardson** [comment]
I've always thought that a repo/project without a CHANGELOG is a repo/project that doesn't want users. Definitely in favor of this. Dropping this here for posterity: http://keepachangelog.com/. 

Anyway, let's start with just `CHANGELOG.md` file at minimum. Thoughts on a cohesive workflow? Thoughts on 2.0 release time frame?

**Comment by weilu** [comment]
@dcousens I thought we listed the interface changes in one of the issues. I can't seem to find it. Do you recall?

**Comment by dcousens** [comment]
>  I can't seem to find it.

Excellent point. Ha.

https://github.com/bitcoinjs/bitcoinjs-lib/pull/317#issuecomment-65926330

``` markdown
Backward incompatible changes:

__removed__
- `bitcoin.crypto.HmacSHA256 ` // use `require('crypto').createHmac` instead
- `bitcoin.crypto.HmacSHA512 ` // use `require('crypto').createHmac` instead
- `bitcoin.base58check` // use `require("bs58check")` instead
- `bitcoin.Wallet` // build your own
- `bitcoin.HDNode.fromBuffer` // use `bitcoin.HDNode.fromBase58 instead
- `bitcoin.HDNode.fromHex` // use `bitcoin.HDNode.fromBase58 instead
- `bitcoin.HDNode.toBuffer` // use `bitcoin.HDNode.toBase58 instead
- `bitcoin.HDNode.toHex` // use `bitcoin.HDNode.toBase58 instead
- `bitcoin.Transaction.prototype.sign` // use `bitcoin.TransactionBuilder.prototype.sign` instead
- `bitcoin.Transaction.prototype.signInput` // use `bitcoin.TransactionBuilder.prototype.sign` instead
- `bitcoin.Transaction.prototype.validateInput` // use `hashForSignature` and ecdsa `verify`

__updated__
- `bitcoin.Message` -> `bitcoin.message`
- `bitcoin.HDNode.toBase58(isPrivate)` -> `bitcoin.HDNode.prototype.neutered().toBase58()` for exporting a extended public key and `bitcoin.HDNode.prototype.toBase58()` for exporting an extended private key
- `bitcoin.scripts.dataOutput ` -> `bitcoin.nullDataOutput`
- `Transaction.prototype.hashForSignature(prevOutScript, inIndex, hashType)` -> `Transaction.prototype.hashForSignature(inIndex, prevOutScript, hashType)` 

- `Transaction.prototype.addInput(hash, ...)`: `hash` could be a string, Transaction or Buffer -> `hash` can now **only** be a `Buffer`. 

- `Transaction.prototype.addOutput(scriptPubKey, ...)`: `scriptPubKey ` could be a string, `Address` or `Buffer` -> `scriptPubKey` can now **only** be a `Buffer`. 

- `TransactionBuilder` API unchanged.
```

**Comment by dcousens** [comment]
> - `bitcoin.scripts.dataOutput ` -> `bitcoin.scripts.nullDataOutput`

I'm not sure this is a rationale change,  what was the reasoning for it?

**Comment by weilu** [comment]
To be consistent I suppose? https://github.com/bitcoinjs/bitcoinjs-lib/commit/62e86e0dc116b32482775b2b91f374f31edd96dd

**Comment by dcousens** [comment]
@weilu seems that it was also a [synonym adopted by the community](https://bitcoin.org/en/glossary/null-data-transaction).
