### ISSUE TITLE
Rename Address

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#439]
Currently [Address](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/address.js) is imported as `Address` around the project,  this is in light of it previously being instantiable.

As this is no longer an instantiable object,  we should adhere to convention and name it as its lowercase companion.

However, `address` is a very common variable name,  and it would be a bit odd to set that as the convention,  so maybe we should make peoples lives easier and rename it here? 

Any ideas?

**Comment by dcousens** [comment]
ping @jprichardson,  ideas?

**Comment by jprichardson** [comment]
> However, address is a very common variable name, and it would be a bit odd to set that as the convention, so maybe we should make peoples lives easier and rename it here.

I think `address` (lowercase) is fine. Someone could always use `addr` as a variable instead of `address` to prevent conflicts.

**Comment by dcousens** [comment]
@jprichardson I think also its important to remember most people will use the `bitcoin` namespace anyway.
So,  it could be: `var myAddress = bitcoin.address.fromBase58Check(string)`.
