### ISSUE TITLE
Now using protected branches

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#452]
Master is now protected.

See https://github.com/blog/2051-protected-branches-and-required-status-checks for more information.

TL;DR, all tests must pass before we can merge,  force pushing is also disabled [for master].

**Comment by weilu** [comment]
:+1:

**Comment by dcousens** [comment]
Enabled travis-ci as a status update that must pass,  for some reason that isn't the default.

**Comment by dcousens** [comment]
Stopped TRAVIS from testing merges since the current branch protection policy stops non-fast forward merges anyway.

**Comment by dcousens** [comment]
Merged https://github.com/bitcoinjs/bitcoinjs-lib/pull/499 and https://github.com/bitcoinjs/bitcoinjs-lib/pull/502 without status checks.
Now re-enabled.
