### ISSUE TITLE
Constants

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#464]
How should constants be exposed?

Currently, in `Transaction`:

``` javascript
Transaction.DEFAULT_SEQUENCE = 0xffffffff
Transaction.SIGHASH_ALL = 0x01
Transaction.SIGHASH_NONE = 0x02
Transaction.SIGHASH_SINGLE = 0x03
Transaction.SIGHASH_ANYONECANPAY = 0x80
```

`HDNode`:

```javascript
HDNode.MASTER_SECRET = new Buffer('Bitcoin seed')
HDNode.HIGHEST_BIT = 0x80000000
```

IMHO,  this implies they are global parameters which can be changed.  It isn't clear these are properties that should not be changed.
@jprichardson / @weilu any ideas on how we can make it clearer for `3.0.0`?

**Comment by dcousens** [comment]
There is also the fact that changing these constants currently can have an adverse effect on the underlying properties and variants enforced by these classes.
This shouldn't be possible IMHO.

**Comment by jprichardson** [comment]
Any thoughts on moving to ES2015 syntax for 3.0? We could then safely use `const`... and `export` these directly.

**Comment by dcousens** [comment]
@jprichardson as long as we lock down the language dependencies so a SHA can be verified... I'm OK with it.

**Comment by dcousens** [comment]
Agreed with @jprichardson.  Until we move to ES next, this is the best approach.
