### ISSUE TITLE
Add io.js travis target?

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#465]
Anyone use io.js and bitcoinjs-lib?

**Comment by jprichardson** [comment]
I use io.js. But now with Node v4 (first merge of io.js/node), I think it makes sense to set focus there as I think we'll quickly see io.js usage drop now.

**Comment by dcousens** [comment]
@jprichardson what is the travis target for that?

**Comment by fanatid** [comment]
@dcousens for iojs target is `iojs` ([more info in docs](http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Choosing-Node-versions-to-test-against)), for node v4 as usual for node -- `4.0`

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/pull/473
