### ISSUE TITLE
[question] Signing Txs with Keypair from WIF

### ISSUE THREAD

**Issue by barisser** [bitcoinjs/bitcoinjs-lib#475]
Uncaught TypeError: Expected BigInteger, got r

I'm getting this error repeatedly.

var tx = new bitcoin.TransactionBuilder()
var keyPair = bitcoin.ECPair.fromWIF(private_key)
tx.sign(0, keyPair)

Also strangely works locally, fails on Heroku.

I suspect something is wrong with dependencies.
Probably this line in ecpair.js
line 73:  var d = BigInteger.fromBuffer(decoded.d)

I appreciate any help!

**Comment by dcousens** [comment]
Hey @barisser!

Can you elaborate on this part:
``` Uncaught TypeError: Expected BigInteger, got r```

That seems a bit odd, as the expected error in that case would usually be `Uncaught TypeError: Expected BigInteger, got [TYPE] r`.

This definitely could be a dependency problem, but,  there remains the fact the error is occurring at all. 

> Also strangely works locally, fails on Heroku.

What version of node?

> line 73: var d = BigInteger.fromBuffer(decoded.d)

Unlikely, that would give other errors very quickly (see `ECPair.constructor`).

**Comment by dcousens** [comment]
@barisser shall I close this?

**Comment by weilu** [comment]
@barisser try disable heroku npm cache (`heroku config:set NODEMODULESCACHE=false`), and redeploy. See if that solves your problem. 

https://coderwall.com/p/jjcpra/clean-heroku-npm-cache

**Comment by dcousens** [comment]
Going to close,  please re-open @barisser if you're still having the issue.
