### ISSUE TITLE
got error on makeRandom() function

### ISSUE THREAD

**Issue by itsasad** [bitcoinjs/bitcoinjs-lib#486]
I try to execute the file using nodejs but got error on makeRandom.
i try every thing but still its giving me error.
please help me.
below is the detail error
F:\wamp\www\coloredcoins\verify_bjs.js:4
key = bitcoin.ECKey.makeRandom();

TypeError: Cannot call method 'makeRandom' of undefined
    at Object.<anonymous> (F:\wamp\www\coloredcoins\verify_bjs.js:4:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by fanatid** [comment]
Are you trying run example from [coloredcoins.org](http://coloredcoins.org/documentation/#BitcoinJS) ?
Obviously, their docs are obsolete.
Instead `bitcoin.ECKey` your should use `bitcoin.ECPair` now.

**Comment by dcousens** [comment]
> sudo npm install bitcoinjs-lib

Eek.

Anyway, that documentation seems to be written for version `1.5.0`,  @itsasad so make sure you `npm install bitcoinjs-lib@^1.5.0 --save`.

Master of this repository is currently at `2.1.1`.

**Comment by itsasad** [comment]
yes i am trying to run coloredcoains.org.
@dcousens and @fanatid  thanks for helping . its working when i down grade bitconjs to 1.5.0
thanks :)
