### ISSUE TITLE
[question] Is ECKey deprecated from current release?

### ISSUE THREAD

**Issue by SillyKnight** [bitcoinjs/bitcoinjs-lib#487]
Hello,

I am using node module and following "from creating a transaction" example on bitcoinjs.org. 

```javascript
var keyPair = bitcoin.ECKey.fromWIF("L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF2BRUVwy"); 
```
Then got below error.
```javascript
Cannot read property fromWIF of undefined. 
```
After reading document, it seems to me that ECPair serves same functionality as ECKey. Does that mean we should use ECPair instead of ECKey from now on?

Thanks!

**Comment by dcousens** [comment]
Hi @SillyKnight!

Thanks for letting us know,  fixed in https://github.com/bitcoinjs/bitcoinjs.github.com/commit/cd431cb24fc53db89c5a5daf965b049274445f89.

You are right in every respect,  `ECKey/ECPubKey` has been removed in favour of `ECPair`.
