### ISSUE TITLE
Two release tags for 2.1.1

### ISSUE THREAD

**Issue by Sjors** [bitcoinjs/bitcoinjs-lib#488]
There is 2.1.1 and v2.1.1: https://github.com/bitcoinjs/bitcoinjs-lib/releases

Are they the same? Can you delete one of them? 

```sh
git tag -d 2.1.1
git push origin :refs/tags/2.1.1
```

**Comment by dcousens** [comment]
Good question.

**Comment by dcousens** [comment]
Thanks for spotting this @Sjors.
Resolved by removing `2.1.1`.

`v2.1.1` is now reflective of the published version,  excluding this change to the README: https://github.com/bitcoinjs/bitcoinjs-lib/commit/8b882842dd5f43b07ef2eab2ad767cfb285ca5ab
