### ISSUE TITLE
README.md BIP38 and BIP39 descriptions swapped

### ISSUE THREAD

**Issue by Codes4Fun** [bitcoinjs/bitcoinjs-lib#491]
It looks like the descriptions and names for BIP38 and BIP39 were accidentally swapped in the README.md with commit eb21f6f90a4bc52e1248a6e41325744628280a82.

**Comment by dcousens** [comment]
@Codes4Fun thanks for the heads up!
Feel free to make a PR next time. :+1: 

I'll get around to it later today.
