### ISSUE TITLE
Documentation feedback, exception messaging

### ISSUE THREAD

**Issue by rromanchuk** [bitcoinjs/bitcoinjs-lib#500]
Just want to give some feedback that may help new users in the future. 

I lost a lot of time debugging an issue that is probably extremely obvious to some, but it was not directly obvious to me.

```javascript
var bitcoin = require("bitcoinjs-lib");
var keyPair = bitcoin.ECPair.fromWIF("mywif", bitcoin.networks.testnet);
var txb = new bitcoin.TransactionBuilder();
txb.addOutput("myaddress", satoshis);  // <---- this will fail with "has no matching Script"
```

Because of the error message I came to the conclusion that I was doing something fundamentally wrong creating the transaction. In the end, it turns out I just needed `var txb = new bitcoin.TransactionBuilder(bitcoin.networks.testnet);`

Feel free to close this, just wanted to share my experience

**Comment by dcousens** [comment]
This is a good point.  

In light of documentation still being a WIP,  would an added integration test/example aid in this? (and have helped you?)

**Comment by weilu** [comment]
Alternatively we could have the examples all specify networks explicitly where possible.

**Comment by dcousens** [comment]
@weilu I like that idea

**Comment by dcousens** [comment]
@weilu maybe we should add `has no matching Script (check your expected network)` if `process.env == 'development'`?

**Comment by mohsenbinary** [comment]
Hello, please private key wallets  1JyyNoY9TQRkL9JTjG6DXYCbjDZtwtBitcoin Sneak PeekZLM9
To submit to the transfer of funds

**Comment by dadaista** [comment]
Who opened this issue saved me a lot of time. I think TransactionBuilder() should always take the argument and not work w/ any default, but I understand this will break so much code.

**Comment by dcousens** [comment]
@dadaista indeed.
It was mostly because network information was originally omitted from `TransactionBuilder`,  and added post-hoc,  hence we didn't want to break the API.

I'm still not sure what the best approach is here,  since it is only needed for `TransactionBuilder.prototype.addOutput`.

**Comment by freakotter** [comment]
Does it work with regtest?

**Comment by dcousens** [comment]
@freakotter does what?  We haven't got `regtest` constants defined,  but its a very tiny PR away from that default support.
Or you could pass in those constants yourself with ease.

**Comment by freakotter** [comment]
@dcousens can you explain how can I pass these constants please? Or point me to some documentation?

**Comment by freakotter** [comment]
@dcousens Oh my mistake. I though that regtest had different version prefixes than testnet that should be registered, like explained in the readme of the bitcoinjs-testnets npm package. The Bitcoin wiki doesn't clarify that (sorry, noob here). The solution by @rromanchuk  worked, thanks.

**Comment by dcousens** [comment]
@freakotter sorry I missed your recent question,  but certainly adding a new network is very simple,  and you could optionally easily pass one through.
