### ISSUE TITLE
newbie

### ISSUE THREAD

**Issue by brw31415** [bitcoinjs/bitcoinjs-lib#501]
meteor seems to require and exact version number to import node libraries. do you have one? tx

**Comment by dcousens** [comment]
Sorted this out @brw31415 ?

**Comment by brw31415** [comment]
meteor is expecting something like this this in a config file for node imports
{
  "redis": "0.8.2",
  "github": "0.1.8"
}

**Comment by brw31415** [comment]
i'm trying to pull into meteor.

{
  "redis": "0.8.2",
  "github": "0.1.8"
}

not sure about version number

**Comment by dcousens** [comment]
@brw31415 I'm not entirely sure what you need.  However, `bitcoinjs-lib`'s latest version is `2.1.3` if that helps.
