### ISSUE TITLE
Error: No, this would invalidate signatures

### ISSUE THREAD

**Issue by adityapatadia** [bitcoinjs/bitcoinjs-lib#503]
I am getting following error

Error: No, this would invalidate signatures
    at TransactionBuilder.addOutput (node_modules/bitcoinjs-lib/src/transaction_builder.js:236:21)

Can't trace its root. Can someone help me here?

**Comment by fanatid** [comment]
Are you trying add output to signed tx (fully or partially)?

**Comment by adityapatadia** [comment]
I dont think so. I add only before sign. Is it possible that this will happen before sign?

Moreover, I will properly debug my code today and let you know.

**Comment by dcousens** [comment]
@adityapatadia this only occurs when a signature already exists, and the SIGHASH type is incompatible.
In most cases, `SIGHASH_ALL` is used (the default), and once that is applied, the inputs/outputs of the transactions cannot change without invalidating signatures.  Hence the error.

**Comment by fanatid** [comment]
@dcousens BTW, why condition is
```js
return (input.hashType & 0x1f) === Transaction.SIGHASH_SINGLE
```
As I understand should be:
```js
return (input.hashType & 0x1f) === Transaction.SIGHASH_SINGLE ||
       (input.hashType & 0x1f) === Transaction.SIGHASH_NONE
```

**Comment by dcousens** [comment]
Indeed.

**Comment by dcousens** [comment]
@fanatid could you make a new issue?
Late here, but, I'll fix it tomorrow.  Test case appreciated if you have one :+1:.

**Comment by dcousens** [comment]
Resolved in #504

**Comment by adityapatadia** [comment]
Thanks for the fast fix but I also confirm that it happened for me because of my code. tx object was not properly initialised which caused this error.

**Comment by dcousens** [comment]
No worries @adityapatadia, thanks for reporting the issue any way :+1:
