### ISSUE TITLE
Money transfer

### ISSUE THREAD

**Issue by mohsenbinary** [bitcoinjs/bitcoinjs-lib#510]
hi
I have money in your wallet, but the software in Chrome and I reset my
wallet software Please remove the amount from the wallet
1JyyNoY9TQRkL9JTjG6DXYCbjDZtwtBitcoin Sneak PeekZLM9  Remove the wallet
1P2kAZdYGvfHfPGp4k8P6qDV2nGSq7Bitcoin Sneak PeekMDPB  Otherwise transfer advise how I
took your image

**Comment by dcousens** [comment]
@mohsenbinary what are you on about?
