### ISSUE TITLE
Generalizable serialization format

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#513]
Related to https://github.com/bitcoinjs/bitcoinjs-lib/pull/428,  would make patching in alternate crypto currencies much simpler.
Could potentially allow for stricter and more deterministic type checking.

I don't want to over-generalize though, and if this was to be done, it'd definitely be implemented/tested through an external module, not in `bitcoinjs-lib`.

**edit**:  Should also support encoding of `valueBuffer` natively
* Would also rename internal variables more consistently (aka #622)

**Comment by jprichardson** [comment]
I'm definitely in favor of this and more than happy to take the lead on this. This is something that I definitely need.

**Comment by dcousens** [comment]
@jprichardson taking your time on this one? :laughing: 
Going to un-assign for now

**Comment by dcousens** [comment]
Wants https://github.com/varstruct/varstruct/pull/32

**Comment by dcousens** [comment]
Bump to `5.0.0`?
I don't see anything easy to do here.

**Comment by dcousens** [comment]
Moved to `5.0.0`

**Comment by junderw** [comment]
Moving to 6.0.0 ...

**Comment by brandoncurtis** [comment]
The workflow of using bitcoinjs-lib for multiple coins with network parameters provided by something like https://github.com/cryptocoinjs/coininfo is quite a nice one.  This improvement would enable that workflow for coins such as Decred, Zcash (https://github.com/bitcoinjs/bitcoinjs-lib/issues/865), and many more.

**Comment by jprichardson** [comment]
yes, I'd love this. Exodus would be willing to fund the work here for this effort.

**Comment by junderw** [comment]
tbh, I'm sort of at a loss on how to move forward on this.

Would be nice if we could get a laundry list going.

**Comment by maxchernin** [comment]
Hi everyone, whats the status on this one?

**Comment by junderw** [comment]
I'm closing this.
