### ISSUE TITLE
Feature req.: support for Multichain

### ISSUE THREAD

**Issue by giacecco** [bitcoinjs/bitcoinjs-lib#523]
Multichain http://www.multichain.com is an open source fork of Bitcoin Core that support creating custom blockchains. As a fork of Core, integration may be very easy to add to the other networks that you already support, perhaps you will just need to add a way to connect to the specific multichain instance. Thanks!

**Comment by dcousens** [comment]
I'm not sure what you're asking for?

**Comment by giacecco** [comment]
I'll try again, sorry if it wasn't clear.

bitcoinjs-lib supports already bitcoin, testnet, litecoin and dogecoin ([that's what I see here](https://github.com/bitcoinjs/bitcoinjs-lib/blob/85a399d46b6e1e4db83bac4f7105d51e6e789c46/src/networks.js). Would you support Multichain, too, please? The specifications are at http://www.multichain.com .

Multichain is a fork of the Bitcoin Core protocol, the effort required to add it to the supported network should be limited. The advantage of Multichain is that it is intended to support creating any number of custom blockchains, not for the objective to use them as virtual currency but more for the additional functionality, e.g. proof of existence or the transfer of ownership of digital assets.

**Comment by dcousens** [comment]
@giacecco we are actually trying to reduce those constants down to a subset of just bitcoin and testnet.
We don't actually support any other networks except for the changes in constants.

**Comment by giacecco** [comment]
Understood, it's a pity. People like me aren't actually interested in Bitcoin but rather in the blockchain as a technology in general. Bitcoin's blockchain was great to introduce the concepts but is also doomed by a very unsustainable implementation. I will suggest the Multichain project to fork your work, it's sad there can't be convergence of effort.

**Comment by dcousens** [comment]
@giacecco no worries!
Feel free to fork.

This wasn't a political decision,  it simply a matter of purity.  This code base is for bitcoin,  and while I'll it's nice that other networks can easily operate with the library, and that we allow for that,  there is no point extending entire data structures just to allow for it.
