### ISSUE TITLE
Fix integration tests from periodical failure

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#527]
It seems to periodically fail due on BlockTrail's end, @rubensayshi ?

**Comment by dcousens** [comment]
@rubensayshi this is still an issue.

See https://travis-ci.org/bitcoinjs/bitcoinjs-lib/jobs/109219660.

**Comment by fanatid** [comment]
@dcousens as I understand it issue with faucet?
We can use [bitcoin-faucet-api](https://github.com/fanatid/bitcoin-faucet-api), only need install somewhere.

**Comment by dcousens** [comment]
This isn't an issue with faucet anymore.  Its a matter of the BlockTrail common-blockchain API failing occasionally.

**Comment by dcousens** [comment]
Seems to have stopped happening for now.
If it happens again I'll be changing it over to a different API that I know is solid
