### ISSUE TITLE
Add TransactionBuilder.prototype.setVersion

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#528]

**Comment by dcousens** [comment]
Added in https://github.com/bitcoinjs/bitcoinjs-lib/commit/6faeae397ffcca0a6d163003cc871fb75222b143

**Comment by takahser** [comment]
Where can I see, which versions are supported?
I crawled issues and code in this repo for `setVersion` but I didn't find any explanation on this, and in the tests its always set to `1`.

**Comment by Janaka-Steph** [comment]
@takahser The setVersion method specify the transaction version number, not to be confused with the protocol version.

From the bitcoin doc https://bitcoin.org/en/developer-guide#transactions
`Each transaction is prefixed by a four-byte transaction version number which tells Bitcoin peers and miners which set of rules to use to validate it. This lets developers create new rules for future transactions without invalidating previous transactions.`

And here https://bitcoin.org/en/developer-reference#raw-transaction-format
`Transaction version number; currently version 1 or 2. Programs creating transactions using newer consensus rules may use higher version numbers. Version 2 means that BIP 68 applies.`

But I agree I would also like to see more documentation on bitcoinjs.
