### ISSUE TITLE
Uncaught TypeError: tx.sign is not a function

### ISSUE THREAD

**Issue by off-bank** [bitcoinjs/bitcoinjs-lib#543]
I'm trying to sign a raw transaction in browser as below, but it throws me "Uncaught TypeError: tx.sign is not a function". Am I doing something wrong?

`var key = bitcoin.ECPair.fromWIF('correct_private_key');
console.log(key.getAddress());  //1Fy5MmbdHMSVozmek5Wsn4EqA7NyuDry5q
var tx = bitcoin.Transaction.fromHex('010000000171575c7585d347a2d31a09973bd118ea45083592f873cc53eea42f70f816dc4b000000001976a914a42cb159f6f8be525632491980eb9315cccef20e88acffffffff02e8030000000000001976a914e8db9f4559cbaa586dab4e6d1eedd482bdc3fc9d88acd07e0100000000001976a914a42cb159f6f8be525632491980eb9315cccef20e88ac00000000');
tx.sign(0, key);
console.log(tx.build().toHex());`

**Comment by fanatid** [comment]
Because `Transaction` doesn't have `.sign` method, you should use `TransactionBuilder`:
```js
var tx = bitcoin.Transaction.fromHex(...)
var txb = bitcoin.TransactionBuilder.fromTransaction(tx)
txb.sign(0, key)
console.log(tx.build().toHex())
```
(not checked)

**Comment by dcousens** [comment]
@off-bank indeed, `Transaction.prototype.sign` is undefined.
You want `TransactionBuilder`.

`Transaction` in this case is a raw data type with no specialized logic.

**Comment by off-bank** [comment]
I tried as @fanatid recommended (thanks!), but I get "Uncaught Error: nonstandard not supported" instead.

**Comment by dcousens** [comment]
@off-bank `TransactionBuilder.prototype.sign` only supports `multisig`, `pubkey` and `pubkeyhash` script signing.
Anything else is too custom to be able to do generically.

See https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L306 for more details.

**Comment by fanatid** [comment]
@dcousens  I think error throwing from `.sign` because `.fromTransaction` not add `prevOutScript` to inputs.

**Comment by dcousens** [comment]
Hmmm,  you're right.  This isn't a complicated transaction at all...

**Comment by dcousens** [comment]
The input script has an output script for its `scriptSig`... that is why this is breaking.
I think @off-bank has made a mistake with this `txHex` at some point and as a result is having trouble :)

**Comment by dcousens** [comment]
Try:

``` javascript
010000000171575c7585d347a2d31a09973bd118ea45083592f873cc53eea42f70f816dc4b0000000000ffffffff02e8030000000000001976a914e8db9f4559cbaa586dab4e6d1eedd482bdc3fc9d88acd07e0100000000001976a914a42cb159f6f8be525632491980eb9315cccef20e88ac00000000
```

Instead

**Comment by off-bank** [comment]
I am able to sign it using coinprism api and broadcasted the way it is, no changes to hex

https://blockchain.info/tx/7615f57f6ffb6407389fd3d596ced1b79b91504587d2f9b76374f5995e0115ae

**Comment by dcousens** [comment]
> I am able to sign it using coinprism api

Then they are just ignoring your input script.
We don't allow for silent errors,  and are quite strict about types in `bitcoinjs-lib`.
:)

**Comment by off-bank** [comment]
Oh, I see. That's probably because they created it :)
Maybe a openassets transaction is different than a regular btc transaction. 
Thanks, guys. I will check if can adapt something somewhere.

**Comment by fanatid** [comment]
@dcousens I don't see the way how two users can sign one transaction, I mean how I can serialize/deserialize instance of TransactionBuilder? Except `.buildIncomplete`, because this drop prevOutScript for inputs.

In bitcore-lib you can use toObject/fromObject, also you can extract and apply signatures (getSignatures/applySignatures) -- that is really helpful functions. Do you have plans to add something like this to bitcoinjs-lib?

**Comment by dcousens** [comment]
@fanatid sounds like we should make an integration test.
