### ISSUE TITLE
[question] Transaction and malleability

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/bitcoinjs-lib#545]
How does Transaction class deal with malleability?

If I am will import two "variants" of the same transaction, via for example `Transaction.fromHex`, will they return the same `hash`/`id`, or different?

I, unfortunately, have no way to test it right now

**Comment by fanatid** [comment]
They will return different ids.

**Comment by dcousens** [comment]
@runn1ng the transaction hash is as per the current standard.
It does not use any of the "normalization" techniques.
