### ISSUE TITLE
[question] Take Blockchain key and generate HDNode that generates new addresses

### ISSUE THREAD

**Issue by prideofconcept** [bitcoinjs/bitcoinjs-lib#548]
**How can I either:**
A take a passphrase suitable for a brain wallet
B take a blockchain.info wallet private key

to X: 
generate a HDNode and create new addresses for said wallets.
then Z:
grab private key suitable for import back into blockchain.info??

**here is what I have tried:**
A
`var hash = Bitcoin.crypto.sha256(private_hash);`
`var master_keyPair = new Bitcoin.ECPair( bigi.fromBuffer(hash) );`
`HDMaster = new Bitcoin.HDNode(master_keyPair, chainCode);`

B
`master_keyPair = Bitcoin.ECPair.fromWIF(blockchainwallet_WIF);`
`HDMaster = new Bitcoin.HDNode(master_keyPair, new Buffer(blockchain_sharedkey) );`

--

X

`var child_keypair = HDMasterNode.derive(index).neutered();`
`var uniq_address = child_keypair.getAddress();`

Z
`console.log('WIF of masterKey',master_keyPair.toWIF());`

stated problem - I can either get the first address correct. But all derived addresses don't make it into the same wallet. Or I cannot seem to import my generated HDNode (Method A) private key into Blockchain.info

**Comment by fanatid** [comment]
If I understand you right, this should work:
```js
var bip39 = require('bip39')
var bitcoinjs = require('bitcoinjs-lib')

var seed = bip39.mnemonicToSeed(...)
var hdnode = bitcoinjs.HDNode.fromSeedBuffer(seed).derive('m/0/0/1')
console.log('Address: ' + hdnode.getAddress())
console.log('Private key (WIF): ' + hdnode.keyPair.toWIF())
```

**Comment by dcousens** [comment]
@fanatid `derivePath` isn't merged yet.

That would be `.deriveHardened(0).derive(0).derive(1)`

**Comment by prideofconcept** [comment]
@fanatid @dcousens Thank you for the help.

Hopefully I am understanding things correctly. But how would I then derive new bitcoin addresses from my hdnode (so that money sent to the derive bitcoin address still shows up in the same wallet?)

**Comment by dcousens** [comment]
`.derive(addressNumber).getAddress()`

**Comment by dcousens** [comment]
@prideofconcept see the [implementation](https://github.com/bitcoinjs/bip32-wallet/blob/master/index.js) of https://github.com/bitcoinjs/bip32-wallet/

**Comment by prideofconcept** [comment]
@dcousens  Thank you. Just wanted to insure step X was correct!
