### ISSUE TITLE
Getting latest release (not master) for browser?

### ISSUE THREAD

**Issue by SuperHenkie** [bitcoinjs/bitcoinjs-lib#553]
Apologies if this is a stupid question (or more related to npm/nodejs/browserify rather than bitcoinjs) but as someone completely unfamiliar with npm or nodejs or browserify, the instructions in readme.md to get a standalone bitcoinjs (i.e. "browser version") weren't quite clear to me.

However the instructions on the [BitcoinJS website](http://bitcoinjs.org/) worked fine:
```
$ npm -g install bitcoinjs-lib browserify uglify-js
$ browserify -r bitcoinjs-lib -s bitcoin | uglifyjs > bitcoinjs.min.js
```
But if I'm not mistaken this gets me the **master** build. In order to get a bitcoinjs version that I can safely use in production, I'd need a **release** build (preferably the latest).

Looking at the [releases](https://github.com/bitcoinjs/bitcoinjs-lib/releases) the latest seems to be tagged "v2.1.4" so I tried this:
```
$ npm -g install bitcoinjs-lib@v2.1.4 browserify uglify-js
$ browserify -r bitcoinjs-lib -s bitcoin | uglifyjs > bitcoinjs.min.js
```
But this results in the exact same .js file. **How do I get the latest stable release?**

**Comment by fanatid** [comment]
You can see all bitcoinjs-lib releases on npm with command: `npm info bitcoinjs-lib versions`

```
$ cd any_temp_directory
$ npm info bitcoinjs-lib versions
...
  '2.1.4',
  '2.2.0' ]
$ npm i browserify uglify-js bitcoinjs-lib@2.1.4
...
$ ./node_modules/.bin/browserify -r bitcoinjs-lib -s bitcoin |./node_modules/.bin/uglifyjs |md5sum
01f16ba7d171c897b9e63b73080994a5  -
$ npm i bitcoinjs-lib@2.2.0
...
$ ./node_modules/.bin/browserify -r bitcoinjs-lib -s bitcoin |./node_modules/.bin/uglifyjs |md5sum
b41092244c131202ed2949cb207c8b4f  -
$ npm i bitcoinjs-lib@latest
...
$ ./node_modules/.bin/browserify -r bitcoinjs-lib -s bitcoin |./node_modules/.bin/uglifyjs |md5sum
b41092244c131202ed2949cb207c8b4f  -
```

**Comment by SuperHenkie** [comment]
Ah, thanks, apparently I had to use "2.1.4" instead of "v2.1.4" - I guess with the "v" it's a tag (string), and without it's a version number.

Got it working now!
