### ISSUE TITLE
Is there any util that convert byte to base64?

### ISSUE THREAD

**Issue by kob-e** [bitcoinjs/bitcoinjs-lib#558]
the redeem script coming in byte array and i want it in base64, i used another tool for it but i prefer to stay with bitcoinjs file only.

**Comment by fanatid** [comment]
`bitcoinjs-lib` doesn't provide base64

**Comment by kob-e** [comment]
Thank you, i didnt find it in the docs.

**Comment by jpochyla** [comment]
Just for the record, you can convert `Buffer` objects to base64 by calling `buffer.toString('base64')`

**Comment by dcousens** [comment]
`Buffer.prototype.toString` with `'base64'` as the argument.

Example:

``` javascript
var x = new Buffer('001122ff', 'hex')

console.log(x.toString('base64'))
```
