### ISSUE TITLE
bip44 indexes for coins

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/bitcoinjs-lib#561]
Hello,

do you somewhere have BIP44 indexes for coin networks ( https://github.com/satoshilabs/slips/blob/master/slip-0044.md ) ?

I could add it to networks.js, but then, you might not want to put BIP44 stuff there...

**Comment by runn1ng** [comment]
Nevermind, it's here
https://github.com/bitcoinjs/bip44-constants

**Comment by fanatid** [comment]
@runn1ng probably it also would be available in [cryptocoinjs/coininfo](https://github.com/cryptocoinjs/coininfo/) soon: https://github.com/cryptocoinjs/coininfo/pull/19

**Comment by runn1ng** [comment]
Great! Just a question - do you plan to move to coininfo in bitcoinjs-lib in the near (or far) future?

**Comment by fanatid** [comment]
ping @dcousens

**Comment by jprichardson** [comment]
> Great! Just a question - do you plan to move to coininfo in bitcoinjs-lib in the near (or far) future?

I don't see the benefit in doing this.

**Comment by dcousens** [comment]
@runn1ng we don't want to become a database for all the varying cryptocoin constants.
It becomes difficult and cumbersome to maintain, especially when they all have subtle differences in the general meaning of the those constants.

I'd rather `bitcoinjs-lib` set the standard for the network object's type-structure,  and a module like `coininfo` be the "end all".

**Comment by runn1ng** [comment]
That's really  a good idea... But then it would make sense to me that bitcoinjs would use coininfo :)
