### ISSUE TITLE
Handling large transaction amounts with Altcoins

### ISSUE THREAD

**Issue by joaopaulofonseca** [bitcoinjs/bitcoinjs-lib#562]
The verifications done by `verifuint` on `bufferutils.js` when parsing transaction amounts, make it impossible to work with transaction amounts larger than UINT53. When dealing with an Altcoin, there's the need to handle larger amounts, while mantaining the precision, which is impossible at the moment with this UINT53 limit (e.g. for a value such as 12345678.12341234).

Maybe a way to solve this is to use BigInteger to handle transaction amounts.

**Comment by dcousens** [comment]
@jpdffonseca hmph. 
I'd rather not over-complicate the interface... maybe `addOutputBN` which allows for a `BigInteger` output `value`?

**Comment by dcousens** [comment]
It would break a lot of code that interfaces with it though... and would need to be serialized immediately on `addOutput` to avoid issues later.

**Comment by fanatid** [comment]
@jpdffonseca if you need bitcoinjs-lib only for parsing transactions you should check transaction message from [bitcoin-protocol](https://github.com/mappum/bitcoin-protocol) (tx message from bitcoin-protocol don't parse value as `Number` and you can handle this buffer with big integer library, such as [bn.js](https://github.com/indutny/bn.js) for example)

**Comment by jprichardson** [comment]
@dcousens potential for inclusion in 3.0?

**Comment by dcousens** [comment]
@jpdffonseca you can technically use `.valueBuffer` currently rather than `.value` in `tx.outs` to use values greater than 53-bits,  however you would need to encode them yourself.

**Comment by dcousens** [comment]
@jprichardson we basically could do this with the `varstruct` pull,  but I suspect we'd be switching entirely to:

> would need to be serialized immediately on addOutput to avoid issues later.

Which is a breaking change of its own.

**Comment by dcousens** [comment]
Actually... no,  we could just accept a `valueBuffer` input in `Transaction`... we should be doing that anyway.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/issues/628

**Comment by dcousens** [comment]
I'm not sure if this is the right thing to do.
The only reason we need to support `valueBuffer` internally at the moment is because of `hashForSignature`.... I feel like if we mangle all the interfaces to just for the sake of alt-coins, its going a bit further than necessary.

I understand the need to want to use the full range of 64-bit values,  and hence `Buffer`...  but I feel like that is entirely a breaking change that is ultimately no more useful than  https://github.com/bitcoinjs/bitcoinjs-lib/issues/622,  and could potentially break a lot of user code and implementations silently until they realise `.value` or `.vout` is undefined.

**Comment by afk11** [comment]
Maybe something similar to CChainParams that defines the maximum value (and type thereof, or vice versa) so other networks can be supported?

**Comment by dcousens** [comment]
@afk11 sounds similar to our `network` object,  and I'm not against that, but would it help the `valueBuffer` situ?

**Comment by dcousens** [comment]
Related https://github.com/bitcoinjs/bitcoinjs-lib/issues/513

**Comment by dcousens** [comment]
Closing in v
