### ISSUE TITLE
How to get previous transactions on a btc address?

### ISSUE THREAD

**Issue by charredgrass** [bitcoinjs/bitcoinjs-lib#568]
I'm sorry, this is probably a really stupid question.

How do I get the transactions previously done by an address?

**Comment by dcousens** [comment]
`bitcoinjs-lib` is not a full implementation of bitcoin (nor does it ever intend to be) and does not interact with the bitcoin network in any way [directly].

To achieve your goal,  you will [most likely] need to use a library that talks over HTTP such as `cb-http-client` in combination with a compliant block explorer such as blocktrail.com. 
Then, read up on https://github.com/common-blockchain/common-blockchain to find out the relevant API's you need to do what you want.

Example
``` javascript
var Blockchain = require('cb-http-client')
var mainnet = new Blockchain('https://api.blocktrail.com/cb/v0.2.1/BTC', {
  api_key = '...'
})

mainnet.addresses.transaction('1GV2J4CNLXiAHDhEKTGgATbReTDy9nDixq', 0, function (err, res) {
  console.log(res)
})
```
