### ISSUE TITLE
question: How can i get the public key compressed (66 characters) from ECPair

### ISSUE THREAD

**Issue by kob-e** [bitcoinjs/bitcoinjs-lib#570]
for ex:
```
//this giving me array, i need 66 cahracter compressed
var k = new authme.bitcoin.ECPair.makeRandom()
k.Q.getEncoded()
//output: [3, 228, 212, 232, 89, 33, 65, 78, 136, 167, ......]
```

**Comment by fanatid** [comment]
66-bytes length compressed key? about what you are talking?

**Comment by fanatid** [comment]
compressed key is 33 bytes -- `bitcoin.ECPair.makeRandom().Q.getEncoded().length`
uncompressed is 65 bytes -- `bitcoin.ECPair.makeRandom().Q.getEncoded(false).length`

**Comment by kob-e** [comment]
Example of what i need:
![publioc key example](https://cloud.githubusercontent.com/assets/6986221/14528912/a35ac34a-025a-11e6-9111-4a536775dd55.png)

**Comment by fanatid** [comment]
`.getEncoded()` return [buffer](https://nodejs.org/api/buffer.html)
you can convert to `hex` with `.toString('hex')`
`bitcoin.ECPair.makeRandom().Q.getEncoded().toString('hex')`

**Comment by kob-e** [comment]
Thank you very much!
