### ISSUE TITLE
did we stop backporting things to 1.5.x ?

### ISSUE THREAD

**Issue by rubensayshi** [bitcoinjs/bitcoinjs-lib#577]
the 1.5.x branch is gone, did we completely stop backporting things to 1.5.x ?

**Comment by dcousens** [comment]
@rubensayshi https://github.com/bitcoinjs/bitcoinjs-lib/pull/376

We ended up back-porting all the compatible changes.
Did you have something in mind for a backport?

**Comment by rubensayshi** [comment]
@dcousens yea; https://github.com/blocktrail/bitcoinjs-lib/commit/5d2e9ac024d0c28ea5f86c569d1e217b37ae8808

**Comment by dcousens** [comment]
@rubensayshi if you want to set up the branch,  feel free to PR the back port of that feature :+1:

**Comment by dcousens** [comment]
@rubensayshi ,  as above,  happy to re-open a branch if you want to.  :+1:
