### ISSUE TITLE
Extract merkle calculations to 3rd party package

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#581]
As per https://github.com/bitcoinjs/bitcoinjs-lib/pull/580,  we should extract the merkle calculations to a 3rd party **generic** package which is agnostic of transactions,  and simply operates on hashes.

This way it can be used for more than just bitcoin transactions.
The only pre-requisites is that it should be using `Buffer`s,  with extensive testing and it should probably be as concise as our own implementation.
Performance should also be on par or better.

I personally would like to use merkle trees in this way,  so if I [or others] can't find something suitable, I'm up for implementing it under `bitcoinjs` org.

Thoughts @jprichardson @fanatid ?

**Comment by jprichardson** [comment]
Yep, I like this idea.

**Comment by dcousens** [comment]
ping @olalonde,  maybe we could use your package at https://github.com/blockai/merkletree,  it meets the above requirements quite well.

My only concern is that it is written in ES6,  which might still discriminate at several of our users.

**Comment by olalonde** [comment]
@dcousens would be happy to collaborate. As a user of this library, you wouldn't really need to worry about it being written in ES6 as I compile it with babel before publishing to npm. I didn't really worry about performance when writing it but I'm sure it wouldn't be too hard to optimise.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/pull/653
