### ISSUE TITLE
How to generate a seed, retrieve its 12-word phrase, and generate private keys & addresses from it?

### ISSUE THREAD

**Issue by ffxsam** [bitcoinjs/bitcoinjs-lib#583]
I haven't had much luck digging around for an answer to this. What I'm trying to accomplish:

1. Generate a random seed
2. Get a 12-word phrase from said seed
3. Generate X private keys (and public addresses) from the seed

A nod in the right direction would be appreciated!

**Comment by jprichardson** [comment]
1 & 2:

```js
var bip39 = require('bip39') // npm i -S bip39
var crypto = require('crypto')

// what you describe as 'seed'
var  randomBytes = crypto.randomBytes(16) // 128 bits is enough

// your 12 word phrase
var mnemonic = bip39.entropyToMnemonic(randomBytes.toString('hex')) 

// what is accurately described as the wallet seed
var seed = bip39.mnemonicToSeed() // you'll use this in #3 below
```

3:

```js
var bitcoin = require('bitcoinjs-lib') // npm i -S bitcoinjs-lib

var bitcoinNetwork = bitcoin.networks.bitcoin
var hdMaster = bitcoin.HDNodeFromSeedBuffer(seed, bitcoinNetwork) // seed from above

var key1 = hdMaster.derivePath('m/0')
var key2 = hdMaster.derivePath('m/1')

console.log(key1.keyPair.toWIF())
console.log(key2.keyPair.toWIF())
```

.... should do it. May be a typo or incorrect parameter here or there. I strongly encourage you to read the BIP32 spec and learn about the paths and what hardened keys are.

**Comment by ffxsam** [comment]
This line:

    var hdMaster = bitcoin.HDNodeFromSeedBuffer(seed, bitcoinNetwork) // seed from above

should be:

    var hdMaster = bitcoin.HDNode.fromSeedBuffer(seed, bitcoinNetwork) // seed from above

And `hdMaster.derivePath` throws an error.. I can't seem to figure that one out. It says it's not a function. I don't see `derivePath` anywhere else.

**Comment by jprichardson** [comment]
> I don't see derivePath anywhere else.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/7203b7a94dc5820458785262de4b1dfc6474ba22/src/hdnode.js#L296

Maybe @dcousens can chime in?

**Comment by ffxsam** [comment]
And thank you! I would've never been able to figure all that out, as there isn't much in the way of documentation. Not to mention I also don't fully understand how this works under the hood.

**Comment by jprichardson** [comment]
> as there isn't much in the way of documentation.

Yeah, we've been meaning to address that. It's really tough with our limited resources and how the fast the entire Bitcoin and JavaScript ecosystems move. I know it's not a good answer... but the best we have at this moment is to ask questions and to look at the tests. Overall, we realize that it's a shitty solution.

**Comment by ffxsam** [comment]
Yeah, but it's open source, and I understand most devs are busy with jobs & other obligations. Nothing pressing going on here! At some point I'd like to build a wallet app in React Native. I'm not really that impressed with the current selection of wallets (for iOS) at the moment.

**Comment by dcousens** [comment]
@ffxsam @jprichardson `derivePath` was added recently,  and hasn't yet been released.
It is part of the `2.3.0` milestone. 

@ffxsam in the mean time,  you can use `.derive(0)` and `.derive(1)`.

We'll add some more integration tests to show these examples...

**Comment by plastygrove** [comment]
Sorry for commenting here - my question is related to the derivepath and I figured better put it in one place rather than opening a new issue.

Is there a way to derive change addresses as per the BIP32 path using the current release version (2.2.0)? Looking at hdnode.js, I can't find any way to generate a change address. Is this up to the wallet software then to separate change addresses from external addresses?

I think it has something to do with chainCode but I can't really fathom how to use it. Any suggestions will be greatly appreciated!

**Comment by dcousens** [comment]
Closed in favour of https://github.com/bitcoinjs/bitcoinjs-lib/issues/627

**Comment by saeveritt** [comment]
Note that in the examples above
`bitcoin.HDNode.fromSeedBuffer`  
is now,  
`bitcoin.bip32.fromSeed`

**Comment by kadimi** [comment]
This solves `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toWIF' of undefined`:

```
console.log(key1.toWIF())
console.log(key2.toWIF())
```

**Comment by fletbel** [comment]
console.log(key1.keyPair.toWIF())
should be 
console.log(key1.toWIF())

**Comment by random9brat** [comment]
Bump, hehe...sry but im so curious,

Can someone write an example how would today with bitcoinjs-lib@3.3.2 and bip39 one create menmonic seed, and from that seeds private key and address???

Would much appreciate that.

**Comment by junderw** [comment]
Generating a mnemonic would just be: `bip39.generateMnemonic()` for 12 words, `bip39.generateMnemonic(256)` for 24 words

Then generating wallets is just like the tests.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/59b21162a2c4645c64271ca004c7a3755a3d72fb/test/integration/bip32.spec.ts#L106-L123

**Comment by random9brat** [comment]
I made this code and im not getting public addreses with bc1... (P2PKH) but P2PKH (starting with 1)... I did send some test funds and tried to import words into Trust Wallet but he is not recognizing anything. This is my code:

`var bip39 = require('bip39');
var crypto = require('crypto');
var bitcoin = require('bitcoinjs-lib');
const coinjs = require('coinjs-lib');

var  randomBytes = crypto.randomBytes(16)
var mnemonic = bip39.entropyToMnemonic(randomBytes.toString('hex')) 

const seed = coinjs.bip39.mnemonicToSeed(mnemonic);
const rootNode = coinjs.HDNode.fromSeedBuffer(seed);

// get bip44 constants https://github.com/satoshilabs/slips/blob/master/slip-0044.md
const btcchild = rootNode.derivePath(`m/84'/0'/0'/0/0`); //trust wallet derivation path

// get addresses
const btcaddress = btcchild.getAddress();

// get private key
const btcprivkey = btcchild.getPrivateKey();

**Comment by junderw** [comment]
You are using `coinjs-lib` which is not us. Please ask them.

It looks like they forked a very old version of us.

`getAddress` used to exist on bip32 objects. This existed back when P2PKH was the only type of address at all.

Most likely this is the reason why it only creates p2pkh.

If you'd like to use bitcoinjs-lib, examples are in the tests.

**Comment by random9brat** [comment]
Oh ok, sry.

**Comment by random9brat** [comment]
For some reason its hitting me with this message:

const root = bip32.fromSeed(seed)
                   ^

TypeError: bip32.fromSeed is not a function

**Comment by random9brat** [comment]
also I had a problems with newer version of bip32, so try to go for npm install bip32@2.0.6, it cleared the errors for me
