### ISSUE TITLE
Derive Addresses from xpub key

### ISSUE THREAD

**Issue by stefanhuber** [bitcoinjs/bitcoinjs-lib#584]
Dear all, sry to ask this question here... However, I am not able to figure out how to use the API and derive addresses from a **xpub key only**. 

The same functionality is available in bitcore-lib e.g. (https://github.com/bitpay/bitcore-lib/blob/master/test/hdpublickey.js#L189)

Can anybody give me an example, how this works with? In a way like: `var address1 = hdnode.derive(1234)`. _The question is how to configure `hdnode` with the respective xpub key._

**Comment by dcousens** [comment]
`HDNode.fromBase58(xpub).derive(0)`

**Comment by stefanhuber** [comment]
Works great! Thank you!

**Comment by dcousens** [comment]
Excellent!   Let us know if we could improve the examples at all :+1:

**Comment by NeuralChris** [comment]
I would love to see how to generate a SegWit address using the xpub key as well.  Also, am I correct in thinking that by only using the xpub key, even if someone gained access to my server, they'd never be able to steal the bitcoin because all they have is the public key, correct?
