### ISSUE TITLE
is it possible to implement coin control?

### ISSUE THREAD

**Issue by frndxyz** [bitcoinjs/bitcoinjs-lib#600]

**Comment by dcousens** [comment]
Can you elaborate on coin control?

**Comment by frndxyz** [comment]
@dcousens  http://bitcoin.stackexchange.com/questions/37486/what-does-bitcoin-cores-coin-control-features-do-and-how-do-i-use-it

**Comment by dcousens** [comment]
This is a wallet feature,  I'm not sure what you're after in regards to this library.

**Comment by dcousens** [comment]
@frndxyz this might be what you're after: https://github.com/dcousens/coinselect
