### ISSUE TITLE
Help, cant obtain bitcoinjs.min.js

### ISSUE THREAD

**Issue by cellcoin** [bitcoinjs/bitcoinjs-lib#601]
when I follow the instructions on bitcoinjs.org to get bitcoinjs.min.js (for a browser), all I get is an empty file. Can you give me a copy of bitcoinjs.min.js?
- npm, node, browserify, etc. is all installed.

**Comment by dcousens** [comment]
Hi @cellcoin,  please see https://github.com/bitcoinjs/bitcoinjs-lib/issues/593

**Comment by cellcoin** [comment]
thank you!
