### ISSUE TITLE
Newb question, but after running the sample script I get Uncaught ReferenceError: bitcoin is not defined

### ISSUE THREAD

**Issue by chris41188** [bitcoinjs/bitcoinjs-lib#606]
```
<!DOCTYPE html>
<html>
<body>

<h1>My First Web Page</h1>

<p id="demo">A Paragraph.</p>

<button type="button" onclick="myFunction()">Try it</button>

<script src='https://cdnjs.cloudflare.com/ajax/libs/bitcoinjs-lib/0.2.0-1/bitcoinjs-min.js'></script>

<script>
function myFunction() {
    
    var keyPair = bitcoin.ECPair.makeRandom()
    
    // Print your private key (in WIF format)
    console.log(keyPair.toWIF())
    // => Kxr9tQED9H44gCmp6HAdmemAzU3n84H3dGkuWTKvE23JgHMW8gct
    
    // Print your public key address
    console.log(keyPair.getAddress())
    // => 14bZ7YWde4KdRb5YN7GYkToz3EHVCvRxkF
    
  //  key = Bitcoin.ECKey.makeRandom();
    //document.getElementById("demo").innerHTML = key.toWIF();
}
</script>

</body>
</html>
```

**Comment by dcousens** [comment]
I'm not sure where `https://cdnjs.cloudflare.com/ajax/libs/bitcoinjs-lib/0.2.0-1/bitcoinjs-min.js` comes from,  but it certainly isn't supported by the maintainers of this library.
It also appears to be before version `1.0.0`,  `0.2.0` even,  so,  the code you are attempting to use is completely wrong.

**Comment by dcousens** [comment]
@chris41188 I suggest you read [this](https://github.com/bitcoinjs/bitcoinjs-lib#browser) in its entirety,  and try again.

**Comment by chris41188** [comment]
Thanks,

yes I tried this but an error was thrown here
$ browserify foo.js -s foobar > bar.js

is there a place I can get a pre browserfied version?

**Comment by dcousens** [comment]
What was the error?

**Comment by chris41188** [comment]
I created the foobar.js, added the code and ran this

as-MacBook-Pro:~ a$ sudo nano foobar.js 
as-MacBook-Pro:~ a$ sudo browserify foo.js -s foobar > bar.js
Error: Cannot find module '/Users/a/foo.js' from '/Users/a'

**Comment by dcousens** [comment]
Don't use `sudo`,  there is no need.

Also,  it appears the README has a mistake which I just fixed in https://github.com/bitcoinjs/bitcoinjs-lib/pull/608

**Comment by dcousens** [comment]
Perhaps more semantic names will be more helpful than `foo` and `bar`.
I was trying to keep it abstract.

**Comment by chris41188** [comment]
Thanks for your help I will give it another try

**Comment by chris41188** [comment]
Everything is working well now, thank you

**Comment by dcousens** [comment]
Awesome,  thanks for making the issue!
