### ISSUE TITLE
TypeError: slice.copy is not a function

### ISSUE THREAD

**Issue by Head** [bitcoinjs/bitcoinjs-lib#612]
Im getting "TypeError: slice.copy is not a function" in https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/block.js#L91

**Comment by fanatid** [comment]
Can you demonstrate error throwing with code example?

**Comment by Head** [comment]
My fault. I've inserted a string not a Buffer(). Maybe a check and proper error...?

**Comment by dcousens** [comment]
We could type check it,  but the above error was usually "safe" enough.
