### ISSUE TITLE
Changing network for multisigOutput and ScriptHashOutput

### ISSUE THREAD

**Issue by starsoccer** [bitcoinjs/bitcoinjs-lib#618]
Unlike bitcoin.ECPair.makeRandom, bitcoin.script.multisigOutput and bitcoin.script.scriptHashOutput do not seem to support setting a different network. Is there a way to set a default network or any way to change the network typed used in both functions?

**Comment by starsoccer** [comment]
I have figured it out. For those having issues, you simply need to add the network type to fromoutputscript.

**Comment by dcousens** [comment]
> add the network type to fromoutputscript.

This is `address.fromOutputScript` I assume?
That is because an address and WIF data are the only data structures that capture network information in any way.

Scripts,  private keys and transactions all don't care about the implied network.
However,  as you have noticed, `ECPair` requires a network for the simple fact of the `toWIF` and `getAddress` functions.

**Comment by starsoccer** [comment]
Yes, I later realized that the network type needed to simply be passed in bitcoin.address.fromOutputScript

On an unrelated note, I am working on creating a raw transaction with no signature using the below code but keep getting an error, "Transaction is not complete". It seems to require that I sign the transaction atleast once before I can get the ID or hex value of it. Is there anyway around that?

    var bitcoin = require('bitcoinjs-lib');

    var tx = new bitcoin.TransactionBuilder()
    tx.addInput("TRANSACTIONIDHERE", 0);
    tx.addOutput('ADDRESSHERE', 0.01 * 100000000)

    //tx.sign(0, keyPairs[0])

    var tx2 = tx.build()
    console.log(tx2.getId()) // transaction id
    console.log(tx2.toHex()) // push tx to network

**Comment by dcousens** [comment]
`tx.buildIncomplete()`?

**Comment by starsoccer** [comment]
Thanks, thats what I was looking for.

**Comment by starsoccer** [comment]
Sorry to post again here,  but I couldnt find any example or reference code on how to check or verify a signature on a raw transaction, similar to a bitcoin message verification.

Basically I just want to plug in a raw transaction spending from a multisig as string(hex), and confirm if address/public key X has signed it or not.

**Comment by dcousens** [comment]
@starsoccer the typical approach for that would be to `Transaction.fromHex` the transaction hex, that way you have a deserialized transaction object to work with.
Then I'd iterate over the `ins` (inputs) checking for multisigs.

``` js
var tx = bitcoin.Transaction.fromHex(txHex)

// loop through every input, ensure it is either not multisig, or if it is, that it is signed by us
tx.ins.every(function (input) {
  // P2SH?
  if (!bitcoin.script.isScriptHashInput(input.script)) return true

  var chunks = bitcoin.script.decompile(input.script)
  var scriptSigChunks = chunks.slice(0, -1)
  var redeemScriptChunks = bitcoin.script.decompile(chunks[chunks.length - 1])

  if (!bitcoin.script.isMultisigInput(scriptSigChunks, true)) return true
  if (!bitcoin.script.isMultisigOutput(redeemScriptChunks)) return true

  // ...  
})
```

Now,  at this point (`// ...`)  you can either match `redeemScriptChunks` against a known redeem script such that you can immediately know what public keys it should have,  and thereby also check the ordering of the signatures matches. 

You can find these algorithms in https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js,  but I agree, this isn't the most straightforward thing to do and maybe we should help improve that...
Perhaps at least adding some template code to simplify public key and signature extraction would be worthwhile,  as it would leave the complexity up to just the script/pubkey matching.

**Comment by dcousens** [comment]
Ping @fanatid,  thoughts on `bitcoin.script.extract*`?

**Comment by dcousens** [comment]
Alternatively @starsoccer,  just import the transaction into `TransactionBuilder` and attempt to sign any of the multisig inputs.  If it works,  awesome!
But that isn't very reassuring...

**Comment by starsoccer** [comment]
I am not really sure what you mean when you said match redeemscriptchunks. The only mention I can find of redeemscriptchunks was using processScript.

Would there be a way to compare an original raw transaction to this new signed transaction and be able to figure out from there what public key has signed it? I can live with not knowing who should be signing it as I would have the redeemscript stored.

To go a bit more into detail into exactly what I am trying to do, basically I will provide the user a raw transaction to sign which will be stored. Once signed I need to verify that its the correct rawtransactiom(user did not maliciously change it), and then verify the user used the correct public key to sign it. Once signed I would then broadcast it.  The transaction creation code I have already via your help, and the broadcast code I have as well. So I just need to verify the rawtransaction hasnt changed, and then verify the user signed it correctly.

Preferably bitcoin.script.extract would return the input/outputs and then return a list of public keys that have signed it.

**Comment by starsoccer** [comment]
@dcousens ssorry to reopen this case, but it looks like #681 might do exactly what I mentioned and it seems to be merged. Could you just clarify for me how I would go about using it as I am having a bit of trouble figuring it out.

For the sake of this example, lets just assume I am going to be importing the transaction as a string.

**Comment by dcousens** [comment]
Closing,  but re-open @starsoccer if you still need help.

> Once signed I need to verify that its the correct rawtransactiom(user did not maliciously change it)

 The easiest way to do that would just be to match the transactions ID is a match without any `scriptSigs`.

**Comment by starsoccer** [comment]
Yes I think this can be closed. I ended up using a mix of 2 different functions to basically get the address that funds are being sent to along with the amount, and then another function to get the redeemscript from the rawtx and confirm it is the same redeemscript.

**Comment by afk11** [comment]
You could the TXID of the transaction when its totally unsigned, before you give it to the client. When you receive a signed copy back, before checking it's signatures are valid, just copy the tx, strip out the signatures, and check that it matches. Nothing but input signatures change when signing.
