### ISSUE TITLE
HDNode with consistent and quick serialization

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/bitcoinjs-lib#619]
Hello,

is there a way to serialize/deserialize HDNode to a JavaScript object in a way, that's efficient?

We are now saving HDNodes in MyTrezor using toBase58 and HDNode.fromBase58; however, we found this to be quite slow, especially if the user has more such HDNodes (one per account).

I am now experimenting with function like this, but it feels too "hacky" and any internal implementation change might break something. However, the speed is immediately obvious. (We *do* know that the HDNode is neutered.)

````javascript
function serializeBitcoinJsHDPubNode(node) {
    return {
        depth: node.depth,
        index: node.index,
        parentFingerprint: node.parentFingerprint,
        chainCode: node.chainCode,
        Q: node.keyPair.Q.getEncoded(false),
    };
}

function deserializeBitcoinJsHDPubNode(node) {
    const depth = node.depth;
    const index = node.index;
    const parentFingerprint = node.parentFingerprint;
    const chainCode = new Buffer(node.chainCode);
    const Q = ecurve.Point.decodeFrom(bcurve, new Buffer(node.Q));
    const res = new HDNode(new ECPair(null, Q), chainCode);
    res.depth = depth;
    res.index = index;
    res.parentFingerprint = parentFingerprint;
    return res;
}
````

**Comment by runn1ng** [comment]
I might have said, the speed is probably more important for the *de*serialization...

**Comment by dcousens** [comment]
While the performance of these functions leaves so much to be desired,  and is easily resolved by https://github.com/bitcoinjs/bitcoinjs-lib/issues/610 (aka, moving to a faster ECDSA library),  there are other tricks you can do.

Lazy evaluation is by far the simplest path through this.
However,  it would be much simpler for you to just save the X/Y `bigi` coordinates of the `ECPoint` rather than re-calculating (`ecurve.Point.decodeFrom`) them each time.
This is the only real operation that takes any time.

**Comment by dcousens** [comment]
As simply,  you could just use the non-compressed versions of the public key.  That would be as performant as just a `new Buffer` operation IIRC.

**Comment by dcousens** [comment]
> I am now experimenting with function like this, but it feels too "hacky" and any internal implementation change might break something.

Understandable,  and I apologise we haven't moved on #610 sooner to make this not worth your time,  that said,  you can assume these are part of the public API and will adhere to SEMVER.

**Comment by runn1ng** [comment]
> I do 100's of these operations in the space of a second in a mobile browser, let alone the web browser and never feel this as a performance issue.

Interesting. I will make a test script page just for this and will share it here.

**Comment by dcousens** [comment]
@runn1ng I'm using https://github.com/bitcoinjs/bip32-wallet for my wallets, which lazily uses `this.account.getChildren(addresses, [external, internal])` to retrieve the BIP32 nodes when needed.

**Comment by runn1ng** [comment]
Here you go. Super simple and easy script that just do 100 of BIP32 deserializations

````javascript
  var HDNode = bitcoin.HDNode;
  var begin = Date.now();
  for (var i = 0; i < 100; i++) {
      var newNode = HDNode.fromBase58("xpub6BiVtCpG9fQPxnPmHXG8PhtzQdWC2Su4qWu6XW9tpWFYhxydCLJGrWBJZ5H6qTAHdPQ7pQhtpjiYZVZARo14qHiay2fvrX996oEP42u8wZy");
  }
  var end = Date.now();
  var timeSpent = (end - begin) + " ms";
  document.querySelector("#info").innerHTML = timeSpent;
````

it is here

https://github.com/runn1ng/bitcoinjs-serialization-performance

and deployed here using github pages

http://www.karelbilek.com/bitcoinjs-serialization-performance/

It takes 7 seconds on my Linux Chrome, 15 seconds on my Android Chrome, 4.7 seconds on my Linux Firefox (huh, it used to be slower than Chrome, now it seems to be actually quicker... I wonder what happened). I use the newest version of bitcoin.js (it is browserified in `bitcoin.js`).

**Comment by runn1ng** [comment]
Interestingly enough, if I deserialize it from **xprv**, it is basically instant!

https://github.com/runn1ng/bitcoinjs-serialization-performance/blob/gh-pages/index-xprv.html

http://www.karelbilek.com/bitcoinjs-serialization-performance/index-xprv.html

So it is issue *only* when deserializing neutered nodes.

**Comment by runn1ng** [comment]
Most time is spent on this line
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/hdnode.js#L114

````javascript
    // Verify that the X coordinate in the public point corresponds to a point on the curve.
    // If not, the extended public key is invalid.
    curve.validate(Q)
````

So, for me, the easiest "fix" would be to add option to skip validation here.

**Comment by runn1ng** [comment]
screenshot from profiler (sorry if it ends up too giant)

![screenshot from 2016-09-13 14-09-10](https://cloud.githubusercontent.com/assets/104945/18473133/b57c129e-79bb-11e6-8b99-981d1075cd3d.png)

**Comment by runn1ng** [comment]
I have added a PR and indeed, with the skipValidation set to true, the deserialization is instant

Version of the script with patch #620 and skipValidation to true : 

https://github.com/runn1ng/bitcoinjs-serialization-performance/blob/gh-pages/index-patched.html

http://www.karelbilek.com/bitcoinjs-serialization-performance/index-patched.html

**Comment by dcousens** [comment]
Good find.  Indeed that function has always been a pain in the ass.
My Chrome performed the test in `1559 ms`... in any case, still quite long.

**Comment by runn1ng** [comment]
Thanks. It is definitely better for my use case than saving it in the low level representation (since that might change in the future, for example with the new bignum library).

**Comment by dcousens** [comment]
@runn1ng my concern is this hack will go away with `3.0.0` because we'll be using `bn.js`.
Maybe it'd be better off doing that conversion now instead of this 1 edge case?

**Comment by runn1ng** [comment]
Is bn.js that much faster?

**Comment by dcousens** [comment]
@runn1ng we're talking about 10-15x IIRC.

**Comment by runn1ng** [comment]
Oh. In that case, my `skipVerification` hack might not be needed long-term. So yeah I understand your hesitation

I am however already using it short-term in my patched version in a new mytrezor version (not yet online, but soon).

**Comment by dcousens** [comment]
Related #623 and #620.
