### ISSUE TITLE
.vout instead of .index for Transaction Inputs

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#622]
After a long time,  I've closed https://github.com/bitcoinjs/bitcoinjs-lib/pull/440.
The only positive rename I can forsee that would have come for #440 would be `in.vout`.
That would also be consistent with the bitcoin RPC IIRC.

**Comment by afk11** [comment]
What about passing the txid instead of hash? The hash is the serialized encoding (flipped), but when you actually want to refer to a transaction I think it makes most sense to use the txid. It's also the convention bitcoind uses.

**Comment by afk11** [comment]
In other words, it's like carrying around it's serialization rather than the artifact.

**Comment by dcousens** [comment]
@afk11 interesting idea. 
It is arguably infinitely more useful than the pain in the ass reversal you have to constantly do... however,  it also means when building a transaction, you increase the total amount of memory used by double (encoding -> decoding -> encoding).

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/issues/513 - as that would be the only justification for a change
