### ISSUE TITLE
inherits_browser.js error on ES6 (Using on React Native 0.33)

### ISSUE THREAD

**Issue by TaiPA** [bitcoinjs/bitcoinjs-lib#625]
inherits_browser.js:6 Uncaught TypeError: Object prototype may only be an Object or null: undefinedinherits_browser.js:6 inherits_stream_readable.js:16 (anonymous function)_stream_readable.js:609 (anonymous function)_stream_readable.js:611 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)readable.js:3 (anonymous function)readable.js:11 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)index.js:6 (anonymous function)index.js:75 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)stream-browserify@1.0.0.js:1 (anonymous function)stream-browserify@1.0.0.js:2 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)index.js:2 (anonymous function)index.js:3 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)nodelibs-stream@0.1.0.js:1 (anonymous function)nodelibs-stream@0.1.0.js:2 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:530 lsystem.src.js:841 $__global.upgradeSystemLoader.e.instantiate.Promise.all.then.executees6-module-loader.src.js:1929 oes6-module-loader.src.js:1977 pes6-module-loader.src.js:1751 jes6-module-loader.src.js:1799 kes6-module-loader.src.js:1619 (anonymous function)es6-module-loader.src.js:1183 Oes6-module-loader.src.js:1142 Kes6-module-loader.src.js:930 7.y.whenes6-module-loader.src.js:821 7.v.runes6-module-loader.src.js:97 3.a._draines6-module-loader.src.js:62 3.a.draines6-module-loader.src.js:268 b
system.src.js:2230 Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/lib/_stream_readable.js
Uncaught TypeError: Object prototype may only be an Object or null: undefinedsystem.src.js:2230 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)readable.js:3 (anonymous function)readable.js:11 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)index.js:6 (anonymous function)index.js:75 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)stream-browserify@1.0.0.js:1 (anonymous function)stream-browserify@1.0.0.js:2 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)index.js:2 (anonymous function)index.js:3 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)nodelibs-stream@0.1.0.js:1 (anonymous function)nodelibs-stream@0.1.0.js:2 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:530 lsystem.src.js:841 $__global.upgradeSystemLoader.e.instantiate.Promise.all.then.executees6-module-loader.src.js:1929 oes6-module-loader.src.js:1977 pes6-module-loader.src.js:1751 jes6-module-loader.src.js:1799 kes6-module-loader.src.js:1619 (anonymous function)es6-module-loader.src.js:1183 Oes6-module-loader.src.js:1142 Kes6-module-loader.src.js:930 7.y.whenes6-module-loader.src.js:821 7.v.runes6-module-loader.src.js:97 3.a._draines6-module-loader.src.js:62 3.a.draines6-module-loader.src.js:268 b
system.src.js:2230 Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/readable.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/lib/_stream_readable.js
Uncaught TypeError: Object prototype may only be an Object or null: undefinedsystem.src.js:2230 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)index.js:6 (anonymous function)index.js:75 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)stream-browserify@1.0.0.js:1 (anonymous function)stream-browserify@1.0.0.js:2 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)index.js:2 (anonymous function)index.js:3 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)nodelibs-stream@0.1.0.js:1 (anonymous function)nodelibs-stream@0.1.0.js:2 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:530 lsystem.src.js:841 $__global.upgradeSystemLoader.e.instantiate.Promise.all.then.executees6-module-loader.src.js:1929 oes6-module-loader.src.js:1977 pes6-module-loader.src.js:1751 jes6-module-loader.src.js:1799 kes6-module-loader.src.js:1619 (anonymous function)es6-module-loader.src.js:1183 Oes6-module-loader.src.js:1142 Kes6-module-loader.src.js:930 7.y.whenes6-module-loader.src.js:821 7.v.runes6-module-loader.src.js:97 3.a._draines6-module-loader.src.js:62 3.a.draines6-module-loader.src.js:268 b
system.src.js:2230 Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/stream-browserify@1.0.0/index.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/readable.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/lib/_stream_readable.js
Uncaught TypeError: Object prototype may only be an Object or null: undefinedsystem.src.js:2230 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)stream-browserify@1.0.0.js:1 (anonymous function)stream-browserify@1.0.0.js:2 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)index.js:2 (anonymous function)index.js:3 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)nodelibs-stream@0.1.0.js:1 (anonymous function)nodelibs-stream@0.1.0.js:2 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:530 lsystem.src.js:841 $__global.upgradeSystemLoader.e.instantiate.Promise.all.then.executees6-module-loader.src.js:1929 oes6-module-loader.src.js:1977 pes6-module-loader.src.js:1751 jes6-module-loader.src.js:1799 kes6-module-loader.src.js:1619 (anonymous function)es6-module-loader.src.js:1183 Oes6-module-loader.src.js:1142 Kes6-module-loader.src.js:930 7.y.whenes6-module-loader.src.js:821 7.v.runes6-module-loader.src.js:97 3.a._draines6-module-loader.src.js:62 3.a.draines6-module-loader.src.js:268 b
system.src.js:2230 Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/stream-browserify@1.0.0.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/stream-browserify@1.0.0/index.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/readable.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/lib/_stream_readable.js
Uncaught TypeError: Object prototype may only be an Object or null: undefinedsystem.src.js:2230 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)index.js:2 (anonymous function)index.js:3 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)nodelibs-stream@0.1.0.js:1 (anonymous function)nodelibs-stream@0.1.0.js:2 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:530 lsystem.src.js:841 $__global.upgradeSystemLoader.e.instantiate.Promise.all.then.executees6-module-loader.src.js:1929 oes6-module-loader.src.js:1977 pes6-module-loader.src.js:1751 jes6-module-loader.src.js:1799 kes6-module-loader.src.js:1619 (anonymous function)es6-module-loader.src.js:1183 Oes6-module-loader.src.js:1142 Kes6-module-loader.src.js:930 7.y.whenes6-module-loader.src.js:821 7.v.runes6-module-loader.src.js:97 3.a._draines6-module-loader.src.js:62 3.a.draines6-module-loader.src.js:268 b
system.src.js:2230 Uncaught Error evaluating http://localhost:3000/jspm_packages/github/jspm/nodelibs-stream@0.1.0/index.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/stream-browserify@1.0.0.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/stream-browserify@1.0.0/index.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/readable.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/lib/_stream_readable.js
Uncaught TypeError: Object prototype may only be an Object or null: undefinedsystem.src.js:2230 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:636 csystem.src.js:671 (anonymous function)nodelibs-stream@0.1.0.js:1 (anonymous function)nodelibs-stream@0.1.0.js:2 (anonymous function)system.src.js:2256 doEvalsystem.src.js:2222 __evalsystem.src.js:335 asystem.src.js:1160 $__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.executesystem.src.js:667 fsystem.src.js:530 lsystem.src.js:841 $__global.upgradeSystemLoader.e.instantiate.Promise.all.then.executees6-module-loader.src.js:1929 oes6-module-loader.src.js:1977 pes6-module-loader.src.js:1751 jes6-module-loader.src.js:1799 kes6-module-loader.src.js:1619 (anonymous function)es6-module-loader.src.js:1183 Oes6-module-loader.src.js:1142 Kes6-module-loader.src.js:930 7.y.whenes6-module-loader.src.js:821 7.v.runes6-module-loader.src.js:97 3.a._draines6-module-loader.src.js:62 3.a.draines6-module-loader.src.js:268 b
es6-module-loader.src.js:140 Potentially unhandled rejection [2] Error loading "github:jspm/nodelibs-stream@0.1.0" at http://localhost:3000/jspm_packages/github/jspm/nodelibs-stream@0.1.0.js
Error loading "github:jspm/nodelibs-stream@0.1.0" from "lib/main" at http://localhost:3000/lib/main.js
Error evaluating http://localhost:3000/jspm_packages/github/jspm/nodelibs-stream@0.1.0.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/github/jspm/nodelibs-stream@0.1.0/index.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/stream-browserify@1.0.0.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/stream-browserify@1.0.0/index.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/readable.js
Uncaught Error evaluating http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/lib/_stream_readable.js
Uncaught TypeError: Object prototype may only be an Object or null: undefined (WARNING: non-Error used)es6-module-loader.src.js:140 (anonymous function)es6-module-loader.src.js:167 fes6-module-loader.src.js:189 i

**Comment by TaiPA** [comment]
![simulator screen shot sep 23 2016 12 15 43 am](https://cloud.githubusercontent.com/assets/19204597/18758676/31469b10-8123-11e6-8dda-5e34cce11f12.png)

**Comment by dcousens** [comment]
I'm not sure how this relates to bitcoinjs-lib.

**Comment by enomind** [comment]
Oh yes, sorry for this.
This is not related to bitcoinjs-lib, it's related to inherits_browser.js.
Anyone was success to integrated with react-native yet ?

**Comment by dcousens** [comment]
> Anyone was success to integrated with react-native yet ?

Why would there be issues?

**Comment by enomind** [comment]
Sorry, first time, i thought this is issue of BitcoinJS-Lib. So i posted it here.
I will try research to use bitcoinjs-lib on my react-native project...Thank you.
