### ISSUE TITLE
How to convert bitcoind private key to ECPair?

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/bitcoinjs-lib#643]
I have a private key from bitcoind, and I want to convert it to ECPair.

Is there some simple tool for this, either in this library or elsewhere on npm? I cannot find anything usable.

**Comment by runn1ng** [comment]
I am not 100% sure what exactly is coming from bitcoind (when using `dumpprivkey`), but it seems like base58. But I try to use `bs58` and `base58check` to decode, and it doesn't work really

**Comment by runn1ng** [comment]
oh nevermind, it's already WIF, I just put in wrong network. Closing.

**Comment by jprichardson** [comment]
`dumprivkey` provides your key in `WIF` format which happens to be base58 check encoded. 

See this as an example:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/4ae06003c4b38aa2335a152e12a003d8f4dee889/test/integration/basic.js#L44

**Comment by runn1ng** [comment]
Yes. I put in wrong network (main instead of testnet) and it confused me. :)

**Comment by dcousens** [comment]
`ECPair.fromWIF`

**Comment by blockskipsupport** [comment]
What is the command in node using bitcoin js to dumprivkey? I have the private key and need to generate the wif, to be use to generate ECPair.

**Comment by Generalsuki02** [comment]
> `ECPair.fromWIF`,  with the right network provided :smiley: 
> Bitcoin
