### ISSUE TITLE
ecurve.Point.decodeFrom failes with typeforce.quacksLike('Point') using uglifyjs

### ISSUE THREAD

**Issue by Head** [bitcoinjs/bitcoinjs-lib#659]
I get "Expected Point, got r" in https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/ecpair.js#L32 when using uglifyjs. I debugged this down to:
`var ECPoint = typeforce.quacksLike('Point')`

See bottom of the typeforce readme:
> WARNING: Be wary of using quacksLike types which inherently rely on the MyType.name property, if that property is mangled by say uglifyjs you will have a bad time.

And yes, I had a bad time debugging this :(

**Comment by jprichardson** [comment]
@Head does `keep_fnames` help at all? (ref: https://github.com/mishoo/UglifyJS2#compressor-options)

**Comment by dcousens** [comment]
And in the `bitcoinjs-lib` README:

> **NOTE:** When uglifying the javascript, you must exclude the following variable names from being mangled: Array, BigInteger, Boolean, Buffer, ECPair, Function, Number, Point and Script. This is because of the function-name-duck-typing used in typeforce. Example:

```
uglifyjs ... --mangle --reserved 'Array,BigInteger,Boolean,Buffer,ECPair,Function,Number,Point'
```

**Comment by dcousens** [comment]
Maybe the warning needs to be higher?

**Comment by dcousens** [comment]
> And yes, I had a bad time debugging this :(

:disappointed: ,  I wonder if we should detect this happening on behalf of users?  Its so specific though...

**Comment by Head** [comment]
Oh, RTFM. Now I feel stupid. But as a excuse, I started using it before this notice was in the readme :)

Finally it works, using
```
new webpack.optimize.UglifyJsPlugin({
  mangle: {
    except: ['Array','BigInteger','Boolean','Buffer','ECPair','Function','Number','Point']
  }
})
```

thank you!

**Comment by andreashuber69** [comment]
FWIW, for anyone wanting to use bitcoinjs-lib from vue.js 3 (currently in beta), here's how to surgically change the (hidden) webpack config according to what @Head has found above:

If it doesn't already exist, create `vue.config.js` in the project root (same folder as package.json):
```
module.exports = {
    chainWebpack: config => {
        if (config.plugins.store.has('uglify')) {
            config.plugin('uglify').tap(options => {
                options[0].uglifyOptions.mangle.reserved = [
                    'Array', 'BigInteger', 'Boolean', 'Buffer', 'ECPair', 'Function', 'Number', 'Point'
                ];

                return options;
            });
        }
    }
}
```
To verify the changes, you can dump the webpack config before and after adding `vue.config.js` with the usual:
`vue inspect --mode production >webpack.js`

HTH
