### ISSUE TITLE
Add test fixtures for Block/Transaction w/ signed int version

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#663]
Ref https://github.com/bitcoinjs/bitcoinjs-lib/pull/662

https://en.bitcoin.it/wiki/Protocol_documentation#Block_Headers
https://en.bitcoin.it/wiki/Protocol_documentation#tx

https://github.com/bitcoin/bitcoin/blob/master/src/primitives/transaction.h#L373
https://github.com/bitcoin/bitcoin/blob/master/src/primitives/block.h#L23

**Comment by afk11** [comment]
I added small tests for both of these in the PR. (The ones for transaction might demonstrate the effect more - version/locktime have the serialization, but are interpreted differently)

https://github.com/bitcoinjs/bitcoinjs-lib/pull/662/files#diff-bf93e9f5180db5c003ef49fd2fb9a5acR9
https://github.com/bitcoinjs/bitcoinjs-lib/pull/662/files#diff-47fd755279d6a2638f13d68e56a3304dR90

**Comment by dcousens** [comment]
@afk11 :+1: ,  in future lets see if we can't put them in the vectors file though.
