### ISSUE TITLE
How to decode P2SH input script addresses? ECPair.fromPublicKeyBuffer throws error

### ISSUE THREAD

**Issue by Head** [bitcoinjs/bitcoinjs-lib#669]
I try to decode an incoming script to get the address.

for the output I use:
`const pubKey = address.fromOutputScript(output.script, bitcoinjs.networks.testnet);`

This seems to work, but for the input:
`const chunksIn = bitcoinjs.script.decompile(input.script);`
`input.pubKey = bitcoinjs.ECPair.fromPublicKeyBuffer(chunksIn[1], bitcoinjs.networks.testnet).getAddress();`

failes with 
AssertionError: Invalid sequence length
    at Function.Point.decodeFrom
    at Function.ECPair.fromPublicKeyBuffer

when the input is a "pay-to-script-hash"

**Comment by dcousens** [comment]
Ultimately,  we'd have to see what `chunksIn[1]` is.  P2SH has nothing to do with a public key though...

**Comment by Head** [comment]
This is chunksIn[1] I want to get the address from:

> 00473044022049dc8948dc631a9aa8e9afc38211c680ae69ae94621d7518feb874d72ea9c95a022048b704f5ee0f356d6b93b5b5c3f3c98706c26ad89fc10cccb6591b39d719377101473044022074c113b2e63df04c199e09b1dbde7c1bf24fb029b1fb7d12901ddacf115ff1e102202c9c7286f2f31b4bb939ceb12247b6ef0e4d9c20cc4e2f197ef6eef63bd5bc22014c695221021061e2d01da3cf77c27de489c924818954480e556a5cbf1194a21a89ca8ddfca2102112518629d8c472b19210a41d348f1ecf5afbc19a1159bd6562f65fb3afe83682103376935a92d616911bd2ddc928e9ac6dd5777db28515d15f86fa2c7e6b04cbffb53ae

This is the whole transaction script:

> 01000000018f0f4015e05378c6f50a2e093dc2def97f1a88bc5d7a014b20d3d47c303a857c00000000fc00473044022049dc8948dc631a9aa8e9afc38211c680ae69ae94621d7518feb874d72ea9c95a022048b704f5ee0f356d6b93b5b5c3f3c98706c26ad89fc10cccb6591b39d719377101473044022074c113b2e63df04c199e09b1dbde7c1bf24fb029b1fb7d12901ddacf115ff1e102202c9c7286f2f31b4bb939ceb12247b6ef0e4d9c20cc4e2f197ef6eef63bd5bc22014c695221021061e2d01da3cf77c27de489c924818954480e556a5cbf1194a21a89ca8ddfca2102112518629d8c472b19210a41d348f1ecf5afbc19a1159bd6562f65fb3afe83682103376935a92d616911bd2ddc928e9ac6dd5777db28515d15f86fa2c7e6b04cbffb53aeffffffff02404b4c00000000001976a9144123701cbf149deb4e3beae34aaa56aa4ff386d888aca8e1fa020000000017a914318f2267c78c88c9e7bfa50e6755a03c377c30978700000000

https://live.blockcypher.com/btc-testnet/decodetx/ decodes latter it to:
```
"inputs": [
        {
            "addresses": [
                "2NFbQdbmL2LsTYjUXqLkEjmcnUPYgisP9Rk"
            ], 
            "output_index": 0, 
            "output_value": 55000000, 
            "prev_hash": "7c853a307cd4d3204b017a5dbc881a7ff9dec23d092e0af5c67853e015400f8f", 
            "script": "00473044022049dc8948dc631a9aa8e9afc38211c680ae69ae94621d7518feb874d72ea9c95a022048b704f5ee0f356d6b93b5b5c3f3c98706c26ad89fc10cccb6591b39d719377101473044022074c113b2e63df04c199e09b1dbde7c1bf24fb029b1fb7d12901ddacf115ff1e102202c9c7286f2f31b4bb939ceb12247b6ef0e4d9c20cc4e2f197ef6eef63bd5bc22014c695221021061e2d01da3cf77c27de489c924818954480e556a5cbf1194a21a89ca8ddfca2102112518629d8c472b19210a41d348f1ecf5afbc19a1159bd6562f65fb3afe83682103376935a92d616911bd2ddc928e9ac6dd5777db28515d15f86fa2c7e6b04cbffb53ae", 
            "script_type": "pay-to-script-hash", 
            "sequence": 4294967295
        }
    ], 
```

**The in script don't show the address on https://live.blockcypher.com/btc-testnet/decodetx/ eigher...?**

But it does when using another transaction like this one:

whole script:
> 010000000181ea87f4a1f837eff1ed712ce55b1445ef6468f869dbea80ab064275c64ee31f010000006b483045022100ad31c224959c2b10ab310207f8a60d653606eb4a7b81fb9aea1919136e23e66102202c8e020f3bdfacf0cd069b22c3dc3711291cdc19f837919dc9c6b8c10eeb766e0121034f17f60f4a15c0511eeed575b861075172460e7af4eb38bb350f6ddd4f809c67ffffffff02e09da301000000001976a9144123701cbf149deb4e3beae34aaa56aa4ff386d888ac29f234eb000000001976a91422b20c38477ec181d416d72ad3a1cb9a9b8654d588ac00000000

input[1]
> 483045022100ad31c224959c2b10ab310207f8a60d653606eb4a7b81fb9aea1919136e23e66102202c8e020f3bdfacf0cd069b22c3dc3711291cdc19f837919dc9c6b8c10eeb766e0121034f17f60f4a15c0511eeed575b861075172460e7af4eb38bb350f6ddd4f809c67

this works with
```
var bitcoinjs = require("bitcoinjs-lib")

var script = '483045022100ad31c224959c2b10ab310207f8a60d653606eb4a7b81fb9aea1919136e23e66102202c8e020f3bdfacf0cd069b22c3dc3711291cdc19f837919dc9c6b8c10eeb766e0121034f17f60f4a15c0511eeed575b861075172460e7af4eb38bb350f6ddd4f809c67';
var chunks = bitcoinjs.script.decompile(new Buffer(script, 'hex'));

bitcoinjs.ECPair.fromPublicKeyBuffer(chunks[1], bitcoinjs.networks.testnet).getAddress();
```

https://live.blockcypher.com/btc-testnet/decodetx/ decodes this to:
```
    "inputs": [
        {
            "addresses": [
                "mjyPDckq3FM6TAVb3iJeY1igQCPGE8PbR1"
            ], 
            "output_index": 1, 
            "output_value": 3973715625, 
            "prev_hash": "1fe34ec6754206ab80eadb69f86864ef45145be52c71edf1ef37f8a1f487ea81", 
            "script": "483045022100ad31c224959c2b10ab310207f8a60d653606eb4a7b81fb9aea1919136e23e66102202c8e020f3bdfacf0cd069b22c3dc3711291cdc19f837919dc9c6b8c10eeb766e0121034f17f60f4a15c0511eeed575b861075172460e7af4eb38bb350f6ddd4f809c67", 
            "script_type": "pay-to-pubkey-hash", 
            "sequence": 4294967295
        }
    ], 
```

**Comment by dcousens** [comment]
```
            "script_type": "pay-to-script-hash", 
```
is not the same as
```
            "script_type": "pay-to-pubkey-hash", 
```

What are you trying to do with this P2SH script?

**Comment by afk11** [comment]
From the OP it seems like he's parsing addresses from scriptSig's. 
> const chunksIn = bitcoinjs.script.decompile(input.script);
> 
input.pubKey = bitcoinjs.ECPair.fromPublicKeyBuffer(chunksIn[1], bitcoinjs.networks.testnet).getAddress();

But the transaction the code breaks on is P2SH/multisig, you definitely need code to handle P2SH, or just reject the script types you can't handle.

**Comment by Head** [comment]
Well, all I wanna do is "decoding a raw transaction". I need to get the input and output addresses. And output works, but input not.

**Comment by dcousens** [comment]
If the input is a pay-to-script-hash,  the address is the `hash160` of the last data chunk.
Nothing to do with public keys.

**Comment by Head** [comment]
Ah perfect! Thank you!

When I find time, I'll try to write a TransactionDecoder as a counterpart to the TransactionBuilder ;)
For inexperienced people It's a lot of stuff you have to put together to get the transaction data while building transactions was pretty easy for me.

For the future reference:

```
let pubKeyIn = '';
let chunksIn = bitcoinjs.script.decompile(tx.ins[0].script);
if (bitcoinjs.script.isScriptHashInput(chunksIn)) {
	let hash = bitcoinjs.crypto.hash160(chunksIn[chunksIn.length - 1])
	pubKeyIn = bitcoinjs.address.toBase58Check(hash, bitcoinjs.networks.bitcoin.scriptHash)
}else{
	pubKeyIn = bitcoinjs.ECPair.fromPublicKeyBuffer(chunksIn[1], bitcoinjs.networks.testnet).getAddress();
}

if (pubKeyIn) {
	debug("pubKeyIn", pubKeyIn);
}
```

**Comment by dcousens** [comment]
The issue is,  assuming addresses from input scripts is unsafe, and is not guaranteed.
You are just pattern matching,  which is best guess.

**Comment by Head** [comment]
That's fine for my purpose. I just need to check if that transaction was sent from an own address to remove it from the wallets UTXO array.

**Comment by dcousens** [comment]
Why not just match the public key against your own?
