### ISSUE TITLE
get address balance

### ISSUE THREAD

**Issue by edenn** [bitcoinjs/bitcoinjs-lib#678]
Is there a way to get address balance ?

**Comment by jprichardson** [comment]
Sure, you need to use an API. I'd suggest using either of the following:

- https://www.blockcypher.com/dev/bitcoin/
- https://blockchain.info/api
- https://github.com/bitpay/insight-api

**Comment by dcousens** [comment]
Alternatively,  you can get all the transactions for an address and derive the UTXOs yourself.

**Comment by suusofttruongnv** [comment]
Hi 
I want use Bitcoinjs-lib for get balance, create transaction and get list history transaction . Please show me how to use bitcoinjs to do it !

Thanks for support !!!
