### ISSUE TITLE
TransactionBuilder: cache hashPrevouts, hashSequence and hashOutputs

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#685]
TODO

**Comment by dcousens** [comment]
I wonder how this could be done by `TransactionBuilder`... it isn't something we want to put in `Transaction` on its own,  nor do we want it to be opaque to the user if it isn't part of `TransactionBuilder`.

**Comment by junderw** [comment]
txb._hashPrevouts etc. could be stored and cleared whenever an input is added.

Then do the same for everything else.

You’re right that Transaction doesn’t need that info.

**Comment by dcousens** [comment]
I'm going to close this,   most aren't using bitcoinjs in an environment where this will make a real difference,  and if they are,  they probably will want to use native anyway!
