### ISSUE TITLE
SegWit: add Transaction.prototype.addInput support

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#687]
~~(or add a new method)~~

Options object parameter?

**Comment by dcousens** [comment]
@afk11 as seen in https://github.com/bitcoinjs/bitcoinjs-lib/pull/696, we could use an options object rather than a new method.

**Comment by afk11** [comment]
It's just on TransactionBuilder though right?

This is stepping into breaking things, since there are already parameters there. I'd suggest we start thinking about solving by scriptPubKey now, because when adding an input with it's scriptPubKey and related opts we can check that the user is providing the right values (whether it's pre-signed or not)

**Comment by dcousens** [comment]
This is for `Transaction`.  See `Transaction.prototype.addInput`, you can pass the `scriptSig` in without having to an extra `setInputScript` call.

Whether that is useful,  could be up for discussion, but, consistent calls for both or neither.

**Comment by dcousens** [comment]
`scriptSig` if `isBuffer`,  else `opts` object?

**Comment by dcousens** [comment]
> scriptSig if isBuffer, else opts object?

I suppose I am open to this

**Comment by afk11** [comment]
I'd rather leave it as is for Transaction.addInput - it's straightforward, takes everything that constitutes a txin, and doesn't make any assumptions about how you're passing around data when calling it. 

Does need a witness field now though I guess :)

**Comment by dcousens** [comment]
> Does need a witness field now though I guess :)

That is the entire premise of this issue haha.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/issues/695,  IMHO confusing there is two issues.  I'll add a check list there.
