### ISSUE TITLE
wrong block version header data type

### ISSUE THREAD

**Issue by axvm** [bitcoinjs/bitcoinjs-lib#712]
Hello,
Official developer reference says [version header datatype is uint32](https://bitcoin.org/en/developer-reference#block-headers) but [in library it defined as int32](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/block.js#L41)

**Comment by fanatid** [comment]
@axvm looks like this docs lie about version type
[protocol documentation on bitcoin.it/wiki](https://en.bitcoin.it/wiki/Protocol_documentation#Block_Headers) looks right

also you can check that type is really Int32LE looking on any bitcoin header, for example header for block#1 in testnet: 
```
0100000000000000000000000000000000000000000000000000000000000000000000003ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4adae5494dffff001d1aa4ae18
```
as you can see first 8 charters is `01000000` that equal 1 if encoding is Int32LE

**Comment by axvm** [comment]
@fanatid looks like you are right. [nVersion is signed int32 in official client](https://github.com/bitcoin/bitcoin/blob/master/src/primitives/block.h#L24) 

Thank you for clarification.

**Comment by fanatid** [comment]
@axvm that is good that you check bitcoin core source code, that what I should do first.
My words above is not totally right, because `01000000` is valid UInt32LE.

**Comment by dcousens** [comment]
@fanatid that is what I ended up doing before I merged https://github.com/bitcoinjs/bitcoinjs-lib/pull/662,  as the documentation is all over the place.

**Comment by afk11** [comment]
Should check 2^31-1 or something, a correct implementation should parse this as -1 instead of 2^31-1. It matters for block version checks (ISM, etc)
