### ISSUE TITLE
Question: ECDSA Characteristic-2 support?

### ISSUE THREAD

**Issue by FGasper** [bitcoinjs/bitcoinjs-lib#719]
Does this library support ECDSA Characteristic-2 curves?

**Comment by fanatid** [comment]
@FGasper I'm afraid that characteristic-2 is not supported here, maybe https://github.com/indutny/elliptic will be helpful.
@dcousens please fix me, if I wrong.

**Comment by dcousens** [comment]
@fanatid is correct,  we do not officially support anything other `secp256k1`.
However,  that doesn't mean you couldn't change it yourself.
The code doesn't care *that* much,  it'd just be a matter of updating `ECPair` and some of the `ecdsa` code.
