### ISSUE TITLE
How to sign from multisigrawtransaction ?

### ISSUE THREAD

**Issue by namuyan** [bitcoinjs/bitcoinjs-lib#728]
First ,I try to create and sign general transaction.

I try to inport and sign a rawtransaction on standalone browser.
But script didn't work with an error "TypeError: transaction.ins is undefined".
What's wrong???

`        <script>`
`        function createTX() {`
`            var rawtoransaction = '0100000001313eb630b128102b60241ca895f1d0ffca2170d5a0990e094f2182c102ab94aa0000000000ffffffff01983a0000000000001976a914ad618cf4333b3b248f9744e8e81db2964d0ae39788ac00000000';`
`            var tx = new Bitcoin.TransactionBuilder.fromTransaction(rawtoransaction);`
`            console.log(tx);`
`            }`
`            </script>`

I use https://gist.github.com/Someguy123/49f849d693a063e4fbb2
I don't use node.js.

**Comment by dcousens** [comment]
``` js
var txHex = '0100000001313eb630b128102b60241ca895f1d0ffca2170d5a0990e094f2182c102ab94aa0000000000ffffffff01983a0000000000001976a914ad618cf4333b3b248f9744e8e81db2964d0ae39788ac00000000'
var tx = bitcoin.Transaction.fromHex(txHex)
var txb = new Bitcoin.TransactionBuilder.fromTransaction(tx)
```
