### ISSUE TITLE
how to get a public key?

### ISSUE THREAD

**Issue by harryio** [bitcoinjs/bitcoinjs-lib#733]
The basic examples show how to get the private key/public address, but how do I get the public key?

**Comment by dcousens** [comment]
@harryio what do you need the public key for? (I ask simply so I can determine what format you might need)

**Comment by harryio** [comment]
@dcousens um I want to encrypt some data, so that it could be later decrypted using the private key..

**Comment by dcousens** [comment]
``` js
let kp = bitcoin.ECPair.makeRandom()

console.log(kp.getPublicKeyBuffer())
// this is the serialized public key,  potentially ready for use in other ECC libraries

console.log(kp.Q)
// the ECPoint used by bitcoinjs-lib... see https://www.npmjs.com/package/ecurve
```

**Comment by harryio** [comment]
thanks, please close the issue

**Comment by harryio** [comment]
@dcousens can I convert the buffer to hex and store it in the database for later use?

**Comment by fanatid** [comment]
@harryio of course you, check [buffer docs at nodejs.org](https://nodejs.org/api/buffer.html)
```js
let kp = bitcoin.ECPair.makeRandom()
console.log(kp.getPublicKeyBuffer().toString('hex'))
```

**Comment by afk11** [comment]
@harrio: > um I want to encrypt some data, so that it could be later decrypted using the private key..

What are you trying to do here? There are more sound ways to implement encryption (not that you should) than by using this libraries public/private key, it already seems the wrong way to go.
