### ISSUE TITLE
How can I look at incoming transaction for specific addresses?

### ISSUE THREAD

**Issue by michelem09** [bitcoinjs/bitcoinjs-lib#734]
I'm looking for how to trigger something when a transaction is done to a specific address.
Is it possible with this library?

**Comment by afk11** [comment]
This library is a toolkit for working with bitcoin data, but you have to bring your own data unfortunately! Most explorer API's have something for this - it's kind of pointless to have API/networking code in here, because people will always need something different

**Comment by michelem09** [comment]
Thanks! Can you kindly point me to an explorer API compatible with Node.js?

**Comment by afk11** [comment]
Well they're all compatible with Node.js because they're over HTTP :) really, it's up to you, you probably wouldn't be wrong if you picked one at random.
