### ISSUE TITLE
Transaction on bitcoin address  derived  from bitcoinjs-lib not showing in Bitcoin core

### ISSUE THREAD

**Issue by Priyankaagrawal** [bitcoinjs/bitcoinjs-lib#739]
I have generated the xpub using bip32.org  and derieved random address using xpub

var hdNode = bitcoinjs.HDNode.fromBase58(derivedPubKey);
hdNode.derive(index).pubKey.getAddress().toString();

 the Private wif generated via  bip32.org imported in the Bitcoin core. On transferring amount on the address generated by above code., amount is not showing in my bitcoin-core..

**Comment by dcousens** [comment]
@Priyankaagrawal I'm not sure I understand what you're trying to do

**Comment by Priyankaagrawal** [comment]
I want to create unique address for all the user registered on my side for that I have used the below code
var hdNode = bitcoinjs.HDNode.fromBase58(derivedPubKey);
hdNode.derive(index).pubKey.getAddress().toString();

where derivedPubKey= bip32 xpub key.. 
Now, I am confused where I can view the amount deposited by user on derived address...

**Comment by dcousens** [comment]
If you have the address, you can view the balance using a block explorer such as https://webbtc.com/

**Comment by Priyankaagrawal** [comment]
Is there any way to amount deposited on derived address will show in bitcoin core 0.13??

**Comment by dcousens** [comment]
@Priyankaagrawal if you have access to a bitcoin-core full node,  and you can use the RPC.
See https://bitcoin.org/en/developer-reference#importaddress

**Comment by Priyankaagrawal** [comment]
![bip32 - copy](https://cloud.githubusercontent.com/assets/8734801/21287521/923b4854-c493-11e6-94b0-c137bd8b1517.png)

I have added the private key in the image in my bitcoin core.. and using xpub key in the image to generate the dynamic address.. But, on making transaction on the the address derived from  bitcoinjs-lib it's not  reflecting in bitcoin core..

My rpc is working and downloaded all the blocks

**Comment by dcousens** [comment]
@Priyankaagrawal watch out,  that image contains enough information to potentially recover that extended private key.

**Comment by Priyankaagrawal** [comment]
Sorry, I m not getting what you write?? Please explain..

**Comment by Priyankaagrawal** [comment]
@dcousens  I have checked in webbtc.com for the address derieved by  bitcoinjs individually it is showing balance, but I m not get how can I get this amount in my wallet to withdraw..

**Comment by dcousens** [comment]
@Priyankaagrawal look up each address individually?
