### ISSUE TITLE
All-at-once integration tests

### ISSUE THREAD

**Issue by afk11** [bitcoinjs/bitcoinjs-lib#753]
The transaction_builder.json fixtures file could be the basis of our integration tests going forward. Instead of using a hardcoded txid/vout/value/scriptPubKey, we can generate scriptPubKeys, fund them, and check the library never loses the ability to redeem them. 

Hopefully use the same method to produce invalid transactions (ie, CLTV output spent before it's time) and test those also. 

* we would know when a soft-fork screws the library, like accidentally using uncompressed keys on segwit (libraries which didn't implement DERSIG in advance had a 50% bad signature rate)
* we would know when a change has unintended effects (the library can't verify signatures itself, may as well check the network)
* we'd also notice a vector the library 'passes' but shouldn't pass on the network

**Comment by dcousens** [comment]
> The transaction_builder.json fixtures file could be the basis of our integration tests going forward. Instead of using a hardcoded txid/vout/value/scriptPubKey, we can generate scriptPubKeys, fund them, and check the library never loses the ability to redeem them.

Solid idea.
Up to implementing it?

**Comment by afk11** [comment]
I think so, hopefully isn't much on top of the current tests. 

Not 100% sure on that part, probably won't be able to leverage many API's yet until support improves. To try and detect cheating/bad propagation, we could have workers that watch for INV messages of those txids or something

**Comment by dcousens** [comment]
@afk11 shall I Close?

**Comment by afk11** [comment]
Leave open for now, have been thinking about this one.. would like to do it with regtest, since we can test out tx validity at certain blocks..

Then we can take the script & signing fixtures from the test fixtures, get freshly funded UTXO's, and check they're accepted through sendrawtransaction

**Comment by dcousens** [comment]
@afk11 are you happy to re-open this when its a priority?
Or did we want to keep it open?
