### ISSUE TITLE
Add Block.prototype.getParentId

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#761]
Thoughts @afk11 ?

Or maybe we should re-think and go with a `uint256` type that prints in reverse byte order... :man_shrugging:

**Comment by afk11** [comment]
Just had a quick look, we could do that.. if people decoded block hex I could them being confused why bitcoind can't find the prevBlock. The merkleRoot might also be worth doing as well so it's in the representation you'd compare against. 

Maybe worth splitting out the header into another object at the same time? Could put things like verifyMerkleBranch on the header, leaving calculateMerkleRoot where it is for people with the full block.

**Comment by dcousens** [comment]
@afk11 you use the non-reversed hash when you're using it cryptographically... about it.

**Comment by dcousens** [comment]
I don't think is ever going to be convenient.
