### ISSUE TITLE
How to get Address and TXID?

### ISSUE THREAD

**Issue by namuyan** [bitcoinjs/bitcoinjs-lib#762]
Im advised yesterday, I solved problems.
> var tx = new bitcoin.Transaction.fromHex(rawTX);
>             var txb = new bitcoin.TransactionBuilder.fromTransaction(tx);
>             console.log(Object.keys(txb.tx.ins[0]));
>             console.log(Object.keys(txb.tx.outs[0]));
> 

> ins : Array [ "hash", "index", "script", "sequence" ]  
> outs : Array [ "script", "value" ]

I extract input and output data. But, I cannot go to next step.
I want to convert ins.hash to HEX(TXID), and outs.script to Address(Base58).
I thought HDNode is needed.
How to do?

**Comment by dcousens** [comment]
``` js
let txId = Buffer.from(tx.ins[0].hash).reverse().toString('hex')

// may throw if no address exists
let address = bitcoin.address.fromOutputScript(tx.outs[0].script)
```

@afk11 these APIs throwing is annoying in most cases...  I wonder if `null` returned would be better if no address/script can be determined.

**Comment by namuyan** [comment]
Thank you for quick answer.
But error has occured....
**ReferenceError: Buffer is not defined**
What do I mistake ?
I use webrawser standalone. Not node.js .

**Comment by dcousens** [comment]
Are you using `browserify`?

See https://github.com/bitcoinjs/bitcoinjs-lib#browser

**Comment by namuyan** [comment]
No, I edit PaperWallet https://walletgenerator.net/

**Comment by namuyan** [comment]
I serched same your code on bitcoin.js.
This code works well
`var txInId = bitcoin.bufferutils.reverse(tx.ins[0].hash).toString("hex");`
`var address = bitcoin.Address.fromOutputScript(tx.outs[0].script).toString();`
Thank you for advice!
