### ISSUE TITLE
How to get scriptSig ?

### ISSUE THREAD

**Issue by namuyan** [bitcoinjs/bitcoinjs-lib#763]
> var tx = new Altcoin.Transaction.fromHex(rawTX);
> var txb = new Altcoin.TransactionBuilder.fromTransaction(tx);
> var scriptSig = txb.tx.ins[0].script;
> console.log("Script:" + scriptSig.toString("hex"));

I can get TXID ,Address! Thank !
Next, I need scriptSig as hex code.I searched and write code above.
But the code don't works. How to get scriptSig as hex?

**edit**: I changed `val` to txb.tx.ins[0] .

**Comment by dcousens** [comment]
> But the code don't works.

If `scriptSig` is indeed,  the script you want,  then `scriptSig.toString('hex')` should work.
What is wrong?

**Comment by namuyan** [comment]
Thank you for reply.
My browser console print `Script:[object Object]`.
It's Object..  I want get value like below. (decoderawtransaction on ssh)
How to do?
![scriptsig](https://cloud.githubusercontent.com/assets/19928816/23704668/6006a5c2-0449-11e7-9b7e-554818c10813.png)

**Comment by dcousens** [comment]
What is `console.log(scriptSig)` on its own?

**Comment by dcousens** [comment]
Don't use `txb.tx`,  use `tx`.

`txb.tx` is an internal representation and does not represent the actual transaction in its deserialized state.
From the code above,  you don't need `TransactionBuilder` at this time.

**Comment by namuyan** [comment]
> Don't use txb.tx, use tx.
OK
I edit PaperWallet with bitcoinjs. https://github.com/MichaelMure/WalletGenerator.net
I debug with FireFox, so use `console.log`.
