### ISSUE TITLE
Tests failing due to empty faucet

### ISSUE THREAD

**Issue by daynisy** [bitcoinjs/bitcoinjs-lib#767]
Hi all,
I just try to run the test cases in 'bitcoinjs-lib/integration/cltv.js', all test cases give error:
Error: Missing inputs
    at C:\bitcoinjs-lib\node_modules\cb-http-client\index.js:32:54
    at Request._callback (C:\bitcoinjs-lib\node_modules\httpify\index.js:27:7)
    at Request.self.callback (C:\bitcoinjs-lib\node_modules\request\request.js:188:22)
    at Request.<anonymous> (C:\bitcoinjs-lib\node_modules\request\request.js:1171:10)
    at IncomingMessage.<anonymous> (C:\bitcoinjs-lib\node_modules\request\request.js:1091:12)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

You can reproduce by running the test cases. The problem may be  the faucet part: can't get testnet bitcoin from faucet.

**Comment by rubensayshi** [comment]
@dcousens issue @blocktrail, looking into it now

**Comment by rubensayshi** [comment]
fixed the issue but it's still brittle cuz when multiple tests run in quick succession they'll try to use the same UTXO if the backend hasn't updated fast enough.

**Comment by daynisy** [comment]
Not working now. Check again please

**Comment by daynisy** [comment]
@dcousens will this be fixed or change another faucet?

**Comment by dcousens** [comment]
@daynisy I haven't had a chance to look into another faucet.

If someone funds `mwCMcEFUwXHpt4gLTB2wUhbP5c4M3HS9Un` with test net coins,  it should last for quite a while.

**Comment by dcousens** [comment]
Filled with more testnet BTC... hopefully it lasts a while.

**Comment by dcousens** [comment]
Nevermind,  this wasn't related to the testnet balance any way.

@rubensayshi this was just the slow @blocktrail backend :stuck_out_tongue: - having trouble keeping up aye? haha

**Comment by HungNguyen007** [comment]
@dcousens The Faucet Empty issue is still available. Please check my log attached.
[FaucetEmpty_log.txt](https://github.com/bitcoinjs/bitcoinjs-lib/files/1097096/FaucetEmpty_log.txt).

More info,  link https://api.blocktrail.com/cb/v0.2.1/tBTC always returns {code: 404, msg: Endpoint not found}

**Comment by rubensayshi** [comment]
in this case it really was just the "faucet" address of bitcoinjs being empty, I filled it up with a bunch of UTXOs ;)

**Comment by rubensayshi** [comment]
@dcousens I'm not sure how much longer we'll continue to support the cb API, the bitcoinjs test suit is the only usage of it and we're getting closer to finally migrating to our new backend and tbh I don't really feel much for reimplementing it.

me or @afk11 could update the testsuite to use the BTC.com API if you'd like ;)

**Comment by dcousens** [comment]
@rubensayshi all we really need is a faucet API... the rest I could easily switch over to one of my own CB end points

**Comment by dcousens** [comment]
Hilariously,  [someone appears to have swept the WIF a few times](https://www.blocktrail.com/tBTC/tx/ec72551edb6230fb7f45221f398545b7383f99becaf20b88fc1c38131eea5f17).  Can't say I didn't expect it,  but,  anyway.

If you're wanting to decommision the CB API,  no worries,  I have an API I can switch to.

**Comment by rubensayshi** [comment]
you could pull the WIF from an ENV var and set it in travis to a different one?

**Comment by dcousens** [comment]
@rubensayshi I could,  if it continues being an issue,  but,  it is OK for now

**Comment by dcousens** [comment]
The problem is PR's from outside the organization won't have that ENV
