### ISSUE TITLE
ECPair.fromPublicKeyBuffer fails when code is browserified and minified

### ISSUE THREAD

**Issue by shea256** [bitcoinjs/bitcoinjs-lib#768]
Earlier I was using this function:

```js
import { ECPair } from 'bitcoinjs-lib'
export function publicKeyToAddress(publicKey) {
  const publicKeyBuffer = new Buffer(publicKey, 'hex')
  const keyPair = ECPair.fromPublicKeyBuffer(publicKeyBuffer)
  return keyPair.getAddress()
}
```

I would get the following error:

```text
Error at new o
Function.o.fromPublicKeyBuffer
```

Specifically, it fails on this line:

```js
return new ECPair(null, Q, {
  compressed: Q.compressed,
  network: network
})
```

Now, in order to avoid this error, I'm doing the following:

```js
import { address as baddress, crypto as bcrypto } from 'bitcoinjs-lib'
export function publicKeyToAddress(publicKey) {
  const publicKeyBuffer = new Buffer(publicKey, 'hex')
  const publicKeyHash160 = bcrypto.hash160(publicKeyBuffer)
  const address = baddress.toBase58Check(publicKeyHash160, 0x00)
  return address
}
```

I am currently no longer facing this error, as I've shifted over to using other code (what I just mentioned above).

That said, I wanted to bring this up because I had an earlier issue with `bitcoinjs-lib` and browserified and minified code.

Thanks for all the work that was put into this library. Please let me know if you'd like more details.

**Comment by dcousens** [comment]
Probably at this line: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/ecpair.js#L32 - but you don't seem to be showing the right error.

I would have expected `Expected ECPoint, got o` or similar.
In future,  please heed the warning in the README.

> When uglifying the javascript, you must exclude the following variable names from being mangled: Array, BigInteger, Boolean, ECPair, Function, Number, Point and Script. This is because of the function-name-duck-typing used in typeforce. Example:

**Comment by shea256** [comment]
Ahhhh yes, thank you for pointing this out.

I'll try calling uglify like so:

```
uglifyjs ... --mangle --reserved 'Array,BigInteger,Boolean,ECPair,Function,Number,Point'
```

I assume this will fix the error. Closing this issue now.
