### ISSUE TITLE
Invalid checksum on iOS devices

### ISSUE THREAD

**Issue by coreyphillips** [bitcoinjs/bitcoinjs-lib#769]
I'm currently receiving the following error on an iOS device for a React Native project ("Invalid checksum"). The error is triggered when attempting to use the following:
```
const HDNode = require("./bitcoinjs-lib/src/hdnode");
const xpub = "xpub6AoynT2YixgjHK2yNTDPJGmbFaNfiKTVNb4zVygVmSfhWktotj8woL2nT7FALSFEhggNemiy5KEGWxRpNYtsHVVvWCC99WuhzvAvZTJD1SH";
let node = HDNode.fromBase58(xpub);
```
The error appears to be coming from `base58check.decode` where `decodeRaw` doesn't pass the checksum check. 

One important thing to note is that this error does not occur within the iOS simulator, Android emulator or on an Android device. It appears to be isolated to iOS devices only. Does anyone have any thoughts as to why this error seems to only pop up on iOS devices?

<img width="375" alt="screen shot 2017-03-25 at 4 42 32 pm" src="https://cloud.githubusercontent.com/assets/8532651/24325960/62aa6d0c-117a-11e7-9a56-fdc4bdf3d3fb.png">

**Comment by dcousens** [comment]
Check your sha implementation.
Specifically,  run the tests in https://github.com/crypto-browserify/sha.js on device and see what happens.

**Comment by dcousens** [comment]
What iOS version?
And how have you shimmed `Buffer` for `react-native`?

**Comment by coreyphillips** [comment]
I'm currently using iOS v10.2 and rn-nodeify to shim buffer. 

Thanks for the suggestions, dcousens. After some more digging, I'm fairly certain I know where the issue is coming from. It appears that iOS does not want to slice the buffer in `bs58check`'s `decodeRaw`. Specifically, `var payload = buffer.slice(0, -4)` does not appear to be called at all on iOS resulting in the invalid checksum error. Currently looking into possible workarounds, but that behavior is throwing me for loop.

**Comment by coreyphillips** [comment]
Got it! 
I found the solution here (https://github.com/feross/buffer/issues/136). It appears that iOS 10 devices have difficulty with `buffer.slice`. To resolve this issue I had to update buffer to v5.0.5.

**Comment by dcousens** [comment]
@coreyphillips perhaps you'd be willing to PR a README note here for our users under "#browserify"?

**Comment by silence-may** [comment]
excuse me 
  I update my buffer to 5.1.0  
 howere,  It still doesn't work,
what should i do ???

**Comment by Brain-tech** [comment]
Updated to 5.1.0 too and it's not working either...

**Comment by coreyphillips** [comment]
@Brain-tech, I've since created a gist to help get bitcoinjs-lib working in a RN project [here](https://gist.github.com/coreyphillips/723a718f3630f965a83007a81afe5926). Feel free to ping me if you have any trouble getting it setup.

Also, hdnode has been removed from bitcoinjs-lib. You'll want to use [bip32](https://github.com/bitcoinjs/bip32) instead.
