### ISSUE TITLE
Get from XPRV to WIF (BIP32)

### ISSUE THREAD

**Issue by shayanb** [bitcoinjs/bitcoinjs-lib#772]
I'm having issues trying to get from (xprv... , path) to a WIF to sign a transaction with, regular BIP32 derive and sign procedure. 
 
My last guess was to try [HDNode.fromBase58](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/hdnode.js#L54) but still failing to get the private key.

Even on the tests I couldn't find a code sample that does this. Is it possible to do with bitcoinjs-lib?

**Comment by dcousens** [comment]
> My last guess was to try HDNode.fromBase58 but still failing to get the private key.

How was this failing you?
We'll add an example to the integration tests based on what your problem is.

**Comment by shayanb** [comment]
So this fails to get me the key
```
    var xprv = 'tprv8ZgxMBicQKsPd7Uf69XL1XwhmjHopUGep8GuEiJDZmbQz6o58LninorQAfcKZWARbtRtfnLcJ5MQ2AtHcQJCCRUcMRvmDUjyEmNUWwx8UbK'
    var bitcoin = require('bitcoinjs-lib')
    var key = bitcoin.HDNode.fromBase58(xprv, 'testnet')
    console.log(key)
```

a working example would be great.

**Comment by dcousens** [comment]
@shayanb you were very close to the actual solution.

> var key = bitcoin.HDNode.fromBase58(xpriv, bitcoin.networks.testnet)

Example added: https://github.com/bitcoinjs/bitcoinjs-lib/pull/773

**Comment by dcousens** [comment]
@shayanb was the error reported in your example not clear?

**Comment by shayanb** [comment]
@dcousens thanks, can't remember the exact error message but it had something to do with can't find Private attribute of undefined. anyways thanks for the example it was clear enough from there.

Just another thing, in order to sign a transaction (from unsigned hex generated by pycoin) with a child key, is this the best way to do it? it seems too complicated comparing to how pycoin does this

```javascript
var HDkey = bitcoin.HDNode.fromBase58(self.options.sellXprv, self.options.network)
  var child = HDkey.derivePath('m/' + txs.subkeys[0].toString())
  var key = bitcoin.ECPair.fromWIF(child.keyPair.toWIF(), self.options.network)
  var tx = bitcoin.Transaction.fromBuffer(new Buffer(txs.unsigned_tx, 'hex'), true) // disable validation
  var builder = bitcoin.TransactionBuilder.fromTransaction(tx, self.options.network)

  tx.ins.forEach(function (input, index) {
    builder.sign(index, key)
  })
  tx = builder.build()
```

**Comment by dcousens** [comment]
No need to go to WIF.

``` js
var HDkey = bitcoin.HDNode.fromBase58(self.options.sellXprv, self.options.network)
var child = HDkey.derivePath('m/' + txs.subkeys[0].toString())

var tx = bitcoin.Transaction.fromBuffer(Buffer.from(txs.unsigned_tx, 'hex'), true)
var builder = bitcoin.TransactionBuilder.fromTransaction(tx, self.options.network)
tx.ins.forEach(function (input, index) {
  builder.sign(index, key)
})
tx = builder.build()
```

**Comment by shayanb** [comment]
Thanks, this is basically the process of getting a child keys, which the sample you sent me is pretty similar process.
```python
    da_key = BIP32Node.from_wallet_key(wallet_key)
    btc_address = da_key.subkey_for_path(path).bitcoin_address()
    btc_private = da_key.subkey_for_path(path).wif()
# secret_exponents = da_key.subkey_for_path(path).secret_exponents()
```

and to sign an unsigned_tx, it's similarly complicated :)
```python
    hash160_lookup = build_hash160_lookup(secret_exponents)
    tx = Tx.from_hex(unsigned_tx)
    signed_tx = tx.sign(hash160_lookup).as_hex()
```

**Comment by dcousens** [comment]
@shayanb you can use `bitcoin.Transaction.fromHex(hex)`,  I assumed you were using `fromBuffer` because you disabled data length validation...
