### ISSUE TITLE
Segwit block serialization not read by Block.fromHex (or Block.fromString)

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/bitcoinjs-lib#777]
When you call 'getBlock' on segwit-enabled nodes (for example with testnet), they return block together with segwit data.

Block class, however, cannot deal with this and returns error.

For example, this is a block 0000000000001ea1cbaf188f2d3b4c6d92a39ff89ffeefcc587f93a62f049ad6 from testnet

(you get it by `bitcoin-cli getblock 0000000000001ea1cbaf188f2d3b4c6d92a39ff89ffeefcc587f93a62f049ad6 false`)

https://gist.github.com/runn1ng/c12991022b53313a94f212c67bf74767

When you run Block.fromHex on this, you get an error

```js
var bitcoin = require("bitcoinjs-lib");
var fs = require('fs');


var data = fs.readFileSync('segwit_block', 'utf8').replace(/\n/g,'');

var block = bitcoin.Block.fromHex(data);

```

> buffer.js:829
>     throw new RangeError('Index out of range');
>     ^
> 
> RangeError: Index out of range
>     at checkOffset (buffer.js:829:11)
>     at Buffer.readUInt32LE (buffer.js:891:5)
>     at readUInt32 (/.../node_modules/bitcoinjs-lib/src/transaction.js:30:20)
>     at Function.Transaction.fromBuffer (/.../node_modules/bitcoinjs-lib/src/transaction.js:60:17)
>     at readTransaction (/.../node_modules/bitcoinjs-lib/src/block.js:50:26)
>     at Function.Block.fromBuffer (/.../node_modules/bitcoinjs-lib/src/block.js:60:14)
>     at Function.Block.fromHex (/.../node_modules/bitcoinjs-lib/src/block.js:68:16)
>     at Object.<anonymous> (/.../do.js:8:27)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)

**Comment by runn1ng** [comment]
Actually, it's not a Block issue but a Transaction issue; I was under the impression that the segwit data are separate in the block serialization (so it will be enough to cut it off from the end), but they are actually in the transaction data itself, so what needs to be fixed is Transaction, not Block

**Comment by dcousens** [comment]
OOI, have you tried this on `master`? [not encouraged for production,  but we are late on this release]

**Comment by runn1ng** [comment]
Ah, no I haven't, I will

**Comment by runn1ng** [comment]
It's working. Sorry for the noise then!

**Comment by dcousens** [comment]
> I was under the impression that the segwit data are separate in the block serialization (so it would be enough to cut it off from the end), but they are actually in the transaction data itself, so what needs to be fixed is Transaction, not Block

On a side note,  this misconception is why it is funny when you hear someone say that SegWit isn't a block size increase :laughing: .
