### ISSUE TITLE
how do you validate a btc addressing using this?

### ISSUE THREAD

**Issue by satoshinakamotos** [bitcoinjs/bitcoinjs-lib#781]
I couldn't find a function that validates a btc address. How can this be done? Thanks.

**Comment by bityogi** [comment]
If you're generating an address using the library, then I'm sure it will only return a valid address, but if you want to add your own checks to it, here is a good resource:

http://stackoverflow.com/questions/21559851/bitcoin-address-form-validation-javascript-and-php

**Comment by dcousens** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/address.js#L7

`bitcoin.addresses.fromBase58Check` will throw if the provided `address` parameter is invalid.

Use `bitcoin.addresses.toOutputScript` to also check the version byte for a valid script.
