### ISSUE TITLE
Should P2PKH still be the default `getAddress`?

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#787]
Following on from discussion in https://github.com/bitcoinjs/bitcoinjs-lib/issues/779.

Is `getAddress` a sane assumption now that P2SH is highly prevalent,  and SegWit introduces P2WPKH and P2WSH ... and bech32 soon...

For now,  I vote we deprecated `getAddress` asap,  and remove it in `4.0.0`... thoughts?
What do we promote as the idiomatic flow for getting addresses?
How we do we even start that conversation...

**Comment by afk11** [comment]
Yea it's probably a good idea to make people think twice about it. 

There's a similar situation if we exposed 'getScriptHash' or something. The current route is to make use of the primitives directly. Maybe a script.getHash160() and script.getSha256() for P2SH and P2WSH respectively?

ECPair could expose getHash160() ?

* `baddress.p2pkh`
  * `.fromHash()` 
  * `.fromKey()`
  * `.fromOutputScript()`

* `baddress.p2sh`
    * `.fromHash()`
    * `.fromRedeemScript()` 
    * `.fromOutputScript()`

* `baddress.p2wpkh`
    * `.fromHash()`
    * `.fromKey()`
    * `.fromOutputScript()`

* `baddress.p2wsh`
    * `.fromHash()`
    * `.fromWitnessScript()` 
    * `.fromOutputScript()`

maybe setting us up for:
* `baddress.fromOutputScript()`
* `baddress.toOutputScript()`

Random thoughts:
* If we encourage the fromKey/fromScript when people generate addresses, it's a chance to enforce (meaning: reject) certain things before an address is produced. For example, segwit requires compressed keys everywhere - something we can enforce in `baddress.p2wpkh.fromKey` &  `baddress.p2wsh.fromScript` (or maybe a more ideal place)

* `fromKey`/`fromScript` will require hashing, so after the initial generation `fromHash`/`fromOutputScript` might be preferred (hmm, if ECPair is immutable, maybe we can cache the hash160/sha256 as they're generated?

* something that's often handy is the ability to go from address -> scriptPubKey..

**Comment by dcousens** [comment]
`bitcoin.address.P2WPK.fromKeyPair(keyPair)` ... could work.

Will read again tomorrow,  but good ideas!

**Comment by dcousens** [comment]
And it would/could be consistent with our script template interface.

**Comment by dcousens** [comment]
How does a `bech32` address fit into this?

**Comment by afk11** [comment]
I guess address classes need to indicate what serialization they are, since to date we've only had base58? Hopefully not too messy..

**Comment by dcousens** [comment]
I think you're proposal is solid,  with `fromKey` being `fromKeyPair`.

@afk11 I don't think the serialization classes will be an issue,  it'll simply be `baddress.P2PKH.toString/fromString` functions.

`fromBase58Check` will be Base58Check only.
`fromString` will allow anything.
`fromBech32` will be Bech32 only.

How do we deal with the "QR code" optimized address schemes (aka, uppercase bech32)?

`toQRString`?

**Comment by dabura667** [comment]
Everything sounds great so far...

I would like the prototypes on the ECPair as an option though.

**Comment by dcousens** [comment]
@dabura667 I don't think the `ECPair` options would be necessary if `bitcoin.address` offers `fromKeyPair`

**Comment by dcousens** [comment]
I think this change should align with a renaming of `bitcoin.script.*` templates to be identical.

I personally prefer `p2wpkh` over `witnessPubKeyHash`

**Comment by afk11** [comment]
p2wpkh is nicer, shorter, though notice it's a break for script.*, but not the worst thing if this goes into a major release.

not sure if changing the default is a good idea, but could gradually remove support for 'key.getAddress()' over time so people are forced to think about it?

**Comment by dcousens** [comment]
@afk11 I think the general consensus is to phase out P2PKH as soon as possible.

This requires a major bump any way,  lets do both now.  Keeping `.getAddress()` is only serving to confuse IMHO.

**Comment by dcousens** [comment]
Consensus is remove `.getAddress` with new streamline/compact interfaces that support all script types.
