### ISSUE TITLE
message.{sign,verify} missing in v3

### ISSUE THREAD

**Issue by Polve** [bitcoinjs/bitcoinjs-lib#795]
I was using the message class to sign and verify bitcoin messages in v2.3 and I'm unable to find any documentation about the removal of the "message" class in v3.

Do I need to reimplement those methods or are they available in other classes?

**Comment by Polve** [comment]
Checking closed tickets I discovered the new bitcoinjs-message module.
I think that it would be useful to mention it more clearly in the release notes.

Sorry for the noise.

**Comment by dcousens** [comment]
Thanks @Polve - added it](https://github.com/bitcoinjs/bitcoinjs-lib/commit/866a[59f7a3ab0042f1b587357122b4bd916f7716) to the CHANGELOG.
