### ISSUE TITLE
React Native compatibility

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#797]
Use of `safe-buffer`,  all the way down, will likely be the easiest and friendliest method to fix this.

**Comment by mwaeckerlin** [comment]
That's exactly what I'm looking for.

Do you already have a timeline / release plan? ;)

**Comment by dcousens** [comment]
> Do you already have a timeline / release plan?

Nope,  but the PR's are straight forward if you'd like to help :+1:

**Comment by dcousens** [comment]
Partially completed in https://github.com/bitcoinjs/bitcoinjs-lib/pull/790,  waiting on:

- [ ] https://github.com/crypto-browserify/sha.js/pull/45
- [ ] https://github.com/crypto-browserify/createHash/pull/19

**Comment by dcousens** [comment]
I think this is OK now... but I'd appreciate some more feedback.
Closing until someone pipes in.
