### ISSUE TITLE
Basic questions about address generation

### ISSUE THREAD

**Issue by DSofter** [bitcoinjs/bitcoinjs-lib#798]
Hi thanks for making this awesome library!

I have some silly questions about address generation.

My first question is, when I generate address with the following code:
```js
function rng () { return new Buffer('zzvvzzzzzzzzzzzzzzzzzzzzzzzzzzzz') }

// generate random keyPair
var keyPair = bitcoin.ECPair.makeRandom({ rng: rng })
var address = keyPair.getAddress()
```
Why does `rng` have to be 32 bytes? I found the check here: https://github.com/bitcoinjs/bitcoinjs-lib/blob/170328341bdcf2a22d6ee6df1df587ea4e83c8a9/src/ecpair.js#L95

Another question I have is: 
Why do most wallet have 12-word seeds? I think any number of words is fine right? Why not make it 10 or 18 or 24? Also how to wallets make sure they don't generate the same 12 words?

Thanks in advance!

**Comment by dcousens** [comment]
> Why does rng have to be 32 bytes? I found the check here: 

The enforcement of 32 bytes is to protect you from accidentally providing a bad RNG implementation.
It doesn't protect you against low or no entropy, but, its simply a better guarantee than the alternative.

> Why do most wallet have 12-word seeds? I think any number of words is fine right? Why not make it 10 or 18 or 24? Also how to wallets make sure they don't generate the same 12 words?

That is a question for https://github.com/bitcoinjs/bip39,  but the answer is,  the entropy  has to be a multiple of 32 bits,  and it must be in the range of 128-256 bits.
See https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic.

IIRC,  that leaves us with  12, 15, 18, 21, 24 as options.
