### ISSUE TITLE
Various address transaction for an address.

### ISSUE THREAD

**Issue by nikoliveira** [bitcoinjs/bitcoinjs-lib#799]
Various address transaction for an address.

How can I create a transaction (without propagating ..) from multiple pvtKeys to a publicAddress?

I did not find the example.
Thank you.

**Comment by dcousens** [comment]
Do you mean multisig?
Or do you mean https://github.com/bitcoinjs/bitcoinjs-lib/blob/d853806/test/integration/basic.js#L43?

**Comment by nikoliveira** [comment]
I did not understand what the #L43 example is.

What I have is about 20 pvt with balance. And I want to send it to one puclic address.

**Comment by dcousens** [comment]
@nikoliveira what was unclear about the example?

If you understand this concept,  you'll be able to extrapolate it to your task using a mix of https://github.com/bitcoinjs/bitcoinjs-lib/blob/d853806/test/integration/basic.js#L43 and https://github.com/bitcoinjs/bitcoinjs-lib/blob/d853806/test/integration/basic.js#L62.

**Comment by nikoliveira** [comment]
I'm sorry, but what is "txId"? I am generating a transaction as I can already know its transactionId. If I understood correctly

**Comment by nikoliveira** [comment]
/\ i speed in your example:

"// Add the input (who is paying):
// [previous transaction hash, index of the output to use]
var txId = 'aa94ab02c182214f090e99a0d57021caffd0f195a81c24602b1028b130b63e31'"

https://bitcoinjs.org/

**Comment by dcousens** [comment]
`txId` is **t**rans**actio**[x]n **id**

**Comment by nikoliveira** [comment]
I do not understand how I can buy this value. I know only my pvtKey, the value and the recipient's pubKey.

Where to get the txId?

**Comment by dcousens** [comment]
You need to know the previous transaction you are spending *from*,  that is,  the transaction which you received Bitcoin from in the first place.

You can use a block explorer to figure this out.

If you're doing this for a one-off,  I suggest you import these private keys into a wallet such as `bitcoind` and use that for sending your recipient the funds,  rather than doing this yourself.
