### ISSUE TITLE
Incorrect value of the sum of inputs in tx.build()

### ISSUE THREAD

**Issue by nikoliveira** [bitcoinjs/bitcoinjs-lib#802]
Hi,
I'm doing some tests on testnet and I sent 0.58326400 btc to this address mmCmB4St9q7RCkH22ZpcQiAbw3dRmd4Dky.

When I try to generate a transaction from this address to another value after the build is 0.91443000.

You know what might be causing the difference?

Here my code: https://jsfiddle.net/gqauh6gj/

**Comment by nikoliveira** [comment]
PS: I used this site to do decode of tx http://tbtc.blockr.io/tx/push

**Comment by dcousens** [comment]
Can you post the code that is the problem?

**Comment by nikoliveira** [comment]
https://jsfiddle.net/gqauh6gj/ code full

**Comment by dcousens** [comment]
What's the issue?

**Comment by nikoliveira** [comment]
This address contains 0.58326400 (http://tbtc.blockr.io/address/info/mmCmB4St9q7RCkH22ZpcQiAbw3dRmd4Dky),
but when creating a _transaction.Builder()_ as the example code (https://jsfiddle.net/gqauh6gj/) it returns that The sum of the inputs is **0.91443000**. The correct would be the sum of the inputs returning **0.58326400**

**Comment by dcousens** [comment]
What do you mean sum of the inputs?

**Comment by nikoliveira** [comment]
When I get the generated hex of `tx.build().toHex ()` and paste it into the decode and push service, it informs that the sum of the inputs is `0.91443`

See a print
Https://gyazo.com/5476cc80994eb85fdd3c5977a0488d03

**Comment by nikoliveira** [comment]
this is service: http://tbtc.blockr.io/tx/push

**Comment by dcousens** [comment]
@nikoliveira then that sum is wrong provided the transactions actually only add up to ` 0.58326400`.

**Comment by fanatid** [comment]
@nikoliveira some UTXOs is wrong, for example:
[844ddafdc500b24d4174cffc1350f9256a752a657b8638a4c0065810a2ed9e14](http://tbtc.blockr.io/tx/info/844ddafdc500b24d4174cffc1350f9256a752a657b8638a4c0065810a2ed9e14) you use `0` output, but should use `1`
