### ISSUE TITLE
can one WIF Address generate many bitcoin address?

### ISSUE THREAD

**Issue by modernduck** [bitcoinjs/bitcoinjs-lib#804]
Hi i'm completely new to this i have compile bitcoin.min.js to test at browser(client side) Just wonder if we can generate multi bitcoin address from single WIF

**Comment by dcousens** [comment]
8 WIF is a private key.
A private key has a public key.
The public key can be encoded in a compressed and uncompressed format.
An encoded public key can be used in scripts.
Scripts can be used raw,  as a P2SH address,  some can even be a P2PKH address!

You see, the question,  can a "WIF address generate many bitcoin address",  isn't entirely clear.
It can be used to generate two  P2PKH addresses,  using a compressed and uncompressed public key.

**Comment by modernduck** [comment]
So if I got a keypair from wif and I need to generate 2000 Bitcoin address from it I need to get public key first? Or I could use like keypair.getAddress(???)

**Comment by dcousens** [comment]
@modernduck I suggest you look at and use BIP32.   An example can be seen [here](https://github.com/bitcoinjs/bitcoinjs-lib/blob/8e1c69183f74acce06d6e35b614e504b18bb04e1/test/integration/bip32.js#L19).

**Comment by modernduck** [comment]
Thank you so much I think it's working now
