### ISSUE TITLE
Cannot Pass the Raw transaction from BIP32 derived format (Script resulted in a non-true stack)

### ISSUE THREAD

**Issue by modernduck** [bitcoinjs/bitcoinjs-lib#805]
Hi (again)

So what I did was trying to create a main wallet from seed Hex to be able to send bitcoin to other but use child wallet (derived from main wallet) to retrieve bitcoin so what i did was
`var root = bitcoin.HDNode.fromBase58("xprv....");`
`  var child = root2.derivePath("m/42'/0");`
  `child.getAddress();// use this address to test for retrieve the btc which is 1DUu92g876dWfrqiR3gyYhSjHSLtYnj7te `

then when I check at https://blockchain.info/tx/1a6ab38963e218a8616f357c40a7d788f45f964a9b52181830b545bad41398f1?show_adv=false

I use 1a6ab38963e218a8616f357c40a7d788f45f964a9b52181830b545bad41398f1 as previous hash then do follow
`var prev_hash = "1a6ab38963e218a8616f357c40a7d788f45f964a9b52181830b545bad41398f1" `
`var root = bitcoin.HDNode.fromBase58("xprv...."); //same base58 key as previous`
`var tx =  new bitcoin.TransactionBuilder()`
`tx.addInput(prev_hash, 0)`
`tx.addOutput("destination_address", 350000)//want to transfer 0.0035 btc`
`tx.sign(0, root.keyPair)`
`tx.build().toHex()` 

then pass it to https://blockchain.info/pushtx  but got error
`java.lang.RuntimeException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@7b5654bc]
`

instead any idea what I did wrong?

**Comment by modernduck** [comment]
would you mind enlighten me a bit @dcousens  :)

**Comment by dcousens** [comment]
I can't really tell what is wrong without seeing the result of `tx.build().toHex()` - it looks good.

**Comment by dcousens** [comment]
I think `tx.addInput(prev_hash, 0)` should be `tx.addInput(prev_hash, 1)`,  as `1DUu92g876dWfrqiR3gyYhSjHSLtYnj7te` is the 2nd output in https://blockchain.info/tx/1a6ab38963e218a8616f357c40a7d788f45f964a9b52181830b545bad41398f1

**Comment by modernduck** [comment]
here is result of tx.build().toHex()
0100000001f19813d4ba45b5301818529b4a965ff488d7a7407c356f61a818e26389b36a1a000000006b483045022100f8a80fb01b36054aede15eecedc6b8723faf1de4bd6801a8cc0eedf2df06bc610220788d8870e62b5fefe92e82e21eee8bf0d7babb54c5e9988e10c1620599d39334012103e42df4ef7ecc0c0d4c10fd55efd3b2c63c562ba28b421b57e49336d92e911138ffffffff01305705000000000017a91462d219199171882edfd8e7fecb32ccaead13f0da8700000000

**Comment by modernduck** [comment]
@dcousens  oh i try to fix as you said but and go
`0100000001f19813d4ba45b5301818529b4a965ff488d7a7407c356f61a818e26389b36a1a010000006b48304502210084325303f3523a52fb63ae9ed61cda3efaa04295ab03ca7858e9fd1da77b28ee02200dc3a1998ebefe9196a5842bd0549d4c798060d3751daa7f6f635cfb45f7c8c4012103e42df4ef7ecc0c0d4c10fd55efd3b2c63c562ba28b421b57e49336d92e911138ffffffff01305705000000000017a91462d219199171882edfd8e7fecb32ccaead13f0da8700000000`

but got java.lang.RuntimeException: org.bitcoinj.core.ScriptException: OP_EQUALVERIFY: non-equal data instead

**Comment by dcousens** [comment]
That means the public key provided in the signature does not hash to the address  `1DUu92g876dWfrqiR3gyYhSjHSLtYnj7te`.

Based on
> var child = root2.derivePath("m/42'/0");

Shouldn't
> tx.sign(0, root.keyPair)

be
> tx.sign(0, root.derivePath("m/42'/0").keyPair)

**Comment by modernduck** [comment]
Woo hoo I think it's working now thank you for helping me understand bitcoin more
