### ISSUE TITLE
Watching bitcoin addresses

### ISSUE THREAD

**Issue by lumio** [bitcoinjs/bitcoinjs-lib#807]
Hello,

I'm sorry, this is a real newbie question, but ... is it possible to watch other addresses with this library?

**Comment by afk11** [comment]
No - this library focuses solely on the mechanics of keys/scripts/transactions, and leaves data up to the user. Offering support for one API instead of another would be a vendor lock in, while letting down the other 99% of users that need something different.

**Comment by lumio** [comment]
Thank you! Do you know any API to watch bitcoin addresses?
