### ISSUE TITLE
How to get unspent / balance / getReceivedBy[...] for HD Wallet

### ISSUE THREAD

**Issue by thrastarson** [bitcoinjs/bitcoinjs-lib#809]
I've set up an HD Wallet as described in BIP32 and BIP44. On the same server I am also running a bitcoin core daemon (bitcoind). 

At first, I thought I could use a JS wrapper for the Bitcoin HTTP JSON-RPC to query for balances, unspent output, and getReceivedByAddress for addresses created by my bitcoinjs-lib HD Wallet. I managed to get such a wrapper working. However, many of those API calls won't work since the addresses are not connected to the wallet in the bitcoind, and will not return meaningful results.

I'm trying to figure out if there is a native bitcionjs-lib way to make queries about transactions to addresses created by HDNode. If not, am I forced to use an outside API like blockchain.info to get these results?

Thanks,

**Comment by dcousens** [comment]
> If not, am I forced to use an outside API like blockchain.info to get these results?

`bitcoinjs-lib` does not have a blockchain associated with it,  nor does it interact with the bitcoin network in any way.

So yes,  you will need an external source for your blockchain data.

**Comment by thrastarson** [comment]
Thanks. So just to confirm, there's no way to 'register' `bitcoinjs-lib` keys with a separate blockchain on the same server, so the `bitcoin-cli` on that server recognizes me as their owner?

**Comment by dcousens** [comment]
>  there's no way to 'register' bitcoinjs-lib keys with a separate blockchain on the same server

You can use `bitcoind`'s RPC command [`importprivkey`](https://bitcoin.org/en/developer-reference#importprivkey),  whether that meets your use case is up to you.

**Comment by thrastarson** [comment]
Great. Thanks for your help. My issue is resolved.
