### ISSUE TITLE
Add example for storing, deserializing HDNodes

### ISSUE THREAD

**Issue by thrastarson** [bitcoinjs/bitcoinjs-lib#812]
I have two questions to ask you wise men that I feel would be useful to future generations.

I'm creating what is, for all intents and purposes, a web merchant, and following the BIP44 design of an HD wallet structure. Currently, I keep a separate server to handle bitcoin logic (and keys). The web application server talks to the btc server to request new addresses to receive payments, and to make requests for refunds.

First issue, what is the correct way to store an HDNode? Should I store it in a db in some canonical serialized format? Should I store the original mnemonic seed and rebuild all nodes as needed? The latter is easily done by following your examples. Ideally, I would want to store the top level key(s) offline, so as not to expose the entire wallet to this server.

Which brings me to...

Second issue, is there a way to initialize, possibly deserialize, a 'downstream' HDNode (let's say path "m/44'/0'/0") without building out the higher-up pairs in the tree. It is my understanding that BIP32 is designed for this, and I have a layman's understanding of the raw derivation, but I am unsure how to get there with bitcoinjs-lib.

If I can initialize such a lowly HDNode, hd_low, I assume hd_low.derive(index) is the right way.

Thanks, gentlemen.

**Comment by dcousens** [comment]
`HDNode.prototype.toBase58`?

**Comment by thrastarson** [comment]
Yes, this works out great. 
`
var bitcoin = require('bitcoinjs-lib');
var add1 = hdnodeA.getAddress();
var hdnodeSer = hdnodeA.toBase58();
var hdnodeB = bitcoin.HDNode.fromBase58(hdnodeSer, bitcoin.networks.bitcoin);
var add2 = hdnodeB.getAddress();

assert.strictEqual(add1, add2);
`
Problem solved!

**Comment by dcousens** [comment]
See #844
