### ISSUE TITLE
how to access .dat file using bitcoinjs-lib

### ISSUE THREAD

**Issue by tabz11** [bitcoinjs/bitcoinjs-lib#813]
Hi,

I am trying to access the full node from my javascript code using this library, how can I do this? also is there any documentation of available functions for this library.

Thanks,

**Comment by dcousens** [comment]
https://github.com/bitcoinjs/blkdat-stream

**Comment by tabz11** [comment]
Thanks, 
is there any wiki which can help me with examples?

**Comment by dcousens** [comment]
@tabz11 did you figure it out?
`Block.fromBuffer` should be all you need,  combined with example in `blkdat-stream` README.

**Comment by tabz11** [comment]
HI Dcousens,
I figured out, how to extract the buffer, but my first bytes are not magic numbers instead version number , I m  still wondering I am parsing correctly ???

**Comment by dcousens** [comment]
@tabz11 perhaps https://github.com/bitcoinjs/blkdat-stream/issues/1 is your issue?

**Comment by dcousens** [comment]
@tabz11 the magic byte is consumed by the `blkdat-stream`, and is not required by `Block.fromBuffer`.

**Comment by tabz11** [comment]
many thanks, for your help 
and the field to next to magic number (i.e Block length)?

also for the hash and Merkle root I am getting output with lot of zeros appended
Buffer(140645) [2, 0, 0, 0, 71, 124, 172, 141, …]
Possible Merkle Root------>4cd51133a1087400000000000000000000000000000000000000000000000000
Possible Time Stamp -------->1429650140
Possible Transaction Counter ---->253
Possible Date ----->Tue Apr 21 2015 22:02:20 GMT+0100 (GMT Daylight Time)
>> Read block ( 46 )
Possibly version------>3
Possible Previous Hash ---->>10a7308dce4fc90000000000000000000000000000000000
Possible Merkle Root------>b7db66886aaf1800000000000000000000000000000000000000000000000000

**Comment by dcousens** [comment]
@tabz you should be able to take the `buffer` given by `blkdat-stream` and directly give it to `Block.fromBuffer`

**Comment by tabz11** [comment]
Thanks

**Comment by tabz11** [comment]
can you please advise me on the issue I am getting a lot of padded zeros .
Im using 
var pre_hash_1 = data.readUIntLE(4,32).toString(16);

**Comment by dcousens** [comment]
@tabz11 I'll need to have more context to understand your problem.
