### ISSUE TITLE
Litecoin has invalid BIP32 network constants 

### ISSUE THREAD

**Issue by bluen** [bitcoinjs/bitcoinjs-lib#816]
It seems the network definition for bip32 extended keys of litecoin do not match
the real ones, see https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L133 and https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L134

    base58Prefixes[EXT_PUBLIC_KEY] = boost::assign::list_of(0x04)(0x88)(0xB2)(0x1E).convert_to_container<std::vector<unsigned char> >();
    base58Prefixes[EXT_SECRET_KEY] = boost::assign::list_of(0x04)(0x88)(0xAD)(0xE4).convert_to_container<std::vector<unsigned char> >();

**Comment by dcousens** [comment]
PR accepted.

**Comment by dcousens** [comment]
As per @coblee in https://github.com/bitcoinjs/bitcoinjs-lib/pull/819#issuecomment-315238237,  the fault is at https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L133, not here

**Comment by tonychew1986** [comment]
Just wondered if anyone managed to resolve or find a solution for this?

**Comment by dcousens** [comment]
@tonychew1986 please read https://github.com/bitcoinjs/bitcoinjs-lib/pull/819

**Comment by tonychew1986** [comment]
Thanks @dcousens
