### ISSUE TITLE
Error using transaction fromHex 

### ISSUE THREAD

**Issue by blkmaarx** [bitcoinjs/bitcoinjs-lib#817]
A created (incomplete) transaction, exported to hex, then "reimported" cannot be used. (modelled after the example in basic.js)

To reproduce: 

	var keyPair = bitcoin.ECPair.fromWIF('L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF2BRUVwy');
	
	var tx = new bitcoin.TransactionBuilder();
	tx.addInput('aa94ab02c182214f090e99a0d57021caffd0f195a81c24602b1028b130b63e31', 0);
	
	// store the incomplete tx for reimport later ->
	var incomplete = tx.buildIncomplete().toHex();
	
	// sign the tx.. all will go as we expect
	tx.addOutput('1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK', 15000);
	tx.sign(0, keyPair);
	var signed_in_one_go = tx.build().toHex();
	
	// -> import the incomplete tx from earlier
	var tx = bitcoin.TransactionBuilder.fromTransaction(bitcoin.Transaction.fromHex(incomplete));

	// we cannot sign, something is wrong with this imported tx hex
	tx.addOutput('1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK', 15000);
	tx.sign(0, keyPair);
	var signed_after_fromtx = tx.build().toHex();
	
	// it should all be the same signed hex (console output expected: true, true)
	console.log(signed_in_one_go == signed_after_fromtx);
	console.log(signed_in_one_go == '0100000001313eb630b128102b60241ca895f1d0ffca2170d5a0990e094f2182c102ab94aa000000006b483045022100aefbcf847900b01dd3e3debe054d3b6d03d715d50aea8525f5ea3396f168a1fb022013d181d05b15b90111808b22ef4f9ebe701caf2ab48db269691fdf4e9048f4f60121029f50f51d63b345039a290c94bffd3180c99ed659ff6ea6b1242bca47eb93b59fffffffff01983a0000000000001976a914ad618cf4333b3b248f9744e8e81db2964d0ae39788ac00000000')

Expected output = true, true

It has to do with the copy inputs part of TransactionBuilder.fromTransaction. I believe that the __addInputUnsafe expects a buffer but is not given a buffer with this procedure. 

It can be fixed replacing the // copy inputs part with this (addInput vs __addInputUnsafe):

    transaction.ins.forEach(function (txIn) {
        txb.addInput(txIn.hash, txIn.index)
    })

But that is probably not recommended procedure!

**Comment by blkmaarx** [comment]
After some more looking through the code, it appears the error is created in the prepareInput function under the "else if(input.prevOutType)" clause. 

It all appears to work fine for a (partially) signed transaction, but not for an unsigned transaction. When removing the above clause, it appears to work fine for either transaction. This is probably not a solution though.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/pull/818

@blkmaarx I hope you don't mind I used your test case verbatim :+1:

**Comment by blkmaarx** [comment]
Looks good. Solution works good! :) I tested it a few more times with incomplete transactions and did not notice any further errors.

Test case verbatim can be changed slightly to put the addOutput before the buildIncomplete (saves a line)
