### ISSUE TITLE
Fee is too low. Minimum fee is 1.5 satoshi / B. Is: 0.00

### ISSUE THREAD

**Issue by rawmaterials** [bitcoinjs/bitcoinjs-lib#827]
ref: https://bitcoinjs.org/

i did exactly as in example., **Creating a Transaction**

> var tx = new bitcoin.TransactionBuilder()
> 
> // Add the input (who is paying):
> // [previous transaction hash, index of the output to use]
> var txId = 'aa94ab02c182214f090e99a0d57021caffd0f195a81c24602b1028b130b63e31'
> tx.addInput(txId, 0)
> 
> // Add the output (who to pay to):
> // [payee's address, amount in satoshis]
> tx.addOutput("1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK", 15000)
> 
> // Initialize a private key using WIF
> var privateKeyWIF = 'L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF2BRUVwy'
> var keyPair = bitcoin.ECPair.fromWIF(privateKeyWIF)
> 
> // Sign the first input with the new key
> tx.sign(0, keyPair)
> 
> // Print transaction serialized as hex
> console.log(tx.build().toHex())
> // => 0100000001313eb630b128102b60241ca895f1d0ffca21 ...
> 
> // You could now push the transaction onto the Bitcoin network manually
> // (see https://blockchain.info/pushtx)

and pushed transaction to https://blockchain.info/pushtx and 
i got 

Fee is too low. Minimum fee is 1.5 satoshi / B. Is: 0.00

so where do i set the fee ?

thanks

**Comment by dcousens** [comment]
The fee is the remaining value from your inputs,  not send in your outputs.

You have attempted to send `15000` to `1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK`,  therefore the remaining value would be the value at `aa94ab02c182214f090e99a0d57021caffd0f195a81c24602b1028b130b63e31, 0`  minus `15000`.

`aa94ab02c182214f090e99a0d57021caffd0f195a81c24602b1028b130b63e31, 0` has a value of `15000`,  therefore,  `in:15000 - out:15000 = fee:0`.
You need `in > out`,  and `in - out` will be your `fee`.

**Comment by rawmaterials** [comment]
so i want to transfer whole balance, how much should be fee.

thanks

**Comment by dcousens** [comment]
@rawmaterials as high as you think needed.  
You could make a guess based on data from a place like https://bitcoinfees.21.co/. 

But,  that estimate is typically way too high.

The median fee for the last 12 blocks was 107 satoshis/byte,  with an upper IQR value of 150 satoshis/byte.

**Comment by rawmaterials** [comment]
thank you, looking in to it.
