### ISSUE TITLE
Create a Transaction

### ISSUE THREAD

**Issue by Thinkdiff** [bitcoinjs/bitcoinjs-lib#828]
I found this code for creating custom transaction:
`  it('can create a Transaction', function () {
    var keyPair = bitcoin.ECPair.fromWIF('L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF022673Thinkdiff2BRUVwy')
    var tx = new bitcoin.TransactionBuilder()
    tx.addInput('aa94ab02c182214f090e99a0d57021caffd0f195a81c24602b1028b130b63e31', 0)
    tx.addOutput('1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK', 15000)
    tx.sign(0, keyPair)
    assert.strictEqual(tx.build().toHex(), '0100000001313eb630b128102b60241ca895f1d0ffca2170d5a0990e094f2182c102ab94aa000000006b483045022100aefbcf847900b01dd3e3debe054d3b6d03d715d50aea8525f5ea3396f168a1fb022013d181d05b15b90111808b22ef4f9ebe701caf2ab48db269691fdf4e9048f4f60121029f50f51d63b345039a290c94bffd3180c99ed659ff6ea6b1242bca47eb93b59fffffffff01983a0000000000001976a914ad618cf4333b3b248f9744e8e81db2964d0ae39788ac00000000')
  })`

https://github.com/bitcoinjs/bitcoinjs-lib/blob/d853806/test/integration/basic.js#L50

But I do not know what is "tx.addInput" and "tx.addOutput" and where you generated these hash addresses:

- "L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF022673Thinkdiff2BRUVwy

- aa94ab02c182214f090e99a0d57021caffd0f195a81c24602b1028b130b63e31

- 1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK

Could you please express it for me?

**Comment by dcousens** [comment]
@Thinkdiff do you know how to use Javascript?

**Comment by Thinkdiff** [comment]
Yes, sure I`m using it for many years.
Come on please you did not explain it perfectly!! for this purpose should I use the block: "can generate an address from a SHA256 hash"

if yes, for the random world is there any limitation? like:"correct horse battery staple"

and what do these mean:
- bitcoin.ECPair.fromWIF
- tx.addInput 
- tx.addOutput
- and the numbers in tx object after hash string such as "0" and "15000" 
- build().toHex

Did you describe these definitions yet? Is there any documentation and example?

**Comment by afk11** [comment]
There are certainly examples, tests count as those. You should click around the project to learn about it's structure first before asking people to explain each function call.

**Comment by dcousens** [comment]
> bitcoin.ECPair.fromWIF
https://en.bitcoin.it/wiki/Wallet_import_format

> tx.add*
https://en.bitcoin.it/wiki/Transaction

> and the numbers in tx object after hash string such as "0" and "15000"

`0` was for the prevtxout index (`vout`).
`15000` was the output value in satoshis.

> tx.build().toHex()
The abstraction used was `TransactionBuilder`.
https://en.wikipedia.org/wiki/Builder_pattern
