### ISSUE TITLE
Generate uncompressed key

### ISSUE THREAD

**Issue by Beardcoding** [bitcoinjs/bitcoinjs-lib#829]
How can I generate uncompressed address?
This method outputs compressed version only:
`keyPair.getAddress()`

Thanks!

**Comment by dcousens** [comment]
``` js
keyPair.compressed = true/false
keyPair.getAddress()
```

**Comment by dcousens** [comment]
Or,  from the start.

`ECPair.makeRandom({ compressed: false })`

**Comment by Beardcoding** [comment]
Awesome, many thanks!
