### ISSUE TITLE
iOS browserify

### ISSUE THREAD

**Issue by rubensayshi** [bitcoinjs/bitcoinjs-lib#830]
the README says "NOTE: If you expect this library to run on an iOS 10 device, ensure that you are using buffer@5.0.5 or greater."
I assume that is for the Buffer.prototype.reverse issue that I'm running into, but it doesn't seem to actually fix it ...
also I don't see anything in the buffer package that indicates a fix for the missing reverse method, or was that about Buffer.from? 

`Uint8Array` doesnt have `reverse` in my iOS emulator.

**Comment by dcousens** [comment]
https://github.com/feross/buffer/search?q=5.0.5&type=Issues&utf8=%E2%9C%93

**Comment by rubensayshi** [comment]
npm -g ls | grep browserify
```
├─┬ browserify@14.4.0

```

npm -g ls | grep buffer
```
│ ├─┬ buffer@5.0.6
│ │ │ │ └── buffer-xor@1.0.3
│ │ ├── is-buffer@1.1.5
│ │ ├── safe-buffer@5.1.1
│ │ └── to-arraybuffer@1.0.1
│ │ │   ├─┬ buffer@4.9.1
│ │ │   │ │ │ └── buffer-xor@1.0.3
│ │ │   │ ├── is-buffer@1.1.4
│ │ │   │ ├── buffer-shims@1.0.0
│ │ │   │ └── to-arraybuffer@1.0.1
│ │ │ │ ├── buffer-shims@1.0.0
│ │     │ └── stream-buffers@0.2.6
│ │ │ ├── safe-buffer@5.1.1
│ │ │ │ ├── buffer-shims@1.0.0
│ │ │ │ │ └── is-buffer@1.1.4
│ │ │ │ ├── buffer-shims@1.0.0
│ │ │ │   ├─┬ buffer@3.6.0
│ │ │ │   │ │ │ └── buffer-xor@1.0.3
│ │ │ │   │ ├── is-buffer@1.1.4
npm ERR! peer dep missing: eslint@^3.19.0, required by eslint-config-react-app@1.0.5
npm ERR! peer dep missing: eslint-plugin-flowtype@^2.33.0, required by eslint-config-react-app@1.0.5
npm ERR! peer dep missing: eslint-plugin-import@^2.2.0, required by eslint-config-react-app@1.0.5
npm ERR! peer dep missing: eslint-plugin-jsx-a11y@^5.0.3, required by eslint-config-react-app@1.0.5
│ │ │ │ │ ├── buffer-shims@1.0.0
│ │ │ │   │ ├── buffer-shims@1.0.0
│   │ ├── buffers@0.1.1
│   │ └── buffers@0.1.1
│ │ │   ├── buffer-shims@1.0.0
│ │ │   │ └── safe-buffer@5.0.1
│ │ │   │ └── is-buffer@1.1.5
│ │   │ ├── buffer-shims@1.0.0
│ │   │ │ └── safe-buffer@5.0.1
│ │ ├── buffer-shims@1.0.0
│ │ │   │ ├── safe-buffer@5.0.1
│ │     │ │ │ │ └── is-buffer@1.1.4
│ │   │     │ ├── buffer-shims@1.0.0
│   │   │ ├── safe-buffer@5.0.1
│ │ │ │ │ ├── buffer-shims@1.0.0
  │ ├── safe-buffer@5.0.1
  │ │ ├── buffer-shims@1.0.0
```

```
// test.js

var b = Buffer.from('00ffee00ffee', 'hex')

alert(b.toString('hex'))
alert(b.reverse().toString('hex'));
alert(typeof b.reverse);
```


running this on iPhone6 iOS8 and iOS9 simulator fails with reverse being undefined, iOS10 is fine, can't we bring back buffer-reverse?

**Comment by dcousens** [comment]
@rubensayshi I think this is the wrong repository to report this... maybe https://github.com/feross/buffer ?

**Comment by rubensayshi** [comment]
https://github.com/feross/buffer/issues/167

reported it there, I guess you prefer waiting for a fix there instead of brining back buffer-reverse?

**Comment by dcousens** [comment]
@rubensayshi ideally yes,  if there is such an issue,  upstream is the best place to resolve it.
Do you agree?

**Comment by dcousens** [comment]
@rubensayshi apparently it isn't upstream.
Enforcing `buffer-reverse` through your stack,  is going to be painful.

I think drop iOS<10.

**Comment by rubensayshi** [comment]
I'd strongly prefer bringing back `buffer-reverse` then ...

from our business perspective ~2% users is too much to ignore for us, as a FOSS project you can be a bit more "focused on the future instead of the past", but the cost is pretty low in this case I think

**Comment by dcousens** [comment]
@rubensayshi is `bitcoinjs-lib` the only place to change?

**Comment by rubensayshi** [comment]
yes, reversing buffers is not something that is done often, if at all ;)

**Comment by dcousens** [comment]
@rubensayshi PR it up

**Comment by dcousens** [comment]
@rubensayshi and please submit a `safe-buffer` PR to https://github.com/crypto-browserify/buffer-reverse

**Comment by dcousens** [comment]
I too have experienced this on my stack,  but I opted to drop the support.
It wans't specifically a `bitcoinjs-lib` issue,  as I had other libraries using `Buffer.prototype.reverse` too.
