### ISSUE TITLE
buildIncomplete fails for unsigned P2SH inputs

### ISSUE THREAD

**Issue by Melvillian** [bitcoinjs/bitcoinjs-lib#833]
I am trying to write test cases for sending an unsigned transaction P2SH transaction to my service, but I'm unable to get the hex because the `buildIncomplete` function fails with a strange error. See below for bug repro:

```
var b = require('bitcoinjs-lib');
var inp = Buffer.from('010000000173120703f67318aef51f7251272a6816d3f7523bb25e34b136d80be959391c100000000000ffffffff0100c817a80400000017a91471a8ec07ff69c6c4fee489184c462a9b1b9237488700000000', 'hex') // arbitrary P2SH input
var inpTx = b.Transaction.fromBuffer(inp)

var txb = new b.TransactionBuilder(b.networks.testnet)
txb.addInput(inpTx, 0)
txb.addOutput(b.address.toOutputScript('2NAkqp5xffoomp5RLBcakuGpZ12GU4twdz4', b.networks.testnet), 1e8) // arbitrary output

txb.buildIncomplete()
```

produces the error

```
Error: Impossible to sign this type
    at buildInput (/Users/alex/dev/bitcoinjs-lib/src/transaction_builder.js:408:13)
    at /Users/alex/dev/bitcoinjs-lib/src/transaction_builder.js:614:18
    at Array.forEach (native)
    at TransactionBuilder.__build (/Users/alex/dev/bitcoinjs-lib/src/transaction_builder.js:611:15)
    at TransactionBuilder.buildIncomplete (/Users/alex/dev/bitcoinjs-lib/src/transaction_builder.js:600:15)
    at repl:1:5
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)

```

Based on reading transaction_builder.js it looks like the `buildInput` function assumes the input's `redeemScriptType` would have been set. I would write up a PR but don't know enough about bitcoinjs-lib to know if this is a simple fix or requires a deeper reworking of the txn build/sign flow. Suggestions appreciated!

**Comment by Melvillian** [comment]
By the way this is running bitcoinjs-lib v3.1.1 on node v6.9.5

**Comment by dcousens** [comment]
@Melvillian to sign it,  you need a `redeemScript`,  however,  you aren't even trying to sign it,  so this shouldn't be failing.

`buildInput` is making the assumption for P2SH that you intended for it to be signed... when you don't (not yet).

**Comment by dcousens** [comment]
I'll get to this ASAP,  @Melvillian there could be a day or two delay.

**Comment by Melvillian** [comment]
I fixed my problem by adding `&& !allowIncomplete` to line 407 of transaction_builder.js
