### ISSUE TITLE
bitcoinjs-lib to PIVX

### ISSUE THREAD

**Issue by EvandroZanatta** [bitcoinjs/bitcoinjs-lib#836]
I wanted to adapt this code to PIVX (PIVX is a fork of Bitcoin). Does changing the daemon make it work with PIVX?

**Comment by dcousens** [comment]
@EvandroZanatta I think you may have this library confused with something else?
`bitcoinjs-lib` is a library for interop with Bitcoin,  but it does not have any code to interact with the network layer.

**Comment by EvandroZanatta** [comment]
Yes, I got confused, sorry.
