### ISSUE TITLE
Check Address Balance?

### ISSUE THREAD

**Issue by deniskrop** [bitcoinjs/bitcoinjs-lib#837]
Is there a way to check the balance of an address?

**Comment by dcousens** [comment]
Duplicate of https://github.com/bitcoinjs/bitcoinjs-lib/issues/776, https://github.com/bitcoinjs/bitcoinjs-lib/issues/809, https://github.com/bitcoinjs/bitcoinjs-lib/issues/678

**Comment by deniskrop** [comment]
@dcousens  There is no way to do it without an external API? I have my own node.

**Comment by dcousens** [comment]
@deniskrop if you have your own node,  you can retrieve related transactions to determine the balance of an address. 
If you want to be able to simply ask `bitcoind` "what is the balance of XXXXXXXXXXXX",  I'm afraid it isn't so simple.

See https://github.com/bitcoinjs/indexd for a module that provides an address-index,  which,  if set up,  would allow you to retrieve related transactions by their related script.

**Comment by afk11** [comment]
@dcousens maybe should have an FAQ for this?

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bitcoinjs-lib/issues/822 for task and appropriate example to be added
