### ISSUE TITLE
How to broadcast a transaction?

### ISSUE THREAD

**Issue by vekexasia** [bitcoinjs/bitcoinjs-lib#839]
Hello,

I'm new to BTC and wouldn't want to screw things up. Lets say I can craft and sign a new tx with this library. How do I send it to the network?

**Comment by arunoda** [comment]
Use this: https://blockchain.info/pushtx
or
https://blockr.io/tx/push
or similar.

(You can push with multiple sites and it's safe)

**Comment by dcousens** [comment]
If you have a `bitcoind` node: [`sendrawtranscation`](https://bitcoin.org/en/developer-reference#sendrawtransaction)

**Comment by vekexasia** [comment]
Hello @arunoda it seems i cant find an API for any of that.

just regular http form.

**Comment by dcousens** [comment]
```
curl -d '{"hex":"TX_HASH"}' http://btc.blockr.io/api/v1/tx/push
```

From https://blockr.io/documentation/api

**Comment by dcousens** [comment]
```
POST https://blockchain.info/pushtx
```

For blockchain.info

**Comment by murphman300** [comment]
half the links on this thread points to Coinbase's API on my end..
So just to be clear, your official recommendation is to use a third-party API to broadcast?

**Comment by dcousens** [comment]
> So just to be clear, your official recommendation is to use a third-party API to broadcast?

3rd party,  1st party,  it doesn't matter,  `bitcoinjs-lib` doesn't connect to the bitcoin network,  so you need to use something else.  But that something can be your own `bitcoind` node.

**Comment by murphman300** [comment]
Ahh alright, makes more sense now. Still getting the hang of things :)

**Comment by dabura667** [comment]
sendrawtransaction RPC call or cli.
