### ISSUE TITLE
Help me recover my BitGo private keys

### ISSUE THREAD

**Issue by jason0027** [bitcoinjs/bitcoinjs-lib#842]
hi please help i want to recover my btc in bitgo now i come here for help but programming language i dont understand it please if anyone can help to instail all those codes and recover my codes will give a percentage from the coins please

**Comment by dcousens** [comment]
@jason0027 please take caution with any information you post here.

Do not post anything that remotely looks like a bitcoin address,  or like a 12 word mnemonic.

If you can outline your issue,  I'm sure users here [including myself] can help post any necessary code that may help you without exposing any private details.

**Comment by dcousens** [comment]
@bpdavenport @jlopp @RobertBaron

**Comment by jason0027** [comment]
actually i forgot my password and i dont have private key to recover it so my coins is stuck in bitgo i dnt even knw where to sart in order to get my coins please help if anyone have idea on how to get those coins moved to another wallet please

**Comment by afk11** [comment]
I suggest you start with contacting BitGo if you haven't - they might be able to recover your coins for you, or advise how to get your private key so you can recover your coins yourself. 

You're in the right place if you can get the private keys, or can work out how to decrypt/whatever to get your private keys.

**Comment by jason0027** [comment]
I contected them several times they said they cant help me the private keys i have for the wallet theres no xprv wht they need i want and if i can check all my wallets in Bitgo are 3 the passwords and private keys i have them and works perfect but if i want to transfere the coins from user acc the password says wrong but other user acc the password works well the main website where the user created the wallet is now down so i want to send funds through bitgo cause tht website were using bitgo API to eccept bitcoins now i dont have where to start to give the user her bitcoins im really in trouble any help please i will apriciate tht

**Comment by afk11** [comment]
I don't really know what to say. If you don't know your password, or don't have _any_ copy of the private keys, there's not much anyone can do to help. 

I see that BitGo has a recovery tool however, which means with your password and Recovery Card, you should be able to gain access to your account.

**Comment by jason0027** [comment]
I have all my key cards with me but in the key card theres no xprv to resert the password

**Comment by dcousens** [comment]
@jason0027 I don't think we can help you if you don't have any private key data.
I'm going to close this issue as it isn't pertaining to `bitcoinjs-lib`.

**Comment by heidibit** [comment]
I need help recovering my wallet pasword on bitgo i have full access to my account ans have several other wakkets but one of them says thw password is incorrect and the are all the same. Please help me
