### ISSUE TITLE
How to propagate transaction to BTC network

### ISSUE THREAD

**Issue by nihiluis** [bitcoinjs/bitcoinjs-lib#843]
I created a transaction. How do I insert this into the BTC network?

I think I read somewhere that the CB API of Blocktrail will be scrapped. Are there alternatives?

Can I get the transaction in a format that is accessible for a RPC client?

**Comment by afk11** [comment]
Blocktrails CB API is still there IIRC. 

https://github.com/bitcoinjs/bitcoinjs-lib/issues/839 is a related issue - we described some quick ways to broadcast transactions using public API's

**Comment by dcousens** [comment]
I suspect this is a direct duplicate of #839.

And yes,  I suspect this an example of an example we'll add that will be "skipped",  but good to show users :smiley:
