### ISSUE TITLE
Expected Buffer, got Buffer

### ISSUE THREAD

**Issue by ddabek** [bitcoinjs/bitcoinjs-lib#847]
![screen shot 2017-08-14 at 7 50 57 pm 1](https://user-images.githubusercontent.com/10568692/29284226-1e2ab6a8-812a-11e7-928c-259da23e2785.png)

Trying the OP_RETURN example and getting this error:

> message : "Expected Buffer, got Buffer"

`var data = Buffer.from('bitcoinjs-lib', 'utf8')`
`var dataScript = bitcoin.script.nullData.output.encode(data)`

**Comment by dcousens** [comment]
Browserified?

**Comment by vkjvivek7** [comment]
I am getting same error while using bip39 can you please tell me how resolved this error.
getRoot() {
const mnemonic = bip39.generateMnemonic();
const seed = bip39.mnemonicToSeedSync(mnemonic);
const root = bip32.fromSeed(seed, bitcoin.networks.testnet)
return root;
}

But I am getting this error in line where I am trying to get root bip32.fromSeed(seed, bitcoin.networks.testnet)

Error: Expected Buffer, got Buffer

**Comment by junderw** [comment]
are you using multiple bundles?

one for bip32 and bitcoinjs-lib and one for bip39?
