### ISSUE TITLE
How to receive a payment

### ISSUE THREAD

**Issue by HeilShuckle** [bitcoinjs/bitcoinjs-lib#848]
I'd like to know how my node js code can detect when a certain address has received a payment and how much btc it got. I can't find this anywhere, so im hoping this can get to you and you can help me out.

**Comment by fanatid** [comment]
You do not need `bitcoinjs-lib` for this. Instead you should use one of bitcoin blockchain API.
https://github.com/bitpay/insight-api/
https://www.blocktrail.com/api/docs
https://blockchain.info/api
http://btc.blockr.io/documentation/api

**Comment by HeilShuckle** [comment]
And so which one of these would you recommend, and how would i go about doing this? I'm a bit of a noob to node js, but I'm trying to learn.

**Comment by dcousens** [comment]
@HeilShuckle please see the example ["Support the retrieval of transactions for an address (3rd party blockchain)"](https://github.com/bitcoinjs/bitcoinjs-lib/blob/ae8422d/test/integration/addresses.js#L52)

**Comment by dcousens** [comment]
For your API,  use any of the above.
Use multiple for higher [but not great] censorship resistance.
