### ISSUE TITLE
Is there a way to get the balance of a transaction from the transaction id?

### ISSUE THREAD

**Issue by HeilShuckle** [bitcoinjs/bitcoinjs-lib#849]
For example, I use a command like 
getTransactionBalance('3acf49df9175856d190748380e45b83d5208a2b7a5745ad7ccff06767b63795a');

and it would return an object that says in some way how much btc was sent/taken from the addresses that had to do with this transaction.

**Comment by clarkmoody** [comment]
A transaction conveys value from its inputs to its outputs. Using bitcoind's `getrawtransaction`, you can see how much bitcoin was sent to each output, and pulling the transaction inputs, you may also see the input amounts (and compute fees).

Public block explorers also provide this information through their APIs.
