### ISSUE TITLE
Add TransactionBuilder support for Coinbase Transactions

### ISSUE THREAD

**Issue by milewski** [bitcoinjs/bitcoinjs-lib#850]
Im trying to create a Coinbase Transaction but i get this message... now im confuse if this lib is not able to generate a coinbase transaction or if some input i gave is wrong?

**Comment by dcousens** [comment]
@milewski `TransactionBuilder` doesn't support creating coinbase transactions directly.
PR accepted to add that feature/tests,  but otherwise you can manually create it using `Transaction`.
