### ISSUE TITLE
Multibyte pubKeyHash

### ISSUE THREAD

**Issue by iancoleman** [bitcoinjs/bitcoinjs-lib#865]
ZEC uses 0x1CB8 for the pubkeyhash

But the type is forced to be Uint8 so throws an error.

Is this something that can be worked around or will it require changes to bitcoinjs-lib?

**Comment by dcousens** [comment]
Only changes required would be in `fromBase58Check` and `toBase58Check`,   but we'd be forcing those functions to be variable length.

I think I can safely say this is something fork would cover,  but, the changes are tiny.

If we add support for https://github.com/bitcoinjs/bitcoinjs-lib/issues/513 - then doing this is trivial as the `pubKeyHash` constant could be defined strictly as a fixed length `Buffer`.
