### ISSUE TITLE
BTC Sent to BCH ADDRESS

### ISSUE THREAD

**Issue by 12011986** [bitcoinjs/bitcoinjs-lib#876]
I have sent some bitcoins from  BTC coinbase to a CEX.IO BCH account. I was trying to contact CEX.IO and they are not very helpful, the last email that I got from them they were asking for screenshots of everything.However, that was last week and now they went silent.  I asked them if they could provide the private key of my BHC address and they are not willing to do it. 

How could I be able to get my private key? is anyway to key pair it? What should I do?

**Comment by kabutosamourai** [comment]
Unfortunately, Bitcoin Cash's irresponsible use of identical addresses to Bitcoin means that this sort of error will continue to happen. Your only hope is to continue with CEX.io support.

Once you obtain the private key, you can use this library to construct a transaction. Until then, this is not the proper venue to obtain support.
