### ISSUE TITLE
txId for TransactionBuilder

### ISSUE THREAD

**Issue by wendelmaques** [bitcoinjs/bitcoinjs-lib#878]
In the example, the txId (addInput) is text string. How I can generate a valid txId for my transactions. Can I use random text as txId?

**Comment by wendelmaques** [comment]
Hi, I found de solution here: https://bitcoin.stackexchange.com/questions/49260/how-to-use-bitcoinjs-lib-with-regtest

**Comment by wendelmaques** [comment]
Never mind, found another way with bitcoin-core

**Comment by dcousens** [comment]
> How I can generate a valid txId for my transactions

Pre-existing,  or `bitcoinjs-lib` `Transaction`s?

**Comment by wendelmaques** [comment]
From a new bitcoinjs-lib transaction. 
Example: I want is to move funds from a main-wallet to dozens of wallets. Is simple faucet system.

**Comment by dcousens** [comment]
`.getId()`?
