### ISSUE TITLE
Implement message Signing/Verifying for SegWit P2SH addresses

### ISSUE THREAD

**Issue by prusnak** [bitcoinjs/bitcoinjs-lib#880]
For TREZOR we implemented a way how to Sign and Verify SegWit P2SH addresses. This is achieved by introducing extra `v` values used during signing.

Currently the following are used:

* 27-30 uncompressed pubkey (base58)
* 31-34 compressed pubkey (base58)

We added the following:

* 35-38 p2sh segwit pubkey (base58)
* 39-42 segwit pubkey (bech32)

[Unit tests for reference](https://github.com/trezor/python-trezor/blob/master/tests/device_tests/test_msg_signmessage_segwit.py)

**Comment by dabura667** [comment]
Affected places: (Plus fixtures and tests needed)

https://github.com/bitcoinjs/bitcoinjs-message/blob/a2943623118b28766b7e783ff8e650a081245c9a/index.js

https://github.com/bitcoinjs/bitcoinjs-lib/blob/56dfb873d3f05817e19befa976592bc0f371a6d3/src/ecsignature.js

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-message/issues/6 (aka, moved the issue to `bitcoinjs-message`)
