### ISSUE TITLE
Default TransactionBuilder Transaction version

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#881]
Bitcoin Core defaults to `0x02`.

What should we do?

**Comment by afk11** [comment]
We don't yet support signing CSV or stuff where version 2 is required (BIP112/BIP68), so we could save it until then.

**Comment by dabura667** [comment]
I think version 2 defaulting in Bitcoin Core is to help prevent fingerprinting of transactions to track lightning usage etc.

I say we should default to 2 to assist in obfuscation.

**Comment by afk11** [comment]
@dabura667 Also a fair point, but our transaction's don't set a locktime, so are distinguishable from Bitcoin Core :)

**Comment by dcousens** [comment]
> I say we should default to 2 to assist in obfuscation.

My reasoning.

@afk11 speak for yourself,  but I set locktime :)

**Comment by dcousens** [comment]
Assigned to `4.0.0`

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/issues/957
