### ISSUE TITLE
Getting UTXO/Signing

### ISSUE THREAD

**Issue by wmpedersen** [bitcoinjs/bitcoinjs-lib#885]
I'm building a simple HD wallet with P2SH-P2WSH support and I can generate the addresses fine, but I'm having trouble understanding how to determine which addresses to sign with. Do I have to iterate over the whole account and find the last UTXO and keep adding them if I don't have enough to cover the spend?

Is there a better way to determine what utxo to use?

**Comment by dabura667** [comment]
Store the HD path with the address, then you can append the hd path to the unspent info and pass it along to your app which will generate the keys according to the path.

**Comment by dcousens** [comment]
@wmpedersen if you use [`bip32-utils`](https://github.com/bitcoinjs/bip32-utils#bip32-chains),  you can use `chain.derive(address)` to get the `HDNode` for an address.

No lookup exists in `bitcoinjs-lib` as is.
