### ISSUE TITLE
GPG sign commits and tags

### ISSUE THREAD

**Issue by junderw** [bitcoinjs/bitcoinjs-lib#887]
@dcousens @afk11 

1. sign each commit and tag automatically with `git config --global commit.gpgsign true` `git config --global tag.gpgsign true`
2. When merging a pull request, do so by command line by adding their repo as a remote `git remote add username git:.....` then `git fetch username` then `git checkout master` and `git merge -S username/branchname` the -S will sign the merge commit itself which maintains all the signed commits (if any) in the branch. (this could be made into a bash alias, add remote > fetch > merge)

`git config --local user.signingkey DEADBEE` can be used globally or locally using --global --local to specify which GPG key you want to use locally to sign. (make sure the key shows up in gpg -K (or gpg2 -K) ) also `git config --global gpg.program gpg2` or gpg to tell git which one to use (in case you don't have a key imported in one keyring or the other.

Then the next step would be to get someone in the community to verify and sign your keys. And maybe place your pubkeys in the github repo for redundancy (dcousens-pubkey.asc etc. etc.)

**Comment by dcousens** [comment]
Can we merge this thread with the other, or vice versa?
I'm happy to find a process that works for us and put it in place.

**Comment by junderw** [comment]
Merge with #886 and rename.
