### ISSUE TITLE
Double-underscore TransactionBuilder (and other) internals

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#888]
`TransactionBuilder.prototype.tx` was never for public consumption,  and it has changed several times between releases.
I think it should be changed to `.__tx` to eliminate confusion,  and avoid code breakage for users (which has happened previously).

**Comment by dcousens** [comment]
Alternatively,  lets use closures?
@afk11 @junderw thoughts?

**Comment by junderw** [comment]
Closures could be good... but one downside is it makes debugging slightly harder.

Also, I am always afraid that closures will break in some version of Node... lol

**Comment by dcousens** [comment]
>  I am always afraid that closures will break in some version of Node... 

Example? Or simply a fear?

**Comment by junderw** [comment]
irrational fear. closures just FEEL hacky and like one of those things that nodeJS devs will say "oops, we broke closures... oh well."

**Comment by dcousens** [comment]
Hilariously,  I think closures are more first-class to Javascript then prototypical functions.

**Comment by junderw** [comment]
haha. Then closures it is!

**Comment by dcousens** [comment]
Considering this a breaking change.

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bitcoinjs-lib/pull/1038
