### ISSUE TITLE
Bitgo issue

### ISSUE THREAD

**Issue by jason0027** [bitcoinjs/bitcoinjs-lib#889]
Im still struggling to get my coins i got another article here saying tht if i can get a developer to create a third part eccess token to my bitgo acc tht will have full admin excess of the main bitgo acc i can sebd the coins tht is in the account tht need a xprv key to recover it how true is tht please help to get my coins out i do have all my keys i got while registering but the thing is i didnt get any key tht start with xprv all my keys start with xpub so im confused why Bitgo request a key tht i didnt receive even at the time for sighning up

**Comment by dakk** [comment]
I think this is not the right  place for your question

**Comment by dcousens** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/issues/874
https://github.com/bitcoinjs/bitcoinjs-lib/issues/842

Closing as duplicate.
