### ISSUE TITLE
Use Trezor to sign BIP49 SegWit Multisig raw transaction?

### ISSUE THREAD

**Issue by hoangan** [bitcoinjs/bitcoinjs-lib#896]
Is there a way to sign BIP49 Segwit Multisig raw transaction using Trezor?

Thanks

**Comment by afk11** [comment]
Yea this is pretty easy with the library. We don't have examples for such a specific case though, though there are some in the readme that should be enough to get you started. 

BIP49 is just BIP32, with a specific type of script being used for the address, & transaction signing is unchanged. Check the BIP32 examples, the BIP49 BIP, and the segwit address examples, then the transaction signing examples.

**Comment by dcousens** [comment]
There is even a [BIP49 derivation example](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/bip32.js#L66).

Combine that with a [multi-sig transaction example](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L183),  and you're good to go.

**Comment by hoangan** [comment]
Thanks guys.
