### ISSUE TITLE
Issue when using browserify instructions on bitcoinjs.org

### ISSUE THREAD

**Issue by mandelmonkey** [bitcoinjs/bitcoinjs-lib#902]
I used the compile for browser instructions on bitcoinjs.org

and the follow error was shown

`as-MacBook-Pro:test a$ sudo npm install -g browserify uglify-js
/usr/local/bin/uglifyjs -> /usr/local/lib/node_modules/uglify-js/bin/uglifyjs
/usr/local/bin/browserify -> /usr/local/lib/node_modules/browserify/bin/cmd.js
+ uglify-js@3.1.1
+ browserify@14.4.0
added 135 packages in 8.086s
as-MacBook-Pro:test a$ browserify -r bitcoinjs-lib -s bitcoin | uglifyjs > bitcoinjs.min.js
Parse error at 0:96,4
let ALPHABET = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l'
    ^
ERROR: Unexpected token: name (ALPHABET)
    at JS_Parse_Error.get (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:79:23)
    at fatal (/usr/local/lib/node_modules/uglify-js/bin/uglifyjs:268:52)
    at run (/usr/local/lib/node_modules/uglify-js/bin/uglifyjs:225:9)
    at Socket.<anonymous> (/usr/local/lib/node_modules/uglify-js/bin/uglifyjs:163:9)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)`

**Comment by junderw** [comment]
Hey Christian.

What version of node are you using? Try switching nvm to use v7

**Comment by mandelmonkey** [comment]
seems my handle gave me away
am on v5.0.3 so will upgrade and give it another go thanks!

**Comment by dcousens** [comment]
@mandelmonkey it appears that `uglify-js` doesn't support ES6 `let` statements.
In repository,  we track LTS node versions for tracking backwards compatibility.

I'd recommend using `--transform [ babelify ]` on your browserify build step to downgrade to ES5.

I think this should be something we outline in the README,  with steps.
Thoughts @bitcoinjs/committers ?

**Comment by junderw** [comment]
I agree. Let’s. ;-)

**Comment by dcousens** [comment]
Closing in favour of #903

**Comment by mandelmonkey** [comment]
thanks I managed to browserify using the github readme instructions
https://github.com/bitcoinjs/bitcoinjs-lib#browser

**Comment by dcousens** [comment]
@mandelmonkey was #903 helpful
?

**Comment by mandelmonkey** [comment]
Yes thank you!

**Comment by tweeres04** [comment]
Hey @mandelmonkey would you mind sharing what you did to get yours running? I'm still having that issue with the bech32 lib not compiling to es5.

My script is `browserify src/index.js --transform [ babelify --presets [ env ] ] --standalone bitcoinjs-lib > bin/bitcoinjs-lib.js`

**Comment by dcousens** [comment]
> EDIT: I got it to work for now by making it a global transform.

can you elaborate?

**Comment by mandelmonkey** [comment]
@tweeres04 I know that if your node version is too low it wouldn't support the 'let'

**Comment by tweeres04** [comment]
@dcousens @mandelmonkey It looks like by default browserify transforms only apply to files at or below the directory level of the entry file. The bech32 library (the one in es6 that was causing me problems) is one level up from BitcoinJS's `src/index.js`, so by adding the `--global` flag to my transform I was able to get it to compile.

For those who encounter this issue, my full script for compiling is `browserify src/index.js --t [ babelify --global --presets [ env ] ] --standalone bitcoinjs-lib | uglifyjs --compress --mangle reserved=['BigInteger,ECPair,Point'] > bin/bitcoinjs-lib.min.js`

**Comment by dcousens** [comment]
Ah,  you are doing a `--standalone` compilation,  that explains it.
I suspect many users are not doing `--standalone`,  but simply using `browserify` at the top of their stack.

**Comment by tweeres04** [comment]
Right. Yeah I have an existing project with webpack so I'm compiling just BitcoinJS with browserify.
