### ISSUE TITLE
got error from Transaction.fromHex ()

### ISSUE THREAD

**Issue by KanoczTomas** [bitcoinjs/bitcoinjs-lib#912]
Hello,

my app crashed and it seems from the trace that Transaction.fromHex () is to blame. See the crash output:
```
<--- Last few GCs --->
 
17005074 ms: Mark-sweep 697.2 (738.7) -> 697.1 (738.7) MB, 5794.1 / 4 ms [allocation failure] [GC in old space requested].
17010896 ms: Mark-sweep 697.1 (738.7) -> 697.1 (738.7) MB, 5821.9 / 4 ms [allocation failure] [GC in old space requested].
17016691 ms: Mark-sweep 697.1 (738.7) -> 697.0 (738.7) MB, 5790.5 / 7 ms [last resort gc].
17022548 ms: Mark-sweep 697.0 (738.7) -> 695.9 (738.7) MB, 5857.2 / 4 ms [last resort gc].
 
 
<--- JS stacktrace --->
 
==== JS stack trace =========================================
 
Security context: 0xb4b258f9 <JS Object>
    1: fromBuffer [/home/btc/raspinodemon/node_modules/bitcoinjs-lib/src/transaction.js:~49] [pc=0x21b528a8] (this=0x27ce95fd <JS Function Transaction (SharedFu
nctionInfo 0x26f186d1)>,buffer=0x2f2b7c8d <an Uint8Array with map 0x39d151ad>,__noStrict=0xb4b08099 <undefined>)
    2: arguments adaptor frame: 1->2
    3: fromHex [/home/btc/raspinodemon/node_modules/bitcoinjs-lib/src/transaction.js:~140] ...
 
```
running node v4.8.4,  bitcoinjs-lib 3.1.1 (from npm).

I know am not running the latest node version, still would like to at least know what that error means. I can not reproduce the error though sadly.

**Comment by junderw** [comment]
This stack trace is not very helpful... If you can't reproduce it, it is probably a fluke memory error...

Please let us know if you can reproduce it and send any additional information you find.

Thanks for the report.

**Comment by dcousens** [comment]
Will have to close,  we have no way of re-producing this... maybe it could have been an OOM?If you have any kind of reproduction steps,  please don't hesitate to re-open :+1:
