### ISSUE TITLE
Transaction.fromHex() Error: RangeError: Index out of range

### ISSUE THREAD

**Issue by enkrypter** [bitcoinjs/bitcoinjs-lib#913]
Not really an issue - I am sure I am doing something wrong.But not sure where I could ask thi question.

I am creating a new transaction for an altcoin from a local wallet, and looking to sign the resultant transaction with a supplied private key on the client-side using bitcoinjs.
When run the script below, I get a RangeError: Index out of range error:

Script (I have already defined network, privkey and bitcoin):
var txhex = "01000000da2dd359016d5760b013046c56f2ea0c06104458b074dadc2e0e96db7a025d1332db5e27d50000000000ffffffff012c000000000000001976a914e813d471ec99965c1341fdfc66c89ec1707ad6c588ac00000000"
var transaction = bitcoin.Transaction.fromHex(txhex, network);

This results in:
RangeError: Index out of range
    at checkOffset (buffer.js:835:11)
    at Buffer.readUInt32LE (buffer.js:897:5)
    at readUInt32 (C:\Dev\coinjs\app1\node_modules\bitcoinjs-lib\src\transaction
.js:57:20)
    at Function.Transaction.fromBuffer (C:\Dev\coinjs\app1\node_modules\bitcoinj
s-lib\src\transaction.js:110:17)
    at Function.Transaction.fromHex (C:\Dev\coinjs\app1\node_modules\bitcoinjs-l
ib\src\transaction.js:141:22)
    at repl:1:39
    at realRunInThisContextScript (vm.js:22:35)
    at sigintHandlersWrap (vm.js:98:12)
    at ContextifyScript.Script.runInThisContext (vm.js:24:12)
    at REPLServer.defaultEval (repl.js:313:29)

Can anyone please tell me how I could resolve this? Thanks very much, in advance!

**Comment by dcousens** [comment]
Gnerally that means the transaction is malformed...
How did you generate `txhex`?

**Comment by enkrypter** [comment]
Thanks for your prompt response!
I am sending a call to the chain (via php) to build the transaction: 
createrawtransaction '[{"txid":<transaction,"vout":0}]' '{"<recipient address>":44}'
The hash is what I now attempt to sign using bitcoinjs.
Thanks again!

**Comment by enkrypter** [comment]
Just to add to my comment above:
I added my altcoin details (messagePrefix, bip32 etc) to network.js. 
I started with attempting to create and sign the tracsaction from bitcoinjs:

var bitcoin = require('bitcoinjs-lib');
var network = bitcoin.networks.<altcoin name>;

var key = bitcoin.ECPair.fromWIF(<private key>, network);
var tx = new bitcoin.Transaction(network);

tx.addInput(<transaction id>, 0);
tx.addOutput(<recipient address>,  88)

tx.sign(0, key)
console.log(tx.toHex())

However, when I try to send the resultant signed transaction from the above on the chain, it spits a code -22 error, suggesting (as you have, above) that the signedtransaction is malformed.

**Comment by junderw** [comment]
which coin? Don't just assume all coins are exactly like bitcoin.

**Comment by junderw** [comment]
I can tell from your original issue, the txincount varint is missing. This tells me the altcoin you're using is probably using a different transaction serialization method.

Based on my observations bitcoinjs-lib can not support your altcoin out of the box. You will need to fork bitcoinjs-lib and redo some of the transaction serialization and deserialization methods as well as sighash generation...

but then of course, I don't know, because I don't know which altcoin it is.

Which altcoin is it?

**Comment by enkrypter** [comment]
Thanks, @junderw!
I will fork the ibrary and do as you suggested.
The coin is blakestar (BLAS). Below are the network details, if it helps:
blakestar: {
    messagePrefix: 'Blakestar Signed Message:\n',
    bip32: {
      public: 0x0481DAAE,
      private: 0x0482A1A4
    },
    pubKeyHash: 0x1a,
    scriptHash: 0x5,
    wif: 0x9a
  }

Thanks again - any other suggestions (based on the above coin info) appreciated!

**Comment by dabura667** [comment]
Ahhhhh, I think some other altcoin had a similar issue.

Peercoin or something tried to make a pull request a long time ago, because POS coins use a different transaction format or something.

@dcousens I couldn’t find the pr. Can u?

**Comment by dcousens** [comment]
@dabura667 were you thinking of https://github.com/bitcoinjs/bitcoinjs-lib/pull/428 ?

**Comment by junderw** [comment]
ok so it looks like POS coins put a uint32LE datetime data between the version data and the txin varint.

@enkrypter please check #428 to see one way to allow POS coin signing.

Be aware that you must also encode the sighash preimage correctly as well.

**Comment by enkrypter** [comment]
@junderw, Just working on that now. Thank you, very much appreciated
