### ISSUE TITLE
Add Bitcoin Gold support

### ISSUE THREAD

**Issue by hoshsadiq** [bitcoinjs/bitcoinjs-lib#918]
Is this planned? Will a PR be accepted if I do the implementation? If so, any pointers on where to start?

**Comment by dcousens** [comment]
PRs are welcome,  but they will not be merged.
Like https://github.com/bitcoinjs/bitcoinjs-lib/pull/831,  it will remain open as a PR for visibility for those who need it.   If the fork fails to reach a clear majority,  then we'll probably close any PRs within 6 months.

**Comment by lacksfish** [comment]
#932

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/pull/932
