### ISSUE TITLE
Error #-25: Missing inputs, code=-25

### ISSUE THREAD

**Issue by EasonWang01** [bitcoinjs/bitcoinjs-lib#930]
When broadcast transaction using bitcoinjs signed transaction will result the error code
```
Validation Error: BitcoindException(super=com.neemre.btcdcli4j.core.BitcoindException: Error #-25: Missing inputs, code=-25)
```

```js
var bitcoin = require('bitcoinjs-lib')
var keyPair = bitcoin.ECPair.fromWIF('L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF2BRUVw1')
var tx = new bitcoin.TransactionBuilder()

tx.addInput('aa94ab02c182214f090e99a0d57021caffd0f195a81c24602b1028b130b63e31', 0)
tx.addOutput('1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK', 15000)
tx.sign(0, keyPair)
txHEX = tx.build().toHex()
console.log(txHEX);

var tx = bitcoin.Transaction.fromHex(txHEX);
console.log(tx)
```

but if I using some exist TXhex from blockchain.info it can success broadcast.
I thought it's about the version?

**Comment by afk11** [comment]
That output was already spent in 2014:

https://btc.com/105eeeb9c448872c2257f93d5e2b14248c4a800cd69641911aa7e964cf570872#in_0

**Comment by EasonWang01** [comment]
It just an key from other example.
If it already spend it will says already spend not response code:-25.
Because 6 month ago I was doing the same thing,it wil response `already spend` message to me.
But now only give some exception.I also notice new TXhex now have more bytes in hex,guess it was cause by node version?

**Comment by EasonWang01** [comment]
You can also using the example from your bitcoinjs website.

```js
var bitcoin = require('bitcoinjs-lib')
var keyPair = bitcoin.ECPair.fromWIF('L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF2BRUVwy')
var tx = new bitcoin.TransactionBuilder()

var tx = new bitcoin.TransactionBuilder()

// Add the input (who is paying):
// [previous transaction hash, index of the output to use]
var txId = 'aa94ab02c182214f090e99a0d57021caffd0f195a81c24602b1028b130b63e31'
tx.addInput(txId, 0)

// Add the output (who to pay to):
// [payee's address, amount in satoshis]
tx.addOutput("1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK", 15000)

// Initialize a private key using WIF
var privateKeyWIF = 'L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF2BRUVwy'
var keyPair = bitcoin.ECPair.fromWIF(privateKeyWIF)

// Sign the first input with the new key
tx.sign(0, keyPair)

// Print transaction serialized as hex
console.log(tx.build().toHex())
```
then broadcast using https://blockchain.info/pushtx or bitpay,tou will see the error

**Comment by dcousens** [comment]
@EasonWang01 can you post the `txHex` that you have,  so we can compare?

**Comment by EasonWang01** [comment]
```
0100000001313eb630b128102b60241ca895f1d0ffca2170d5a0990e094f2182c102ab94aa000000006b483045022100aefbcf847900b01dd3e3debe054d3b6d03d715d50aea8525f5ea3396f168a1fb022013d181d05b15b90111808b22ef4f9ebe701caf2ab48db269691fdf4e9048f4f60121029f50f51d63b345039a290c94bffd3180c99ed659ff6ea6b1242bca47eb93b59fffffffff01983a0000000000001976a914ad618cf4333b3b248f9744e8e81db2964d0ae39788ac00000000
```

https://blockchain.info/pushtx will cause error.

**Comment by dcousens** [comment]
I get `Missing inputs` as the `Error` from `bitcoind`.

The inputs aren't in the UTXO,  so it makes sense as an Error.

Maybe your previous Error was using a different setup and they therefor had more information?
I don't think this is an unexpected result.

**Comment by EasonWang01** [comment]
I found the error only happened when using blockchain.info,so not related to bitcoinjs lib.

**Comment by lubana89** [comment]
i am getting same, how i can transfer? help
