### ISSUE TITLE
Implementing bitcoin gold (BTG) signing

### ISSUE THREAD

**Issue by Melvillian** [bitcoinjs/bitcoinjs-lib#939]
Is anyone planning or in the process of implementing transaction signing for bitcoin gold? If so please let me know here and I can help, otherwise I'll look into implementing it myself and maintain a branch.

**Comment by dcousens** [comment]
@Melvillian please see https://github.com/bitcoinjs/bitcoinjs-lib/pull/937 - which recently merged https://github.com/bitcoinjs/bitcoinjs-lib/pull/933 which added "Bitcoin Gold" support,  AFAIK.

Closing in favour of #937.
