### ISSUE TITLE
Can't resolve all parameters for ECPair: (?, ?, ?)

### ISSUE THREAD

**Issue by chiemekailo** [bitcoinjs/bitcoinjs-lib#946]
I am new to Ionic/Angular programming and designs (used to design iOS apps). I have the following problem with the bitcoinjs-lib:

I try to implement bitcoinjs-lib in a new angular 4.x app. What i did :

```
npm install bitcoinjs-lib --save
npm install @types/bitcoinjs-lib --save
```

My app.module.ts :

```
import { ECPair, HDNode, Transaction } from 'bitcoinjs-lib'

@NgModule({
  ...
  providers: [
    ...
    ECPair,
    HDNode,
    Transaction
  ]
})
```

It fails to Compile in my browser :

```
Uncaught Error: Can't resolve all parameters for ECPair: (?, ?, ?).
    at syntaxError (compiler.js:466)
```

This question has been asked on https://stackoverflow.com/questions/47231555/cant-resolve-all-parameters-for-ecpair, but the selected correct answer which was...

> You have to provide it properly. In your @NgModule you should use something like this:
> 
```
@NgModule({
  ...
  providers: [
    ...
    { ECPair, useFactory:()=>new ECPair(d,Q,options) }
  ]
})
```
> Specify appropriate arguments for d Q and options.

...didn't teach on how to appropriately specify the 'd', 'Q' and 'options' arguments for the app.module.ts file. 
Please, what do I do?

**Comment by dcousens** [comment]
I don't know Angular/Ionic,  so I can't help you here.  Maybe someone else is around who could help?

**Comment by dcousens** [comment]
@chiemekailo if you can resolve this,  please reply back for others.  But I don't think this is an issue related to `bitcoinjs-lib` specifically.

**Comment by sushrest** [comment]
Hi @chiemekailo, This may be very old issue for you.. if could recall could u pls share how you got around fixing this issue?
