### ISSUE TITLE
How many kinds of wallet that BitcoinJS lib support

### ISSUE THREAD

**Issue by tuyennvtb** [bitcoinjs/bitcoinjs-lib#948]
Hi

I'm going to build a site to store Crypto Currency online, I reviewed all documentations regarding to this lib but can't see how many kind of wallets that this lib support.
Can any one tell me how many kind of wallet can i create by using this lib ?
thank you

**Comment by mjal** [comment]
Take a look at this source file [1], the wallet support bitcoin, bitcoin testnet and litecoin. But the format is straightforward and it should be easy to add other bitcoin-forked cryptocurrencies.
[1] https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/networks.js

**Comment by tuyennvtb** [comment]
I'll look into it
thank you @mjal

**Comment by dcousens** [comment]
@tuyennvtb I think the question is a bit open-ended.  It is akin to asking how many drinks can you make with water as the base ingredient?
I think the answer is,  as many as you can think of!

There is no reason you couldn't use this library for a consensus node,  so be it for you to write the necessary code.   It **is** used by many SPV wallets, and standard "web-wallets".

BIP32, BIP44, BIP49,  you name it.
It is up to you!
