### ISSUE TITLE
Support for the Lightning Network

### ISSUE THREAD

**Issue by rbndg** [bitcoinjs/bitcoinjs-lib#954]
Hello everyone.

With the release of the lightning network specs, how far are we from creating/closing channels, sending and receiving funds on the network and other features of the LN or are we already there?

Thank you

**Comment by dcousens** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/pull/944 is probably priority 1 to even start

**Comment by dcousens** [comment]
Additionally, work is being done by @junderw in https://github.com/bitcoinjs/bolt11

**Comment by dcousens** [comment]
This issue is quite general.  If there any features in specific to the LN that we want added,  let us prioritize them in their own issues.
