### ISSUE TITLE
Where i can found ... = require('dhttp/200') ... on node js on Windows ?

### ISSUE THREAD

**Issue by nanshakov** [bitcoinjs/bitcoinjs-lib#960]
I had an error: Cannot find module 'dhttp/200'. I dont understand, where i must get module. I try npm install 'dhttp/200', and google, but nothing.

**Comment by dabura667** [comment]
What version of node are you using?

node -v
npm -v

**Comment by dcousens** [comment]
@nanshakov `npm install dhttp`
