### ISSUE TITLE
WebCrypto support for storing mnemonic seed?

### ISSUE THREAD

**Issue by sondreb** [bitcoinjs/bitcoinjs-lib#961]
Are you considering support for WebCrypto for storing the mnemonic seed within the web browser? How about some guidelines to help developers understand the various ways to protect secrets in the browser? It might be beyond the scope of the library?

I have replicated the bip39.mnemonicToSeedHex method using crypto.subtle (supported in Chrome, FireFox and Safari) in TypeScript. The benefits from using the WebCrypto is that the key are stored more securely on the device.

The initial 12-word mnemonic can be stored "safely" and non-exportable, but as long as the HDNode class does not support WebCrypto, the crypto.subtle.deriveKey require a registration with the exportable key flag set to true. If support for WebCrypto existed in HDNode, it could be supplied an instance of the **CryptoKey** class, and rely on that to derive new keys.

While using the WebCrypto, there are two steps where the key can be persisted. The first step is simply storing the generated mnemonic in a manner that is not exportable. The second step includes the salt (password), which would be less secure as it has to be registered as exportable (cross-side scripting could retrieve it).

Example code in TypeScript/JavaScript:

```
import { HDNode } from 'bitcoinjs-lib';
const bip39 = require('bip39');

const stringToArrayBuffer = function (string) {
	const encoder = new TextEncoder('utf-8');
	return encoder.encode(string);
};

const arrayBufferToHexString = function (arrayBuffer) {
	const byteArray = new Uint8Array(arrayBuffer);
	let hexString = '';
	let nextHexByte;

	for (let i = 0; i < byteArray.byteLength; i++) {
		nextHexByte = byteArray[i].toString(16);
		if (nextHexByte.length < 2) {
			nextHexByte = '0' + nextHexByte;
		}
		hexString += nextHexByte;
	}
	return hexString;
};

const passphrase = 'My Pass Phrase';
const mnemonic = 'situate bid venue strategy chase bird split pact spatial romance mobile furnace';

const seed = bip39.mnemonicToSeedHex(mnemonic, passphrase); // undefined/null passphrase/password defaults to a salt value of 'mnemonic'.
const root1 = HDNode.fromSeedHex(seed);

const buffer = stringToArrayBuffer(mnemonic);
const bufferSalt = stringToArrayBuffer('mnemonic' + passphrase);

// This could be used with async/await pattern, to simplify the code.
window.crypto.subtle.importKey(
	'raw',
	buffer,
	{
		name: 'PBKDF2',
	},
	false,
	['deriveKey']
).then((importedKey) => {
	// importedKey can be stored to IndexedDB for persistence across browser sessions.
	// To improve security, only the imported key could be persisted and user would be required to enter the salt (password) on every restart.
	window.crypto.subtle.deriveKey(
		{
			'name': 'PBKDF2',
			salt: bufferSalt,
			iterations: 2048,
			hash: { name: 'SHA-512' },
		},
		importedKey,
		{
			name: 'HMAC',
			hash: 'SHA-512',
			length: 512
		},
		true,
		['sign']
	)
		.then(function (derivedKey) {
			// derivedKey can be stored to IndexedDB for persistance across browser sessions.
			// This is less secure, but more user friendly, not requiring user to supply their salt (password) on every use.
			window.crypto.subtle.exportKey('raw', derivedKey).then((exportedKey) => {
				const exportedKeyHex = arrayBufferToHexString(exportedKey); // seed == exportedKeyHex - both values should be same.
				const root2 = HDNode.fromSeedHex(exportedKeyHex);
			});

		});
});
```

**Comment by dcousens** [comment]
@sondreb BIP39 uses [`pbkdf2`](https://www.npmjs.com/package/pbkdf2),  which has support for the [`subtle` API](https://github.com/crypto-browserify/pbkdf2/blob/a0fcb18c3e42add5695724eb4cbb481cb2f3a48f/lib/async.js#L41).

Therefore,  if you use `browserify`,  you already have this support.

What you are really asking is about private key storage,  and,  honestly,  I don't think there is a single answer to this question,  and it is certainly out of scope.
Browsers are fickle things,  and complex,  but,  the risks can be mitigated,  controlled,  sometimes.

**Comment by sondreb** [comment]
BIP39 uses the synchronous method, which doesn't use the subtle API, so no performance gains from native support in BIP39 lib. I see the async method of pbkdf2 uses deriveBits, not deriveKey, not sure if that makes any difference.

As more and more apps are built on the web, and I'm sure there are plenty of developers that is using bitcoinjs, it becomes important for easy and readily available documentation on keeping and storing secrets in the browser. I might write some content on this in the future, as I progress in my current project.

**Comment by dcousens** [comment]
@sondreb excellent point,  I realised that briefly after posting the above.
[I've changed the BIP39 `v3.0.0` API TODO](https://github.com/bitcoinjs/bip39/issues/48#issuecomment-352300519) list to include switching `mnemonicToSeed` to use the async variant to promote high performance usage.

**Comment by dcousens** [comment]
> As more and more apps are built on the web, and I'm sure there are plenty of developers that is using bitcoinjs, it becomes important for easy and readily available documentation on keeping and storing secrets in the browser. I might write some content on this in the future, as I progress in my current project.

@sondreb please do post a link or the contents back here if you do!  Sharing review and discussion on these techniques is sorely lacking at this time.
