### ISSUE TITLE
How do you make an address to receive bitcoin payments?

### ISSUE THREAD

**Issue by joonhocho** [bitcoinjs/bitcoinjs-lib#964]
I am new to crypto world as a developer.
I want to receive online payments with bitcoin.
I see that there are many functions available for creating address at disposal, but which one do you choose and how are they different?
It is a noob question, but which address type is the most standard?
It would be really great if there is a wiki explaining the differences.

Thank you in advance.

**Comment by ralphtheninja** [comment]
If you just want to generate a standard bitcoin address you can do:

```js
var keyPair = bitcoin.ECPair.makeRandom()
var address = keyPair.getAddress()
```

I'd start looking at SegWit addresses though, which should be cheaper to send coins to:

```js
var keyPair = bitcoin.ECPair.makeRandom()
var pubKey = keyPair.getPublicKeyBuffer()
var scriptPubKey = bitcoin.script.witnessPubKeyHash.output.encode(bitcoin.crypto.hash160(pubKey))
var address = bitcoin.address.fromOutputScript(scriptPubKey)
```

I got the code above from the examples in the test code.

@dcousens Does this look about right?

**Comment by dcousens** [comment]
@ralphtheninja spot on.
Both examples will hopefully be simpler soon.

**Comment by joonhocho** [comment]
@ralphtheninja Thank you very much! Why would anyone wants to create standard if SegWit is cheaper?

**Comment by dcousens** [comment]
@joonhocho compatability.  Old software/hardware.  Etc.

**Comment by joonhocho** [comment]
@dcousens I see. So if I create SegWit then there's a chance that someone may not be able to send to the address.

**Comment by dcousens** [comment]
@joonhocho yes,   but it should be miniscule.

The alternative is wrapping the above in a P2SH address,  but,  that is lame and complicates your spending code.

**Comment by joonhocho** [comment]
I heard Coinbase is not supporting SegWit yet, does that mean Coinbase users cannot send me coins if I create SegWit address?

**Comment by dcousens** [comment]
@joonhocho then you're best bet is a P2SH address wrapping P2WPKH.
See the example here: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/addresses.js#L60

**Comment by joonhocho** [comment]
@dcousens Thank you so much.
