### ISSUE TITLE
@Typing Address.fromOutputScript returns string not buffer

### ISSUE THREAD

**Issue by youssefgh** [bitcoinjs/bitcoinjs-lib#969]
This is only for reference
The fix for this issue is already included in a PR at #https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22461
Feel free to review the PR even though changes are very small
I will close once the PR is merged

**Comment by youssefgh** [comment]
PR changed to #https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22560

**Comment by dcousens** [comment]
Reviewed (and ACK'd) https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22560
