### ISSUE TITLE
BTC does not transfer

### ISSUE THREAD

**Issue by Bensigo** [bitcoinjs/bitcoinjs-lib#975]
my code run smooth without any error but the bitcoin does not transfer to toAddress . code 
```
     sendTestnetBTC (paperWallet, toAddress, amount, txID) {
        const address = bitcoin.ECPair.fromWIF(paperWallet.privateKey, bitcoin.networks.testnet)
        const txb = new bitcoin.TransactionBuilder(bitcoin.networks.testnet)
        txb.addInput(txID , 0) // previous transactionId from the address at index 0
        txb.addOutput(toAddress, amount) 
        txb.sign(0, address)
        txb.build().toHex() 
  }
```

**Comment by dabura667** [comment]
Did you broadcast the transaction?

**Comment by Bensigo** [comment]
I probably didn't do that. How do I do that?

**Comment by dabura667** [comment]
Before you do that, are you calculating fees properly?

**Comment by Bensigo** [comment]
This is all I wrote to make a transaction . Pls if any is missing an example would be better. thanks

**Comment by Bensigo** [comment]
How do I go about it ?

**Comment by Bensigo** [comment]
@dabura667 pls how do i go about solving the problem. if possible an example. thanks

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/issues/843
