### ISSUE TITLE
How to generate a SegWit address (via P2SH) on testnet or litecoin

### ISSUE THREAD

**Issue by jinglics** [bitcoinjs/bitcoinjs-lib#978]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/addresses.js#L61
I change keyPair network to bitcoin.networks.testnet, but the result is same as default, still bitcoin mainnet address.

**Comment by jinglics** [comment]
I add network in this function, the result is correct?
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/addresses.js#L66
var address = bitcoin.address.fromOutputScript(scriptPubKey, bitcoin.networks.testnet)

**Comment by junderw** [comment]
> I add network in this function, the result is correct?
> https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/addresses.js#L66
> var address = bitcoin.address.fromOutputScript(scriptPubKey, bitcoin.networks.testnet)

Yes this is correct.
