### ISSUE TITLE
update comment to say bech32 as well?

### ISSUE THREAD

**Issue by mandelmonkey** [bitcoinjs/bitcoinjs-lib#979]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/e0f24fdd46e11533a7140e02dc43b04a4cc4522e/src/transaction_builder.js#L607

this is pedantic I know lol but im using the library to walk my self through how segwit addresses and transactions are made 

I noticed on this line it says
>  // Attempt to get a script if it's a base58 address string

should it say?

>  // Attempt to get a script if it's a base58 or bech32 address string

**Comment by dabura667** [comment]
Thanks for the report!

Closing in favor of #980
