### ISSUE TITLE
Include a precompiled version?

### ISSUE THREAD

**Issue by rbndg** [bitcoinjs/bitcoinjs-lib#982]
Hey guys

I'm using bitcoinjs-lib in a create-react-app app.
Create-react-app is a boilerplate project that take cares of webpack/babel config. So the configurations are hidden from the developer and its maintained by the boilerplate code.

See issue here:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Unfortunately this means that bitcoinjs-lib isn't compatible Create-react-app (and other projects that hide webpack/babel)

Would it be possible to add a precompiled version to the npm package?

Thanks

**Comment by dabura667** [comment]
Did you reserve the terms in the README?
