### ISSUE TITLE
Key generated is incorrect according to http://bip32.org/

### ISSUE THREAD

**Issue by mmick66** [bitcoinjs/bitcoinjs-lib#983]
I am generating a key through:

```js
const bitcoin = require('bitcoinjs-lib');
const bip39 = require('bip39');
let mnemonic = 'maximum sun ticket prefer jelly coast galaxy crack column jewel cargo city';
let seed = bip39.mnemonicToSeed(mnemonic);
let master =bitcoin.HDNode.fromSeedBuffer(seed, bitcoin.networks['testnet']);
console.log(master.toBase58());
```

The key generated is not the same as http://bip32.org/

I get: `tprv8ZgxMBicQKsPf6dWVLADtEqGCtw8qHHrLGtaxKaXTfobA8XKQ88KQ5R93UvAvrJn7C9za9je9bieep96XvKQ4FgV7gQAvoTtpf2VQ5dQ8RX`

Should be: `tprv8ZgxMBicQKsPcvE69mqJ3kzpeEuWeepTayTrU1CCHnLrd8QdXv3nS7E3fXWBL5vBnLu4oSNsJCbVFPkyRRKsX1FwcR4Nv1u55KmQLjUdBiH`

**Comment by dabura667** [comment]
bip32.org does not support BIP39

**Comment by mmick66** [comment]
Ah! Thank you... I though 'passphrase' meant mnemonic, but it obviously does not.

**Comment by dabura667** [comment]
It’s all good.

**Comment by dcousens** [comment]
Duplicate of https://github.com/bitcoinjs/bip39/issues/64
