### ISSUE TITLE
moving bitcoins out of this bitcoinjs-lib address

### ISSUE THREAD

**Issue by dondre** [bitcoinjs/bitcoinjs-lib#984]
Trying to do this. Seems more difficult than it should. 
TransactionId required to make a transaction? This seems like the chicken before the egg. 
How can I find the TXID, I checked the documentation and it's just showing hard coded values. 

```js
let send = (wif, toAddress, amount, txID) => {
    const keyPair = bitcoin.ECPair.fromWIF(wif)
    const txb = new bitcoin.TransactionBuilder()
      txb.addInput(txID , 0) 
      txb.addOutput(toAddress, amount) 
      txb.sign(0, keyPair)
      txb.build().toHex()
}
```

Where can I find txID?

**Comment by junderw** [comment]
`https://testnet-api.smartbit.com.au/v1/blockchain/address/xxxxxxxxx/unspent?limit=1000`

Where xxxxxxxxx is the address you are sending FROM.

response.unspent will be an array of objects. Three attributes you want to look at are: txid, n, value_int

use txid and n to add the input. And after adding that input there will be value_int satoshis added to the transaction.

txb.addInput(txid , n)

You can not send more money in the Outputs than you add in the inputs.

Amount of Inputs - Amount of Outputs = Fee for miners.

Be sure to add change outputs to adjust your fees properly.

**Comment by dcousens** [comment]
@junderw could we improve the examples do you think?
