### ISSUE TITLE
 How can I broadcast a transaction? - // prepare for broadcast to the Bitcoin network, see "can broadcast a Transaction" below

### ISSUE THREAD

**Issue by byenic** [bitcoinjs/bitcoinjs-lib#986]
Thanks for everyone's contribution to this excellent project.
Forgive me to ask this stupid question! As the title, I can see the comment " // prepare for broadcast to the Bitcoin network, see "can broadcast a Transaction" below", however, I can't find the code sample about broadcasting the transaction out. How can I broadcast a transaction?

Thanks for the help.

**Comment by dcousens** [comment]
Closing as duplicate of https://github.com/bitcoinjs/bitcoinjs-lib/issues/839
