### ISSUE TITLE
How to Generate Altcoin Address using this awesome library (Qtum)

### ISSUE THREAD

**Issue by wannabit-jayb** [bitcoinjs/bitcoinjs-lib#988]
This might be too simple question to ask, but I can't figure out by myself. 

So, I decide to reach out for help. 

I am trying to use this bitcoinjs-lib to generate QTUM address.

Here is what I have done so far.

First, I tested private key and bitcoin address.

```
// Import bitcoinjs-lib
var bitcoin = require('bitcoinjs-lib')

var keyPair = bitcoin.ECPair.makeRandom()
var wif = keyPair.toWIF()
var BTCaddress = keyPair.getAddress()

console.log("\n")
console.log("BTC Private Key : " + wif);
console.log("BTC Address : " + BTCaddress);
console.log("\n")
```

From what I have been searching, it seems like i need to add this code inside 
the **bitcoinjs-lib/networks.js**

```
  qtum: {
    messagePrefix: '\x19Qtum Signed Message:\n',
    bip32: {
      public: 0x0488ade4,
      private: 0x0488b21e,
    },
    pubKeyHash: 0x3A,
    scriptHash: 0x32,
    wif: 0x80
  }
```

And I tried this code. 

```
//import bitcoinjs libs
var bitcoin = require('bitcoinjs-lib') // v2.x.x

var qtum = bitcoin.networks.qtum

var key = bitcoin.ECPair.makeRandom()
var wif = key.toWIF(qtum)
var QTUMaddress = key.getAddress(qtum).toString()

console.log("\n")
console.log("wif: " + wif)
console.log("QTUMaddress: " + QTUMaddress + "\n")
```

QTUM Address should start with 'Q' letter. But the returned address starts with '1' like bitcoin.

Anyone has any idea of what am I missing?

**Comment by liuhuanhui** [comment]
public: 0x0488ade4,
      private: 0x0488b21e,


Hello, how do public and private come from?

**Comment by junderw** [comment]
Google "bip32"
