### ISSUE TITLE
ScriptHash from bitcoin address

### ISSUE THREAD

**Issue by youssefgh** [bitcoinjs/bitcoinjs-lib#990]
How can i get the scripthash from the address ? as in the following example : 

```
{'priv': 'L8g5V8kFFeg2WbecahRSdobARbHz2w2STH9S8ePHVSY4fmia7Rsj',
        'pub': '03e9f948421aaa89415dc5f281a61b60dde12aae3181b3a76cd2d849b164fc6d0b',
        'address': 'bc1qqmpt7u5e9hfznljta5gnvhyvfd2kdd0r90hwue',
        'minikey': False,
        'txin_type': 'p2wpkh',
        'compressed': True,
        'addr_encoding': 'bech32',
        'scripthash': '1929acaaef3a208c715228e9f1ca0318e3a6b9394ab53c8d026137f847ecf97b'}
```

Sorry to bother you with opening an issue here as a question
The original question in stackexchange : [ScriptHash from bitcoin address with BitcoinJS](https://bitcoin.stackexchange.com/questions/68565/scripthash-from-bitcoin-address-with-bitcoinjs)

**Comment by dcousens** [comment]
> Sorry to bother you with opening an issue here as a question

Not a problem!
I don't have time to peruse the stackexchange for related Q&A; your issue here is useful to others,  so don't hesitate to open questions.

> How can i get the scripthash from the address ?

I think `electrum` uses a similar indexing scheme to https://github.com/bitcoinjs/indexd,  that is,  `SHA256(script)`.
If so,  then the following should be what you need:

``` js
let script = bitcoin.address.toOutputScript(address)
let hash = bitcoin.crypto.sha256(script)

console.log(address, ' maps to ', hash.toString('hex'))
```

**Comment by youssefgh** [comment]
Thanks a lot
Your example worked with just a small modification: 
`
let script = bitcoin.address.toOutputScript(address)
let hash = bitcoin.crypto.sha256(script)
let reversedHash = new Buffer(hash.reverse())
console.log(address, ' maps to ', reversedHash.toString('hex'))
`
No idea why Electrum uses the reverse of the hash and not the hash itself
Cheers

**Comment by junderw** [comment]
endianness and Bitcoin ftw

**Comment by dcousens** [comment]
@youssefgh you can do `hash.reverse().toString('hex')`

**Comment by YanDevDe** [comment]
And how can you do that in reverse order? I mean by converting from scripthash to public address?

**Comment by lukechilds** [comment]
@YanDevDe `bitcoin.address.fromOutputScript` requires an output script, you are passing it the hash of the output script.

**Comment by Adamb83** [comment]
I found this ScriptHash situation to be a pain in the butt after finally getting server working I almost re-indexed electrumx as I couldn't generate results from a reversed upside down inside out scripthash...

Anywho... Heres the python code to do it for you from a BTC wallet address.

#Pyhton code to convert BTC wallet address into Scripthash for Electrumx

import hashlib
import base58

def compute_scripthash(address):
    # Decode the address using Base58Check
    decoded = base58.b58decode_check(address)
    pubkeyhash = decoded[1:]  # Remove version byte

    # Build the P2PKH locking script
    script = b'\x76\xa9\x14' + pubkeyhash + b'\x88\xac'

    # Compute the SHA256 hash and reverse it
    sha256_hash = hashlib.sha256(script).digest()
    reversed_hash = sha256_hash[::-1]  # Reverse endianness

    return reversed_hash.hex()

# Example: Compute scripthash for my address
address = "1BmTcUnEFHZxupBQcHVJCUJ6hJBfQQtT57"  #My address, donations welcomed and encouraged
scripthash = compute_scripthash(address)
print("Scripthash:", scripthash)
