### ISSUE TITLE
Expected property "0" of type ECPair, got i

### ISSUE THREAD

**Issue by totaki** [bitcoinjs/bitcoinjs-lib#998]
I try use react application, on develop server all works fine, but when i build it i have a problem on step bitcoin.HDNode.seedFromBuffer

**Comment by totaki** [comment]
In debbuger i see network is undefined

**Comment by dabura667** [comment]
Read the readme.

You need to reserve keywords in uglify.

**Comment by totaki** [comment]
```uglifyjs ... --mangle reserved=['BigInteger','ECPair','Point']```

**Comment by dabura667** [comment]
Yes

**Comment by totaki** [comment]
I add to webpack UglifyJsPlugin this 
```
      mangle: {
        safari10: true,
          reserved: ["BigInteger","ECPair","Point"]
      }
```
not work :(

**Comment by dabura667** [comment]
Ask uglifyjsPlugin devs.

**Comment by dcousens** [comment]
@totaki the issue you present is that `ECPair` was mangled.  For better or worse,  that is the problem you need to solve.

In `4.0.0` we hope to minimalize these errors by removing the need to detect types via their constructor names.

**Comment by foloinfo** [comment]
For anyone facing same issue, it is a bug on uglifyjsPlugin.Adding line below to uglify option solved it.

```
mangle: {
  safari10: true,
  keep_fnames: true
}
```

**Comment by rhyek** [comment]
With Webpack 4 and Terser:
```
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          keep_fnames: true,
          safari10: true,
        },
      }),
    ],
  },
```
